/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.parser.sparql.manifest;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/** JSON optimizer round trips for the local and W3C SPARQL 1.1 corpora. */
class TupleExprJsonSPARQL11RoundTripComplianceTest extends AbstractTupleExprJsonRoundTripComplianceTest {

	static final int EXPECTED_LOCAL_MANIFEST_CASES = 118;
	static final int EXPECTED_LOCAL_CASES = 115;
	static final int EXPECTED_SYNTAX_ONLY_CASES = 3;
	static final int EXPECTED_W3C_CASES = 179;
	static final int EXPECTED_CASES = EXPECTED_LOCAL_CASES + EXPECTED_W3C_CASES;
	private static final Set<String> SYNTAX_ONLY_TESTS = Set.of(
			"sparql11-sequence-04", "sparql11-sequence-05", "sparql11-sequence-06");

	@TestFactory
	@Override
	public Collection<DynamicTest> tests() {
		Collection<DynamicTest> localManifest = getTestData("testcases-sparql-1.1/manifest-evaluation.ttl");
		Collection<DynamicTest> w3c = getTestData("testcases-sparql-1.1-w3c/manifest-all.ttl");
		assertEquals(EXPECTED_LOCAL_MANIFEST_CASES, localManifest.size(),
				"local SPARQL 1.1 manifest census changed");
		List<DynamicTest> local = localManifest.stream()
				.filter(test -> SYNTAX_ONLY_TESTS.stream()
						.noneMatch(syntaxOnlyTest -> test.getDisplayName().endsWith(syntaxOnlyTest)))
				.toList();
		assertEquals(EXPECTED_LOCAL_CASES, local.size(), "local SPARQL 1.1 corpus census changed");
		assertEquals(EXPECTED_W3C_CASES, w3c.size(), "W3C SPARQL 1.1 corpus census changed");

		List<DynamicTest> tests = new ArrayList<>(EXPECTED_CASES);
		tests.addAll(local);
		tests.addAll(w3c);
		assertEquals(EXPECTED_CASES, tests.size(), "combined SPARQL 1.1 corpus census changed");
		return tests;
	}
}
