/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.sketch;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.ListMemberOperator;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.BagEstimate;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class SketchBasedJoinEstimatorOmniSurfaceRetentionTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI TYPE = VF.createIRI("urn:omni-retention:type");
	private static final IRI ENTITY = VF.createIRI("urn:omni-retention:Entity");
	private static final IRI EDGE = VF.createIRI("urn:omni-retention:edge");
	private static final IRI EDGE_COPY = VF.createIRI("urn:omni-retention:edge-copy");
	private static final IRI FLAG = VF.createIRI("urn:omni-retention:flag");
	private static final IRI STATUS = VF.createIRI("urn:omni-retention:status");
	private static final IRI GRAPH = VF.createIRI("urn:omni-retention:graph");
	private static final Value ACTIVE = VF.createLiteral("active");
	private static final Value CLOSED = VF.createLiteral("closed");

	private final List<SketchBasedJoinEstimator> estimators = new ArrayList<>();
	private StubSketchStatementSource store;
	private SketchBasedJoinEstimator estimator;

	@BeforeEach
	void setUp() {
		store = new StubSketchStatementSource();
		for (int index = 0; index < 64; index++) {
			Resource root = VF.createIRI("urn:omni-retention:root:" + index);
			Resource middle = VF.createIRI("urn:omni-retention:middle:" + index);
			store.add(VF.createStatement(root, TYPE, ENTITY));
			store.add(VF.createStatement(root, EDGE, middle));
			store.add(VF.createStatement(root, EDGE_COPY, middle));
			store.add(VF.createStatement(middle, FLAG, index < 32 ? ACTIVE : CLOSED));
			store.add(VF.createStatement(root, STATUS, index < 16 ? CLOSED : ACTIVE));
		}
		estimator = track(new SketchBasedJoinEstimator(store, omniConfig()));
		estimator.rebuild();
	}

	@AfterEach
	void tearDown() {
		for (SketchBasedJoinEstimator current : estimators) {
			current.close();
		}
	}

	@Test
	void subjectStarAndBridgeChainRetainBindingsWitnessesAndSteps() {
		StatementPattern rootType = fixedObjectPattern("root", TYPE, ENTITY);
		StatementPattern rootStatus = fixedObjectPattern("root", STATUS, ACTIVE);
		StatementPattern rootEdge = pattern("root", EDGE, "middle");
		StatementPattern middleFlag = fixedObjectPattern("middle", FLAG, ACTIVE);

		OmniSketchSurfaceEstimate subjectStar = estimator.estimateSubjectStarOmniSurface(
				List.of(rootType, rootStatus), "root");
		OmniSketchSurfaceEstimate bridgeChain = estimator.estimateOmniBridgeChain(
				List.of(rootType, rootEdge, middleFlag), Set.of());

		assertCompleteSurface(subjectStar, "root", "subject-star");
		assertCompleteSurface(bridgeChain, "middle", "bridge-chain");
	}

	@Test
	void subjectStarDropsUnavailableContextDimensionWithoutDroppingOmniEvidence() {
		StubSketchStatementSource contextStore = new StubSketchStatementSource();
		for (int index = 0; index < 64; index++) {
			Resource root = VF.createIRI("urn:omni-retention:context-root:" + index);
			contextStore.add(VF.createStatement(root, TYPE, ENTITY, GRAPH));
			contextStore.add(VF.createStatement(root, STATUS, ACTIVE, GRAPH));
		}
		SketchBasedJoinEstimator contextEstimator = track(new SketchBasedJoinEstimator(contextStore,
				omniConfig().withoutContextPairSketches()));
		contextEstimator.rebuild();
		StatementPattern rootType = fixedObjectPattern("root", TYPE, ENTITY, GRAPH);
		StatementPattern rootStatus = fixedObjectPattern("root", STATUS, ACTIVE, GRAPH);

		OmniSketchSurfaceEstimate subjectStar = contextEstimator.estimateSubjectStarOmniSurface(
				List.of(rootType, rootStatus), "root");

		assertCompleteSurface(subjectStar, "root", "subject-star");
		assertEquals(64.0d, subjectStar.selectedRows(), 0.0d);
	}

	@Test
	void publicOneVariableObjectToSubjectJoinUsesOrderedOmniSurface() {
		StatementPattern rootEdge = pattern("root", EDGE, "middle");
		StatementPattern activeMiddle = fixedObjectPattern("middle", FLAG, ACTIVE);

		OmniSketchSurfaceEstimate surface = estimator.estimateOmniSurface(List.of(rootEdge, activeMiddle), "middle");

		assertCompleteSurface(surface, "middle", "ordered-connected");
	}

	@Test
	void tuplePlanCarriesOmniSurfaceIntoJoinOrderingCostBag() {
		StatementPattern rootEdge = pattern("root", EDGE, "middle");
		StatementPattern activeMiddle = fixedObjectPattern("middle", FLAG, ACTIVE);
		OmniSketchSurfaceEstimate surface = estimator.estimateOmniSurface(List.of(rootEdge, activeMiddle), "middle");
		OmniSketchSurfaceEstimate.CostInputs costInputs = surface.toCostInputs();

		BagEstimate bag = estimator.bagEstimateForJoinOrdering(new Join(rootEdge, activeMiddle), Set.of())
				.orElseThrow();

		assertEquals(costInputs.rows(), bag.rows(), 0.0d);
		assertEquals(costInputs.workRows(), bag.workRows(), 0.0d);
		assertEquals(costInputs.confidence(), bag.confidence(), 0.0d);
		assertEquals(surface.source(), bag.source());
		assertEquals(costInputs.rowQErrorMax(), bag.metrics().get("plannedCardinalityQError"), 0.0d);
		assertTrue(bag.variables().keySet().containsAll(Set.of("root", "middle")));
		for (OmniSketchBindingEvidence binding : surface.bindings().values()) {
			assertEquals(binding.distinctRows(), bag.variable(binding.bindingName()).distinctRows(), 0.0d);
		}
	}

	@Test
	void bridgeProbeEmbedsCompleteOmniSurface() {
		StatementPattern rootType = fixedObjectPattern("root", TYPE, ENTITY);
		StatementPattern rootEdge = pattern("root", EDGE, "middle");

		OmniBridgeProbeEstimate probe = estimator.estimateOmniBridgeProbe(List.of(rootType), rootEdge, 64.0d)
				.orElseThrow();

		assertCompleteSurface(probe.omniSurface(), "middle", "bridge-probe");
		assertEquals(probe.omniSurface().samplingProbability(), probe.samplingProbability(), 0.0d);
	}

	@Test
	void finiteFilterEmbedsCompleteOmniSurface() {
		StatementPattern rootStatus = pattern("root", STATUS, "status");
		ListMemberOperator condition = new ListMemberOperator();
		condition.addArgument(new Var("status"));
		condition.addArgument(new ValueConstant(ACTIVE));

		OmniFiniteFilterProbeEstimate probe = estimator.estimateOmniFiniteFilterProbe(rootStatus, condition, 64.0d)
				.orElseThrow();

		assertCompleteSurface(probe.omniSurface(), "root", "finite-filter-probe");
		assertEquals(probe.omniSurface().samplingProbability(), probe.samplingProbability(), 0.0d);
	}

	@Test
	void correlatedSemiAndAntiProbesEmbedCompleteOmniSurfaces() {
		StatementPattern rootType = fixedObjectPattern("root", TYPE, ENTITY);
		StatementPattern closedStatus = fixedObjectPattern("root", STATUS, CLOSED);

		OmniCorrelatedProbeEstimate semi = estimator
				.estimateOmniCorrelatedSemiProbe(rootType, closedStatus, Set.of("root"), 64.0d)
				.orElseThrow();
		OmniCorrelatedProbeEstimate anti = estimator
				.estimateOmniCorrelatedAntiProbe(rootType, closedStatus, Set.of("root"), 64.0d)
				.orElseThrow();

		assertCompleteSurface(semi.omniSurface(), "root", "correlated-semi-probe");
		assertCompleteSurface(anti.omniSurface(), "root", "correlated-anti-probe");
		assertEquals(semi.omniSurface().samplingProbability(), semi.samplingProbability(), 0.0d);
		assertEquals(anti.omniSurface().samplingProbability(), anti.samplingProbability(), 0.0d);
	}

	@Test
	void correlatedSemiAndAntiSupportObjectToSubjectTraversal() {
		StatementPattern rootEdge = pattern("root", EDGE, "middle");
		StatementPattern activeMiddle = fixedObjectPattern("middle", FLAG, ACTIVE);

		OmniCorrelatedProbeEstimate semi = estimator
				.estimateOmniCorrelatedSemiProbe(rootEdge, activeMiddle, Set.of("middle"), 64.0d)
				.orElseThrow();
		OmniCorrelatedProbeEstimate anti = estimator
				.estimateOmniCorrelatedAntiProbe(rootEdge, activeMiddle, Set.of("middle"), 64.0d)
				.orElseThrow();

		assertCompleteSurface(semi.omniSurface(), "middle", "correlated-semi-probe");
		assertCompleteSurface(anti.omniSurface(), "middle", "correlated-anti-probe");
		assertEquals(32.0d, semi.outputRows(), 0.0d);
		assertEquals(32.0d, anti.outputRows(), 0.0d);
	}

	@Test
	void correlatedSemiSupportsTwoBindingTupleWitnesses() {
		StatementPattern rootEdge = pattern("root", EDGE, "middle");
		StatementPattern copiedEdge = pattern("root", EDGE_COPY, "middle");

		OmniCorrelatedProbeEstimate semi = estimator
				.estimateOmniCorrelatedSemiProbe(rootEdge, copiedEdge, Set.of("root", "middle"), 64.0d)
				.orElseThrow();

		assertCompleteSurface(semi.omniSurface(), "root", "correlated-semi-probe");
		assertCompleteSurface(semi.omniSurface(), "middle", "correlated-semi-probe");
		assertEquals(2, semi.keyWidth());
		assertEquals(64.0d, semi.outputRows(), 0.0d);
	}

	private static void assertCompleteSurface(OmniSketchSurfaceEstimate surface, String bindingName,
			String surfaceKind) {
		assertNotNull(surface);
		assertTrue(surface.bindings().containsKey(bindingName), () -> "missing binding evidence: " + surface);
		assertNotNull(surface.bindings().get(bindingName).witnesses());
		assertTrue(surface.bindings().get(bindingName).witnessCount() > 0);
		assertFalse(surface.steps().isEmpty(), () -> "missing step evidence: " + surface);
		assertTrue(surface.steps().stream().anyMatch(step -> surfaceKind.equals(step.operatorKind())),
				() -> "missing " + surfaceKind + " step: " + surface.steps());
	}

	private SketchBasedJoinEstimator track(SketchBasedJoinEstimator current) {
		estimators.add(current);
		return current;
	}

	private static StatementPattern pattern(String subjectName, IRI predicate, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var("predicate", predicate), new Var(objectName));
	}

	private static StatementPattern fixedObjectPattern(String subjectName, IRI predicate, Value object) {
		return new StatementPattern(new Var(subjectName), new Var("predicate", predicate), new Var("object", object));
	}

	private static StatementPattern fixedObjectPattern(String subjectName, IRI predicate, Value object,
			Resource context) {
		return new StatementPattern(new Var(subjectName), new Var("predicate", predicate), new Var("object", object),
				new Var("context", context));
	}

	private static SketchBasedJoinEstimator.Config omniConfig() {
		return SketchBasedJoinEstimator.Config.defaults()
				.withSketchStrategy(SketchBasedJoinEstimator.SketchStrategy.OMNI)
				.withNominalEntries(4096)
				.withSubjectBucketCount(4096)
				.withPredicateBucketCount(64)
				.withObjectBucketCount(4096)
				.withContextBucketCount(16)
				.withEstimateCacheSeconds(0)
				.withThrottleEveryN(1)
				.withThrottleMillis(0)
				.withRefreshSleepMillis(5);
	}
}
