/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

/// <reference lib="es2015.promise" />

interface QueryRowStoreMessage {
    requestId: number;
    op: 'create' | 'append' | 'read' | 'count' | 'dispose';
    storeId?: string;
    rows?: any[][];
    start?: number;
    count?: number;
}

interface QueryRowStoreResponse {
    requestId: number;
    ok: boolean;
    storeId?: string;
    rows?: any[][];
    count?: number;
    disposed?: boolean;
    error?: string;
}

interface QueryRowStoreDatabase extends IDBDatabase {
}

var queryRowStoreScope: any = typeof self !== 'undefined' ? self : null;
var queryRowStoreQueue: Promise<void> = Promise.resolve();
var queryRowStoreDatabasePromise: Promise<QueryRowStoreDatabase> = null;

function queryRowStoreDatabase(): Promise<QueryRowStoreDatabase> {
    if (queryRowStoreDatabasePromise) {
        return queryRowStoreDatabasePromise;
    }
    if (!queryRowStoreScope || !queryRowStoreScope.indexedDB) {
        return Promise.reject(new Error('IndexedDB is unavailable for Workbench query results.'));
    }

    queryRowStoreDatabasePromise = new Promise((resolve, reject) => {
        var request = queryRowStoreScope.indexedDB.open('rdf4j-workbench-query-results', 1);
        request.onupgradeneeded = function() {
            var database = request.result;
            if (!database.objectStoreNames.contains('stores')) {
                database.createObjectStore('stores', { keyPath: 'id' });
            }
            if (!database.objectStoreNames.contains('rows')) {
                database.createObjectStore('rows', { keyPath: ['storeId', 'index'] });
            }
        };
        request.onsuccess = function() {
            var database = <QueryRowStoreDatabase>request.result;
            database.onversionchange = function() {
                database.close();
                queryRowStoreDatabasePromise = null;
            };
            resolve(database);
        };
        request.onerror = function() {
            queryRowStoreDatabasePromise = null;
            reject(request.error || new Error('Unable to open Workbench query result storage.'));
        };
        request.onblocked = function() {
            queryRowStoreDatabasePromise = null;
            reject(new Error('Workbench query result storage is blocked by another tab.'));
        };
    });
    return queryRowStoreDatabasePromise;
}

function queryRowStoreError(error: any): string {
    return error && (error.name || error.message) ? String(error.name || error.message) : String(error);
}

function queryRowStoreRun(message: QueryRowStoreMessage): Promise<QueryRowStoreResponse> {
    if (!message || !isFinite(message.requestId) || Math.floor(message.requestId) !== message.requestId) {
        return Promise.reject(new Error('Invalid query row-store request.'));
    }
    return queryRowStoreDatabase().then(database => {
        if (message.op === 'create') {
            var storeId = 'rows-' + Date.now().toString(36) + '-' + Math.random().toString(36).substring(2);
            return new Promise<QueryRowStoreResponse>((resolve, reject) => {
                var transaction = database.transaction(['stores'], 'readwrite');
                transaction.objectStore('stores').add({ id: storeId, count: 0 });
                transaction.oncomplete = function() {
                    resolve({ requestId: message.requestId, ok: true, storeId: storeId, count: 0 });
                };
                transaction.onerror = function() {
                    reject(transaction.error || new Error('Unable to create query result storage.'));
                };
                transaction.onabort = function() {
                    reject(transaction.error || new Error('Unable to create query result storage.'));
                };
            });
        }

        if (!message.storeId) {
            return Promise.reject(new Error('A row-store id is required.'));
        }

        if (message.op === 'append') {
            if (!Array.isArray(message.rows)) {
                return Promise.reject(new Error('A row batch is required.'));
            }
            return new Promise<QueryRowStoreResponse>((resolve, reject) => {
                var transaction = database.transaction(['stores', 'rows'], 'readwrite');
                var stores = transaction.objectStore('stores');
                var rows = transaction.objectStore('rows');
                var storeRequest = stores.get(message.storeId);
                var nextCount: number;
                storeRequest.onsuccess = function() {
                    var store = storeRequest.result;
                    if (!store) {
                        transaction.abort();
                        return;
                    }
                    nextCount = store.count + message.rows.length;
                    for (var index = 0; index < message.rows.length; index++) {
                        rows.add({ storeId: message.storeId, index: store.count + index, values: message.rows[index] });
                    }
                    store.count = nextCount;
                    stores.put(store);
                };
                transaction.oncomplete = function() {
                    resolve({ requestId: message.requestId, ok: true, storeId: message.storeId, count: nextCount });
                };
                transaction.onerror = function() {
                    reject(transaction.error || storeRequest.error || new Error('Unable to append query result rows.'));
                };
                transaction.onabort = function() {
                    reject(transaction.error || storeRequest.error || new Error('Unable to append query result rows.'));
                };
            });
        }

        if (message.op === 'read') {
            var start = Math.max(0, Math.floor(Number(message.start) || 0));
            var count = Math.max(0, Math.floor(Number(message.count) || 0));
            return new Promise<QueryRowStoreResponse>((resolve, reject) => {
                if (count === 0) {
                    resolve({ requestId: message.requestId, ok: true, storeId: message.storeId, rows: [] });
                    return;
                }
                var transaction = database.transaction(['rows'], 'readonly');
                var objectStore = transaction.objectStore('rows');
                var range = queryRowStoreScope.IDBKeyRange.bound(
                    [message.storeId, start], [message.storeId, start + count - 1]);
                var request = objectStore.openCursor(range);
                var values: any[][] = [];
                request.onsuccess = function() {
                    var cursor = request.result;
                    if (!cursor) {
                        return;
                    }
                    values.push(cursor.value.values);
                    cursor.continue();
                };
                transaction.oncomplete = function() {
                    resolve({ requestId: message.requestId, ok: true, storeId: message.storeId, rows: values });
                };
                transaction.onerror = function() {
                    reject(transaction.error || request.error || new Error('Unable to read query result rows.'));
                };
                transaction.onabort = function() {
                    reject(transaction.error || request.error || new Error('Unable to read query result rows.'));
                };
            });
        }

        if (message.op === 'count') {
            return new Promise<QueryRowStoreResponse>((resolve, reject) => {
                var transaction = database.transaction(['stores'], 'readonly');
                var request = transaction.objectStore('stores').get(message.storeId);
                var count = 0;
                request.onsuccess = function() {
                    if (!request.result) {
                        transaction.abort();
                        return;
                    }
                    count = request.result.count;
                };
                transaction.oncomplete = function() {
                    resolve({ requestId: message.requestId, ok: true, storeId: message.storeId, count: count });
                };
                transaction.onerror = function() {
                    reject(transaction.error || request.error || new Error('Unable to count query result rows.'));
                };
                transaction.onabort = function() {
                    reject(transaction.error || request.error || new Error('Unable to count query result rows.'));
                };
            });
        }

        if (message.op === 'dispose') {
            return new Promise<QueryRowStoreResponse>((resolve, reject) => {
                var transaction = database.transaction(['stores', 'rows'], 'readwrite');
                transaction.objectStore('stores').delete(message.storeId);
                var range = queryRowStoreScope.IDBKeyRange.bound(
                    [message.storeId, 0], [message.storeId, 9007199254740991]);
                var request = transaction.objectStore('rows').openCursor(range);
                request.onsuccess = function() {
                    var cursor = request.result;
                    if (cursor) {
                        cursor.delete();
                        cursor.continue();
                    }
                };
                transaction.oncomplete = function() {
                    resolve({ requestId: message.requestId, ok: true, storeId: message.storeId, disposed: true });
                };
                transaction.onerror = function() {
                    reject(transaction.error || request.error || new Error('Unable to dispose query result rows.'));
                };
                transaction.onabort = function() {
                    reject(transaction.error || request.error || new Error('Unable to dispose query result rows.'));
                };
            });
        }

        return Promise.reject(new Error('Unsupported query row-store operation.'));
    });
}

if (queryRowStoreScope && typeof queryRowStoreScope.addEventListener === 'function') {
    queryRowStoreScope.addEventListener('message', function(event: MessageEvent) {
        var message = <QueryRowStoreMessage>event.data;
        queryRowStoreQueue = queryRowStoreQueue.then(() => queryRowStoreRun(message))
            .then(response => queryRowStoreScope.postMessage(response), error => {
                var response: QueryRowStoreResponse = {
                    requestId: message && message.requestId,
                    ok: false,
                    error: queryRowStoreError(error)
                };
                queryRowStoreScope.postMessage(response);
            });
    });
}
