/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

/** Reference-counted set of already validated and mapped mandatory query shards. */
final class FrontierStatisticsGeneration {

	private static final long BASE_METADATA_BYTES = 64L * 1024L;
	private static final long GENERATION_METADATA_BYTES_PER_SHARD = 4L * 1024L;
	private static final long SHARED_SHARD_METADATA_BYTES = 252L * 1024L;
	private static final long LOGICAL_METADATA_BYTES_PER_SHARD = GENERATION_METADATA_BYTES_PER_SHARD
			+ SHARED_SHARD_METADATA_BYTES;
	private static final long MAXIMUM_MAPPED_METADATA_BYTES = 256L * 1024L * 1024L;

	private final FrontierStatisticsManifest manifest;
	private final Map<Integer, FrontierStatisticsShard> shards;
	private final Map<Integer, SharedShard> sharedShards;
	private final Map<FrontierStatisticsTier, Long> diskBytesByTier;
	private final List<String> optionalFailures;
	private final FrontierStatisticsHeapGovernor.Lease metadataLease;
	private final FrontierMappedStatistics mappedStatistics;
	private final AtomicInteger references = new AtomicInteger(1);

	private FrontierStatisticsGeneration(FrontierStatisticsManifest manifest,
			Map<Integer, FrontierStatisticsShard> shards,
			Map<Integer, SharedShard> sharedShards,
			Map<FrontierStatisticsTier, Long> diskBytesByTier,
			List<String> optionalFailures,
			FrontierStatisticsHeapGovernor.Lease metadataLease) throws IOException {
		this.manifest = manifest;
		this.shards = Map.copyOf(shards);
		this.sharedShards = Map.copyOf(sharedShards);
		this.diskBytesByTier = Map.copyOf(diskBytesByTier);
		this.optionalFailures = List.copyOf(optionalFailures);
		this.metadataLease = metadataLease;
		mappedStatistics = new FrontierMappedStatistics(manifest, this.shards);
	}

	static FrontierStatisticsGeneration open(FrontierStatisticsManifestStore store,
			FrontierStatisticsManifest manifest, FrontierFileOps fileOps,
			FrontierStatisticsHeapGovernor governor) throws IOException {
		return open(store, manifest, fileOps, governor, null);
	}

	static FrontierStatisticsGeneration open(FrontierStatisticsManifestStore store,
			FrontierStatisticsManifest manifest, FrontierFileOps fileOps,
			FrontierStatisticsHeapGovernor governor, FrontierStatisticsGeneration reusable) throws IOException {
		requireQueryableCore(manifest);
		long logicalMetadataBytes;
		long generationMetadataBytes;
		try {
			logicalMetadataBytes = Math.addExact(BASE_METADATA_BYTES,
					Math.multiplyExact((long) manifest.shards().size(), LOGICAL_METADATA_BYTES_PER_SHARD));
			generationMetadataBytes = Math.addExact(BASE_METADATA_BYTES,
					Math.multiplyExact((long) manifest.shards().size(), GENERATION_METADATA_BYTES_PER_SHARD));
		} catch (ArithmeticException overflow) {
			throw new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
					"Frontier statistics mapped metadata size overflow", overflow);
		}
		if (logicalMetadataBytes > MAXIMUM_MAPPED_METADATA_BYTES) {
			throw new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
					"Frontier statistics generation exceeds the 256 MiB mapped-metadata envelope");
		}
		FrontierStatisticsHeapGovernor.Lease metadataLease = governor.tryAcquire(
				FrontierStatisticsMemoryPurpose.MAPPED_METADATA, generationMetadataBytes);
		if (metadataLease == null) {
			throw new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
					"Frontier statistics mapped metadata lease was refused");
		}

		HashMap<Integer, FrontierStatisticsShard> shards = new HashMap<>();
		HashMap<Integer, SharedShard> sharedShards = new HashMap<>();
		EnumMap<FrontierStatisticsTier, Long> diskBytes = new EnumMap<>(FrontierStatisticsTier.class);
		ArrayList<String> optionalFailures = new ArrayList<>();
		try {
			for (FrontierStatisticsShardDescriptor descriptor : manifest.shards()) {
				if (sharedShards.containsKey(descriptor.shardId())) {
					throw new FrontierStatisticsException(FrontierFallbackReason.SHARD_CORRUPT,
							"Frontier generation contains duplicate shard IDs");
				}
				Path path = store.shardPath(descriptor);
				SharedShard sharedShard = null;
				try {
					if (!fileOps.exists(path)) {
						throw new IOException("shard is missing: " + descriptor.fileName());
					}
					long actualLength = fileOps.size(path);
					if (actualLength != descriptor.byteLength()) {
						throw new IOException("shard length mismatch for " + descriptor.fileName()
								+ ": expected " + descriptor.byteLength() + " but found " + actualLength);
					}
					sharedShard = reusable == null
							? null
							: reusable.retainSharedShard(descriptor, manifest.generationId());
					if (sharedShard == null) {
						sharedShard = SharedShard.open(path, descriptor, manifest.generationId(), governor);
					}
					FrontierStatisticsShard shard = sharedShard.shard();
					validateShard(manifest, descriptor, shard);
				} catch (IOException | RuntimeException failure) {
					if (sharedShard != null) {
						sharedShard.release(failure);
					}
					if (descriptor.mandatory()) {
						throw new FrontierStatisticsException(FrontierFallbackReason.SHARD_CORRUPT,
								"Mandatory Frontier statistics shard is unavailable: " + descriptor.fileName(),
								failure);
					}
					optionalFailures.add(descriptor.fileName() + ": " + failure.getMessage());
					continue;
				}
				FrontierStatisticsShard shard = sharedShard.shard();
				sharedShards.put(descriptor.shardId(), sharedShard);
				shards.put(descriptor.shardId(), shard);
				diskBytes.merge(descriptor.tier(), descriptor.byteLength(), Math::addExact);
			}
			return new FrontierStatisticsGeneration(
					manifest, shards, sharedShards, diskBytes, optionalFailures, metadataLease);
		} catch (IOException | RuntimeException failure) {
			releaseSharedShards(sharedShards.values(), failure);
			metadataLease.close();
			throw failure;
		}
	}

	private SharedShard retainSharedShard(FrontierStatisticsShardDescriptor descriptor, long manifestGenerationId) {
		SharedShard sharedShard = sharedShards.get(descriptor.shardId());
		return sharedShard != null && sharedShard.matches(descriptor, manifestGenerationId) && sharedShard.retain()
				? sharedShard
				: null;
	}

	private static void requireQueryableCore(FrontierStatisticsManifest manifest) throws IOException {
		if (manifest.formatRevision() != 0
				&& manifest.formatRevision() != FrontierStatisticsManifest.CURRENT_FORMAT_REVISION
				|| manifest.hashSchemaId() != FrontierStatisticsHash.HASH_SCHEMA_ID
				|| manifest.bucketSchemaId() != FrontierStatisticsHash.BUCKET_SCHEMA_ID
				|| manifest.tupleOrdinalWidth() != FrontierStatisticsManifest.TUPLE_ORDINAL_WIDTH) {
			throw new FrontierStatisticsException(FrontierFallbackReason.SHARD_CORRUPT,
					"Frontier statistics generation uses an incompatible persisted algorithm identity");
		}
		EnumSet<FrontierStatisticsCapability> missing = EnumSet.copyOf(FrontierStatisticsCapability.queryCore());
		for (FrontierStatisticsShardDescriptor descriptor : manifest.shards()) {
			if (!descriptor.mandatory()) {
				continue;
			}
			for (FrontierStatisticsCapability capability : FrontierStatisticsCapability.queryCore()) {
				if ((manifest.capabilityMask() & capability.bit()) != 0L
						&& descriptor.kind() == capability.shardKind()) {
					missing.remove(capability);
				}
			}
		}
		if (!missing.isEmpty()) {
			throw new FrontierStatisticsException(FrontierFallbackReason.SHARD_CORRUPT,
					"Frontier statistics generation is missing mandatory query capabilities: " + missing);
		}
		FrontierStatisticsShardDescriptor directory = manifest.shards()
				.stream()
				.filter(FrontierStatisticsShardDescriptor::mandatory)
				.filter(descriptor -> descriptor.kind() == FrontierStatisticsShardKind.OMNI_CELL_DIRECTORY)
				.findFirst()
				.orElseThrow();
		FrontierOmniLayout layout = FrontierOmniLayout.fromDirectory(directory);
		if (layout.depth() != manifest.depth() || layout.width() != manifest.width()
				|| layout.designLanes() != manifest.designLaneCount()
				|| layout.auditLanes() != manifest.auditLaneCount()) {
			throw new FrontierStatisticsException(FrontierFallbackReason.SHARD_CORRUPT,
					"Frontier statistics manifest and Omni directory dimensions disagree");
		}
	}

	private static void validateShard(FrontierStatisticsManifest manifest,
			FrontierStatisticsShardDescriptor descriptor, FrontierStatisticsShard shard) throws IOException {
		long ownerGenerationId = descriptor.resolvedOwnerGenerationId(manifest.generationId());
		boolean reusedLayer = ownerGenerationId != manifest.generationId();
		if (manifest.formatRevision() != 0 && shard.formatVersion() != manifest.formatRevision()
				|| shard.generationId() != ownerGenerationId
				|| shard.shardId() != descriptor.shardId()
				|| shard.snapshotEpoch() < manifest.baseEpoch() || shard.snapshotEpoch() > manifest.coveredEpoch()
				|| reusedLayer && shard.maximumTermId() > manifest.maximumTermId()
				|| !reusedLayer && shard.maximumTermId() != manifest.maximumTermId()
				|| shard.rowCount() != descriptor.rowCount()
				|| shard.fileLength() != descriptor.byteLength()) {
			shard.close();
			throw new IOException("Frontier statistics shard identity does not match its manifest");
		}
	}

	FrontierStatisticsManifest manifest() {
		return manifest;
	}

	FrontierStatisticsShard shard(int shardId) {
		FrontierStatisticsShard shard = shards.get(shardId);
		if (shard == null) {
			throw new IllegalArgumentException("Frontier statistics generation has no mapped shard " + shardId);
		}
		return shard;
	}

	Map<Integer, FrontierStatisticsShard> shards() {
		return shards;
	}

	Map<FrontierStatisticsTier, Long> diskBytesByTier() {
		return diskBytesByTier;
	}

	List<String> optionalFailures() {
		return optionalFailures;
	}

	FrontierLeafEstimate estimateLeaf(FrontierLeafProbe probe, FrontierOmniIndex.Scratch scratch)
			throws IOException {
		return mappedStatistics.estimateLeaf(probe, scratch);
	}

	double estimateProjectedDistinct(FrontierLeafProbe probe, int component, FrontierOmniIndex.Scratch scratch)
			throws IOException {
		return mappedStatistics.estimateProjectedDistinct(probe, component, scratch);
	}

	FrontierJoinEstimate estimateJoin(FrontierJoinProbe probe, FrontierOmniIndex.Scratch scratch)
			throws IOException {
		return mappedStatistics.estimateJoin(probe, scratch);
	}

	FrontierJoinEstimate estimateConditionalJoin(FrontierJoinProbe probe, double upperRowsPerLeft,
			FrontierOmniIndex.Scratch scratch) throws IOException {
		return mappedStatistics.estimateConditionalJoin(probe, upperRowsPerLeft, scratch);
	}

	FrontierJoinEstimate estimateSubgraph(FrontierJoinProgram program, FrontierOmniIndex.Scratch scratch)
			throws IOException {
		return mappedStatistics.estimateSubgraph(program, scratch);
	}

	double deleteDebt() {
		return mappedStatistics.deleteDebt();
	}

	boolean retain() {
		int observed = references.get();
		while (observed != 0) {
			if (references.compareAndSet(observed, observed + 1)) {
				return true;
			}
			observed = references.get();
		}
		return false;
	}

	void release() {
		int remaining = references.decrementAndGet();
		if (remaining < 0) {
			throw new IllegalStateException("Frontier statistics generation reference count underflow");
		}
		if (remaining == 0) {
			releaseSharedShards(sharedShards.values(), null);
			metadataLease.close();
		}
	}

	private static void releaseSharedShards(Iterable<SharedShard> shards, Throwable primary) {
		for (SharedShard shard : shards) {
			shard.release(primary);
		}
	}

	private static final class SharedShard {

		private final FrontierStatisticsShardDescriptor identity;
		private final FrontierStatisticsShard shard;
		private final FrontierStatisticsHeapGovernor.Lease metadataLease;
		private final AtomicInteger references = new AtomicInteger(1);

		private SharedShard(FrontierStatisticsShardDescriptor identity, FrontierStatisticsShard shard,
				FrontierStatisticsHeapGovernor.Lease metadataLease) {
			this.identity = identity;
			this.shard = shard;
			this.metadataLease = metadataLease;
		}

		private static SharedShard open(Path path, FrontierStatisticsShardDescriptor descriptor,
				long manifestGenerationId, FrontierStatisticsHeapGovernor governor) throws IOException {
			FrontierStatisticsHeapGovernor.Lease lease = governor.tryAcquire(
					FrontierStatisticsMemoryPurpose.MAPPED_METADATA, SHARED_SHARD_METADATA_BYTES);
			if (lease == null) {
				throw new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
						"Frontier statistics mapped shard metadata lease was refused");
			}
			try {
				return new SharedShard(normalize(descriptor, manifestGenerationId),
						FrontierStatisticsShard.open(path), lease);
			} catch (IOException | RuntimeException failure) {
				lease.close();
				throw failure;
			}
		}

		private FrontierStatisticsShard shard() {
			return shard;
		}

		private boolean matches(FrontierStatisticsShardDescriptor descriptor, long manifestGenerationId) {
			return identity.equals(normalize(descriptor, manifestGenerationId));
		}

		private boolean retain() {
			int observed = references.get();
			while (observed != 0) {
				if (references.compareAndSet(observed, observed + 1)) {
					return true;
				}
				observed = references.get();
			}
			return false;
		}

		private void release(Throwable primary) {
			int remaining = references.decrementAndGet();
			if (remaining < 0) {
				throw new IllegalStateException("Frontier shared-shard reference count underflow");
			}
			if (remaining == 0) {
				try {
					shard.close();
				} catch (IOException closeFailure) {
					if (primary != null) {
						primary.addSuppressed(closeFailure);
					}
				} finally {
					metadataLease.close();
				}
			}
		}

		private static FrontierStatisticsShardDescriptor normalize(
				FrontierStatisticsShardDescriptor descriptor, long manifestGenerationId) {
			return descriptor.ownedBy(descriptor.resolvedOwnerGenerationId(manifestGenerationId));
		}
	}
}
