/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import java.io.IOException;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;

/** Query-local, generation-consistent mapped statistics view with bounded reusable scratch ownership. */
public final class FrontierStatisticsView implements AutoCloseable {

	private final FrontierStatisticsLease generation;
	private final FrontierStatisticsHeapGovernor.Lease scratch;
	private final FrontierFallbackReason fallbackReason;
	private final Consumer<Throwable> failureRecorder;
	private final AtomicBoolean closed = new AtomicBoolean();

	private FrontierStatisticsView(FrontierStatisticsLease generation,
			FrontierStatisticsHeapGovernor.Lease scratch, FrontierFallbackReason fallbackReason,
			Consumer<Throwable> failureRecorder) {
		this.generation = generation;
		this.scratch = scratch;
		this.fallbackReason = Objects.requireNonNull(fallbackReason, "fallbackReason");
		this.failureRecorder = failureRecorder;
	}

	static FrontierStatisticsView ready(FrontierStatisticsLease generation,
			FrontierStatisticsHeapGovernor.Lease scratch, Consumer<Throwable> failureRecorder) {
		return new FrontierStatisticsView(Objects.requireNonNull(generation, "generation"),
				Objects.requireNonNull(scratch, "scratch"), FrontierFallbackReason.NONE,
				Objects.requireNonNull(failureRecorder, "failureRecorder"));
	}

	static FrontierStatisticsView unavailable(FrontierFallbackReason fallbackReason) {
		if (fallbackReason == FrontierFallbackReason.NONE) {
			throw new IllegalArgumentException("an unavailable statistics view requires a fallback reason");
		}
		return new FrontierStatisticsView(null, null, fallbackReason, null);
	}

	public boolean ready() {
		return generation != null && !closed.get();
	}

	public FrontierFallbackReason fallbackReason() {
		return fallbackReason;
	}

	public long generationId() {
		return generation == null ? -1L : generation.generationId();
	}

	public long baseEpoch() {
		return generation == null ? -1L : generation.baseEpoch();
	}

	public long coveredEpoch() {
		return generation == null ? -1L : generation.coveredEpoch();
	}

	public FrontierLeafEstimate estimateLeaf(FrontierLeafProbe probe) {
		Objects.requireNonNull(probe, "probe");
		if (!ready()) {
			return FrontierLeafEstimate.unavailable(unavailableReason());
		}
		try {
			return generation.estimateLeaf(probe);
		} catch (IOException | RuntimeException failure) {
			recordFailure(failure);
			return FrontierLeafEstimate.unavailable(FrontierFallbackReason.SHARD_CORRUPT);
		}
	}

	public double estimateProjectedDistinct(FrontierLeafProbe probe, int component) {
		Objects.requireNonNull(probe, "probe");
		if (component < 0 || component >= 4) {
			throw new IllegalArgumentException("Frontier projected component must be in [0, 3]");
		}
		if (!ready()) {
			return Double.NaN;
		}
		try {
			return generation.estimateProjectedDistinct(probe, component);
		} catch (IOException | RuntimeException failure) {
			recordFailure(failure);
			return Double.NaN;
		}
	}

	public FrontierJoinEstimate estimateJoin(FrontierJoinProbe probe) {
		Objects.requireNonNull(probe, "probe");
		if (!ready()) {
			return FrontierJoinEstimate.unavailable(unavailableReason());
		}
		try {
			return generation.estimateJoin(probe);
		} catch (IOException | RuntimeException failure) {
			recordFailure(failure);
			return FrontierJoinEstimate.unavailable(FrontierFallbackReason.SHARD_CORRUPT);
		}
	}

	/** Returns joined rows per left input row from coordinated center lanes. */
	public FrontierJoinEstimate estimateConditionalJoin(FrontierJoinProbe probe, double upperRowsPerLeft) {
		Objects.requireNonNull(probe, "probe");
		if (!ready()) {
			return FrontierJoinEstimate.unavailable(unavailableReason());
		}
		try {
			return generation.estimateConditionalJoin(probe, upperRowsPerLeft);
		} catch (IOException | RuntimeException failure) {
			recordFailure(failure);
			return FrontierJoinEstimate.unavailable(FrontierFallbackReason.SHARD_CORRUPT);
		}
	}

	public FrontierJoinEstimate estimateSubgraph(FrontierJoinProgram program) {
		Objects.requireNonNull(program, "program");
		if (!ready()) {
			return FrontierJoinEstimate.unavailable(unavailableReason());
		}
		try {
			return generation.estimateSubgraph(program);
		} catch (IOException | RuntimeException failure) {
			recordFailure(failure);
			return FrontierJoinEstimate.unavailable(FrontierFallbackReason.SHARD_CORRUPT);
		}
	}

	private FrontierFallbackReason unavailableReason() {
		return closed.get() && fallbackReason == FrontierFallbackReason.NONE
				? FrontierFallbackReason.NO_GENERATION
				: fallbackReason;
	}

	private void recordFailure(Throwable failure) {
		if (failureRecorder != null) {
			failureRecorder.accept(failure);
		}
	}

	@Override
	public void close() {
		if (!closed.compareAndSet(false, true)) {
			return;
		}
		if (scratch != null) {
			scratch.close();
		}
		if (generation != null) {
			generation.close();
		}
	}
}
