/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

/** One effective statement insertion or deletion, durably ordered in the LMDB write transaction. */
public record FrontierMutation(long sequence, long epoch, boolean insertion, boolean explicit,
		long subjectId, long predicateId, long objectId, long contextId) {

	public FrontierMutation {
		if (sequence <= 0L || epoch <= 0L || subjectId <= 0L || predicateId <= 0L || objectId <= 0L
				|| contextId < 0L) {
			throw new IllegalArgumentException("Frontier mutation coordinates and term IDs are invalid");
		}
	}
}
