/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Two-pass, externally sorted builder for coordinated per-cell Omni statement witnesses. */
final class FrontierOmniBuilder implements AutoCloseable {

	static final int CELL_DIRECTORY_SHARD = 300;
	static final int PROJECTED_DISTINCT_SHARD = 301;
	private static final int DOMAIN_SHARD_BASE = 1_000;
	private static final int MAXIMUM_DOMAIN_ROWS = 4_000_000;
	private static final int DOMAIN_SORT_MEMORY_DIVISOR = 18;
	private static final long MAXIMUM_TEMPORARY_BYTES = 32L * 1024L * 1024L * 1024L;
	private static final int TEMPORARY_EVENT_HEADROOM_DENOMINATOR = 50;
	private static final double EMISSION_SAFETY_STANDARD_DEVIATIONS = 6.0d;
	private static final double TEMPORARY_EVENT_HEADROOM_STANDARD_DEVIATIONS = 8.0d;
	private static final int CAPACITY_SCALE_ITERATIONS = 48;

	private final Path directory;
	private final long generationId;
	private final long epoch;
	private final FrontierStatisticsBuildConfig config;
	private final FrontierFileOps fileOps;
	private final FrontierOmniLayout layout;
	private final int[] partitionStarts;
	private final int[] partitionEnds;
	private final long sortMemoryPerCollector;
	private final FrontierTemporaryDiskReservation temporaryDisk;
	private final long[] populations;
	private int[] authorityCapacity;
	private int[] retentionCapacity;
	private int[] retainedByAuthority;
	private long reservePopulatedCells;
	private int[] emissionTarget;
	private FrontierOmniExternalSorter.Collector[] events;
	private long maximumTermId;
	private boolean prepared;
	private boolean finished;

	FrontierOmniBuilder(Path directory, long generationId, long epoch, FrontierStatisticsBuildConfig config,
			FrontierFileOps fileOps) {
		this(directory, generationId, epoch, config, fileOps, 1, config.sortMemoryBytes(),
				new FrontierTemporaryDiskReservation(temporaryBudgetBytes(config)));
	}

	FrontierOmniBuilder(Path directory, long generationId, long epoch, FrontierStatisticsBuildConfig config,
			FrontierFileOps fileOps, int partitions, long sortMemoryPerCollector,
			FrontierTemporaryDiskReservation temporaryDisk) {
		this.directory = directory.toAbsolutePath().normalize();
		this.generationId = generationId;
		this.epoch = epoch;
		this.config = config;
		this.fileOps = fileOps;
		layout = new FrontierOmniLayout(config.designLaneCount(), config.auditLaneCount(), config.omniDepth(),
				config.cellCount());
		int planeLanes = Math.multiplyExact(FrontierOmniLayout.PLANE_COUNT, layout.lanes());
		if (partitions <= 0 || partitions > planeLanes
				|| sortMemoryPerCollector < FrontierOmniExternalSorter.RECORD_BYTES) {
			throw new IllegalArgumentException("Frontier Omni partition dimensions are invalid");
		}
		this.sortMemoryPerCollector = sortMemoryPerCollector;
		this.temporaryDisk = temporaryDisk;
		partitionStarts = new int[partitions];
		partitionEnds = new int[partitions];
		for (int partition = 0; partition < partitions; partition++) {
			partitionStarts[partition] = partition * planeLanes / partitions;
			partitionEnds[partition] = (partition + 1) * planeLanes / partitions;
		}
		populations = new long[layout.cells()];
	}

	void addPopulation(int plane, long subject, long predicate, long object, long context) {
		for (int partition = 0; partition < partitionStarts.length; partition++) {
			addPopulation(partition, plane, subject, predicate, object, context);
		}
	}

	void addPopulation(int partition, int plane, long subject, long predicate, long object, long context) {
		if (prepared) {
			throw new IllegalStateException("Frontier Omni populations are already sealed");
		}
		for (int planeLane = partitionStarts[partition]; planeLane < partitionEnds[partition]; planeLane++) {
			if (planeLane / layout.lanes() != plane) {
				continue;
			}
			int lane = planeLane % layout.lanes();
			addComponentPopulation(plane, lane, 0, subject);
			addComponentPopulation(plane, lane, 1, predicate);
			addComponentPopulation(plane, lane, 2, object);
			addComponentPopulation(plane, lane, 3, context);
		}
	}

	void prepareWitnessPass(long maximumTermId) throws IOException {
		if (prepared) {
			throw new IllegalStateException("Frontier Omni witness pass is already prepared");
		}
		prepared = true;
		this.maximumTermId = maximumTermId;
		allocateSamples();
		events = new FrontierOmniExternalSorter.Collector[partitionStarts.length];
		try {
			for (int partition = 0; partition < events.length; partition++) {
				events[partition] = FrontierOmniExternalSorter.collector(directory, sortMemoryPerCollector,
						temporaryBudgetBytes(config), temporaryDisk);
			}
		} catch (IOException failure) {
			closeCollectors();
			throw failure;
		}
	}

	void addWitnesses(int plane, long subject, long predicate, long object, long context) throws IOException {
		for (int partition = 0; partition < partitionStarts.length; partition++) {
			addWitnesses(partition, plane, subject, predicate, object, context);
		}
	}

	void addWitnesses(int partition, int plane, long subject, long predicate, long object, long context)
			throws IOException {
		if (!prepared || finished) {
			throw new IllegalStateException("Frontier Omni witness pass is not active");
		}
		FrontierOmniExternalSorter.Collector collector = events[partition];
		long rowPriority = FrontierStatisticsHash.rowPriority(plane, subject, predicate, object, context);
		for (int planeLane = partitionStarts[partition]; planeLane < partitionEnds[partition]; planeLane++) {
			if (planeLane / layout.lanes() != plane) {
				continue;
			}
			int lane = planeLane % layout.lanes();
			long priority = FrontierStatisticsHash.omniPriorityFromRowPriority(lane, rowPriority);
			addComponentWitnesses(collector, plane, lane, 0, subject, priority, subject, predicate, object, context);
			addComponentWitnesses(collector, plane, lane, 1, predicate, priority, subject, predicate, object, context);
			addComponentWitnesses(collector, plane, lane, 2, object, priority, subject, predicate, object, context);
			addComponentWitnesses(collector, plane, lane, 3, context, priority, subject, predicate, object, context);
		}
	}

	List<FrontierStatisticsShardDescriptor> finish() throws IOException {
		if (!prepared || finished) {
			throw new IllegalStateException("Frontier Omni builder is not ready to finish");
		}
		finished = true;
		Output output = new Output();
		try {
			for (FrontierOmniExternalSorter.Collector collector : events) {
				collector.finish(output::accept);
			}
			output.finish();
			return output.descriptors();
		} finally {
			closeCollectors();
			events = null;
		}
	}

	int partitions() {
		return partitionStarts.length;
	}

	static long estimatedHeapBytes(FrontierStatisticsBuildConfig config) {
		return estimatedHeapBytes(config, config.sortMemoryBytes());
	}

	static long estimatedHeapBytes(FrontierStatisticsBuildConfig config, long sortMemoryBytes) {
		FrontierOmniLayout layout = new FrontierOmniLayout(config.designLaneCount(), config.auditLaneCount(),
				config.omniDepth(), config.cellCount());
		long cells = layout.cells();
		long matrixAndDirectory = Math.multiplyExact(cells,
				2L * Long.BYTES + 6L * Integer.BYTES + Byte.BYTES);
		long boundedBuffers = Math.addExact(sortMemoryBytes, domainBufferBytes(config));
		long cellBuffer = Math.multiplyExact((long) maximumRetention(config),
				6L * Long.BYTES + Integer.BYTES + Byte.BYTES);
		return Math.addExact(matrixAndDirectory, Math.addExact(boundedBuffers, cellBuffer));
	}

	@Override
	public void close() throws IOException {
		if (events != null) {
			closeCollectors();
			events = null;
		}
	}

	private void addComponentPopulation(int plane, int lane, int component, long value) {
		for (int row = 0; row < layout.depth(); row++) {
			int cell = layout.cell(plane, lane, component, row, value);
			populations[cell] = Math.incrementExact(populations[cell]);
		}
	}

	private void addComponentWitnesses(FrontierOmniExternalSorter.Collector collector,
			int plane, int lane, int component, long value, long priority,
			long subject, long predicate, long object, long context) throws IOException {
		for (int row = 0; row < layout.depth(); row++) {
			int cell = layout.cell(plane, lane, component, row, value);
			long population = populations[cell];
			int emission = emissionTarget[cell];
			if (emission != 0 && (emission >= population
					|| FrontierStatisticsHash.unsignedMultiplyHigh(priority, population) < emission)) {
				collector.add(cell, priority, subject, predicate, object, context);
			}
		}
	}

	private void closeCollectors() throws IOException {
		IOException failure = null;
		for (FrontierOmniExternalSorter.Collector collector : events) {
			if (collector == null) {
				continue;
			}
			try {
				collector.close();
			} catch (IOException current) {
				if (failure == null) {
					failure = current;
				} else {
					failure.addSuppressed(current);
				}
			}
		}
		if (failure != null) {
			throw failure;
		}
	}

	private void allocateSamples() throws FrontierStatisticsException {
		authorityCapacity = new int[layout.cells()];
		retentionCapacity = new int[layout.cells()];
		emissionTarget = new int[layout.cells()];
		long directoryBytes = Math.multiplyExact((long) layout.cells(), 40L);
		long availableBytes = config.leafWitnessBudgetBytes() - directoryBytes;
		int termWidth = FrontierStatisticsShard.bitWidth(maximumTermId);
		long bytesPerWitness = Math.max(24L, (4L * termWidth + 7L) / 8L + 21L);
		if (availableBytes <= 0L) {
			throw insufficientLeafBudget();
		}
		long retainedRecordBudget = availableBytes / bytesPerWitness;
		long populatedCells = 0L;
		long requestedBase = 0L;
		for (long population : populations) {
			if (population != 0L) {
				populatedCells++;
				requestedBase = Math.addExact(requestedBase,
						Math.min(population, config.witnessFloorPerCell()));
			}
		}
		if (populatedCells == 0L) {
			return;
		}
		long maximumBaseSamples = retainedRecordBudget;
		if (maximumBaseSamples < populatedCells) {
			throw insufficientLeafBudget();
		}
		int effectiveFloor = config.witnessFloorPerCell();
		if (requestedBase > maximumBaseSamples) {
			effectiveFloor = Math.max(1, Math.toIntExact(maximumBaseSamples / populatedCells));
		}

		long allocatedBase = 0L;
		double expandableWeight = 0.0d;
		for (int cell = 0; cell < populations.length; cell++) {
			long population = populations[cell];
			if (population == 0L) {
				continue;
			}
			int target = Math.toIntExact(Math.min(population, effectiveFloor));
			authorityCapacity[cell] = target;
			allocatedBase += target;
			if (target < Math.min(population, config.witnessCeilingPerCell())) {
				expandableWeight += Math.sqrt(population);
			}
		}
		long remainingBase = Math.max(0L, maximumBaseSamples - allocatedBase);
		if (remainingBase != 0L && expandableWeight != 0.0d) {
			for (int cell = 0; cell < populations.length; cell++) {
				long population = populations[cell];
				int current = authorityCapacity[cell];
				long ceiling = Math.min(population, config.witnessCeilingPerCell());
				if (current >= ceiling) {
					continue;
				}
				long proposed = (long) Math.floor(remainingBase * Math.sqrt(population) / expandableWeight);
				int extra = Math.toIntExact(Math.min(ceiling - current, proposed));
				authorityCapacity[cell] = Math.addExact(current, extra);
			}
		}
		fitRetainedEnvelope(retainedRecordBudget, populatedCells);
		fitTemporaryEventEnvelope();
	}

	private void fitRetainedEnvelope(long retainedRecordBudget, long populatedCells)
			throws FrontierStatisticsException {
		reservePopulatedCells = populatedCells;
		retainedByAuthority = new int[config.witnessCeilingPerCell() + 1];
		if (projectedRetainedRows(1.0d, false) <= retainedRecordBudget) {
			projectedRetainedRows(1.0d, true);
			return;
		}
		if (projectedRetainedRows(0.0d, false) > retainedRecordBudget) {
			throw insufficientLeafBudget();
		}
		double low = 0.0d;
		double high = 1.0d;
		for (int iteration = 0; iteration < CAPACITY_SCALE_ITERATIONS; iteration++) {
			double middle = (low + high) * 0.5d;
			if (projectedRetainedRows(middle, false) <= retainedRecordBudget) {
				low = middle;
			} else {
				high = middle;
			}
		}
		if (projectedRetainedRows(low, true) > retainedRecordBudget) {
			throw insufficientLeafBudget();
		}
	}

	private long projectedRetainedRows(double capacityScale, boolean apply) {
		long total = 0L;
		for (int cell = 0; cell < populations.length; cell++) {
			int original = authorityCapacity[cell];
			if (original == 0) {
				continue;
			}
			int authoritative = capacityScale >= 1.0d
					? original
					: Math.max(1, (int) Math.floor(original * capacityScale));
			int retained = retainedCapacity(authoritative, populations[cell]);
			total = Math.addExact(total, retained);
			if (apply) {
				authorityCapacity[cell] = authoritative;
				retentionCapacity[cell] = retained;
			}
		}
		return total;
	}

	private void fitTemporaryEventEnvelope() throws FrontierStatisticsException {
		long temporaryRecords = temporaryBudgetBytes(config) / FrontierOmniExternalSorter.RECORD_BYTES;
		long proportionalHeadroom = Math.max(1L,
				temporaryRecords / TEMPORARY_EVENT_HEADROOM_DENOMINATOR);
		double correlatedEvents = 4.0d * layout.depth() * temporaryRecords;
		long deviationHeadroom = (long) Math.ceil(
				TEMPORARY_EVENT_HEADROOM_STANDARD_DEVIATIONS * Math.sqrt(correlatedEvents));
		long eventBudget = Math.max(0L,
				temporaryRecords - Math.max(proportionalHeadroom, deviationHeadroom));
		if (projectedEmissionRows(1.0d, false) <= eventBudget) {
			projectedEmissionRows(1.0d, true);
			return;
		}
		if (projectedEmissionRows(0.0d, false) > eventBudget) {
			throw insufficientTemporaryBudget();
		}

		double low = 0.0d;
		double high = 1.0d;
		for (int iteration = 0; iteration < CAPACITY_SCALE_ITERATIONS; iteration++) {
			double middle = (low + high) * 0.5d;
			if (projectedEmissionRows(middle, false) <= eventBudget) {
				low = middle;
			} else {
				high = middle;
			}
		}
		long admitted = projectedEmissionRows(low, true);
		if (admitted > eventBudget) {
			throw insufficientTemporaryBudget();
		}
	}

	private long projectedEmissionRows(double capacityScale, boolean apply) {
		long total = 0L;
		for (int cell = 0; cell < populations.length; cell++) {
			int original = authorityCapacity[cell];
			if (original == 0) {
				continue;
			}
			int authoritative = capacityScale >= 1.0d
					? original
					: Math.max(1, (int) Math.floor(original * capacityScale));
			long population = populations[cell];
			int retained = retainedCapacity(authoritative, population);
			long safety = (long) Math.ceil(EMISSION_SAFETY_STANDARD_DEVIATIONS * Math.sqrt(retained));
			int emission = Math.toIntExact(Math.min(population, Math.addExact((long) retained, safety)));
			total = Math.addExact(total, emission);
			if (apply) {
				authorityCapacity[cell] = authoritative;
				retentionCapacity[cell] = retained;
				emissionTarget[cell] = emission;
			}
		}
		return total;
	}

	private int retainedCapacity(int authoritative, long population) {
		int retained = retainedByAuthority[authoritative];
		if (retained == 0) {
			retained = FrontierDeleteReserveSizing.retainedCapacity(authoritative, Long.MAX_VALUE,
					config.deleteReserveFraction(), reservePopulatedCells);
			retainedByAuthority[authoritative] = retained;
		}
		return Math.toIntExact(Math.min(population, retained));
	}

	static long temporaryBudgetBytes(FrontierStatisticsBuildConfig config) {
		return Math.min(MAXIMUM_TEMPORARY_BYTES, config.diskBudgetBytes());
	}

	private static int maximumRetention(FrontierStatisticsBuildConfig config) {
		FrontierOmniLayout layout = new FrontierOmniLayout(config.designLaneCount(), config.auditLaneCount(),
				config.omniDepth(), config.cellCount());
		return FrontierDeleteReserveSizing.retainedCapacity(config.witnessCeilingPerCell(), Long.MAX_VALUE,
				config.deleteReserveFraction(), layout.cells());
	}

	private static int domainCapacity(FrontierStatisticsBuildConfig config) {
		long memoryBound = Math.max(1_024L, config.sortMemoryBytes() / DOMAIN_SORT_MEMORY_DIVISOR);
		int bounded = Math.toIntExact(Math.min(MAXIMUM_DOMAIN_ROWS, memoryBound));
		return Math.max(maximumRetention(config), bounded);
	}

	private static long domainBufferBytes(FrontierStatisticsBuildConfig config) {
		int capacity = domainCapacity(config);
		long columns = Math.multiplyExact((long) capacity,
				5L * Long.BYTES + Byte.BYTES + Integer.BYTES);
		long hash = Math.multiplyExact((long) domainHashCapacity(capacity), Integer.BYTES);
		return Math.addExact(columns, hash);
	}

	private static int domainHashCapacity(int capacity) {
		int hashCapacity = 1;
		while (hashCapacity < Math.multiplyExact(capacity, 2)) {
			hashCapacity <<= 1;
		}
		return hashCapacity;
	}

	private static FrontierStatisticsException insufficientLeafBudget() {
		return new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
				"Frontier Omni cell floor cannot fit the leaf-witness disk envelope");
	}

	private static FrontierStatisticsException insufficientTemporaryBudget() {
		return new FrontierStatisticsException(FrontierFallbackReason.MEMORY_PRESSURE,
				"Frontier Omni minimum sampling support cannot fit the temporary-disk envelope");
	}

	private final class Output {

		private final int[] domains = new int[layout.cells()];
		private final int[] starts = new int[layout.cells()];
		private final int[] counts = new int[layout.cells()];
		private final int[] samplingNumerators = new int[layout.cells()];
		private final long[] cutoffPriorities = new long[layout.cells()];
		private final byte[] flags = new byte[layout.cells()];
		private final ArrayList<FrontierStatisticsShardDescriptor> descriptors = new ArrayList<>();
		private final CellBuffer cellBuffer = new CellBuffer(maximumRetention(config));
		private final DomainBuffer domainBuffer = new DomainBuffer();
		private int currentCell = -1;
		private long emittedForCell;

		private void accept(long cellValue, long priority, long subject, long predicate, long object, long context)
				throws IOException {
			int cell = Math.toIntExact(cellValue);
			if (cell < currentCell || cell < 0 || cell >= layout.cells()) {
				throw new IOException("Frontier Omni external sort emitted an invalid cell order");
			}
			if (cell != currentCell) {
				finishCell();
				currentCell = cell;
				emittedForCell = 0L;
				cellBuffer.clear();
			}
			emittedForCell = Math.incrementExact(emittedForCell);
			if (cellBuffer.size < retentionCapacity[cell]) {
				cellBuffer.add(priority, subject, predicate, object, context);
			}
		}

		private void finish() throws IOException {
			finishCell();
			domainBuffer.finish();
			for (int cell = 0; cell < populations.length; cell++) {
				if (populations[cell] == 0L) {
					flags[cell] = FrontierOmniCellFlags.COMPLETE | FrontierOmniCellFlags.AUTHORITATIVE;
				}
			}
			descriptors.add(writeDirectory());
		}

		private List<FrontierStatisticsShardDescriptor> descriptors() {
			return List.copyOf(descriptors);
		}

		private void finishCell() throws IOException {
			if (currentCell < 0) {
				return;
			}
			long population = populations[currentCell];
			int retained = cellBuffer.size;
			byte state = 0;
			if (retained != 0) {
				state |= FrontierOmniCellFlags.AUTHORITATIVE;
				if (population <= retentionCapacity[currentCell]) {
					if (retained != population) {
						throw new IOException("Frontier Omni complete cell lost a witness during build");
					}
					state |= FrontierOmniCellFlags.COMPLETE;
				} else if (emittedForCell >= retentionCapacity[currentCell]) {
					state |= FrontierOmniCellFlags.BOTTOM_K;
				} else {
					state |= FrontierOmniCellFlags.THRESHOLD_SAMPLE;
				}
				if (retentionCapacity[currentCell] > authorityCapacity[currentCell]) {
					state |= FrontierOmniCellFlags.DELETE_RESERVE_PRESENT;
				}
			}
			flags[currentCell] = state;
			samplingNumerators[currentCell] = (state & FrontierOmniCellFlags.THRESHOLD_SAMPLE) != 0
					? emissionTarget[currentCell]
					: retained;
			cutoffPriorities[currentCell] = retained == 0 ? 0L : cellBuffer.priorities[retained - 1];
			domainBuffer.append(currentCell, cellBuffer);
		}

		private FrontierStatisticsShardDescriptor writeDirectory() throws IOException {
			return writeShard(CELL_DIRECTORY_SHARD, layout.cells(), FrontierStatisticsShardKind.OMNI_CELL_DIRECTORY,
					layout.encodedDimensions(), layout.lanes(), layout.designLanes(), layout.lanes(), writer -> {
						writer.addUnsignedColumn(0, populations);
						writer.addUnsignedIntColumn(1, domains, domains.length);
						writer.addUnsignedIntColumn(2, starts, starts.length);
						writer.addUnsignedIntColumn(3, counts, counts.length);
						writer.addUnsignedByteColumn(4, flags, flags.length);
						writer.addUnsignedIntColumn(5, samplingNumerators, samplingNumerators.length);
						writer.addSignedColumn(6, cutoffPriorities);
					});
		}

		private final class DomainBuffer {

			private final int capacity = domainCapacity(config);
			private final long[] priorities = new long[capacity];
			private final byte[] planes = new byte[capacity];
			private final long[] subjects = new long[capacity];
			private final long[] predicates = new long[capacity];
			private final long[] objects = new long[capacity];
			private final long[] contexts = new long[capacity];
			private final int[] postings = new int[capacity];
			private final int[] tupleSlots = new int[domainHashCapacity(capacity)];
			private int domain;
			private int tupleSize;
			private int postingSize;
			private int minimumCell = Integer.MAX_VALUE;
			private int maximumCell = -1;

			private void append(int cell, CellBuffer source) throws IOException {
				if (source.size == 0) {
					return;
				}
				if (postingSize != 0 && postingSize > capacity - source.size) {
					flush();
				}
				if (source.size > capacity) {
					throw new IOException("Frontier Omni cell exceeds the bounded tuple-domain capacity");
				}
				domains[cell] = domain;
				starts[cell] = postingSize;
				counts[cell] = source.size;
				minimumCell = Math.min(minimumCell, cell);
				maximumCell = Math.max(maximumCell, cell);
				byte plane = (byte) layout.plane(cell);
				for (int index = 0; index < source.size; index++) {
					postings[postingSize++] = findOrAddTuple(
							source.priorities[index], plane, source.subjects[index], source.predicates[index],
							source.objects[index], source.contexts[index]);
				}
			}

			private void finish() throws IOException {
				if (postingSize != 0) {
					flush();
				} else if (domain == 0) {
					writeDomainPair(0, 0, 0, 0, 0);
					domain++;
				}
			}

			private void flush() throws IOException {
				writeDomainPair(domain, tupleSize, postingSize, minimumCell, maximumCell);
				domain++;
				tupleSize = 0;
				postingSize = 0;
				Arrays.fill(tupleSlots, 0);
				minimumCell = Integer.MAX_VALUE;
				maximumCell = -1;
			}

			private int findOrAddTuple(long priority, byte plane, long subject, long predicate, long object,
					long context) {
				int mask = tupleSlots.length - 1;
				int slot = (int) tupleHash(priority, plane, subject, predicate, object, context) & mask;
				while (true) {
					int entry = tupleSlots[slot];
					if (entry == 0) {
						int ordinal = tupleSize++;
						priorities[ordinal] = priority;
						planes[ordinal] = plane;
						subjects[ordinal] = subject;
						predicates[ordinal] = predicate;
						objects[ordinal] = object;
						contexts[ordinal] = context;
						tupleSlots[slot] = ordinal + 1;
						return ordinal;
					}
					int ordinal = entry - 1;
					if (priorities[ordinal] == priority && planes[ordinal] == plane
							&& subjects[ordinal] == subject && predicates[ordinal] == predicate
							&& objects[ordinal] == object && contexts[ordinal] == context) {
						return ordinal;
					}
					slot = slot + 1 & mask;
				}
			}

			private void writeDomainPair(int domainId, int tupleRows, int postingRows, int minimum, int maximum)
					throws IOException {
				int tupleShardId = Math.addExact(DOMAIN_SHARD_BASE, Math.multiplyExact(domainId, 2));
				int postingShardId = Math.incrementExact(tupleShardId);
				FrontierStatisticsShardDescriptor tuples = writeShard(tupleShardId, tupleRows,
						FrontierStatisticsShardKind.OMNI_TUPLES, domainId, 0, minimum, maximum, writer -> {
							writer.addSignedColumn(0, priorities, tupleRows);
							writer.addUnsignedByteColumn(1, planes, tupleRows);
							writer.addTermColumn(2, subjects, tupleRows);
							writer.addTermColumn(3, predicates, tupleRows);
							writer.addTermColumn(4, objects, tupleRows);
							writer.addTermColumn(5, contexts, tupleRows);
						});
				FrontierStatisticsShardDescriptor posting = writeShard(postingShardId, postingRows,
						FrontierStatisticsShardKind.OMNI_POSTINGS, domainId, 0, minimum, maximum,
						writer -> writer.addUnsignedIntColumn(0, postings, postingRows));
				descriptors.add(tuples);
				descriptors.add(posting);
			}

			private static long tupleHash(long priority, byte plane, long subject, long predicate, long object,
					long context) {
				long hash = FrontierStatisticsHash.mix64(priority ^ Byte.toUnsignedLong(plane));
				hash = FrontierStatisticsHash.mix64(hash ^ subject);
				hash = FrontierStatisticsHash.mix64(hash ^ predicate);
				hash = FrontierStatisticsHash.mix64(hash ^ object);
				return FrontierStatisticsHash.mix64(hash ^ context);
			}
		}
	}

	private FrontierStatisticsShardDescriptor writeShard(int shardId, long rows, FrontierStatisticsShardKind kind,
			long logicalKey, int lane, long minimumKey, long maximumKey, ShardColumns columns) throws IOException {
		String fileName = "generation-%019d-shard-%05d.fs2s".formatted(generationId, shardId);
		Path target = directory.resolve(fileName);
		Path temporary = directory.resolve(fileName + ".tmp");
		boolean moved = false;
		try {
			try (FrontierStatisticsShardWriter writer = new FrontierStatisticsShardWriter(
					temporary, generationId, shardId, epoch, maximumTermId, rows)) {
				columns.write(writer);
				writer.finish();
			}
			fileOps.moveAtomically(temporary, target);
			moved = true;
			return new FrontierStatisticsShardDescriptor(shardId, FrontierStatisticsTier.LEAF_WITNESSES, true,
					fileName, Files.size(target), rows, kind, logicalKey, lane, minimumKey, maximumKey);
		} finally {
			if (!moved) {
				fileOps.deleteIfExists(temporary);
			}
		}
	}

	@FunctionalInterface
	private interface ShardColumns {

		void write(FrontierStatisticsShardWriter writer) throws IOException;
	}

	private static final class CellBuffer {

		private final long[] priorities;
		private final long[] subjects;
		private final long[] predicates;
		private final long[] objects;
		private final long[] contexts;
		private int size;

		private CellBuffer(int capacity) {
			priorities = new long[capacity];
			subjects = new long[capacity];
			predicates = new long[capacity];
			objects = new long[capacity];
			contexts = new long[capacity];
		}

		private void clear() {
			size = 0;
		}

		private void add(long priority, long subject, long predicate, long object, long context) {
			priorities[size] = priority;
			subjects[size] = subject;
			predicates[size] = predicate;
			objects[size] = object;
			contexts[size] = context;
			size++;
		}
	}
}
