/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Objects;
import java.util.zip.CRC32C;

final class FrontierPayloadBlockWriter {

	static final int MAGIC = 0x524a4642; // RJFB
	static final int LEGACY_VERSION = 1;
	static final int VERSION = 2;
	static final int HEADER_BYTES = 40;
	static final int CHECKSUM_BYTES = Long.BYTES;
	static final int MINIMUM_BLOCK_BYTES = HEADER_BYTES + CHECKSUM_BYTES;

	private final OutputStream output;
	private final FrontierPayloadKind kind;
	private final long generation;
	private final FrontierPayloadBlockLimits limits;
	private final MessageDigest digest;

	private long payloadBytes;
	private long payloadRecords;
	private int blockCount;
	private boolean finished;
	private boolean failed;

	FrontierPayloadBlockWriter(OutputStream output, FrontierPayloadKind kind, long generation,
			FrontierPayloadBlockLimits limits) {
		this.output = Objects.requireNonNull(output, "output");
		this.kind = Objects.requireNonNull(kind, "kind");
		if (generation <= 0L) {
			throw new IllegalArgumentException("Frontier payload generation must be positive");
		}
		this.generation = generation;
		this.limits = Objects.requireNonNull(limits, "limits");
		this.digest = sha256();
	}

	void writeBlock(int longsPerRecord, long[] packedRecords) throws IOException {
		ensureWritable();
		Objects.requireNonNull(packedRecords, "packedRecords");
		if (longsPerRecord <= 0) {
			throw new IllegalArgumentException("longsPerRecord must be positive");
		}
		if (longsPerRecord > limits.maximumLongsPerRecord()) {
			throw budgetExceeded("Frontier payload record width exceeds its configured cap");
		}
		if (packedRecords.length == 0 || packedRecords.length % longsPerRecord != 0) {
			throw new IllegalArgumentException("packedRecords must contain one or more complete records");
		}

		int recordCount = packedRecords.length / longsPerRecord;
		if (recordCount > limits.maximumBlockRecords()) {
			throw budgetExceeded("Frontier payload block record count exceeds its configured cap");
		}
		long nextPayloadRecords;
		try {
			nextPayloadRecords = Math.addExact(payloadRecords, recordCount);
		} catch (ArithmeticException e) {
			throw budgetExceeded("Frontier payload record count overflow", e);
		}
		if (nextPayloadRecords > limits.maximumPayloadRecords()) {
			throw budgetExceeded("Frontier payload record count exceeds its configured cap");
		}

		int bodyBytes;
		int blockBytes;
		try {
			bodyBytes = Math.multiplyExact(packedRecords.length, Long.BYTES);
			blockBytes = Math.addExact(Math.addExact(HEADER_BYTES, bodyBytes), CHECKSUM_BYTES);
		} catch (ArithmeticException e) {
			throw budgetExceeded("Frontier payload block byte count overflow", e);
		}
		if (blockBytes > limits.maximumBlockBytes()) {
			throw budgetExceeded("Frontier payload block exceeds its configured byte cap");
		}
		long nextPayloadBytes;
		try {
			nextPayloadBytes = Math.addExact(payloadBytes, blockBytes);
		} catch (ArithmeticException e) {
			throw budgetExceeded("Frontier payload byte count overflow", e);
		}
		if (nextPayloadBytes > limits.maximumPayloadBytes()) {
			throw budgetExceeded("Frontier payload exceeds its configured byte cap");
		}

		try {
			ByteBuffer block = ByteBuffer.allocate(blockBytes)
					.putInt(MAGIC)
					.putInt(VERSION)
					.putInt(HEADER_BYTES)
					.putInt(blockBytes)
					.putInt(kind.code())
					.putLong(generation)
					.putInt(longsPerRecord)
					.putInt(recordCount)
					.putInt(bodyBytes);
			for (long value : packedRecords) {
				block.putLong(value);
			}
			CRC32C checksum = new CRC32C();
			checksum.update(block.array(), 0, blockBytes - CHECKSUM_BYTES);
			block.putLong(checksum.getValue());
			output.write(block.array());
			digest.update(block.array());
		} catch (IOException | RuntimeException | Error e) {
			failed = true;
			throw e;
		}
		payloadBytes = nextPayloadBytes;
		payloadRecords = nextPayloadRecords;
		blockCount++;
	}

	FrontierPayloadDescriptor finish() throws IOException {
		ensureWritable();
		if (blockCount == 0) {
			throw new IllegalStateException("Frontier payload must contain at least one block");
		}
		try {
			output.flush();
			finished = true;
			return new FrontierPayloadDescriptor(kind, generation, payloadBytes, digest.digest());
		} catch (IOException | RuntimeException | Error e) {
			failed = true;
			throw e;
		}
	}

	private void ensureWritable() {
		if (finished || failed) {
			throw new IllegalStateException("Frontier payload writer is finished or failed");
		}
	}

	private static FrontierPayloadException budgetExceeded(String message) {
		return new FrontierPayloadException(FrontierSynopsisStatus.BUDGET_EXCEEDED, message);
	}

	private static FrontierPayloadException budgetExceeded(String message, Throwable cause) {
		return new FrontierPayloadException(FrontierSynopsisStatus.BUDGET_EXCEEDED, message, cause);
	}

	private static MessageDigest sha256() {
		try {
			return MessageDigest.getInstance("SHA-256");
		} catch (NoSuchAlgorithmException e) {
			throw new ExceptionInInitializerError(e);
		}
	}
}
