/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

import org.eclipse.rdf4j.sail.lmdb.config.FrontierEstimatorMode;

/**
 * Owns the persistent Frontier synopsis lifecycle.
 *
 * <p>
 * A zero-byte budget is intentionally resolved before any filesystem or snapshot-source operation. This permits an
 * authoritative estimator mode to use exact query-local states while persistent sampled evidence remains disabled.
 * </p>
 */
public final class LmdbFrontierSynopsisService implements AutoCloseable {

	static final int SYNOPSIS_SCHEMA_VERSION = 1;
	static final int HASH_VERSION = 1;
	static final int SEED_SCHEDULE_VERSION = 2;
	private static final int MAXIMUM_PAYLOAD_BLOCK_BYTES = 64 * 1024;
	private static final int MAXIMUM_EXACT_INSERT_GENERATIONS = 8;
	private static final int DIRTY_MARKER_MAGIC = 0x524a4644; // RJFD
	private static final int DIRTY_MARKER_VERSION = 1;
	private static final String DIRTY_MARKER_FILE = "dirty-deletion.bin";
	private static final String DIRTY_MARKER_TEMPORARY_FILE = "dirty-deletion.bin.tmp";
	private static final String INSERTION_MARKER_FILE = "dirty-insertion.bin";
	private static final String INSERTION_MARKER_TEMPORARY_FILE = "dirty-insertion.bin.tmp";

	private final Path frontierDirectory;
	private final FrontierFileOps fileOps;
	private final BuildContext buildContext;
	private ArrayList<FrontierInsertion> pendingInsertions;
	private boolean pendingInsertionsOverflowed;
	private boolean insertionMarkerOwnedByCurrentTransaction;
	private volatile FrontierSynopsisStatus status;
	private volatile FrontierQueryIndexView queryIndexView;
	private volatile String queryIndexFailureReason = "query_index_unavailable";
	private final AtomicLong planningRevision = new AtomicLong(1L);

	private LmdbFrontierSynopsisService(FrontierSynopsisStatus status) {
		this(null, null, null, status);
	}

	private LmdbFrontierSynopsisService(Path frontierDirectory, FrontierFileOps fileOps,
			FrontierSynopsisStatus status) {
		this(frontierDirectory, fileOps, null, status);
	}

	private LmdbFrontierSynopsisService(Path frontierDirectory, FrontierFileOps fileOps, BuildContext buildContext,
			FrontierSynopsisStatus status) {
		this.frontierDirectory = frontierDirectory;
		this.fileOps = fileOps;
		this.buildContext = buildContext;
		this.status = Objects.requireNonNull(status, "status");
	}

	public static LmdbFrontierSynopsisService open(Path frontierDirectory, FrontierEstimatorMode mode,
			UUID durableStoreId, long synopsisBudgetBytes, int designLaneCount, int auditLaneCount,
			FrontierSnapshotSourceFactory snapshotSourceFactory, long queryIndexBudgetBytes) {
		Objects.requireNonNull(mode, "mode");
		if (synopsisBudgetBytes < 0L) {
			throw new IllegalArgumentException("Frontier synopsis budget must be nonnegative");
		}
		if (queryIndexBudgetBytes < 0L) {
			throw new IllegalArgumentException("Frontier query index budget must be nonnegative");
		}
		if (mode == FrontierEstimatorMode.OFF) {
			return new LmdbFrontierSynopsisService(FrontierSynopsisStatus.DISABLED_MODE);
		}
		if (synopsisBudgetBytes == 0L) {
			return new LmdbFrontierSynopsisService(FrontierSynopsisStatus.DISABLED_ZERO_BUDGET);
		}
		if (designLaneCount <= 0 || auditLaneCount <= 0) {
			throw new IllegalArgumentException("Frontier design and audit lane counts must be positive");
		}

		Path normalizedDirectory = Objects.requireNonNull(frontierDirectory, "frontierDirectory")
				.toAbsolutePath()
				.normalize();
		FrontierFileOps fileOps = NioFrontierFileOps.INSTANCE;
		BuildContext buildContext = new BuildContext(
				durableStoreId,
				synopsisBudgetBytes,
				queryIndexBudgetBytes,
				designLaneCount,
				auditLaneCount,
				Objects.requireNonNull(snapshotSourceFactory, "snapshotSourceFactory"));
		FrontierSynopsisStatus dirtyStatus = dirtyMarkerStatus(normalizedDirectory, fileOps);
		if (dirtyStatus == FrontierSynopsisStatus.DIRTY_DELETION) {
			return new LmdbFrontierSynopsisService(normalizedDirectory, fileOps, buildContext, dirtyStatus);
		}
		boolean dirtyInsertion = dirtyStatus == FrontierSynopsisStatus.DIRTY_INSERTION;
		FrontierManifest manifest;
		try {
			manifest = new FrontierManifestStore(normalizedDirectory, fileOps).load();
		} catch (FrontierManifestException e) {
			return new LmdbFrontierSynopsisService(normalizedDirectory, fileOps, buildContext,
					dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : e.status());
		} catch (IOException e) {
			return new LmdbFrontierSynopsisService(normalizedDirectory, fileOps, buildContext,
					dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : FrontierSynopsisStatus.CORRUPT);
		}

		if (durableStoreId == null) {
			return new LmdbFrontierSynopsisService(normalizedDirectory, fileOps, buildContext,
					FrontierSynopsisStatus.STORE_MISMATCH);
		}
		FrontierManifestIdentity expectedIdentity = new FrontierManifestIdentity(
				durableStoreId,
				manifest.identity().snapshotEpoch(),
				SYNOPSIS_SCHEMA_VERSION,
				HASH_VERSION,
				SEED_SCHEDULE_VERSION,
				designLaneCount,
				auditLaneCount,
				FrontierManifestIdentity.ALL_DIRECTIONS,
				FrontierManifestIdentity.ALL_LANE_ROLES,
				synopsisBudgetBytes);
		try {
			manifest.identity().requireCompatible(expectedIdentity);
		} catch (FrontierManifestException e) {
			return new LmdbFrontierSynopsisService(normalizedDirectory, fileOps, buildContext,
					dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : e.status());
		}
		FrontierSynopsisStatus status = verifyLoadedManifest(
				normalizedDirectory,
				synopsisBudgetBytes,
				manifest,
				snapshotSourceFactory,
				fileOps);
		if (dirtyInsertion) {
			status = recoverInsertionMarker(normalizedDirectory, fileOps, status);
		}
		LmdbFrontierSynopsisService service = new LmdbFrontierSynopsisService(
				normalizedDirectory, fileOps, buildContext, status);
		service.initializeQueryIndexIfReady(manifest);
		return service;
	}

	LmdbFrontierSynopsisService(Path frontierDirectory, long synopsisBudgetBytes,
			FrontierSnapshotSourceFactory snapshotSourceFactory, FrontierFileOps fileOps) {
		Objects.requireNonNull(frontierDirectory, "frontierDirectory");
		if (synopsisBudgetBytes < 0L) {
			throw new IllegalArgumentException("Frontier synopsis budget must be nonnegative");
		}
		Objects.requireNonNull(snapshotSourceFactory, "snapshotSourceFactory");
		Objects.requireNonNull(fileOps, "fileOps");
		if (synopsisBudgetBytes == 0L) {
			this.frontierDirectory = null;
			this.fileOps = null;
			this.buildContext = null;
			status = FrontierSynopsisStatus.DISABLED_ZERO_BUDGET;
			return;
		}
		throw new UnsupportedOperationException("Positive-budget Frontier persistence is not initialized");
	}

	LmdbFrontierSynopsisService(Path frontierDirectory, FrontierEstimatorMode mode,
			FrontierManifestIdentity expectedIdentity, FrontierSnapshotSourceFactory snapshotSourceFactory,
			FrontierFileOps fileOps) {
		Path normalizedDirectory = Objects.requireNonNull(frontierDirectory, "frontierDirectory")
				.toAbsolutePath()
				.normalize();
		Objects.requireNonNull(mode, "mode");
		Objects.requireNonNull(expectedIdentity, "expectedIdentity");
		Objects.requireNonNull(snapshotSourceFactory, "snapshotSourceFactory");
		Objects.requireNonNull(fileOps, "fileOps");

		if (mode == FrontierEstimatorMode.OFF) {
			this.frontierDirectory = null;
			this.fileOps = null;
			this.buildContext = null;
			status = FrontierSynopsisStatus.DISABLED_MODE;
			return;
		}
		long synopsisBudgetBytes = expectedIdentity.configuredBudgetBytes();
		if (synopsisBudgetBytes == 0L) {
			this.frontierDirectory = null;
			this.fileOps = null;
			this.buildContext = null;
			status = FrontierSynopsisStatus.DISABLED_ZERO_BUDGET;
			return;
		}
		this.frontierDirectory = normalizedDirectory;
		this.fileOps = fileOps;
		this.buildContext = new BuildContext(
				expectedIdentity.storeId(),
				synopsisBudgetBytes,
				synopsisBudgetBytes,
				expectedIdentity.designLaneCount(),
				expectedIdentity.auditLaneCount(),
				snapshotSourceFactory);
		status = bootstrap(normalizedDirectory, synopsisBudgetBytes, expectedIdentity, snapshotSourceFactory, fileOps);
		if (status == FrontierSynopsisStatus.READY) {
			try {
				initializeQueryIndexIfReady(new FrontierManifestStore(normalizedDirectory, fileOps).load());
			} catch (IOException ignored) {
				queryIndexFailureReason = "query_index_build_failed";
			}
		}
	}

	public FrontierSynopsisStatus status() {
		return status;
	}

	/** Returns the in-process generation of Frontier availability and mapped evidence used during planning. */
	public long planningRevision() {
		return planningRevision.get();
	}

	/**
	 * Retains the immutable mapped query view matching one LMDB read snapshot.
	 */
	public FrontierQueryIndexLease acquireQueryIndex(long requiredSnapshotEpoch) {
		if (requiredSnapshotEpoch < 0L) {
			throw new IllegalArgumentException("requiredSnapshotEpoch must be nonnegative");
		}
		for (;;) {
			FrontierSynopsisStatus currentStatus = status;
			if (currentStatus != FrontierSynopsisStatus.READY) {
				return FrontierQueryIndexLease.unavailable(
						currentStatus, "query_index_unavailable", requiredSnapshotEpoch);
			}
			FrontierQueryIndexView candidate = queryIndexView;
			if (candidate == null) {
				return FrontierQueryIndexLease.unavailable(
						currentStatus, queryIndexFailureReason, requiredSnapshotEpoch);
			}
			if (candidate.snapshotEpoch() != requiredSnapshotEpoch) {
				return FrontierQueryIndexLease.unavailable(
						FrontierSynopsisStatus.EPOCH_MISMATCH,
						"query_index_epoch_mismatch",
						requiredSnapshotEpoch);
			}
			if (!candidate.tryRetain()) {
				continue;
			}
			if (candidate == queryIndexView && status == FrontierSynopsisStatus.READY) {
				return FrontierQueryIndexLease.ready(candidate);
			}
			candidate.release();
		}
	}

	/**
	 * Streams one compatible generation through bounded payload blocks.
	 *
	 * <p>
	 * The required epoch must be the native epoch of the exact LMDB read transaction that will execute the query.
	 * Records are validated before delivery, but remain provisional until this method returns {@code READY}, because
	 * the whole-file digest is verified only after the final block.
	 * </p>
	 *
	 * @param requiredSnapshotEpoch exact query snapshot epoch
	 * @param sink                  validated primitive-record consumer
	 * @return stable scan classification and manifest identity
	 */
	public synchronized FrontierSynopsisReadResult scanSnapshot(long requiredSnapshotEpoch,
			FrontierSynopsisRecordSink sink) {
		if (requiredSnapshotEpoch < 0L) {
			throw new IllegalArgumentException("requiredSnapshotEpoch must be nonnegative");
		}
		Objects.requireNonNull(sink, "sink");
		if (status != FrontierSynopsisStatus.READY || buildContext == null) {
			return unavailableRead(status, requiredSnapshotEpoch, 0L);
		}

		FrontierManifest manifest;
		try {
			manifest = new FrontierManifestStore(frontierDirectory, fileOps).load();
			manifest.identity().requireCompatible(expectedIdentity(manifest.identity().snapshotEpoch()));
		} catch (FrontierManifestException e) {
			publishStatus(e.status());
			return unavailableRead(status, requiredSnapshotEpoch, 0L);
		} catch (IOException e) {
			publishStatus(FrontierSynopsisStatus.CORRUPT);
			return unavailableRead(status, requiredSnapshotEpoch, 0L);
		}
		FrontierManifestIdentity identity = manifest.identity();
		if (identity.snapshotEpoch() != requiredSnapshotEpoch) {
			return readResult(FrontierSynopsisStatus.EPOCH_MISMATCH, identity, 0L);
		}

		ReadAccumulator accumulator = new ReadAccumulator();
		try {
			streamPayload(manifest, sink, accumulator);
			return readResult(FrontierSynopsisStatus.READY, identity, accumulator);
		} catch (FrontierPayloadException e) {
			publishStatus(e.status());
			return readResult(status, identity, accumulator);
		} catch (IOException e) {
			publishStatus(FrontierSynopsisStatus.CORRUPT);
			return readResult(status, identity, accumulator);
		}
	}

	/**
	 * Rebuilds and atomically publishes one base generation from an independently pinned LMDB snapshot.
	 *
	 * @return the resulting stable availability classification
	 */
	public synchronized FrontierSynopsisStatus rebuild() {
		if (buildContext == null) {
			return status;
		}
		if (buildContext.storeId() == null) {
			publishStatus(FrontierSynopsisStatus.STORE_MISMATCH);
			return status;
		}
		try (FrontierSnapshotSource snapshot = buildContext.snapshotSourceFactory().open()) {
			long snapshotEpoch = snapshot.snapshotEpoch();
			long generation = snapshotEpoch == 0L ? 1L : snapshotEpoch;
			FrontierManifestIdentity identity = new FrontierManifestIdentity(
					buildContext.storeId(),
					snapshotEpoch,
					SYNOPSIS_SCHEMA_VERSION,
					HASH_VERSION,
					SEED_SCHEDULE_VERSION,
					buildContext.designLaneCount(),
					buildContext.auditLaneCount(),
					FrontierManifestIdentity.ALL_DIRECTIONS,
					FrontierManifestIdentity.ALL_LANE_ROLES,
					buildContext.synopsisBudgetBytes());
			FrontierPayloadDescriptor descriptor = FrontierSynopsisBuilder.build(
					frontierDirectory,
					generation,
					buildContext.synopsisBudgetBytes(),
					buildContext.designLaneCount(),
					buildContext.auditLaneCount(),
					snapshot,
					fileOps);
			if (snapshot.snapshotEpoch() != snapshotEpoch) {
				publishStatus(FrontierSynopsisStatus.EPOCH_MISMATCH);
				return status;
			}
			FrontierManifest manifest = new FrontierManifest(generation, identity, descriptor);
			new FrontierManifestStore(frontierDirectory, fileOps).publish(manifest);
			refreshQueryIndex(manifest);
			/*
			 * The in-process status becomes READY before the durable dirty markers disappear: an observer keying on a
			 * vanished marker must never see a stale dirty status, while a crash between the two merely leaves a marker
			 * that triggers one redundant coalesced rebuild.
			 */
			publishStatus(FrontierSynopsisStatus.READY);
			fileOps.deleteIfExists(frontierDirectory.resolve(DIRTY_MARKER_FILE));
			fileOps.deleteIfExists(frontierDirectory.resolve(INSERTION_MARKER_FILE));
			fileOps.forceDirectory(frontierDirectory);
		} catch (FrontierSnapshotInvalidatedException e) {
			publishStatus(FrontierSynopsisStatus.EPOCH_MISMATCH);
		} catch (FrontierPayloadException e) {
			publishStatus(e.status());
		} catch (IOException | RuntimeException e) {
			publishStatus(FrontierSynopsisStatus.CORRUPT);
		}
		return status;
	}

	/**
	 * Durably invalidates sampled Frontier evidence before a deletion transaction may commit.
	 *
	 * <p>
	 * Deletions cannot be subtracted from the nonnegative sampled measure without a signed estimator. Once a clean
	 * generation is ready, the owning LMDB store must call this method before publishing any deletion. Failure to force
	 * the marker is reported to the caller so the storage transaction can fail closed.
	 * </p>
	 */
	public synchronized void invalidateForDeletion() throws IOException {
		if (status != FrontierSynopsisStatus.READY
				&& status != FrontierSynopsisStatus.DIRTY_INSERTION
				&& status != FrontierSynopsisStatus.BUDGET_EXCEEDED) {
			return;
		}
		persistDirtyMarker(DIRTY_MARKER_TEMPORARY_FILE, DIRTY_MARKER_FILE,
				FrontierSynopsisStatus.DIRTY_DELETION);
		pendingInsertions = null;
		pendingInsertionsOverflowed = false;
		insertionMarkerOwnedByCurrentTransaction = false;
		fileOps.deleteIfExists(frontierDirectory.resolve(INSERTION_MARKER_FILE));
		fileOps.forceDirectory(frontierDirectory);
	}

	/**
	 * Durably marks and retains one exact insertion before its transaction may commit.
	 */
	public synchronized void recordInsertion(FrontierInsertion insertion) throws IOException {
		Objects.requireNonNull(insertion, "insertion");
		if (status == FrontierSynopsisStatus.READY) {
			persistDirtyMarker(INSERTION_MARKER_TEMPORARY_FILE, INSERTION_MARKER_FILE,
					FrontierSynopsisStatus.DIRTY_INSERTION);
			insertionMarkerOwnedByCurrentTransaction = true;
		}
		if (status != FrontierSynopsisStatus.DIRTY_INSERTION || !insertionMarkerOwnedByCurrentTransaction
				|| pendingInsertionsOverflowed) {
			return;
		}
		int maximumInsertions = maximumPendingInsertions();
		if (pendingInsertions == null) {
			pendingInsertions = new ArrayList<>(Math.min(maximumInsertions, 256));
		}
		if (pendingInsertions.size() >= maximumInsertions) {
			pendingInsertions = null;
			pendingInsertionsOverflowed = true;
			return;
		}
		pendingInsertions.add(insertion);
	}

	/**
	 * Publishes the exact insert payload selected by the newest committed LMDB epoch.
	 *
	 * <p>
	 * Failure leaves the durable insertion marker in place. The LMDB commit is already authoritative at this point, so
	 * publication failures cannot be reported as transaction failures.
	 * </p>
	 */
	public synchronized FrontierSynopsisStatus completeInsertionCommit() {
		if (status != FrontierSynopsisStatus.DIRTY_INSERTION || !insertionMarkerOwnedByCurrentTransaction) {
			clearPendingInsertions();
			return status;
		}
		if (pendingInsertionsOverflowed || pendingInsertions == null || pendingInsertions.isEmpty()
				|| buildContext == null) {
			clearPendingInsertions();
			return status;
		}
		List<FrontierInsertion> committedInsertions = List.copyOf(pendingInsertions);
		try {
			FrontierManifestStore manifestStore = new FrontierManifestStore(frontierDirectory, fileOps);
			FrontierManifest previous = manifestStore.load();
			previous.identity().requireCompatible(expectedIdentity(previous.identity().snapshotEpoch()));
			if (previous.insertPayloads().size() >= MAXIMUM_EXACT_INSERT_GENERATIONS) {
				/*
				 * Keep the durable insertion marker and let the next supported authoritative planning session
				 * consolidate the committed store into one base generation. This bounds manifest publication, fsync,
				 * open-file, and read-amplification costs independently of commit count.
				 */
				return status;
			}
			long usedBytes = payloadBytes(previous);
			long remainingBytes = Math.subtractExact(buildContext.synopsisBudgetBytes(), usedBytes);
			try (FrontierSnapshotSource snapshot = buildContext.snapshotSourceFactory().open()) {
				long snapshotEpoch = snapshot.snapshotEpoch();
				long previousPayloadGeneration = previous.insertPayloads().isEmpty()
						? previous.payload().generation()
						: previous.insertPayloads().getLast().generation();
				if (snapshotEpoch <= previous.identity().snapshotEpoch()
						|| snapshotEpoch <= previousPayloadGeneration) {
					throw new FrontierSnapshotInvalidatedException(
							previous.identity().snapshotEpoch(), snapshotEpoch, previousPayloadGeneration,
							snapshotEpoch);
				}
				FrontierPayloadDescriptor insert = FrontierInsertGenerationBuilder.build(
						frontierDirectory,
						snapshotEpoch,
						remainingBytes,
						buildContext.designLaneCount(),
						buildContext.auditLaneCount(),
						committedInsertions,
						snapshot,
						fileOps);
				if (snapshot.snapshotEpoch() != snapshotEpoch) {
					throw new FrontierSnapshotInvalidatedException(snapshotEpoch, snapshot.snapshotEpoch(),
							snapshotEpoch, snapshot.snapshotEpoch());
				}
				ArrayList<FrontierPayloadDescriptor> inserts = new ArrayList<>(previous.insertPayloads());
				inserts.add(insert);
				FrontierManifestIdentity identity = expectedIdentity(snapshotEpoch);
				FrontierManifest manifest = new FrontierManifest(
						snapshotEpoch, identity, previous.payload(), inserts);
				manifestStore.publish(manifest);
				refreshQueryIndex(manifest);
			}
			/*
			 * READY becomes visible before the durable insertion marker disappears so a marker-gone observation can
			 * never coexist with a stale dirty status; a crash between the two just repeats one coalesced rebuild.
			 */
			publishStatus(FrontierSynopsisStatus.READY);
			fileOps.deleteIfExists(frontierDirectory.resolve(INSERTION_MARKER_FILE));
			fileOps.forceDirectory(frontierDirectory);
		} catch (FrontierManifestException e) {
			publishStatus(e.status() == FrontierSynopsisStatus.BUDGET_EXCEEDED
					? FrontierSynopsisStatus.BUDGET_EXCEEDED
					: FrontierSynopsisStatus.DIRTY_INSERTION);
		} catch (FrontierPayloadException e) {
			publishStatus(e.status() == FrontierSynopsisStatus.BUDGET_EXCEEDED
					? FrontierSynopsisStatus.BUDGET_EXCEEDED
					: FrontierSynopsisStatus.DIRTY_INSERTION);
		} catch (IOException | RuntimeException e) {
			publishStatus(FrontierSynopsisStatus.DIRTY_INSERTION);
		} finally {
			clearPendingInsertions();
		}
		return status;
	}

	/** Clears transaction-local insert rows after an LMDB rollback and restores a still-valid clean manifest. */
	public synchronized void discardInsertionTransaction() {
		if (!insertionMarkerOwnedByCurrentTransaction) {
			clearPendingInsertions();
			return;
		}
		try {
			fileOps.deleteIfExists(frontierDirectory.resolve(INSERTION_MARKER_FILE));
			fileOps.forceDirectory(frontierDirectory);
			publishStatus(FrontierSynopsisStatus.READY);
		} catch (IOException e) {
			publishStatus(FrontierSynopsisStatus.DIRTY_INSERTION);
		} finally {
			clearPendingInsertions();
		}
	}

	private void persistDirtyMarker(String temporaryFileName, String fileName, FrontierSynopsisStatus dirtyStatus)
			throws IOException {
		Path temporaryMarker = frontierDirectory.resolve(temporaryFileName);
		Path marker = frontierDirectory.resolve(fileName);
		byte[] encoded = ByteBuffer.allocate(2 * Integer.BYTES)
				.putInt(DIRTY_MARKER_MAGIC)
				.putInt(DIRTY_MARKER_VERSION)
				.array();
		boolean replaced = false;
		try {
			fileOps.createDirectories(frontierDirectory);
			fileOps.writeAndForce(temporaryMarker, encoded);
			fileOps.moveAtomically(temporaryMarker, marker);
			replaced = true;
			fileOps.forceDirectory(frontierDirectory);
			publishStatus(dirtyStatus);
		} finally {
			if (!replaced) {
				fileOps.deleteIfExists(temporaryMarker);
			}
		}
	}

	private int maximumPendingInsertions() {
		long laneCopies = Math.multiplyExact(2L,
				Math.addExact(buildContext.designLaneCount(), buildContext.auditLaneCount()));
		long retainedBytesPerInsertion = Math.multiplyExact(
				laneCopies, FrontierSynopsisBuilder.RECORD_LONGS * Long.BYTES);
		long budgetBound = Math.max(1L, Math.min(Integer.MAX_VALUE,
				buildContext.synopsisBudgetBytes() / retainedBytesPerInsertion));
		int singleBlockBound = FrontierInsertGenerationBuilder.maximumSingleBlockInsertions(
				buildContext.designLaneCount(), buildContext.auditLaneCount());
		return (int) Math.min(budgetBound, singleBlockBound);
	}

	private static long payloadBytes(FrontierManifest manifest) throws FrontierPayloadException {
		long bytes = 0L;
		try {
			for (FrontierPayloadDescriptor payload : manifest.payloads()) {
				bytes = Math.addExact(bytes, payload.byteLength());
			}
			return bytes;
		} catch (ArithmeticException e) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.BUDGET_EXCEEDED, "Frontier payload byte total overflowed");
		}
	}

	private void clearPendingInsertions() {
		pendingInsertions = null;
		pendingInsertionsOverflowed = false;
		insertionMarkerOwnedByCurrentTransaction = false;
	}

	@Override
	public void close() {
		replaceQueryIndex(null, "query_index_unavailable");
	}

	private void initializeQueryIndexIfReady(FrontierManifest manifest) {
		if (status == FrontierSynopsisStatus.READY) {
			refreshQueryIndex(manifest);
		}
	}

	private void refreshQueryIndex(FrontierManifest manifest) {
		if (buildContext == null || buildContext.queryIndexBudgetBytes() == 0L) {
			replaceQueryIndex(null, "query_index_unavailable");
			return;
		}
		ArrayList<FrontierQueryIndex> indexes = new ArrayList<>(manifest.payloads().size());
		long remainingIndexBytes = buildContext.queryIndexBudgetBytes();
		long remainingPayloadBytes = buildContext.synopsisBudgetBytes();
		try {
			for (FrontierPayloadDescriptor descriptor : manifest.payloads()) {
				FrontierQueryIndex index;
				try {
					index = FrontierQueryIndex.open(
							frontierDirectory, manifest.identity(), descriptor, remainingIndexBytes, fileOps);
				} catch (IOException invalidOrMissing) {
					FrontierQueryIndex.Builder builder = FrontierQueryIndex.builder(
							frontierDirectory, manifest.identity(), descriptor, remainingIndexBytes, fileOps);
					ReadAccumulator accumulator = new ReadAccumulator();
					streamPayload(
							descriptor,
							manifest.identity(),
							builder,
							accumulator,
							remainingPayloadBytes);
					index = builder.finish(accumulator.inclusionProbability, accumulator.databaseExact);
				}
				indexes.add(index);
				remainingIndexBytes = Math.subtractExact(remainingIndexBytes, index.byteLength());
				remainingPayloadBytes = Math.subtractExact(remainingPayloadBytes, descriptor.byteLength());
			}
			replaceQueryIndex(new FrontierQueryIndexView(manifest.identity(), indexes), "");
		} catch (IOException | RuntimeException failure) {
			closeQueryIndexes(indexes);
			replaceQueryIndex(null, "query_index_build_failed");
		}
	}

	private void replaceQueryIndex(FrontierQueryIndexView replacement, String failureReason) {
		FrontierQueryIndexView previous = queryIndexView;
		queryIndexView = replacement;
		queryIndexFailureReason = failureReason;
		planningRevision.incrementAndGet();
		if (previous != null) {
			previous.release();
		}
	}

	private void publishStatus(FrontierSynopsisStatus replacement) {
		status = Objects.requireNonNull(replacement, "replacement");
		planningRevision.incrementAndGet();
	}

	private static void closeQueryIndexes(List<FrontierQueryIndex> indexes) {
		for (FrontierQueryIndex index : indexes) {
			try {
				index.close();
			} catch (IOException ignored) {
				// A failed close cannot make a rejected derived index authoritative.
			}
		}
	}

	private static FrontierSynopsisStatus bootstrap(Path frontierDirectory, long synopsisBudgetBytes,
			FrontierManifestIdentity expectedIdentity, FrontierSnapshotSourceFactory snapshotSourceFactory,
			FrontierFileOps fileOps) {
		FrontierSynopsisStatus dirtyStatus = dirtyMarkerStatus(frontierDirectory, fileOps);
		if (dirtyStatus == FrontierSynopsisStatus.DIRTY_DELETION) {
			return dirtyStatus;
		}
		boolean dirtyInsertion = dirtyStatus == FrontierSynopsisStatus.DIRTY_INSERTION;
		FrontierManifest manifest;
		try {
			manifest = new FrontierManifestStore(frontierDirectory, fileOps).load();
		} catch (FrontierManifestException e) {
			return dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : e.status();
		} catch (IOException e) {
			return dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : FrontierSynopsisStatus.CORRUPT;
		}
		try {
			manifest.identity().requireCompatible(expectedIdentity);
		} catch (FrontierManifestException e) {
			return dirtyInsertion ? FrontierSynopsisStatus.DIRTY_INSERTION : e.status();
		}
		FrontierSynopsisStatus verified = verifyLoadedManifest(
				frontierDirectory, synopsisBudgetBytes, manifest, snapshotSourceFactory, fileOps);
		return dirtyInsertion ? recoverInsertionMarker(frontierDirectory, fileOps, verified) : verified;
	}

	private static FrontierSynopsisStatus dirtyMarkerStatus(Path frontierDirectory, FrontierFileOps fileOps) {
		try {
			if (fileOps.exists(frontierDirectory.resolve(DIRTY_MARKER_FILE))) {
				return FrontierSynopsisStatus.DIRTY_DELETION;
			}
			if (fileOps.exists(frontierDirectory.resolve(INSERTION_MARKER_FILE))) {
				return FrontierSynopsisStatus.DIRTY_INSERTION;
			}
			return null;
		} catch (IOException e) {
			return FrontierSynopsisStatus.CORRUPT;
		}
	}

	private static FrontierSynopsisStatus recoverInsertionMarker(Path frontierDirectory, FrontierFileOps fileOps,
			FrontierSynopsisStatus verifiedStatus) {
		if (verifiedStatus != FrontierSynopsisStatus.READY) {
			return FrontierSynopsisStatus.DIRTY_INSERTION;
		}
		try {
			fileOps.deleteIfExists(frontierDirectory.resolve(INSERTION_MARKER_FILE));
			fileOps.forceDirectory(frontierDirectory);
			return FrontierSynopsisStatus.READY;
		} catch (IOException e) {
			return FrontierSynopsisStatus.DIRTY_INSERTION;
		}
	}

	private static FrontierSynopsisStatus verifyLoadedManifest(Path frontierDirectory, long synopsisBudgetBytes,
			FrontierManifest manifest, FrontierSnapshotSourceFactory snapshotSourceFactory, FrontierFileOps fileOps) {
		try (FrontierSnapshotSource snapshot = snapshotSourceFactory.open()) {
			if (snapshot.snapshotEpoch() != manifest.identity().snapshotEpoch()) {
				return FrontierSynopsisStatus.EPOCH_MISMATCH;
			}
			long remainingBytes = synopsisBudgetBytes;
			for (FrontierPayloadDescriptor payload : manifest.payloads()) {
				if (payload.byteLength() > remainingBytes) {
					return FrontierSynopsisStatus.BUDGET_EXCEEDED;
				}
				FrontierSynopsisStatus payloadStatus = verifyPayload(
						frontierDirectory, remainingBytes, payload, fileOps);
				if (payloadStatus != FrontierSynopsisStatus.READY) {
					return payloadStatus;
				}
				remainingBytes -= payload.byteLength();
			}
			return FrontierSynopsisStatus.READY;
		} catch (FrontierSnapshotInvalidatedException e) {
			return FrontierSynopsisStatus.EPOCH_MISMATCH;
		} catch (FrontierPayloadException e) {
			return e.status();
		} catch (IOException e) {
			return FrontierSynopsisStatus.CORRUPT;
		}
	}

	private static FrontierSynopsisStatus verifyPayload(Path frontierDirectory, long synopsisBudgetBytes,
			FrontierPayloadDescriptor descriptor, FrontierFileOps fileOps) throws IOException {
		Path payloadPath = frontierDirectory.resolve(descriptor.fileName()).normalize();
		if (!frontierDirectory.equals(payloadPath.getParent())) {
			return FrontierSynopsisStatus.CORRUPT;
		}
		if (!fileOps.exists(payloadPath)) {
			return FrontierSynopsisStatus.MISSING;
		}
		if (descriptor.byteLength() > synopsisBudgetBytes) {
			return FrontierSynopsisStatus.BUDGET_EXCEEDED;
		}

		long payloadBytes = fileOps.size(payloadPath);
		if (payloadBytes < descriptor.byteLength()) {
			return FrontierSynopsisStatus.TRUNCATED;
		}
		if (payloadBytes > descriptor.byteLength()) {
			return FrontierSynopsisStatus.CORRUPT;
		}

		FrontierPayloadBlockLimits limits = validationLimits(synopsisBudgetBytes);
		try (InputStream input = fileOps.openInput(payloadPath)) {
			FrontierPayloadBlockReader reader = new FrontierPayloadBlockReader(input, descriptor, limits);
			while (reader.readBlock() != null) {
				// The reader validates and releases one bounded primitive block at a time.
			}
		}
		return FrontierSynopsisStatus.READY;
	}

	private FrontierManifestIdentity expectedIdentity(long snapshotEpoch) {
		return new FrontierManifestIdentity(
				buildContext.storeId(),
				snapshotEpoch,
				SYNOPSIS_SCHEMA_VERSION,
				HASH_VERSION,
				SEED_SCHEDULE_VERSION,
				buildContext.designLaneCount(),
				buildContext.auditLaneCount(),
				FrontierManifestIdentity.ALL_DIRECTIONS,
				FrontierManifestIdentity.ALL_LANE_ROLES,
				buildContext.synopsisBudgetBytes());
	}

	private void streamPayload(FrontierManifest manifest, FrontierSynopsisRecordSink sink,
			ReadAccumulator accumulator) throws IOException {
		long remainingBytes = buildContext.synopsisBudgetBytes();
		List<FrontierPayloadDescriptor> payloads = manifest.payloads();
		for (int index = 0; index < payloads.size(); index++) {
			FrontierPayloadDescriptor descriptor = payloads.get(index);
			if (descriptor.byteLength() > remainingBytes) {
				throw new FrontierPayloadException(
						FrontierSynopsisStatus.BUDGET_EXCEEDED,
						"Frontier payload generations exceed their configured budget");
			}
			streamPayload(descriptor, manifest.identity(), sink, accumulator, remainingBytes);
			remainingBytes -= descriptor.byteLength();
			if (index == 0 && accumulator.emptySnapshot && payloads.size() > 1) {
				accumulator.beginInsertPayloads();
			}
		}
	}

	private void streamPayload(FrontierPayloadDescriptor descriptor, FrontierManifestIdentity identity,
			FrontierSynopsisRecordSink sink, ReadAccumulator accumulator, long remainingBytes) throws IOException {
		Path payloadPath = frontierDirectory.resolve(descriptor.fileName()).normalize();
		if (!frontierDirectory.equals(payloadPath.getParent())) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.CORRUPT, "Frontier payload escaped its synopsis directory");
		}
		if (!fileOps.exists(payloadPath)) {
			throw new FrontierPayloadException(FrontierSynopsisStatus.MISSING, "Frontier payload is missing");
		}
		if (descriptor.byteLength() > remainingBytes) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.BUDGET_EXCEEDED,
					"Frontier payload exceeds its configured budget");
		}
		long payloadBytes = fileOps.size(payloadPath);
		if (payloadBytes < descriptor.byteLength()) {
			throw new FrontierPayloadException(FrontierSynopsisStatus.TRUNCATED, "Frontier payload is truncated");
		}
		if (payloadBytes > descriptor.byteLength()) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.CORRUPT, "Frontier payload has trailing durable bytes");
		}

		try (InputStream input = fileOps.openInput(payloadPath)) {
			FrontierPayloadBlockReader reader = new FrontierPayloadBlockReader(
					input, descriptor, validationLimits(remainingBytes));
			FrontierPayloadBlock block;
			while ((block = reader.readBlock()) != null) {
				deliverBlock(block, identity, descriptor.kind(), sink, accumulator);
			}
		}
	}

	private static void deliverBlock(FrontierPayloadBlock block, FrontierManifestIdentity identity,
			FrontierPayloadKind payloadKind, FrontierSynopsisRecordSink sink, ReadAccumulator accumulator)
			throws FrontierPayloadException {
		if (block.longsPerRecord() != FrontierSynopsisBuilder.RECORD_LONGS) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.VERSION_MISMATCH,
					"Unsupported Frontier synopsis record width: " + block.longsPerRecord());
		}
		long[] values = block.values();
		for (int offset = 0; offset < values.length; offset += FrontierSynopsisBuilder.RECORD_LONGS) {
			deliverRecord(values, offset, identity, payloadKind, sink, accumulator);
		}
	}

	private static void deliverRecord(long[] values, int offset, FrontierManifestIdentity identity,
			FrontierPayloadKind payloadKind, FrontierSynopsisRecordSink sink, ReadAccumulator accumulator)
			throws FrontierPayloadException {
		long recordVersion = values[offset];
		if (recordVersion != FrontierSynopsisBuilder.LEGACY_RECORD_FORMAT_VERSION
				&& recordVersion != FrontierSynopsisBuilder.RECORD_FORMAT_VERSION) {
			throw new FrontierPayloadException(
					FrontierSynopsisStatus.VERSION_MISMATCH,
					"Unsupported Frontier synopsis record version: " + recordVersion);
		}
		int direction = exactInt(values[offset + 1], "direction");
		int laneRole = exactInt(values[offset + 2], "lane role");
		int laneIndex = exactInt(values[offset + 3], "lane index");
		long flags = values[offset + 4];
		long knownFlags = FrontierSynopsisBuilder.FLAG_EXPLICIT
				| FrontierSynopsisBuilder.FLAG_DATABASE_EXACT
				| FrontierSynopsisBuilder.FLAG_EMPTY_SNAPSHOT
				| FrontierSynopsisBuilder.FLAG_SHARED_ACROSS_LANES;
		if ((flags & ~knownFlags) != 0L) {
			throw corruptRecord("unknown record flags");
		}
		boolean empty = (flags & FrontierSynopsisBuilder.FLAG_EMPTY_SNAPSHOT) != 0L;
		if (empty) {
			validateEmptyRecord(values, offset, direction, laneRole, laneIndex, flags, accumulator);
			return;
		}
		if (accumulator.emptySnapshot) {
			throw corruptRecord("empty marker was mixed with data records");
		}
		if (direction != FrontierManifestIdentity.SUBJECT_TO_OBJECT_DIRECTION
				&& direction != FrontierManifestIdentity.OBJECT_TO_SUBJECT_DIRECTION) {
			throw corruptRecord("unknown record direction");
		}
		boolean sharedAcrossLanes = (flags & FrontierSynopsisBuilder.FLAG_SHARED_ACROSS_LANES) != 0L;
		if (sharedAcrossLanes) {
			if (recordVersion != FrontierSynopsisBuilder.RECORD_FORMAT_VERSION
					|| laneRole != FrontierManifestIdentity.ALL_LANE_ROLES
					|| laneIndex != -1) {
				throw corruptRecord("invalid shared exact-lane record scope");
			}
		} else {
			if (laneRole != FrontierManifestIdentity.DESIGN_LANE_ROLE
					&& laneRole != FrontierManifestIdentity.AUDIT_LANE_ROLE) {
				throw corruptRecord("unknown lane role");
			}
			int laneCount = laneRole == FrontierManifestIdentity.DESIGN_LANE_ROLE
					? identity.designLaneCount()
					: identity.auditLaneCount();
			if (laneIndex < 0 || laneIndex >= laneCount) {
				throw corruptRecord("lane index is outside its manifest lane family");
			}
		}
		long center = values[offset + 5];
		long predicate = values[offset + 6];
		long neighbor = values[offset + 7];
		long context = values[offset + 8];
		if (center <= 0L || predicate <= 0L || neighbor <= 0L || context < 0L) {
			throw corruptRecord("record contains an invalid exact LMDB term ID");
		}
		double weight = Double.longBitsToDouble(values[offset + 9]);
		double inclusionProbability = Double.longBitsToDouble(values[offset + 10]);
		if (!Double.isFinite(weight) || weight <= 0.0d
				|| !Double.isFinite(inclusionProbability)
				|| inclusionProbability <= 0.0d
				|| inclusionProbability > 1.0d
				|| Double.doubleToLongBits(weight) != Double.doubleToLongBits(1.0d / inclusionProbability)) {
			throw corruptRecord("record has inconsistent inclusion probability and weight");
		}
		boolean databaseExact = (flags & FrontierSynopsisBuilder.FLAG_DATABASE_EXACT) != 0L;
		if (databaseExact && (weight != 1.0d || inclusionProbability != 1.0d)) {
			throw corruptRecord("database-exact record has a sampled weight");
		}
		if (sharedAcrossLanes && !databaseExact) {
			throw corruptRecord("only database-exact records may be shared across lanes");
		}
		if (payloadKind == FrontierPayloadKind.INSERT && !databaseExact) {
			throw corruptRecord("insert payload contains sampled mass");
		}
		long laneHash = values[offset + 11];
		if (sharedAcrossLanes ? laneHash != 0L
				: laneHash != FrontierSynopsisBuilder.laneHash(center, laneRole, laneIndex)) {
			throw corruptRecord("record lane hash is inconsistent with its center and lane");
		}
		accumulator.observeDesign(inclusionProbability, databaseExact, payloadKind);
		boolean explicit = (flags & FrontierSynopsisBuilder.FLAG_EXPLICIT) != 0L;
		if (sharedAcrossLanes) {
			for (int index = 0; index < identity.designLaneCount(); index++) {
				deliverLane(sink, accumulator, direction, FrontierManifestIdentity.DESIGN_LANE_ROLE, index,
						explicit, center, predicate, neighbor, context);
			}
			for (int index = 0; index < identity.auditLaneCount(); index++) {
				deliverLane(sink, accumulator, direction, FrontierManifestIdentity.AUDIT_LANE_ROLE, index,
						explicit, center, predicate, neighbor, context);
			}
		} else {
			sink.accept(direction, laneRole, laneIndex, explicit, databaseExact, center, predicate, neighbor, context,
					weight, inclusionProbability, laneHash);
			accumulator.deliveredRecords = Math.incrementExact(accumulator.deliveredRecords);
		}
	}

	private static void deliverLane(FrontierSynopsisRecordSink sink, ReadAccumulator accumulator, int direction,
			int laneRole, int laneIndex, boolean explicit, long center, long predicate, long neighbor, long context) {
		sink.accept(direction, laneRole, laneIndex, explicit, true, center, predicate, neighbor, context,
				1.0d, 1.0d, FrontierSynopsisBuilder.laneHash(center, laneRole, laneIndex));
		accumulator.deliveredRecords = Math.incrementExact(accumulator.deliveredRecords);
	}

	private static void validateEmptyRecord(long[] values, int offset, int direction, int laneRole, int laneIndex,
			long flags, ReadAccumulator accumulator) throws FrontierPayloadException {
		if (accumulator.emptySnapshot || accumulator.deliveredRecords != 0L
				|| direction != FrontierManifestIdentity.SUBJECT_TO_OBJECT_DIRECTION
				|| laneRole != 1
				|| laneIndex != 0
				|| flags != (FrontierSynopsisBuilder.FLAG_DATABASE_EXACT
						| FrontierSynopsisBuilder.FLAG_EMPTY_SNAPSHOT)
				|| values[offset + 5] != 0L
				|| values[offset + 6] != 0L
				|| values[offset + 7] != 0L
				|| values[offset + 8] != 0L
				|| Double.longBitsToDouble(values[offset + 9]) != 0.0d
				|| Double.longBitsToDouble(values[offset + 10]) != 1.0d
				|| values[offset + 11] != 0L) {
			throw corruptRecord("invalid empty-snapshot record");
		}
		accumulator.emptySnapshot = true;
		accumulator.observeDesign(1.0d, true, FrontierPayloadKind.BASE);
	}

	private static int exactInt(long value, String field) throws FrontierPayloadException {
		if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
			throw corruptRecord("record " + field + " is outside the integer range");
		}
		return (int) value;
	}

	private static FrontierPayloadException corruptRecord(String message) {
		return new FrontierPayloadException(FrontierSynopsisStatus.CORRUPT, "Frontier synopsis " + message);
	}

	private static FrontierSynopsisReadResult readResult(FrontierSynopsisStatus status,
			FrontierManifestIdentity identity, long records) {
		UUID storeId = identity.storeId();
		return new FrontierSynopsisReadResult(
				status,
				storeId.getMostSignificantBits(),
				storeId.getLeastSignificantBits(),
				identity.snapshotEpoch(),
				records,
				Double.NaN,
				false);
	}

	private static FrontierSynopsisReadResult readResult(FrontierSynopsisStatus status,
			FrontierManifestIdentity identity, ReadAccumulator accumulator) {
		UUID storeId = identity.storeId();
		return new FrontierSynopsisReadResult(
				status,
				storeId.getMostSignificantBits(),
				storeId.getLeastSignificantBits(),
				identity.snapshotEpoch(),
				accumulator.deliveredRecords,
				accumulator.inclusionProbability,
				accumulator.databaseExact);
	}

	private static FrontierSynopsisReadResult unavailableRead(FrontierSynopsisStatus status,
			long requiredSnapshotEpoch, long records) {
		return new FrontierSynopsisReadResult(
				status, 0L, 0L, requiredSnapshotEpoch, records, Double.NaN, false);
	}

	private static FrontierPayloadBlockLimits validationLimits(long synopsisBudgetBytes)
			throws FrontierPayloadException {
		if (synopsisBudgetBytes < FrontierPayloadBlockWriter.MINIMUM_BLOCK_BYTES) {
			throw new FrontierPayloadException(FrontierSynopsisStatus.BUDGET_EXCEEDED,
					"Frontier synopsis budget cannot contain one payload block");
		}
		int maximumBlockBytes = (int) Math.min(synopsisBudgetBytes, MAXIMUM_PAYLOAD_BLOCK_BYTES);
		int maximumValuesPerBlock = Math.max(1,
				(maximumBlockBytes - FrontierPayloadBlockWriter.MINIMUM_BLOCK_BYTES) / Long.BYTES);
		long maximumPayloadRecords = Math.max(1L, synopsisBudgetBytes / Long.BYTES);
		return new FrontierPayloadBlockLimits(
				synopsisBudgetBytes,
				maximumBlockBytes,
				maximumPayloadRecords,
				maximumValuesPerBlock,
				maximumValuesPerBlock);
	}

	private record BuildContext(
			UUID storeId,
			long synopsisBudgetBytes,
			long queryIndexBudgetBytes,
			int designLaneCount,
			int auditLaneCount,
			FrontierSnapshotSourceFactory snapshotSourceFactory) {

		private BuildContext {
			Objects.requireNonNull(snapshotSourceFactory, "snapshotSourceFactory");
			if (queryIndexBudgetBytes < 0L) {
				throw new IllegalArgumentException("Frontier query index budget must be nonnegative");
			}
		}
	}

	private static final class ReadAccumulator {
		private long deliveredRecords;
		private double inclusionProbability = Double.NaN;
		private boolean databaseExact;
		private boolean emptySnapshot;
		private boolean sawSampledBase;

		private void observeDesign(double probability, boolean exact, FrontierPayloadKind payloadKind)
				throws FrontierPayloadException {
			if (payloadKind == FrontierPayloadKind.INSERT) {
				if (!exact || probability != 1.0d) {
					throw corruptRecord("insert payload does not contain exact additive mass");
				}
				/*
				 * NaN means no sampling design has been observed yet, which is legitimate here: per-generation
				 * query-index builds stream one insert payload with a fresh accumulator, and a combined scan can reach
				 * the insert payloads after an empty base snapshot. Insert mass is exact by the check above, so an
				 * insert-initialized design is exact until a sampled base record overrides it.
				 */
				if (Double.isNaN(inclusionProbability)) {
					inclusionProbability = 1.0d;
					databaseExact = true;
				}
				return;
			}
			if (exact) {
				if (probability != 1.0d) {
					throw corruptRecord("exact-heavy base record has a sampled inclusion probability");
				}
				if (Double.isNaN(inclusionProbability)) {
					inclusionProbability = 1.0d;
					databaseExact = true;
				}
				return;
			}
			if (sawSampledBase
					&& Double.doubleToLongBits(inclusionProbability) != Double.doubleToLongBits(probability)) {
				throw corruptRecord("records disagree on their generation sampling design");
			}
			sawSampledBase = true;
			inclusionProbability = probability;
			databaseExact = false;
		}

		private void beginInsertPayloads() {
			emptySnapshot = false;
		}
	}
}
