/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
/// <reference path="template.ts" />
/// <reference path="jquery.d.ts" />
// Edit this TypeScript source and run compileTypescript.sh to regenerate JavaScript.
var workbench;
(function (workbench) {
    var savedQueries;
    (function (savedQueries) {
        var pages = new WeakMap();
        function confirmDeletion(savedBy, name, form) {
            var encoded = workbench.getCookie('server-user-password');
            var decoded = encoded && window.atob ? window.atob(encoded) : encoded;
            var currentUser = decoded && decoded.substring(0, decoded.indexOf(':'));
            if (!savedBy || currentUser === savedBy) {
                workbench.confirmDialog.open({
                    title: 'Delete saved query?',
                    body: "'" + name + "' will no longer be accessible, even using your browser's history.",
                    confirmLabel: 'Delete', danger: true
                }).then(function (confirmed) {
                    var target = confirmed && form();
                    if (target) {
                        workbench.submitForm(target);
                    }
                });
            }
            else {
                alert("'" + name + "' was saved by user '" + savedBy + "'.\nUser '"
                    + currentUser + "' is not allowed do delete it.");
            }
        }
        /** Legacy page callers; route actions additionally retain their actual form and mount. */
        function deleteQuery(savedBy, name, urn) {
            var form = document.forms.namedItem(urn);
            var owner = workbench.captureFormOwner(form);
            confirmDeletion(savedBy, name, function () { return owner.isCurrent() ? form : null; });
        }
        savedQueries.deleteQuery = deleteQuery;
        /** IDs are opaque saved-query URNs, so never interpolate them into CSS selectors. */
        function element(page, id) {
            var candidate = page.outlet.ownerDocument.getElementById(id);
            if (candidate && page.outlet.contains(candidate)) {
                return candidate;
            }
            var nodes = page.outlet.querySelectorAll('[id]');
            for (var index = 0; index < nodes.length; index++) {
                if (nodes[index].id === id) {
                    return nodes[index];
                }
            }
            return null;
        }
        function closeEditor(page, urn) {
            var editor = page.editors.get(urn);
            if (editor) {
                editor.instance.toTextArea();
                page.editors.delete(urn);
            }
        }
        function showDetails(page, urn, expanded) {
            var metadata = element(page, urn + '-metadata');
            var textarea = element(page, urn + '-text');
            var button = element(page, urn + '-toggle');
            if (!metadata || !textarea || !button) {
                return;
            }
            var previous = page.editors.get(urn);
            if (previous && previous.textarea !== textarea) {
                closeEditor(page, urn);
            }
            metadata.style.display = expanded ? '' : 'none';
            button.setAttribute('aria-expanded', expanded ? 'true' : 'false');
            button.textContent = expanded ? 'Hide details' : 'Show details';
            if (expanded) {
                page.expanded.add(urn);
                if (!page.editors.has(urn)) {
                    textarea.value = textarea.value.trim();
                    textarea.style.display = '';
                    var instance = YASQE.fromTextArea(textarea, { readOnly: 'nocursor', createShareLink: null });
                    page.editors.set(urn, { textarea: textarea, instance: instance });
                    $(instance.getWrapperElement()).css({ fontSize: '14px', height: 'auto' });
                    instance.refresh();
                }
            }
            else {
                page.expanded.delete(urn);
                closeEditor(page, urn);
                textarea.style.display = 'none';
            }
        }
        /** Show or hide details for legacy callers as well as delegated native button activation. */
        function toggle(urn) {
            var button = document.getElementById(urn + '-toggle');
            for (var parent_1 = button; parent_1; parent_1 = parent_1.parentNode) {
                var page = pages.get(parent_1);
                if (page && !page.disposed) {
                    showDetails(page, urn, !page.expanded.has(urn));
                    return;
                }
            }
        }
        savedQueries.toggle = toggle;
        /** Called after the virtual row renderer changes the visible cards. */
        function refresh(outlet) {
            var page = pages.get(outlet);
            if (!page || page.disposed) {
                return;
            }
            page.editors.forEach(function (editor, urn) {
                if (!outlet.contains(editor.textarea) || element(page, urn + '-text') !== editor.textarea) {
                    closeEditor(page, urn);
                }
            });
            var queries = outlet.getElementsByTagName('pre');
            for (var index = 0; index < queries.length; index++) {
                queries[index].innerHTML = queries[index].innerHTML.trim();
            }
            var inputs = outlet.querySelectorAll('[name="edit-query"] [name="query"]');
            for (var index = 0; index < inputs.length; index++) {
                var value = inputs[index].getAttribute('value');
                if (value !== null) {
                    inputs[index].setAttribute('value', value.trim());
                }
            }
            var buttons = outlet.querySelectorAll('.saved-query-toggle');
            for (var index = 0; index < buttons.length; index++) {
                var urn = buttons[index].getAttribute('data-query-urn');
                showDetails(page, urn, page.expanded.has(urn));
            }
        }
        savedQueries.refresh = refresh;
        /** One stable native listener serves current and future cards; disposal releases only this page's editors. */
        function mount(outlet) {
            var previous = pages.get(outlet);
            if (previous && previous.dispose) {
                previous.dispose();
            }
            var page = { outlet: outlet, editors: new Map(), expanded: new Set(), disposed: false };
            pages.set(outlet, page);
            var onClick = function (event) {
                var target = event.target;
                var button = target && target.closest
                    ? target.closest('.saved-query-toggle, .saved-query-delete') : null;
                if (!button || !outlet.contains(button) || page.disposed) {
                    return;
                }
                var urn = button.getAttribute('data-query-urn');
                if (button.classList.contains('saved-query-toggle')) {
                    showDetails(page, urn, !page.expanded.has(urn));
                }
                else {
                    var form_1 = element(page, urn);
                    confirmDeletion(button.getAttribute('data-query-owner'), button.getAttribute('data-query-name'), function () { return !page.disposed && outlet.contains(button) && form_1 && outlet.contains(form_1) ? form_1 : null; });
                }
            };
            outlet.addEventListener('click', onClick, false);
            refresh(outlet);
            page.dispose = function () {
                if (page.disposed) {
                    return;
                }
                page.disposed = true;
                outlet.removeEventListener('click', onClick, false);
                page.editors.forEach(function (_editor, urn) { return closeEditor(page, urn); });
                page.expanded.clear();
                if (pages.get(outlet) === page) {
                    pages.delete(outlet);
                }
            };
            return page.dispose;
        }
        savedQueries.mount = mount;
    })(savedQueries = workbench.savedQueries || (workbench.savedQueries = {}));
})(workbench || (workbench = {}));
//# sourceMappingURL=saved-queries.js.map