/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
/// <reference path="template.ts" />
/// <reference path="jquery.d.ts" />
// Edit this TypeScript source and run compileTypescript.sh to regenerate JavaScript.
var workbench;
(function (workbench) {
    var savedQueries;
    (function (savedQueries) {
        var pages = new WeakMap();
        /** A cookie's value, URI-decoded only (workbench.getCookie reads '+' as a space, a digit in base64). */
        function rawCookie(name) {
            var cookies = typeof document !== 'undefined' && typeof document.cookie === 'string'
                ? document.cookie.split(';') : [];
            for (var index = 0; index < cookies.length; index++) {
                var cookie = cookies[index].trim();
                var separator = cookie.indexOf('=');
                if (separator > 0 && cookie.substring(0, separator) === name) {
                    var value = cookie.substring(separator + 1);
                    try {
                        return decodeURIComponent(value);
                    }
                    catch (error) {
                        return value;
                    }
                }
            }
            return '';
        }
        /**
         * The text of the base64 server-user-password credentials: UTF-8 "user:password" (C15), or, for credentials
         * written one byte per character (an older Connection page), the bytes as they are. '' when it is no base64.
         */
        function decodeCredentials(encoded) {
            var view = typeof window !== 'undefined' ? window : null;
            if (!view || typeof view.atob !== 'function') {
                return encoded;
            }
            var binary;
            try {
                binary = view.atob(encoded);
            }
            catch (error) {
                return '';
            }
            try {
                var bytes = new Uint8Array(binary.length);
                for (var index = 0; index < binary.length; index++) {
                    bytes[index] = binary.charCodeAt(index);
                }
                return new TextDecoder('utf-8', { fatal: true }).decode(bytes);
            }
            catch (error) {
                return binary;
            }
        }
        function confirmDeletion(savedBy, name, form) {
            // The signed-in user as the server reads it: base64 "user:password" (raw: '+' is a base64 digit there).
            var encoded = rawCookie('server-user-password') || workbench.getCookie('server-user-password');
            var decoded = encoded ? decodeCredentials(encoded) : '';
            var colon = decoded ? decoded.indexOf(':') : -1;
            var user = colon >= 0 ? decoded.substring(0, colon) : decoded;
            var currentUser = user === '""' ? '' : user;
            if (!savedBy || currentUser === savedBy) {
                workbench.confirmDialog.open({
                    title: 'Delete saved query?',
                    body: "'" + name + "' will no longer be accessible, even using your browser's history.",
                    confirmLabel: 'Delete', danger: true
                }).then(function (confirmed) {
                    var target = confirmed && form();
                    if (target) {
                        workbench.submitForm(target);
                    }
                });
            }
            else {
                alert("'" + name + "' was saved by user '" + savedBy + "'.\nUser '"
                    + currentUser + "' is not allowed do delete it.");
            }
        }
        /** IDs are opaque saved-query URNs, so never interpolate them into CSS selectors. */
        function element(page, id) {
            var candidate = page.outlet.ownerDocument.getElementById(id);
            if (candidate && page.outlet.contains(candidate)) {
                return candidate;
            }
            var nodes = page.outlet.querySelectorAll('[id]');
            for (var index = 0; index < nodes.length; index++) {
                if (nodes[index].id === id) {
                    return nodes[index];
                }
            }
            return null;
        }
        function closeEditor(page, urn) {
            var editor = page.editors.get(urn);
            if (editor) {
                editor.instance.toTextArea();
                page.editors.delete(urn);
            }
        }
        function showDetails(page, urn, expanded) {
            var metadata = element(page, urn + '-metadata');
            var textarea = element(page, urn + '-text');
            var button = element(page, urn + '-toggle');
            if (!metadata || !textarea || !button) {
                return;
            }
            var previous = page.editors.get(urn);
            if (previous && previous.textarea !== textarea) {
                closeEditor(page, urn);
            }
            metadata.style.display = expanded ? '' : 'none';
            button.setAttribute('aria-expanded', expanded ? 'true' : 'false');
            // Refresh runs on every scroll: replacing the label of a pressed toggle would make WebKit drop the click.
            var label = expanded ? 'Hide details' : 'Show details';
            if (button.textContent !== label) {
                button.textContent = label;
            }
            if (expanded) {
                page.expanded.add(urn);
                if (!page.editors.has(urn)) {
                    textarea.value = textarea.value.trim();
                    textarea.style.display = '';
                    // A read-only query needs no completion: YASQE's default completers fetch prefix.cc and
                    // vocabulary services from the reader's browser. YASQE deep-merges its options into its
                    // defaults, which merges an empty list into the default one; null replaces it.
                    var instance = YASQE.fromTextArea(textarea, { readOnly: 'nocursor', createShareLink: null, autocompleters: null });
                    page.editors.set(urn, { textarea: textarea, instance: instance });
                    $(instance.getWrapperElement()).css({ fontSize: '14px', height: 'auto' });
                    instance.refresh();
                }
            }
            else {
                page.expanded.delete(urn);
                closeEditor(page, urn);
                textarea.style.display = 'none';
            }
        }
        /** Called after the virtual row renderer changes the visible cards. */
        function refresh(outlet) {
            var page = pages.get(outlet);
            if (!page || page.disposed) {
                return;
            }
            page.editors.forEach(function (editor, urn) {
                if (!outlet.contains(editor.textarea) || element(page, urn + '-text') !== editor.textarea) {
                    closeEditor(page, urn);
                }
            });
            var queries = outlet.getElementsByTagName('pre');
            for (var index = 0; index < queries.length; index++) {
                var query_1 = queries[index].innerHTML.trim();
                if (queries[index].innerHTML !== query_1) {
                    queries[index].innerHTML = query_1;
                }
            }
            var inputs = outlet.querySelectorAll('[name="edit-query"] [name="query"]');
            for (var index = 0; index < inputs.length; index++) {
                var value = inputs[index].getAttribute('value');
                if (value !== null) {
                    inputs[index].setAttribute('value', value.trim());
                }
            }
            var buttons = outlet.querySelectorAll('.saved-query-toggle');
            for (var index = 0; index < buttons.length; index++) {
                var urn = buttons[index].getAttribute('data-query-urn');
                showDetails(page, urn, page.expanded.has(urn));
            }
        }
        savedQueries.refresh = refresh;
        /** One stable native listener serves current and future cards; disposal releases only this page's editors. */
        function mount(outlet) {
            var previous = pages.get(outlet);
            if (previous && previous.dispose) {
                previous.dispose();
            }
            var page = { outlet: outlet, editors: new Map(), expanded: new Set(), disposed: false };
            pages.set(outlet, page);
            var onClick = function (event) {
                var target = event.target;
                var button = target && target.closest
                    ? target.closest('.saved-query-toggle, .saved-query-delete') : null;
                if (!button || !outlet.contains(button) || page.disposed) {
                    return;
                }
                var urn = button.getAttribute('data-query-urn');
                if (button.classList.contains('saved-query-toggle')) {
                    showDetails(page, urn, !page.expanded.has(urn));
                }
                else {
                    var form_1 = element(page, urn);
                    confirmDeletion(button.getAttribute('data-query-owner'), button.getAttribute('data-query-name'), function () { return !page.disposed && outlet.contains(button) && form_1 && outlet.contains(form_1) ? form_1 : null; });
                }
            };
            outlet.addEventListener('click', onClick, false);
            refresh(outlet);
            page.dispose = function () {
                if (page.disposed) {
                    return;
                }
                page.disposed = true;
                outlet.removeEventListener('click', onClick, false);
                page.editors.forEach(function (_editor, urn) { return closeEditor(page, urn); });
                page.expanded.clear();
                if (pages.get(outlet) === page) {
                    pages.delete(outlet);
                }
            };
            return page.dispose;
        }
        savedQueries.mount = mount;
    })(savedQueries = workbench.savedQueries || (workbench.savedQueries = {}));
})(workbench || (workbench = {}));
//# sourceMappingURL=saved-queries.js.map