/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.base;

import java.util.ArrayDeque;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.ReentrantLock;

/** Defers physical model disposal until all reader-sensitive locks and preparation reservations are released. */
final class SailModelCleanup {

	private static final ThreadLocal<State> CURRENT = ThreadLocal.withInitial(State::new);

	private SailModelCleanup() {
	}

	static Scope enter() {
		Scope scope = new Scope(CURRENT.get());
		beginLock();
		return scope;
	}

	static void beginLock() {
		CURRENT.get().holds++;
	}

	/** Intermediate unlocks must neither run delegate cleanup nor replace an in-flight failure. */
	static void endLock() {
		if (--CURRENT.get().holds < 0) {
			throw new IllegalStateException("Model cleanup suppression underflow");
		}
	}

	static void defer(SailClosable resource) {
		CURRENT.get().pending.addLast(resource);
	}

	private static final class State {
		private int holds;
		private boolean draining;
		private final ArrayDeque<SailClosable> pending = new ArrayDeque<>();

		private void drain() {
			if (holds != 0 || draining) {
				return;
			}
			draining = true;
			Throwable failure = null;
			try {
				while (!pending.isEmpty() && holds == 0) {
					try {
						pending.removeFirst().close();
					} catch (RuntimeException | Error closeFailure) {
						if (failure == null) {
							failure = closeFailure;
						} else if (failure != closeFailure) {
							failure.addSuppressed(closeFailure);
						}
					}
				}
			} finally {
				draining = false;
				if (holds == 0 && pending.isEmpty()) {
					CURRENT.remove();
				}
			}
			if (failure instanceof Error error) {
				throw error;
			}
			if (failure instanceof RuntimeException runtime) {
				throw runtime;
			}
		}
	}

	static final class Scope implements SailClosable {
		private final State state;
		private final Thread owner = Thread.currentThread();
		private boolean closed;

		private Scope(State state) {
			this.state = state;
		}

		@Override
		public void close() {
			if (Thread.currentThread() != owner) {
				throw new IllegalStateException("A cleanup scope must be released by its owner thread");
			}
			if (!closed) {
				closed = true;
				endLock();
				state.drain();
			}
		}
	}

	/** Physical hold accounting also follows the explicit all-hold continuation unlock/relock protocol. */
	static final class Lock extends ReentrantLock {
		private static final long serialVersionUID = 1L;

		@Override
		public void lock() {
			beginLock();
			try {
				super.lock();
			} catch (RuntimeException | Error failure) {
				endLock();
				throw failure;
			}
		}

		@Override
		public void lockInterruptibly() throws InterruptedException {
			beginLock();
			try {
				super.lockInterruptibly();
			} catch (InterruptedException | RuntimeException | Error failure) {
				endLock();
				throw failure;
			}
		}

		@Override
		public boolean tryLock() {
			beginLock();
			boolean acquired = false;
			try {
				return acquired = super.tryLock();
			} finally {
				if (!acquired) {
					endLock();
				}
			}
		}

		@Override
		public boolean tryLock(long timeout, TimeUnit unit) throws InterruptedException {
			beginLock();
			boolean acquired = false;
			try {
				return acquired = super.tryLock(timeout, unit);
			} finally {
				if (!acquired) {
					endLock();
				}
			}
		}

		@Override
		public void unlock() {
			super.unlock();
			endLock();
		}
	}
}
