/*******************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.base;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.eclipse.rdf4j.common.annotation.InternalUseOnly;
import org.eclipse.rdf4j.common.transaction.IsolationLevel;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.sail.SailConflictException;
import org.eclipse.rdf4j.sail.SailException;

/**
 * A persistent yet mutable source or container of RDF graphs. In which its state can change over time. The life cycle
 * follows that of a store and/or transactions. The {@link SailClosable#close()} is only applicable to results from
 * {@link #fork()}, not to the backing {@link SailSource} itself.
 *
 * @author James Leigh
 */
public interface SailSource extends SailClosable {

	/**
	 * Retains an ordered batch of logical changes until the caller confirms native commit. Each flush applies the
	 * complete batch again; it does not consume the retained input. The caller owns publication and commit.
	 */
	@InternalUseOnly
	default FlushBatch freezeForFlush() throws SailException {
		throw new UnsupportedOperationException("This source does not support retained flush batches");
	}

	/** A retained logical batch. Acknowledgement is valid only after confirmed backing commit. */
	@InternalUseOnly
	interface FlushBatch extends SailClosable {
		void flush() throws SailException;

		void unFreezeAndDiscardFlushed() throws SailException;

		/** Cancels freezing without acknowledging the pending logical changes. */
		@Override
		void close() throws SailException;
	}

	/**
	 * Discards this private source branch as part of replaying an operation whose results have not escaped.
	 * Implementors may release internal buffered changes without publishing them. This method must not be used for
	 * ordinary commit, rollback, or close lifecycle handling.
	 */
	@InternalUseOnly
	default void abandonUnobserved() throws SailException {
		close();
	}

	/**
	 * Retires an idle cached snapshot generation so subsequent readers acquire a fresh backing view. Existing dataset
	 * borrowers keep their generation until they close; this hook does not close the source branch or alter the
	 * ordinary close behavior of those borrowers.
	 */
	@InternalUseOnly
	default void retireIdleSnapshot() throws SailException {
	}

	/**
	 * Retires cached snapshot generations before a transaction prepares while preserving normal close semantics for
	 * existing borrowers. Active borrowers continue to own their generation until they release it.
	 */
	@InternalUseOnly
	default void retireSnapshotsPreservingBorrowers() throws SailException {
	}

	/**
	 * A dataset-admission scope that indicates whether its owner is responsible for retrying the complete acquisition.
	 */
	interface DatasetAcquisition extends SailClosable {
		/**
		 * @return {@code true} if closing this scope also unwinds the outermost acquisition
		 */
		boolean isOutermost();

		static DatasetAcquisition wrap(SailClosable delegate, boolean outermost) {
			return new DatasetAcquisition() {
				@Override
				public boolean isOutermost() {
					return outermost;
				}

				@Override
				public void close() throws SailException {
					delegate.close();
				}
			};
		}
	}

	/**
	 * A publication scope that can be explicitly aborted when work performed inside it fails. Composite sources must
	 * mark the shared scope before closing it so an earlier child cannot be committed after a later child fails.
	 */
	interface PublicationScope extends SailClosable {
		/** Marks the entire publication as failed. */
		void fail();
	}

	/** Ownership of buffered work, retained until that work is published or discarded. */
	@InternalUseOnly
	record WriteIntent(Object owner, SailClosable lease) implements SailClosable {
		@Override
		public void close() {
			lease.close();
		}
	}

	/** Resolves an internal descendant's owner before it mutates a buffer. */
	@InternalUseOnly
	default Object writeIntentOwner(Object requestedOwner) {
		return requestedOwner;
	}

	/** Registers logical write intent without acquiring a native writer or publishing any data. */
	@InternalUseOnly
	default WriteIntent beginWriteIntent(Object writeOwner) throws SailException {
		return null;
	}

	/** A snapshot of the logical write inputs used to reserve capacity before branch preparation. */
	@InternalUseOnly
	record WritePreflight(List<Statement> statements, List<NamespaceUpdate> addedNamespaces,
			Set<String> removedNamespacePrefixes, Set<Resource> clearedContexts, boolean statementCleared,
			boolean namespaceCleared) {
		public WritePreflight {
			statements = List.copyOf(statements);
			addedNamespaces = List.copyOf(addedNamespaces);
			removedNamespacePrefixes = Set.copyOf(removedNamespacePrefixes);
			clearedContexts = Collections.unmodifiableSet(new HashSet<>(clearedContexts));
		}

		static WritePreflight empty() {
			return new WritePreflight(List.of(), List.of(), Set.of(), Set.of(), false, false);
		}

		public WritePreflight merge(WritePreflight other) {
			List<Statement> mergedStatements = new ArrayList<>(statements);
			mergedStatements.addAll(other.statements);
			List<NamespaceUpdate> mergedNamespaces = new ArrayList<>(addedNamespaces);
			mergedNamespaces.addAll(other.addedNamespaces);
			Set<String> mergedRemovedPrefixes = new HashSet<>(removedNamespacePrefixes);
			mergedRemovedPrefixes.addAll(other.removedNamespacePrefixes);
			Set<Resource> mergedClearedContexts = new HashSet<>(clearedContexts);
			mergedClearedContexts.addAll(other.clearedContexts);
			return new WritePreflight(mergedStatements, mergedNamespaces, mergedRemovedPrefixes, mergedClearedContexts,
					statementCleared || other.statementCleared, namespaceCleared || other.namespaceCleared);
		}

		public boolean hasChanges() {
			return !statements.isEmpty() || !addedNamespaces.isEmpty() || !removedNamespacePrefixes.isEmpty()
					|| !clearedContexts.isEmpty() || statementCleared || namespaceCleared;
		}

		boolean contains(WritePreflight other) {
			return containsOccurrences(statements, other.statements)
					&& containsOccurrences(addedNamespaces, other.addedNamespaces)
					&& removedNamespacePrefixes.containsAll(other.removedNamespacePrefixes)
					&& clearedContexts.containsAll(other.clearedContexts)
					&& (!other.statementCleared || statementCleared) && (!other.namespaceCleared || namespaceCleared);
		}

		private static <T> boolean containsOccurrences(List<T> available, List<T> requested) {
			if (available.size() < requested.size()) {
				return false;
			}
			Map<T, Integer> remaining = new HashMap<>();
			for (T value : available) {
				remaining.merge(value, 1, Integer::sum);
			}
			for (T value : requested) {
				Integer count = remaining.get(value);
				if (count == null) {
					return false;
				}
				if (count == 1) {
					remaining.remove(value);
				} else {
					remaining.put(value, count - 1);
				}
			}
			return true;
		}

		public boolean hasOperationsWithoutAnExactEstimate() {
			return statementCleared || !clearedContexts.isEmpty() || namespaceCleared
					|| !removedNamespacePrefixes.isEmpty();
		}
	}

	/** A namespace value buffered for insertion. */
	@InternalUseOnly
	record NamespaceUpdate(String prefix, String name) {
	}

	/**
	 * Signals that the entire dataset acquisition must be retried after its owning admission scope has closed.
	 */
	final class RetryableDatasetAcquisitionException extends SailException {
		private static final long serialVersionUID = 1L;

		public RetryableDatasetAcquisitionException(String message) {
			super(message);
		}
	}

	static boolean isOutermostDatasetAcquisition(SailClosable scope) {
		return !(scope instanceof DatasetAcquisition acquisition) || acquisition.isOutermost();
	}

	/** Marks a publication scope as failed when the supplied scope supports coordinated rollback. */
	static void failPublication(SailClosable scope) {
		if (scope instanceof PublicationScope publication) {
			publication.fail();
		}
	}

	/**
	 * Creates a new branch of this source. When it's {@link #flush()} is called the changes are applied to this backing
	 * source.
	 *
	 * @return a branched {@link SailSource}.
	 */
	SailSource fork();

	/** Creates a private branch whose buffered writes share the supplied logical writer identity. */
	@InternalUseOnly
	default SailSource fork(Object writeOwner) {
		return fork();
	}

	/**
	 * Starts preflight for all buffered writes in this source before publication or prepared-write reservations are
	 * held. Composite sources propagate the request to their children; branches establish and retain their own
	 * estimate.
	 */
	@InternalUseOnly
	default void preflightWrite() throws SailException {
		preflightWrite(writePreflightEstimate());
	}

	/** Returns this source's buffered logical write inputs without beginning preflight. */
	@InternalUseOnly
	default WritePreflight writePreflightEstimate() {
		return WritePreflight.empty();
	}

	/**
	 * Indicates whether the current approximate buffered-write size is close enough to this source's native capacity to
	 * justify taking a complete write-preflight snapshot. The approximation is only an early-warning signal; a complete
	 * {@link WritePreflight} is still required before publication. Operations whose size cannot be estimated exactly
	 * are reported separately so implementations can start conservative preflight immediately.
	 */
	@InternalUseOnly
	default boolean shouldPreflightWrite(long approximateWriteBytes, boolean hasUnestimatedOperations) {
		return false;
	}

	/**
	 * Indicates whether this source wants buffered write intents estimated incrementally. Sources that do not use the
	 * advisory estimates avoid traversing or stringifying values while changes are buffered.
	 */
	@InternalUseOnly
	default boolean tracksWriteIntent() {
		return false;
	}

	/**
	 * Closes new top-level read admission for a bounded warning period, without draining readers or resizing a map.
	 * Implementations retain the returned scope until the write is prepared or abandoned.
	 */
	@InternalUseOnly
	default SailClosable beginWriteWarning() throws SailException {
		return () -> {
		};
	}

	/** A warning lease whose liveness is tied to one exact coordinator episode. */
	@InternalUseOnly
	interface WriteWarning extends SailClosable {
		boolean isActive();

		static WriteWarning inactive() {
			return new WriteWarning() {
				@Override
				public boolean isActive() {
					return false;
				}

				@Override
				public void close() {
				}
			};
		}
	}

	/** Starts an advisory warning for a stable logical writer identity. */
	@InternalUseOnly
	default WriteWarning beginWriteWarning(Object writeOwner) throws SailException {
		SailClosable warning = beginWriteWarning();
		return new WriteWarning() {
			@Override
			public boolean isActive() {
				return true;
			}

			@Override
			public void close() throws SailException {
				warning.close();
			}
		};
	}

	/** Identifies sources whose logical writes consume the same backing capacity. */
	@InternalUseOnly
	default Object writePreflightGroup() {
		return this;
	}

	/** Explicit opt-in; unknown implementations keep the complete legacy list-preflight protocol. */
	@InternalUseOnly
	default boolean supportsStreamingWritePreflight() {
		return false;
	}

	/** Backend-specific numeric demand. Implementations must not retain the input or any statements. */
	@InternalUseOnly
	interface NumericWriteEstimate {
		NumericWriteEstimate EMPTY = new NumericWriteEstimate() {
		};
	}

	@InternalUseOnly
	default NumericWriteEstimate estimateWritePreflight(StatementInput input) {
		return NumericWriteEstimate.EMPTY;
	}

	/** A physical forecast can be retired independently of its cached logical numeric estimate. */
	@InternalUseOnly
	interface WritePreflightScope extends SailClosable {
		boolean isActive();
	}

	/** Registers advisory demand only; must not acquire a writer, drain readers or resize synchronously. */
	@InternalUseOnly
	default WritePreflightScope beginWritePreflight(NumericWriteEstimate estimate, Object owner) {
		return new WritePreflightScope() {
			private volatile boolean active = true;

			@Override
			public boolean isActive() {
				return active;
			}

			@Override
			public void close() {
				active = false;
			}
		};
	}

	/** Retains logical ownership without acquiring a physical writer reservation. */
	@InternalUseOnly
	interface WriteOwner extends SailClosable {
		Object owner();
	}

	@InternalUseOnly
	default WriteOwner retainWriteOwner(Object requestedOwner) {
		return new WriteOwner() {
			@Override
			public Object owner() {
				return requestedOwner;
			}

			@Override
			public void close() {
			}
		};
	}

	/** Starts preflight for the supplied complete write estimate. */
	@InternalUseOnly
	default void preflightWrite(WritePreflight estimate) throws SailException {
	}

	/**
	 * Create a {@link SailSink} that when when its {@link #flush()} is called, the changes are applied to this source.
	 *
	 * @param level If this level is compatible with {@link IsolationLevels#SERIALIZABLE} then a
	 *              {@link SailSink#prepare()} can throw a {@link SailConflictException}.
	 * @return Newly created {@link SailSink}
	 * @throws SailException
	 */
	SailSink sink(IsolationLevel level) throws SailException;

	/**
	 * Create an observable {@link SailDataset} of the current state of this {@link SailSource}. Repeatedly calling with
	 * methods with {@link IsolationLevels#SNAPSHOT} (or higher) isolation levels will result in {@link SailDataset}s
	 * that are all derived from the same state of the backing {@link SailSource} (if applicable), that is the only
	 * difference between the states of the {@link SailDataset} will be from changes using this
	 * {@link #sink(IsolationLevel)}.
	 *
	 * @param level If this is compatible with {@link IsolationLevels#SNAPSHOT_READ} the resulting {@link SailDataset}
	 *              will observe a single state of this {@link SailSource}.
	 * @return an {@link SailDataset} of the current state
	 * @throws SailException
	 */
	SailDataset dataset(IsolationLevel level) throws SailException;

	/**
	 * Opens a scope for acquiring one or more datasets from this source as one read view. Composite sources use this to
	 * keep their child datasets on the same backing generation. Implementations that do not coordinate snapshots may
	 * use the default no-op scope.
	 *
	 * @param level the requested isolation level
	 * @return a scope that releases any resources reserved for this acquisition
	 * @throws SailException if the requested view cannot be acquired
	 */
	default SailClosable beginDatasetAcquisition(IsolationLevel level) throws SailException {
		return DatasetAcquisition.wrap(() -> {
		}, true);
	}

	/**
	 * Opens a scope around publication of one or more related backing changes. Composite sources use this to ensure
	 * that new readers do not observe only part of a multi-source publication. Implementations that do not coordinate
	 * publication may use the default no-op scope.
	 *
	 * @return a scope that completes the publication when closed
	 * @throws SailException if publication cannot be started
	 */
	default SailClosable beginPublication() throws SailException {
		return () -> {
		};
	}

	/** Coordinates branch bookkeeping within the exact dataset acquisition already admitted by the backing source. */
	@InternalUseOnly
	default SailClosable beginDatasetPublication() throws SailException {
		return beginPublication();
	}

	/** Starts publication under the supplied logical writer identity. */
	@InternalUseOnly
	default SailClosable beginPublication(Object writeOwner) throws SailException {
		return beginPublication();
	}

	/**
	 * Attempts to start publication without waiting for another writer. This is used by automatic flush during dataset
	 * or branch cleanup, where waiting for a prepared writer could prevent that writer from being released. A source
	 * that coordinates publication should return {@code null} when it cannot acquire publication immediately. The
	 * default implementation is a no-op scope for sources that do not coordinate publication.
	 *
	 * @return a publication scope, or {@code null} when publication is currently unavailable
	 * @throws SailException if publication cannot be started for another reason
	 */
	default SailClosable tryBeginPublication() throws SailException {
		return () -> {
		};
	}

	/** Attempts publication under the supplied logical writer identity. */
	@InternalUseOnly
	default SailClosable tryBeginPublication(Object writeOwner) throws SailException {
		return tryBeginPublication();
	}

	/**
	 * Reserves the backing source for a prepared write without opening a publication epoch. A source may retain this
	 * reservation from {@link SailSink#prepare()} until the prepared sink is flushed or closed. Implementations that do
	 * not need to reserve write ownership may use the default no-op scope.
	 *
	 * @return a scope that releases the prepared-write reservation
	 * @throws SailException if the reservation cannot be acquired
	 */
	default SailClosable beginPreparedWrite() throws SailException {
		return () -> {
		};
	}

	/** Reserves a prepared write under the supplied logical writer identity. */
	@InternalUseOnly
	default SailClosable beginPreparedWrite(Object writeOwner) throws SailException {
		return beginPreparedWrite();
	}

	/**
	 * Starts a preflight for a complete buffered write before publication or prepared-write reservations are held.
	 * Implementations may use additions, removals, namespace updates, and clear intents to estimate capacity required
	 * by the branch write. Sources that do not need preflight coordination may use the default no-op scope.
	 *
	 * @param approvedStatements the additions buffered by the branch
	 * @return a scope retained until the write is published or abandoned
	 * @throws SailException if the preflight cannot be established
	 */
	default SailClosable beginWritePreflight(List<Statement> approvedStatements) throws SailException {
		return () -> {
		};
	}

	/** Starts preflight with the complete logical write snapshot. */
	default SailClosable beginWritePreflight(WritePreflight writePreflight) throws SailException {
		return beginWritePreflight(writePreflight.statements());
	}

	/** Starts exact capacity preflight under the same logical writer identity as its advisory warning. */
	@InternalUseOnly
	default SailClosable beginWritePreflight(WritePreflight writePreflight, Object writeOwner) throws SailException {
		return beginWritePreflight(writePreflight);
	}

	/**
	 * Checks whether this source has uncommitted write changes that need preparation or publication.
	 *
	 * @return {@code true} if a prepared write reservation is needed
	 */
	default boolean hasPendingWriteChanges() {
		return false;
	}

	/**
	 * Checks whether a dataset still represents the latest committed generation visible through this source.
	 * Implementations may use an active publication scope on the calling thread to distinguish that scope's own
	 * in-progress generation from a committed change. Sources that cannot perform this check should use the dataset's
	 * default currentness signal.
	 *
	 * @param dataset the dataset to check
	 * @return {@code true} if the dataset is current
	 */
	default boolean isSnapshotCurrent(SailDataset dataset) {
		return dataset.isSnapshotCurrent();
	}

	/**
	 * Check the consistency of this branch and throws a {@link SailConflictException} if {@link #flush()}ing this
	 * branch would cause the backing {@link SailSource} to be inconsistent, if applicable. If this is the final backing
	 * {@link SailSource} calling this method has no effect.
	 *
	 * @throws SailException
	 */
	void prepare() throws SailException;

	/**
	 * Apply all the changes to this branch to the backing {@link SailSource}, if applicable. If this is the final
	 * backing {@link SailSource} calling this method has no effect.
	 *
	 * @throws SailException
	 */
	void flush() throws SailException;

}
