/*******************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.base;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.IdentityHashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.ReentrantLock;

import org.eclipse.rdf4j.common.iteration.QueryExecutionDeadline;
import org.eclipse.rdf4j.common.transaction.IsolationLevel;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.ModelFactory;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.DynamicModelFactory;
import org.eclipse.rdf4j.query.QueryInterruptedException;
import org.eclipse.rdf4j.sail.SailConflictException;
import org.eclipse.rdf4j.sail.SailException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * An {@link SailSource} that keeps a delta of its state from a backing {@link SailSource}.
 *
 * @author James Leigh
 */
class SailSourceBranch implements SailSource, FrozenFlush {

	private static final Logger logger = LoggerFactory.getLogger(SailSourceBranch.class);

	/**
	 * Used to prevent changes to this object's field from multiple threads.
	 */
	private final ReentrantLock semaphore = new SailModelCleanup.Lock();
	/** Signalled under {@code semaphore} when a suspended write continuation resumes. */
	private final Condition writesResumed = semaphore.newCondition();
	private final Map<Changeset, SailWriteContinuation.Scope> preparedContinuations = new IdentityHashMap<>();
	private int suspendedWrites;

	/**
	 * The difference between this {@link SailSource} and the backing {@link SailSource}.
	 */
	private final ArrayDeque<Changeset> changes = new ArrayDeque<>();
	private BranchFlushBatch frozenBatch;
	/** Leases transferred with shallow models; pending sinks retain their own leases until merge or close. */
	private final ArrayDeque<WriteIntent> bufferedWriteIntents = new ArrayDeque<>();

	/**
	 * {@link SailSink} that have been created, but not yet {@link SailSink#flush()}ed to this {@link SailSource}.
	 */
	private final Set<Changeset> pending = Collections
			.synchronizedSet(Collections.newSetFromMap(new IdentityHashMap<>()));

	/**
	 * Set of open {@link SailDataset} for this {@link SailSource}.
	 */
	private final Collection<SailDataset> observers = new ArrayList<>();

	/**
	 * The underly {@link SailSource} this {@link SailSource} is derived from.
	 */
	private final SailSource backingSource;
	private final Object writePreflightOwner;

	/**
	 * The {@link Model} instances that should be used to store {@link SailSink#approve(Resource, IRI, Value, Resource)}
	 * and {@link SailSink#deprecate(Statement)} statements.
	 */
	private final ModelFactory modelFactory;

	/**
	 * If this {@link SailSource} should be flushed to the backing {@link SailSource} when it is not in use.
	 */
	private final boolean autoFlush;
	private volatile boolean closed;
	private volatile boolean abandoned;
	private final AtomicInteger abandoningDatasets = new AtomicInteger();
	private final Object writePreflightLock = new Object();
	private WritePreflightRegistration writePreflight;
	private SailSource.WriteWarning writeWarning;
	private final StreamingWritePreflight streamingPreflight = new StreamingWritePreflight(this);

	/**
	 * Non-null when in {@link IsolationLevels#SNAPSHOT} (or higher) mode.
	 */
	private SnapshotLease snapshot;

	/** A shared admission for a snapshot generation being acquired outside {@code semaphore}. */
	private SnapshotAdmission snapshotAdmission;

	/** Incremented whenever the cached snapshot generation is retired. Guarded by {@code semaphore}. */
	private long snapshotGeneration;

	/**
	 * Snapshot generations borrowed by open observers. Identity keys ensure each observer releases its generation once;
	 * the map and all lease counts are guarded by {@code semaphore}.
	 */
	private final Map<SailDataset, SnapshotLease> observerSnapshots = new IdentityHashMap<>();

	/**
	 * Non-null when in {@link IsolationLevels#SERIALIZABLE} (or higher) mode.
	 */
	private SailSink serializable;
	/** Admission metadata belongs to the persistent validation role, never to an adopted statement generation. */
	private IsolationLevel serializableIsolationLevel;

	/**
	 * Non-null after {@link #prepare()}, but before {@link #flush()}.
	 */
	private SailSink prepared;
	private Map<Changeset, Long> preparedObservations;

	private record WritePreflightRegistration(SailSource.WritePreflight estimate, SailClosable scope) {
	}

	private static final class SnapshotLease {
		private final SailDataset dataset;
		private int borrowers;
		private boolean retired;
		private boolean closed;
		private boolean abandoned;

		private SnapshotLease(SailDataset dataset) {
			this.dataset = dataset;
		}
	}

	private static final class SnapshotAdmission {
		private final long generation;
		private final CountDownLatch completed = new CountDownLatch(1);
		private boolean invalidated;
		private Throwable failure;

		private SnapshotAdmission(long generation) {
			this.generation = generation;
		}
	}

	/**
	 * Creates a new in-memory {@link SailSource} derived from the given {@link SailSource}.
	 *
	 * @param backingSource
	 */
	public SailSourceBranch(SailSource backingSource) {
		this(backingSource, new DynamicModelFactory(), false);
	}

	/**
	 * Creates a new {@link SailSource} derived from the given {@link SailSource}.
	 *
	 * @param backingSource
	 * @param modelFactory
	 */
	public SailSourceBranch(SailSource backingSource, ModelFactory modelFactory) {
		this(backingSource, modelFactory, false);
	}

	/**
	 * Creates a new {@link SailSource} derived from the given {@link SailSource} and if <code>autoFlush</code> is true,
	 * will automatically call {@link #flush()} when not in use.
	 *
	 * @param backingSource
	 * @param modelFactory
	 * @param autoFlush
	 */
	public SailSourceBranch(SailSource backingSource, ModelFactory modelFactory, boolean autoFlush) {
		this(backingSource, modelFactory, autoFlush, null);
	}

	private SailSourceBranch(SailSource backingSource, ModelFactory modelFactory, boolean autoFlush,
			Object writePreflightOwner) {
		this.backingSource = backingSource;
		this.modelFactory = modelFactory;
		this.autoFlush = autoFlush;
		this.writePreflightOwner = writePreflightOwner;
	}

	@Override
	public void close() throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			Throwable failure = null;
			SailSink toCloseSerializable;
			SailSink toClosePrepared;
			SailClosable toClosePreflight;
			List<WriteIntent> discardedPendingIntents = new ArrayList<>();
			Set<Changeset> discardedChanges = Collections.newSetFromMap(new IdentityHashMap<>());
			semaphore.lock();
			try {
				awaitWriteResumption();
				if (closed) {
					return;
				}
				if (frozenBatch != null) {
					try {
						frozenBatch.close();
					} catch (RuntimeException | Error closeFailure) {
						failure = addFailure(failure, closeFailure);
					}
				}
				closed = true;
				try {
					retireSnapshot(abandoned);
				} catch (RuntimeException | Error retireFailure) {
					failure = addFailure(failure, retireFailure);
				}
				toCloseSerializable = serializable;
				serializable = null;
				serializableIsolationLevel = null;
				toClosePrepared = prepared;
				prepared = null;
				preparedObservations = null;
				toClosePreflight = detachWritePreflights();
				failure = closeBufferedWriteIntents(failure);
				for (Changeset change : pending) {
					WriteIntent intent = change.takeWriteIntent();
					if (intent != null) {
						discardedPendingIntents.add(intent);
					}
				}
				discardedChanges.addAll(changes);
				discardedChanges.addAll(pending);
				changes.clear();
				pending.clear();
			} finally {
				semaphore.unlock();
			}
			failure = closeResource(failure, toCloseSerializable);
			if (toClosePrepared != toCloseSerializable) {
				failure = closeResource(failure, toClosePrepared);
			}
			failure = closeResource(failure, toClosePreflight);
			for (Changeset discarded : discardedChanges) {
				failure = closeResource(failure, discarded);
			}
			for (WriteIntent intent : discardedPendingIntents) {
				failure = closeResource(failure, intent);
			}
			failure = closeResource(failure, streamingPreflight);
			if (failure != null) {
				rethrow(failure);
			}

		}
	}

	@Override
	public void abandonUnobserved() throws SailException {
		semaphore.lock();
		try {
			awaitWriteResumption();
			abandoned = true;
			for (SnapshotLease lease : observerSnapshots.values()) {
				lease.abandoned = true;
			}
		} finally {
			semaphore.unlock();
		}
		close();
	}

	@Override
	public void retireIdleSnapshot() throws SailException {
		List<SnapshotLease> toClose = new ArrayList<>();
		semaphore.lock();
		try {
			snapshotGeneration++;
			if (snapshotAdmission != null) {
				// Let the active admission finish outside the branch lock, but do not allow it to publish this
				// generation.
				snapshotAdmission.invalidated = true;
			}
			if (snapshot != null) {
				SnapshotLease cached = snapshot;
				snapshot = null;
				retireSnapshotForGrowth(cached, toClose);
			}
			// A prior branch flush can leave borrowed generations in this map after the current cache has moved on.
			// They
			// are still native views owned by this branch and must become abandonable after their final observer
			// releases.
			for (SnapshotLease borrowed : observerSnapshots.values()) {
				retireSnapshotForGrowth(borrowed, toClose);
			}
		} finally {
			semaphore.unlock();
		}

		Throwable failure = null;
		for (SnapshotLease lease : toClose) {
			try {
				closeSnapshotDataset(lease);
			} catch (RuntimeException | Error closeFailure) {
				failure = addFailure(failure, closeFailure);
			}
		}
		if (failure != null) {
			rethrow(failure);
		}
	}

	@Override
	public void retireSnapshotsPreservingBorrowers() throws SailException {
		List<SnapshotLease> toClose = new ArrayList<>();
		semaphore.lock();
		try {
			snapshotGeneration++;
			if (snapshotAdmission != null) {
				// Do not publish a candidate from the generation being retired.
				snapshotAdmission.invalidated = true;
			}
			if (snapshot != null) {
				SnapshotLease cached = snapshot;
				snapshot = null;
				retireSnapshotPreservingBorrowers(cached, toClose);
			}
			for (SnapshotLease borrowed : observerSnapshots.values()) {
				retireSnapshotPreservingBorrowers(borrowed, toClose);
			}
		} finally {
			semaphore.unlock();
		}

		Throwable failure = null;
		for (SnapshotLease lease : toClose) {
			try {
				closeSnapshotDataset(lease);
			} catch (RuntimeException | Error closeFailure) {
				failure = addFailure(failure, closeFailure);
			}
		}
		if (failure != null) {
			rethrow(failure);
		}
	}

	/** Marks one generation as retired and defers native dataset close until outside {@code semaphore}. */
	private void retireSnapshotForGrowth(SnapshotLease lease, List<SnapshotLease> toClose) {
		lease.retired = true;
		lease.abandoned = true;
		if (lease.borrowers == 0 && !lease.closed) {
			lease.closed = true;
			toClose.add(lease);
		}
	}

	/** Retires a generation without changing how its current borrowers release it. */
	private void retireSnapshotPreservingBorrowers(SnapshotLease lease, List<SnapshotLease> toClose) {
		lease.retired = true;
		if (lease.borrowers == 0 && !lease.closed) {
			lease.closed = true;
			toClose.add(lease);
		}
	}

	@Override
	public SailSink sink(IsolationLevel level) throws SailException {
		checkWriteContinuationAdmission();
		Changeset changeset = new Changeset() {

			private boolean prepared;
			private SailClosable preparedWrite;
			private SailModelCleanup.Retained preparedCleanup;
			private final Object fallbackWriteOwner = new Object();
			private volatile WriteIntent writeIntent;
			private Object admittedWriteOwner;
			private boolean sinkClosed;

			@Override
			protected void beforeWriteIntent() {
				if (!tracksWriteIntent() || writeIntent != null) {
					return;
				}
				checkWriteContinuationAdmission();
				Object owner = writeIntentOwner(fallbackWriteOwner);
				WriteIntent registration = backingSource.beginWriteIntent(owner);
				boolean retained = false;
				try {
					synchronized (this) {
						if (sinkClosed || SailSourceBranch.this.closed) {
							throw new SailException("SailSourceBranch sink is closed");
						}
						if (writeIntent == null) {
							writeIntent = registration;
							admittedWriteOwner = owner;
							retained = true;
						}
					}
				} finally {
					if (!retained && registration != null) {
						registration.close();
					}
				}
			}

			@Override
			protected synchronized WriteIntent takeWriteIntent() {
				WriteIntent result = writeIntent;
				writeIntent = null;
				return result;
			}

			private Object pendingWriteOwner() {
				return admittedWriteOwner == null ? writePreflightOwner : admittedWriteOwner;
			}

			@Override
			protected boolean tracksWriteIntent() {
				return backingSource.tracksWriteIntent();
			}

			@Override
			protected void writeIntentChanged() {
				SailSourceBranch.this.preflightBufferedWriteIfNeeded();
			}

			@Override
			public void prepare() throws SailException {
				try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter();
						SailClosable preflight = streamingPreflight.enter()) {
					try {
						if (prepared) {
							try (SailClosable publication = SailSourceBranch.this
									.beginPublication(pendingWriteOwner())) {
								StreamingWritePreflight.validate(SailSourceBranch.this);
								super.prepare();
							}
							return;
						}

						SailClosable reservation = null;
						SailModelCleanup.Retained retainedCleanup = null;
						boolean branchLockHeld = false;
						try {
							if (hasWriteChanges()) {
								// Snapshot all pending and already-flushed branch intents before acquiring either
								// prepared-write or
								// publication reservations. Growth coordination may need the branch's complete write
								// estimate.
								SailSourceBranch.this.ensureWritePreflight();
							}
							// Every prepared sink retains a branch lock until close, including observation-only
							// SERIALIZABLE
							// sinks. Keep its backing reservation for that lifetime so a competing publisher cannot own
							// the
							// backing writer while waiting for a lock the prepared owner needs to publish and release.
							retainedCleanup = SailModelCleanup.retain();
							reservation = SailSourceBranch.this.beginPreparedWrite(pendingWriteOwner());
							try (SailClosable publication = SailSourceBranch.this
									.beginPublication(pendingWriteOwner())) {
								StreamingWritePreflight.validate(SailSourceBranch.this);
								preparedChangeset(this);
								branchLockHeld = true;
								super.prepare();
							}
							prepared = true;
							preparedWrite = reservation;
							preparedCleanup = retainedCleanup;
							retainedCleanup = null;
							reservation = null;
						} catch (RuntimeException | Error prepareFailure) {
							StreamingWritePreflight.failed(SailSourceBranch.this, prepareFailure);
							Throwable failure = prepareFailure;
							if (branchLockHeld) {
								try {
									closeChangeset(this);
								} catch (RuntimeException | Error unlockFailure) {
									failure = addFailure(failure, unlockFailure);
								}
							}
							failure = closeResource(failure, reservation);
							failure = closeResource(failure, retainedCleanup);
							rethrow(failure);
						}
					} catch (RuntimeException | Error failure) {
						StreamingWritePreflight.failed(SailSourceBranch.this, failure);
						throw failure;
					}
				}
			}

			@Override
			public void flush() throws SailException {
				merge(this);
			}

			@Override
			public void releasePrepared() {
				try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
					Throwable failure = null;
					if (prepared) {
						prepared = false;
						try {
							closeChangeset(this);
						} catch (RuntimeException | Error releaseFailure) {
							failure = releaseFailure;
						}
					}
					SailClosable reservation = preparedWrite;
					preparedWrite = null;
					SailModelCleanup.Retained retainedCleanup = preparedCleanup;
					preparedCleanup = null;
					failure = closeResource(failure, reservation);
					failure = closeResource(failure, retainedCleanup);
					if (failure != null) {
						rethrow(failure);
					}
				}
			}

			@Override
			public void close() throws SailException {
				try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
					Throwable failure = null;
					synchronized (this) {
						sinkClosed = true;
					}
					try {
						// Reusable carriers retain intervening validation history until they close.
						if (pending.contains(this)) {
							removeThisFromPendingWithoutCausingDeadlock();
						}
					} catch (RuntimeException | Error closeFailure) {
						failure = closeFailure;
					}
					try {
						super.close();
					} catch (RuntimeException | Error closeFailure) {
						failure = addFailure(failure, closeFailure);
					}
					try {
						releasePrepared();
					} catch (RuntimeException | Error releaseFailure) {
						failure = addFailure(failure, releaseFailure);
					}
					failure = closeResource(failure, takeWriteIntent());
					try {
						autoFlush();
					} catch (RuntimeException | Error closeFailure) {
						failure = addFailure(failure, closeFailure);
					}
					if (failure != null) {
						rethrow(failure);
					}

				}
			}

			/**
			 * The outer SailSourceBranch could be in use in a SERIALIZABLE transaction, so we don't want to cause any
			 * deadlocks by taking the ´semaphore´ if ´this´ Changeset is already in the process of being removed from
			 * ´pending´.
			 */
			private void removeThisFromPendingWithoutCausingDeadlock() {
				long tryLockMillis = 10;
				boolean interrupted = false;
				while (pending.contains(this)) {
					boolean locked = false;
					try {
						try {
							locked = semaphore.tryLock(500, TimeUnit.MILLISECONDS);
						} catch (InterruptedException e) {
							interrupted = true;
							try {
								// retry once if interrupted
								locked = semaphore.tryLock(500, TimeUnit.MILLISECONDS);
								if (locked) {
									pending.remove(this);
									break;
								} else {
									if (pending.contains(this)) {
										throw new SailException(
												"Interrupted while trying to remove Changeset from pending list, giving up.",
												e);
									} else {
										// Changeset was removed from pending by another thread, so we can exit the loop
										break;
									}

								}
							} catch (InterruptedException e1) {
								if (pending.contains(this)) {
									throw new SailException(
											"Interrupted while trying to remove Changeset from pending list, giving up.",
											e1);
								} else {
									// Changeset was removed from pending by another thread, so we can exit the loop
									break;
								}
							}
						}
						if (locked) {
							pending.remove(this);
							break;
						}
					} finally {
						try {
							if (locked) {
								semaphore.unlock();
							}
						} finally {
							if (interrupted) {
								Thread.currentThread().interrupt();
							}
						}

					}

					tryLockMillis = Math.min(tryLockMillis * 2, 1000);
				}
			}

			@Override
			public Model createEmptyModel() {
				return modelFactory.createEmptyModel();
			}
		};
		changeset.setSinkIsolationLevel(level);
		try {
			semaphore.lock();
			if (closed) {
				throw new SailException("SailSourceBranch is closed");
			}
			pending.add(changeset);
		} finally {
			semaphore.unlock();
		}
		return changeset;
	}

	@Override
	public SailDataset dataset(IsolationLevel level) throws SailException {
		return dataset(level, true);
	}

	private SailDataset dataset(IsolationLevel level, boolean observe) throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			if (closed) {
				throw new SailException("SailSourceBranch is closed");
			}
			while (true) {
				SailClosable admission = backingSource.beginDatasetAcquisition(level);
				boolean outermost = SailSource.isOutermostDatasetAcquisition(admission);
				SailDataset result = null;
				Throwable failure = null;
				try {
					result = datasetWithinAdmission(level, observe);
				} catch (Throwable datasetFailure) {
					failure = datasetFailure;
				}
				failure = closeResource(failure, admission);
				if (failure instanceof RetryableDatasetAcquisitionException && outermost
						&& failure.getSuppressed().length == 0) {
					if (Thread.currentThread().isInterrupted()) {
						throw new SailException("Interrupted while retrying dataset acquisition", failure);
					}
					continue;
				}
				if (failure != null) {
					failure = closeResource(failure, result);
					rethrow(failure);
				}
				return result;
			}

		}
	}

	private SailDataset datasetWithinAdmission(IsolationLevel level, boolean observe) throws SailException {
		while (true) {
			SnapshotAdmission admissionToWaitFor = null;
			SnapshotAdmission ownedAdmission = null;
			long generation;

			SailDataset cachedObserver = null;
			try (SailClosable publication = backingSource.beginDatasetPublication()) {
				semaphore.lock();
				try {
					if (closed) {
						throw new SailException("SailSourceBranch is closed");
					}
					if (snapshot != null && !isSnapshotUsable(snapshot.dataset, level)) {
						// A writer outside this long-lived branch advanced the backing source. Existing borrowers keep
						// their pinned generation while new readers derive from a compatible snapshot.
						retireSnapshot();
					}
					generation = snapshotGeneration;
					if (observe && level.isCompatibleWith(IsolationLevels.SERIALIZABLE) && serializable == null) {
						serializable = backingSource.sink(level);
						serializableIsolationLevel = level;
					}
					if (snapshot != null) {
						cachedObserver = observeDataset(level, snapshot.dataset, snapshot, observe);
					} else {
						if (level.isCompatibleWith(IsolationLevels.SNAPSHOT)) {
							if (snapshotAdmission == null) {
								ownedAdmission = new SnapshotAdmission(generation);
								snapshotAdmission = ownedAdmission;
							} else {
								admissionToWaitFor = snapshotAdmission;
							}
						}
					}
				} finally {
					semaphore.unlock();
				}
			}
			if (cachedObserver != null) {
				return cachedObserver;
			}

			if (admissionToWaitFor != null) {
				awaitSnapshotAdmission(admissionToWaitFor);
				continue;
			}

			if (ownedAdmission != null) {
				SailDataset admitted;
				try {
					// Reader-capacity admission can wait. Never hold the branch semaphore across this call.
					admitted = backingSource.dataset(level);
				} catch (Throwable failure) {
					completeSnapshotAdmission(ownedAdmission, failure);
					rethrow(failure);
					throw new AssertionError("unreachable");
				}

				SailDataset observer = null;
				boolean retry = false;
				boolean closeAdmitted = false;
				boolean branchClosed = false;
				boolean admissionCompleted = false;
				boolean candidateCached = false;
				boolean candidateUsable = false;
				Throwable observerFailure = null;
				try {
					try (SailClosable publication = backingSource.beginDatasetPublication()) {
						candidateUsable = isSnapshotUsable(admitted, level);
						if (candidateUsable) {
							semaphore.lock();
							try {
								branchClosed = closed;
								boolean ownsAdmission = snapshotAdmission == ownedAdmission;
								if (ownsAdmission) {
									snapshotAdmission = null;
								}
								if (branchClosed) {
									closeAdmitted = true;
								} else if (ownsAdmission && !ownedAdmission.invalidated
										&& ownedAdmission.generation == snapshotGeneration && snapshot == null) {
									snapshot = new SnapshotLease(admitted);
									candidateCached = true;
									try {
										observer = observeDataset(level, snapshot.dataset, snapshot, observe);
									} catch (RuntimeException | Error failure) {
										observerFailure = failure;
										snapshot.retired = true;
										snapshot = null;
										candidateCached = false;
										closeAdmitted = true;
									}
								} else if (snapshot != null && isSnapshotUsable(snapshot.dataset, level)) {
									try {
										observer = observeDataset(level, snapshot.dataset, snapshot, observe);
									} catch (RuntimeException | Error failure) {
										observerFailure = failure;
									}
									closeAdmitted = true;
								} else if (snapshot != null) {
									retireSnapshot();
									retry = true;
									closeAdmitted = true;
								} else {
									retry = true;
									closeAdmitted = true;
								}
								ownedAdmission.completed.countDown();
								admissionCompleted = true;
							} finally {
								semaphore.unlock();
							}
						}
					}
				} catch (Throwable failure) {
					failure = closeResource(failure, candidateCached ? null : admitted);
					if (!admissionCompleted) {
						completeSnapshotAdmission(ownedAdmission, failure);
					}
					failure = closeResource(failure, observer);
					rethrow(failure);
				}

				if (!candidateUsable) {
					Throwable failure = new RetryableDatasetAcquisitionException(
							"The admitted snapshot no longer matches the requested read view");
					failure = closeResource(failure, admitted);
					completeSnapshotAdmission(ownedAdmission, failure);
					rethrow(failure);
				}

				Throwable failure = observerFailure;
				if (branchClosed) {
					failure = addFailure(failure, new SailException("SailSourceBranch is closed"));
				}
				if (closeAdmitted) {
					failure = closeResource(failure, admitted);
					admitted = null;
				}
				if (failure != null) {
					failure = closeResource(failure, observer);
					rethrow(failure);
				}
				if (observer != null) {
					return observer;
				}
				if (retry) {
					throw new RetryableDatasetAcquisitionException(
							"The snapshot admission was invalidated while its dataset was being created");
				}
			}

			// Low-isolation readers bypass an in-flight snapshot admission so a saturated reader pool cannot hold up
			// unrelated direct callers behind this branch's semaphore.
			SailDataset admitted = backingSource.dataset(level);

			SailDataset observer = null;
			boolean closeAdmitted = false;
			boolean branchClosed = false;
			boolean candidateUsable = false;
			Throwable observerFailure = null;
			try {
				try (SailClosable publication = backingSource.beginDatasetPublication()) {
					candidateUsable = isSnapshotUsable(admitted, level);
					if (candidateUsable) {
						semaphore.lock();
						try {
							branchClosed = closed;
							if (branchClosed) {
								closeAdmitted = true;
							} else if (snapshot != null && !isSnapshotUsable(snapshot.dataset, level)) {
								retireSnapshot();
							}
							if (!branchClosed && snapshot != null) {
								try {
									observer = observeDataset(level, snapshot.dataset, snapshot, observe);
								} catch (RuntimeException | Error failure) {
									observerFailure = failure;
								}
								closeAdmitted = true;
							} else if (!branchClosed) {
								try {
									observer = observeDataset(level, admitted, null, observe);
									admitted = null;
								} catch (RuntimeException | Error failure) {
									observerFailure = failure;
									closeAdmitted = true;
								}
							}
						} finally {
							semaphore.unlock();
						}
					}
				}
			} catch (Throwable failure) {
				failure = closeResource(failure, admitted);
				failure = closeResource(failure, observer);
				rethrow(failure);
			}

			if (!candidateUsable) {
				Throwable failure = new RetryableDatasetAcquisitionException(
						"The admitted snapshot no longer matches the requested read view");
				failure = closeResource(failure, admitted);
				rethrow(failure);
			}

			Throwable failure = observerFailure;
			if (branchClosed) {
				failure = addFailure(failure, new SailException("SailSourceBranch is closed"));
			}
			if (closeAdmitted) {
				failure = closeResource(failure, admitted);
			}
			if (failure != null) {
				failure = closeResource(failure, observer);
				rethrow(failure);
			}
			return observer;
		}
	}

	private SailDataset observeDataset(IsolationLevel level, SailDataset base, SnapshotLease lease, boolean observe)
			throws SailException {
		// The caller owns the base until the entire reader graph has been constructed successfully.
		AtomicBoolean adoptedBase = new AtomicBoolean();
		SailDataset derivedFrom = new DelegatingSailDataset(base) {
			@Override
			public void close() {
				if (adoptedBase.get() && lease == null) {
					super.close();
				}
			}

			@Override
			public void abandonUnobserved() {
				if (adoptedBase.get() && lease == null) {
					super.abandonUnobserved();
				}
			}
		};
		class SnapshotObserver extends DelegatingSailDataset {
			private boolean borrowed;

			SnapshotObserver(SailDataset derivedFrom) {
				super(derivedFrom);
			}

			void register() {
				observers.add(this);
				if (lease != null) {
					lease.borrowers++;
					borrowed = true;
					observerSnapshots.put(this, lease);
				}
			}

			private final AtomicBoolean closed = new AtomicBoolean();

			@Override
			public void close() throws SailException {
				release(false);
			}

			@Override
			public void abandonUnobserved() throws SailException {
				release(true);
			}

			private void release(boolean abandon) throws SailException {
				if (!closed.compareAndSet(false, true)) {
					return;
				}
				if (abandon) {
					abandoningDatasets.incrementAndGet();
				}

				try {
					Throwable failure = null;
					SnapshotLease retiredSnapshot = null;
					try {
						if (abandon) {
							super.abandonUnobserved();
						} else {
							super.close();
						}
					} catch (RuntimeException | Error closeFailure) {
						failure = closeFailure;
					}

					try {
						semaphore.lock();
						try {
							observers.remove(this);
							observerSnapshots.remove(this);
							SnapshotLease borrowedSnapshot = borrowed ? lease : null;
							borrowed = false;
							if (borrowedSnapshot != null) {
								try {
									borrowedSnapshot.abandoned |= abandon;
									retiredSnapshot = releaseSnapshot(borrowedSnapshot);
								} catch (RuntimeException | Error cleanupFailure) {
									failure = addFailure(failure, cleanupFailure);
								}
							}
							if (!abandon) {
								try {
									compressChanges();
								} catch (RuntimeException | Error cleanupFailure) {
									failure = addFailure(failure, cleanupFailure);
								}
							}
						} finally {
							semaphore.unlock();
						}
					} catch (RuntimeException | Error cleanupFailure) {
						failure = addFailure(failure, cleanupFailure);
					}

					if (retiredSnapshot != null) {
						try {
							closeSnapshotDataset(retiredSnapshot);
						} catch (RuntimeException | Error cleanupFailure) {
							failure = addFailure(failure, cleanupFailure);
						}
					}

					if (!abandon) {
						try {
							autoFlush();
						} catch (RuntimeException | Error cleanupFailure) {
							failure = addFailure(failure, cleanupFailure);
						}
					}

					if (failure != null) {
						rethrow(failure);
					}
				} finally {
					if (abandon) {
						abandoningDatasets.decrementAndGet();
					}
				}
			}
		}
		SnapshotObserver physical = null;
		SailSink observationSink = null;
		try {
			for (Changeset change : changes) {
				derivedFrom = new SailDatasetImpl(derivedFrom, change);
			}
			physical = new SnapshotObserver(derivedFrom);
			physical.register();
			RetainedSailDataset retained = new RetainedSailDataset(physical);
			SailDataset result = retained;
			if (observe && serializable != null) {
				observationSink = sink(level);
				SailDataset observing = new ObservingSailDataset(retained, observationSink);
				result = new DelegatingSailDataset(observing) {
					private final AtomicBoolean released = new AtomicBoolean();

					@Override
					public void close() {
						if (released.compareAndSet(false, true)) {
							retained.closeWithObservations(observing, false);
						}
					}

					@Override
					public void abandonUnobserved() {
						if (released.compareAndSet(false, true)) {
							retained.closeWithObservations(observing, true);
						}
					}
				};
			}
			adoptedBase.set(true);
			return result;
		} catch (RuntimeException | Error failure) {
			closeResource(failure, observationSink);
			try {
				if (physical == null) {
					derivedFrom.abandonUnobserved();
				} else {
					physical.abandonUnobserved();
				}
			} catch (RuntimeException | Error cleanup) {
				addFailure(failure, cleanup);
			}
			throw failure;
		}
	}

	private boolean isSnapshotUsable(SailDataset dataset, IsolationLevel level) {
		if (!dataset.isSnapshotCompatibleWithCurrentAdmission()) {
			return false;
		}
		return level.isCompatibleWith(IsolationLevels.SNAPSHOT) || backingSource.isSnapshotCurrent(dataset);
	}

	private void awaitSnapshotAdmission(SnapshotAdmission admission) throws SailException {
		QueryExecutionDeadline deadline = QueryExecutionDeadline.current();
		try {
			if (deadline == null) {
				admission.completed.await();
			} else {
				while (admission.completed.getCount() != 0) {
					long remainingNanos = deadline.remainingNanos();
					if (remainingNanos == 0) {
						throw new QueryInterruptedException("Query evaluation took too long");
					}
					if (!admission.completed.await(remainingNanos, TimeUnit.NANOSECONDS)
							&& deadline.remainingNanos() == 0) {
						throw new QueryInterruptedException("Query evaluation took too long");
					}
				}
				if (deadline.remainingNanos() == 0) {
					throw new QueryInterruptedException("Query evaluation took too long");
				}
			}
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			throw new SailException("Interrupted while waiting for a snapshot generation", e);
		}
		if (admission.failure != null) {
			rethrow(admission.failure);
		}
	}

	private void completeSnapshotAdmission(SnapshotAdmission admission, Throwable failure) {
		semaphore.lock();
		try {
			if (snapshotAdmission == admission) {
				if (!admission.invalidated && admission.generation == snapshotGeneration) {
					admission.failure = failure;
				}
				snapshotAdmission = null;
			}
		} finally {
			semaphore.unlock();
		}
		admission.completed.countDown();
	}

	private static Throwable addFailure(Throwable failure, Throwable later) {
		if (failure == null) {
			return later;
		}
		if (failure != later) {
			failure.addSuppressed(later);
		}
		return failure;
	}

	private static Throwable closeResource(Throwable failure, SailClosable resource) {
		if (resource != null) {
			try {
				resource.close();
			} catch (RuntimeException | Error closeFailure) {
				return addFailure(failure, closeFailure);
			}
		}
		return failure;
	}

	private static void rethrow(Throwable failure) throws SailException {
		if (failure instanceof SailException sailException) {
			throw sailException;
		}
		if (failure instanceof RuntimeException runtimeException) {
			throw runtimeException;
		}
		throw (Error) failure;
	}

	@Override
	public SailSource fork() {
		return new SailSourceBranch(this, modelFactory);
	}

	/**
	 * Preserves this branch's backing snapshot and changeset overlays while bypassing its own observation layer.
	 * Observing datasets already retained by a backing source are left intact.
	 */
	SailDataset datasetWithoutObservations(IsolationLevel level) {
		return dataset(level, false);
	}

	@Override
	public SailSource fork(Object writeOwner) {
		return new SailSourceBranch(this, modelFactory, false, writeOwner);
	}

	@Override
	public SailClosable beginDatasetAcquisition(IsolationLevel level) throws SailException {
		return backingSource.beginDatasetAcquisition(level);
	}

	@Override
	public SailClosable beginPublication() throws SailException {
		return beginPublicationForOwner(bufferedPublicationOwner());
	}

	@Override
	public SailClosable beginDatasetPublication() throws SailException {
		return backingSource.beginDatasetPublication();
	}

	@Override
	public SailClosable beginPublication(Object writeOwner) throws SailException {
		return beginPublicationForOwner(owner(writeOwner));
	}

	@Override
	public SailClosable tryBeginPublication() throws SailException {
		return tryBeginPublicationForOwner(bufferedPublicationOwner());
	}

	private Object bufferedPublicationOwner() {
		if (writePreflightOwner != null) {
			return writePreflightOwner;
		}
		Object current = backingSource.writeIntentOwner(null);
		if (current != null) {
			return current;
		}
		semaphore.lock();
		try {
			return bufferedWriteIntents.isEmpty() ? null : bufferedWriteIntents.getFirst().owner();
		} finally {
			semaphore.unlock();
		}
	}

	@Override
	public Object writeIntentOwner(Object requestedOwner) {
		return backingSource.writeIntentOwner(owner(requestedOwner));
	}

	@Override
	public WriteIntent beginWriteIntent(Object writeOwner) {
		return backingSource.beginWriteIntent(owner(writeOwner));
	}

	@Override
	public SailClosable tryBeginPublication(Object writeOwner) throws SailException {
		return tryBeginPublicationForOwner(owner(writeOwner));
	}

	@Override
	public boolean isSnapshotCurrent(SailDataset dataset) {
		return backingSource.isSnapshotCurrent(dataset);
	}

	@Override
	public SailClosable beginPreparedWrite() throws SailException {
		return beginPreparedWriteForOwner(writePreflightOwner);
	}

	@Override
	public SailClosable beginPreparedWrite(Object writeOwner) throws SailException {
		return beginPreparedWriteForOwner(owner(writeOwner));
	}

	private SailClosable beginPublicationForOwner(Object effectiveOwner) throws SailException {
		return effectiveOwner == null ? backingSource.beginPublication()
				: backingSource.beginPublication(effectiveOwner);
	}

	private SailClosable tryBeginPublicationForOwner(Object effectiveOwner) throws SailException {
		return effectiveOwner == null ? backingSource.tryBeginPublication()
				: backingSource.tryBeginPublication(effectiveOwner);
	}

	private SailClosable beginPreparedWriteForOwner(Object effectiveOwner) throws SailException {
		return effectiveOwner == null ? backingSource.beginPreparedWrite()
				: backingSource.beginPreparedWrite(effectiveOwner);
	}

	@Override
	public boolean hasPendingWriteChanges() {
		try {
			semaphore.lock();
			for (Changeset change : changes) {
				if (change.hasWriteChanges()) {
					return true;
				}
			}
			return false;
		} finally {
			semaphore.unlock();
		}
	}

	@Override
	public void prepare() throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter();
				SailClosable preflight = streamingPreflight.enter()) {
			try {
				checkWriteContinuationAdmission();
				ensureWritePreflight();
				try (SailClosable publication = beginPublication()) {
					StreamingWritePreflight.validate(this);
					semaphore.lock();
					try {
						if (!changes.isEmpty()) {
							prepareLocked();
						}
					} finally {
						semaphore.unlock();
					}
				}
			} catch (Throwable failure) {
				StreamingWritePreflight.failed(SailSourceBranch.this, failure);
				rethrow(closeWritePreflight(failure));
			}

		}
	}

	@Override
	public SailSource.WritePreflight writePreflightEstimate() {
		ArrayList<Statement> statements = new ArrayList<>();
		ArrayList<SailSource.NamespaceUpdate> addedNamespaces = new ArrayList<>();
		Set<String> removedNamespacePrefixes = new HashSet<>();
		Set<Resource> clearedContexts = new HashSet<>();
		boolean[] clearIntents = new boolean[2];
		boolean[] hasWriteChanges = new boolean[1];
		semaphore.lock();
		try {
			for (Changeset change : changes) {
				addWritePreflight(change, statements, addedNamespaces, removedNamespacePrefixes, clearedContexts,
						clearIntents, hasWriteChanges);
			}
			synchronized (pending) {
				for (Changeset change : pending) {
					addWritePreflight(change, statements, addedNamespaces, removedNamespacePrefixes, clearedContexts,
							clearIntents, hasWriteChanges);
				}
			}
		} finally {
			semaphore.unlock();
		}
		if (!hasWriteChanges[0]) {
			return SailSource.WritePreflight.empty();
		}
		return new SailSource.WritePreflight(statements, addedNamespaces, removedNamespacePrefixes, clearedContexts,
				clearIntents[0], clearIntents[1]);
	}

	private void preflightBufferedWriteIfNeeded() throws SailException {
		if (!backingSource.tracksWriteIntent()) {
			return;
		}
		long approximateWriteBytes = 0L;
		boolean hasUnestimatedOperations = false;
		semaphore.lock();
		try {
			for (Changeset change : changes) {
				approximateWriteBytes = saturatedAdd(approximateWriteBytes, change.getApproximateWriteIntentBytes());
				hasUnestimatedOperations |= change.hasUnestimatedWriteIntent();
			}
			synchronized (pending) {
				for (Changeset change : pending) {
					approximateWriteBytes = saturatedAdd(approximateWriteBytes,
							change.getApproximateWriteIntentBytes());
					hasUnestimatedOperations |= change.hasUnestimatedWriteIntent();
				}
			}
		} finally {
			semaphore.unlock();
		}
		if (backingSource.shouldPreflightWrite(approximateWriteBytes, hasUnestimatedOperations)) {
			beginBufferedWriteWarning();
		}
	}

	private void beginBufferedWriteWarning() throws SailException {
		SailSource.WriteWarning previous;
		synchronized (writePreflightLock) {
			if (closed) {
				return;
			}
			previous = writeWarning;
		}
		if (previous != null && previous.isActive()) {
			return;
		}
		if (previous != null) {
			synchronized (writePreflightLock) {
				if (writeWarning == previous) {
					writeWarning = null;
				}
			}
			Throwable failure = closeResource(null, previous);
			if (failure != null) {
				rethrow(failure);
			}
		}
		SailSource.WriteWarning warning = beginWriteWarning(writePreflightOwner);
		if (warning == null) {
			throw new IllegalStateException("SailSource.beginWriteWarning returned null");
		}
		synchronized (writePreflightLock) {
			if (!closed && writeWarning == null) {
				writeWarning = warning;
				warning = null;
			}
		}
		Throwable failure = closeResource(null, warning);
		if (failure != null) {
			rethrow(failure);
		}
	}

	private static long saturatedAdd(long left, long right) {
		return Long.MAX_VALUE - left < right ? Long.MAX_VALUE : left + right;
	}

	@Override
	public Object writePreflightGroup() {
		return backingSource.writePreflightGroup();
	}

	@Override
	public boolean shouldPreflightWrite(long approximateWriteBytes, boolean hasUnestimatedOperations) {
		return backingSource.shouldPreflightWrite(approximateWriteBytes, hasUnestimatedOperations);
	}

	@Override
	public boolean tracksWriteIntent() {
		return backingSource.tracksWriteIntent();
	}

	@Override
	public SailClosable beginWriteWarning() throws SailException {
		return backingSource.beginWriteWarning();
	}

	@Override
	public SailSource.WriteWarning beginWriteWarning(Object writeOwner) throws SailException {
		Object effectiveOwner = owner(writeOwner);
		return effectiveOwner == null ? backingSource.beginWriteWarning((Object) null)
				: backingSource.beginWriteWarning(effectiveOwner);
	}

	@Override
	public void preflightWrite(SailSource.WritePreflight estimate) throws SailException {
		ensureWritePreflight(estimate);
	}

	@Override
	public SailClosable beginWritePreflight(SailSource.WritePreflight estimate) throws SailException {
		return beginWritePreflightForOwner(estimate, writePreflightOwner);
	}

	@Override
	public SailClosable beginWritePreflight(SailSource.WritePreflight estimate, Object writeOwner)
			throws SailException {
		return beginWritePreflightForOwner(estimate, owner(writeOwner));
	}

	private SailClosable beginWritePreflightForOwner(SailSource.WritePreflight estimate, Object effectiveOwner)
			throws SailException {
		return effectiveOwner == null ? backingSource.beginWritePreflight(estimate)
				: backingSource.beginWritePreflight(estimate, effectiveOwner);
	}

	private Object owner(Object requestedOwner) {
		return writePreflightOwner == null ? requestedOwner : writePreflightOwner;
	}

	/**
	 * Estimates the complete buffered branch before publication or prepared-write locks are acquired. The temporary
	 * semaphore hold is used only to snapshot the logical write intents; the source preflight runs after releasing it.
	 */
	private boolean ensureWritePreflight() throws SailException {
		if (StreamingWritePreflight.covers(this)) {
			return false;
		}
		return ensureWritePreflight(writePreflightEstimate());
	}

	@Override
	public boolean supportsStreamingWritePreflight() {
		return backingSource.supportsStreamingWritePreflight();
	}

	SailSource streamingBacking() {
		return backingSource;
	}

	record StreamingSnapshot(List<Changeset> changes, boolean forwarded, Object owner) {
	}

	StreamingSnapshot streamingSnapshot(boolean nonblocking, Object inherited) {
		// Backing callbacks must precede the short branch guard, including the nonblocking reader-close path.
		Object effectiveOwner = owner(inherited);
		if (effectiveOwner == null) {
			effectiveOwner = backingSource.writeIntentOwner(null);
		}
		lockStreamingSnapshot(nonblocking);
		try {
			if (effectiveOwner == null && !bufferedWriteIntents.isEmpty()) {
				effectiveOwner = bufferedWriteIntents.getFirst().owner();
			}
			return new StreamingSnapshot(streamingChangesLocked(), frozenBatch != null && frozenBatch.forwarded,
					effectiveOwner);
		} finally {
			semaphore.unlock();
		}
	}

	private void lockStreamingSnapshot(boolean nonblocking) {
		if (nonblocking) {
			if (!semaphore.tryLock()) {
				throw new StreamingWritePreflight.Unavailable();
			}
		} else {
			semaphore.lock();
		}
	}

	List<Changeset> streamingChanges(boolean nonblocking) {
		lockStreamingSnapshot(nonblocking);
		try {
			return streamingChangesLocked();
		} finally {
			semaphore.unlock();
		}
	}

	private List<Changeset> streamingChangesLocked() {
		if (frozenBatch != null) {
			return List.copyOf(frozenBatch.captured);
		}
		List<Changeset> snapshot = new ArrayList<>(changes);
		synchronized (pending) {
			snapshot.addAll(pending);
		}
		return snapshot;
	}

	private boolean ensureWritePreflight(SailSource.WritePreflight estimate) throws SailException {
		if (!estimate.hasChanges()) {
			return false;
		}
		SailClosable warning = null;
		synchronized (writePreflightLock) {
			if (writePreflight != null && writePreflight.estimate().contains(estimate)) {
				warning = writeWarning;
				writeWarning = null;
				if (warning == null) {
					return false;
				}
			}
		}
		if (warning != null) {
			Throwable failure = closeResource(null, warning);
			if (failure != null) {
				rethrow(failure);
			}
			return false;
		}
		SailClosable preflight = beginWritePreflightForOwner(estimate, writePreflightOwner);
		if (preflight == null) {
			throw new IllegalStateException("SailSource.beginWritePreflight returned null");
		}
		SailClosable previousPreflight;
		SailClosable warningToClose = null;
		boolean retained = false;
		boolean alreadyCovered = false;
		synchronized (writePreflightLock) {
			if (!closed) {
				if (writePreflight != null && writePreflight.estimate().contains(estimate)) {
					previousPreflight = null;
					warningToClose = writeWarning;
					writeWarning = null;
					alreadyCovered = true;
				} else {
					previousPreflight = writePreflight == null ? null : writePreflight.scope();
					writePreflight = new WritePreflightRegistration(estimate, preflight);
					warningToClose = writeWarning;
					writeWarning = null;
					retained = true;
					preflight = null;
				}
			} else {
				previousPreflight = null;
			}
		}
		Throwable failure = closeResource(null, preflight);
		failure = closeResource(failure, previousPreflight);
		failure = closeResource(failure, warningToClose);
		if (failure != null) {
			rethrow(failure);
		}
		return retained && !alreadyCovered;
	}

	private static void addWritePreflight(Changeset change, List<Statement> statements,
			List<SailSource.NamespaceUpdate> addedNamespaces, Set<String> removedNamespacePrefixes,
			Set<Resource> clearedContexts, boolean[] clearIntents, boolean[] hasWriteChanges) {
		Changeset.WritePreflightSnapshot snapshot = change.getWritePreflightSnapshot();
		statements.addAll(snapshot.statements());
		addedNamespaces.addAll(snapshot.addedNamespaces());
		removedNamespacePrefixes.addAll(snapshot.removedNamespacePrefixes());
		clearedContexts.addAll(snapshot.clearedContexts());
		clearIntents[0] |= snapshot.statementCleared();
		clearIntents[1] |= snapshot.namespaceCleared();
		hasWriteChanges[0] |= snapshot.hasWrites();
	}

	private Throwable closeWritePreflight(Throwable failure) {
		SailClosable preflight = detachWritePreflights();
		SailModelCleanup.defer(streamingPreflight::close);
		return closeResource(failure, preflight);
	}

	private SailClosable detachWritePreflights() {
		WritePreflightRegistration preflight;
		SailClosable warning;
		synchronized (writePreflightLock) {
			if (writePreflight == null && writeWarning == null) {
				return null;
			}
			preflight = writePreflight;
			writePreflight = null;
			warning = writeWarning;
			writeWarning = null;
		}
		return () -> {
			Throwable failure = closeResource(null, preflight == null ? null : preflight.scope());
			failure = closeResource(failure, warning);
			if (failure != null) {
				rethrow(failure);
			}
		};
	}

	private void closeWritePreflight() throws SailException {
		Throwable failure = closeWritePreflight(null);
		if (failure != null) {
			rethrow(failure);
		}
	}

	private void prepareLocked() throws SailException {
		renewSealedSerializableCarrier();
		if (prepared == null && serializable == null) {
			prepared = backingSource.sink(backingSinkIsolationLevel());
		} else if (prepared == null) {
			prepared = serializable;
		}
		prepare(prepared);
		prepared.prepare();
		preparedObservations = new IdentityHashMap<>();
		rememberPreparedObservations(changes);
	}

	private boolean coversPreparedObservations(Collection<Changeset> generations) {
		if (preparedObservations == null) {
			return false;
		}
		for (Changeset change : generations) {
			long revision = change.observationRevision();
			if (revision >= 0 && !Long.valueOf(revision).equals(preparedObservations.get(change))) {
				return false;
			}
		}
		return true;
	}

	private void rememberPreparedObservations(Collection<Changeset> generations) {
		for (Changeset change : generations) {
			long revision = change.observationRevision();
			if (revision >= 0) {
				preparedObservations.put(change, revision);
			}
		}
	}

	/** Internal validation carriers may move to fresh models; original writer aliases must remain sealed. */
	private void renewSealedSerializableCarrier() {
		if (!(serializable instanceof Changeset carrier) || !carrier.hasSealedGeneration()) {
			return;
		}
		SailSink previous = serializable;
		previous.releasePrepared();
		SailSink replacement = backingSource.sink(serializableIsolationLevel);
		try {
			carrier.copyValidationTo(replacement);
		} catch (RuntimeException | Error validationFailure) {
			rethrow(closeResource(validationFailure, replacement));
		}
		serializable = replacement;
		if (prepared == previous) {
			prepared = null;
			preparedObservations = null;
		}
		previous.close();
	}

	/** The two roles can share one carrier, but neither role is implied by the other's presence. */
	private List<SailSink> validationCarriers() {
		if (prepared == null) {
			return serializable == null ? List.of() : List.of(serializable);
		}
		return serializable == null || prepared == serializable ? List.of(prepared)
				: List.of(prepared, serializable);
	}

	private Throwable releaseValidationPreparation(Throwable failure) {
		for (SailSink carrier : validationCarriers()) {
			try {
				carrier.releasePrepared();
			} catch (RuntimeException | Error cleanupFailure) {
				failure = addFailure(failure, cleanupFailure);
			}
		}
		return failure;
	}

	private IsolationLevel backingSinkIsolationLevel() {
		return backingSinkIsolationLevel(changes);
	}

	private IsolationLevel backingSinkIsolationLevel(Collection<Changeset> generations) {
		for (Changeset change : generations) {
			IsolationLevel level = change.getSinkIsolationLevel();
			if (!IsolationLevels.NONE.isCompatibleWith(level)) {
				return level;
			}
		}
		return IsolationLevels.NONE;
	}

	@Override
	public void flush() throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter();
				SailClosable preflight = streamingPreflight.enter()) {
			try {
				checkWriteContinuationAdmission();
				semaphore.lock();
				try {
					if (frozenBatch != null) {
						throw new IllegalStateException("Use the retained batch while this branch is frozen");
					}
				} finally {
					semaphore.unlock();
				}
				boolean startedPreflight = ensureWritePreflight();
				try {
					try (SailClosable publication = beginPublication()) {
						StreamingWritePreflight.validate(this);
						semaphore.lock();
						try (SailWriteContinuation.Scope continuation = writeContinuation()) {
							if (frozenBatch != null) {
								throw new IllegalStateException("Use the retained batch while this branch is frozen");
							}
							try {
								flushLocked();
							} catch (Throwable failure) {
								StreamingWritePreflight.failed(SailSourceBranch.this, failure);
								SailSource.failPublication(publication);
								rethrow(cleanupFailedFlush(failure));
							}
						} finally {
							semaphore.unlock();
						}
					}
				} catch (Throwable failure) {
					StreamingWritePreflight.failed(SailSourceBranch.this, failure);
					if (startedPreflight) {
						failure = closeWritePreflight(failure);
					}
					rethrow(failure);
				}
			} catch (RuntimeException | Error failure) {
				StreamingWritePreflight.failed(SailSourceBranch.this, failure);
				throw failure;
			}
		}
	}

	@Override
	public FlushBatch freezeForFlush() {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			semaphore.lock();
			try {
				return freezeLocked(List.of());
			} finally {
				semaphore.unlock();
			}

		}
	}

	private BranchFlushBatch freezeLocked(List<Changeset> staged) {
		checkWriteNotSuspended();
		if (closed || frozenBatch != null) {
			throw new IllegalStateException("This branch is closed or already frozen");
		}
		BranchFlushBatch batch = new BranchFlushBatch(List.copyOf(changes), staged,
				List.copyOf(bufferedWriteIntents));
		frozenBatch = batch;
		return batch;
	}

	/** Transfers an ordered suffix once, retaining any older parent prefix in the physical replay batch. */
	@Override
	public void enlistValidationCarriers(FrozenFlush.Context context) {
		List<SailSink> carriers;
		semaphore.lock();
		try {
			if (closed || frozenBatch != null && !context.owns(frozenBatch)) {
				throw new IllegalStateException("The backing branch is closed or independently frozen");
			}
			carriers = validationCarriers();
		} finally {
			semaphore.unlock();
		}
		for (SailSink carrier : carriers) {
			context.validationCarrier(carrier);
		}
		context.discover(backingSource);
	}

	@Override
	public FrozenFlush.Batch stageFrozen(List<Changeset> incoming, Changeset validationCarrier,
			FrozenFlush.Context context) {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			List<Changeset> staged = new ArrayList<>(incoming.size());
			boolean adopted = false;
			semaphore.lock();
			try {
				checkWriteNotSuspended();
				if (closed || frozenBatch != null && !context.owns(frozenBatch)) {
					throw new IllegalStateException("The backing branch is closed or independently frozen");
				}
				for (Changeset change : incoming) {
					Changeset published = change.shallowClone();
					staged.add(published);
					StreamingWritePreflight.staged(this, change, published);
				}
				changes.addAll(staged);
				BranchFlushBatch batch = frozenBatch;
				if (batch == null) {
					batch = freezeLocked(staged);
				} else {
					batch.appendStaged(staged);
				}
				adopted = true;
				batch.enlist(context);
				for (Changeset change : staged) {
					for (Changeset other : pending) {
						if (other != validationCarrier && !context.ownsValidationCarrier(other)) {
							other.prepend(change);
						}
					}
				}
				if (!batch.stagedOnce) {
					batch.stage(context);
				} else {
					batch.stageSuffix(staged);
				}
				return batch;
			} catch (RuntimeException | Error failure) {
				if (!adopted) {
					changes.removeAll(staged);
					for (Changeset provisional : staged) {
						closeResource(failure, provisional);
					}
				}
				throw failure;
			} finally {
				semaphore.unlock();
			}
		}
	}

	private final class BranchFlushBatch implements FrozenFlush.Batch {
		private final ArrayList<Changeset> captured;
		private final ArrayList<Changeset> staged;
		private final List<WriteIntent> intents;
		private final ArrayList<SailClosable> models = new ArrayList<>();
		private FrozenFlush.Context context;
		private boolean stagedOnce;
		private boolean forwarded;
		private boolean released;

		private BranchFlushBatch(List<Changeset> captured, List<Changeset> staged, List<WriteIntent> intents) {
			this.captured = new ArrayList<>(captured);
			this.staged = new ArrayList<>(staged);
			this.intents = intents;
			models.ensureCapacity(captured.size());
			try {
				for (Changeset change : captured) {
					models.add(change.freezeModel());
				}
			} catch (RuntimeException | Error failure) {
				for (SailClosable model : models) {
					closeResource(failure, model);
				}
				throw failure;
			}
		}

		@Override
		public StreamingWritePreflight preflight() {
			return streamingPreflight;
		}

		private void appendStaged(List<Changeset> additions) {
			models.ensureCapacity(Math.addExact(models.size(), additions.size()));
			captured.ensureCapacity(Math.addExact(captured.size(), additions.size()));
			staged.ensureCapacity(Math.addExact(staged.size(), additions.size()));
			List<SailClosable> acquired = new ArrayList<>(additions.size());
			try {
				for (Changeset change : additions) {
					acquired.add(change.freezeModel());
				}
			} catch (RuntimeException | Error failure) {
				for (SailClosable lease : acquired) {
					closeResource(failure, lease);
				}
				throw failure;
			}
			for (int i = 0; i < additions.size(); i++) {
				models.add(acquired.get(i));
				captured.add(additions.get(i));
				staged.add(additions.get(i));
			}
		}

		@Override
		public void enlist(FrozenFlush.Context requested) {
			semaphore.lock();
			try {
				if (released || stagedOnce && context != requested) {
					throw new IllegalStateException("The retained batch is closed or belongs to another publication");
				}
				context = requested;
				context.register(this);
			} finally {
				semaphore.unlock();
			}
		}

		@Override
		public void discoverValidationCarriers(FrozenFlush.Context requested) {
			requested.discover(SailSourceBranch.this);
		}

		@Override
		public void stage(FrozenFlush.Context requested) {
			enlist(requested);
			semaphore.lock();
			try {
				if (stagedOnce) {
					return;
				}
				stageSuffix(captured);
				stagedOnce = true;
			} finally {
				semaphore.unlock();
			}
		}

		private void stageSuffix(List<Changeset> suffix) {
			renewSealedSerializableCarrier();
			for (SailSink carrier : validationCarriers()) {
				context.validationCarrier(carrier);
				for (Changeset change : suffix) {
					prepare(change, carrier);
				}
				if (carrier instanceof Changeset changeset) {
					changeset.validateReadBoundary();
					changeset.releasePrepared();
				} else {
					// Native Memory validation owns the only exclusion protecting its original read snapshot.
					// Keep it through physical application; release it only after acknowledgement/cancellation.
					if (carrier != prepared || carrier == serializable || !coversPreparedObservations(suffix)) {
						carrier.prepare();
						if (carrier == prepared) {
							if (preparedObservations == null) {
								preparedObservations = new IdentityHashMap<>();
							}
							rememberPreparedObservations(suffix);
						}
					}
				}
			}
			FrozenFlush.Batch destination = null;
			// Reserve this position before wrappers stage additional sources. A raw primary still applies first.
			context.terminal(this);
			if (backingSource instanceof FrozenFlush buffered) {
				destination = buffered.stageFrozen(suffix,
						prepared instanceof Changeset carrier ? carrier : null, context);
			}
			if (destination != null) {
				forwarded = true;
				context.forwarded(this);
			}
		}

		@Override
		public void flush() {
			if (context == null) {
				enlist(new FrozenFlush.Context());
			}
			context.flush(this);
		}

		@Override
		public void apply() {
			if (!captured.isEmpty()) {
				try (SailSink attempt = backingSource.sink(backingSinkIsolationLevel(captured))) {
					context.attempt(attempt);
					for (Changeset change : captured) {
						prepare(change, attempt);
					}
					attempt.prepare();
					for (Changeset change : captured) {
						SailSourceBranch.this.flush(change, attempt);
					}
					attempt.flush();
					context.recordOwnFlush(attempt);
				}
			}
		}

		@Override
		public void unFreezeAndDiscardFlushed() {
			if (context == null) {
				throw new IllegalStateException("An unapplied batch cannot be acknowledged");
			}
			context.release(true);
		}

		@Override
		public void close() {
			if (context == null) {
				releaseLocal(false);
			} else {
				context.release(false);
			}
		}

		@Override
		public void releaseLocal(boolean acknowledged) {
			try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
				semaphore.lock();
				try {
					if (released) {
						return;
					}
					released = true;
					preparedObservations = null;
					Throwable failure = context == null ? releaseValidationPreparation(null) : null;
					if (acknowledged) {
						for (Changeset change : captured) {
							change.sealModel();
						}
						changes.removeAll(captured);
						for (Changeset change : captured) {
							failure = closeResource(failure, change);
						}
						SailSink completedPrepared = prepared;
						SailSink previousSerializable = serializable;
						prepared = null;
						try {
							renewSealedSerializableCarrier();
						} catch (RuntimeException | Error renewalFailure) {
							failure = addFailure(failure, renewalFailure);
						}
						if (completedPrepared != previousSerializable) {
							failure = closeResource(failure, completedPrepared);
						}
						for (WriteIntent intent : intents) {
							bufferedWriteIntents.remove(intent);
							failure = closeResource(failure, intent);
						}
						try {
							retireSnapshot();
						} catch (RuntimeException | Error cleanupFailure) {
							failure = addFailure(failure, cleanupFailure);
						}
						failure = closeWritePreflight(failure);
					} else {
						changes.removeAll(staged);
						for (Changeset other : pending) {
							for (Changeset change : staged) {
								other.removePrepend(change);
							}
						}
					}
					if (!acknowledged) {
						for (Changeset change : staged) {
							failure = closeResource(failure, change);
						}
					}
					for (SailClosable model : models) {
						failure = closeResource(failure, model);
					}
					frozenBatch = null;
					SailModelCleanup.defer(streamingPreflight::close);
					if (failure != null) {
						rethrow(failure);
					}
				} finally {
					semaphore.unlock();
				}

			}
		}
	}

	private void flushLocked() throws SailException {
		if (!changes.isEmpty()) {
			renewSealedSerializableCarrier();
			if (prepared == null) {
				prepareLocked();
			}
			flush(prepared);
			prepared.flush();
			try {
				if (prepared != serializable) {
					prepared.close();
				}
			} finally {
				prepared = null;
				preparedObservations = null;
			}
			retireSnapshot();
			closeWritePreflight();
			Throwable failure = closeBufferedWriteIntents(null);
			if (failure != null) {
				rethrow(failure);
			}
		}
	}

	private Throwable cleanupFailedFlush(Throwable failure) {
		while (!changes.isEmpty()) {
			failure = closeResource(failure, changes.removeFirst());
		}
		SailSink toClose = prepared;
		prepared = null;
		preparedObservations = null;
		if (toClose != serializable) {
			failure = closeResource(failure, toClose);
		}
		try {
			retireSnapshot();
		} catch (Throwable retireFailure) {
			failure = addFailure(failure, retireFailure);
		}
		failure = closeWritePreflight(failure);
		return closeBufferedWriteIntents(failure);
	}

	private Throwable closeBufferedWriteIntents(Throwable failure) {
		while (!bufferedWriteIntents.isEmpty()) {
			failure = closeResource(failure, bufferedWriteIntents.removeFirst());
		}
		return failure;
	}

	/**
	 * Retires the cached snapshot after a branch flush or close. Existing borrowers retain the retired generation until
	 * their datasets close; new readers will derive from the backing source again. Callers hold {@code semaphore}.
	 */
	private void retireSnapshot() throws SailException {
		retireSnapshot(false);
	}

	private void retireSnapshot(boolean abandon) throws SailException {
		snapshotGeneration++;
		if (snapshotAdmission != null) {
			// Keep the admission reserved until its backing call returns, so a second snapshot admission cannot block
			// behind the first while holding a resource it needs to complete.
			snapshotAdmission.invalidated = true;
		}
		if (snapshot != null) {
			SnapshotLease toRetire = snapshot;
			snapshot = null;
			toRetire.retired = true;
			toRetire.abandoned |= abandon;
			if (toRetire.borrowers == 0) {
				closeSnapshot(toRetire);
			}
		}
	}

	private SnapshotLease releaseSnapshot(SnapshotLease lease) {
		if (lease.borrowers <= 0) {
			throw new IllegalStateException("Snapshot lease has no borrowers to release");
		}
		lease.borrowers--;
		if (lease.retired && lease.borrowers == 0 && !lease.closed) {
			lease.closed = true;
			return lease;
		}
		return null;
	}

	private void closeSnapshot(SnapshotLease lease) throws SailException {
		if (!lease.closed) {
			lease.closed = true;
			closeSnapshotDataset(lease);
		}
	}

	private void closeSnapshotDataset(SnapshotLease lease) throws SailException {
		if (lease.abandoned) {
			lease.dataset.abandonUnobserved();
		} else {
			lease.dataset.close();
		}
	}

	public boolean isChanged() {
		try {
			semaphore.lock();
			return !changes.isEmpty();
		} finally {
			semaphore.unlock();
		}
	}

	@Override
	public String toString() {
		return backingSource.toString() + "\n" + changes;
	}

	void preparedChangeset(Changeset changeset) {
		semaphore.lock();
		try {
			checkWriteNotSuspended();
			preparedContinuations.put(changeset, writeContinuation());
		} catch (RuntimeException | Error failure) {
			semaphore.unlock();
			throw failure;
		}
	}

	void merge(Changeset change) {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			try {
				semaphore.lock();
				mergeLocked(change);
			} finally {
				semaphore.unlock();
			}

		}
	}

	void mergeLocked(Changeset change) {
		checkWriteNotSuspended();
		Changeset.Transfer transfer = change.transfer(this);
		if (transfer != null) {
			Changeset incoming = transfer.changeset();
			changes.add(incoming);
			WriteIntent intent = transfer.intent();
			if (intent != null) {
				bufferedWriteIntents.addLast(intent);
			}
			// Reusable carriers remain pending until close so that intervening publications are still validated.
			// Publish the exact incoming generation before compression can combine it with any older prefix.
			for (Changeset other : pending) {
				if (other != change) {
					other.prepend(incoming);
				}
			}
			compressChanges();
		}
	}

	void closeChangeset(Changeset changeset) {
		try {
			checkWriteNotSuspended();
			SailWriteContinuation.Scope continuation = preparedContinuations.remove(changeset);
			if (continuation != null) {
				continuation.close();
			}
		} finally {
			semaphore.unlock();
		}
	}

	private SailWriteContinuation.Scope writeContinuation() {
		return SailWriteContinuation.enter(semaphore, () -> suspendedWrites++, () -> {
			suspendedWrites--;
			if (semaphore.isHeldByCurrentThread()) {
				writesResumed.signalAll();
			}
		});
	}

	/**
	 * Lifecycle cleanup from another thread waits for a suspended continuation to resume instead of failing and leaving
	 * the branch's snapshots and sinks open. A thread that owns continuations must not close the suspended branch.
	 */
	private void awaitWriteResumption() {
		while (suspendedWrites != 0) {
			if (SailWriteContinuation.isPresent()) {
				checkWriteNotSuspended();
			}
			writesResumed.awaitUninterruptibly();
		}
	}

	private void checkWriteNotSuspended() {
		if (suspendedWrites != 0) {
			throw new SailConflictException("A suspended buffered write cannot mutate, close, or publish its suffix");
		}
	}

	private void checkWriteContinuationAdmission() {
		semaphore.lock();
		try {
			checkWriteNotSuspended();
		} finally {
			semaphore.unlock();
		}
	}

	void compressChanges() {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			try {
				semaphore.lock();

				if (changes.size() == 2) {
					boolean swap = false;
					Changeset[] array = changes.toArray(new Changeset[0]);
					if (!(array[0].hasDeprecated() || array[0].hasApproved())
							&& (array[1].hasDeprecated() || array[1].hasApproved())) {

						if (!array[0].isFrozen() && !array[1].isFrozen()
								&& Changeset.isOrderIndependent(array[0], array[1])) {

							// The last change contains all the approved and deprecated statements, faster to swap
							// before
							// merging. This is typically the case when parsing a file with namespaces at the beginning.

							Changeset second = changes.removeLast();
							if (changes.peekLast().isRetained()) {
								changes.addLast(second);
								return;
							}
							Changeset first = changes.removeLast();

							changes.addFirst(second);
							changes.addLast(first);
						}

					}

				}

				while (changes.size() > 1) {
					Changeset pop = changes.removeLast();
					if (pop.isFrozen() || changes.peekLast().isFrozen() || changes.peekLast().isRetained()
							|| pop.sharesModelWith(changes.peekLast())) {
						changes.addLast(pop);
						return;
					}

					try {
						prepare(pop, changes.getLast());
						flush(pop, changes.getLast());
					} catch (RuntimeException | Error failure) {
						changes.addLast(pop);
						throw failure;
					}
					StreamingWritePreflight.removed(pop);
					pop.close();
				}

			} finally {
				semaphore.unlock();
			}

		}
	}

	void autoFlush() throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			if (autoFlush && !abandoned && abandoningDatasets.get() == 0) {
				boolean eligible = false;
				if (semaphore.tryLock()) {
					try {
						eligible = frozenBatch == null && suspendedWrites == 0 && observers.isEmpty()
								&& !changes.isEmpty();
					} finally {
						semaphore.unlock();
					}
				}
				if (!eligible) {
					return;
				}
				try (SailClosable preflight = streamingPreflight.enter(true)) {
					try {
						boolean startedPreflight = ensureWritePreflight();
						SailClosable publication;
						try {
							publication = tryBeginPublication();
						} catch (Throwable failure) {
							StreamingWritePreflight.failed(SailSourceBranch.this, failure);
							if (startedPreflight) {
								failure = closeWritePreflight(failure);
							}
							rethrow(failure);
							return;
						}
						if (publication == null) {
							if (startedPreflight) {
								closeWritePreflight();
							}
							return;
						}
						boolean flushed = false;
						try (publication) {
							StreamingWritePreflight.validate(this);
							if (semaphore.tryLock()) {
								try (SailWriteContinuation.Scope continuation = writeContinuation()) {
									if (frozenBatch == null && suspendedWrites == 0 && observers.isEmpty()) {
										try {
											flushLocked();
											flushed = true;
										} catch (Throwable failure) {
											StreamingWritePreflight.failed(SailSourceBranch.this, failure);
											SailSource.failPublication(publication);
											rethrow(cleanupFailedFlush(failure));
										}
									}
								} finally {
									semaphore.unlock();
								}
							}
						} catch (RuntimeException | Error failure) {
							StreamingWritePreflight.failed(SailSourceBranch.this, failure);
							throw failure;
						} finally {
							if (startedPreflight && !flushed) {
								closeWritePreflight();
							}
						}
					} catch (RuntimeException | Error failure) {
						StreamingWritePreflight.failed(SailSourceBranch.this, failure);
						throw failure;
					}
				} catch (StreamingWritePreflight.Unavailable busyAncestor) {
					// Reader cleanup must not wait for an ancestor's retained preparation.
					return;
				}
			}

		}
	}

	private boolean isChanged(Changeset change) {
		return change.isChanged();
	}

	private void prepare(SailSink sink) throws SailException {
		try {
			semaphore.lock();
			for (Changeset change : changes) {
				prepare(change, sink);
			}
		} finally {
			semaphore.unlock();
		}
	}

	private void prepare(Changeset change, SailSink sink) throws SailException {
		change.sinkObserved(sink);
	}

	private void flush(SailSink sink) throws SailException {
		try (SailModelCleanup.Scope cleanup = SailModelCleanup.enter()) {
			if (sink instanceof Changeset destination) {
				// The optimized model transfer bypasses the ordinary mutation methods. Establish the destination's
				// intent under this publication owner before either branch lock or the retained model changes hands.
				destination.beforeWriteIntent();
			}
			try {
				semaphore.lock();
				if (changes.size() == 1 && !changes.getFirst().isRetained() && sink instanceof Changeset
						&& !isChanged((Changeset) sink)) {
					// one change to apply that is not in use to an empty Changeset
					Changeset dst = (Changeset) sink;
					Changeset change = changes.getFirst();
					StreamingWritePreflight.apply(this, change, dst,
							() -> StreamingWritePreflight.mutate(change, dst, () -> dst.setChangeset(change)));
					changes.removeFirst();
					StreamingWritePreflight.removed(change);
					change.close();
				} else {
					Iterator<Changeset> iter = changes.iterator();
					while (iter.hasNext()) {
						Changeset change = iter.next();
						flush(change, sink);
						iter.remove();
						StreamingWritePreflight.removed(change);
						change.close();
					}
				}
			} finally {
				semaphore.unlock();
			}

		}
	}

	private void flush(Changeset change, SailSink sink) throws SailException {
		StreamingWritePreflight.apply(this, change, sink, () -> flushContents(change, sink));
	}

	private void flushContents(Changeset change, SailSink sink) throws SailException {
		prepare(change, sink);
		if (change.isNamespaceCleared()) {
			StreamingWritePreflight.mutate(change, sink, sink::clearNamespaces);
		}
		Set<String> removedPrefixes = change.getRemovedPrefixes();
		if (removedPrefixes != null) {
			for (String prefix : removedPrefixes) {
				StreamingWritePreflight.mutate(change, sink, () -> sink.removeNamespace(prefix));
			}
		}
		Map<String, String> addedNamespaces = change.getAddedNamespaces();
		if (addedNamespaces != null) {
			for (Map.Entry<String, String> e : addedNamespaces.entrySet()) {
				StreamingWritePreflight.mutate(change, sink, () -> sink.setNamespace(e.getKey(), e.getValue()));
			}
		}
		if (change.isStatementCleared()) {
			StreamingWritePreflight.mutate(change, sink, sink::clear);
		}
		Set<Resource> deprecatedContexts = change.getDeprecatedContexts();
		if (deprecatedContexts != null && !deprecatedContexts.isEmpty()) {
			StreamingWritePreflight.mutate(change, sink, () -> sink.clear(deprecatedContexts.toArray(new Resource[0])));
		}

		change.sinkDeprecated(sink);
		change.sinkApproved(sink);
	}

}
