/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.base;

import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.common.annotation.InternalUseOnly;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.sail.base.Changeset.SimpleStatementPattern;

/** Immutable read patterns with their original snapshot and publication owner. */
@InternalUseOnly
public final class SnapshotObservation implements SailClosable {

	private final SnapshotReadContext origin;
	private final Object publicationOwner;
	private final Set<SimpleStatementPattern> patterns;
	private final Set<SnapshotValidationSource> completedParticipants;
	private final AtomicInteger references = new AtomicInteger(1);

	public SnapshotObservation(SnapshotReadContext origin, Object publicationOwner,
			Set<SimpleStatementPattern> patterns) {
		this(origin, publicationOwner, patterns.stream()
				.map(pattern -> new SimpleStatementPattern(
						(Resource) SnapshotValues.detach(pattern.subject()),
						(IRI) SnapshotValues.detach(pattern.predicate()),
						SnapshotValues.detach(pattern.object()), (Resource) SnapshotValues.detach(pattern.context()),
						pattern.allContexts()))
				.collect(Collectors.toUnmodifiableSet()), Set.of());
	}

	private SnapshotObservation(SnapshotReadContext origin, Object publicationOwner,
			Set<SimpleStatementPattern> patterns, Set<SnapshotValidationSource> completedParticipants) {
		this.origin = Objects.requireNonNull(origin);
		this.publicationOwner = Objects.requireNonNull(publicationOwner);
		this.patterns = patterns;
		this.completedParticipants = completedParticipants;
		if (origin instanceof SnapshotReadContextImpl) {
			((SnapshotReadContextImpl) origin).retainValidation();
		} else {
			origin.retain();
		}
	}

	public SnapshotReadContext origin() {
		return origin;
	}

	/**
	 * Returns every original context of this participant. A composed view can contain several boundaries for the same
	 * source, and each must be validated. Returned contexts are borrowed from this observation's ownership. For a
	 * directly supplied external context, its source must recognize its own context implementation. A participant that
	 * has already accepted this batch's publication has no remaining validation contexts.
	 */
	public List<SnapshotReadContext> contexts(SnapshotValidationSource source) {
		return capturedOrigins(source).stream().map(SnapshotReadContextImpl.CapturedOrigin::context).toList();
	}

	public Object publicationOwner() {
		return publicationOwner;
	}

	public Set<SimpleStatementPattern> patterns() {
		return patterns;
	}

	SnapshotObservation retain() {
		references.updateAndGet(count -> {
			if (count == 0) {
				throw new IllegalStateException("Observation has been released");
			}
			return count + 1;
		});
		return this;
	}

	List<SnapshotReadContextImpl.CapturedOrigin> capturedOrigins(SnapshotValidationSource source) {
		if (completedParticipants.contains(source)) {
			return List.of();
		}
		return origin instanceof SnapshotReadContextImpl
				? ((SnapshotReadContextImpl) origin).capturedOrigins(source, Set.of())
				: List.of(new SnapshotReadContextImpl.CapturedOrigin(origin, Set.of()));
	}

	/** Keeps downstream validation, without extending an accepted shared participant's serialization interval. */
	SnapshotObservation publishedTo(SnapshotValidationSource participant) {
		Set<SnapshotValidationSource> completed = Collections.newSetFromMap(new IdentityHashMap<>());
		completed.addAll(completedParticipants);
		completed.add(participant);
		return new SnapshotObservation(origin, publicationOwner, patterns, Collections.unmodifiableSet(completed));
	}

	@Override
	public void close() {
		int remaining = references.decrementAndGet();
		if (remaining < 0) {
			throw new IllegalStateException("Observation released more than once");
		}
		if (remaining == 0) {
			if (origin instanceof SnapshotReadContextImpl) {
				((SnapshotReadContextImpl) origin).releaseValidation();
			} else {
				origin.close();
			}
		}
	}
}
