/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude Code

// Safari freezes background tabs. A Workbench tab frozen in the middle of an IndexedDB write transaction kept that
// transaction open, and with it the lock on the one database every Workbench page used: every other Workbench page
// stayed blank until the frozen tab woke up. Pages now keep ordinary results in memory, and a large result is a
// database of its own that no other tab writes, so a held transaction elsewhere holds nothing up.

// @ts-check
const { test, expect } = require('@playwright/test');
const { createSeededRepository, deleteRepository, repositoryPageUrl, serverBaseUrl, uniqueRepositoryId,
	waitForRoute } = require('./workbench-test-helpers.js');
const { DATABASE_PREFIX, largeQuery, storedResults } = require('../row-store-helpers.js');

const REPOSITORY_ID = uniqueRepositoryId('row-store-isolation');
const LEGACY_DATABASE = 'rdf4j-workbench-query-results';

test.beforeAll(async ({ request }) => {
	await createSeededRepository(request, serverBaseUrl(), REPOSITORY_ID, { graphs: [] });
});

test.afterAll(async ({ request }) => {
	await deleteRepository(request, serverBaseUrl(), REPOSITORY_ID);
});

/**
 * Keeps one readwrite transaction open on each database for as long as the page lives, as a frozen tab does: a cursor
 * walks the database's stores over and over and never lets the transaction finish.
 */
async function holdWriteTransactions(page, names) {
	await page.evaluate((databaseNames) => Promise.all(databaseNames.map((name) => new Promise((resolve, reject) => {
		const request = indexedDB.open(name, 1);
		request.onupgradeneeded = () => {
			request.result.createObjectStore('stores', { keyPath: 'id' });
			request.result.createObjectStore('rows', { keyPath: ['storeId', 'index'] });
		};
		request.onerror = () => reject(request.error);
		request.onsuccess = () => {
			const database = request.result;
			const seed = database.transaction(['stores'], 'readwrite');
			seed.objectStore('stores').put({ id: 'held', count: 0, format: 'blocks-v2', tailStart: 0, tailRows: 0,
				tailChars: 0 });
			seed.oncomplete = () => {
				const held = database.transaction(['stores', 'rows'], 'readwrite');
				const stores = held.objectStore('stores');
				const walk = () => {
					const cursor = stores.openCursor();
					cursor.onsuccess = () => {
						if (cursor.result) {
							cursor.result.update(cursor.result.value);
							cursor.result.continue();
						} else {
							walk();
						}
					};
				};
				walk();
				resolve();
			};
		};
	}))), names);
}

/** Whether a read-only transaction on a database finishes within ms (false while a write transaction holds it). */
async function readsWithin(page, name, ms) {
	return page.evaluate(({ name, ms }) => new Promise((resolve) => {
		const timer = setTimeout(() => resolve(false), ms);
		const request = indexedDB.open(name);
		request.onsuccess = () => {
			const transaction = request.result.transaction(['stores']);
			transaction.objectStore('stores').count();
			transaction.oncomplete = () => { clearTimeout(timer); resolve(true); };
		};
	}), { name, ms });
}

test('pages and a large query result work while another tab holds write transactions open', async ({ page, context }) => {
	test.setTimeout(120000);
	const holder = await context.newPage();
	await holder.goto(repositoryPageUrl(REPOSITORY_ID, 'summary'));
	await waitForRoute(holder, 'summary');
	const otherStore = DATABASE_PREFIX + 'rows-' + Date.now().toString(36) + '-held-by-another-tab';
	await holdWriteTransactions(holder, [LEGACY_DATABASE, otherStore]);

	await page.goto(repositoryPageUrl(REPOSITORY_ID, 'summary'));
	await waitForRoute(page, 'summary');
	expect(await readsWithin(page, LEGACY_DATABASE, 1000), 'the old shared database is held').toBe(false);
	expect(await readsWithin(page, otherStore, 1000), 'the other tab\'s store is held').toBe(false);

	// The Workbench in this tab is not held up: its pages render and a large result is stored on its own.
	const pageErrors = [];
	page.on('pageerror', (error) => pageErrors.push(error.message));
	await page.goto(repositoryPageUrl('NONE', 'repositories'));
	await waitForRoute(page, 'repositories');
	await expect(page.locator('#workbench-app')).toContainText(REPOSITORY_ID);
	await page.goto(repositoryPageUrl(REPOSITORY_ID, 'query'));
	await waitForRoute(page, 'query');
	await page.locator('.CodeMirror').first().evaluate((element, query) => element.CodeMirror.setValue(query),
		largeQuery());
	await page.locator('#exec').click();
	await expect(page.locator('#query-results .query-result-status')).toHaveText(/^12,000 rows · complete/,
		{ timeout: 30000 });
	const stored = await storedResults(page);
	const own = stored.databases.filter((id) => DATABASE_PREFIX + id !== otherStore);
	expect(own, 'the result is in a database of its own').toHaveLength(1);
	await page.keyboard.press('End');
	await expect(page.locator('#query-results tbody tr[data-query-row-index="11999"]')).toBeAttached();
	expect(pageErrors).toEqual([]);
	await holder.close();
});
