/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

// @ts-check
const { test, expect } = require('@playwright/test');
const { waitForRoute, waitForWriteDone } = require('./workbench-test-helpers');
const fs = require('fs');
const path = require('path');

const SERVER_BASE_URL = (process.env.RDF4J_SERVER_BASE_URL || 'http://127.0.0.1:8091/rdf4j-server').replace(/\/+$/, '');
const WORKBENCH_BASE_URL = (process.env.RDF4J_WORKBENCH_BASE_URL || 'http://127.0.0.1:8091/rdf4j-workbench').replace(/\/+$/, '');
const ARTIFACT_DIRECTORY = process.env.WORKBENCH_VISUAL_REFINEMENT_DIRECTORY
	|| '/Users/havardottestad/.codex/visualizations/2026/09/27/01a0e2fb-705d-7ee2-9a69-d25d3da4d594/workbench-refinement';
const SCREENSHOT_DIRECTORY = path.join(ARTIFACT_DIRECTORY, 'final', 'operation-states');
const RUN_ID = `${process.pid}-${Date.now()}`;
const REPOSITORY_ID = `visual-operation-${RUN_ID}`;
const DELETE_REPOSITORY_ID = `visual-delete-${RUN_ID}`;
const REPOSITORY_URL = `${SERVER_BASE_URL}/repositories/${REPOSITORY_ID}`;
const DELETE_REPOSITORY_URL = `${SERVER_BASE_URL}/repositories/${DELETE_REPOSITORY_ID}`;

test.beforeAll(async ({ request }) => {
	fs.mkdirSync(SCREENSHOT_DIRECTORY, { recursive: true });
	await createRepository(request, REPOSITORY_ID);
	await createRepository(request, DELETE_REPOSITORY_ID);
	const loaded = await request.post(`${REPOSITORY_URL}/statements`, {
		headers: { 'Content-Type': 'application/n-quads' },
		data: [
			'<urn:visual:alice> <urn:visual:name> "Alice" .',
			'<urn:visual:bob> <urn:visual:name> "Bob" .',
			'<urn:visual:alice> <urn:visual:type> <urn:visual:Person> <urn:visual:people> .',
			'<urn:visual:bob> <urn:visual:type> <urn:visual:Person> <urn:visual:people> .'
		].join('\n')
	});
	expect([200, 201, 204]).toContain(loaded.status());
});

test.afterAll(async ({ request }) => {
	for (const repositoryUrl of [REPOSITORY_URL, DELETE_REPOSITORY_URL]) {
		const response = await request.delete(repositoryUrl);
		expect([200, 204, 400, 404]).toContain(response.status());
	}
});

test('covers task-fixture operation states without touching user repositories', async ({ page, request }) => {
	test.setTimeout(180_000);
	page.setDefaultTimeout(10_000);
	page.setDefaultNavigationTimeout(10_000);
	const errors = [];
	page.on('pageerror', error => errors.push(error.message));
	await page.setViewportSize({ width: 1440, height: 1000 });
	await openPage(page, 'repositories/NONE/repositories');
	await page.evaluate(() => window.RDF4JWorkbenchTheme.setPreference('light'));
	await openPage(page, `repositories/${REPOSITORY_ID}/add`);
	await expect(page.locator('#source-file')).toBeChecked();
	await expect(page.locator('#file')).toBeEnabled();
	await expect(page.locator('#url')).toBeDisabled();
	await expect(page.locator('#text')).toBeDisabled();
	await capture(page, 'add-source-file-enabled-text-url-disabled-1440.png');

	await page.locator('label[for="source-text"]').click();
	await expect(page.locator('#text')).toBeEnabled();
	await expect(page.locator('#file')).toBeDisabled();
	await page.locator('#text').fill('<urn:visual:added> <urn:visual:value> "Added" .');
	await page.locator('#add-upload-actions input[type="submit"]').click();
	// Add stays and shows a tick (plan task M14.2).
	await waitForWriteDone(page, 'add');
	await capture(page, 'add-success-1440.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/add`);
	await page.locator('label[for="source-text"]').click();
	await page.locator('#text').fill('<urn:visual:good> <urn:visual:predicate> "valid" .');
	await page.locator('#Content-Type').evaluate(select => {
		const unsupported = document.createElement('option');
		unsupported.value = 'application/x-rdf4j-visual-test';
		unsupported.textContent = 'Unsupported test format';
		select.appendChild(unsupported);
		select.value = unsupported.value;
	});
	await page.locator('#add-upload-actions input[type="submit"]').click();
	await expect(page.locator('.workbench-callout--error[role="alert"]')).toBeVisible();
	await capture(page, 'add-unsupported-format-error-1440.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/update`);
	await setCodeMirror(page, 'INSERT DATA { <urn:visual:updated> <urn:visual:value> "Updated" }');
	await page.locator('#update-form input[type="submit"]').click();
	await waitForWriteDone(page, 'update');
	await capture(page, 'update-success-1440.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/update`);
	await setCodeMirror(page, 'INSERT {');
	await page.locator('#update-form input[type="submit"]').click();
	await expect(page.locator('[id="updateString.errors"]')).toBeVisible();
	await expect(page.locator('[id="updateString.errors"]')).not.toBeEmpty();
	await capture(page, 'update-invalid-sparql-error-1440.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/remove`);
	// Remove's button stays disabled while every field is empty (plan task M6.5); post the empty form directly.
	await page.locator('#remove-form').evaluate((form) => form.submit());
	// The server's rejection is an error callout in the form (plan task M6.1).
	await expect(page.locator('#remove-form .workbench-callout--error')).toContainText('No values');
	await capture(page, 'remove-empty-request-error-1440.png');
	await page.locator('#subj').fill('<urn:visual:alice>');
	await page.locator('#pred').fill('<urn:visual:name>');
	await page.locator('#remove-form button[type="submit"]').click();
	await page.getByRole('dialog').getByRole('button', { name: 'Remove statements' }).click();
	await waitForWriteDone(page, 'remove');
	await capture(page, 'remove-success-1440.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/clear`);
	await expect(page.locator('#clear-warning')).toBeVisible();
	await capture(page, 'clear-warning-before-operation-1440.png');
	// Clear chooses a listed graph and confirms in a dialog (plan task M6.4).
	await page.locator('#context').selectOption('<urn:visual:people>');
	await page.locator('#clear-form button[type="submit"]').click();
	await page.getByRole('dialog', { name: 'Clear graph?' }).getByRole('button', { name: 'Clear graph' }).click();
	await waitForWriteDone(page, 'clear');
	await capture(page, 'clear-named-graph-success-1440.png');
	const size = await request.get(`${REPOSITORY_URL}/size`);
	expect(size.ok()).toBeTruthy();
	expect(Number((await size.text()).trim())).toBeGreaterThan(0);

	await openPage(page, `repositories/${REPOSITORY_ID}/query`);
	await expect(page.locator('#query-cancel')).toBeDisabled();
	await capture(page, 'query-idle-cancel-disabled-1440.png');
	await page.locator('#save-query-toggle').click();
	await expect(page.locator('#save-query-panel')).toBeVisible();
	await expect(page.locator('#save')).toBeDisabled();
	await capture(page, 'query-save-disabled-until-name-1440.png');
	await page.locator('#query-name').pressSequentially(`visual-${RUN_ID}`.slice(0, 32));
	await expect(page.locator('#save')).toBeEnabled();
	await page.locator('#save').click();
	await expect(page.locator('#save-feedback')).toHaveText('Query saved.');
	await capture(page, 'query-save-success-1440.png');

	await setCodeMirror(page, 'SELECT ?s WHERE { ?s <urn:visual:name> ?name }');
	await page.locator('#exec').click();
	const resultFrame = page.frameLocator('#query-results-frame');
	await expect(resultFrame.locator('table.data tbody tr')).toHaveCount(1);
	await capture(page, 'query-success-results-1440.png');

	await setCodeMirror(page, 'SELECT WHERE {');
	await page.locator('#exec').click();
	await expect(resultFrame.locator('.error, [role="alert"]')).toBeVisible();
	await capture(page, 'query-invalid-sparql-error-1440.png');

	await page.setViewportSize({ width: 390, height: 900 });
	await page.reload({ waitUntil: 'domcontentloaded' });
	await setCodeMirror(page, 'SELECT ?s WHERE { ?s <urn:visual:name> ?name }');
	let releaseBlockedRequest;
	let queryRequestReceived;
	const blockedRequest = new Promise(resolve => {
		releaseBlockedRequest = resolve;
	});
	const requestReceived = new Promise(resolve => {
		queryRequestReceived = resolve;
	});
	await page.route(url => url.pathname.endsWith('/query') && url.searchParams.get('action') === 'exec', async route => {
		queryRequestReceived();
		await blockedRequest;
		try {
			await route.abort();
		} catch (error) {
			// Cancel already removed the iframe request; this is expected after the UI response is asserted.
		}
	});
	await page.locator('#exec').click();
	await requestReceived;
	await expect(page.locator('#query-results-loading')).toBeVisible();
	await expect(page.locator('#query-cancel')).toBeEnabled();
	await capture(page, 'query-loading-cancel-enabled-390.png');
	await page.locator('#query-cancel').click();
	await expect(page.locator('#query-results-status')).toHaveText('Query cancelled.');
	await expect(page.locator('#query-cancel')).toBeDisabled();
	await capture(page, 'query-cancelled-loading-cleared-390.png');
	releaseBlockedRequest();
	await page.unrouteAll({ behavior: 'wait' });

	await page.setViewportSize({ width: 1440, height: 1000 });
	await openPage(page, 'repositories/NONE/delete');
	await expect(page.locator('#delete-feedback')).toBeEmpty();
	await page.locator('#id').selectOption(DELETE_REPOSITORY_ID);
	await page.route(url => url.pathname.endsWith('/delete') && url.searchParams.has('checkSafe'), route =>
		route.fulfill({ status: 503, contentType: 'text/plain', body: 'fixture safety-check failure' }));
	await page.locator('#delete-actions button[type="submit"]').click();
	await expect(page.locator('#delete-feedback')).toContainText('problem with the server');
	await capture(page, 'delete-safety-check-error-1440.png');
	await page.unrouteAll();
	// Deleting asks for the typed repository id in a dialog (plan task M6.6).
	await page.locator('#delete-actions button[type="submit"]').click();
	const deleteDialog = page.getByRole('dialog', { name: `Delete repository ${DELETE_REPOSITORY_ID}?` });
	await deleteDialog.getByRole('textbox').fill(DELETE_REPOSITORY_ID);
	await deleteDialog.getByRole('button', { name: 'Delete repository' }).click();
	await expect(page).toHaveURL(/\/rdf4j-workbench\/repositories\/NONE\/repositories(?:[?#]|$)/);
	await waitForRoute(page, 'repositories');
	await expect.poll(async () => {
		const status = (await request.get(DELETE_REPOSITORY_URL)).status();
		return status === 400 || status === 404;
	}).toBeTruthy();
	await capture(page, 'delete-disposable-repository-success-1440.png');

	expect(errors, 'browser page errors during fixture operations').toEqual([]);
	console.log('OPERATION_STATE_COVERAGE', JSON.stringify({
		repositoryId: REPOSITORY_ID,
		deleteRepositoryId: DELETE_REPOSITORY_ID,
		states: ['disabled source fields', 'enabled source field', 'success redirects', 'unsupported format error',
			'SPARQL update error', 'empty remove error', 'clear warning', 'query save success', 'query results',
			'query error', 'loading', 'cancel enabled', 'cancelled', 'delete safety-check error', 'delete success']
	}));
});

async function createRepository(request, repositoryId) {
	const response = await request.put(`${SERVER_BASE_URL}/repositories/${repositoryId}`, {
		headers: { 'Content-Type': 'text/turtle' },
		data: repositoryConfiguration(repositoryId)
	});
	expect([200, 201, 204]).toContain(response.status());
}

async function openPage(page, route) {
	await page.goto(`${WORKBENCH_BASE_URL}/${route}`, { waitUntil: 'domcontentloaded' });
	await page.locator('#workbench-page-surface').waitFor({ state: 'visible', timeout: 15_000 });
	await page.evaluate(() => document.fonts.ready);
}

async function setCodeMirror(page, query) {
	await page.locator('.CodeMirror').first().evaluate((editor, value) => editor.CodeMirror.setValue(value), query);
}

async function capture(page, fileName) {
	await page.screenshot({
		path: path.join(SCREENSHOT_DIRECTORY, fileName),
		fullPage: true,
		animations: 'disabled',
		caret: 'hide'
	});
}

function repositoryConfiguration(repositoryId) {
	return `@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix config: <tag:rdf4j.org,2023:config/>.
[] a config:Repository ; config:rep.id "${repositoryId}" ; rdfs:label "Workbench disposable operation fixture" ;
   config:rep.impl [ config:rep.type "openrdf:SailRepository" ;
      config:sail.impl [ config:sail.type "openrdf:MemoryStore" ] ].`;
}
