/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

// @ts-check
const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');

const SERVER_BASE_URL = (process.env.RDF4J_SERVER_BASE_URL || 'http://127.0.0.1:8090/rdf4j-server').replace(/\/+$/, '');
const WORKBENCH_BASE_URL = (process.env.RDF4J_WORKBENCH_BASE_URL || 'http://127.0.0.1:8090/rdf4j-workbench').replace(/\/+$/, '');
const ARTIFACT_DIRECTORY = process.env.WORKBENCH_VISUAL_REFINEMENT_DIRECTORY
	|| path.resolve(__dirname, '../../output/workbench-visual-refinement');
const SCREENSHOT_DIRECTORY = path.join(ARTIFACT_DIRECTORY, 'final', 'states');
const REPOSITORY_ID = `workbench-visual-pane-states-${process.pid}-${Date.now()}`;
const REPOSITORY_URL = `${SERVER_BASE_URL}/repositories/${REPOSITORY_ID}`;

test.beforeAll(async ({ request }) => {
	fs.mkdirSync(SCREENSHOT_DIRECTORY, { recursive: true });
	const response = await request.put(REPOSITORY_URL, {
		headers: { 'Content-Type': 'text/turtle' },
		data: repositoryConfiguration(REPOSITORY_ID)
	});
	expect([200, 201, 204]).toContain(response.status());
	const loaded = await request.post(`${REPOSITORY_URL}/statements`, {
		headers: { 'Content-Type': 'application/n-quads' },
		data: [
			'<urn:visual:alice> <urn:visual:name> "Alice" .',
			'<urn:visual:bob> <urn:visual:name> "Bob" .',
			'<urn:visual:alice> <urn:visual:type> <urn:visual:Person> <urn:visual:people> .',
			'<urn:visual:bob> <urn:visual:type> <urn:visual:Person> <urn:visual:people> .'
		].join('\n')
	});
	expect([200, 201, 204]).toContain(loaded.status());
});

test.afterAll(async ({ request }) => {
	const response = await request.delete(REPOSITORY_URL);
	expect([200, 204, 404]).toContain(response.status());
});

test('captures actual query explanation, comparison, result disclosure, and form states', async ({ page }) => {
	test.setTimeout(180_000);
	const browserErrors = [];
	page.on('pageerror', error => browserErrors.push(error.message));
	page.on('console', message => {
		if (message.type() === 'error') {
			browserErrors.push(message.text());
		}
	});
	await page.setViewportSize({ width: 1440, height: 1000 });
	await setTheme(page, 'light');
	await openPage(page, `repositories/${REPOSITORY_ID}/query`);
	await setPrimaryQuery(page, 'SELECT ?s WHERE { ?s <urn:visual:name> ?name }');
	await page.locator('#explain-trigger').click();
	await waitForExplanation(page, '#query-explanation');
	await expect(page.locator('#query-explanation')).toHaveAttribute('data-format', 'text');
	await captureState(page, 'query-explanation-text-1440-light.png');

	await page.locator('#explanation-settings-toggle').press('Enter');
	await expect(page.locator('#explanation-settings-toggle')).toHaveAttribute('aria-expanded', 'true');
	await expect(page.locator('#explanation-settings-panel')).toBeVisible();
	await captureState(page, 'query-explanation-config-open-1440-light.png');
	await page.locator('#explanation-settings-toggle').press('Enter');
	await expect(page.locator('#explanation-settings-toggle')).toHaveAttribute('aria-expanded', 'false');

	for (const format of ['dot', 'json']) {
		await page.locator('#explain-format').selectOption(format);
		await page.locator('#rerun-explanation').click();
		await waitForRenderedFormat(page, format);
		const renderer = page.locator(format === 'dot' ? '#query-explanation-dot-view' : '#query-explanation-json-view');
		await expect(renderer).toBeVisible();
		const rendererContent = await renderer.evaluate(element => ({
			textLength: element.textContent.trim().length,
			svgCount: element.querySelectorAll('svg').length,
			childCount: element.children.length
		}));
		console.log(`QUERY_EXPLANATION_RENDERER ${format} ${JSON.stringify(rendererContent)}`);
		expect(rendererContent.childCount + rendererContent.textLength).toBeGreaterThan(0);
		await captureState(page, `query-explanation-${format}-1440-light.png`);
	}

	await page.locator('#explain-format').selectOption('text');
	await page.locator('#rerun-explanation').click();
	await waitForExplanation(page, '#query-explanation');
	await expect(page.locator('#query-explanation')).toHaveAttribute('data-format', 'text');
	await page.locator('#compare-toggle').click();
	await expect(page.locator('#query-compare-pane')).toBeVisible();
	await expect(page.locator('.query-compare-pane .CodeMirror')).toHaveCount(2);
	await setCompareQueries(page,
		'SELECT ?s WHERE { ?s <urn:visual:name> ?name }',
		'SELECT ?s WHERE { ?s <urn:visual:type> <urn:visual:Person> }');
	await page.locator('#explain-compare-trigger').click();
	await waitForComparison(page);
	await captureState(page, 'query-compare-explanations-1440-light.png');
	await expect(page.locator('#query-diff-trigger')).toBeEnabled();
	await page.locator('#query-diff-trigger').click();
	await expect(page.locator('#query-diff-modal')).toHaveClass(/query-diff-modal--open/);
	const queryDiffRows = await page.locator('#query-diff-query .query-diff-row').count();
	const explanationDiffRows = await page.locator('#query-diff-explanation .query-diff-row').count();
	expect(queryDiffRows).toBeGreaterThan(0);
	expect(explanationDiffRows).toBeGreaterThan(0);
	await captureState(page, 'query-compare-diff-open-1440-light.png');
	await page.locator('#query-diff-close').click();
	await expect(page.locator('#query-diff-modal')).not.toHaveClass(/query-diff-modal--open/);
	await page.setViewportSize({ width: 390, height: 900 });
	await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
	await captureState(page, 'query-compare-explanations-390-light.png');
	await page.setViewportSize({ width: 1440, height: 1000 });

	await page.goto(`${WORKBENCH_BASE_URL}/repositories/${REPOSITORY_ID}/query`);
	await page.locator('.CodeMirror').first().evaluate((editor, query) => editor.CodeMirror.setValue(query),
		'SELECT * WHERE { VALUES ?s { "one" "two" "three" } }');
	await page.locator('#exec').click();
	const resultFrame = page.frameLocator('#query-results-frame');
	await expect(resultFrame.locator('table.data tbody tr')).toHaveCount(3);
	await resultFrame.locator('#query-result-download-toggle').press('Enter');
	await expect(resultFrame.locator('#query-result-download-toggle')).toHaveAttribute('aria-expanded', 'true');
	await expect(resultFrame.locator('#Accept')).toBeVisible();
	await captureState(page, 'query-result-download-open-1440-light.png');
	await resultFrame.locator('#query-result-options-toggle').press('Enter');
	await expect(resultFrame.locator('#query-result-options-toggle')).toHaveAttribute('aria-expanded', 'true');
	await expect(resultFrame.locator('#limit_query')).toBeVisible();
	await captureState(page, 'query-result-options-open-1440-light.png');

	await openPage(page, `repositories/${REPOSITORY_ID}/add`);
	await page.locator('#add-import-settings > summary').press('Enter');
	await expect(page.locator('#add-import-settings')).toHaveAttribute('open', '');
	await captureState(page, 'add-advanced-open-1440-light.png');
	await openPage(page, `repositories/${REPOSITORY_ID}/export`);
	await page.locator('#export-result-options > summary').press('Enter');
	await expect(page.locator('#export-result-options')).toHaveAttribute('open', '');
	await captureState(page, 'export-options-open-1440-light.png');

	expect(browserErrors).toEqual([]);
});

async function setTheme(page, theme) {
	await openPage(page, 'repositories/NONE/repositories');
	await page.locator('#workbench-theme').selectOption(theme);
	await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
}

async function openPage(page, route) {
	await page.goto(`${WORKBENCH_BASE_URL}/${route}`, { waitUntil: 'domcontentloaded' });
	await page.locator('#workbench-page-surface').waitFor({ state: 'visible', timeout: 15_000 });
	await page.evaluate(() => document.fonts.ready);
}

async function setPrimaryQuery(page, query) {
	await page.locator('.CodeMirror').first().evaluate((editor, value) => editor.CodeMirror.setValue(value), query);
}

async function setCompareQueries(page, primary, compare) {
	await page.evaluate(({ primary, compare }) => {
		const editors = document.querySelectorAll('.query-compare-pane .CodeMirror');
		editors[0].CodeMirror.setValue(primary);
		editors[1].CodeMirror.setValue(compare);
	}, { primary, compare });
}

async function waitForExplanation(page, selector) {
	await page.waitForFunction(explanationSelector => {
		const explanation = document.querySelector(explanationSelector);
		const status = document.querySelector('#query-explanation-status');
		return explanation && explanation.getAttribute('data-format') && explanation.textContent.trim().length > 0
			&& !(status && /loading/i.test(status.textContent));
	}, selector);
	await expect(page.locator('.query-explanation-overlay--visible')).toHaveCount(0);
}

async function waitForRenderedFormat(page, format) {
	await page.waitForFunction(requestedFormat => {
		const explanation = document.querySelector('#query-explanation');
		if (!explanation || explanation.getAttribute('data-format') !== requestedFormat) {
			return false;
		}
		if (requestedFormat === 'text') {
			return explanation.textContent.trim().length > 0;
		}
		const view = document.getElementById(`query-explanation-${requestedFormat}-view`);
		return Boolean(view && (view.textContent.trim().length > 0 || view.children.length > 0));
	}, format);
	await expect(page.locator('.query-explanation-overlay--visible')).toHaveCount(0);
}

async function waitForComparison(page) {
	await page.waitForFunction(() => {
		const selectors = ['#query-explanation', '#query-explanation-compare'];
		return selectors.every(selector => {
			const explanation = document.querySelector(selector);
			return explanation && explanation.textContent.trim().length > 0;
		});
	});
	await expect(page.locator('.query-explanation-overlay--visible')).toHaveCount(0);
}

async function captureState(page, fileName) {
	await page.screenshot({
		path: path.join(SCREENSHOT_DIRECTORY, fileName),
		fullPage: true,
		animations: 'disabled',
		caret: 'hide'
	});
}

function repositoryConfiguration(repositoryId) {
	return `@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix config: <tag:rdf4j.org,2023:config/>.
[] a config:Repository ; config:rep.id "${repositoryId}" ; rdfs:label "Workbench visual state fixture" ;
   config:rep.impl [ config:rep.type "openrdf:SailRepository" ;
      config:sail.impl [ config:sail.type "openrdf:MemoryStore" ] ].`;
}
