/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude

// @ts-check
const { test, expect } = require('@playwright/test');
const {
	createSeededRepository,
	deleteRepository,
	openQueryPage,
	repositoryPageUrl,
	runQuery,
	serverBaseUrl,
	uniqueRepositoryId
} = require('./workbench-test-helpers.js');

const REPOSITORY_ID = uniqueRepositoryId('workbench-design-system');

test.describe.configure({ mode: 'serial' });

test.beforeAll(async ({ request }) => {
	await createSeededRepository(request, serverBaseUrl(), REPOSITORY_ID, { graphs: ['bsbm', 'spl'] });
});

test.afterAll(async ({ request }) => {
	await deleteRepository(request, serverBaseUrl(), REPOSITORY_ID);
});

test('result headings show variable names exactly as written', async ({ page }) => {
	await openQueryPage(page, REPOSITORY_ID);
	await runQuery(page, 'SELECT ?num1 ?x_y WHERE { BIND(1 AS ?num1) BIND(2 AS ?x_y) }');
	const headings = page.locator('#query-results table.data thead th');
	await expect(headings).toHaveCount(2);
	const rendered = await headings.evaluateAll((cells) => cells.map((cell) => ({
		text: cell.innerText.trim(),
		transform: getComputedStyle(cell).textTransform
	})));
	expect(rendered.map((cell) => cell.transform)).toEqual(['none', 'none']);
	expect(rendered.map((cell) => cell.text)).toEqual(['num1', 'x_y']);
});

test('query page actions share one button height and one secondary border', async ({ page }) => {
	await openQueryPage(page, REPOSITORY_ID);
	const metrics = await page.evaluate(() => ['#exec', '#explain-trigger', '#save-query-toggle', '#query-options-toggle']
		.map((selector) => {
			const element = document.querySelector(selector);
			const style = getComputedStyle(element);
			return { selector, height: element.getBoundingClientRect().height, border: style.borderTopColor };
		}));
	const heights = metrics.map((metric) => Math.round(metric.height));
	expect(new Set(heights).size, JSON.stringify(metrics)).toBe(1);
	const secondaryBorders = metrics.slice(1).map((metric) => metric.border);
	expect(new Set(secondaryBorders).size, JSON.stringify(metrics)).toBe(1);
});

/** Returns the first visible card (bordered, filled box) inside the page surface and the surface's width. */
async function firstCardGeometry(page) {
	return page.evaluate(() => {
		const surface = document.querySelector('#workbench-page-surface');
		const isCard = (element) => {
			const style = getComputedStyle(element);
			const rect = element.getBoundingClientRect();
			const filled = style.backgroundColor !== 'rgba(0, 0, 0, 0)' && style.backgroundColor !== 'transparent';
			return rect.width > 0 && rect.height > 0 && filled
				&& (parseFloat(style.borderTopWidth) > 0 || style.boxShadow !== 'none');
		};
		const candidates = Array.from(surface.querySelectorAll('*')).filter(isCard);
		const card = candidates[0];
		const rect = card.getBoundingClientRect();
		const surfaceRect = surface.getBoundingClientRect();
		return {
			card: card.tagName.toLowerCase() + (card.id ? '#' + card.id : '') + '.' + Array.from(card.classList).join('.'),
			left: rect.left, right: rect.right, width: rect.width, surfaceWidth: surfaceRect.width
		};
	});
}

test('browsing pages share one content width and form pages share one form width', async ({ page }) => {
	await page.setViewportSize({ width: 1440, height: 900 });
	const product1 = encodeURIComponent('<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product1>');
	const browsing = ['summary', 'namespaces', 'types', 'query', 'explore?resource=' + product1];
	const rights = [];
	for (const view of browsing) {
		await page.goto(repositoryPageUrl(REPOSITORY_ID, view), { waitUntil: 'networkidle' });
		await page.locator('#workbench-page-surface').waitFor();
		rights.push({ view, ...(await firstCardGeometry(page)) });
	}
	const firstRight = rights[0].right;
	for (const geometry of rights) {
		expect(Math.abs(geometry.right - firstRight), JSON.stringify(rights)).toBeLessThanOrEqual(1);
	}
	const forms = [`${REPOSITORY_ID}/add`, `${REPOSITORY_ID}/remove`, `${REPOSITORY_ID}/clear`,
		`${REPOSITORY_ID}/export`, 'NONE/create', 'NONE/delete', 'NONE/server'];
	for (const path of forms) {
		const [repositoryId, view] = path.split('/');
		await page.goto(repositoryPageUrl(repositoryId, view), { waitUntil: 'networkidle' });
		await page.locator('#workbench-page-surface').waitFor();
		const geometry = await firstCardGeometry(page);
		expect(Math.abs(geometry.width - Math.min(760, geometry.surfaceWidth)), path + ' ' + JSON.stringify(geometry))
			.toBeLessThanOrEqual(1);
	}
});
