/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.estimation;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;

/** Fixed-capacity Space-Saving heavy-key directory backed only by primitive arrays. */
final class PrimitiveSpaceSaving {

	record Offer(int slot, boolean replaced, long previousKey) {
	}

	private final long[] keys;
	private final long[] counts;
	private final long[] errors;
	private final byte[] occupied;
	private final int[] heap;
	private final int[] heapPositions;
	private final int[] index;
	private final int indexMask;
	private int size;

	PrimitiveSpaceSaving(int capacity) {
		if (capacity < 1) {
			throw new IllegalArgumentException("capacity must be positive: " + capacity);
		}
		keys = new long[capacity];
		counts = new long[capacity];
		errors = new long[capacity];
		occupied = new byte[capacity];
		heap = new int[capacity];
		heapPositions = new int[capacity];
		int indexLength = ceilingPowerOfTwo(Math.max(4, Math.multiplyExact(capacity, 4)));
		index = new int[indexLength];
		indexMask = indexLength - 1;
	}

	Offer offer(long key, long increment) {
		if (increment < 1L) {
			throw new IllegalArgumentException("increment must be positive: " + increment);
		}
		int existing = findSlot(key);
		if (existing >= 0) {
			counts[existing] = saturatingAdd(counts[existing], increment);
			siftDown(heapPositions[existing]);
			return new Offer(existing, false, key);
		}
		if (size < keys.length) {
			int slot = size;
			keys[slot] = key;
			counts[slot] = increment;
			errors[slot] = 0L;
			occupied[slot] = 1;
			heap[size] = slot;
			heapPositions[slot] = size;
			size++;
			insertIndex(slot);
			siftUp(size - 1);
			return new Offer(slot, false, 0L);
		}

		int slot = heap[0];
		long previousKey = keys[slot];
		long minimum = counts[slot];
		removeIndex(previousKey);
		keys[slot] = key;
		errors[slot] = minimum;
		counts[slot] = saturatingAdd(minimum, increment);
		insertIndex(slot);
		siftDown(0);
		return new Offer(slot, true, previousKey);
	}

	boolean contains(long key) {
		return findSlot(key) >= 0;
	}

	long estimate(long key) {
		int slot = findSlot(key);
		return slot < 0 ? 0L : counts[slot];
	}

	long error(long key) {
		int slot = findSlot(key);
		return slot < 0 ? 0L : errors[slot];
	}

	int slot(long key) {
		return findSlot(key);
	}

	long keyAt(int slot) {
		checkSlot(slot);
		return keys[slot];
	}

	long countAt(int slot) {
		checkSlot(slot);
		return counts[slot];
	}

	int size() {
		return size;
	}

	int capacity() {
		return keys.length;
	}

	long allocatedBytes() {
		return (long) keys.length * Long.BYTES * 3L
				+ occupied.length
				+ (long) (heap.length + heapPositions.length + index.length) * Integer.BYTES;
	}

	void writeTo(DataOutput output) throws IOException {
		output.writeInt(keys.length);
		output.writeInt(size);
		for (int slot = 0; slot < size; slot++) {
			output.writeLong(keys[slot]);
			output.writeLong(counts[slot]);
			output.writeLong(errors[slot]);
		}
	}

	static PrimitiveSpaceSaving readFrom(DataInput input, int maximumCapacity) throws IOException {
		int capacity = input.readInt();
		int size = input.readInt();
		if (capacity < 1 || capacity > maximumCapacity || size < 0 || size > capacity) {
			throw new IOException("invalid Space-Saving dimensions: " + size + "/" + capacity);
		}
		PrimitiveSpaceSaving result = new PrimitiveSpaceSaving(capacity);
		for (int slot = 0; slot < size; slot++) {
			long key = input.readLong();
			long count = input.readLong();
			long error = input.readLong();
			if (count < 0L || error < 0L || error > count || result.contains(key)) {
				throw new IOException("invalid Space-Saving entry");
			}
			result.keys[slot] = key;
			result.counts[slot] = count;
			result.errors[slot] = error;
			result.occupied[slot] = 1;
			result.heap[slot] = slot;
			result.heapPositions[slot] = slot;
			result.size++;
			result.insertIndex(slot);
		}
		for (int position = result.size / 2; position >= 0; position--) {
			result.siftDown(position);
		}
		return result;
	}

	private int findSlot(long key) {
		int position = hashPosition(key);
		while (true) {
			int entry = index[position];
			if (entry == 0) {
				return -1;
			}
			int slot = entry - 1;
			if (occupied[slot] != 0 && keys[slot] == key) {
				return slot;
			}
			position = (position + 1) & indexMask;
		}
	}

	private void insertIndex(int slot) {
		int position = hashPosition(keys[slot]);
		while (index[position] != 0) {
			position = (position + 1) & indexMask;
		}
		index[position] = slot + 1;
	}

	private void removeIndex(long key) {
		int position = hashPosition(key);
		while (index[position] != 0) {
			int slot = index[position] - 1;
			if (keys[slot] == key) {
				index[position] = 0;
				int next = (position + 1) & indexMask;
				while (index[next] != 0) {
					int reinsert = index[next] - 1;
					index[next] = 0;
					insertIndex(reinsert);
					next = (next + 1) & indexMask;
				}
				return;
			}
			position = (position + 1) & indexMask;
		}
	}

	private void siftUp(int position) {
		while (position > 0) {
			int parent = (position - 1) >>> 1;
			if (compareSlots(heap[parent], heap[position]) <= 0) {
				return;
			}
			swapHeap(parent, position);
			position = parent;
		}
	}

	private void siftDown(int position) {
		while (position >= 0 && position < size) {
			int left = (position << 1) + 1;
			if (left >= size) {
				return;
			}
			int right = left + 1;
			int smallest = right < size && compareSlots(heap[right], heap[left]) < 0 ? right : left;
			if (compareSlots(heap[position], heap[smallest]) <= 0) {
				return;
			}
			swapHeap(position, smallest);
			position = smallest;
		}
	}

	private int compareSlots(int left, int right) {
		int countOrder = Long.compare(counts[left], counts[right]);
		return countOrder != 0 ? countOrder : Long.compareUnsigned(keys[left], keys[right]);
	}

	private void swapHeap(int left, int right) {
		int leftSlot = heap[left];
		int rightSlot = heap[right];
		heap[left] = rightSlot;
		heap[right] = leftSlot;
		heapPositions[leftSlot] = right;
		heapPositions[rightSlot] = left;
	}

	private int hashPosition(long key) {
		return (int) QuadHash.mix64(key) & indexMask;
	}

	private void checkSlot(int slot) {
		if (slot < 0 || slot >= size || occupied[slot] == 0) {
			throw new IndexOutOfBoundsException("slot: " + slot);
		}
	}

	private static int ceilingPowerOfTwo(int value) {
		if (value > 1 << 29) {
			throw new IllegalArgumentException("capacity is too large: " + value);
		}
		return 1 << (32 - Integer.numberOfLeadingZeros(value - 1));
	}

	private static long saturatingAdd(long left, long right) {
		return Long.MAX_VALUE - left < right ? Long.MAX_VALUE : left + right;
	}
}
