/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.estimation;

import java.util.Arrays;
import java.util.OptionalDouble;

import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.DistributionSketch;

/** Query-local distribution view derived from bounded primitive witnesses. */
final class PrimitiveDistributionSketch implements DistributionSketch {

	private final long[] hashes;
	private final double[] frequencies;
	private final double rows;
	private final double distinctRows;
	private final boolean complete;

	private PrimitiveDistributionSketch(long[] hashes, double[] frequencies, double rows, double distinctRows,
			boolean complete) {
		this.hashes = hashes;
		this.frequencies = frequencies;
		this.rows = rows;
		this.distinctRows = distinctRows;
		this.complete = complete;
	}

	static PrimitiveDistributionSketch from(PrimitiveBottomK.ProjectionSample sample, double estimatedRows,
			boolean complete) {
		long[] samples = sample.hashes();
		if (samples.length == 0 || estimatedRows <= 0.0d) {
			return new PrimitiveDistributionSketch(new long[0], new double[0], Math.max(0.0d, estimatedRows), 0.0d,
					complete);
		}
		int unique = 1;
		for (int index = 1; index < samples.length; index++) {
			if (samples[index] != samples[index - 1]) {
				unique++;
			}
		}
		long[] hashes = new long[unique];
		double[] frequencies = new double[unique];
		double scale = complete ? 1.0d : Math.max(1.0d, estimatedRows / samples.length);
		int output = 0;
		int runStart = 0;
		while (runStart < samples.length) {
			int runEnd = runStart + 1;
			while (runEnd < samples.length && samples[runEnd] == samples[runStart]) {
				runEnd++;
			}
			hashes[output] = samples[runStart];
			frequencies[output] = (runEnd - runStart) * scale;
			output++;
			runStart = runEnd;
		}
		double distinct = complete ? unique : Math.min(estimatedRows, unique * scale);
		return new PrimitiveDistributionSketch(hashes, frequencies, estimatedRows, distinct, complete);
	}

	static PrimitiveDistributionSketch merge(PrimitiveDistributionSketch left, PrimitiveDistributionSketch right) {
		long[] hashes = new long[left.hashes.length + right.hashes.length];
		double[] frequencies = new double[hashes.length];
		int leftIndex = 0;
		int rightIndex = 0;
		int output = 0;
		while (leftIndex < left.hashes.length || rightIndex < right.hashes.length) {
			if (rightIndex >= right.hashes.length
					|| leftIndex < left.hashes.length
							&& Long.compareUnsigned(left.hashes[leftIndex], right.hashes[rightIndex]) < 0) {
				hashes[output] = left.hashes[leftIndex];
				frequencies[output++] = left.frequencies[leftIndex++];
			} else if (leftIndex >= left.hashes.length
					|| Long.compareUnsigned(right.hashes[rightIndex], left.hashes[leftIndex]) < 0) {
				hashes[output] = right.hashes[rightIndex];
				frequencies[output++] = right.frequencies[rightIndex++];
			} else {
				hashes[output] = left.hashes[leftIndex];
				frequencies[output++] = left.frequencies[leftIndex++] + right.frequencies[rightIndex++];
			}
		}
		return new PrimitiveDistributionSketch(Arrays.copyOf(hashes, output), Arrays.copyOf(frequencies, output),
				left.rows + right.rows, Math.min(left.rows + right.rows, output), left.complete && right.complete);
	}

	@Override
	public double distinctRows() {
		return distinctRows;
	}

	@Override
	public OptionalDouble totalRows() {
		return OptionalDouble.of(rows);
	}

	@Override
	public boolean equals(Object object) {
		return this == object
				|| object instanceof PrimitiveDistributionSketch other
						&& complete == other.complete
						&& Double.compare(rows, other.rows) == 0
						&& Double.compare(distinctRows, other.distinctRows) == 0
						&& Arrays.equals(hashes, other.hashes)
						&& Arrays.equals(frequencies, other.frequencies);
	}

	@Override
	public int hashCode() {
		int result = Arrays.hashCode(hashes);
		result = 31 * result + Arrays.hashCode(frequencies);
		result = 31 * result + Double.hashCode(rows);
		result = 31 * result + Double.hashCode(distinctRows);
		return 31 * result + Boolean.hashCode(complete);
	}

	@Override
	public OptionalDouble innerProduct(DistributionSketch other) {
		if (!(other instanceof PrimitiveDistributionSketch right)) {
			return OptionalDouble.empty();
		}
		double result = 0.0d;
		int leftIndex = 0;
		int rightIndex = 0;
		while (leftIndex < hashes.length && rightIndex < right.hashes.length) {
			int comparison = Long.compareUnsigned(hashes[leftIndex], right.hashes[rightIndex]);
			if (comparison < 0) {
				leftIndex++;
			} else if (comparison > 0) {
				rightIndex++;
			} else {
				result += frequencies[leftIndex++] * right.frequencies[rightIndex++];
			}
		}
		return OptionalDouble.of(result);
	}

	@Override
	public OptionalDouble highQualityInnerProduct(DistributionSketch other) {
		if (!(other instanceof PrimitiveDistributionSketch right) || !complete || !right.complete) {
			return OptionalDouble.empty();
		}
		return innerProduct(other);
	}

	@Override
	public OptionalDouble overlapDistinctRows(DistributionSketch other) {
		if (!(other instanceof PrimitiveDistributionSketch right)) {
			return OptionalDouble.empty();
		}
		int overlap = 0;
		int leftIndex = 0;
		int rightIndex = 0;
		while (leftIndex < hashes.length && rightIndex < right.hashes.length) {
			int comparison = Long.compareUnsigned(hashes[leftIndex], right.hashes[rightIndex]);
			if (comparison < 0) {
				leftIndex++;
			} else if (comparison > 0) {
				rightIndex++;
			} else {
				overlap++;
				leftIndex++;
				rightIndex++;
			}
		}
		double scale = complete && right.complete || overlap == 0 ? 1.0d
				: Math.min(distinctRows / Math.max(1, hashes.length),
						right.distinctRows / Math.max(1, right.hashes.length));
		return OptionalDouble.of(Math.min(Math.min(distinctRows, right.distinctRows), overlap * scale));
	}
}
