/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.proxy.config;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.InputStream;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import org.junit.jupiter.api.Test;

class WorkbenchPolicyTest {

	/**
	 * Source-control-to-feature matrix reviewed against query.xsl, tuple.xsl, graph.xsl, and query.js. Result formats
	 * and page directions are separate capabilities because the source exposes distinct controls for them. Rerun,
	 * compare-refresh, and editor fullscreen are client-side presentation controls, not authorization boundaries. Rerun
	 * and compare-refresh share the server's action=explain operation; server enforcement remains on query-explain and
	 * explicit Explain options. YASQE's editor fullscreen button and F11 shortcut are separate from result fullscreen.
	 */
	/** Policy feature identifiers rendered by the Workbench query and result views. */
	private static final Set<String> BUILT_IN_QUERY_FEATURE_IDS = Set.of(
			"query-execution",
			"query-language",
			"query-save",
			"query-private-save",
			"query-options",
			"query-explain",
			"explain-level-unoptimized",
			"explain-level-optimized",
			"explain-level-executed",
			"explain-level-telemetry",
			"explain-level-timed",
			"explain-format-text",
			"explain-format-dot",
			"explain-format-json",
			"explain-view-text",
			"explain-view-dot",
			"explain-view-json",
			"explain-download",
			"explain-copy",
			"explain-cancel",
			"query-compare",
			"query-diff",
			"query-swap",
			"result-layout",
			"result-wrap",
			"result-totals",
			"result-paging",
			"result-download-format",
			"result-download-limit",
			"result-fullscreen",
			"query-rerun",
			"query-cancel",
			"editor-namespaces",
			"editor-sidebar",
			"result-page-size",
			"query-timeout",
			"query-inferred-statements",
			"result-download",
			"result-show-datatypes",
			"explain-highlight-syntax",
			"explain-highlight-hotspot",
			"explain-property-selection",
			"editor-fullscreen",
			"result-download-format-tuple",
			"result-download-format-graph",
			"result-page-previous",
			"result-page-next");

	@Test
	void omissionAndHiddenGroupDenyCanonicalPagesEvenWhenVisibleItemLinksToOne() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "query-shortcut,summary,update,add");
		properties.setProperty("menu.groups", "server,explore,modify,system");
		properties.setProperty("menu.item.query-shortcut.href", "/query");
		properties.setProperty("menu.item.query-shortcut.group", "server");
		properties.setProperty("menu.group.server.visible", "true");
		properties.setProperty("menu.group.explore.visible", "false");
		properties.setProperty("menu.group.modify.visible", "true");
		properties.setProperty("menu.item.add.visible", "false");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of("query-shortcut"));

		assertThat(policy.getVisibleMenuItemIds()).contains("query-shortcut");
		assertThat(policy.isRouteAllowed("/repositories/example/query")).isFalse();
		assertThat(policy.isRouteAllowed("/repositories/example/summary")).isFalse();
		assertThat(policy.isRouteAllowed("/repositories/example/update")).isTrue();
		assertThat(policy.isRouteAllowed("/repositories/example/add")).isFalse();
		assertThat(policy.isRouteAllowed("/repositories/example/namespaces")).isFalse();
		assertThat(policy.isRouteAllowed("/repositories/example/_internal/namespaces")).isTrue();
		assertThat(policy.isRouteAllowed("/repositories/example/info")).isTrue();
	}

	@Test
	void hiddenCustomAliasDeniesItsCanonicalRouteEvenWhenBuiltInPageIsVisible() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "query,query-shortcut");
		properties.setProperty("menu.consumer-ids", "query-shortcut");
		properties.setProperty("menu.group.explore.visible", "true");
		properties.setProperty("menu.item.query-shortcut.group", "explore");
		properties.setProperty("menu.item.query-shortcut.href", "/query");
		properties.setProperty("menu.item.query-shortcut.route", "/query");
		properties.setProperty("menu.item.query-shortcut.visible", "false");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());

		assertThat(policy.getVisibleMenuItemIds()).contains("query").doesNotContain("query-shortcut");
		assertThat(policy.isRouteAllowed("/repositories/example/query")).isFalse();
	}

	@Test
	void menuItemsUseNumericOrderThenListPositionAndAreImmutable() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "custom-z,summary,query,custom-a");
		properties.setProperty("menu.groups", "custom,explore");
		properties.setProperty("menu.group.custom.visible", "true");
		properties.setProperty("menu.group.explore.visible", "true");
		properties.setProperty("menu.item.custom-z.order", "10");
		properties.setProperty("menu.item.summary.order", "10");
		properties.setProperty("menu.item.query.order", "2");
		properties.setProperty("menu.item.custom-a.order", "10");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of("custom-z", "custom-a"));

		assertThat(policy.getVisibleMenuItemIds()).containsExactly("query", "custom-z", "summary", "custom-a");
		assertThatThrownBy(() -> policy.getVisibleMenuItemIds().add("injected"))
				.isInstanceOf(UnsupportedOperationException.class);
	}

	@Test
	void unsafeMenuHrefsFailStartupValidation() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "external-tool");
		properties.setProperty("menu.groups", "custom");
		properties.setProperty("menu.group.custom.visible", "true");
		properties.setProperty("menu.item.external-tool.href", "javascript:alert(1)");

		assertThatThrownBy(() -> WorkbenchPolicy.fromProperties(properties, Set.of("external-tool")))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void queryFeaturePolicyExposesConfiguredFixedDownloadDefault() {
		Properties properties = new Properties();
		properties.setProperty("query.feature.result-download-limit.enabled", "false");
		properties.setProperty("query.download.default-limit", "0");
		properties.setProperty("theme.deployment-default", "dark");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());

		assertThat(policy.isQueryFeatureEnabled("result-download-limit")).isFalse();
		assertThat(policy.getQueryDownloadDefaultLimit()).isZero();
		assertThat(policy.getDeploymentThemeDefault()).isEqualTo("dark");
	}

	@Test
	void builtInQueryFeatureIdsAreStableImmutableAndEagerlyValidated() {
		Set<String> expected = BUILT_IN_QUERY_FEATURE_IDS;
		WorkbenchPolicy defaults = WorkbenchPolicy.fromProperties(new Properties(), Set.of());
		assertThat(expected).hasSize(47);
		assertThat(defaults.getQueryFeatureIds()).containsExactlyInAnyOrderElementsOf(expected);

		Properties properties = new Properties();
		for (String id : expected) {
			properties.setProperty("query.feature." + id + ".enabled", "false");
		}

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());

		assertThat(policy.getQueryFeatureIds()).containsExactlyInAnyOrderElementsOf(expected);
		assertThatThrownBy(() -> policy.getQueryFeatureIds().add("injected-feature"))
				.isInstanceOf(UnsupportedOperationException.class);
		for (String id : expected) {
			assertThat(policy.isQueryFeatureEnabled(id)).as(id).isFalse();
		}
	}

	@Test
	void placeholderQueryFeatureIdsAreNotBuiltInOrAcceptedAsProperties() {
		WorkbenchPolicy defaults = WorkbenchPolicy.fromProperties(new Properties(), Set.of());
		assertThat(defaults.getQueryFeatureIds()).doesNotContain("query-copy", "editor-reset");

		for (String removedId : List.of("query-copy", "editor-reset")) {
			Properties properties = new Properties();
			properties.setProperty("query.feature." + removedId + ".enabled", "true");
			assertThatThrownBy(() -> WorkbenchPolicy.fromProperties(properties, Set.of()))
					.as(removedId)
					.isInstanceOf(IllegalArgumentException.class)
					.hasMessageContaining("Unknown or undeclared Workbench property");
		}
	}

	@Test
	void packagedDefaultsEnableEveryBuiltInQueryFeature() throws Exception {
		Set<String> expected = BUILT_IN_QUERY_FEATURE_IDS;
		Properties packagedDefaults = new Properties();
		try (InputStream input = getClass().getResourceAsStream(
				"/org/eclipse/rdf4j/common/app/config/defaults/workbench.properties")) {
			assertThat(input).as("packaged Workbench defaults").isNotNull();
			packagedDefaults.load(input);
		}

		for (String id : expected) {
			assertThat(packagedDefaults.getProperty("query.feature." + id + ".enabled")).as(id).isEqualTo("true");
		}
	}

	@Test
	void invalidDeploymentThemeFailsStartupValidation() {
		Properties properties = new Properties();
		properties.setProperty("theme.deployment-default", "orange");

		assertThatThrownBy(() -> WorkbenchPolicy.fromProperties(properties, Set.of()))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void unknownWorkbenchPropertyFailsStartupValidation() {
		Properties properties = new Properties();
		properties.setProperty("workbench.unknown-option", "unexpected");

		assertThatThrownBy(() -> WorkbenchPolicy.fromProperties(properties, Set.of()))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void malformedFeatureBooleanFailsStartupValidation() {
		Properties properties = new Properties();
		properties.setProperty("query.feature.result-download-limit.enabled", "sometimes");

		assertThatThrownBy(() -> WorkbenchPolicy.fromProperties(properties, Set.of()))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void visibleMenuGroupsAndItemsExposeImmutableConfiguredMetadata() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "query,summary,update,add");
		properties.setProperty("menu.groups", "explore,modify");
		properties.setProperty("menu.group.explore.visible", "true");
		properties.setProperty("menu.group.explore.label", "Explore data");
		properties.setProperty("menu.group.explore.icon", "database");
		properties.setProperty("menu.group.explore.order", "9");
		properties.setProperty("menu.group.modify.visible", "true");
		properties.setProperty("menu.group.modify.label", "Modify data");
		properties.setProperty("menu.group.modify.icon", "edit");
		properties.setProperty("menu.group.modify.order", "2");
		properties.setProperty("menu.item.query.label", "SPARQL query");
		properties.setProperty("menu.item.query.icon", "search");
		properties.setProperty("menu.item.query.order", "4");
		properties.setProperty("menu.item.summary.order", "4");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());
		var groups = policy.getVisibleMenuGroups();

		assertThat(groups).extracting(group -> group.getId()).containsExactly("modify", "explore");
		assertThat(groups).extracting(group -> group.getLabel()).containsExactly("Modify data", "Explore data");
		assertThat(groups).extracting(group -> group.getIcon()).containsExactly("edit", "database");
		assertThat(groups).extracting(group -> group.getOrder()).containsExactly(2, 9);
		assertThat(groups.get(1).getItems()).extracting(item -> item.getId()).containsExactly("query", "summary");
		assertThat(groups.get(1).getItems().get(0).getLabel()).isEqualTo("SPARQL query");
		assertThat(groups.get(1).getItems().get(0).getIcon()).isEqualTo("search");
		assertThat(groups.get(1).getItems().get(0).getOrder()).isEqualTo(4);
		assertThat(groups.get(1).getItems().get(0).getHref()).isEqualTo("query");
		assertThatThrownBy(() -> groups.clear()).isInstanceOf(UnsupportedOperationException.class);
		assertThatThrownBy(() -> groups.get(1).getItems().clear())
				.isInstanceOf(UnsupportedOperationException.class);
	}

	@Test
	void explicitPageSettingIntersectsWithMenuVisibilityAndOmittedGroupsDenyChildren() {
		Properties pageDisabled = new Properties();
		pageDisabled.setProperty("menu.items", "summary");
		pageDisabled.setProperty("menu.group.explore.visible", "true");
		pageDisabled.setProperty("page.summary.enabled", "false");
		WorkbenchPolicy disabledPolicy = WorkbenchPolicy.fromProperties(pageDisabled, Set.of());

		assertThat(disabledPolicy.isRouteAllowed("/repositories/example/summary")).isFalse();

		Properties pageEnabledButGroupHidden = new Properties();
		pageEnabledButGroupHidden.setProperty("menu.items", "summary");
		pageEnabledButGroupHidden.setProperty("menu.group.explore.visible", "false");
		pageEnabledButGroupHidden.setProperty("page.summary.enabled", "true");
		WorkbenchPolicy hiddenGroupPolicy = WorkbenchPolicy.fromProperties(pageEnabledButGroupHidden, Set.of());

		assertThat(hiddenGroupPolicy.isRouteAllowed("/repositories/example/summary")).isFalse();

		Properties groupOmitted = new Properties();
		groupOmitted.setProperty("menu.items", "summary");
		WorkbenchPolicy omittedGroupPolicy = WorkbenchPolicy.fromProperties(groupOmitted, Set.of());

		assertThat(omittedGroupPolicy.isRouteAllowed("/repositories/example/summary")).isFalse();
	}

	@Test
	void emptyMenuIsValidAndPreservesTheRawInfoRoute() {
		Properties properties = new Properties();
		properties.setProperty("menu.items", "");

		WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());

		assertThat(policy.getVisibleMenuItemIds()).isEmpty();
		assertThat(policy.isAllPagesHidden()).isTrue();
		assertThat(policy.isRouteAllowed("/repositories/example/summary")).isFalse();
		assertThat(policy.isRouteAllowed("/repositories/example/info")).isTrue();
	}
}
