BASE <ex:>
CONSTRUCT {
  ?s0 ?p0 ( <a0> ( <b0> <c0> ) ).
  ( <a0> ( <b0> <c0> ) ) ?p0 ?o0.
}
WHERE {
  ?s1 ?p1 (), <a1>.
  ()  ?p2 ?o2.
  ?s3 ?p3 ( <a3> ).
  ?s4 ?p4 ( <a4> <b4> <c4> ).
  ?s5 ?p5 ( <a5> ( <b5> <c5> ) ).
  ( <a6> ( <b6> <c6> ) ) ?p6 ?o6.
  ( <a7> <b7> ).
  ?s8 ?p8 ( [ <a8> <b8>; <c8> <d8>, <e8> ] ).
}
