PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
SELECT * WHERE {
  ?city dbpedia-owl:country dbpedia:Belgium.

  { ?city <http://www.w3.org/2000/01/rdf-schema#label> ?label. }
  UNION
  { ?city <http://dbpedia.org/property/commonName>     ?label. }
  UNION
  { ?city <http://xmlns.com/foaf/0.1/name>             ?label. }
}
