/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.sketch;

public record OmniSketchBindingEvidence(String bindingName, double rows, double distinctRows, int witnessCount,
		OmniWitnessSet witnesses, OmniWitnessSet.SourceKind sourceKind, String relationProvenance,
		String attributeProvenance) {

	public OmniSketchBindingEvidence {
		bindingName = normalize(bindingName, "unknown");
		rows = finiteNonNegative(rows);
		distinctRows = Math.min(finiteNonNegative(distinctRows), Math.max(1.0d, rows));
		witnessCount = Math.max(0, witnessCount);
		sourceKind = sourceKind == null ? OmniWitnessSet.SourceKind.BASE : sourceKind;
		relationProvenance = normalize(relationProvenance, "unknown");
		attributeProvenance = normalize(attributeProvenance, "unknown");
	}

	private static double finiteNonNegative(double value) {
		return Double.isFinite(value) && value >= 0.0d ? value : 0.0d;
	}

	private static String normalize(String value, String fallback) {
		return value == null || value.isBlank() ? fallback : value;
	}
}
