/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.sketch;

/**
 * Exact primitive-payload and serialized footprint of a bounded sketch snapshot.
 */
public record SketchFootprint(int capacity, int retainedRows, long totalRows, boolean complete,
		long publishedPrimitiveBytes, long serializedBytes, long builderPrimitiveBytes,
		long builderPlusPublishedPeakPrimitiveBytes, long predicateSupportMin, long predicateSupportP25,
		long predicateSupportP50, long predicateSupportP75, long predicateSupportP95,
		long predicateSupportMax) {
}
