PREFIX ex: <http://example.com/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {

ex:person0 a ex:Person .

ex:person0 ex:knows1 ex:person1.
ex:person1 ex:knows2 ex:person2.
ex:person2 ex:knows3 ex:person3.

ex:person0 ex:knows1 ex:dog1.
ex:dog1 ex:knows2 ex:dog2.
ex:dog2 ex:knows3 ex:dog3.

ex:dog1 ex:knows2 ex:cat2.
ex:cat2 ex:knows3 ex:cat3.

}
