/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.multirepo;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.common.transaction.IsolationLevel;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.SailReadOnlyException;
import org.eclipse.rdf4j.sail.base.SailDataset;
import org.eclipse.rdf4j.sail.base.SailSink;
import org.eclipse.rdf4j.sail.base.SailSource;

final class MultiRepoSailSource implements SailSource {

	private final List<SailSource> sources;
	private final boolean closeOnClose;

	MultiRepoSailSource(List<SailSource> sources, boolean closeOnClose) {
		this.sources = List.copyOf(sources);
		this.closeOnClose = closeOnClose;
	}

	@Override
	public SailSource fork() {
		return new MultiRepoSailSource(sources.stream()
				.map(SailSource::fork)
				.collect(Collectors.toList()), true);
	}

	@Override
	public SailSink sink(IsolationLevel level) throws SailException {
		throw new SailReadOnlyException("MultiRepoStore is read-only");
	}

	@Override
	public SailDataset dataset(IsolationLevel level) throws SailException {
		List<SailDataset> datasets = new ArrayList<>(sources.size());
		try {
			for (SailSource source : sources) {
				datasets.add(source.dataset(level));
			}
			return new MultiRepoSailDataset(datasets);
		} catch (Throwable t) {
			for (SailDataset dataset : datasets) {
				if (dataset != null) {
					dataset.close();
				}
			}
			throw t;
		}
	}

	@Override
	public void prepare() throws SailException {
		for (SailSource source : sources) {
			source.prepare();
		}
	}

	@Override
	public void flush() throws SailException {
		for (SailSource source : sources) {
			source.flush();
		}
	}

	@Override
	public void close() throws SailException {
		if (!closeOnClose) {
			return;
		}
		SailException failure = null;
		for (SailSource source : sources) {
			try {
				source.close();
			} catch (SailException e) {
				if (failure == null) {
					failure = e;
				} else {
					failure.addSuppressed(e);
				}
			}
		}
		if (failure != null) {
			throw failure;
		}
	}
}
