#!/bin/bash
asciidoctor -n -D html doc/index.adoc
asciidoctor -n -D html/server-workbench-console doc/server-workbench-console/index.adoc
asciidoctor -n -D html/migration doc/migration/index.adoc
asciidoctor -n -D html/programming doc/programming/index.adoc
asciidoctor -n -D html/getting-started doc/getting-started/index.adoc
cp -r doc/images html/
cp -r doc/css html/
