/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Co-Pilot
package org.eclipse.rdf4j.sail.lmdb.model;

import java.util.Objects;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.base.AbstractTripleTerm;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.lmdb.ValueStoreRevision;

public class LmdbTripleTerm extends AbstractTripleTerm implements LmdbValue {

	private static final long serialVersionUID = 138753260239097856L;

	private ValueStoreRevision revision;
	private long internalID;

	private Resource subject;
	private IRI predicate;
	private Value object;

	public LmdbTripleTerm(ValueStoreRevision revision, Resource subject, IRI predicate, Value object) {
		this(revision, subject, predicate, object, UNKNOWN_ID);
	}

	public LmdbTripleTerm(ValueStoreRevision revision, Resource subject, IRI predicate, Value object, long internalID) {
		this.revision = revision;
		this.subject = Objects.requireNonNull(subject, "subject must not be null");
		this.predicate = Objects.requireNonNull(predicate, "predicate must not be null");
		this.object = Objects.requireNonNull(object, "object must not be null");
		this.internalID = internalID;
	}

	@Override
	public Resource getSubject() {
		return subject;
	}

	@Override
	public IRI getPredicate() {
		return predicate;
	}

	@Override
	public Value getObject() {
		return object;
	}

	@Override
	public void setInternalID(long id, ValueStoreRevision revision) {
		this.internalID = id;
		this.revision = revision;
	}

	@Override
	public long getInternalID() {
		return internalID;
	}

	@Override
	public void init() {
		// Triple terms are eagerly initialized and currently not lazily resolved from the value store.
	}

	@Override
	public ValueStoreRevision getValueStoreRevision() {
		return revision;
	}

	@Override
	public void setFromInitializedValue(LmdbValue initializedValue) {
		if (initializedValue instanceof LmdbTripleTerm lmdbTripleTerm) {
			this.subject = lmdbTripleTerm.subject;
			this.predicate = lmdbTripleTerm.predicate;
			this.object = lmdbTripleTerm.object;
		} else {
			throw new SailException("Trying to initialize LmdbTripleTerm from non-triple-term value");
		}
	}
}
