/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.support;

import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Vector;

import javax.servlet.FilterConfig;
import javax.servlet.ServletContext;

import org.springframework.mock.web.MockServletContext;

public class TestFilterConfig implements FilterConfig {

	private final String filterName;
	private final ServletContext servletContext;
	private final Map<String, String> initParameters;

	public TestFilterConfig(String filterName, Map<String, String> initParameters) {
		this(filterName, new MockServletContext(), initParameters);
	}

	public TestFilterConfig(String filterName, ServletContext servletContext, Map<String, String> initParameters) {
		this.filterName = filterName;
		this.servletContext = servletContext;
		this.initParameters = new LinkedHashMap<>(initParameters);
	}

	public static TestFilterConfig withParams(String filterName, String... keyValues) {
		if (keyValues.length % 2 != 0) {
			throw new IllegalArgumentException("Expected key/value pairs.");
		}
		Map<String, String> initParameters = new LinkedHashMap<>();
		for (int i = 0; i < keyValues.length; i += 2) {
			initParameters.put(keyValues[i], keyValues[i + 1]);
		}
		return new TestFilterConfig(filterName, initParameters);
	}

	@Override
	public String getFilterName() {
		return filterName;
	}

	@Override
	public ServletContext getServletContext() {
		return servletContext;
	}

	@Override
	public String getInitParameter(String name) {
		return initParameters.get(name);
	}

	@Override
	public Enumeration<String> getInitParameterNames() {
		return new Vector<>(initParameters.keySet()).elements();
	}
}
