BASE <ex:>
CONSTRUCT {
  ?s0 ?p0 [ <a0> [ <b0> <c0> ] ].
  [ <a0> [ <b0> <c0> ] ] ?p0 ?o0.
}
WHERE {
  ?s1 ?p1 [], <a1>; ?q1 <b1>, <c1>.
  []  ?p2 ?o2.
  ?s3 ?p3 [ <a3> <b3> ].
  ?s4 ?p4 [ <a4> <b4>; <c4> <d4>, <e4> ].
  ?s5 ?p5 [ <a5> [ <b5> <c5> ] ].
  [ <a6> [ <b6> <c6> ] ] ?p6 ?o6.
  [ <a7> <b7>; <c7> <d7>, <e7> ].
}
