PREFIX dbpedia: <http://dbpedia.org/resource/>
SELECT ?label WHERE {
  { dbpedia:Belgium <http://www.w3.org/2000/01/rdf-schema#label> ?label. }
  UNION
  { dbpedia:Belgium <http://dbpedia.org/property/commonName>     ?label. }
  UNION
  { dbpedia:Belgium <http://xmlns.com/foaf/0.1/name>             ?label. }
}
