/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.BindingMask;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.BindingUniverse;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.PhysicalProperties;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.BagEstimate;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.FiniteRelationEstimate;
import org.eclipse.rdf4j.sail.lmdb.estimation.QuadSnapshotIdentity;

/** One normalized context for every semantic estimate. */
record EstimateContext(BindingUniverse universe, BindingMask boundMask,
		Optional<FiniteRelationEstimate> finiteBindings, BagEstimate prefixEstimate, double invocationCount,
		EvidencePolicy evidencePolicy, JoinFactorCostModel.EstimationTier estimationTier,
		QuadSnapshotIdentity snapshotIdentity, long snapshotVersion, MetricsPreference metricsPreference,
		boolean exactProbePermitted) {

	enum EvidencePolicy {
		SNAPSHOT_ONLY,
		ADAPTIVE
	}

	enum MetricsPreference {
		NONE,
		SUMMARY,
		DETAILED
	}

	EstimateContext {
		universe = Objects.requireNonNull(universe, "universe");
		boundMask = boundMask == null ? BindingMask.EMPTY : boundMask;
		finiteBindings = finiteBindings == null ? Optional.empty() : finiteBindings;
		prefixEstimate = prefixEstimate == null ? BagEstimate.exact(1.0d, "root-prefix") : prefixEstimate;
		invocationCount = finitePositive(invocationCount, 1.0d);
		evidencePolicy = evidencePolicy == null ? EvidencePolicy.ADAPTIVE : evidencePolicy;
		estimationTier = estimationTier == null ? JoinFactorCostModel.EstimationTier.STANDARD : estimationTier;
		snapshotIdentity = Objects.requireNonNull(snapshotIdentity, "snapshotIdentity");
		snapshotVersion = Math.max(0L, snapshotVersion);
		metricsPreference = metricsPreference == null ? MetricsPreference.SUMMARY : metricsPreference;
	}

	static EstimateContext root(TupleExpr expression, QuadSnapshotIdentity snapshotIdentity, long snapshotVersion) {
		BindingUniverse universe = BindingUniverse.from(Objects.requireNonNull(expression, "expression"),
				PhysicalProperties.ANY);
		return new EstimateContext(universe, BindingMask.EMPTY, Optional.empty(),
				BagEstimate.exact(1.0d, "root-prefix"), 1.0d, EvidencePolicy.ADAPTIVE,
				JoinFactorCostModel.EstimationTier.STANDARD, snapshotIdentity, snapshotVersion,
				MetricsPreference.SUMMARY, false);
	}

	Set<String> boundNames() {
		return universe.names(boundMask);
	}

	EstimateContext withBoundNames(Collection<String> names) {
		LinkedHashSet<String> allNames = new LinkedHashSet<>(boundNames());
		if (names != null) {
			allNames.addAll(names);
		}
		return copy(universe.maskOf(allNames), finiteBindings, prefixEstimate, invocationCount, evidencePolicy,
				estimationTier, metricsPreference, exactProbePermitted);
	}

	EstimateContext withFiniteBindings(FiniteRelationEstimate bindings) {
		Optional<FiniteRelationEstimate> relation = Optional.ofNullable(bindings);
		Collection<String> names = bindings == null ? boundNames() : bindings.variables();
		return copy(universe.maskOf(names).union(boundMask), relation, prefixEstimate, invocationCount, evidencePolicy,
				estimationTier, metricsPreference, exactProbePermitted);
	}

	EstimateContext withPrefixEstimate(BagEstimate prefix) {
		return copy(boundMask, finiteBindings, prefix, invocationCount, evidencePolicy, estimationTier, metricsPreference,
				exactProbePermitted);
	}

	EstimateContext withInvocationCount(double invocations) {
		return copy(boundMask, finiteBindings, prefixEstimate, invocations, evidencePolicy, estimationTier,
				metricsPreference, exactProbePermitted);
	}

	EstimateContext withEvidencePolicy(EvidencePolicy policy) {
		return copy(boundMask, finiteBindings, prefixEstimate, invocationCount, policy, estimationTier,
				metricsPreference, exactProbePermitted);
	}

	EstimateContext withEstimationTier(JoinFactorCostModel.EstimationTier tier) {
		return copy(boundMask, finiteBindings, prefixEstimate, invocationCount, evidencePolicy, tier, metricsPreference,
				exactProbePermitted);
	}

	EstimateContext withMetricsPreference(MetricsPreference preference) {
		return copy(boundMask, finiteBindings, prefixEstimate, invocationCount, evidencePolicy, estimationTier, preference,
				exactProbePermitted);
	}

	EstimateContext withExactProbePermission(boolean permitted) {
		return copy(boundMask, finiteBindings, prefixEstimate, invocationCount, evidencePolicy, estimationTier,
				metricsPreference, permitted);
	}

	private EstimateContext copy(BindingMask mask, Optional<FiniteRelationEstimate> bindings, BagEstimate prefix,
			double invocations, EvidencePolicy policy, JoinFactorCostModel.EstimationTier tier,
			MetricsPreference preference, boolean exactPermission) {
		return new EstimateContext(universe, mask, bindings, prefix, invocations, policy, tier, snapshotIdentity,
				snapshotVersion, preference, exactPermission);
	}

	private static double finitePositive(double value, double fallback) {
		return Double.isFinite(value) && value > 0.0d ? value : fallback;
	}
}
