/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;

final class FilteringRecordIterator implements RecordIterator {

	private final RecordIterator delegate;
	private final long subjectId;
	private final long predicateId;
	private final long objectId;
	private final long contextId;
	private long filtered;

	FilteringRecordIterator(RecordIterator delegate, long subjectId, long predicateId, long objectId, long contextId) {
		this.delegate = delegate;
		this.subjectId = subjectId;
		this.predicateId = predicateId;
		this.objectId = objectId;
		this.contextId = contextId;
	}

	@Override
	public long[] next() {
		long[] record;
		while ((record = delegate.next()) != null) {
			if (matches(record)) {
				return record;
			}
			filtered++;
		}
		return null;
	}

	private boolean matches(long[] record) {
		return matches(subjectId, record[0])
				&& matches(predicateId, record[1])
				&& matches(objectId, record[2])
				&& matches(contextId, record[3]);
	}

	private static boolean matches(long expected, long actual) {
		return expected == LmdbValue.UNKNOWN_ID || expected == actual;
	}

	@Override
	public String getIndexName() {
		return delegate.getIndexName();
	}

	@Override
	public long getSourceRowsScannedActual() {
		return delegate.getSourceRowsScannedActual();
	}

	@Override
	public long getSourceRowsMatchedActual() {
		return delegate.getSourceRowsMatchedActual();
	}

	@Override
	public long getSourceRowsFilteredActual() {
		long delegateFiltered = delegate.getSourceRowsFilteredActual();
		return delegateFiltered < 0 ? filtered : delegateFiltered + filtered;
	}

	@Override
	public void close() {
		delegate.close();
	}
}
