/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

/** Independently observable cardinality and physical-work dimensions learned by Frontier LEO. */
enum FrontierCostDimension {
	OUTPUT_ROWS,
	SOURCE_ROWS_SCANNED,
	INDEX_SEEKS,
	ITERATOR_OPENS,
	EXPRESSION_EVALUATIONS,
	HASH_BUILD_ROWS,
	HASH_PROBE_ROWS,
	PATH_EXPANSIONS,
	RESULT_ROWS,
	REMOTE_CALLS,
	SEMI_ANTI_HIT_RATE,
	STARTUP_ONCE,
	REOPEN_WORK,
	FIRST_MATCH_WORK,
	EXHAUSTION_WORK,
	CACHE_HIT_WORK,
	CACHE_MISS_WORK,
	CACHE_EVICTION_WORK,
	MATERIALIZATION_BUILD_WORK,
	MATERIALIZATION_LOOKUP_WORK,
	MEMORY_SPILL_WORK
}
