/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Arrays;

final class LeadingFieldSorters {

	private static final int LSD_RADIX_THRESHOLD = 96;

	private LeadingFieldSorters() {
	}

	public static void lsdRadixSort(int[] statementIndices, long[] leadingValues, int length, int[] scratchIndices,
			long[] scratchValues, int[] counts, int[] offsets) {
		if (length < 2 || isSorted(leadingValues, 0, length)) {
			return;
		}
		if (length <= LSD_RADIX_THRESHOLD) {
			unguardedInsertionSort(statementIndices, leadingValues, 0, length);
			return;
		}

		long differingBits = 0L;
		long firstValue = leadingValues[0];
		for (int i = 1; i < length; i++) {
			differingBits |= firstValue ^ leadingValues[i];
		}
		if (differingBits == 0L) {
			return;
		}

		int activePasses = 0;
		for (int shift = 0; shift < Long.SIZE; shift += Byte.SIZE) {
			if (((differingBits >>> shift) & 0xFFL) != 0L) {
				activePasses++;
			}
		}

		int[] sourceIndices = statementIndices;
		long[] sourceValues = leadingValues;
		int[] targetIndices = scratchIndices;
		long[] targetValues = scratchValues;

		if ((activePasses & 1) != 0) {
			System.arraycopy(statementIndices, 0, scratchIndices, 0, length);
			System.arraycopy(leadingValues, 0, scratchValues, 0, length);
			sourceIndices = scratchIndices;
			sourceValues = scratchValues;
			targetIndices = statementIndices;
			targetValues = leadingValues;
		}

		for (int shift = 0; shift < Long.SIZE; shift += Byte.SIZE) {
			if (((differingBits >>> shift) & 0xFFL) == 0L) {
				continue;
			}

			Arrays.fill(counts, 0);
			for (int i = 0; i < length; i++) {
				counts[(int) ((sourceValues[i] >>> shift) & 0xFFL)]++;
			}

			int offset = 0;
			for (int bucket = 0; bucket < counts.length; bucket++) {
				offsets[bucket] = offset;
				offset += counts[bucket];
			}

			for (int i = 0; i < length; i++) {
				int bucket = (int) ((sourceValues[i] >>> shift) & 0xFFL);
				int target = offsets[bucket]++;
				targetIndices[target] = sourceIndices[i];
				targetValues[target] = sourceValues[i];
			}

			int[] swappedIndices = sourceIndices;
			sourceIndices = targetIndices;
			targetIndices = swappedIndices;

			long[] swappedValues = sourceValues;
			sourceValues = targetValues;
			targetValues = swappedValues;
		}
	}

	private static void unguardedInsertionSort(int[] statementIndices, long[] leadingValues, int from, int to) {
		if (to - from < 2) {
			return;
		}
		int minPosition = from;
		long minValue = leadingValues[from];
		for (int i = from + 1; i < to; i++) {
			long value = leadingValues[i];
			if (value < minValue) {
				minValue = value;
				minPosition = i;
			}
		}
		if (minPosition != from) {
			int minIndex = statementIndices[minPosition];
			for (int i = minPosition; i > from; i--) {
				statementIndices[i] = statementIndices[i - 1];
				leadingValues[i] = leadingValues[i - 1];
			}
			statementIndices[from] = minIndex;
			leadingValues[from] = minValue;
		}
		for (int i = from + 1; i < to; i++) {
			int statementIndex = statementIndices[i];
			long statementValue = leadingValues[i];
			int position = i;
			while (statementValue < leadingValues[position - 1]) {
				statementIndices[position] = statementIndices[position - 1];
				leadingValues[position] = leadingValues[position - 1];
				position--;
			}
			statementIndices[position] = statementIndex;
			leadingValues[position] = statementValue;
		}
	}

	private static boolean isSorted(long[] leadingValues, int from, int to) {
		for (int i = from + 1; i < to; i++) {
			if (leadingValues[i - 1] > leadingValues[i]) {
				return false;
			}
		}
		return true;
	}
}
