/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.Objects;

/** Exact applicability contract under which one logical or physical observation may be reused. */
final class LearningApplicability {

	private static final String EXTERNAL_VERSION = "lap1";
	private final long bindingShapeFingerprint;
	private final long correlationContractFingerprint;
	private final String conditionalFeatureBucket;
	private final long dataEpoch;
	private final long catalogEpoch;
	private final long modelEpoch;
	private final String externalForm;
	private final String digest;
	private final int hashCode;

	LearningApplicability(long bindingShapeFingerprint, long correlationContractFingerprint,
			String conditionalFeatureBucket, long dataEpoch, long catalogEpoch, long modelEpoch) {
		if (dataEpoch < 0L || catalogEpoch < 0L || modelEpoch < 0L) {
			throw new IllegalArgumentException("learning applicability epochs must be non-negative");
		}
		this.bindingShapeFingerprint = bindingShapeFingerprint;
		this.correlationContractFingerprint = correlationContractFingerprint;
		this.conditionalFeatureBucket = LearningKeyCodec.canonicalLower(conditionalFeatureBucket, "unconditional");
		this.dataEpoch = dataEpoch;
		this.catalogEpoch = catalogEpoch;
		this.modelEpoch = modelEpoch;
		this.externalForm = encode();
		this.digest = LearningKeyCodec.digest(externalForm);
		this.hashCode = Objects.hash(bindingShapeFingerprint, correlationContractFingerprint,
				this.conditionalFeatureBucket, dataEpoch, catalogEpoch, modelEpoch);
	}

	static LearningApplicability parse(String externalForm) {
		if (externalForm == null || externalForm.isBlank()) {
			return null;
		}
		String[] fields = externalForm.split("\\|", -1);
		if (fields.length != 7 || !EXTERNAL_VERSION.equals(fields[0])) {
			return null;
		}
		try {
			return new LearningApplicability(Long.parseUnsignedLong(fields[1], 16),
					Long.parseUnsignedLong(fields[2], 16), LearningKeyCodec.decode(fields[3]),
					Long.parseUnsignedLong(fields[4], 16), Long.parseUnsignedLong(fields[5], 16),
					Long.parseUnsignedLong(fields[6], 16));
		} catch (IllegalArgumentException malformed) {
			return null;
		}
	}

	String externalForm() {
		return externalForm;
	}

	String digest() {
		return digest;
	}

	long correlationContractFingerprint() {
		return correlationContractFingerprint;
	}

	String conditionalFeatureBucket() {
		return conditionalFeatureBucket;
	}

	long dataEpoch() {
		return dataEpoch;
	}

	long catalogEpoch() {
		return catalogEpoch;
	}

	long modelEpoch() {
		return modelEpoch;
	}

	private String encode() {
		return EXTERNAL_VERSION + '|' + Long.toUnsignedString(bindingShapeFingerprint, 16) + '|'
				+ Long.toUnsignedString(correlationContractFingerprint, 16) + '|'
				+ LearningKeyCodec.encode(conditionalFeatureBucket) + '|'
				+ Long.toUnsignedString(dataEpoch, 16) + '|' + Long.toUnsignedString(catalogEpoch, 16) + '|'
				+ Long.toUnsignedString(modelEpoch, 16);
	}

	@Override
	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof LearningApplicability that)) {
			return false;
		}
		return bindingShapeFingerprint == that.bindingShapeFingerprint
				&& correlationContractFingerprint == that.correlationContractFingerprint
				&& dataEpoch == that.dataEpoch
				&& catalogEpoch == that.catalogEpoch
				&& modelEpoch == that.modelEpoch
				&& conditionalFeatureBucket.equals(that.conditionalFeatureBucket);
	}

	@Override
	public int hashCode() {
		return hashCode;
	}

	@Override
	public String toString() {
		return "LearningApplicability[bindingShapeFingerprint=" + bindingShapeFingerprint
				+ ", correlationContractFingerprint=" + correlationContractFingerprint
				+ ", conditionalFeatureBucket=" + conditionalFeatureBucket
				+ ", dataEpoch=" + dataEpoch
				+ ", catalogEpoch=" + catalogEpoch
				+ ", modelEpoch=" + modelEpoch + ']';
	}

	void writeTo(DataOutputStream out) throws IOException {
		out.writeLong(bindingShapeFingerprint);
		out.writeLong(correlationContractFingerprint);
		LearningKeyCodec.writeString(out, conditionalFeatureBucket);
		out.writeLong(dataEpoch);
		out.writeLong(catalogEpoch);
		out.writeLong(modelEpoch);
	}

	static LearningApplicability readFrom(DataInputStream in) throws IOException {
		try {
			return new LearningApplicability(in.readLong(), in.readLong(),
					LearningKeyCodec.readString(in, "conditional feature bucket"), in.readLong(), in.readLong(),
					in.readLong());
		} catch (IllegalArgumentException malformed) {
			throw new IOException("Invalid learning applicability", malformed);
		}
	}
}
