/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.List;
import java.util.Objects;

import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.join.ExhaustiveLegalJoinSearchContributor;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.join.JoinSearchService;

/** Creates LMDB's contributor set without granting any contributor ownership of the join region. */
final class LmdbJoinSearchProvider {

	private LmdbJoinSearchProvider() {
	}

	static JoinSearchService create(JoinFactorCostModel costModel, EvaluationStatistics fallbackStatistics) {
		Objects.requireNonNull(costModel, "costModel");
		Objects.requireNonNull(fallbackStatistics, "fallbackStatistics");
		return new JoinSearchService(List.of(
				new LmdbDphypJoinSearchContributor(request -> LmdbHypergraphJoinPlanner.tryCandidate(request,
						costModel, fallbackStatistics)),
				new ExhaustiveLegalJoinSearchContributor()));
	}
}
