/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.EvidenceGuarantee;

/** Pure, saturating fan-out and orientation arithmetic for LMDB independent hash joins. */
final class LmdbHashJoinCosting {

	private LmdbHashJoinCosting() {
	}

	static CandidateEstimate estimateCandidates(double leftRows, double rightRows, double executionPartitions,
			double matchedRows, int lookupMaskId, FrontierCorrelationDomain leftDomain,
			FrontierCorrelationDomain rightDomain) {
		return estimateCandidates(leftRows, rightRows, executionPartitions, matchedRows, lookupMaskId, -1,
				leftDomain, rightDomain);
	}

	static CandidateEstimate estimateCandidates(double leftRows, double rightRows, double executionPartitions,
			double matchedRows, int lookupMaskId, int compatibilityMaskId, FrontierCorrelationDomain leftDomain,
			FrontierCorrelationDomain rightDomain) {
		double repeatedRightRows = saturatedMultiply(rightRows, executionPartitions);
		double productRows = saturatedMultiply(leftRows, repeatedRightRows);
		double candidateRows = productRows;
		double leftJointNdv = Double.NaN;
		double rightJointNdv = Double.NaN;
		String source;
		if (lookupMaskId == 0) {
			source = "product-no-assured-key";
		} else if (lookupMaskId == compatibilityMaskId && finiteNonNegative(matchedRows)) {
			/*
			 * Every shared compatibility binding is present in the assured lookup key. A bucket lookup therefore
			 * performs no compatibility rejections: its candidate multiplicity is exactly the logical join
			 * multiplicity, independently of whether either Frontier state retained a joint-NDV payload.
			 */
			candidateRows = matchedRows;
			source = "assured-compatibility-output";
		} else if (leftDomain == null || rightDomain == null) {
			source = "product-missing-evidence";
		} else {
			leftJointNdv = leftDomain.distinctKeyEstimate();
			rightJointNdv = rightDomain.distinctKeyEstimate();
			FrontierPrimitiveCorrelationRelation leftRelation = leftDomain.primitiveRelation();
			FrontierPrimitiveCorrelationRelation rightRelation = rightDomain.primitiveRelation();
			boolean exactJointEvidence = leftDomain.guarantee() == EvidenceGuarantee.DATABASE_EXACT
					&& rightDomain.guarantee() == EvidenceGuarantee.DATABASE_EXACT
					&& Double.compare(leftDomain.rows(), leftRows) == 0
					&& Double.compare(rightDomain.rows(), rightRows) == 0
					&& leftRelation != null
					&& rightRelation != null
					&& leftRelation.fullyBound()
					&& rightRelation.fullyBound();
			if (exactJointEvidence) {
				candidateRows = saturatedMultiply(leftRelation.weightedOverlap(rightRelation), executionPartitions);
				source = "exact-frontier-joint-key";
			} else if (usableJointNdv(leftJointNdv, leftRows) && usableJointNdv(rightJointNdv, rightRows)) {
				double divisor = Math.max(leftJointNdv, rightJointNdv);
				candidateRows = divisor == 0.0d ? 0.0d : productRows / divisor;
				source = "joint-ndv";
			} else {
				source = "product-unusable-evidence";
			}
		}
		candidateRows = clampCandidates(candidateRows, matchedRows, productRows);
		return new CandidateEstimate(candidateRows, productRows, leftJointNdv, rightJointNdv, source);
	}

	static Orientation chooseOrientation(double leftRows, double rightRows, double executionPartitions,
			double candidateRows, double resultRows, long maxMaterializedRows) {
		double repeatedRightRows = saturatedMultiply(rightRows, executionPartitions);
		double leftBuildRows = leftRows;
		double leftProbeInputRows = repeatedRightRows;
		double leftPeakMemoryRows = leftRows;
		double rightBuildRows = repeatedRightRows;
		double rightProbeInputRows = leftRows;
		double rightPeakMemoryRows = rightRows;
		double memoryLimit = Math.max(0L, maxMaterializedRows);
		boolean leftAdmissible = leftPeakMemoryRows <= memoryLimit;
		boolean rightAdmissible = rightPeakMemoryRows <= memoryLimit;
		double leftObjective = leftAdmissible
				? orientationObjective(leftBuildRows, leftProbeInputRows, candidateRows, resultRows,
						leftPeakMemoryRows)
				: Double.MAX_VALUE;
		double rightObjective = rightAdmissible
				? orientationObjective(rightBuildRows, rightProbeInputRows, candidateRows, resultRows,
						rightPeakMemoryRows)
				: Double.MAX_VALUE;
		boolean buildFromLeft;
		if (leftAdmissible != rightAdmissible) {
			buildFromLeft = leftAdmissible;
		} else if (leftAdmissible) {
			buildFromLeft = leftObjective <= rightObjective;
		} else {
			buildFromLeft = leftPeakMemoryRows <= rightPeakMemoryRows;
		}
		return buildFromLeft
				? new Orientation(true, leftAdmissible, leftBuildRows, leftProbeInputRows, leftPeakMemoryRows,
						leftObjective)
				: new Orientation(false, rightAdmissible, rightBuildRows, rightProbeInputRows, rightPeakMemoryRows,
						rightObjective);
	}

	static Orientation rightBuildOrientation(double leftRows, double rightRows, double executionPartitions,
			double candidateRows, double resultRows) {
		double partitions = Double.isFinite(executionPartitions) && executionPartitions > 0.0d
				? executionPartitions
				: 1.0d;
		double buildRows = saturatedMultiply(rightRows, partitions);
		return new Orientation(false, true, buildRows, leftRows, rightRows,
				orientationObjective(buildRows, leftRows, candidateRows, resultRows, rightRows));
	}

	private static boolean usableJointNdv(double distinctKeys, double rows) {
		return finiteNonNegative(distinctKeys) && (distinctKeys > 0.0d || rows == 0.0d);
	}

	private static double clampCandidates(double candidateRows, double matchedRows, double productRows) {
		double upper = finiteNonNegative(productRows) ? productRows : Double.MAX_VALUE;
		double lower = finiteNonNegative(matchedRows) ? Math.min(matchedRows, upper) : 0.0d;
		if (!finiteNonNegative(candidateRows)) {
			return upper;
		}
		return Math.min(upper, Math.max(lower, candidateRows));
	}

	private static double orientationObjective(double buildRows, double probeInputRows, double candidateRows,
			double resultRows, double peakMemoryRows) {
		double objective = saturatedAdd(buildRows, probeInputRows);
		objective = saturatedAdd(objective, candidateRows);
		objective = saturatedAdd(objective, resultRows);
		return saturatedAdd(objective, peakMemoryRows);
	}

	private static boolean finiteNonNegative(double value) {
		return Double.isFinite(value) && value >= 0.0d;
	}

	private static double saturatedMultiply(double left, double right) {
		double product = left * right;
		return Double.isFinite(product) && product >= 0.0d ? product : Double.MAX_VALUE;
	}

	private static double saturatedAdd(double left, double right) {
		double sum = left + right;
		return Double.isFinite(sum) && sum >= 0.0d ? sum : Double.MAX_VALUE;
	}

	record CandidateEstimate(double candidateRows, double productRows, double leftJointNdv, double rightJointNdv,
			String source) {
	}

	record Orientation(boolean buildFromLeft, boolean admissible, double buildRows, double probeInputRows,
			double peakMemoryRows, double objective) {
	}
}
