/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude Code
package org.eclipse.rdf4j.sail.lmdb;

import static org.eclipse.rdf4j.sail.lmdb.LmdbNativeAggregateCompiler.*;

import java.io.IOException;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Predicate;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.transaction.QueryEvaluationMode;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.base.CoreDatatype;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.RDF4J;
import org.eclipse.rdf4j.model.vocabulary.SESAME;
import org.eclipse.rdf4j.query.Binding;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.algebra.AbstractAggregateOperator;
import org.eclipse.rdf4j.query.algebra.AggregateOperator;
import org.eclipse.rdf4j.query.algebra.And;
import org.eclipse.rdf4j.query.algebra.Avg;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Bound;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Count;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Distinct;
import org.eclipse.rdf4j.query.algebra.Exists;
import org.eclipse.rdf4j.query.algebra.Extension;
import org.eclipse.rdf4j.query.algebra.ExtensionElem;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Group;
import org.eclipse.rdf4j.query.algebra.GroupElem;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.ListMemberOperator;
import org.eclipse.rdf4j.query.algebra.MathExpr;
import org.eclipse.rdf4j.query.algebra.Max;
import org.eclipse.rdf4j.query.algebra.Min;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.Order;
import org.eclipse.rdf4j.query.algebra.OrderElem;
import org.eclipse.rdf4j.query.algebra.Projection;
import org.eclipse.rdf4j.query.algebra.ProjectionElem;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.Reduced;
import org.eclipse.rdf4j.query.algebra.SingletonSet;
import org.eclipse.rdf4j.query.algebra.Slice;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.StatementPattern.Scope;
import org.eclipse.rdf4j.query.algebra.Sum;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryBindingSet;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryEvaluationStep;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryValueEvaluationStep;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.QueryEvaluationContext;
import org.eclipse.rdf4j.query.algebra.evaluation.util.MathUtil;
import org.eclipse.rdf4j.query.algebra.evaluation.util.QueryEvaluationUtil;
import org.eclipse.rdf4j.query.algebra.evaluation.util.ValueComparator;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;
import org.eclipse.rdf4j.query.algebra.helpers.collectors.VarNameCollector;
import org.eclipse.rdf4j.sail.SailException;

abstract class LmdbNativeAggregateFilterCompiler extends LmdbNativeAggregateValuesCompiler {

	LmdbNativeAggregateFilterCompiler(QueryEvaluationContext context, LmdbNativeEvaluationStrategy strategy,
			NativeLmdbQuerySource source) {
		super(context, strategy, source);
	}

	NativeBooleanFilter compileDirectExists(Exists exists) {
		if (!(exists.getSubQuery() instanceof StatementPattern)) {
			return null;
		}
		StatementPattern pattern = (StatementPattern) exists.getSubQuery();
		ContextConstraint contexts = compileContextConstraint(pattern, context.getDataset());
		if (contexts == ContextConstraint.EMPTY) {
			return row -> false;
		}
		Term s = compileCorrelatedTerm(pattern.getSubjectVar(), NativePatternField.SUBJECT);
		Term p = compileCorrelatedTerm(pattern.getPredicateVar(), NativePatternField.PREDICATE);
		Term o = compileCorrelatedTerm(pattern.getObjectVar(), NativePatternField.OBJECT);
		Term c = compileCorrelatedTerm(pattern.getContextVar(), NativePatternField.CONTEXT);
		if (s == null || p == null || o == null || c == null) {
			return null;
		}
		return new StatementPatternExistsFilter(source, s, p, o, c, contexts,
				pattern.getScope() == Scope.NAMED_CONTEXTS);
	}

	Term compileCorrelatedTerm(Var var, NativePatternField field) {
		if (var == null) {
			return Term.unbound();
		}
		if (var.hasValue()) {
			Value value = var.getValue();
			if (!validValueForField(value, field)) {
				return null;
			}
			if (field == NativePatternField.CONTEXT && isNullContextValue(value)) {
				return Term.constant(NULL_CONTEXT_ID);
			}
			long id = idOf(value);
			return id == UNKNOWN ? null : Term.constant(id);
		}
		Integer existing = slots.get(var.getName());
		return existing == null ? Term.unbound() : Term.slot(existing);
	}

	SlotPlan compileFactorizedLeftJoinFilter(Filter filter, boolean duplicateInsensitive) {
		if (!duplicateInsensitive || !(filter.getArg() instanceof LeftJoin)) {
			return null;
		}
		LeftJoin leftJoin = (LeftJoin) filter.getArg();
		Set<String> rightNames = rightOnlyBindingNames(leftJoin);
		if (rightNames.isEmpty() || !Collections.disjoint(rightNames, requiredAggregateNames)
				|| !nullRejects(filter.getCondition(), rightNames)) {
			return null;
		}
		SlotPlan left = compileTuple(leftJoin.getLeftArg(), true);
		SlotPlan right = compileTuple(leftJoin.getRightArg(), true);
		NativeBooleanFilter condition = compileBoolean(filter.getCondition());
		if (left == null || right == null || condition == null) {
			return null;
		}
		return SlotPlan.filter(left,
				new ExistsFilter(SlotPlan.filter(right, condition, placeableFilterMask(filter.getCondition()))));
	}

	Set<String> rightOnlyBindingNames(LeftJoin leftJoin) {
		java.util.HashSet<String> rightOnly = new java.util.HashSet<>(leftJoin.getRightArg().getBindingNames());
		rightOnly.removeAll(leftJoin.getLeftArg().getBindingNames());
		return rightOnly;
	}

	Set<String> sharedBindingNames(TupleExpr left, TupleExpr right) {
		java.util.HashSet<String> shared = new java.util.HashSet<>(left.getBindingNames());
		shared.retainAll(right.getBindingNames());
		return shared;
	}

	Set<String> withRequired(Set<String> base, Set<String> extra) {
		if (extra.isEmpty()) {
			return base;
		}
		java.util.HashSet<String> required = new java.util.HashSet<>(base);
		required.addAll(extra);
		return required;
	}

	boolean nullRejects(ValueExpr condition, Set<String> nullableNames) {
		if (condition instanceof And) {
			return nullRejects(((And) condition).getLeftArg(), nullableNames)
					|| nullRejects(((And) condition).getRightArg(), nullableNames);
		}
		if (condition instanceof Or) {
			return nullRejects(((Or) condition).getLeftArg(), nullableNames)
					&& nullRejects(((Or) condition).getRightArg(), nullableNames);
		}
		if (condition instanceof Compare) {
			return referencesAny(((Compare) condition).getLeftArg(), nullableNames)
					|| referencesAny(((Compare) condition).getRightArg(), nullableNames);
		}
		if (condition instanceof ListMemberOperator) {
			List<ValueExpr> args = ((ListMemberOperator) condition).getArguments();
			return !args.isEmpty() && referencesAny(args.get(0), nullableNames);
		}
		if (condition instanceof Bound) {
			return referencesAny(((Bound) condition).getArg(), nullableNames);
		}
		return false;
	}

	boolean referencesAny(ValueExpr expr, Set<String> names) {
		for (String name : VarNameCollector.process(expr)) {
			if (names.contains(name)) {
				return true;
			}
		}
		return false;
	}

	QueryEvaluationContext slotAwareContext() {
		if (slotAwareContext == null) {
			slotAwareContext = new SlotAwareQueryEvaluationContext(context, layout);
		}
		return slotAwareContext;
	}

	NativeBooleanFilter compileBoolean(ValueExpr expr) {
		if (!syntheticVarNames.isEmpty()
				&& !Collections.disjoint(VarNameCollector.process(expr), syntheticVarNames)) {
			// raw-id shortcuts (IN, sameTerm, = against constants) must never compare a plan-local
			// synthetic id against a real store id; the generic path materializes values instead
			return compileGenericBoolean(expr);
		}
		if (expr instanceof And) {
			NativeBooleanFilter left = compileBoolean(((And) expr).getLeftArg());
			NativeBooleanFilter right = compileBoolean(((And) expr).getRightArg());
			return left == null || right == null ? null : row -> left.accept(row) && right.accept(row);
		}
		if (expr instanceof Or) {
			NativeBooleanFilter left = compileBoolean(((Or) expr).getLeftArg());
			NativeBooleanFilter right = compileBoolean(((Or) expr).getRightArg());
			return left == null || right == null ? null : row -> left.accept(row) || right.accept(row);
		}
		if (expr instanceof Not && cannotProduceError(((Not) expr).getArg())) {
			// Native leaves collapse type errors (e.g. comparisons against unbound OPTIONAL vars) to
			// false, which is safe under And/Or and at the row gate, but Not would turn that false
			// into true while SPARQL three-valued logic keeps the error and drops the row. Only
			// negate natively when the argument cannot produce an error; otherwise the expression
			// falls through to the generic evaluator below, which implements full three-valued logic.
			NativeBooleanFilter arg = compileBoolean(((Not) expr).getArg());
			return arg == null ? null : row -> !arg.accept(row);
		}
		if (expr instanceof Exists) {
			NativeBooleanFilter direct = compileDirectExists((Exists) expr);
			if (direct != null) {
				return direct;
			}
			SlotPlan subPlan = compileTuple(((Exists) expr).getSubQuery(), false);
			return subPlan == null ? null : new ExistsFilter(subPlan);
		}
		if (expr instanceof ListMemberOperator) {
			NativeBooleanFilter membership = compileListMember((ListMemberOperator) expr);
			if (membership != null) {
				return membership;
			}
		}
		if (expr instanceof Compare) {
			NativeBooleanFilter comparison = compileCompare((Compare) expr);
			if (comparison != null) {
				return comparison;
			}
		}

		return compileGenericBoolean(expr);
	}

	NativeBooleanFilter compileGenericBoolean(ValueExpr expr) {
		Set<String> names = VarNameCollector.process(expr);
		for (String name : names) {
			slot(name);
		}
		QueryValueEvaluationStep step;
		try {
			// the slot-aware context resolves each variable's slot index once at precompile time, so the
			// per-row accessor is a direct slot read instead of a name lookup
			step = strategy.precompile(expr, slotAwareContext());
		} catch (QueryEvaluationException e) {
			// a condition that fails to precompile (e.g. a constant sub-expression that always raises a
			// type error) can never accept a row; the generic engine folds it to constant-false the same
			// way in FilterIterator.supply instead of surfacing the error at evaluate() time
			return row -> false;
		}
		Predicate<BindingSet> predicate = step.asPredicate();
		return row -> predicate.test(row.view);
	}

	/**
	 * Whether the expression is guaranteed to evaluate to plain true/false and can never raise a SPARQL type error.
	 * Only such expressions may be negated natively: for everything else the collapsed error would incorrectly flip to
	 * true under Not.
	 */
	static boolean cannotProduceError(ValueExpr expr) {
		if (expr instanceof Exists || expr instanceof Bound) {
			return true;
		}
		if (expr instanceof Not) {
			return cannotProduceError(((Not) expr).getArg());
		}
		if (expr instanceof And) {
			return cannotProduceError(((And) expr).getLeftArg()) && cannotProduceError(((And) expr).getRightArg());
		}
		if (expr instanceof Or) {
			return cannotProduceError(((Or) expr).getLeftArg()) && cannotProduceError(((Or) expr).getRightArg());
		}
		return false;
	}

	/**
	 * The placement mask of a filter condition: the slots the condition can read, or -1 when the condition is not
	 * safely placeable. A filter with a complete mask may run at any join depth at which all masked slots are bound —
	 * evaluating it later never changes the outcome because slots are write-once. Conditions containing EXISTS are
	 * never placeable: an EXISTS constrains differently depending on which of its variables happen to be bound at
	 * evaluation time, so it must stay exactly where the algebra put it.
	 */
	long placeableFilterMask(ValueExpr condition) {
		if (containsExists(condition)) {
			return -1L;
		}
		long mask = 0L;
		for (String name : VarNameCollector.process(condition)) {
			Integer slot = slots.get(name);
			if (slot == null) {
				return -1L;
			}
			mask |= 1L << slot;
		}
		return mask;
	}

	static boolean containsExists(ValueExpr expr) {
		class ExistsFinder extends AbstractQueryModelVisitor<RuntimeException> {
			boolean found;

			@Override
			public void meet(Exists node) {
				found = true;
			}
		}
		ExistsFinder finder = new ExistsFinder();
		expr.visit(finder);
		return finder.found;
	}

	NativeBooleanFilter compileListMember(ListMemberOperator list) {
		List<ValueExpr> args = list.getArguments();
		if (args.size() < 2 || !(args.get(0) instanceof Var)) {
			return null;
		}
		Var var = (Var) args.get(0);
		if (var.hasValue()) {
			return null;
		}
		int slot = slot(var.getName());
		long[] accepted = new long[args.size() - 1];
		Value[] acceptedValues = new Value[args.size() - 1];
		int acceptedSize = 0;
		for (int i = 1; i < args.size(); i++) {
			ValueExpr candidate = args.get(i);
			Value value;
			if (candidate instanceof ValueConstant) {
				value = ((ValueConstant) candidate).getValue();
			} else if (candidate instanceof Var && ((Var) candidate).hasValue()) {
				value = ((Var) candidate).getValue();
			} else {
				return null;
			}
			long id = idOf(value);
			if (id == UNKNOWN) {
				return null;
			}
			accepted[acceptedSize] = id;
			acceptedValues[acceptedSize] = value;
			acceptedSize++;
		}
		if (acceptedSize == 0) {
			return row -> false;
		}
		return new ValueSetFilter(source, slot,
				acceptedSize == accepted.length ? accepted : Arrays.copyOf(accepted, acceptedSize),
				acceptedSize == acceptedValues.length ? acceptedValues
						: Arrays.copyOf(acceptedValues, acceptedSize));
	}

	NativeBooleanFilter compileCompare(Compare compare) {
		Compare.CompareOp op = compare.getOperator();
		IdOperand left = compileIdOperand(compare.getLeftArg());
		IdOperand right = compileIdOperand(compare.getRightArg());
		if (left == null || right == null) {
			return null;
		}
		if (op == Compare.CompareOp.EQ || op == Compare.CompareOp.NE) {
			Predicate<BindingSet> fallback = strategy.precompile(compare, slotAwareContext()).asPredicate();
			NativeBooleanFilter cached = cachedCompareIfPossible(op, left, right, fallback);
			if (cached != null) {
				return cached;
			}
			return row -> {
				long l = left.id(row);
				long r = right.id(row);
				if (l == UNKNOWN || r == UNKNOWN) {
					return false;
				}
				if (safeResourceId(l) && safeResourceId(r)) {
					return op == Compare.CompareOp.EQ ? l == r : l != r;
				}
				return fallback.test(row.view);
			};
		}
		Predicate<BindingSet> fallback = strategy.precompile(compare, slotAwareContext()).asPredicate();
		NativeBooleanFilter cached = cachedCompareIfPossible(op, left, right, fallback);
		return cached != null ? cached : row -> {
			long l = left.id(row);
			long r = right.id(row);
			return l != UNKNOWN && r != UNKNOWN && fallback.test(row.view);
		};
	}

	NativeBooleanFilter cachedCompareIfPossible(Compare.CompareOp op, IdOperand left, IdOperand right,
			Predicate<BindingSet> fallback) {
		if (left.isSlot() && right.isConstant()) {
			return new CachedCompareFilter(left.slot, right.constant, false, op, fallback);
		}
		if (left.isConstant() && right.isSlot()) {
			return new CachedCompareFilter(right.slot, left.constant, true, op, fallback);
		}
		return null;
	}

	IdOperand compileIdOperand(ValueExpr expr) {
		if (expr instanceof Var) {
			Var var = (Var) expr;
			if (var.hasValue()) {
				long id = idOf(var.getValue());
				return id == UNKNOWN ? null : IdOperand.constant(id);
			}
			return IdOperand.slot(slot(var.getName()));
		}
		if (expr instanceof ValueConstant) {
			long id = idOf(((ValueConstant) expr).getValue());
			return id == UNKNOWN ? null : IdOperand.constant(id);
		}
		return null;
	}

}
