/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.List;

/** Path-copy mutation planner for codec-3 version-2 persistent rows. */
final class LmdbAdjacencyPersistentRowRewriter {

	static final class Plan {
		private final boolean changed;
		private final LmdbAdjacencySourceRegistry registry;
		private final TreeChild root;
		private final long decodedPairs;
		private final long encodedPairs;
		private final long visitedNodes;
		private final long rewrittenLeaves;

		private Plan(boolean changed, LmdbAdjacencySourceRegistry registry, TreeChild root, Counters counters) {
			this.changed = changed;
			this.registry = registry;
			this.root = root;
			this.decodedPairs = counters.decodedPairs;
			this.encodedPairs = counters.encodedPairs;
			this.visitedNodes = counters.visitedNodes;
			this.rewrittenLeaves = counters.rewrittenLeaves;
		}

		boolean changed() {
			return changed;
		}

		boolean tombstone() {
			return changed && root == null;
		}

		long edgeCount() {
			return root == null ? 0 : root.count;
		}

		long decodedPairs() {
			return decodedPairs;
		}

		long encodedPairs() {
			return encodedPairs;
		}

		long visitedNodes() {
			return visitedNodes;
		}

		long rewrittenLeaves() {
			return rewrittenLeaves;
		}

		long reusedNodes() {
			return root == null ? 0 : root.reusedNodes();
		}

		long directoryBytes() {
			return root == null ? 0 : root.directoryBytes();
		}

		long sharedLogicalBytes() {
			return root == null ? 0 : Math.multiplyExact(root.reusedPairs(), Long.BYTES * 2L);
		}

		long totalBytes() {
			return root == null ? 0 : root.totalBytes();
		}

		List<LmdbAdjacencyRunCodec.SourceSlice> dependencies() {
			ArrayList<LmdbAdjacencyRunCodec.SourceSlice> dependencies = new ArrayList<>();
			if (root != null) {
				root.collectDependencies(registry, dependencies);
			}
			return dependencies;
		}

		void plan(LmdbAdjacencyArenaSizingPlan target) {
			if (root != null) {
				root.plan(target);
			}
		}

		long write(LmdbAdjacencyArena target, LmdbAdjacencyArenaCatalog catalog) {
			if (root == null) {
				return 0;
			}
			int ownSourceId = catalog.sourceRegistry().sourceIdForArena(target);
			LmdbAdjacencyRunCodec.PersistentChild materialized = root.write(target, catalog.sourceRegistry(),
					ownSourceId);
			if (materialized.kind != LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE
					|| materialized.sourceId != ownSourceId) {
				throw new IllegalStateException("persistent rewrite root was not materialized in the target source");
			}
			return materialized.sourceRef;
		}
	}

	static Plan plan(LmdbAdjacencyDeltaApplier.OldRun old,
			LmdbAdjacencySupernodeRewriter.SortedMutationSource mutations, ContextCatalog contexts,
			long targetLeafEdges,
			long targetLeafBytes) {
		LmdbAdjacencyRunCodec.PersistentNode rootNode = LmdbAdjacencyRunCodec.persistentNode(old.catalog, old.handle);
		LmdbAdjacencySourceRegistry registry = old.catalog.sourceRegistry();
		long firstNeighbor = LmdbAdjacencyRunCodec.neighborAt(old.catalog, old.handle, 0);
		long firstContext = LmdbAdjacencyRunCodec.contextAt(old.catalog, old.contexts, old.handle, 0);
		TreeChild oldRoot = TreeChild.reused(firstNeighbor, firstContext, rootNode.edgeCount(), 0,
				old.catalog.sourceIdFor(old.handle, LmdbAdjacencyRunCodec.LEAF_RUN_SLICE),
				old.catalog.unpackLocalRef(old.handle), LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE, rootNode.level());
		Counters counters = new Counters();
		int maxLeafEdges = Math.toIntExact(Math.max(1, Math.min(4_096L, targetLeafEdges)));
		long maxLeafBytes = Math.max(1, Math.min(64L << 10, targetLeafBytes));
		Rewrite rewrite = rewriteChild(registry, oldRoot, mutations, 0, mutations.size(), contexts, maxLeafEdges,
				maxLeafBytes, counters);
		if (!rewrite.changed) {
			return new Plan(false, registry, oldRoot, counters);
		}
		if (rewrite.children.isEmpty()) {
			return new Plan(true, registry, null, counters);
		}
		List<TreeChild> roots = rewrite.children;
		int level = oldRoot.level;
		while (roots.size() > 1) {
			level++;
			roots = packNodes(level, roots);
		}
		TreeChild root = roots.get(0);
		if (root.node == null) {
			root = TreeChild.node(new TreeNode(0, List.of(root)));
		}
		return new Plan(true, registry, root, counters);
	}

	private static Rewrite rewriteChild(LmdbAdjacencySourceRegistry registry, TreeChild old,
			LmdbAdjacencySupernodeRewriter.SortedMutationSource mutations, int from, int to, ContextCatalog contexts,
			int maxLeafEdges, long maxLeafBytes, Counters counters) {
		if (old.kind != LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE) {
			return rewriteLeaf(registry, old, mutations, from, to, contexts, maxLeafEdges, maxLeafBytes, counters);
		}
		LmdbAdjacencyRunCodec.PersistentNode node = LmdbAdjacencyRunCodec.persistentNode(registry, old.sourceId,
				old.sourceRef);
		counters.visitedNodes++;
		int childCount = node.childCount();
		int[] mutationChildren = new int[to - from];
		for (int i = from; i < to; i++) {
			mutationChildren[i - from] = childFor(node, mutations.neighborAt(i), mutations.contextAt(i));
		}
		ArrayList<TreeChild> output = new ArrayList<>(childCount + Math.min(to - from, childCount));
		boolean changed = false;
		int mutation = from;
		for (int childIndex = 0; childIndex < childCount; childIndex++) {
			LmdbAdjacencyRunCodec.PersistentChild encoded = node.child(childIndex);
			TreeChild child = TreeChild.reused(encoded.firstNeighbor, encoded.firstContext, encoded.count,
					encoded.sourceOrdinal, encoded.sourceId, encoded.sourceRef, encoded.kind,
					encoded.kind == LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE ? old.level - 1 : -1);
			int childMutationFrom = mutation;
			while (mutation < to && mutationChildren[mutation - from] == childIndex) {
				mutation++;
			}
			if (childMutationFrom == mutation) {
				output.add(child);
				continue;
			}
			Rewrite childRewrite = rewriteChild(registry, child, mutations, childMutationFrom, mutation, contexts,
					maxLeafEdges, maxLeafBytes, counters);
			changed |= childRewrite.changed;
			output.addAll(childRewrite.children);
		}
		if (mutation != to) {
			throw new IllegalStateException("persistent mutation routing did not consume every mutation");
		}
		if (!changed) {
			return new Rewrite(false, List.of(old));
		}
		return new Rewrite(true, packNodes(old.level, output));
	}

	private static Rewrite rewriteLeaf(LmdbAdjacencySourceRegistry registry, TreeChild old,
			LmdbAdjacencySupernodeRewriter.SortedMutationSource mutations, int from, int to, ContextCatalog contexts,
			int maxLeafEdges, long maxLeafBytes, Counters counters) {
		int oldCount = Math.toIntExact(old.count);
		long[] oldNeighbors = new long[oldCount];
		long[] oldContexts = new long[oldCount];
		LmdbAdjacencyRunCodec.SourceSlice oldSlice = new LmdbAdjacencyRunCodec.SourceSlice(registry, old.sourceId,
				old.sourceRef, old.sourceOrdinal, old.count, old.firstNeighbor, old.firstContext, old.kind);
		int copied = LmdbAdjacencyRunCodec.copy(oldSlice, contexts, old.sourceOrdinal, oldCount, oldNeighbors, 0,
				oldContexts, 0);
		if (copied != oldCount) {
			throw new IllegalStateException("persistent leaf copy returned " + copied + " of " + oldCount);
		}
		counters.decodedPairs = Math.addExact(counters.decodedPairs, oldCount);

		int capacity = Math.addExact(oldCount, to - from);
		long[] neighbors = new long[capacity];
		long[] rawContexts = new long[capacity];
		int oldAt = 0;
		int mutation = from;
		int output = 0;
		boolean changed = false;
		while (oldAt < oldCount || mutation < to) {
			if (mutation >= to) {
				neighbors[output] = oldNeighbors[oldAt];
				rawContexts[output++] = oldContexts[oldAt++];
				continue;
			}
			long mutationNeighbor = mutations.neighborAt(mutation);
			long mutationContext = mutations.contextAt(mutation);
			int cmp = oldAt >= oldCount ? 1
					: LmdbAdjacencyRunCodec.comparePairsUnsigned(oldNeighbors[oldAt], oldContexts[oldAt],
							mutationNeighbor, mutationContext);
			if (cmp < 0) {
				neighbors[output] = oldNeighbors[oldAt];
				rawContexts[output++] = oldContexts[oldAt++];
			} else if (cmp == 0) {
				if (mutations.addAt(mutation)) {
					neighbors[output] = oldNeighbors[oldAt];
					rawContexts[output++] = oldContexts[oldAt];
				} else {
					changed = true;
				}
				oldAt++;
				mutation++;
			} else {
				if (mutations.addAt(mutation)) {
					neighbors[output] = mutationNeighbor;
					rawContexts[output++] = mutationContext;
					changed = true;
				}
				mutation++;
			}
		}
		if (!changed) {
			return new Rewrite(false, List.of(old));
		}
		counters.encodedPairs = Math.addExact(counters.encodedPairs, output);
		ArrayList<TreeChild> leaves = new ArrayList<>((output + maxLeafEdges - 1) / maxLeafEdges);
		for (int at = 0; at < output;) {
			int end = Math.min(output, at + maxLeafEdges);
			appendPreparedLeaves(neighbors, rawContexts, at, end, contexts, maxLeafBytes, leaves, counters);
			at = end;
		}
		return new Rewrite(true, leaves);
	}

	private static void appendPreparedLeaves(long[] neighbors, long[] contexts, int from, int to,
			ContextCatalog contextCatalog, long maxLeafBytes, List<TreeChild> output, Counters counters) {
		LmdbAdjacencyRunCodec.Encoder encoder = LmdbAdjacencyRunCodec.preparingEncoder(contextCatalog);
		boolean ordered = true;
		for (int i = from; i < to; i++) {
			encoder.accept(neighbors[i], contexts[i]);
			ordered &= ValueIds.isOrderedInteger(neighbors[i]);
		}
		LmdbAdjacencyRunCodec.PreparedRun prepared = encoder.finish().preparedRun;
		if (prepared.totalBytes() > maxLeafBytes && to - from > 1) {
			int middle = (from + to) >>> 1;
			appendPreparedLeaves(neighbors, contexts, from, middle, contextCatalog, maxLeafBytes, output, counters);
			appendPreparedLeaves(neighbors, contexts, middle, to, contextCatalog, maxLeafBytes, output, counters);
			return;
		}
		output.add(TreeChild.prepared(neighbors[from], contexts[from], to - from, prepared, ordered));
		counters.rewrittenLeaves++;
	}

	private static List<TreeChild> packNodes(int level, List<TreeChild> children) {
		if (children.isEmpty()) {
			return List.of();
		}
		ArrayList<TreeChild> nodes = new ArrayList<>((children.size() + LmdbAdjacencyRunCodec.PERSISTENT_FANOUT - 1)
				/ LmdbAdjacencyRunCodec.PERSISTENT_FANOUT);
		for (int from = 0; from < children.size(); from += LmdbAdjacencyRunCodec.PERSISTENT_FANOUT) {
			int to = Math.min(children.size(), from + LmdbAdjacencyRunCodec.PERSISTENT_FANOUT);
			nodes.add(TreeChild.node(new TreeNode(level, List.copyOf(children.subList(from, to)))));
		}
		return nodes;
	}

	private static int childFor(LmdbAdjacencyRunCodec.PersistentNode node, long neighbor, long context) {
		int low = 0;
		int high = node.childCount() - 1;
		while (low <= high) {
			int middle = (low + high) >>> 1;
			LmdbAdjacencyRunCodec.PersistentChild child = node.child(middle);
			if (LmdbAdjacencyRunCodec.comparePairsUnsigned(child.firstNeighbor, child.firstContext, neighbor,
					context) <= 0) {
				low = middle + 1;
			} else {
				high = middle - 1;
			}
		}
		return Math.max(0, high);
	}

	private static final class TreeNode {
		final int level;
		final List<TreeChild> children;

		TreeNode(int level, List<TreeChild> children) {
			this.level = level;
			this.children = children;
		}
	}

	private static final class TreeChild {
		final long firstNeighbor;
		final long firstContext;
		final long count;
		final long sourceOrdinal;
		final int sourceId;
		final long sourceRef;
		final int kind;
		final int level;
		final LmdbAdjacencyRunCodec.PreparedRun prepared;
		final TreeNode node;
		final boolean ordered;

		private TreeChild(long firstNeighbor, long firstContext, long count, long sourceOrdinal, int sourceId,
				long sourceRef, int kind, int level, LmdbAdjacencyRunCodec.PreparedRun prepared, TreeNode node,
				boolean ordered) {
			this.firstNeighbor = firstNeighbor;
			this.firstContext = firstContext;
			this.count = count;
			this.sourceOrdinal = sourceOrdinal;
			this.sourceId = sourceId;
			this.sourceRef = sourceRef;
			this.kind = kind;
			this.level = level;
			this.prepared = prepared;
			this.node = node;
			this.ordered = ordered;
		}

		static TreeChild reused(long firstNeighbor, long firstContext, long count, long sourceOrdinal, int sourceId,
				long sourceRef, int kind, int level) {
			return new TreeChild(firstNeighbor, firstContext, count, sourceOrdinal, sourceId, sourceRef, kind, level,
					null, null, false);
		}

		static TreeChild prepared(long firstNeighbor, long firstContext, long count,
				LmdbAdjacencyRunCodec.PreparedRun prepared, boolean ordered) {
			return new TreeChild(firstNeighbor, firstContext, count, 0, 0, 0,
					LmdbAdjacencyRunCodec.LEAF_RUN_SLICE, -1, prepared, null, ordered);
		}

		static TreeChild node(TreeNode node) {
			long count = 0;
			boolean ordered = true;
			for (TreeChild child : node.children) {
				count = Math.addExact(count, child.count);
				ordered &= child.ordered;
			}
			TreeChild first = node.children.get(0);
			return new TreeChild(first.firstNeighbor, first.firstContext, count, 0, 0, 0,
					LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE, node.level, null, node, ordered);
		}

		long totalBytes() {
			if (prepared != null) {
				return prepared.totalBytes();
			}
			if (node == null) {
				return 0;
			}
			long bytes = LmdbAdjacencyRunCodec.persistentNodeBytes(node.children.size());
			for (TreeChild child : node.children) {
				bytes = Math.addExact(bytes, child.totalBytes());
			}
			return bytes;
		}

		long directoryBytes() {
			if (node == null) {
				return 0;
			}
			long bytes = LmdbAdjacencyRunCodec.persistentNodeBytes(node.children.size());
			for (TreeChild child : node.children) {
				bytes = Math.addExact(bytes, child.directoryBytes());
			}
			return bytes;
		}

		long reusedPairs() {
			if (prepared != null) {
				return 0;
			}
			if (node == null) {
				return count;
			}
			long pairs = 0;
			for (TreeChild child : node.children) {
				pairs = Math.addExact(pairs, child.reusedPairs());
			}
			return pairs;
		}

		long reusedNodes() {
			if (node == null) {
				return kind == LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE ? 1 : 0;
			}
			long nodes = 0;
			for (TreeChild child : node.children) {
				nodes = Math.addExact(nodes, child.reusedNodes());
			}
			return nodes;
		}

		void collectDependencies(LmdbAdjacencySourceRegistry registry,
				List<LmdbAdjacencyRunCodec.SourceSlice> dependencies) {
			if (prepared != null) {
				return;
			}
			if (node == null) {
				dependencies.add(new LmdbAdjacencyRunCodec.SourceSlice(registry, sourceId, sourceRef, sourceOrdinal,
						count, firstNeighbor, firstContext, kind));
				return;
			}
			for (TreeChild child : node.children) {
				child.collectDependencies(registry, dependencies);
			}
		}

		void plan(LmdbAdjacencyArenaSizingPlan target) {
			if (prepared != null) {
				prepared.plan(target);
				return;
			}
			if (node == null) {
				return;
			}
			for (TreeChild child : node.children) {
				child.plan(target);
			}
			target.allocate(LmdbAdjacencyRunCodec.persistentNodeBytes(node.children.size()), 8);
		}

		LmdbAdjacencyRunCodec.PersistentChild write(LmdbAdjacencyArena target,
				LmdbAdjacencySourceRegistry registry, int ownSourceId) {
			if (prepared != null) {
				long ref = prepared.write(target).rootRef;
				return new LmdbAdjacencyRunCodec.PersistentChild(firstNeighbor, firstContext, count, 0, ownSourceId,
						ref, LmdbAdjacencyRunCodec.LEAF_RUN_SLICE);
			}
			if (node == null) {
				return new LmdbAdjacencyRunCodec.PersistentChild(firstNeighbor, firstContext, count, sourceOrdinal,
						sourceId, sourceRef, kind);
			}
			ArrayList<LmdbAdjacencyRunCodec.PersistentChild> materialized = new ArrayList<>(node.children.size());
			boolean nodeOrdered = true;
			for (TreeChild child : node.children) {
				materialized.add(child.write(target, registry, ownSourceId));
				nodeOrdered &= child.ordered;
			}
			long ref = LmdbAdjacencyRunCodec.writePersistentNode(target, registry, node.level, materialized, true,
					nodeOrdered);
			return new LmdbAdjacencyRunCodec.PersistentChild(firstNeighbor, firstContext, count, 0, ownSourceId, ref,
					LmdbAdjacencyRunCodec.PERSISTENT_CHILD_NODE);
		}
	}

	private static final class Counters {
		long decodedPairs;
		long encodedPairs;
		long visitedNodes;
		long rewrittenLeaves;
	}

	private record Rewrite(boolean changed, List<TreeChild> children) {
	}

	private LmdbAdjacencyPersistentRowRewriter() {
	}
}
