/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel.CostContext;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel.EstimationTier;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.FiniteRelationEstimate;
import org.eclipse.rdf4j.sail.lmdb.estimation.LmdbQuadSynopsisService;
import org.eclipse.rdf4j.sail.lmdb.estimation.QuadSnapshotIdentity;

/** Builds immutable evidence contexts for one estimator runtime invocation. */
final class LmdbEstimateContextBuilder {

	private LmdbEstimateContextBuilder() {
	}

	static EstimateContext forCost(TupleExpr expression, CostContext cost, EstimateContext root,
			LmdbPrefixEvidenceResolver prefixEvidence, LmdbEstimatorOptimizationScope scope) {
		EstimationTier tier = cost.getEstimationTier();
		EstimateContext context = root
				.withBoundNames(cost.getCurrentlyBoundVars())
				.withInvocationCount(invocations(cost))
				.withEstimationTier(tier)
				.withMetricsPreference(cost.shouldCollectMetrics()
						? EstimateContext.MetricsPreference.DETAILED
						: EstimateContext.MetricsPreference.NONE)
				.withExactProbePermission(tier != null && tier.allowsExactEstimates());
		context = context.withPrefixEstimate(prefixEvidence.estimate(expression, cost, context, scope));
		FiniteRelationEstimate finite = prefixEvidence.finiteBindings(
				relevantFiniteBindingValues(expression, cost.getFiniteBindingValues()),
				scope == null ? null : scope.finiteBindingContexts);
		return finite == null ? context : context.withFiniteBindings(finite);
	}

	static EstimateContext root(TupleExpr expression, LmdbQuadSynopsisService synopsis, long dataRevision,
			long snapshotVersion, long leoRevision, LmdbEstimatorOptimizationScope scope,
			boolean adaptiveEvidenceAllowed) {
		if (synopsis == null) {
			QuadSnapshotIdentity identity = new QuadSnapshotIdentity(0L, 0L, Math.max(0L, dataRevision));
			EstimateContext context = scope == null
					? EstimateContext.root(expression, identity, snapshotVersion, leoRevision)
					: EstimateContext.root(scope.bindingUniverse(expression), identity, snapshotVersion, leoRevision);
			return adaptiveEvidenceAllowed ? context
					: context.withEvidencePolicy(EstimateContext.EvidencePolicy.SNAPSHOT_ONLY);
		}
		EstimateContext context = scope == null
				? EstimateContext.root(expression, synopsis.snapshotIdentity(), synopsis.snapshotVersion(), leoRevision)
				: EstimateContext.root(scope.bindingUniverse(expression), synopsis.snapshotIdentity(),
						synopsis.snapshotVersion(), leoRevision);
		return adaptiveEvidenceAllowed && synopsis.adaptiveEvidenceAllowed() ? context
				: context.withEvidencePolicy(EstimateContext.EvidencePolicy.SNAPSHOT_ONLY);
	}

	private static Map<String, Set<Value>> relevantFiniteBindingValues(TupleExpr expression,
			Map<String, Set<Value>> finiteBindingValues) {
		if (!(expression instanceof BindingSetAssignment assignment)
				|| finiteBindingValues == null || finiteBindingValues.isEmpty()) {
			return finiteBindingValues;
		}
		Set<String> assignmentNames = assignment.getBindingNames();
		if (assignmentNames.containsAll(finiteBindingValues.keySet())) {
			return finiteBindingValues;
		}
		Map<String, Set<Value>> relevant = new LinkedHashMap<>();
		for (String assignmentName : assignmentNames) {
			Set<Value> values = finiteBindingValues.get(assignmentName);
			if (values != null && !values.isEmpty()) {
				relevant.put(assignmentName, values);
			}
		}
		return relevant.isEmpty() ? Map.of() : relevant;
	}

	private static double invocations(CostContext context) {
		if (!context.isNestedIteratorInvocation()) {
			return 1.0d;
		}
		double outerRows = context.getOuterPrefixRows();
		if (Double.isFinite(outerRows) && outerRows >= 0.0d) {
			return outerRows;
		}
		return positive(context.getDistinctLookupBindings(), 1.0d);
	}

	private static double positive(double value, double fallback) {
		return Double.isFinite(value) && value > 0.0d ? value : fallback;
	}
}
