/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import java.lang.foreign.MemorySegment;
import java.nio.ByteBuffer;
import java.util.Arrays;

/**
 * Group run codecs for the strictly in-memory direct adjacency index (plan 27).
 * <p>
 * Every group is a complete sequence sorted by unsigned {@code (rawNeighborId, rawContextId)}; stored context values
 * are catalog ordinals whose conceptual order remains the raw pair order (invariants I9, I12). Three codecs share one
 * physically separate leading tag byte:
 * <ul>
 * <li>{@code SMALL_VARINT} for 1..15 incidences,</li>
 * <li>{@code BLOCK_FOR} for ordinary runs up to 1,048,575 incidences / 64 MiB,</li>
 * <li>{@code CHUNK_DIRECTORY} above that, holding ordered range chunks that are themselves SMALL/BLOCK runs.</li>
 * </ul>
 * The sizing and writing paths share one state machine ({@link #encodedBytes} and {@link #encode} run the identical
 * pipeline), so predicted and emitted sizes cannot differ. All decode methods take the catalogs captured by the read
 * view and range-check every decoded offset, length, count, and ordinal before native access (invariant I18).
 */
final class LmdbAdjacencyRunCodec {

	static final int CODEC_SMALL_VARINT = 0;
	static final int CODEC_BLOCK_FOR = 1;
	static final int CODEC_CHUNK_DIRECTORY = 2;
	static final int CODEC_RESERVED = 3;

	static final int TAG_CONTEXT_PRESENT = 1 << 2;
	static final int TAG_ORDERED_INTEGER = 1 << 3;

	static final long SMALL_MAX_EDGES = 15;
	static final int BLOCK_SHIFT = 7;
	static final int BLOCK_LANES = 1 << BLOCK_SHIFT;
	static final long BLOCK_FOR_MAX_EDGES = 1_048_575;
	static final long ORDINARY_RUN_MAX_BYTES = 64L << 20;
	static final long CHUNK_TARGET_EDGES = 65_536;
	static final long CHUNK_TARGET_BYTES = 64L << 20;

	private static final int BLOCK_HEADER_BYTES = 24; // tag..blockPayloadByteLength
	private static final int DIRECTORY_HEADER_BYTES = 24; // tag..totalEdgeCount
	private static final int DIRECTORY_ENTRY_BYTES = 40;

	/** Chunk arena-slot sentinel: the child lives in the same arena as its directory, whatever slot that is. */
	static final int CHUNK_SLOT_SELF = 255;

	private LmdbAdjacencyRunCodec() {
	}

	// ---------------------------------------------------------------------
	// Encoding
	// ---------------------------------------------------------------------

	/**
	 * Exact total encoded bytes (including chunk runs and the directory for a supernode) for the given sorted pair
	 * source. Runs the identical pipeline as {@link #encode} with a counting sink.
	 */
	static long encodedBytes(SortedPairSource source, ContextCatalog contexts) {
		Encoder encoder = new Encoder(contexts, null);
		while (source.next()) {
			encoder.accept(source.neighbor(), source.context());
		}
		return encoder.finish().totalBytes;
	}

	/**
	 * Encodes the complete run into the target arena and returns the local u40 reference of the run (or chunk
	 * directory).
	 */
	static long encode(SortedPairSource source, ContextCatalog contexts, LmdbAdjacencyArena target) {
		Encoder encoder = new Encoder(contexts, target);
		while (source.next()) {
			encoder.accept(source.neighbor(), source.context());
		}
		return encoder.finish().rootRef;
	}

	/**
	 * Creates a push-mode sizing encoder (counts exact bytes, allocates nothing). Feed pairs with
	 * {@link Encoder#accept(long, long)} and read {@link Encoder#finish()}.
	 */
	static Encoder sizingEncoder(ContextCatalog contexts) {
		return new Encoder(contexts, null);
	}

	/**
	 * Creates a push-mode writing encoder targeting the given arena.
	 */
	static Encoder writingEncoder(ContextCatalog contexts, LmdbAdjacencyArena target) {
		return new Encoder(contexts, target);
	}

	/**
	 * One shared sizing/writing state machine. With a null target it only accumulates exact byte counts; with a target
	 * it also performs the allocations and writes. The base builder drives one group at a time in push mode; working
	 * memory is bounded by the format's ordinary-run/chunk limits, never by total statement count (invariant I8).
	 */
	static final class Encoder {

		private final ContextCatalog contexts;
		private final LmdbAdjacencyArena target;

		private long[] neighbors = new long[16];
		private long[] ordinals = new long[16];
		private int count;

		private long lastNeighbor;
		private long lastRawContext;
		private boolean any;
		private boolean anyContext;
		private boolean allOrderedInteger = true;

		private long totalBytes;

		// chunked mode state
		private boolean chunked;
		private long chunkEdgeStart;
		private long[] chunkFirstNeighbor = new long[16];
		private long[] chunkFirstRawContext = new long[16];
		private long[] chunkEdgeStarts = new long[16];
		private long[] chunkEdgeCounts = new long[16];
		private long[] chunkRefs = new long[16];
		private int chunkCount;

		Encoder(ContextCatalog contexts, LmdbAdjacencyArena target) {
			this.contexts = contexts;
			this.target = target;
		}

		static final class Result {
			long totalBytes;
			long rootRef;
			long edgeCount;
		}

		/**
		 * Completes the run and returns its exact byte total, root reference (zero in sizing mode), and edge count.
		 */
		Result finish() {
			Result result = new Result();
			if (!any) {
				throw new IllegalArgumentException("a run must contain at least one incidence");
			}
			if (!chunked) {
				result.edgeCount = count;
				result.rootRef = emitOrdinaryRun(neighbors, ordinals, 0, count);
			} else {
				if (count > 0) {
					closeChunk();
				}
				result.edgeCount = chunkEdgeStart;
				result.rootRef = emitDirectory();
			}
			result.totalBytes = totalBytes;
			return result;
		}

		void accept(long neighbor, long rawContext) {
			if (any) {
				int cmp = comparePairsUnsigned(lastNeighbor, lastRawContext, neighbor, rawContext);
				if (cmp >= 0) {
					throw new IllegalStateException("pairs must be strictly unsigned ascending: ("
							+ Long.toUnsignedString(neighbor) + ", " + Long.toUnsignedString(rawContext)
							+ ") does not follow (" + Long.toUnsignedString(lastNeighbor) + ", "
							+ Long.toUnsignedString(lastRawContext) + ")");
				}
			}
			long ordinal = 0;
			if (rawContext != 0) {
				ordinal = contexts.ordinalForRaw(rawContext);
				if (ordinal <= 0) {
					throw new IllegalArgumentException(
							"raw context has no catalog ordinal: " + Long.toUnsignedString(rawContext));
				}
				anyContext = true;
			}
			if (!ValueIds.isOrderedInteger(neighbor)) {
				allOrderedInteger = false;
			}
			lastNeighbor = neighbor;
			lastRawContext = rawContext;
			any = true;

			if (chunked && count >= CHUNK_TARGET_EDGES) {
				closeChunk();
			}
			appendPair(neighbor, ordinal);
			if (!chunked && count > BLOCK_FOR_MAX_EDGES) {
				// the run is a supernode: re-chunk the buffered prefix deterministically and continue streaming
				switchToChunked();
			}
		}

		private void appendPair(long neighbor, long ordinal) {
			if (count == neighbors.length) {
				int newLength = Math.multiplyExact(neighbors.length, 2);
				neighbors = Arrays.copyOf(neighbors, newLength);
				ordinals = Arrays.copyOf(ordinals, newLength);
			}
			neighbors[count] = neighbor;
			ordinals[count] = ordinal;
			count++;
		}

		private void switchToChunked() {
			chunked = true;
			long[] bufferedNeighbors = neighbors;
			long[] bufferedOrdinals = ordinals;
			int buffered = count;
			neighbors = new long[(int) CHUNK_TARGET_EDGES];
			ordinals = new long[(int) CHUNK_TARGET_EDGES];
			count = 0;
			chunkEdgeStart = 0;
			for (int i = 0; i < buffered; i++) {
				if (count >= CHUNK_TARGET_EDGES) {
					closeChunk();
				}
				appendPair(bufferedNeighbors[i], bufferedOrdinals[i]);
			}
		}

		private void closeChunk() {
			long chunkBytesBefore = totalBytes;
			long ref = emitOrdinaryRun(neighbors, ordinals, 0, count);
			long chunkBytes = totalBytes - chunkBytesBefore;
			if (chunkBytes > CHUNK_TARGET_BYTES) {
				throw new IllegalStateException("chunk of " + count + " incidences encoded to " + chunkBytes
						+ " bytes, above the " + CHUNK_TARGET_BYTES + "-byte target");
			}
			recordChunk(neighbors[0], ordinals[0], chunkEdgeStart, count, ref);
			chunkEdgeStart += count;
			count = 0;
		}

		private void recordChunk(long firstNeighbor, long firstOrdinal, long edgeStart, long edgeCount, long ref) {
			if (chunkCount == chunkRefs.length) {
				int newLength = Math.multiplyExact(chunkRefs.length, 2);
				chunkFirstNeighbor = Arrays.copyOf(chunkFirstNeighbor, newLength);
				chunkFirstRawContext = Arrays.copyOf(chunkFirstRawContext, newLength);
				chunkEdgeStarts = Arrays.copyOf(chunkEdgeStarts, newLength);
				chunkEdgeCounts = Arrays.copyOf(chunkEdgeCounts, newLength);
				chunkRefs = Arrays.copyOf(chunkRefs, newLength);
			}
			chunkFirstNeighbor[chunkCount] = firstNeighbor;
			chunkFirstRawContext[chunkCount] = firstOrdinal == 0 ? 0 : contexts.rawForOrdinal(firstOrdinal);
			chunkEdgeStarts[chunkCount] = edgeStart;
			chunkEdgeCounts[chunkCount] = edgeCount;
			chunkRefs[chunkCount] = ref;
			chunkCount++;
		}

		private int tagByte(int codec) {
			int tag = codec;
			if (anyContext) {
				tag |= TAG_CONTEXT_PRESENT;
			}
			if (allOrderedInteger) {
				tag |= TAG_ORDERED_INTEGER;
			}
			return tag;
		}

		/**
		 * Emits one SMALL_VARINT or BLOCK_FOR run; returns its local ref (zero in counting mode).
		 */
		private long emitOrdinaryRun(long[] runNeighbors, long[] runOrdinals, int from, int runCount) {
			if (runCount <= SMALL_MAX_EDGES) {
				return emitSmallVarint(runNeighbors, runOrdinals, from, runCount);
			}
			return emitBlockFor(runNeighbors, runOrdinals, from, runCount);
		}

		private long emitSmallVarint(long[] runNeighbors, long[] runOrdinals, int from, int runCount) {
			int neighborByteLength = Varint.calcLengthUnsigned(runNeighbors[from]);
			for (int i = 1; i < runCount; i++) {
				neighborByteLength += Varint.calcLengthUnsigned(runNeighbors[from + i] - runNeighbors[from + i - 1]);
			}
			int contextByteLength = 0;
			if (anyContext) {
				for (int i = 0; i < runCount; i++) {
					contextByteLength += Varint.calcLengthUnsigned(runOrdinals[from + i]);
				}
			}
			long bytes = alignUp(8L + neighborByteLength + contextByteLength, 8);
			totalBytes = Math.addExact(totalBytes, bytes);
			if (target == null) {
				return 0;
			}
			long ref = target.allocateRef(bytes, 8);
			MemorySegment slice = target.slice(ref, bytes);
			slice.set(LmdbAdjacencyArena.U8, 0, (byte) tagByte(CODEC_SMALL_VARINT));
			slice.set(LmdbAdjacencyArena.U8, 1, (byte) runCount);
			slice.set(LmdbAdjacencyArena.U16_LE, 2, (short) neighborByteLength);
			slice.set(LmdbAdjacencyArena.U16_LE, 4, (short) contextByteLength);
			slice.set(LmdbAdjacencyArena.U16_LE, 6, (short) 0);
			ByteBuffer buffer = slice.asSlice(8, bytes - 8).asByteBuffer();
			Varint.writeUnsigned(buffer, runNeighbors[from]);
			for (int i = 1; i < runCount; i++) {
				Varint.writeUnsigned(buffer, runNeighbors[from + i] - runNeighbors[from + i - 1]);
			}
			if (anyContext) {
				for (int i = 0; i < runCount; i++) {
					Varint.writeUnsigned(buffer, runOrdinals[from + i]);
				}
			}
			return ref;
		}

		private long emitBlockFor(long[] runNeighbors, long[] runOrdinals, int from, int runCount) {
			int blockCount = (runCount + BLOCK_LANES - 1) >>> BLOCK_SHIFT;
			long headerBytes = alignUp(BLOCK_HEADER_BYTES + 4L * (blockCount + 1), 8);
			long payloadBytes = 0;
			for (int b = 0; b < blockCount; b++) {
				payloadBytes += blockBytes(runNeighbors, runOrdinals, from + (b << BLOCK_SHIFT),
						Math.min(BLOCK_LANES, runCount - (b << BLOCK_SHIFT)));
			}
			if (payloadBytes > Integer.MAX_VALUE) {
				throw new IllegalStateException("block payload exceeds u32: " + payloadBytes);
			}
			long bytes = Math.addExact(headerBytes, payloadBytes);
			if (bytes > ORDINARY_RUN_MAX_BYTES && !chunked) {
				// format guard: with <= 1,048,575 incidences a BLOCK_FOR run stays far below 64 MiB
				throw new IllegalStateException("ordinary run encoded to " + bytes + " bytes, above the 64-MiB bound");
			}
			totalBytes = Math.addExact(totalBytes, bytes);
			if (target == null) {
				return 0;
			}
			long ref = target.allocateRef(bytes, 8);
			MemorySegment slice = target.slice(ref, bytes);
			slice.set(LmdbAdjacencyArena.U8, 0, (byte) tagByte(CODEC_BLOCK_FOR));
			slice.set(LmdbAdjacencyArena.U8, 1, (byte) BLOCK_SHIFT);
			slice.set(LmdbAdjacencyArena.U16_LE, 2, (short) 0);
			slice.set(LmdbAdjacencyArena.U32_LE, 4, 0);
			slice.set(LmdbAdjacencyArena.U64_LE, 8, runCount);
			slice.set(LmdbAdjacencyArena.U32_LE, 16, blockCount);
			slice.set(LmdbAdjacencyArena.U32_LE, 20, (int) payloadBytes);
			long payloadStart = headerBytes;
			long offset = 0;
			for (int b = 0; b < blockCount; b++) {
				slice.set(LmdbAdjacencyArena.U32_LE, BLOCK_HEADER_BYTES + 4L * b, (int) offset);
				int lanes = Math.min(BLOCK_LANES, runCount - (b << BLOCK_SHIFT));
				offset += writeBlock(slice, payloadStart + offset, runNeighbors, runOrdinals,
						from + (b << BLOCK_SHIFT), lanes);
			}
			slice.set(LmdbAdjacencyArena.U32_LE, BLOCK_HEADER_BYTES + 4L * blockCount, (int) offset);
			if (offset != payloadBytes) {
				throw new IllegalStateException(
						"predicted block payload " + payloadBytes + " differs from written " + offset);
			}
			return ref;
		}

		private long blockBytes(long[] runNeighbors, long[] runOrdinals, int from, int lanes) {
			int neighborWidth = neighborWidth(runNeighbors, from, lanes);
			long bytes = 4 + 8 + packedBytes(lanes, neighborWidth);
			if (anyContext) {
				bytes += 8 + packedBytes(lanes, contextWidth(runOrdinals, from, lanes));
			}
			return alignUp(bytes, 8);
		}

		private long writeBlock(MemorySegment slice, long at, long[] runNeighbors, long[] runOrdinals, int from,
				int lanes) {
			int neighborWidth = neighborWidth(runNeighbors, from, lanes);
			int contextWidth = anyContext ? contextWidth(runOrdinals, from, lanes) : 0;
			slice.set(LmdbAdjacencyArena.U8, at, (byte) (lanes - 1));
			slice.set(LmdbAdjacencyArena.U8, at + 1, (byte) neighborWidth);
			slice.set(LmdbAdjacencyArena.U8, at + 2, (byte) contextWidth);
			slice.set(LmdbAdjacencyArena.U8, at + 3, (byte) 0);
			long neighborBase = runNeighbors[from];
			slice.set(LmdbAdjacencyArena.U64_LE, at + 4, neighborBase);
			long cursor = at + 12;
			if (anyContext) {
				long contextBase = unsignedMin(runOrdinals, from, lanes);
				slice.set(LmdbAdjacencyArena.U64_LE, cursor, contextBase);
				cursor += 8;
				cursor = writeLanes(slice, cursor, runNeighbors, from, lanes, neighborBase, neighborWidth);
				cursor = writeLanes(slice, cursor, runOrdinals, from, lanes, contextBase, contextWidth);
			} else {
				cursor = writeLanes(slice, cursor, runNeighbors, from, lanes, neighborBase, neighborWidth);
			}
			long written = alignUp(cursor - at, 8);
			return written;
		}

		private static long writeLanes(MemorySegment slice, long at, long[] values, int from, int lanes, long base,
				int width) {
			if (width == 0) {
				return at;
			}
			long wordCount = packedBytes(lanes, width) / 8;
			// packed words are already zeroed by the arena; OR each lane into place
			for (int i = 0; i < lanes; i++) {
				long delta = values[from + i] - base;
				long bitPos = (long) i * width;
				long wordIndex = bitPos >>> 6;
				int bitOffset = (int) (bitPos & 63);
				long word = slice.get(LmdbAdjacencyArena.U64_LE, at + wordIndex * 8);
				word |= delta << bitOffset;
				slice.set(LmdbAdjacencyArena.U64_LE, at + wordIndex * 8, word);
				if (bitOffset + width > 64) {
					long next = slice.get(LmdbAdjacencyArena.U64_LE, at + (wordIndex + 1) * 8);
					next |= delta >>> (64 - bitOffset);
					slice.set(LmdbAdjacencyArena.U64_LE, at + (wordIndex + 1) * 8, next);
				}
			}
			return at + wordCount * 8;
		}

		private static int neighborWidth(long[] values, int from, int lanes) {
			// unsigned-sorted: the last lane holds the maximum delta from the first
			long maxDelta = values[from + lanes - 1] - values[from];
			return bitsFor(maxDelta);
		}

		private static int contextWidth(long[] ordinals, int from, int lanes) {
			long base = unsignedMin(ordinals, from, lanes);
			long maxDelta = 0;
			for (int i = 0; i < lanes; i++) {
				long delta = ordinals[from + i] - base;
				if (Long.compareUnsigned(delta, maxDelta) > 0) {
					maxDelta = delta;
				}
			}
			return bitsFor(maxDelta);
		}

		private long emitDirectory() {
			long bytes = DIRECTORY_HEADER_BYTES + (long) DIRECTORY_ENTRY_BYTES * chunkCount;
			totalBytes = Math.addExact(totalBytes, bytes);
			if (target == null) {
				return 0;
			}
			long ref = target.allocateRef(bytes, 8);
			MemorySegment slice = target.slice(ref, bytes);
			slice.set(LmdbAdjacencyArena.U8, 0, (byte) tagByte(CODEC_CHUNK_DIRECTORY));
			slice.set(LmdbAdjacencyArena.U8, 1, (byte) 0); // level
			slice.set(LmdbAdjacencyArena.U16_LE, 2, (short) 0);
			slice.set(LmdbAdjacencyArena.U32_LE, 4, chunkCount);
			slice.set(LmdbAdjacencyArena.U64_LE, 8, bytes);
			slice.set(LmdbAdjacencyArena.U64_LE, 16, chunkEdgeStart);
			for (int i = 0; i < chunkCount; i++) {
				long at = DIRECTORY_HEADER_BYTES + (long) DIRECTORY_ENTRY_BYTES * i;
				slice.set(LmdbAdjacencyArena.U64_LE, at, chunkFirstNeighbor[i]);
				slice.set(LmdbAdjacencyArena.U64_LE, at + 8, chunkFirstRawContext[i]);
				slice.set(LmdbAdjacencyArena.U64_LE, at + 16, chunkEdgeStarts[i]);
				slice.set(LmdbAdjacencyArena.U64_LE, at + 24, chunkEdgeCounts[i]);
				// chunks emitted with the run share its arena, whatever catalog slot that arena ends up in; the
				// sentinel resolves to the directory's own slot at decode time (absolute slots stay available for
				// cross-arena chunk reuse during consolidation)
				slice.set(LmdbAdjacencyArena.U8, at + 32, (byte) CHUNK_SLOT_SELF);
				LmdbAdjacencyArena.writeU40(slice, at + 33, chunkRefs[i]);
				slice.set(LmdbAdjacencyArena.U16_LE, at + 38, (short) 0);
			}
			return ref;
		}
	}

	// ---------------------------------------------------------------------
	// Decoding
	// ---------------------------------------------------------------------

	/**
	 * Caller-owned, reusable resolution of one run. The cursor is confined to one query operator and stays valid only
	 * while that operator owns the catalog/read-view lease.
	 */
	static final class RunCursor {

		private final LmdbAdjacencyArena.ReadCursor memory = new LmdbAdjacencyArena.ReadCursor();

		private LmdbAdjacencyArenaCatalog catalog;
		private long runHandle = Long.MIN_VALUE;
		private int arenaSlot;
		private MemorySegment segment;
		private long baseOffset;
		private int tag;
		private int codec;
		private boolean contextsPresent;
		private long edgeCount;
		private RunCursor child;

		long edgeCount() {
			return edgeCount;
		}

		private boolean resolves(LmdbAdjacencyArenaCatalog catalog, long runHandle) {
			return this.catalog == catalog && this.runHandle == runHandle;
		}

		private RunCursor child() {
			if (child == null) {
				child = new RunCursor();
			}
			return child;
		}
	}

	static void resolve(LmdbAdjacencyArenaCatalog catalog, long runHandle, RunCursor target) {
		if (target.resolves(catalog, runHandle)) {
			return;
		}
		int slot = catalog.unpackSlot(runHandle);
		long localRef = runHandle & LmdbAdjacencyArena.MAX_U40_VALUE;
		LmdbAdjacencyArena arena = catalog.arena(slot);
		arena.resolve(localRef, 8, target.memory);
		MemorySegment header = target.memory.segment();
		long headerAt = target.memory.baseOffset();
		int tag = Byte.toUnsignedInt(header.get(LmdbAdjacencyArena.U8, headerAt));
		int codec = tag & 0x3;
		if (codec == CODEC_RESERVED || (tag & ~0xF) != 0) {
			throw new IllegalStateException("malformed run tag: " + tag);
		}
		long totalLength;
		long edgeCount;
		switch (codec) {
		case CODEC_SMALL_VARINT: {
			edgeCount = Byte.toUnsignedInt(header.get(LmdbAdjacencyArena.U8, headerAt + 1));
			if (edgeCount < 1 || edgeCount > SMALL_MAX_EDGES) {
				throw new IllegalStateException("malformed SMALL_VARINT edge count: " + edgeCount);
			}
			int neighborByteLength = Short.toUnsignedInt(header.get(LmdbAdjacencyArena.U16_LE, headerAt + 2));
			int contextByteLength = Short.toUnsignedInt(header.get(LmdbAdjacencyArena.U16_LE, headerAt + 4));
			if (Short.toUnsignedInt(header.get(LmdbAdjacencyArena.U16_LE, headerAt + 6)) != 0) {
				throw new IllegalStateException("malformed SMALL_VARINT reserved field");
			}
			totalLength = alignUp(8L + neighborByteLength + contextByteLength, 8);
			break;
		}
		case CODEC_BLOCK_FOR: {
			arena.expand(localRef, BLOCK_HEADER_BYTES, target.memory);
			MemorySegment blockHeader = target.memory.segment();
			if (Byte.toUnsignedInt(blockHeader.get(LmdbAdjacencyArena.U8, headerAt + 1)) != BLOCK_SHIFT) {
				throw new IllegalStateException("malformed BLOCK_FOR block shift");
			}
			edgeCount = blockHeader.get(LmdbAdjacencyArena.U64_LE, headerAt + 8);
			long blockCount = Integer.toUnsignedLong(blockHeader.get(LmdbAdjacencyArena.U32_LE, headerAt + 16));
			long payloadBytes = Integer.toUnsignedLong(blockHeader.get(LmdbAdjacencyArena.U32_LE, headerAt + 20));
			if (edgeCount < 1 || blockCount != (edgeCount + BLOCK_LANES - 1) >>> BLOCK_SHIFT) {
				throw new IllegalStateException("malformed BLOCK_FOR counts: " + edgeCount + "/" + blockCount);
			}
			totalLength = Math.addExact(alignUp(BLOCK_HEADER_BYTES + 4L * (blockCount + 1), 8), payloadBytes);
			break;
		}
		default: {
			arena.expand(localRef, DIRECTORY_HEADER_BYTES, target.memory);
			MemorySegment directoryHeader = target.memory.segment();
			long chunkCount = Integer
					.toUnsignedLong(directoryHeader.get(LmdbAdjacencyArena.U32_LE, headerAt + 4));
			long directoryByteLength = directoryHeader.get(LmdbAdjacencyArena.U64_LE, headerAt + 8);
			if (chunkCount < 1
					|| directoryByteLength != DIRECTORY_HEADER_BYTES + DIRECTORY_ENTRY_BYTES * chunkCount) {
				throw new IllegalStateException("malformed chunk directory length: " + directoryByteLength);
			}
			edgeCount = directoryHeader.get(LmdbAdjacencyArena.U64_LE, headerAt + 16);
			if (edgeCount < 1) {
				throw new IllegalStateException("malformed chunk directory edge count: " + edgeCount);
			}
			totalLength = directoryByteLength;
			break;
		}
		}
		arena.expand(localRef, totalLength, target.memory);
		target.catalog = catalog;
		target.runHandle = runHandle;
		target.arenaSlot = slot;
		target.segment = target.memory.segment();
		target.baseOffset = target.memory.baseOffset();
		target.tag = tag;
		target.codec = codec;
		target.contextsPresent = (tag & TAG_CONTEXT_PRESENT) != 0;
		target.edgeCount = edgeCount;
	}

	static long edgeCount(LmdbAdjacencyArenaCatalog catalog, long runHandle) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return cursor.edgeCount;
	}

	/**
	 * True when every neighbor in the run satisfies {@link ValueIds#isOrderedInteger}.
	 */
	static boolean orderedIntegerDomain(LmdbAdjacencyArenaCatalog catalog, long runHandle) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return (cursor.tag & TAG_ORDERED_INTEGER) != 0;
	}

	static long neighborAt(LmdbAdjacencyArenaCatalog catalog, long runHandle, long ordinal) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return neighborAt(cursor, ordinal);
	}

	/**
	 * The raw context ID at the given ordinal (zero for the null graph).
	 */
	static long contextAt(LmdbAdjacencyArenaCatalog catalog, ContextCatalog contexts, long runHandle, long ordinal) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return contextAt(contexts, cursor, ordinal);
	}

	static long contextAt(ContextCatalog contexts, RunCursor cursor, long ordinal) {
		checkOrdinal(cursor, ordinal);
		long contextOrdinal = contextOrdinalAt(cursor, ordinal);
		return contextOrdinal == 0 ? 0 : contexts.rawForOrdinal(contextOrdinal);
	}

	/**
	 * Copies up to {@code length} pairs starting at {@code fromOrdinal}; context values are raw IDs. Returns the copied
	 * count.
	 */
	static int copy(LmdbAdjacencyArenaCatalog catalog, ContextCatalog contexts, long runHandle, long fromOrdinal,
			int length, long[] neighborTarget, int neighborOffset, long[] contextTarget, int contextOffset) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return copy(contexts, cursor, fromOrdinal, length, neighborTarget, neighborOffset, contextTarget,
				contextOffset);
	}

	static int copy(ContextCatalog contexts, RunCursor cursor, long fromOrdinal, int length, long[] neighborTarget,
			int neighborOffset, long[] contextTarget, int contextOffset) {
		if (length < 0) {
			throw new IllegalArgumentException("length must not be negative: " + length);
		}
		if (fromOrdinal < 0 || fromOrdinal > cursor.edgeCount) {
			throw new IllegalArgumentException("fromOrdinal out of range: " + fromOrdinal);
		}
		int copied = (int) Math.min(length, cursor.edgeCount - fromOrdinal);
		switch (cursor.codec) {
		case CODEC_SMALL_VARINT:
			copySmall(contexts, cursor, fromOrdinal, copied, neighborTarget, neighborOffset, contextTarget,
					contextOffset);
			break;
		case CODEC_BLOCK_FOR:
			copyBlocks(contexts, cursor, fromOrdinal, copied, neighborTarget, neighborOffset, contextTarget,
					contextOffset);
			break;
		default:
			copyChunks(contexts, cursor, fromOrdinal, copied, neighborTarget, neighborOffset, contextTarget,
					contextOffset);
			break;
		}
		return copied;
	}

	/**
	 * First ordinal at or after {@code fromOrdinal} whose decoded {@code (rawNeighbor, rawContext)} pair is unsigned
	 * greater than or equal to the given pair; the edge count when none is.
	 */
	static long lowerBound(LmdbAdjacencyArenaCatalog catalog, ContextCatalog contexts, long runHandle,
			long fromOrdinal, long neighbor, long rawContext) {
		RunCursor cursor = new RunCursor();
		resolve(catalog, runHandle, cursor);
		return lowerBound(contexts, cursor, fromOrdinal, neighbor, rawContext);
	}

	static long lowerBound(ContextCatalog contexts, RunCursor cursor, long fromOrdinal, long neighbor,
			long rawContext) {
		if (fromOrdinal < 0 || fromOrdinal > cursor.edgeCount) {
			throw new IllegalArgumentException("fromOrdinal out of range: " + fromOrdinal);
		}
		long low = fromOrdinal;
		long high = cursor.edgeCount;
		while (low < high) {
			long mid = (low + high) >>> 1;
			long midNeighbor = neighborAt(cursor, mid);
			int cmp = Long.compareUnsigned(midNeighbor, neighbor);
			if (cmp == 0) {
				long midOrdinal = contextOrdinalAt(cursor, mid);
				long midRaw = midOrdinal == 0 ? 0 : contexts.rawForOrdinal(midOrdinal);
				cmp = Long.compareUnsigned(midRaw, rawContext);
			}
			if (cmp < 0) {
				low = mid + 1;
			} else {
				high = mid;
			}
		}
		return low;
	}

	private static void checkOrdinal(RunCursor cursor, long ordinal) {
		if (ordinal < 0 || ordinal >= cursor.edgeCount) {
			throw new IllegalArgumentException("run ordinal out of range: " + ordinal + " of " + cursor.edgeCount);
		}
	}

	static long neighborAt(RunCursor cursor, long ordinal) {
		checkOrdinal(cursor, ordinal);
		switch (cursor.codec) {
		case CODEC_SMALL_VARINT: {
			int neighborByteLength = Short
					.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 2));
			long at = cursor.baseOffset + 8;
			long end = at + neighborByteLength;
			long value = 0;
			for (long i = 0; i <= ordinal; i++) {
				int first = unsignedByte(cursor.segment, at);
				int bytes = checkedVarintBytes(first, at, end);
				long encoded = readUnsigned(cursor.segment, at, first);
				value = i == 0 ? encoded : value + encoded;
				at += bytes;
			}
			return value;
		}
		case CODEC_BLOCK_FOR: {
			long blockAt = blockPayloadAt(cursor, ordinal >>> BLOCK_SHIFT);
			int lane = (int) (ordinal & (BLOCK_LANES - 1));
			checkLane(cursor, blockAt, lane);
			int width = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt + 1));
			long base = cursor.segment.get(LmdbAdjacencyArena.U64_LE, blockAt + 4);
			long lanesAt = blockAt + (cursor.contextsPresent ? 20 : 12);
			return base + readLane(cursor.segment, lanesAt, lane, width);
		}
		default: {
			return inChunk(cursor, ordinal, false);
		}
		}
	}

	private static long contextOrdinalAt(RunCursor cursor, long ordinal) {
		if (!cursor.contextsPresent) {
			return 0;
		}
		switch (cursor.codec) {
		case CODEC_SMALL_VARINT: {
			int neighborByteLength = Short
					.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 2));
			int contextByteLength = Short
					.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 4));
			long at = cursor.baseOffset + 8 + neighborByteLength;
			long end = at + contextByteLength;
			long value = 0;
			for (long i = 0; i <= ordinal; i++) {
				int first = unsignedByte(cursor.segment, at);
				int bytes = checkedVarintBytes(first, at, end);
				value = readUnsigned(cursor.segment, at, first);
				at += bytes;
			}
			return value;
		}
		case CODEC_BLOCK_FOR: {
			long blockAt = blockPayloadAt(cursor, ordinal >>> BLOCK_SHIFT);
			int lane = (int) (ordinal & (BLOCK_LANES - 1));
			checkLane(cursor, blockAt, lane);
			int lanes = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt)) + 1;
			int neighborWidth = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt + 1));
			int contextWidth = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt + 2));
			long contextBase = cursor.segment.get(LmdbAdjacencyArena.U64_LE, blockAt + 12);
			long contextLanesAt = blockAt + 20 + packedBytes(lanes, neighborWidth);
			return contextBase + readLane(cursor.segment, contextLanesAt, lane, contextWidth);
		}
		default: {
			return inChunk(cursor, ordinal, true);
		}
		}
	}

	private static void copySmall(ContextCatalog contexts, RunCursor cursor, long fromOrdinal, int copied,
			long[] neighborTarget, int neighborOffset, long[] contextTarget, int contextOffset) {
		long endOrdinal = fromOrdinal + copied;
		if (neighborTarget != null) {
			int neighborByteLength = Short
					.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 2));
			long at = cursor.baseOffset + 8;
			long end = at + neighborByteLength;
			long value = 0;
			for (long ordinal = 0; ordinal < endOrdinal; ordinal++) {
				int first = unsignedByte(cursor.segment, at);
				int bytes = checkedVarintBytes(first, at, end);
				long encoded = readUnsigned(cursor.segment, at, first);
				value = ordinal == 0 ? encoded : value + encoded;
				at += bytes;
				if (ordinal >= fromOrdinal) {
					neighborTarget[neighborOffset + (int) (ordinal - fromOrdinal)] = value;
				}
			}
		}
		if (contextTarget == null) {
			return;
		}
		if (!cursor.contextsPresent) {
			Arrays.fill(contextTarget, contextOffset, contextOffset + copied, 0L);
			return;
		}
		int neighborByteLength = Short
				.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 2));
		int contextByteLength = Short
				.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U16_LE, cursor.baseOffset + 4));
		long at = cursor.baseOffset + 8 + neighborByteLength;
		long end = at + contextByteLength;
		for (long ordinal = 0; ordinal < endOrdinal; ordinal++) {
			int first = unsignedByte(cursor.segment, at);
			int bytes = checkedVarintBytes(first, at, end);
			long contextOrdinal = readUnsigned(cursor.segment, at, first);
			at += bytes;
			if (ordinal >= fromOrdinal) {
				contextTarget[contextOffset + (int) (ordinal - fromOrdinal)] = contextOrdinal == 0 ? 0
						: contexts.rawForOrdinal(contextOrdinal);
			}
		}
	}

	private static void copyBlocks(ContextCatalog contexts, RunCursor cursor, long fromOrdinal, int copied,
			long[] neighborTarget, int neighborOffset, long[] contextTarget, int contextOffset) {
		long ordinal = fromOrdinal;
		long endOrdinal = fromOrdinal + copied;
		int output = 0;
		while (ordinal < endOrdinal) {
			long blockIndex = ordinal >>> BLOCK_SHIFT;
			long blockAt = blockPayloadAt(cursor, blockIndex);
			int lanes = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt)) + 1;
			int lane = (int) (ordinal & (BLOCK_LANES - 1));
			if (lane >= lanes) {
				throw new IllegalStateException("lane out of range: " + lane + " of " + lanes);
			}
			int take = (int) Math.min(endOrdinal - ordinal, lanes - lane);
			int neighborWidth = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt + 1));
			int contextWidth = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt + 2));
			long neighborBase = cursor.segment.get(LmdbAdjacencyArena.U64_LE, blockAt + 4);
			long neighborLanesAt = blockAt + (cursor.contextsPresent ? 20 : 12);
			long contextBase = cursor.contextsPresent
					? cursor.segment.get(LmdbAdjacencyArena.U64_LE, blockAt + 12)
					: 0;
			long contextLanesAt = neighborLanesAt + packedBytes(lanes, neighborWidth);
			for (int i = 0; i < take; i++) {
				int currentLane = lane + i;
				if (neighborTarget != null) {
					neighborTarget[neighborOffset + output + i] = neighborBase
							+ readLane(cursor.segment, neighborLanesAt, currentLane, neighborWidth);
				}
				if (contextTarget != null) {
					long contextOrdinal = cursor.contextsPresent
							? contextBase + readLane(cursor.segment, contextLanesAt, currentLane, contextWidth)
							: 0;
					contextTarget[contextOffset + output + i] = contextOrdinal == 0 ? 0
							: contexts.rawForOrdinal(contextOrdinal);
				}
			}
			ordinal += take;
			output += take;
		}
	}

	private static void copyChunks(ContextCatalog contexts, RunCursor cursor, long fromOrdinal, int copied,
			long[] neighborTarget, int neighborOffset, long[] contextTarget, int contextOffset) {
		long ordinal = fromOrdinal;
		long endOrdinal = fromOrdinal + copied;
		int output = 0;
		while (ordinal < endOrdinal) {
			long chunk = findChunk(cursor, ordinal);
			long at = cursor.baseOffset + DIRECTORY_HEADER_BYTES + DIRECTORY_ENTRY_BYTES * chunk;
			long edgeStart = cursor.segment.get(LmdbAdjacencyArena.U64_LE, at + 16);
			long edgeCount = cursor.segment.get(LmdbAdjacencyArena.U64_LE, at + 24);
			int chunkSlot = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, at + 32));
			long chunkRef = LmdbAdjacencyArena.readU40(cursor.segment, at + 33);
			long childHandle = cursor.catalog
					.packHandle(chunkSlot == CHUNK_SLOT_SELF ? cursor.arenaSlot : chunkSlot, chunkRef);
			RunCursor child = cursor.child();
			resolve(cursor.catalog, childHandle, child);
			if (child.codec == CODEC_CHUNK_DIRECTORY) {
				throw new IllegalStateException("nested chunk directories are not valid at level 0");
			}
			long childOrdinal = ordinal - edgeStart;
			int take = (int) Math.min(endOrdinal - ordinal, edgeCount - childOrdinal);
			int childCopied = copy(contexts, child, childOrdinal, take, neighborTarget,
					neighborTarget == null ? 0 : neighborOffset + output, contextTarget,
					contextTarget == null ? 0 : contextOffset + output);
			if (childCopied != take) {
				throw new IllegalStateException("chunk copy returned " + childCopied + " of " + take);
			}
			ordinal += take;
			output += take;
		}
	}

	/**
	 * Resolves the chunk containing the global ordinal through the directory and reads from the child run, which may
	 * live in a different arena identified by its explicit slot.
	 */
	private static long inChunk(RunCursor cursor, long ordinal, boolean wantContextOrdinal) {
		long found = findChunk(cursor, ordinal);
		long at = cursor.baseOffset + DIRECTORY_HEADER_BYTES + DIRECTORY_ENTRY_BYTES * found;
		long edgeStart = cursor.segment.get(LmdbAdjacencyArena.U64_LE, at + 16);
		int chunkSlot = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, at + 32));
		long chunkRef = LmdbAdjacencyArena.readU40(cursor.segment, at + 33);
		long childHandle = cursor.catalog
				.packHandle(chunkSlot == CHUNK_SLOT_SELF ? cursor.arenaSlot : chunkSlot, chunkRef);
		RunCursor child = cursor.child();
		resolve(cursor.catalog, childHandle, child);
		if (child.codec == CODEC_CHUNK_DIRECTORY) {
			throw new IllegalStateException("nested chunk directories are not valid at level 0");
		}
		long childOrdinal = ordinal - edgeStart;
		checkOrdinal(child, childOrdinal);
		return wantContextOrdinal ? contextOrdinalAt(child, childOrdinal) : neighborAt(child, childOrdinal);
	}

	private static long findChunk(RunCursor cursor, long ordinal) {
		long chunkCount = Integer
				.toUnsignedLong(cursor.segment.get(LmdbAdjacencyArena.U32_LE, cursor.baseOffset + 4));
		long low = 0;
		long high = chunkCount - 1;
		long found = -1;
		while (low <= high) {
			long mid = (low + high) >>> 1;
			long at = cursor.baseOffset + DIRECTORY_HEADER_BYTES + DIRECTORY_ENTRY_BYTES * mid;
			long edgeStart = cursor.segment.get(LmdbAdjacencyArena.U64_LE, at + 16);
			long edgeCount = cursor.segment.get(LmdbAdjacencyArena.U64_LE, at + 24);
			if (ordinal < edgeStart) {
				high = mid - 1;
			} else if (ordinal >= edgeStart + edgeCount) {
				low = mid + 1;
			} else {
				found = mid;
				break;
			}
		}
		if (found < 0) {
			throw new IllegalStateException("chunk directory does not contain ordinal " + ordinal);
		}
		return found;
	}

	private static int unsignedByte(MemorySegment segment, long at) {
		return Byte.toUnsignedInt(segment.get(LmdbAdjacencyArena.U8, at));
	}

	private static int checkedVarintBytes(int first, long at, long end) {
		int bytes = Varint.firstToLength(first);
		if (at > end || bytes > end - at) {
			throw new IllegalStateException("truncated varint at offset " + at);
		}
		return bytes;
	}

	private static long readUnsigned(MemorySegment segment, long at, int first) {
		if (first <= 240) {
			return first;
		}
		if (first <= 248) {
			return 240L + ((long) (first - 241) << 8) + unsignedByte(segment, at + 1);
		}
		if (first == 249) {
			return 2288L + ((long) unsignedByte(segment, at + 1) << 8) + unsignedByte(segment, at + 2);
		}
		int bytes = first - 247;
		long value = 0;
		for (int i = 0; i < bytes; i++) {
			value = value << 8 | unsignedByte(segment, at + 1 + i);
		}
		return value;
	}

	private static long blockPayloadAt(RunCursor cursor, long blockIndex) {
		long blockCount = Integer
				.toUnsignedLong(cursor.segment.get(LmdbAdjacencyArena.U32_LE, cursor.baseOffset + 16));
		if (blockIndex < 0 || blockIndex >= blockCount) {
			throw new IllegalStateException("block index out of range: " + blockIndex);
		}
		long payloadStart = alignUp(BLOCK_HEADER_BYTES + 4L * (blockCount + 1), 8);
		long offset = Integer.toUnsignedLong(
				cursor.segment.get(LmdbAdjacencyArena.U32_LE,
						cursor.baseOffset + BLOCK_HEADER_BYTES + 4L * blockIndex));
		return cursor.baseOffset + payloadStart + offset;
	}

	private static void checkLane(RunCursor cursor, long blockAt, int lane) {
		int lanes = Byte.toUnsignedInt(cursor.segment.get(LmdbAdjacencyArena.U8, blockAt)) + 1;
		if (lane >= lanes) {
			throw new IllegalStateException("lane out of range: " + lane + " of " + lanes);
		}
	}

	private static long readLane(MemorySegment slice, long lanesAt, int lane, int width) {
		if (width == 0) {
			return 0;
		}
		long bitPos = (long) lane * width;
		long wordIndex = bitPos >>> 6;
		int bitOffset = (int) (bitPos & 63);
		long value = slice.get(LmdbAdjacencyArena.U64_LE, lanesAt + wordIndex * 8) >>> bitOffset;
		if (bitOffset + width > 64) {
			value |= slice.get(LmdbAdjacencyArena.U64_LE, lanesAt + (wordIndex + 1) * 8) << (64 - bitOffset);
		}
		return width == 64 ? value : value & ((1L << width) - 1);
	}

	private static long packedBytes(int lanes, int width) {
		long bits = (long) lanes * width;
		return ((bits + 63) >>> 6) * 8;
	}

	private static int bitsFor(long maxUnsignedDelta) {
		return 64 - Long.numberOfLeadingZeros(maxUnsignedDelta);
	}

	private static long unsignedMin(long[] values, int from, int lanes) {
		long min = values[from];
		for (int i = 1; i < lanes; i++) {
			if (Long.compareUnsigned(values[from + i], min) < 0) {
				min = values[from + i];
			}
		}
		return min;
	}

	static int comparePairsUnsigned(long leftNeighbor, long leftContext, long rightNeighbor, long rightContext) {
		int cmp = Long.compareUnsigned(leftNeighbor, rightNeighbor);
		if (cmp != 0) {
			return cmp;
		}
		return Long.compareUnsigned(leftContext, rightContext);
	}

	private static long alignUp(long value, long alignment) {
		return Math.addExact(value, alignment - 1) & -alignment;
	}
}
