/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.CascadesCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.CascadesPlanProvenanceAnnotator;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.CostVector;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.LogicalProperties;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;
import org.eclipse.rdf4j.query.explanation.TelemetryMetricNames;

/**
 * Final LMDB optimized-EXPLAIN cleanup. It never estimates; it only removes legacy exact annotations and fills
 * conservative planner-owned vector metadata when Cascades produced no winner for a node.
 */
final class LmdbCascadesExplainFinalizer implements QueryOptimizer {
	static final LmdbCascadesExplainFinalizer INSTANCE = new LmdbCascadesExplainFinalizer(null);
	static final String PLANNER_ID = "lmdb-cascades";

	private static final String FALLBACK_SOURCE = "lmdb-cascades-fallback";
	private static final String FALLBACK_USAGE = "fallback_no_winner";
	private static final CostVector FALLBACK_COST = new CostVector(1.0d, 1.0d, 0.0d, 0.0d, 0.0d, 4.0d, 4.0d,
			4.0d, 4.0d, 3.0d, 0.0d, 0.0d);

	private final CascadesCostModel costModel;

	LmdbCascadesExplainFinalizer(EvaluationStatistics statistics) {
		this.costModel = statistics == null ? null : CascadesCostModel.from(statistics);
	}

	@Override
	public void optimize(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		CascadesPlanProvenanceAnnotator.annotateFallback(tupleExpr, PLANNER_ID, FALLBACK_SOURCE, FALLBACK_USAGE,
				this::fallbackCost);
		promoteDistinctCursorSkipRuntimeHints(tupleExpr);
	}

	private CostVector fallbackCost(TupleExpr tupleExpr) {
		if (costModel == null || tupleExpr == null) {
			return FALLBACK_COST;
		}
		try {
			LogicalProperties properties = costModel.logicalProperties(tupleExpr);
			double rows = properties.estimatedRows();
			return CostVector.ofRowsAndWork(rows, Math.max(1.0d, rows), properties.qErrorInterval());
		} catch (RuntimeException ignored) {
			return FALLBACK_COST;
		}
	}

	private void promoteDistinctCursorSkipRuntimeHints(TupleExpr tupleExpr) {
		if (tupleExpr == null) {
			return;
		}
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(StatementPattern node) {
				String decision = node.getStringMetricPlanned(TelemetryMetricNames.OPTIMIZER_PREFIX
						+ "distinctCursorSkipDecision");
				String accessMode = node.getStringMetricPlanned(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE);
				if ("selected".equals(decision) && accessMode == null && LmdbDistinctRequirement.from(node)
						.isPresent()) {
					node.setStringMetricPlanned(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE,
							LmdbDistinctCursorSkipSupport.ACCESS_MODE);
				}
				super.meet(node);
			}
		});
	}
}
