/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Objects;
import java.util.Set;

import org.eclipse.rdf4j.query.algebra.AbstractQueryModelNode;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.QueryModelVisitor;
import org.eclipse.rdf4j.query.algebra.TupleExpr;

final class LmdbLftjTupleExpr extends AbstractQueryModelNode implements TupleExpr {

	private final LmdbLftjPlan plan;

	LmdbLftjTupleExpr(LmdbLftjPlan plan) {
		this.plan = plan;
	}

	LmdbLftjPlan plan() {
		return plan;
	}

	@Override
	public Set<String> getBindingNames() {
		return plan.bindingNames();
	}

	@Override
	public Set<String> getAssuredBindingNames() {
		return plan.assuredBindingNames();
	}

	@Override
	public <X extends Exception> void visit(QueryModelVisitor<X> visitor) throws X {
		visitor.meetOther(this);
	}

	@Override
	public <X extends Exception> void visitChildren(QueryModelVisitor<X> visitor) throws X {
		// leaf-like node
	}

	@Override
	public void replaceChildNode(QueryModelNode current, QueryModelNode replacement) {
		throw new IllegalArgumentException("Not a child node: " + current);
	}

	@Override
	public String getSignature() {
		return super.getSignature() + "[varOrder=" + String.join(",", plan.variableOrder())
				+ "; patterns=" + plan.patternCount()
				+ "; indexes=" + String.join(",", plan.indexNames()) + "]";
	}

	@Override
	public boolean equals(Object other) {
		return other instanceof LmdbLftjTupleExpr && Objects.equals(plan, ((LmdbLftjTupleExpr) other).plan);
	}

	@Override
	public int hashCode() {
		return Objects.hash(plan);
	}

	@Override
	public LmdbLftjTupleExpr clone() {
		return new LmdbLftjTupleExpr(plan.copy());
	}
}
