/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

final class LmdbUnionTrieCursor extends LmdbTrieCursor {

	private final LmdbTrieCursor explicitCursor;
	private final LmdbTrieCursor inferredCursor;

	LmdbUnionTrieCursor(LmdbLftjPatternPlan patternPlan, String variableName, LmdbQueryAccess queryAccess) {
		super(patternPlan, variableName, queryAccess, true);
		this.explicitCursor = new LmdbTrieCursor(patternPlan, variableName, queryAccess, true);
		this.inferredCursor = new LmdbTrieCursor(patternPlan, variableName, queryAccess, false);
	}

	@Override
	boolean initialize(LmdbLftjBindingState state) {
		explicitCursor.initialize(state);
		inferredCursor.initialize(state);
		return mergeCurrent();
	}

	@Override
	boolean seek(long target) {
		if (explicitCursor.available()) {
			explicitCursor.seek(target);
		}
		if (inferredCursor.available()) {
			inferredCursor.seek(target);
		}
		return mergeCurrent();
	}

	@Override
	boolean next() {
		if (!available()) {
			return false;
		}

		long previous = value();
		if (explicitCursor.available() && explicitCursor.value() == previous) {
			explicitCursor.next();
		}
		if (inferredCursor.available() && inferredCursor.value() == previous) {
			inferredCursor.next();
		}
		return mergeCurrent();
	}

	@Override
	void release() {
		clearCurrent();
		explicitCursor.release();
		inferredCursor.release();
	}

	private boolean mergeCurrent() {
		boolean explicitAvailable = explicitCursor.available();
		boolean inferredAvailable = inferredCursor.available();
		if (!explicitAvailable && !inferredAvailable) {
			clearCurrent();
			return false;
		}
		if (!explicitAvailable) {
			setCurrentValue(inferredCursor.value());
			return true;
		}
		if (!inferredAvailable) {
			setCurrentValue(explicitCursor.value());
			return true;
		}
		setCurrentValue(Math.min(explicitCursor.value(), inferredCursor.value()));
		return true;
	}
}
