/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.CostVector;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.Memo;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.MemoExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.OptimizationGoal;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.PhysicalProperties;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleApplication;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleContext;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleKind;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleProof;

final class LmdbNullRejectingOptionalJoinRule extends LmdbRule {
	LmdbNullRejectingOptionalJoinRule() {
		super("lmdb-null-rejecting-optional-join", RuleKind.TRANSFORMATION, 96, null);
	}

	@Override
	public boolean matches(MemoExpr expression, OptimizationGoal goal, Memo memo) {
		return expression.logical()
				&& expression.tupleExpr()instanceof Filter filter
				&& LmdbNullRejectingOptionalSupport.matches(filter);
	}

	@Override
	public List<RuleApplication> apply(MemoExpr expression, OptimizationGoal goal, RuleContext context) {
		Filter filter = (Filter) expression.tupleExpr();
		TupleExpr alternative = LmdbNullRejectingOptionalSupport.rewrite(filter);
		if (alternative == null) {
			return List.of();
		}
		RuleProof proof = proof(semanticScope(goal), Set.of("rhsOnlyBinding", "nullRejectingFilter",
				"optionalToInnerJoin"),
				"OPTIONAL guarded by a null-rejecting RHS filter is equivalent to an inner join");
		return List.of(RuleApplication.transformation(expression.groupId(), alternative, proof));
	}
}

final class LmdbOptionalAnchoredLookupRule extends LmdbRule {
	LmdbOptionalAnchoredLookupRule(EvaluationStatistics statistics) {
		super("lmdb-optional-rhs-anchored-lookup", RuleKind.IMPLEMENTATION, 90, statistics);
	}

	@Override
	public boolean matches(MemoExpr expression, OptimizationGoal goal, Memo memo) {
		return expression.logical() && costModel != null
				&& expression.tupleExpr() instanceof LeftJoin;
	}

	@Override
	public List<RuleApplication> apply(MemoExpr expression, OptimizationGoal goal, RuleContext context) {
		LeftJoin leftJoin = (LeftJoin) expression.tupleExpr();
		boolean scopedUnionHashWildcard = LmdbCascadesRuleProvider
				.containsScopedUnionHashWildcardJoin(leftJoin.getLeftArg());
		Optional<JoinFactorCostModel.FactorCostEstimate> estimate = estimate(expression.tupleExpr(), goal, true);
		if (estimate.isEmpty()) {
			trace(context, "lmdb-rule id=" + id() + " status=no-estimate group=" + expression.groupId()
					+ " expr=" + expression.id());
			return List.of();
		}
		PhysicalProperties delivered = delivered(expression.tupleExpr(), estimate.get(), goal).withAccessPath(
				estimate.get().isDirectLookup() ? "optionalAnchoredLookup" : "optionalRhsScan");
		Set<String> boundVars = goal == null ? Set.of() : goal.requiredProperties().boundVars();
		Set<String> anchoredBoundVars = optionalAnchoredBoundVars(leftJoin, boundVars);
		Set<String> facts = new LinkedHashSet<>();
		facts.add("optionalRhs");
		facts.add("childWinnersVisible");
		facts.add("anchoredBoundVars=" + anchoredBoundVars);
		if (scopedUnionHashWildcard) {
			facts.add("scopedUnionHashWildcard");
		}
		RuleProof proof = proof(semanticScope(goal), facts,
				"OPTIONAL RHS can be costed with assured left bindings as a physical lookup alternative");
		CostVector cost = decomposedOptionalOperatorCost(estimate.get());
		tracePhysicalDecision(context, expression, goal, false, "lmdb-optional-anchor-decomposed", cost,
				estimate.get());
		return List.of(RuleApplication.physical(expression.groupId(), expression.tupleExpr().clone(),
				delivered, cost, proof, "lmdb-optional-anchor-decomposed",
				snapshot(estimate.get(), cost)));
	}

	private Set<String> optionalAnchoredBoundVars(LeftJoin leftJoin, Set<String> goalBoundVars) {
		Set<String> rightBindings = leftJoin.getRightArg().getBindingNames();
		Set<String> anchored = new LinkedHashSet<>();
		if (goalBoundVars != null) {
			for (String boundVar : goalBoundVars) {
				if (rightBindings.contains(boundVar)) {
					anchored.add(boundVar);
				}
			}
		}
		for (String assuredBinding : leftJoin.getLeftArg().getAssuredBindingNames()) {
			if (rightBindings.contains(assuredBinding)) {
				anchored.add(assuredBinding);
			}
		}
		return anchored.isEmpty() ? Set.of() : Set.copyOf(anchored);
	}

	private CostVector decomposedOptionalOperatorCost(JoinFactorCostModel.FactorCostEstimate estimate) {
		CostVector base = cost(estimate);
		Map<String, Double> metrics = estimate.getDoubleMetrics();
		double outputRows = finiteMetric(metrics, "plannedOptionalOutputRows", estimate.getOutputRows());
		double rightRows = finiteMetric(metrics, "plannedOptionalRightRows", estimate.getOutputRows());
		double rightWorkRows = finiteMetric(metrics, "plannedOptionalRightWorkRows", estimate.getWorkRows());
		double operatorWorkRows = Math.max(rightRows, rightWorkRows);
		if (!Double.isFinite(operatorWorkRows) || operatorWorkRows < 0.0d) {
			operatorWorkRows = estimate.getWorkRows();
		}
		return base.withRows(outputRows)
				.withWorkRows(operatorWorkRows);
	}
}
