/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.ArbitraryLengthPath;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.ZeroLengthPath;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.BagEstimate;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.FiniteRelationEstimate;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cost.VariableEstimate;
import org.eclipse.rdf4j.sail.lmdb.estimation.LmdbQuadSynopsisService;
import org.eclipse.rdf4j.sail.lmdb.estimation.QuadEvidence;
import org.eclipse.rdf4j.sail.lmdb.estimation.QuadProbe;
import org.eclipse.rdf4j.sail.lmdb.estimation.RowEvidence;

/** Uniform semantic model for property-path endpoint pairs. */
final class LmdbPropertyPathEstimator {

	private static final String SOURCE = "lmdb-property-path";
	private static final int MAX_MODELLED_DEPTH = 8;

	private final LmdbQuadSynopsisService synopsis;

	LmdbPropertyPathEstimator(LmdbQuadSynopsisService synopsis) {
		this.synopsis = synopsis;
	}

	List<EstimateCandidate> candidates(ArbitraryLengthPath path, StatementPattern step,
			List<EstimateCandidate> directCandidates, EstimateContext context) {
		if (step == null || directCandidates == null || directCandidates.isEmpty()) {
			return List.of(heuristic(path, context));
		}
		double fallbackRows = directCandidates.getFirst().estimate().rows();
		double distinctSubjects = endpointDistinct(step, context, QuadProbe.SUBJECT, fallbackRows);
		double distinctObjects = endpointDistinct(step, context, QuadProbe.OBJECT, fallbackRows);
		boolean subjectBound = bound(path.getSubjectVar(), context);
		boolean objectBound = bound(path.getObjectVar(), context);
		boolean identityGuaranteed = sameEndpoint(path.getSubjectVar(), path.getObjectVar());
		List<EstimateCandidate> result = new ArrayList<>(directCandidates.size());
		for (EstimateCandidate direct : directCandidates) {
			RowEvidence directRows = direct.evidence();
			double rows = rows(directRows.estimate(), path.getMinLength(), distinctSubjects, distinctObjects,
					subjectBound, objectBound, context.invocationCount(), identityGuaranteed);
			double lower = Math.min(rows, rows(directRows.lowerBound(), path.getMinLength(), distinctSubjects,
					distinctObjects, subjectBound, objectBound, context.invocationCount(), identityGuaranteed));
			double upper = Math.max(rows, rows(directRows.upperBound(), path.getMinLength(), distinctSubjects,
					distinctObjects, subjectBound, objectBound, context.invocationCount(), identityGuaranteed));
			boolean complete = path.getMinLength() > 0L && exactZero(directRows);
			RowEvidence evidence = new RowEvidence(rows, lower, upper,
					complete ? 1.0d : directRows.confidence() * 0.75d, complete, context.snapshotIdentity(),
					context.snapshotVersion(), SOURCE);
			result.add(new EstimateCandidate(bag(path.getSubjectVar(), path.getObjectVar(), rows,
					distinctSubjects, distinctObjects, subjectBound, objectBound, SOURCE), evidence, direct.kind(),
					direct.freshness()));
		}
		return List.copyOf(result);
	}

	List<EstimateCandidate> candidates(ZeroLengthPath path, EstimateContext context) {
		Var subject = path.getSubjectVar();
		Var object = path.getObjectVar();
		double invocations = context.invocationCount();
		if (subject != null && subject.hasValue() && object != null && object.hasValue()) {
			double rows = FiniteRelationEstimate.sameValue(subject.getValue(), object.getValue()) ? invocations : 0.0d;
			return List.of(exact(path, rows, context));
		}
		Double finiteRows = finiteEqualityRows(subject, object, context);
		if (finiteRows != null) {
			return List.of(exact(path, finiteRows, context));
		}
		boolean subjectBound = bound(subject, context);
		boolean objectBound = bound(object, context);
		if (subjectBound ^ objectBound || subjectBound && sameEndpoint(subject, object)) {
			return List.of(exact(path, invocations, context));
		}
		if (subjectBound && objectBound) {
			return List.of(uncertainEquality(path, context));
		}
		double distinctSubjects = globalDistinct(QuadProbe.SUBJECT);
		double distinctObjects = globalDistinct(QuadProbe.OBJECT);
		double rowsPerInvocation = Math.max(1.0d, Math.max(distinctSubjects, distinctObjects));
		double upperPerInvocation = Math.max(rowsPerInvocation, saturatingAdd(distinctSubjects, distinctObjects));
		double rows = saturatingMultiply(rowsPerInvocation, invocations);
		double upper = saturatingMultiply(upperPerInvocation, invocations);
		RowEvidence evidence = new RowEvidence(rows, 0.0d, upper, 0.35d, false, context.snapshotIdentity(),
				context.snapshotVersion(), "lmdb-zero-length-path");
		return List.of(new EstimateCandidate(bag(subject, object, rows, distinctSubjects, distinctObjects, false,
				false, "lmdb-zero-length-path"), evidence, EstimateCandidate.Kind.SYNOPSIS,
				context.snapshotVersion()));
	}

	private EstimateCandidate exact(ZeroLengthPath path, double rows, EstimateContext context) {
		BagEstimate estimate = bag(path.getSubjectVar(), path.getObjectVar(), rows, rows, rows,
				bound(path.getSubjectVar(), context), bound(path.getObjectVar(), context), "zero-length-path");
		RowEvidence evidence = new RowEvidence(rows, rows, rows, 1.0d, true, context.snapshotIdentity(),
				context.snapshotVersion(), "zero-length-path");
		return new EstimateCandidate(estimate.withRowsPreservingEvidence(rows, rows, 1.0d, "zero-length-path",
				estimate.metrics(), true), evidence, EstimateCandidate.Kind.FINITE_RELATION, context.snapshotVersion());
	}

	private EstimateCandidate heuristic(ArbitraryLengthPath path, EstimateContext context) {
		BagEstimate estimate = bag(path.getSubjectVar(), path.getObjectVar(), 1.0d, 1.0d, 1.0d,
				bound(path.getSubjectVar(), context), bound(path.getObjectVar(), context), SOURCE);
		RowEvidence evidence = new RowEvidence(1.0d, 0.0d, Double.MAX_VALUE, 0.0d, false,
				context.snapshotIdentity(), context.snapshotVersion(), SOURCE);
		return new EstimateCandidate(estimate, evidence, EstimateCandidate.Kind.HEURISTIC, context.snapshotVersion());
	}

	private EstimateCandidate uncertainEquality(ZeroLengthPath path, EstimateContext context) {
		double invocations = context.invocationCount();
		double domain = Math.max(globalDistinct(QuadProbe.SUBJECT), globalDistinct(QuadProbe.OBJECT));
		double rows = Math.min(invocations, positive(invocations / positive(domain)));
		RowEvidence evidence = new RowEvidence(rows, 0.0d, invocations, 0.2d, false, context.snapshotIdentity(),
				context.snapshotVersion(), "lmdb-zero-length-path");
		BagEstimate estimate = bag(path.getSubjectVar(), path.getObjectVar(), rows, rows, rows, true, true,
				"lmdb-zero-length-path");
		return new EstimateCandidate(estimate, evidence,
				synopsis == null ? EstimateCandidate.Kind.HEURISTIC : EstimateCandidate.Kind.SYNOPSIS,
				context.snapshotVersion());
	}

	private double endpointDistinct(StatementPattern step, EstimateContext context, int projectedComponent,
			double fallbackRows) {
		if (synopsis == null) {
			return positive(fallbackRows);
		}
		QuadProbe base = LmdbStorageEstimatorEvidence.probe(step, context);
		if (base.isBound(projectedComponent)) {
			return 1.0d;
		}
		QuadProbe projection = new QuadProbe(base.boundMask(), projectedComponent, base.subjectId(),
				base.predicateId(), base.objectId(), base.contextId(), base.snapshotIdentity());
		QuadEvidence evidence = synopsis.probe(projection);
		return evidence.distribution()
				.map(distribution -> positive(distribution.distinctRows()))
				.orElseGet(() -> positive(fallbackRows));
	}

	private double globalDistinct(int projectedComponent) {
		if (synopsis == null) {
			return 1.0d;
		}
		QuadEvidence evidence = synopsis.probe(new QuadProbe(0, projectedComponent, 0L, 0L, 0L, 0L,
				synopsis.snapshotIdentity()));
		return evidence.distribution().map(distribution -> positive(distribution.distinctRows())).orElse(1.0d);
	}

	private static double rows(double directRows, long minLength, double distinctSubjects, double distinctObjects,
			boolean subjectBound, boolean objectBound, double invocationCount, boolean identityGuaranteed) {
		double direct = finiteNonNegative(directRows);
		double subjectDomain = positive(distinctSubjects);
		double objectDomain = positive(distinctObjects);
		double domain = Math.max(subjectDomain, objectDomain);
		double fanout = Math.min(8.0d, direct / subjectDomain);
		double result = minLength == 0L ? domain : 0.0d;
		double depthRows = direct;
		long finalDepth = Math.min(MAX_MODELLED_DEPTH, Math.max(4L, minLength + 3L));
		for (long depth = 1L; depth <= finalDepth; depth++) {
			if (depth >= minLength) {
				result = saturatingAdd(result, depthRows);
			}
			depthRows = saturatingMultiply(depthRows, fanout);
		}
		double pairCap = saturatingMultiply(subjectDomain, objectDomain);
		result = Math.min(result, Math.min(pairCap, saturatingMultiply(Math.max(direct, domain), 4.0d)));
		double invocations = positive(invocationCount);
		if (subjectBound && objectBound) {
			double perInvocation = Math.min(1.0d, result / Math.max(1.0d, pairCap));
			if (minLength == 0L && identityGuaranteed) {
				perInvocation = 1.0d;
			}
			return saturatingMultiply(perInvocation, Math.min(invocations, pairCap));
		}
		if (subjectBound) {
			double perInvocation = result / subjectDomain;
			if (minLength == 0L) {
				perInvocation = Math.max(1.0d, perInvocation);
			}
			return saturatingMultiply(perInvocation, Math.min(invocations, subjectDomain));
		} else if (objectBound) {
			double perInvocation = result / objectDomain;
			if (minLength == 0L) {
				perInvocation = Math.max(1.0d, perInvocation);
			}
			return saturatingMultiply(perInvocation, Math.min(invocations, objectDomain));
		}
		return finiteNonNegative(result);
	}

	private static Double finiteEqualityRows(Var subject, Var object, EstimateContext context) {
		if (context.finiteBindings().isEmpty()) {
			return null;
		}
		FiniteRelationEstimate relation = context.finiteBindings().orElseThrow();
		int subjectIndex = endpointIndex(subject, relation);
		int objectIndex = endpointIndex(object, relation);
		if (!resolved(subject, subjectIndex) || !resolved(object, objectIndex)) {
			return null;
		}
		double rows = 0.0d;
		for (Map.Entry<List<Value>, Double> entry : relation.frequencies().entrySet()) {
			Value subjectValue = endpointValue(subject, subjectIndex, entry.getKey());
			Value objectValue = endpointValue(object, objectIndex, entry.getKey());
			if (FiniteRelationEstimate.sameValue(subjectValue, objectValue)) {
				rows = saturatingAdd(rows, entry.getValue());
			}
		}
		return rows;
	}

	private static int endpointIndex(Var endpoint, FiniteRelationEstimate relation) {
		return endpoint == null || endpoint.hasValue() || endpoint.getName() == null
				? -1
				: relation.variables().indexOf(endpoint.getName());
	}

	private static boolean resolved(Var endpoint, int relationIndex) {
		return endpoint != null && (endpoint.hasValue() || relationIndex >= 0);
	}

	private static Value endpointValue(Var endpoint, int relationIndex, List<Value> values) {
		return endpoint.hasValue() ? endpoint.getValue() : values.get(relationIndex);
	}

	private static boolean sameEndpoint(Var subject, Var object) {
		if (subject == null || object == null) {
			return false;
		}
		if (subject.hasValue() || object.hasValue()) {
			return subject.hasValue() && object.hasValue()
					&& FiniteRelationEstimate.sameValue(subject.getValue(), object.getValue());
		}
		return subject.getName() != null && subject.getName().equals(object.getName());
	}

	private static boolean exactZero(RowEvidence evidence) {
		return evidence.complete() && evidence.estimate() == 0.0d && evidence.lowerBound() == 0.0d
				&& evidence.upperBound() == 0.0d;
	}

	private static BagEstimate bag(Var subject, Var object, double rows, double distinctSubjects,
			double distinctObjects, boolean subjectBound, boolean objectBound, String source) {
		BagEstimate result = BagEstimate.heuristic(finiteNonNegative(rows), source);
		result = withVariable(result, subject, subjectBound ? Math.min(1.0d, rows) : distinctSubjects);
		return withVariable(result, object, objectBound ? Math.min(1.0d, rows) : distinctObjects);
	}

	private static BagEstimate withVariable(BagEstimate estimate, Var variable, double distinct) {
		if (variable == null || variable.hasValue() || variable.getName() == null
				|| estimate.variables().containsKey(variable.getName())) {
			return estimate;
		}
		double rows = estimate.rows();
		return estimate.withVariable(variable.getName(),
				VariableEstimate.bound(rows, Math.min(rows, finiteNonNegative(distinct))));
	}

	private static boolean bound(Var variable, EstimateContext context) {
		return variable != null && (variable.hasValue()
				|| variable.getName() != null && context.boundNames().contains(variable.getName()));
	}

	private static double positive(double value) {
		return Double.isFinite(value) && value > 0.0d ? value : 1.0d;
	}

	private static double finiteNonNegative(double value) {
		return Double.isFinite(value) && value >= 0.0d ? value : Double.MAX_VALUE;
	}

	private static double saturatingAdd(double left, double right) {
		return finiteNonNegative(left + right);
	}

	private static double saturatingMultiply(double left, double right) {
		return finiteNonNegative(left * right);
	}
}
