/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Arrays;

import org.eclipse.rdf4j.sail.lmdb.LmdbAdjacencyMemoryAccount.MemoryKind;

/**
 * Complete per-write-transaction primitive event capture for the direct adjacency index (plan 27). Owned by
 * {@link TripleStore} only while direct adjacency is enabled and teed from the two genuine-mutation choke points.
 * <p>
 * Derived-state best effort: a refused reservation or exceeded commit cap sets {@link #overflowed()} and makes later
 * record calls no-ops; it never fails the authoritative statement mutation. {@link #seal(long)} builds the sorted,
 * deduplicated touched-row table before the authoritative LMDB commit, under writer exclusion.
 * <p>
 * Milestone-6 reference-path simplification (hardening deferred to Milestone 9): events and the touched table live in
 * charged primitive on-heap arrays rather than off-heap column pages; the byte projection uses the plan's
 * 113-bytes-per-event seal-peak ceiling.
 */
final class LmdbDirectAdjacencyCommitDelta {

	/** Plan worksheet: event columns (33) + two u64 row tokens (32) + two 24-byte unique row entries (48). */
	static final long PROJECTED_BYTES_PER_EVENT = 113;

	private static final int INITIAL_CAPACITY = 1024;

	private final LmdbAdjacencyMemoryAccount account;

	private long commitMaxBytes;
	private long startRevision;
	private boolean begun;
	private boolean overflowed;

	private long[] subjects = new long[0];
	private long[] predicates = new long[0];
	private long[] objects = new long[0];
	private long[] contexts = new long[0];
	private byte[] flags = new byte[0];
	private int count;
	private long chargedBytes;

	LmdbDirectAdjacencyCommitDelta(LmdbAdjacencyMemoryAccount account, long commitMaxBytes) {
		this.account = account;
		this.commitMaxBytes = commitMaxBytes;
	}

	void begin(long startRevision) {
		if (begun) {
			throw new IllegalStateException("commit delta already begun");
		}
		this.startRevision = startRevision;
		this.begun = true;
		this.overflowed = false;
		this.count = 0;
	}

	boolean begun() {
		return begun;
	}

	boolean overflowed() {
		return overflowed;
	}

	int eventCount() {
		return count;
	}

	void recordAdd(long subject, long predicate, long object, long context, boolean explicit) {
		record(subject, predicate, object, context, explicit, true);
	}

	void recordRemove(long subject, long predicate, long object, long context, boolean explicit) {
		record(subject, predicate, object, context, explicit, false);
	}

	private void record(long subject, long predicate, long object, long context, boolean explicit, boolean add) {
		if (!begun) {
			throw new IllegalStateException("commit delta not begun");
		}
		if (overflowed) {
			return;
		}
		if (count == subjects.length && !grow()) {
			return;
		}
		subjects[count] = subject;
		predicates[count] = predicate;
		objects[count] = object;
		contexts[count] = Math.max(0, context);
		flags[count] = (byte) ((explicit ? 1 : 0) | (add ? 2 : 0));
		count++;
	}

	private boolean grow() {
		int newCapacity = subjects.length == 0 ? INITIAL_CAPACITY : Math.multiplyExact(subjects.length, 2);
		long projectedPeak = Math.multiplyExact((long) newCapacity, PROJECTED_BYTES_PER_EVENT);
		long newChargedBytes = (long) newCapacity * 33;
		if (projectedPeak > commitMaxBytes
				|| !account.tryReserve(MemoryKind.PENDING, newChargedBytes - chargedBytes)) {
			markOverflowed();
			return false;
		}
		chargedBytes = newChargedBytes;
		subjects = Arrays.copyOf(subjects, newCapacity);
		predicates = Arrays.copyOf(predicates, newCapacity);
		objects = Arrays.copyOf(objects, newCapacity);
		contexts = Arrays.copyOf(contexts, newCapacity);
		flags = Arrays.copyOf(flags, newCapacity);
		return true;
	}

	private void markOverflowed() {
		overflowed = true;
		releaseArrays();
	}

	private void releaseArrays() {
		subjects = new long[0];
		predicates = new long[0];
		objects = new long[0];
		contexts = new long[0];
		flags = new byte[0];
		count = 0;
		if (chargedBytes > 0) {
			account.release(MemoryKind.PENDING, chargedBytes);
			chargedBytes = 0;
		}
	}

	/**
	 * Seals this transaction's events into an immutable {@link SealedDirectDelta} with its sorted, deduplicated
	 * pending-row table, and resets this collector for the next transaction. Called under writer exclusion before the
	 * authoritative LMDB commit; record calls between seal and the next {@link #begin} fail fast.
	 */
	SealedDirectDelta seal(long committedRevision) {
		if (!begun) {
			throw new IllegalStateException("commit delta not begun");
		}
		begun = false;
		if (overflowed) {
			overflowed = false;
			return SealedDirectDelta.overflowed(committedRevision);
		}
		if (count == 0) {
			return SealedDirectDelta.empty(committedRevision);
		}
		// charge the seal transition: sort tokens (16 bytes/event) plus the worst-case unique table (48 bytes/event)
		long sealScratchBytes = (long) count * 64;
		if (!account.tryReserve(MemoryKind.PENDING, sealScratchBytes)) {
			releaseArrays();
			return SealedDirectDelta.overflowed(committedRevision);
		}
		try {
			PendingTable pending = buildPendingTable();
			SealedDirectDelta sealed = new SealedDirectDelta(account, committedRevision, subjects, predicates, objects,
					contexts, flags, count, pending, chargedBytes + sealScratchBytes);
			// ownership transferred to the sealed delta
			subjects = new long[0];
			predicates = new long[0];
			objects = new long[0];
			contexts = new long[0];
			flags = new byte[0];
			count = 0;
			chargedBytes = 0;
			return sealed;
		} catch (RuntimeException e) {
			account.release(MemoryKind.PENDING, sealScratchBytes);
			releaseArrays();
			throw e;
		}
	}

	/**
	 * One row token per event and direction, sorted by unsigned {@code (rawKey, plane, rawPredicateId)} and
	 * stream-deduplicated.
	 */
	private PendingTable buildPendingTable() {
		int tokens = Math.multiplyExact(count, 2);
		int[] order = new int[tokens];
		for (int i = 0; i < tokens; i++) {
			order[i] = i;
		}
		sortTokens(order, new int[tokens]);
		long[] keys = new long[tokens];
		long[] preds = new long[tokens];
		byte[] planes = new byte[tokens];
		int unique = 0;
		for (int i = 0; i < tokens; i++) {
			long key = tokenKey(order[i]);
			long pred = predicates[order[i] >>> 1];
			byte plane = tokenPlane(order[i]);
			if (unique > 0 && keys[unique - 1] == key && preds[unique - 1] == pred && planes[unique - 1] == plane) {
				continue;
			}
			keys[unique] = key;
			preds[unique] = pred;
			planes[unique] = plane;
			unique++;
		}
		return new PendingTable(Arrays.copyOf(keys, unique), Arrays.copyOf(preds, unique),
				Arrays.copyOf(planes, unique));
	}

	private long tokenKey(int token) {
		int event = token >>> 1;
		return (token & 1) == 0 ? subjects[event] : objects[event];
	}

	private byte tokenPlane(int token) {
		int event = token >>> 1;
		boolean explicit = (flags[event] & 1) != 0;
		if ((token & 1) == 0) {
			return (byte) (explicit ? LmdbReferenceNodeLocator.PLANE_OUTGOING_EXPLICIT
					: LmdbReferenceNodeLocator.PLANE_OUTGOING_INFERRED);
		}
		return (byte) (explicit ? LmdbReferenceNodeLocator.PLANE_INCOMING_EXPLICIT
				: LmdbReferenceNodeLocator.PLANE_INCOMING_INFERRED);
	}

	private int compareTokens(int a, int b) {
		int cmp = Long.compareUnsigned(tokenKey(a), tokenKey(b));
		if (cmp != 0) {
			return cmp;
		}
		cmp = Byte.compare(tokenPlane(a), tokenPlane(b));
		if (cmp != 0) {
			return cmp;
		}
		return Long.compareUnsigned(predicates[a >>> 1], predicates[b >>> 1]);
	}

	private void sortTokens(int[] values, int[] scratch) {
		mergeSort(values, scratch, 0, values.length);
	}

	private void mergeSort(int[] values, int[] scratch, int from, int to) {
		if (to - from <= 1) {
			return;
		}
		int mid = (from + to) >>> 1;
		mergeSort(values, scratch, from, mid);
		mergeSort(values, scratch, mid, to);
		System.arraycopy(values, from, scratch, from, to - from);
		int left = from;
		int right = mid;
		for (int i = from; i < to; i++) {
			if (left < mid && (right >= to || compareTokens(scratch[left], scratch[right]) <= 0)) {
				values[i] = scratch[left++];
			} else {
				values[i] = scratch[right++];
			}
		}
	}

	/**
	 * Rollback/abort: drop this transaction's events and release their charge.
	 */
	void reset() {
		begun = false;
		overflowed = false;
		releaseArrays();
	}

	/**
	 * The sorted, deduplicated, fenced touched-row table of one committed transaction (plan 27).
	 */
	static final class PendingTable {
		private final long[] rawKeys;
		private final long[] rawPredicates;
		private final byte[] planes;
		private final long minRawKey;
		private final long maxRawKey;
		private final int planeMask;
		private long revision;

		PendingTable(long[] rawKeys, long[] rawPredicates, byte[] planes) {
			this.rawKeys = rawKeys;
			this.rawPredicates = rawPredicates;
			this.planes = planes;
			int mask = 0;
			for (byte plane : planes) {
				mask |= 1 << plane;
			}
			this.planeMask = mask;
			this.minRawKey = rawKeys.length == 0 ? 0 : rawKeys[0];
			this.maxRawKey = rawKeys.length == 0 ? 0 : rawKeys[rawKeys.length - 1];
		}

		void stampRevision(long revision) {
			this.revision = revision;
		}

		long revision() {
			return revision;
		}

		long rowCount() {
			return rawKeys.length;
		}

		/**
		 * Fence-first membership check for one bound row.
		 */
		boolean touches(long rawKey, int plane, long rawPredicateId) {
			if (rawKeys.length == 0 || (planeMask & (1 << plane)) == 0
					|| Long.compareUnsigned(rawKey, minRawKey) < 0
					|| Long.compareUnsigned(rawKey, maxRawKey) > 0) {
				return false;
			}
			int low = 0;
			int high = rawKeys.length - 1;
			while (low <= high) {
				int mid = (low + high) >>> 1;
				int cmp = compareRow(mid, rawKey, plane, rawPredicateId);
				if (cmp < 0) {
					low = mid + 1;
				} else if (cmp > 0) {
					high = mid - 1;
				} else {
					return true;
				}
			}
			return false;
		}

		/**
		 * Fence-first check whether any {@code (rawKey, plane, *)} row is present (unbound-predicate enumeration).
		 */
		boolean touchesNode(long rawKey, int plane) {
			if (rawKeys.length == 0 || (planeMask & (1 << plane)) == 0
					|| Long.compareUnsigned(rawKey, minRawKey) < 0
					|| Long.compareUnsigned(rawKey, maxRawKey) > 0) {
				return false;
			}
			int low = 0;
			int high = rawKeys.length - 1;
			while (low <= high) {
				int mid = (low + high) >>> 1;
				int cmp = compareRow(mid, rawKey, plane, 0);
				if (cmp < 0) {
					low = mid + 1;
				} else if (cmp > 0) {
					high = mid - 1;
				} else {
					return true;
				}
			}
			return low < rawKeys.length && rawKeys[low] == rawKey && planes[low] == plane;
		}

		private int compareRow(int index, long rawKey, int plane, long rawPredicateId) {
			int cmp = Long.compareUnsigned(rawKeys[index], rawKey);
			if (cmp != 0) {
				return cmp;
			}
			cmp = Integer.compare(planes[index], plane);
			if (cmp != 0) {
				return cmp;
			}
			return Long.compareUnsigned(rawPredicates[index], rawPredicateId);
		}
	}

	/**
	 * Immutable ownership transfer of one committed transaction's events and pending table. Closing releases the
	 * complete charge exactly once.
	 */
	static final class SealedDirectDelta {
		private final LmdbAdjacencyMemoryAccount account;
		private final long revision;
		final long[] subjects;
		final long[] predicates;
		final long[] objects;
		final long[] contexts;
		final byte[] flags;
		final int eventCount;
		private final PendingTable pending;
		private final boolean overflowed;
		private long chargedBytes;

		private SealedDirectDelta(LmdbAdjacencyMemoryAccount account, long revision, long[] subjects,
				long[] predicates, long[] objects, long[] contexts, byte[] flags, int eventCount,
				PendingTable pending, long chargedBytes) {
			this.account = account;
			this.revision = revision;
			this.subjects = subjects;
			this.predicates = predicates;
			this.objects = objects;
			this.contexts = contexts;
			this.flags = flags;
			this.eventCount = eventCount;
			this.pending = pending;
			this.overflowed = false;
			this.chargedBytes = chargedBytes;
			if (pending != null) {
				pending.stampRevision(revision);
			}
		}

		private SealedDirectDelta(long revision, boolean overflowed) {
			this.account = null;
			this.revision = revision;
			this.subjects = new long[0];
			this.predicates = new long[0];
			this.objects = new long[0];
			this.contexts = new long[0];
			this.flags = new byte[0];
			this.eventCount = 0;
			this.pending = null;
			this.overflowed = overflowed;
			this.chargedBytes = 0;
		}

		static SealedDirectDelta overflowed(long revision) {
			return new SealedDirectDelta(revision, true);
		}

		static SealedDirectDelta empty(long revision) {
			return new SealedDirectDelta(revision, false);
		}

		long revision() {
			return revision;
		}

		boolean isOverflowed() {
			return overflowed;
		}

		boolean isEmpty() {
			return !overflowed && eventCount == 0;
		}

		PendingTable pendingTable() {
			return pending;
		}

		boolean explicitOf(int event) {
			return (flags[event] & 1) != 0;
		}

		boolean addOf(int event) {
			return (flags[event] & 2) != 0;
		}

		void close() {
			if (chargedBytes > 0) {
				account.release(MemoryKind.PENDING, chargedBytes);
				chargedBytes = 0;
			}
		}
	}
}
