/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.algebra.FunctionCall;
import org.eclipse.rdf4j.query.algebra.LmdbIndexOrder;
import org.eclipse.rdf4j.query.algebra.Order;
import org.eclipse.rdf4j.query.algebra.OrderElem;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor;
import org.eclipse.rdf4j.sail.base.SailDatasetTripleTermSource;

class LmdbOrderByOptimizer implements QueryOptimizer {

	private static final String DIRTY_TRANSACTION_ERROR = "STABLE_INDEX(...) is unavailable after the current transaction has pending changes";

	private final LmdbStableOrderPlanner stableOrderPlanner;
	private final boolean pendingTransactionChanges;

	LmdbOrderByOptimizer(TripleSource tripleSource) {
		this(tripleSource, hasPendingStatementChanges(tripleSource));
	}

	LmdbOrderByOptimizer(TripleSource tripleSource, boolean pendingTransactionChanges) {
		this.stableOrderPlanner = new LmdbStableOrderPlanner(tripleSource);
		this.pendingTransactionChanges = pendingTransactionChanges;
	}

	private static boolean hasPendingStatementChanges(TripleSource tripleSource) {
		return tripleSource instanceof SailDatasetTripleTermSource
				&& ((SailDatasetTripleTermSource) tripleSource).hasPendingStatementChanges();
	}

	@Override
	public void optimize(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		List<Order> orders = new ArrayList<>();

		tupleExpr.visit(new AbstractSimpleQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Order node) {
				super.meet(node);
				orders.add(node);
			}
		});

		for (Order order : orders) {
			Var requestedVar = extractRequestedVar(order);
			if (requestedVar == null) {
				continue;
			}
			if (pendingTransactionChanges) {
				throw new QueryEvaluationException(DIRTY_TRANSACTION_ERROR);
			}

			stableOrderPlanner.plan(order.getArg(), requestedVar.getName())
					.ifPresent(resolution -> {
						resolution.apply();
						order.replaceWith(order.getArg());
					});
		}
	}

	private Var extractRequestedVar(Order order) {
		if (order.getElements().size() != 1) {
			return null;
		}

		OrderElem orderElem = order.getElements().get(0);
		if (!orderElem.isAscending()) {
			return null;
		}

		ValueExpr expr = orderElem.getExpr();
		if (!LmdbIndexOrder.isFunctionCall(expr)) {
			return null;
		}

		FunctionCall functionCall = (FunctionCall) expr;
		if (functionCall.getArgs().size() != 1 || !(functionCall.getArgs().get(0) instanceof Var)) {
			return null;
		}

		Var var = (Var) functionCall.getArgs().get(0);
		if (var.getName() == null) {
			return null;
		}

		return var;
	}
}
