/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;

final class LmdbLftjPatternPlan {

	private final StatementPattern pattern;
	private final String indexName;
	private final TermRef subject;
	private final TermRef predicate;
	private final TermRef object;
	private final TermRef context;

	LmdbLftjPatternPlan(StatementPattern pattern, String indexName) {
		this.pattern = pattern.clone();
		this.indexName = indexName;
		this.subject = TermRef.of(TripleStore.SUBJ_IDX, pattern.getSubjectVar());
		this.predicate = TermRef.of(TripleStore.PRED_IDX, pattern.getPredicateVar());
		this.object = TermRef.of(TripleStore.OBJ_IDX, pattern.getObjectVar());
		this.context = TermRef.of(TripleStore.CONTEXT_IDX, pattern.getContextVar());
	}

	StatementPattern pattern() {
		return pattern;
	}

	String indexName() {
		return indexName;
	}

	List<TermRef> terms() {
		return List.of(subject, predicate, object, context);
	}

	List<String> visibleVariableNames() {
		return terms().stream()
				.filter(TermRef::isVisible)
				.map(TermRef::name)
				.distinct()
				.collect(Collectors.toList());
	}

	boolean containsVariable(String name) {
		return terms().stream().anyMatch(term -> term.matchesName(name));
	}

	TermRef term(char field) {
		switch (field) {
		case 's':
			return subject;
		case 'p':
			return predicate;
		case 'o':
			return object;
		case 'c':
			return context;
		default:
			throw new IllegalArgumentException("Unknown LMDB field: " + field);
		}
	}

	long[] scanKey(LmdbLftjBindingState state) {
		return new long[] {
				state.fixedId(subject),
				state.fixedId(predicate),
				state.fixedId(object),
				state.fixedId(context)
		};
	}

	long valueFor(String variableName, long[] quad) {
		return terms().stream()
				.filter(term -> term.matchesName(variableName))
				.findFirst()
				.map(term -> quad[term.component()])
				.orElseThrow(() -> new IllegalArgumentException("Pattern does not bind variable " + variableName));
	}

	@Override
	public boolean equals(Object other) {
		if (!(other instanceof LmdbLftjPatternPlan)) {
			return false;
		}
		LmdbLftjPatternPlan o = (LmdbLftjPatternPlan) other;
		return Objects.equals(pattern, o.pattern) && Objects.equals(indexName, o.indexName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(pattern, indexName);
	}

	static final class TermRef {

		private final int component;
		private final String name;
		private final boolean anonymous;
		private final Value constantValue;

		private TermRef(int component, String name, boolean anonymous, Value constantValue) {
			this.component = component;
			this.name = name;
			this.anonymous = anonymous;
			this.constantValue = constantValue;
		}

		static TermRef of(int component, Var var) {
			if (var == null) {
				return new TermRef(component, null, true, null);
			}
			if (var.hasValue()) {
				return new TermRef(component, null, false, var.getValue());
			}
			return new TermRef(component, var.getName(), var.isAnonymous(), null);
		}

		int component() {
			return component;
		}

		String name() {
			return name;
		}

		Value constantValue() {
			return constantValue;
		}

		boolean isConstant() {
			return constantValue != null;
		}

		boolean isVisible() {
			return !isConstant() && !anonymous && name != null;
		}

		boolean isHidden() {
			return !isConstant() && !isVisible();
		}

		boolean matchesName(String variableName) {
			return isVisible() && name.equals(variableName);
		}
	}
}
