/*******************************************************************************
 * Copyright (c) 2021 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Supplier;
import java.util.stream.Stream;

import org.eclipse.rdf4j.collection.factory.api.CollectionFactory;
import org.eclipse.rdf4j.collection.factory.mapdb.MapDb3CollectionFactory;
import org.eclipse.rdf4j.common.annotation.Experimental;
import org.eclipse.rdf4j.common.annotation.InternalUseOnly;
import org.eclipse.rdf4j.common.concurrent.locks.Lock;
import org.eclipse.rdf4j.common.concurrent.locks.LockManager;
import org.eclipse.rdf4j.common.transaction.IsolationLevel;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategy;
import org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategyFactory;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizerPipeline;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.federation.FederatedServiceResolver;
import org.eclipse.rdf4j.query.algebra.evaluation.federation.FederatedServiceResolverClient;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.sketch.SketchBasedJoinEstimator;
import org.eclipse.rdf4j.repository.sparql.federation.SPARQLServiceResolver;
import org.eclipse.rdf4j.sail.InterruptedSailException;
import org.eclipse.rdf4j.sail.NotifyingSailConnection;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.base.SailSource;
import org.eclipse.rdf4j.sail.base.SailStore;
import org.eclipse.rdf4j.sail.base.SnapshotSailStore;
import org.eclipse.rdf4j.sail.helpers.AbstractNotifyingSail;
import org.eclipse.rdf4j.sail.helpers.DirectoryLockManager;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.evaluation.LmdbNativeEvaluationStrategyFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A SAIL implementation using LMDB for storing and querying its data.
 *
 * @implNote the LMDB store is in an experimental state: its existence, signature or behavior may change without warning
 *           from one release to the next.
 */
@Experimental
public class LmdbStore extends AbstractNotifyingSail implements FederatedServiceResolverClient {

	private static final Logger logger = LoggerFactory.getLogger(LmdbStore.class);

	/*-----------*
	 * Variables *
	 *-----------*/
	/**
	 * The current version of the LMDB store.
	 */
	/**
	 * Version 4 adds core-datatype tags to eligible non-inline literal reference IDs in newly created stores. Existing
	 * stores upgrade their version marker but retain the absent writer capability and continue minting legacy IDs.
	 */
	static final int VERSION = 4;
	static final String CORE_LITERAL_REFERENCE_MARKER_FILE = "lmdbrdf.ver";
	static final String CORE_LITERAL_REFERENCE_MARKER = "rdf4j-lmdb-core-literal-reference-v1\n";

	/**
	 * Specifies which triple indexes this lmdb store must use.
	 */
	private final LmdbStoreConfig config;

	private SailStore store;

	private LmdbSailStore backingStore;

	// used to decide if store is writable, is true if the store was writable during initialization
	private boolean isWritable;

	// indicates if a datadir is temporary (i.e. will be deleted on shutdown)
	private boolean isTmpDatadir = false;

	/**
	 * Data directory lock.
	 */
	private volatile Lock dirLock;

	private EvaluationStrategyFactory explicitEvalStratFactory;

	private LmdbNativeEvaluationStrategyFactory nativeEvalStratFactory;

	private EvaluationStrategyFactory connectionEvalStratFactory;

	private QueryOptimizerPipeline automaticOptimizerPipeline;

	/**
	 * independent life cycle
	 */
	private FederatedServiceResolver serviceResolver;

	/**
	 * dependent life cycle
	 */
	private SPARQLServiceResolver dependentServiceResolver;
	private final boolean allowIncompleteBulkLoad;
	private final boolean validationOnlyOpen;

	/**
	 * Lock manager used to prevent concurrent {@link #getTransactionLock(IsolationLevel)} calls.
	 */
	private final ReentrantLock txnLockManager = new ReentrantLock();

	/**
	 * Holds locks for all isolated transactions.
	 */
	private final LockManager isolatedLockManager = new LockManager(debugEnabled());

	/**
	 * Holds locks for all {@link IsolationLevels#NONE} isolation transactions.
	 */
	private final LockManager disabledIsolationLockManager = new LockManager(debugEnabled());

	/*--------------*
	 * Constructors *
	 *--------------*/

	/**
	 * Creates a new LmdbStore with default settings.
	 */
	public LmdbStore() {
		this(new LmdbStoreConfig());
	}

	/**
	 * Creates a new LmdbStore.
	 */
	public LmdbStore(LmdbStoreConfig config) {
		super();
		this.config = config;
		allowIncompleteBulkLoad = false;
		validationOnlyOpen = false;
		setSupportedIsolationLevels(IsolationLevels.NONE, IsolationLevels.READ_COMMITTED, IsolationLevels.SNAPSHOT_READ,
				IsolationLevels.SNAPSHOT, IsolationLevels.SERIALIZABLE);
		setDefaultIsolationLevel(IsolationLevels.SNAPSHOT_READ);
		config.getDefaultQueryEvaluationMode().ifPresent(this::setDefaultQueryEvaluationMode);
		setSlowQueryLogThresholdSeconds(config.getSlowQueryLogThresholdSeconds());
		setSlowQueryLogFirstResultThresholdSeconds(config.getSlowQueryLogFirstResultThresholdSeconds());
		setSlowQueryLogFile(config.getSlowQueryLogFile());
		if (config.getIterationCacheSyncThreshold() > 0) {
			setIterationCacheSyncThreshold(config.getIterationCacheSyncThreshold());
		}
		EvaluationStrategyFactory evalStrategyFactory = config.getEvaluationStrategyFactory();
		if (evalStrategyFactory != null) {
			setEvaluationStrategyFactory(evalStrategyFactory);
		}
	}

	/**
	 * Creates a new LmdbStore with default settings.
	 */
	public LmdbStore(File dataDir) {
		this(dataDir, new LmdbStoreConfig());
	}

	public LmdbStore(File dataDir, LmdbStoreConfig config) {
		this(config);
		setDataDir(dataDir);
	}

	LmdbStore(File dataDir, LmdbStoreConfig config, boolean allowIncompleteBulkLoad) {
		super();
		this.config = config;
		this.allowIncompleteBulkLoad = allowIncompleteBulkLoad;
		validationOnlyOpen = true;
		setSupportedIsolationLevels(IsolationLevels.NONE, IsolationLevels.READ_COMMITTED, IsolationLevels.SNAPSHOT_READ,
				IsolationLevels.SNAPSHOT, IsolationLevels.SERIALIZABLE);
		setDefaultIsolationLevel(IsolationLevels.SNAPSHOT_READ);
		config.getDefaultQueryEvaluationMode().ifPresent(this::setDefaultQueryEvaluationMode);
		setSlowQueryLogThresholdSeconds(config.getSlowQueryLogThresholdSeconds());
		setSlowQueryLogFirstResultThresholdSeconds(config.getSlowQueryLogFirstResultThresholdSeconds());
		setSlowQueryLogFile(config.getSlowQueryLogFile());
		if (config.getIterationCacheSyncThreshold() > 0) {
			setIterationCacheSyncThreshold(config.getIterationCacheSyncThreshold());
		}
		EvaluationStrategyFactory evalStrategyFactory = config.getEvaluationStrategyFactory();
		if (evalStrategyFactory != null) {
			setEvaluationStrategyFactory(evalStrategyFactory);
		}
		setDataDir(dataDir);
	}

	/*---------*
	 * Methods *
	 *---------*/

	@Override
	public void setDataDir(File dataDir) {
		super.setDataDir(dataDir);
		isTmpDatadir = (dataDir == null);
	}

	/**
	 * @return Returns the {@link EvaluationStrategy}.
	 */
	public synchronized EvaluationStrategyFactory getEvaluationStrategyFactory() {
		EvaluationStrategyFactory factory;
		if (explicitEvalStratFactory != null) {
			factory = explicitEvalStratFactory;
		} else {
			factory = getAutomaticNativeEvaluationStrategyFactory();
		}
		configureEvaluationStrategyFactory(factory);
		return factory;
	}

	public boolean getPageCardinalityEstimator() {
		return config.getPageCardinalityEstimator();
	}

	/**
	 * Sets the {@link EvaluationStrategy} to use.
	 */
	public synchronized void setEvaluationStrategyFactory(EvaluationStrategyFactory factory) {
		explicitEvalStratFactory = factory;
		if (factory != null) {
			configureEvaluationStrategyFactory(factory);
		}
	}

	/**
	 * @return Returns the SERVICE resolver.
	 */
	public synchronized FederatedServiceResolver getFederatedServiceResolver() {
		if (serviceResolver == null) {
			if (dependentServiceResolver == null) {
				dependentServiceResolver = new SPARQLServiceResolver();
			}
			setFederatedServiceResolver(dependentServiceResolver);
		}
		return serviceResolver;
	}

	/**
	 * Overrides the {@link FederatedServiceResolver} used by this instance, but the given resolver is not shutDown when
	 * this instance is.
	 *
	 * @param resolver The SERVICE resolver to set.
	 */
	@Override
	public synchronized void setFederatedServiceResolver(FederatedServiceResolver resolver) {
		this.serviceResolver = resolver;
		if (resolver != null && explicitEvalStratFactory instanceof FederatedServiceResolverClient) {
			((FederatedServiceResolverClient) explicitEvalStratFactory).setFederatedServiceResolver(resolver);
		}
		if (resolver != null && nativeEvalStratFactory != null) {
			nativeEvalStratFactory.setFederatedServiceResolver(resolver);
		}
	}

	/**
	 * Refuses to open a store whose recorded inlining setting differs from the configured one.
	 *
	 * Inlining is not a writer-only choice like the numeric-id encoding: it changes how a value is IDENTIFIED. With it
	 * enabled, a short {@code xsd:string} resolves to a deterministic {@code T_SHORTSTRING} id without consulting the
	 * dictionary at all; with it disabled the same string gets a dictionary {@code T_LITERAL} id. Every index record
	 * already written is keyed under one of those, so opening under the opposite setting leaves those records keyed
	 * under ids no new lookup will ever produce — plain pattern matching then returns nothing, and the filter-to-probe
	 * pushdowns silently miss rows. Failing the open is the only safe outcome; there is no in-place migration.
	 *
	 * A store written before this property existed records nothing. Such a store is assumed to have used the historical
	 * default (enabled) — which is what {@code LmdbStoreConfig} has always defaulted to — and the assumption is
	 * recorded so the ambiguity is resolved once. A pre-existing store that deliberately disabled inlining cannot be
	 * told apart from one that used the default, and must be recreated rather than reopened.
	 */
	private static void enforceInlineLiterals(StoreProperties properties, LmdbStoreConfig config) {
		Boolean recorded = properties.getInlineLiterals();
		boolean configured = config.getInlineLiterals();
		if (recorded == null) {
			properties.setInlineLiterals(configured);
			if (!configured) {
				throw new SailException("This store predates the inline-literals property, so it is assumed to have "
						+ "been created with literal inlining ENABLED (the long-standing default). Opening it with "
						+ "inlining disabled would key new lookups differently from the existing records. Either open "
						+ "it with inlining enabled, or recreate the store.");
			}
			return;
		}
		if (recorded.booleanValue() != configured) {
			throw new SailException("This store was created with literal inlining "
					+ (recorded.booleanValue() ? "ENABLED" : "DISABLED") + " and cannot be opened with it "
					+ (configured ? "ENABLED" : "DISABLED")
					+ ". Inlining decides how a value is identified, so the existing records are keyed under ids that "
					+ "the other setting never produces. Open the store with its original setting, or recreate it.");
		}
	}

	/**
	 * Initializes this LmdbStore.
	 *
	 * @throws SailException If this LmdbStore could not be initialized using the parameters that have been set.
	 */
	@Override
	protected void initializeInternal() throws SailException {
		logger.debug("Initializing LmdbStore...");

		// Check initialization parameters
		File dataDir = getDataDir();

		if (dataDir == null) {
			try {
				setDataDir(Files.createTempDirectory("rdf4j-lmdb-tmp").toFile());
				isTmpDatadir = true;
			} catch (IOException ioe) {
				throw new SailException("Temp data dir could not be created");
			}
			dataDir = getDataDir();
		} else if (!dataDir.exists()) {
			boolean success = dataDir.mkdirs();
			if (!success) {
				throw new SailException("Unable to create data directory: " + dataDir);
			}
		} else if (!dataDir.isDirectory()) {
			throw new SailException("The specified path does not denote a directory: " + dataDir);
		} else if (!dataDir.canRead()) {
			throw new SailException("Not allowed to read from the specified directory: " + dataDir);
		}
		if (!allowIncompleteBulkLoad && new File(dataDir, ".lmdb-bulk-load.incomplete").exists()) {
			throw new SailException("LMDB bulk-load publication is incomplete for directory: " + dataDir);
		}

		// try to lock the directory or fail
		dirLock = new DirectoryLockManager(dataDir).lockOrFail();

		logger.debug("Data dir is " + dataDir);

		try {
			StoreProperties properties = new StoreProperties(dataDir);
			File compatibilityMarker = new File(dataDir, CORE_LITERAL_REFERENCE_MARKER_FILE);
			boolean coreLiteralMarker = acceptsCoreLiteralReferenceMarker(compatibilityMarker);
			boolean updateVersion = false;
			if (properties.load()) {
				if (!String.valueOf(VERSION).equals(properties.getVersion())) {
					updateVersion = upgradeStore(dataDir, properties.getVersion());
				}
				// existing stores keep their recorded numeric-id encoding (absent = legacy ZigZag) — never rewritten
				enforceInlineLiterals(properties, config);
				if (properties.usesCoreDatatypeLiteralReferences() != coreLiteralMarker) {
					throw new SailException(
							"The core-literal reference encoding property and compatibility marker do not "
									+ "agree. Restore both files from the same store generation or rebuild the store.");
				}
			} else {
				properties.setVersion(String.valueOf(VERSION));
				properties.setLiteralReferenceEncoding(StoreProperties.LITERAL_REFERENCE_ENCODING_CORE_V1);
				if (config.getOrderedNumericIds()) {
					// newly created store: record that writers use the value-ordered inlined-numeric encoding
					properties.setNumericIdEncoding(StoreProperties.NUMERIC_ID_ENCODING_ORDERED_V1);
				}
				// record the inlining setting so later opens can refuse to change it (see enforceInlineLiterals)
				properties.setInlineLiterals(config.getInlineLiterals());
				properties.setCanonicalLanguageTags(StoreProperties.CANONICAL_LANGUAGE_TAGS_LOWERCASE_V1);
				writeCoreLiteralReferenceMarker(dataDir.toPath());
			}

			boolean useSketchBasedJoinEstimator = shouldUseSketchBasedJoinEstimator();
			backingStore = new LmdbSailStore(dataDir, properties, config, useSketchBasedJoinEstimator);

			// update version afer loading and potential internal migration within value and triple store
			if (updateVersion) {
				properties.setVersion(String.valueOf(VERSION));
			}
			properties.save();

			this.store = new SnapshotSailStore(backingStore, () -> new MemoryOverflowModel() {
				@Override
				protected LmdbSailStore createSailStore(File dataDir) throws IOException, SailException {
					// Model can't fit into memory, use another LmdbSailStore to store delta
					StoreProperties overflowProperties = new StoreProperties()
							.setLiteralReferenceEncoding(StoreProperties.LITERAL_REFERENCE_ENCODING_CORE_V1);
					LmdbSailStore lmdbSailStore = new LmdbSailStore(dataDir, overflowProperties, config,
							useSketchBasedJoinEstimator);
					lmdbSailStore.enableMultiThreading = false;
					return lmdbSailStore;
				}
			}) {

				@Override
				public SailSource getExplicitSailSource() {
					if (isIsolationDisabled()) {
						// no isolation, use LmdbSailStore directly
						return backingStore.getExplicitSailSource();
					} else {
						return super.getExplicitSailSource();
					}
				}

				@Override
				public SailSource getInferredSailSource() {
					if (isIsolationDisabled()) {
						// no isolation, use LmdbSailStore directly
						return backingStore.getInferredSailSource();
					} else {
						return super.getInferredSailSource();
					}
				}
			};
		} catch (Throwable e) {
			// LmdbStore initialization failed, release any allocated files
			dirLock.release();

			throw new SailException(e);
		}

		isWritable = getDataDir().canWrite();

		logger.debug("LmdbStore initialized");
	}

	@Override
	protected void shutDownInternal() throws SailException {
		logger.debug("Shutting down LmdbStore...");

		try {
			store.close();
		} finally {
			dirLock.release();
			if (dependentServiceResolver != null) {
				dependentServiceResolver.shutDown();
			}
		}

		if (isTmpDatadir) {
			File dataDir = getDataDir();
			if (dataDir != null) {
				try {
					try (Stream<Path> walk = Files.walk(dataDir.toPath())) {
						walk
								.map(Path::toFile)
								.sorted(Comparator.reverseOrder()) // delete files before directory
								.forEach(File::delete);
					}

				} catch (IOException ioe) {
					logger.error("Could not delete temp file " + dataDir);
				}
			}
		}
		logger.debug("LmdbStore shut down");
	}

	@Override
	public void shutDown() throws SailException {
		super.shutDown();
		// edge case when re-initialize after shutdown
		if (isTmpDatadir) {
			setDataDir(null);
		}
	}

	@Override
	public boolean isWritable() {
		return isWritable;
	}

	@Override
	protected NotifyingSailConnection getConnectionInternal() throws SailException {
		return new LmdbStoreConnection(this);
	}

	@Override
	public ValueFactory getValueFactory() {
		return store.getValueFactory();
	}

	/**
	 * This call will block when {@link IsolationLevels#NONE} is provided when there are active transactions with a
	 * higher isolation and block when a higher isolation is provided when there are active transactions with
	 * {@link IsolationLevels#NONE} isolation. Store is either exclusively in {@link IsolationLevels#NONE} isolation
	 * with potentially zero or more transactions, or exclusively in higher isolation mode with potentially zero or more
	 * transactions.
	 *
	 * @param level indicating desired mode {@link IsolationLevels#NONE} or higher
	 * @return Lock used to prevent Store from switching isolation modes
	 * @throws SailException
	 */
	protected Lock getTransactionLock(IsolationLevel level) throws SailException {
		txnLockManager.lock();
		try {
			if (IsolationLevels.NONE.isCompatibleWith(level)) {
				// make sure no isolated transaction are active
				isolatedLockManager.waitForActiveLocks();
				// mark isolation as disabled
				return disabledIsolationLockManager.createLock(level.toString());
			} else {
				// make sure isolation is not disabled
				disabledIsolationLockManager.waitForActiveLocks();
				// mark isolated transaction as active
				return isolatedLockManager.createLock(level.toString());
			}
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			throw new InterruptedSailException(e);
		} finally {
			txnLockManager.unlock();
		}
	}

	/**
	 * Checks if any {@link IsolationLevels#NONE} isolation transactions are active.
	 *
	 * @return <code>true</code> if at least one transaction has direct access to the indexes
	 */
	boolean isIsolationDisabled() {
		return disabledIsolationLockManager.isActiveLock();
	}

	SailStore getSailStore() {
		return store;
	}

	LmdbSailStore getBackingStore() {
		return backingStore;
	}

	/**
	 * Returns the number of LMDB environment map-size increases since this store was initialized.
	 */
	@InternalUseOnly
	public long getMapGrowthCount() {
		LmdbSailStore current = backingStore;
		if (current == null) {
			throw new IllegalStateException("LMDB store is not initialized");
		}
		return current.getMapGrowthCount();
	}

	EvaluationStrategyFactory getConnectionEvaluationStrategyFactory() {
		EvaluationStrategyFactory factory = connectionEvalStratFactory;
		if (factory == null) {
			synchronized (this) {
				factory = connectionEvalStratFactory;
				if (factory == null) {
					factory = new AdaptiveEvaluationStrategyFactory();
					connectionEvalStratFactory = factory;
				}
			}
		}
		return factory;
	}

	public boolean awaitSketchesReady(long timeout, TimeUnit unit) throws InterruptedException {
		SketchBasedJoinEstimator estimator = getSketchBasedJoinEstimator();
		return estimator != null && estimator.awaitReady(timeout, unit);
	}

	/**
	 * Waits for the configured direct-adjacency maintenance work to publish an exact view of the current LMDB data
	 * revision. Returns {@code false} when direct adjacency is disabled, refused, failed, has no scheduled build, or
	 * the timeout expires.
	 */
	@InternalUseOnly
	public boolean awaitDirectAdjacencyReady(long timeout, TimeUnit unit) throws InterruptedException {
		Objects.requireNonNull(unit, "unit");
		if (timeout < 0L) {
			throw new IllegalArgumentException("timeout must be non-negative");
		}
		LmdbSailStore current = backingStore;
		if (current == null) {
			throw new IllegalStateException("LMDB store is not initialized");
		}
		LmdbDirectAdjacencyStore adjacency = current.directAdjacencyStore();
		return adjacency != null && adjacency.awaitCurrentRevisionReady(timeout, unit);
	}

	/**
	 * Returns the number of owning query datasets that engaged exact direct-adjacency fan-out statistics since this
	 * store was initialized. Multiple estimates within one dataset count as one coarse diagnostic event.
	 */
	@InternalUseOnly
	public long getDirectAdjacencyPlannerStatsHitCount() {
		LmdbSailStore current = backingStore;
		if (current == null) {
			throw new IllegalStateException("LMDB store is not initialized");
		}
		LmdbDirectAdjacencyStore adjacency = current.directAdjacencyStore();
		return adjacency == null ? 0L : adjacency.snapshotMetrics().plannerStatsHits;
	}

	/**
	 * Returns a compact diagnostic description of direct-adjacency readiness.
	 */
	@InternalUseOnly
	public String getDirectAdjacencyReadinessDescription() {
		LmdbSailStore current = backingStore;
		if (current == null) {
			return "uninitialized";
		}
		LmdbDirectAdjacencyStore adjacency = current.directAdjacencyStore();
		if (adjacency == null) {
			return "disabled";
		}
		LmdbAdjacencyMetrics.Snapshot snapshot = adjacency.snapshotMetrics();
		return "state=" + snapshot.state + ", baseRevision=" + snapshot.baseRevision + ", appliedRevision="
				+ snapshot.appliedRevision + ", currentDataRevision=" + snapshot.currentDataRevision
				+ ", gapFromRevision=" + snapshot.gapFromRevision + ", emergencyGapFromRevision="
				+ snapshot.emergencyGapFromRevision + ", buildsStarted=" + snapshot.buildsStarted
				+ ", buildsCompleted=" + snapshot.buildsCompleted + ", buildsAborted=" + snapshot.buildsAborted
				+ ", lastBuildFailure=" + adjacency.lastBuildFailureDescription();
	}

	private boolean shouldUseSketchBasedJoinEstimator() {
		if (validationOnlyOpen) {
			return false;
		}
		return shouldUseSketchBasedJoinEstimator(Runtime.getRuntime().maxMemory());
	}

	boolean shouldUseSketchBasedJoinEstimator(long ignoredMaxMemoryBytes) {
		if (explicitEvalStratFactory != null) {
			return false;
		}

		Boolean sketchEstimatorEnabled = config.getSketchEstimatorEnabled();
		if (sketchEstimatorEnabled != null) {
			return sketchEstimatorEnabled;
		}

		return false;
	}

	private SketchBasedJoinEstimator getSketchBasedJoinEstimator() {
		LmdbSailStore backingStore = this.backingStore;
		return backingStore == null ? null : backingStore.getSketchBasedJoinEstimator();
	}

	private LmdbNativeEvaluationStrategyFactory getAutomaticNativeEvaluationStrategyFactory() {
		QueryOptimizerPipeline optimizerPipeline = getAutomaticOptimizerPipeline();
		if (nativeEvalStratFactory == null) {
			nativeEvalStratFactory = new LmdbNativeEvaluationStrategyFactory(getFederatedServiceResolver());
		}
		if (optimizerPipeline != null) {
			nativeEvalStratFactory.setOptimizerPipeline(optimizerPipeline);
		}
		return nativeEvalStratFactory;
	}

	private QueryOptimizerPipeline getAutomaticOptimizerPipeline() {
		if (automaticOptimizerPipeline != null) {
			return automaticOptimizerPipeline;
		}
		if (nativeEvalStratFactory != null) {
			Optional<QueryOptimizerPipeline> optimizerPipeline = nativeEvalStratFactory.getOptimizerPipeline();
			if (optimizerPipeline.isPresent()) {
				automaticOptimizerPipeline = optimizerPipeline.get();
				return automaticOptimizerPipeline;
			}
		}
		return null;
	}

	private void configureEvaluationStrategyFactory(EvaluationStrategyFactory factory) {
		factory.setQuerySolutionCacheThreshold(getIterationCacheSyncThreshold());
		factory.setTrackResultSize(isTrackResultSize());
		factory.setCollectionFactory(getCollectionFactory());
		if (factory instanceof FederatedServiceResolverClient) {
			((FederatedServiceResolverClient) factory).setFederatedServiceResolver(getFederatedServiceResolver());
		}
	}

	private final class AdaptiveEvaluationStrategyFactory
			implements EvaluationStrategyFactory, FederatedServiceResolverClient {

		@Override
		public void setQuerySolutionCacheThreshold(long threshold) {
			getEvaluationStrategyFactory().setQuerySolutionCacheThreshold(threshold);
		}

		@Override
		public long getQuerySolutionCacheThreshold() {
			return getEvaluationStrategyFactory().getQuerySolutionCacheThreshold();
		}

		@Override
		public void setOptimizerPipeline(QueryOptimizerPipeline pipeline) {
			automaticOptimizerPipeline = pipeline;
			if (explicitEvalStratFactory != null) {
				explicitEvalStratFactory.setOptimizerPipeline(pipeline);
			}
			if (nativeEvalStratFactory != null) {
				nativeEvalStratFactory.setOptimizerPipeline(pipeline);
			}
		}

		@Override
		public Optional<QueryOptimizerPipeline> getOptimizerPipeline() {
			return getEvaluationStrategyFactory().getOptimizerPipeline();
		}

		@Override
		public EvaluationStrategy createEvaluationStrategy(Dataset dataset, TripleSource tripleSource,
				EvaluationStatistics evaluationStatistics) {
			return getEvaluationStrategyFactory().createEvaluationStrategy(dataset, tripleSource, evaluationStatistics);
		}

		@Override
		public boolean isTrackResultSize() {
			return getEvaluationStrategyFactory().isTrackResultSize();
		}

		@Override
		public void setTrackResultSize(boolean trackResultSize) {
			getEvaluationStrategyFactory().setTrackResultSize(trackResultSize);
		}

		@Override
		public void setCollectionFactory(Supplier<CollectionFactory> collectionFactory) {
			getEvaluationStrategyFactory().setCollectionFactory(collectionFactory);
		}

		@Override
		public void setFederatedServiceResolver(FederatedServiceResolver resolver) {
			LmdbStore.this.setFederatedServiceResolver(resolver);
		}

		@Override
		public FederatedServiceResolver getFederatedServiceResolver() {
			return LmdbStore.this.getFederatedServiceResolver();
		}
	}

	private boolean upgradeStore(File dataDir, String version) throws SailException {
		final int storedVersion;
		try {
			storedVersion = Integer.parseInt(version);
		} catch (NumberFormatException e) {
			throw new SailException("Unsupported LmdbStore version: " + version, e);
		}
		if (storedVersion < 1 || storedVersion > VERSION) {
			throw new SailException("Unsupported LmdbStore version: " + storedVersion + " (reader supports through "
					+ VERSION + ")");
		}
		return storedVersion < VERSION;
	}

	private static boolean acceptsCoreLiteralReferenceMarker(File marker) throws SailException {
		if (!marker.exists()) {
			return false;
		}
		try {
			if (CORE_LITERAL_REFERENCE_MARKER.equals(Files.readString(marker.toPath()))) {
				return true;
			}
		} catch (IOException e) {
			throw new SailException("Unable to read LmdbStore compatibility marker " + marker, e);
		}
		throw new SailException("Directory contains data from an older unsupported version of LmdbStore");
	}

	static void writeCoreLiteralReferenceMarker(Path directory) throws IOException {
		Path marker = directory.resolve(CORE_LITERAL_REFERENCE_MARKER_FILE);
		if (Files.exists(marker)) {
			String existing = Files.readString(marker);
			if (!CORE_LITERAL_REFERENCE_MARKER.equals(existing)) {
				throw new IOException("Refusing to overwrite an incompatible LmdbStore marker at " + marker);
			}
			return;
		}
		Files.writeString(marker, CORE_LITERAL_REFERENCE_MARKER);
	}

	@Override
	public Supplier<CollectionFactory> getCollectionFactory() {
		return () -> new MapDb3CollectionFactory(getIterationCacheSyncThreshold());
	}

}
