/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.IdentityHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.query.algebra.ArbitraryLengthPath;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.Memo;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.MemoExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.OptimizationGoal;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleApplication;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleContext;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleKind;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RuleProof;
import org.eclipse.rdf4j.query.explanation.TelemetryMetricNames;

final class LmdbConnectedJoinOrderingRule extends LmdbRule {
	LmdbConnectedJoinOrderingRule(EvaluationStatistics statistics) {
		super("lmdb-cascades-connected-join-order", RuleKind.TRANSFORMATION, 60, statistics);
	}

	@Override
	public boolean matches(MemoExpr expression, OptimizationGoal goal, Memo memo) {
		if (!expression.logical() || costModel == null || !(expression.tupleExpr() instanceof Join)
				|| !LmdbJoinIslandConnectivity.connectedJoinProviderCanOwn(expression.tupleExpr())) {
			return false;
		}
		return LmdbJoinIslandConnectivity.flattenFactors(expression.tupleExpr()).size() > 2;
	}

	@Override
	public List<RuleApplication> apply(MemoExpr expression, OptimizationGoal goal, RuleContext context) {
		List<TupleExpr> factors = LmdbJoinIslandConnectivity.flattenFactors(expression.tupleExpr());
		if (factors.size() < 3) {
			return List.of();
		}
		Set<String> initialBoundVars = goal == null ? Set.of() : goal.requiredProperties().boundVars();
		List<TupleExpr> ordered = connectedGreedyOrder(factors, initialBoundVars);
		List<RuleApplication> applications = new ArrayList<>();
		if (!sameOrder(factors, ordered)) {
			TupleExpr alternative = LmdbCascadesRuleProvider.leftDeepJoin(ordered);
			RuleProof proof = proof(semanticScope(goal), Set.of("cascadesNative", "legacySketchPlanner=false",
					"connectedPrefix", "factors=" + factors.size()),
					"Cascades seeds a connected left-deep join order from LMDB factor costs without invoking the legacy sketch join-order provider");
			applications.add(RuleApplication.transformation(expression.groupId(), alternative, proof));
		}
		for (TupleExpr alternative : connectedPathComplementJoinTrees(factors, initialBoundVars)) {
			RuleProof proof = proof(semanticScope(goal), Set.of("cascadesNative", "legacySketchPlanner=false",
					"pathComplement", "hashJoin", "factors=" + factors.size()),
					"Cascades preserves a path-endpoint complement alternative so a selective endpoint can bind a property path before the opposite component is joined");
			applications.add(RuleApplication.transformation(expression.groupId(), alternative, proof));
		}
		return applications.isEmpty() ? List.of() : List.copyOf(applications);
	}

	private List<TupleExpr> connectedGreedyOrder(List<TupleExpr> factors, Set<String> initialBoundVars) {
		List<TupleExpr> remaining = new ArrayList<>(factors);
		List<TupleExpr> ordered = new ArrayList<>(factors.size());
		Set<String> boundVars = new LinkedHashSet<>(initialBoundVars == null ? Set.of() : initialBoundVars);
		while (!remaining.isEmpty()) {
			boolean hasPrefix = !ordered.isEmpty() || !boundVars.isEmpty();
			int selected = selectFactor(remaining, boundVars, hasPrefix, true);
			if (selected < 0) {
				selected = selectFactor(remaining, boundVars, hasPrefix, false);
			}
			if (selected < 0) {
				selected = 0;
			}
			TupleExpr factor = remaining.remove(selected);
			ordered.add(factor);
			boundVars.addAll(runtimeBindingNames(factor));
		}
		return List.copyOf(ordered);
	}

	private int selectFactor(List<TupleExpr> candidates, Set<String> boundVars, boolean hasPrefix,
			boolean requireConnected) {
		FactorChoice best = null;
		for (int i = 0; i < candidates.size(); i++) {
			TupleExpr candidate = candidates.get(i);
			boolean connected = !hasPrefix || intersects(runtimeBindingNames(candidate), boundVars);
			if (requireConnected && !connected) {
				continue;
			}
			FactorChoice choice = choice(i, candidate, boundVars, hasPrefix, connected);
			if (best == null || choice.compareTo(best) < 0) {
				best = choice;
			}
		}
		return best == null ? -1 : best.index();
	}

	private FactorChoice choice(int index, TupleExpr candidate, Set<String> boundVars, boolean hasPrefix,
			boolean connected) {
		JoinFactorCostModel.FactorCostEstimate estimate = estimate(candidate, boundVars, hasPrefix)
				.orElseGet(() -> fallbackEstimate(candidate));
		double workRows = finiteOrMax(estimate.getWorkRows());
		double outputRows = finiteOrMax(estimate.getOutputRows());
		Set<String> names = runtimeBindingNames(candidate);
		return new FactorChoice(index, workRows, outputRows, -publicBindingCount(names), names.size(), !connected,
				candidate.getSignature());
	}

	private JoinFactorCostModel.FactorCostEstimate fallbackEstimate(TupleExpr candidate) {
		double rows = statistics == null || candidate == null ? Double.NaN : statistics.getCardinality(candidate);
		if (!Double.isFinite(rows) || rows < 0.0d) {
			rows = 1.0d;
		}
		return new JoinFactorCostModel.FactorCostEstimate(rows, rows);
	}

	private double finiteOrMax(double value) {
		return Double.isFinite(value) && value >= 0.0d ? value : Double.MAX_VALUE;
	}

	private boolean sameOrder(List<TupleExpr> left, List<TupleExpr> right) {
		if (left.size() != right.size()) {
			return false;
		}
		for (int i = 0; i < left.size(); i++) {
			if (left.get(i) != right.get(i)) {
				return false;
			}
		}
		return true;
	}

	private List<TupleExpr> connectedPathComplementJoinTrees(List<TupleExpr> factors, Set<String> initialBoundVars) {
		if (factors == null || factors.size() < 3) {
			return List.of();
		}
		List<TupleExpr> alternatives = new ArrayList<>();
		Set<String> seen = new HashSet<>();
		for (TupleExpr factor : factors) {
			if (!(factor instanceof ArbitraryLengthPath path)) {
				continue;
			}
			pathComplementJoinTree(factors, path, true, initialBoundVars)
					.ifPresent(alternative -> addUniqueAlternative(alternatives, seen, alternative));
			pathComplementJoinTree(factors, path, false, initialBoundVars)
					.ifPresent(alternative -> addUniqueAlternative(alternatives, seen, alternative));
		}
		return alternatives.isEmpty() ? List.of() : List.copyOf(alternatives);
	}

	private void addUniqueAlternative(List<TupleExpr> alternatives, Set<String> seen, TupleExpr alternative) {
		String key = alternative == null ? "" : alternative.toString();
		if (!key.isBlank() && seen.add(key)) {
			alternatives.add(alternative);
		}
	}

	private Optional<TupleExpr> pathComplementJoinTree(List<TupleExpr> factors, ArbitraryLengthPath path,
			boolean bindSubjectEndpoint, Set<String> initialBoundVars) {
		String subjectName = plannerVarName(path.getSubjectVar());
		String objectName = plannerVarName(path.getObjectVar());
		if (subjectName == null || objectName == null) {
			return Optional.empty();
		}
		String boundEndpoint = bindSubjectEndpoint ? subjectName : objectName;
		String complementEndpoint = bindSubjectEndpoint ? objectName : subjectName;
		List<TupleExpr> remaining = withoutFactor(factors, path);
		List<TupleExpr> pathSideFactors = connectedComponent(remaining, boundEndpoint);
		List<TupleExpr> complementFactors = connectedComponent(remaining, complementEndpoint);
		if (pathSideFactors.isEmpty() || complementFactors.isEmpty()
				|| !disjoint(pathSideFactors, complementFactors)
				|| pathSideFactors.size() + complementFactors.size() != remaining.size()) {
			return Optional.empty();
		}
		List<TupleExpr> pathSideOrder = connectedGreedyOrder(pathSideFactors,
				boundVarsFor(pathSideFactors, initialBoundVars));
		if (!plannerVarNames(pathSideOrder).contains(boundEndpoint)) {
			return Optional.empty();
		}
		List<TupleExpr> complementOrder = connectedGreedyOrder(complementFactors,
				boundVarsFor(complementFactors, initialBoundVars));
		if (!plannerVarNames(complementOrder).contains(complementEndpoint)) {
			return Optional.empty();
		}
		List<TupleExpr> pathSideWithPath = new ArrayList<>(pathSideOrder.size() + 1);
		pathSideWithPath.addAll(pathSideOrder);
		pathSideWithPath.add(path);
		TupleExpr pathSide = LmdbCascadesRuleProvider.leftDeepJoin(pathSideWithPath);
		TupleExpr complementSide = LmdbCascadesRuleProvider.leftDeepJoin(complementOrder);
		Join join = new Join(pathSide, complementSide);
		join.setStringMetricPlanned(LmdbCascadesRuleProvider.OPTIMIZER_CONNECTED_ENUMERATION,
				LmdbCascadesRuleProvider.CONNECTED_ENUMERATION_CSG_CMP);
		join.setStringMetricPlanned(LmdbCascadesRuleProvider.OPTIMIZER_JOIN_ALGORITHM_HINT,
				LmdbCascadesRuleProvider.JOIN_ALGORITHM_HASH);
		join.setStringMetricPlanned("optimizer.connectedComplementEndpoint", complementEndpoint);
		join.setStringMetricPlanned("optimizer.connectedComplementPathEndpoint",
				bindSubjectEndpoint ? "subject" : "object");
		join.setDoubleMetricPlanned(TelemetryMetricNames.PLANNED_COST_CARTESIAN_WORK_ROWS, 0.0d);
		return Optional.of(join);
	}

	private List<TupleExpr> withoutFactor(List<TupleExpr> factors, TupleExpr excluded) {
		List<TupleExpr> retained = new ArrayList<>(factors.size());
		for (TupleExpr factor : factors) {
			if (factor != excluded) {
				retained.add(factor);
			}
		}
		return List.copyOf(retained);
	}

	private List<TupleExpr> connectedComponent(List<TupleExpr> factors, String seedVar) {
		LinkedHashSet<String> componentVars = new LinkedHashSet<>();
		componentVars.add(seedVar);
		Set<TupleExpr> selected = Collections.newSetFromMap(new IdentityHashMap<>());
		boolean changed;
		do {
			changed = false;
			for (TupleExpr factor : factors) {
				if (selected.contains(factor)) {
					continue;
				}
				Set<String> factorVars = plannerVarNames(factor);
				if (intersects(componentVars, factorVars)) {
					selected.add(factor);
					componentVars.addAll(factorVars);
					changed = true;
				}
			}
		} while (changed);
		if (selected.isEmpty()) {
			return List.of();
		}
		List<TupleExpr> component = new ArrayList<>(selected.size());
		for (TupleExpr factor : factors) {
			if (selected.contains(factor)) {
				component.add(factor);
			}
		}
		return List.copyOf(component);
	}

	private boolean disjoint(List<TupleExpr> left, List<TupleExpr> right) {
		return Collections.disjoint(left, right);
	}

	private Set<String> boundVarsFor(List<TupleExpr> factors, Set<String> boundVars) {
		if (factors == null || factors.isEmpty() || boundVars == null || boundVars.isEmpty()) {
			return Set.of();
		}
		Set<String> factorVars = plannerVarNames(factors);
		LinkedHashSet<String> retained = new LinkedHashSet<>();
		for (String boundVar : boundVars) {
			if (factorVars.contains(boundVar)) {
				retained.add(boundVar);
			}
		}
		return retained.isEmpty() ? Set.of() : Set.copyOf(retained);
	}

	private Set<String> plannerVarNames(List<TupleExpr> tupleExprs) {
		LinkedHashSet<String> names = new LinkedHashSet<>();
		for (TupleExpr tupleExpr : tupleExprs) {
			names.addAll(plannerVarNames(tupleExpr));
		}
		return names.isEmpty() ? Set.of() : Set.copyOf(names);
	}

	private Set<String> plannerVarNames(TupleExpr tupleExpr) {
		return runtimeBindingNames(tupleExpr);
	}

	private String plannerVarName(Var var) {
		if (var == null || var.hasValue() || var.isConstant()) {
			return null;
		}
		String name = var.getName();
		return name == null || name.startsWith("_const_") ? null : name;
	}

	private Set<String> runtimeBindingNames(TupleExpr tupleExpr) {
		return LmdbJoinPlanSupport.runtimeBindingNames(tupleExpr);
	}

	private boolean intersects(Set<String> left, Set<String> right) {
		if (left == null || left.isEmpty() || right == null || right.isEmpty()) {
			return false;
		}
		Set<String> smaller = left.size() <= right.size() ? left : right;
		Set<String> larger = left.size() <= right.size() ? right : left;
		for (String value : smaller) {
			if (larger.contains(value)) {
				return true;
			}
		}
		return false;
	}

	private int publicBindingCount(Set<String> names) {
		if (names == null || names.isEmpty()) {
			return 0;
		}
		int count = 0;
		for (String name : names) {
			if (name != null && !name.startsWith("_anon_")) {
				count++;
			}
		}
		return count;
	}

	private record FactorChoice(int index, double workRows, double outputRows, int negativePublicBindingCount,
			int bindingCount, boolean disconnected, String signature) implements Comparable<FactorChoice> {
		@Override
		public int compareTo(FactorChoice other) {
			int comparison = Boolean.compare(disconnected, other.disconnected);
			if (comparison != 0) {
				return comparison;
			}
			comparison = Double.compare(workRows, other.workRows);
			if (comparison != 0) {
				return comparison;
			}
			comparison = Double.compare(outputRows, other.outputRows);
			if (comparison != 0) {
				return comparison;
			}
			comparison = Integer.compare(negativePublicBindingCount, other.negativePublicBindingCount);
			if (comparison != 0) {
				return comparison;
			}
			comparison = Integer.compare(bindingCount, other.bindingCount);
			if (comparison != 0) {
				return comparison;
			}
			comparison = String.valueOf(signature).compareTo(String.valueOf(other.signature));
			return comparison != 0 ? comparison : Integer.compare(index, other.index);
		}
	}
}
