/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;

record ScopedFactorCostCacheKey(Object factor, Set<String> boundVars, long outerPrefixRowsBits,
		long distinctLookupBindingsBits, boolean nestedIteratorInvocation, boolean collectMetrics,
		Map<String, Set<Value>> finiteBindingValues, JoinFactorCostModel.EstimationTier estimationTier,
		FiniteBranchRowsCacheKey prefixFactors, RequestedAccessPath requestedAccessPath) {

	static ScopedFactorCostCacheKey of(TupleExpr factor, JoinFactorCostModel.CostContext context) {
		JoinFactorCostModel.EstimationTier tier = context.getEstimationTier() == null
				? JoinFactorCostModel.EstimationTier.STANDARD
				: context.getEstimationTier();
		FiniteBranchRowsCacheKey prefixFactors = FiniteBranchRowsCacheKey.of(context.getPrefixFactors());
		return new ScopedFactorCostCacheKey(FactorCostCacheKey.factorFingerprint(factor),
				FactorCostCacheKey.immutableBoundVars(context.getCurrentlyBoundVars()),
				Double.doubleToLongBits(context.getOuterPrefixRows()),
				Double.doubleToLongBits(context.getDistinctLookupBindings()),
				context.isNestedIteratorInvocation(),
				context.shouldCollectMetrics(),
				immutableFiniteBindingValues(context.getFiniteBindingValues()), tier, prefixFactors,
				RequestedAccessPath.of(context));
	}

	static Map<String, Set<Value>> immutableFiniteBindingValues(
			Map<String, Set<Value>> finiteBindingValues) {
		if (finiteBindingValues == null || finiteBindingValues.isEmpty()) {
			return Map.of();
		}
		Map<String, Set<Value>> copy = new HashMap<>();
		for (Map.Entry<String, Set<Value>> entry : finiteBindingValues.entrySet()) {
			if (entry.getKey() == null || entry.getValue() == null || entry.getValue().isEmpty()) {
				continue;
			}
			copy.put(entry.getKey(), Set.copyOf(entry.getValue()));
		}
		return copy.isEmpty() ? Map.of() : Map.copyOf(copy);
	}

	ScopedFactorCostCacheKey toStorable() {
		return new ScopedFactorCostCacheKey(factor, FactorCostCacheKey.immutableBoundVars(boundVars),
				outerPrefixRowsBits, distinctLookupBindingsBits, nestedIteratorInvocation, collectMetrics,
				immutableFiniteBindingValues(finiteBindingValues), estimationTier, prefixFactors,
				requestedAccessPath);
	}
}

record FiniteDerivedSurfaceCacheKey(FiniteBranchRowsCacheKey prefixFactors, Object factor,
		String finiteVarName, Set<Value> finiteValues, boolean allowExact) {

	static FiniteDerivedSurfaceCacheKey of(List<TupleExpr> prefixFactors, TupleExpr factor,
			String finiteVarName, Set<Value> finiteValues, boolean allowExact) {
		return new FiniteDerivedSurfaceCacheKey(FiniteBranchRowsCacheKey.of(prefixFactors),
				FactorCostCacheKey.factorFingerprint(factor), finiteVarName,
				finiteValues == null || finiteValues.isEmpty() ? Set.of() : Set.copyOf(finiteValues),
				allowExact);
	}
}

record FiniteBranchSurfaceCacheKey(FiniteBranchRowsCacheKey factors, String joinVarName,
		boolean allowExact, boolean forceExact) {

	static FiniteBranchSurfaceCacheKey of(List<TupleExpr> factors, String joinVarName,
			boolean allowExact) {
		return new FiniteBranchSurfaceCacheKey(FiniteBranchRowsCacheKey.of(factors), joinVarName, allowExact,
				false);
	}
}

record FiniteBranchFactorSurfaceCacheKey(FiniteBranchRowsCacheKey prefixFactors, Object factor,
		String joinVarName, boolean allowExact, boolean forceExact) {

	static FiniteBranchFactorSurfaceCacheKey of(List<TupleExpr> prefixFactors, TupleExpr factor,
			String joinVarName, boolean allowExact) {
		return of(prefixFactors, factor, joinVarName, allowExact, false);
	}

	static FiniteBranchFactorSurfaceCacheKey of(List<TupleExpr> prefixFactors, TupleExpr factor,
			String joinVarName, boolean allowExact, boolean forceExact) {
		return new FiniteBranchFactorSurfaceCacheKey(FiniteBranchRowsCacheKey.of(prefixFactors),
				FactorCostCacheKey.factorFingerprint(factor), joinVarName, allowExact, forceExact);
	}
}

record CountMinSurfaceCacheKey(FiniteBranchRowsCacheKey prefixFactors, Object factor,
		String joinVarName) {

	static CountMinSurfaceCacheKey of(List<TupleExpr> factors, String joinVarName) {
		return new CountMinSurfaceCacheKey(FiniteBranchRowsCacheKey.of(factors), null, joinVarName);
	}

	static CountMinSurfaceCacheKey of(List<TupleExpr> prefixFactors, TupleExpr factor,
			String joinVarName) {
		return new CountMinSurfaceCacheKey(FiniteBranchRowsCacheKey.of(prefixFactors),
				FactorCostCacheKey.factorFingerprint(factor), joinVarName);
	}
}

record FiniteBranchRowsCacheKey(List<Object> factors, boolean decisionDriven) {

	static FiniteBranchRowsCacheKey of(List<TupleExpr> factors) {
		return of(factors, false);
	}

	static FiniteBranchRowsCacheKey of(List<TupleExpr> factors, boolean decisionDriven) {
		if (factors == null || factors.isEmpty()) {
			return new FiniteBranchRowsCacheKey(List.of(), decisionDriven);
		}
		List<Object> fingerprints = new ArrayList<>(factors.size());
		for (TupleExpr factor : factors) {
			fingerprints.add(FactorCostCacheKey.factorFingerprint(factor));
		}
		// The fingerprint list is freshly built and never escapes this key; no defensive copy needed.
		return new FiniteBranchRowsCacheKey(fingerprints, decisionDriven);
	}
}

record RequestedAccessPath(String accessMode, int lookupComponentMask, int missingLookupComponentMask,
		boolean directLookup) {

	static RequestedAccessPath of(JoinFactorCostModel.CostContext context) {
		if (context == null || !context.hasRequestedAccessPath()) {
			return null;
		}
		return new RequestedAccessPath(context.getRequestedAccessMode(), context.getRequestedLookupComponentMask(),
				context.getRequestedMissingLookupComponentMask(), context.isRequestedDirectLookup());
	}
}
