/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Optional;

import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;

/** Planner-facing view of the engine runtime; it never depends on an RDF4J facade implementation. */
final class LmdbPlannerServices {
	private final LmdbEstimatorRuntime runtime;

	private LmdbPlannerServices(LmdbEstimatorRuntime runtime) {
		this.runtime = runtime;
	}

	static Optional<LmdbPlannerServices> from(EvaluationStatistics statistics) {
		return statistics instanceof LmdbEstimatorRuntimeProvider provider
				? Optional.of(new LmdbPlannerServices(provider.estimatorRuntime()))
				: Optional.empty();
	}

	ValueStore valueStore() {
		return runtime.valueStore();
	}

	Optional<BindingSetAssignment> exactStoredTermFilterAnchor(Filter filter, ValueExpr condition,
			String bindingName) {
		if (filter == null || !(filter.getArg()instanceof StatementPattern pattern)) {
			return Optional.empty();
		}
		return runtime.exactStoredTermFilterAnchor(pattern, condition, bindingName);
	}

}
