/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;

/** Fixed-order estimate view retained behind the LMDB planner composition boundary. */
final class LmdbJoinOrderEstimator {
	private final LmdbEvaluationStatistics statistics;

	LmdbJoinOrderEstimator(LmdbEvaluationStatistics statistics) {
		this.statistics = statistics;
	}

	Optional<JoinOrderPlanner.JoinOrderPlan> estimate(List<TupleExpr> orderedArgs, Set<String> initiallyBoundVars,
			JoinOrderPlanner.Algorithm algorithm, List<JoinOrderPlanner.FilterConstraint> deferredFilters) {
		return statistics.estimateJoinOrder(orderedArgs, initiallyBoundVars, algorithm, deferredFilters);
	}
}
