/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;
import java.util.Properties;

import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.EvaluationStrategy;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizerPipeline;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.BindingAssignerOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.CompareOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.ConjunctiveConstraintSplitterOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.ConstantOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.DisjunctiveConstraintOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.FilterOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.ParentReferenceChecker;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.QueryModelNormalizerOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.RegexAsStringFunctionOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.SameTermFilterOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.UnionScopeChangeOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedCascadesPlanner;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedPlanDecisionSummary;
import org.eclipse.rdf4j.sail.base.SailDatasetTripleTermSource;

final class LmdbQueryOptimizerPipeline implements QueryOptimizerPipeline {

	private static boolean assertsEnabled = false;

	static {
		// noinspection AssertWithSideEffects
		assert assertsEnabled = true;
	}

	private static final BindingAssignerOptimizer BINDING_ASSIGNER = new BindingAssignerOptimizer();
	private static final CompareOptimizer COMPARE_OPTIMIZER = new CompareOptimizer();
	private static final ConjunctiveConstraintSplitterOptimizer CONJUNCTIVE_CONSTRAINT_SPLITTER = new ConjunctiveConstraintSplitterOptimizer();
	private static final DisjunctiveConstraintOptimizer DISJUNCTIVE_CONSTRAINT_OPTIMIZER = new DisjunctiveConstraintOptimizer();
	private static final SameTermFilterOptimizer SAME_TERM_FILTER_OPTIMIZER = new SameTermFilterOptimizer();
	private static final UnionScopeChangeOptimizer UNION_SCOPE_CHANGE_OPTIMIZER = new UnionScopeChangeOptimizer();
	private static final QueryModelNormalizerOptimizer QUERY_MODEL_NORMALIZER = new QueryModelNormalizerOptimizer();

	private final EvaluationStrategy strategy;
	private final TripleSource tripleSource;
	private final EvaluationStatistics evaluationStatistics;
	private final boolean preserveSerializableObservationOrder;
	private final LmdbEstimatorRuntime runtime;
	private final LmdbDetachedPlanningSnapshotProvider detachedPlanningSnapshots;
	private final LmdbPipelinePlanCache planCache;
	private final OptionalLong executionSnapshotEpoch;

	LmdbQueryOptimizerPipeline(EvaluationStrategy strategy, TripleSource tripleSource,
			EvaluationStatistics evaluationStatistics) {
		this(strategy, tripleSource, evaluationStatistics, false);
	}

	LmdbQueryOptimizerPipeline(EvaluationStrategy strategy, TripleSource tripleSource,
			EvaluationStatistics evaluationStatistics, boolean preserveSerializableObservationOrder) {
		this.strategy = strategy;
		this.tripleSource = tripleSource;
		this.evaluationStatistics = evaluationStatistics;
		this.preserveSerializableObservationOrder = preserveSerializableObservationOrder;
		this.runtime = evaluationStatistics instanceof LmdbEstimatorRuntimeProvider provider
				? provider.estimatorRuntime()
				: null;
		this.detachedPlanningSnapshots = evaluationStatistics instanceof LmdbDetachedPlanningSnapshotProvider provider
				? provider
				: null;
		this.planCache = runtime == null ? null : runtime.frontierSettings().pipelinePlanCache();
		this.executionSnapshotEpoch = tripleSource instanceof SailDatasetTripleTermSource source
				? source.getSnapshotEpoch()
				: OptionalLong.empty();
	}

	TupleExpr optimize(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		if (tupleExpr == null || planCache == null) {
			return optimizeUncached(tupleExpr, dataset, bindings);
		}
		LmdbPipelinePlanCache.Context context = context(tupleExpr, dataset, bindings);
		LmdbPipelinePlanCache.Result result = planCache.getOrComputePlan(tupleExpr, context, this::revision,
				() -> computePlan(tupleExpr, dataset, bindings, context));
		if (!result.cacheHit()) {
			return result.plan();
		}
		TupleExpr installed = install(tupleExpr, result.plan());
		annotatePipelineCacheHit(installed, true);
		return installed;
	}

	private LmdbPipelinePlanCache.PlanComputation computePlan(TupleExpr tupleExpr, Dataset dataset,
			BindingSet bindings, LmdbPipelinePlanCache.Context context) {
		for (QueryOptimizer optimizer : requestBoundOptimizers()) {
			optimizer.optimize(tupleExpr, dataset, bindings);
		}
		LmdbCascadesOptimizer cascades = cascadesOptimizer();
		LmdbCascadesOptimizer.PlanningOutcome outcome = cascades.optimizeWithResult(tupleExpr, dataset, bindings);
		if (assertsEnabled) {
			new ParentReferenceChecker(cascades).optimize(outcome.installedPlan(), dataset, bindings);
		}
		TupleExpr optimized = outcome.installedPlan();
		annotatePipelineCacheHit(optimized, false);
		PackedPlanDecisionSummary summary = outcome.cascadesPlan() == null
				? null
				: outcome.cascadesPlan().decisionSummary();
		LmdbPlanDecisionCache.DetachedRefreshWork refreshWork = summary == null || runtime.cascadesPlanCache() == null
				|| detachedPlanningSnapshots == null
						? null
						: PackedCascadesPlanner
								.detachedRefreshWork(outcome.detachedPreparedSource(), outcome.goal(), summary)
								.map(work -> new LmdbDetachedPlanRefresh(runtime, detachedPlanningSnapshots, work,
										context.dataset(),
										context.bindings(),
										context.trackResultSize(), context.preserveObservationOrder(),
										context.runtimeTelemetry(), strategy.getQueryEvaluationMode(), outcome.mode(),
										context.revision().predicateRangeVersion(),
										context.predicateRangeIdentity().predicates()))
								.orElse(null);
		return new LmdbPipelinePlanCache.PlanComputation(optimized, summary, refreshWork);
	}

	private TupleExpr optimizeUncached(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		if (tupleExpr == null) {
			return null;
		}
		for (QueryOptimizer optimizer : getOptimizers()) {
			optimizer.optimize(tupleExpr, dataset, bindings);
		}
		return tupleExpr;
	}

	private LmdbCascadesOptimizer cascadesOptimizer() {
		return new LmdbCascadesOptimizer(evaluationStatistics, strategy.isTrackResultSize(),
				preserveSerializableObservationOrder, strategy, tripleSource);
	}

	private LmdbPipelinePlanCache.Context context(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		LmdbPipelinePlanCache.BindingIdentity bindingIdentity = LmdbPipelinePlanCache.BindingIdentity.of(bindings);
		return new LmdbPipelinePlanCache.Context(
				revision(), executionSnapshotEpoch.isPresent(), executionSnapshotEpoch.orElse(0L),
				LmdbPipelinePlanCache.DatasetIdentity.of(dataset),
				bindingIdentity,
				LmdbPipelinePlanCache.PredicateRangeIdentity.capture(tupleExpr, bindingIdentity, runtime),
				planningConfiguration(),
				preserveSerializableObservationOrder, strategy.isTrackResultSize(), strategy.isTrackTime(),
				strategy.getQueryEvaluationMode().name(), tupleExpr.isRuntimeTelemetryEnabled());
	}

	private LmdbPipelinePlanCache.Revision revision() {
		return new LmdbPipelinePlanCache.Revision(runtime.capturePlanningRevisions(), runtime.predicateRangeVersion(),
				runtime.adaptiveEvidenceAllowed());
	}

	private static String planningConfiguration() {
		Properties properties = System.getProperties();
		List<String> names = new ArrayList<>();
		for (String name : properties.stringPropertyNames()) {
			if (name.startsWith("rdf4j.optimizer.") || name.startsWith("org.eclipse.rdf4j.query.algebra.")) {
				names.add(name);
			}
		}
		Collections.sort(names);
		StringBuilder signature = new StringBuilder(names.size() * 48);
		for (String name : names) {
			String value = properties.getProperty(name, "");
			signature.append(name.length())
					.append(':')
					.append(name)
					.append('=')
					.append(value.length())
					.append(':')
					.append(value)
					.append(';');
		}
		return signature.toString();
	}

	private static TupleExpr install(TupleExpr original, TupleExpr replacement) {
		if (original.getParentNode() != null || original instanceof QueryRoot
				|| original.getClass() == replacement.getClass()) {
			return LmdbCascadesOptimizer.replaceRoot(original, replacement);
		}
		return replacement;
	}

	private static void annotatePipelineCacheHit(TupleExpr root, boolean cacheHit) {
		if (root == null) {
			return;
		}
		String value = Boolean.toString(cacheHit);
		root.setStringMetricPlanned("optimizer.pipelinePlanCacheHit", value);
		if (cacheHit) {
			root.setStringMetricPlanned("optimizer.cascadesPlanCacheHit", "true");
		}
		if (root instanceof QueryRoot queryRoot) {
			queryRoot.getArg().setStringMetricPlanned("optimizer.pipelinePlanCacheHit", value);
			if (cacheHit) {
				queryRoot.getArg().setStringMetricPlanned("optimizer.cascadesPlanCacheHit", "true");
			}
		}
	}

	@Override
	public Iterable<QueryOptimizer> getOptimizers() {
		List<QueryOptimizer> optimizers = requestBoundOptimizerList();
		optimizers.add(cascadesOptimizer());
		return withParentChecks(optimizers);
	}

	private Iterable<QueryOptimizer> requestBoundOptimizers() {
		return withParentChecks(requestBoundOptimizerList());
	}

	private List<QueryOptimizer> requestBoundOptimizerList() {
		List<QueryOptimizer> optimizers = new ArrayList<>();
		optimizers.add(BINDING_ASSIGNER);
		optimizers.add(new ConstantOptimizer(strategy));
		optimizers.add(new RegexAsStringFunctionOptimizer(tripleSource.getValueFactory()));
		Optional<LmdbPlannerServices> services = LmdbPlannerServices.from(evaluationStatistics);
		if (services.isPresent() && services.get().valueStore() != null) {
			optimizers.add(new LmdbValueLookupOptimizer(services.get().valueStore()));
		}
		optimizers.add(COMPARE_OPTIMIZER);
		optimizers.add(CONJUNCTIVE_CONSTRAINT_SPLITTER);
		optimizers.add(DISJUNCTIVE_CONSTRAINT_OPTIMIZER);
		optimizers.add(SAME_TERM_FILTER_OPTIMIZER);
		optimizers.add(UNION_SCOPE_CHANGE_OPTIMIZER);
		optimizers.add(QUERY_MODEL_NORMALIZER);
		optimizers.add(new LmdbOptionalNormalFormOptimizer(evaluationStatistics));
		optimizers.add(new FilterOptimizer(null, false, false));
		optimizers.add(new LmdbBoundSimplifierOptimizer());
		if (!preserveSerializableObservationOrder) {
			optimizers.add(new LmdbSetSemanticsOptimizer());
		}
		optimizers.add(new LmdbFilterSimplifierOptimizer(evaluationStatistics));
		optimizers.add(new LmdbFilterHoistOptimizer());
		return optimizers;
	}

	private static List<QueryOptimizer> withParentChecks(List<QueryOptimizer> optimizers) {
		if (!assertsEnabled) {
			return optimizers;
		}
		List<QueryOptimizer> checked = new ArrayList<>();
		checked.add(new ParentReferenceChecker(null));
		for (QueryOptimizer optimizer : optimizers) {
			checked.add(optimizer);
			checked.add(new ParentReferenceChecker(optimizer));
		}
		return checked;
	}
}
