/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.List;
import java.util.Map;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.sail.lmdb.sketch.JoinFrequencyEstimate;

record FilterCostApplication(double workRows, double outputRows, Map<String, String> stringMetrics,
		Map<String, Double> doubleMetrics) {
}

record ConnectedBranchEstimate(double rows, double minRows, double maxRows, int anchorCount, int sampleCount) {
}

record CorrelatedAntiExistsExactEstimate(double inputRows, double matchedRows, double outputRows,
		double probeLookupRows, double rhsRowsScanned, double probeWorkRows) {

	double probeOutputRows() {
		return matchedRows;
	}
}

record CorrelatedAntiProbePattern(StatementPattern pattern, ValueExpr condition) {
}

record CorrelatedAntiExistsExactCacheKey(int tripleStoreIdentity, long dataRevision,
		Object inputFingerprint, Object antiProbeFingerprint, String sharedBinding) {
}

record CorrelatedAntiProbeResult(boolean matched, long rhsRowsScanned) {
}

record PatternIds(long subjectId, long predicateId, long objectId, long contextId) {

	static final PatternIds ZERO_ROWS = new PatternIds(Long.MIN_VALUE, Long.MIN_VALUE,
			Long.MIN_VALUE, Long.MIN_VALUE);

	boolean zeroRows() {
		return this == ZERO_ROWS;
	}
}

record CountMinSurfaceCalibration(double factor, double confidence) {
}

record AccessPathEstimate(double workRowsPerInvocation, double rowsBeforeFilterAtAccess,
		double rowsAfterFilterAtAccess, String indexFieldSequence, int prefixLength, int prefixComponentMask,
		boolean directLookup, int lookupComponentMask, int missingLookupComponentMask, int candidateCount) {
}

record FiniteDerivedSurfaceEstimate(double surfaceRows, double prefixRows, int branchCount,
		boolean exactRows, String finiteVarName, String estimateSource,
		JoinFrequencyEstimate countMinEvidence) {

	FiniteDerivedSurfaceEstimate {
		if (estimateSource == null || estimateSource.isBlank()) {
			estimateSource = LmdbEvaluationStatistics.FINITE_DERIVED_SURFACE_SOURCE;
		}
	}

	FiniteDerivedSurfaceEstimate(double surfaceRows, double prefixRows, int branchCount,
			boolean exactRows, String finiteVarName) {
		this(surfaceRows, prefixRows, branchCount, exactRows, finiteVarName,
				LmdbEvaluationStatistics.FINITE_DERIVED_SURFACE_SOURCE, null);
	}

	FiniteDerivedSurfaceEstimate(double surfaceRows, double prefixRows, int branchCount,
			boolean exactRows, String finiteVarName, String estimateSource) {
		this(surfaceRows, prefixRows, branchCount, exactRows, finiteVarName, estimateSource, null);
	}
}

record FiniteBranchSurfaceEstimate(double rows, boolean exactRows,
		JoinFrequencyEstimate countMinEvidence) {

	FiniteBranchSurfaceEstimate(double rows, boolean exactRows) {
		this(rows, exactRows, null);
	}
}

record BridgeContinuationEstimate(double rows, boolean exactRows) {
}

record BoundProductPageWalkBlend(double rawOutputRows, double rawWorkRows,
		double pageWalkOutputRows, double pageWalkWorkRows, double outputRows, double workRows,
		double repeatedInvocations, double accessRows, double accessWorkRows, double disagreementRatio,
		String fusion) {
}

record BridgeProductPrefixFactors(List<TupleExpr> factors, boolean preservesKnownRows) {
}

record PrefixBridgeEstimate(double rows, double prefixRows, double prefixSurfaceRows,
		double prefixBridgeSurfaceRows, String joinVarName) {
}

record BridgeCandidate(StatementPattern bridge, PrefixBridgeEstimate prefixBridge) {
}

record SubstitutedFactor(TupleExpr factor, boolean substituted, boolean unsupported) {
	static SubstitutedFactor skipped() {
		return new SubstitutedFactor(null, false, false);
	}

	static SubstitutedFactor unsupportedFactor() {
		return new SubstitutedFactor(null, false, true);
	}
}

record VariableCompare(String variableName, Compare.CompareOp operator, Value constant) {
}
