/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Projection;
import org.eclipse.rdf4j.query.algebra.ProjectionElem;
import org.eclipse.rdf4j.query.algebra.ProjectionElemList;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;
import org.eclipse.rdf4j.query.algebra.helpers.collectors.VarNameCollector;

/**
 * Pushes simple identity projections toward join leaves so sketch planning can cost narrower binding surfaces.
 */
final class LmdbProjectionPushdownOptimizer implements QueryOptimizer {

	@Override
	public void optimize(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		Objects.requireNonNull(tupleExpr, "tupleExpr must not be null");
		tupleExpr.visit(new ProjectionPushdownVisitor());
	}

	private static final class ProjectionPushdownVisitor extends AbstractQueryModelVisitor<RuntimeException> {

		@Override
		public void meet(Projection projection) {
			super.meet(projection);

			if (!isIdentityProjection(projection)) {
				return;
			}

			List<String> projectedNames = projectionNames(projection);
			TupleExpr arg = projection.getArg();
			if (arg instanceof Projection innerProjection) {
				mergeNestedProjection(projection, innerProjection, projectedNames);
			} else if (arg instanceof Filter filter) {
				pushThroughFilter(filter, projectedNames);
			} else if (arg instanceof Join join) {
				pushThroughJoin(join, projectedNames);
			} else if (arg instanceof Union union) {
				pushThroughUnion(union, projectedNames);
			} else if (arg instanceof Difference difference) {
				pushThroughDifference(difference, projectedNames);
			} else if (arg instanceof LeftJoin leftJoin) {
				pushThroughLeftJoin(leftJoin, projectedNames);
			}
		}
	}

	private static void mergeNestedProjection(Projection outer, Projection inner, List<String> projectedNames) {
		if (!isIdentityProjection(inner) || !new LinkedHashSet<>(projectionNames(inner)).containsAll(projectedNames)) {
			return;
		}
		outer.setArg(inner.getArg());
	}

	private static void pushThroughFilter(Filter filter, List<String> projectedNames) {
		Set<String> neededNames = linkedSet(projectedNames);
		neededNames.addAll(conditionVarNames(filter.getCondition()));
		filter.setArg(project(filter.getArg(), neededNames));
	}

	private static void pushThroughJoin(Join join, List<String> projectedNames) {
		Set<String> requiredNames = linkedSet(projectedNames);
		Set<String> leftBindingNames = join.getLeftArg().getBindingNames();
		Set<String> rightBindingNames = join.getRightArg().getBindingNames();
		Set<String> sharedNames = intersection(leftBindingNames, rightBindingNames);

		Set<String> leftNeededNames = intersection(requiredNames, leftBindingNames);
		leftNeededNames.addAll(sharedNames);
		Set<String> rightNeededNames = intersection(requiredNames, rightBindingNames);
		rightNeededNames.addAll(sharedNames);

		join.setLeftArg(project(join.getLeftArg(), leftNeededNames));
		join.setRightArg(project(join.getRightArg(), rightNeededNames));
	}

	private static void pushThroughUnion(Union union, List<String> projectedNames) {
		Set<String> requiredNames = linkedSet(projectedNames);
		if (!union.getLeftArg().getBindingNames().containsAll(requiredNames)
				|| !union.getRightArg().getBindingNames().containsAll(requiredNames)) {
			return;
		}
		union.setLeftArg(project(union.getLeftArg(), requiredNames));
		union.setRightArg(project(union.getRightArg(), requiredNames));
	}

	private static void pushThroughDifference(Difference difference, List<String> projectedNames) {
		Set<String> requiredNames = linkedSet(projectedNames);
		Set<String> leftBindingNames = difference.getLeftArg().getBindingNames();
		Set<String> rightBindingNames = difference.getRightArg().getBindingNames();
		Set<String> sharedNames = intersection(leftBindingNames, rightBindingNames);

		Set<String> leftNeededNames = intersection(requiredNames, leftBindingNames);
		leftNeededNames.addAll(sharedNames);
		Set<String> rightNeededNames = intersection(sharedNames, rightBindingNames);

		difference.setLeftArg(project(difference.getLeftArg(), leftNeededNames));
		difference.setRightArg(project(difference.getRightArg(), rightNeededNames));
	}

	private static void pushThroughLeftJoin(LeftJoin leftJoin, List<String> projectedNames) {
		if (leftJoin.hasCondition()) {
			return;
		}
		Set<String> requiredNames = linkedSet(projectedNames);
		Set<String> leftBindingNames = leftJoin.getLeftArg().getBindingNames();
		Set<String> rightBindingNames = leftJoin.getRightArg().getBindingNames();
		Set<String> sharedNames = intersection(leftBindingNames, rightBindingNames);
		Set<String> conditionNames = conditionVarNames(leftJoin.getCondition());

		Set<String> leftNeededNames = intersection(requiredNames, leftBindingNames);
		leftNeededNames.addAll(sharedNames);
		leftNeededNames.addAll(intersection(conditionNames, leftBindingNames));
		Set<String> rightNeededNames = intersection(requiredNames, rightBindingNames);
		rightNeededNames.addAll(sharedNames);
		rightNeededNames.addAll(intersection(conditionNames, rightBindingNames));

		leftJoin.setLeftArg(project(leftJoin.getLeftArg(), leftNeededNames));
		leftJoin.setRightArg(project(leftJoin.getRightArg(), rightNeededNames));
	}

	private static TupleExpr project(TupleExpr arg, Set<String> neededNames) {
		List<String> orderedNames = orderedNames(arg, neededNames);
		if (arg instanceof Projection projection && isIdentityProjection(projection)
				&& projectionNames(projection).equals(orderedNames)) {
			return arg;
		}
		return new Projection(arg, projectionElemList(orderedNames));
	}

	private static List<String> orderedNames(TupleExpr arg, Set<String> neededNames) {
		List<String> orderedNames = new ArrayList<>();
		for (String bindingName : arg.getBindingNames()) {
			if (neededNames.contains(bindingName)) {
				orderedNames.add(bindingName);
			}
		}
		return orderedNames;
	}

	private static ProjectionElemList projectionElemList(List<String> names) {
		ProjectionElemList projectionElemList = new ProjectionElemList();
		for (String name : names) {
			projectionElemList.addElement(new ProjectionElem(name));
		}
		return projectionElemList;
	}

	private static boolean isIdentityProjection(Projection projection) {
		Set<String> names = new LinkedHashSet<>();
		for (ProjectionElem elem : projection.getProjectionElemList().getElements()) {
			if (elem.getName() == null || elem.getProjectionAlias().isPresent()
					|| elem.hasAggregateOperatorInExpression() || elem.getSourceExpression() != null
					|| !names.add(elem.getName())) {
				return false;
			}
		}
		return true;
	}

	private static List<String> projectionNames(Projection projection) {
		return projection.getProjectionElemList()
				.getElements()
				.stream()
				.map(ProjectionElem::getName)
				.toList();
	}

	private static Set<String> conditionVarNames(ValueExpr condition) {
		if (condition == null) {
			return Set.of();
		}
		return VarNameCollector.process(condition);
	}

	private static Set<String> linkedSet(List<String> names) {
		return new LinkedHashSet<>(names);
	}

	private static Set<String> intersection(Set<String> leftNames, Set<String> rightNames) {
		Set<String> intersection = new LinkedHashSet<>(leftNames);
		intersection.retainAll(rightNames);
		return intersection;
	}
}
