/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedCostContext;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedCostEstimate;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedQueryView;

/** LMDB storage-cardinality adapter for the packed ID-based cost boundary. */
final class LmdbPackedCostModel implements PackedCostModel {

	static final long VERSION = 1L;

	private final LmdbEstimatorRuntime runtime;

	LmdbPackedCostModel(LmdbEstimatorRuntime runtime) {
		this.runtime = runtime;
	}

	@Override
	public double estimateRows(PackedQueryView query, int relationId) {
		if (!query.isStatementPattern(relationId)) {
			return Double.NaN;
		}
		Value subjectValue = query.statementPatternValue(relationId, 0);
		Value predicateValue = query.statementPatternValue(relationId, 1);
		Value objectValue = query.statementPatternValue(relationId, 2);
		Value contextValue = query.statementPatternValue(relationId, 3);
		if (subjectValue != null && !(subjectValue instanceof Resource)
				|| predicateValue != null && !(predicateValue instanceof IRI)
				|| contextValue != null && !(contextValue instanceof Resource)) {
			return 0.0d;
		}
		return runtime.packedStatementPatternRows((Resource) subjectValue, (IRI) predicateValue, objectValue,
				(Resource) contextValue, repeatedComponentPairMask(query, relationId));
	}

	@Override
	public double estimateLocalWork(PackedQueryView query, int relationId, double outputRows) {
		return query.isStatementPattern(relationId) ? outputRows : Double.NaN;
	}

	@Override
	public void estimate(PackedQueryView query, int relationId, PackedCostContext context,
			PackedCostEstimate output) {
		if (!query.isStatementPattern(relationId)) {
			output.setRows(Double.NaN, Double.NaN);
			return;
		}
		double rows = finiteLookupRows(query, relationId, context);
		boolean contextualRows = Double.isFinite(rows);
		if (!contextualRows) {
			rows = estimateRows(query, relationId);
		}
		if (!Double.isFinite(rows) || rows < 0.0d) {
			output.setRows(Double.NaN, Double.NaN);
			return;
		}
		double invocations = invocationCount(query, context);
		double accessRows = rows == 0.0d ? 0.0d : Math.max(1.0d, rows / Math.max(1.0d, invocations));
		double workRows = Math.max(rows, invocations);
		if (contextualRows) {
			output.setContextualRows(rows, workRows);
		} else {
			output.setRows(rows, workRows);
		}
		runtime.describePackedAccessPath(lookupMask(query, relationId, context), accessRows, invocations, output);
	}

	private double finiteLookupRows(PackedQueryView query, int relationId, PackedCostContext context) {
		for (int prefixOrdinal = 0; prefixOrdinal < context.prefixRelationCount(); prefixOrdinal++) {
			int assignmentId = context.prefixRelationId(prefixOrdinal);
			if (!query.isBindingSetAssignment(assignmentId)
					|| !bindsStatementComponent(query, assignmentId, relationId)) {
				continue;
			}
			double rows = 0.0d;
			for (int rowOrdinal = 0; rowOrdinal < query.bindingAssignmentRowCount(assignmentId); rowOrdinal++) {
				Value subject = contextualValue(query, assignmentId, rowOrdinal, relationId, 0);
				Value predicate = contextualValue(query, assignmentId, rowOrdinal, relationId, 1);
				Value object = contextualValue(query, assignmentId, rowOrdinal, relationId, 2);
				Value graph = contextualValue(query, assignmentId, rowOrdinal, relationId, 3);
				if (subject != null && !(subject instanceof Resource)
						|| predicate != null && !(predicate instanceof IRI)
						|| graph != null && !(graph instanceof Resource)) {
					continue;
				}
				double estimate = runtime.packedStatementPatternRows((Resource) subject, (IRI) predicate, object,
						(Resource) graph, repeatedComponentPairMask(query, relationId));
				if (!Double.isFinite(estimate) || estimate < 0.0d) {
					return Double.NaN;
				}
				rows = saturatedAdd(rows, estimate);
			}
			return rows;
		}
		return Double.NaN;
	}

	private static boolean bindsStatementComponent(PackedQueryView query, int assignmentId, int relationId) {
		if (query.bindingAssignmentRowCount(assignmentId) == 0) {
			return false;
		}
		for (int component = 0; component < 4; component++) {
			if (query.statementPatternValue(relationId, component) == null
					&& query.bindingAssignmentValue(assignmentId, 0,
							query.statementPatternName(relationId, component)) != null) {
				return true;
			}
		}
		return false;
	}

	private static Value contextualValue(PackedQueryView query, int assignmentId, int rowOrdinal, int relationId,
			int component) {
		Value constant = query.statementPatternValue(relationId, component);
		return constant != null
				? constant
				: query.bindingAssignmentValue(assignmentId, rowOrdinal,
						query.statementPatternName(relationId, component));
	}

	private static int lookupMask(PackedQueryView query, int relationId, PackedCostContext context) {
		int result = 0;
		for (int component = 0; component < 4; component++) {
			if (query.statementPatternValue(relationId, component) != null
					|| query.prefixBindsStatementComponent(context, relationId, component)) {
				result |= 1 << component;
			}
		}
		return result;
	}

	private static double invocationCount(PackedQueryView query, PackedCostContext context) {
		double finiteRows = 1.0d;
		boolean finite = false;
		for (int ordinal = 0; ordinal < context.prefixRelationCount(); ordinal++) {
			int relationId = context.prefixRelationId(ordinal);
			if (!query.isBindingSetAssignment(relationId)) {
				continue;
			}
			finite = true;
			finiteRows = saturatedMultiply(finiteRows, query.bindingAssignmentRowCount(relationId));
		}
		return finite ? finiteRows : Math.max(1.0d, context.prefixRows());
	}

	private static double saturatedMultiply(double left, double right) {
		double result = left * right;
		return Double.isFinite(result) ? result : Double.MAX_VALUE;
	}

	private static double saturatedAdd(double left, double right) {
		return left >= Double.MAX_VALUE - right ? Double.MAX_VALUE : left + right;
	}

	private static int repeatedComponentPairMask(PackedQueryView query, int relationId) {
		int mask = 0;
		for (int left = 0; left < 4; left++) {
			String leftName = repeatedName(query, relationId, left);
			if (leftName == null) {
				continue;
			}
			for (int right = left + 1; right < 4; right++) {
				if (leftName.equals(repeatedName(query, relationId, right))) {
					mask |= TripleStore.repeatedComponentPairMask(left, right);
				}
			}
		}
		return mask;
	}

	private static String repeatedName(PackedQueryView query, int relationId, int component) {
		String name = query.statementPatternName(relationId, component);
		if (name == null || name.isBlank()) {
			return null;
		}
		return query.statementPatternValue(relationId, component) != null
				&& query.statementPatternTermAnonymous(relationId, component)
						? null
						: name;
	}
}
