/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import org.eclipse.rdf4j.common.annotation.Experimental;

@Experimental
public final class LmdbLftjMetrics {

	private long candidateScans;
	private long witnessScans;
	private long emittedBindings;
	private long frontierLoads;
	private long frontierHits;
	private long countLoads;
	private long countHits;
	private long relationLoads;
	private long relationHits;
	private long relationUses;

	public void recordCandidateScan() {
		candidateScans++;
	}

	public void recordWitnessScan() {
		witnessScans++;
	}

	public void recordEmitted(long count) {
		emittedBindings += count;
	}

	public void recordFrontierLoad() {
		frontierLoads++;
	}

	public void recordFrontierHit() {
		frontierHits++;
	}

	public void recordCountLoad() {
		countLoads++;
	}

	public void recordCountHit() {
		countHits++;
	}

	public void recordRelationLoad() {
		relationLoads++;
	}

	public void recordRelationHit() {
		relationHits++;
	}

	public void recordRelationUse() {
		relationUses++;
	}

	long candidateScans() {
		return candidateScans;
	}

	long witnessScans() {
		return witnessScans;
	}

	long emittedBindings() {
		return emittedBindings;
	}

	long frontierLoads() {
		return frontierLoads;
	}

	long frontierHits() {
		return frontierHits;
	}

	long countLoads() {
		return countLoads;
	}

	long countHits() {
		return countHits;
	}

	long relationLoads() {
		return relationLoads;
	}

	long relationHits() {
		return relationHits;
	}

	long relationUses() {
		return relationUses;
	}
}
