/*******************************************************************************
 * Copyright (c) 2021 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.FilterSelectivityKeys;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.PatternKey;
import org.eclipse.rdf4j.sail.base.SketchBasedJoinEstimator;
import org.eclipse.rdf4j.sail.base.SketchBasedJoinEstimator.Component;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 */
class LmdbEvaluationStatistics extends EvaluationStatistics implements JoinOrderPlanner {

	private static final Logger log = LoggerFactory.getLogger(LmdbEvaluationStatistics.class);
	private static final int SHARED_CACHE_MAX_ENTRIES = 262_144;
	private static final long JOIN_SUPPORT_CACHE_TTL_MS = 100;
	private static final Map<SharedCardinalityKey, Double> sharedCardinalityCache = new ConcurrentHashMap<>();

	private final ValueStore valueStore;

	private final TripleStore tripleStore;
	private final int tripleStoreIdentity;
	private final Map<CardinalityKey, Double> cardinalityCache = new ConcurrentHashMap<>();
	private final SketchBasedJoinEstimator sketchBasedJoinEstimator;
	private final LmdbFilterSelectivityStats filterSelectivityStats;
	private final SketchBasedJoinEstimator.JoinOrderWorkAdjuster joinOrderWorkAdjuster;
	private volatile long joinSupportCacheExpiryMs = Long.MIN_VALUE;
	private volatile long joinSupportCacheRevisionId = Long.MIN_VALUE;
	private volatile boolean joinSupportCacheValue = false;

	public LmdbEvaluationStatistics(ValueStore valueStore, TripleStore tripleStore,
			SketchBasedJoinEstimator sketchBasedJoinEstimator) {
		this(valueStore, tripleStore, sketchBasedJoinEstimator, null);
	}

	public LmdbEvaluationStatistics(ValueStore valueStore, TripleStore tripleStore,
			SketchBasedJoinEstimator sketchBasedJoinEstimator, LmdbFilterSelectivityStats filterSelectivityStats) {
		this.valueStore = valueStore;
		this.tripleStore = tripleStore;
		this.tripleStoreIdentity = System.identityHashCode(tripleStore);
		this.sketchBasedJoinEstimator = sketchBasedJoinEstimator;
		this.filterSelectivityStats = filterSelectivityStats;
		this.joinOrderWorkAdjuster = this::adjustJoinOrderWorkRows;
	}

	@Override
	public boolean supportsJoinEstimation() {
		long now = System.currentTimeMillis();
		long revisionId = valueStore.getRevision().getRevisionId();
		if (now < joinSupportCacheExpiryMs && revisionId == joinSupportCacheRevisionId) {
			return joinSupportCacheValue;
		}

		boolean ready = sketchBasedJoinEstimator.isReady();
//		boolean ready = ensureRobustJoinEstimationReady();
		joinSupportCacheValue = ready;
		joinSupportCacheRevisionId = revisionId;
		joinSupportCacheExpiryMs = now + JOIN_SUPPORT_CACHE_TTL_MS;
		return ready;
	}

	@Override
	public boolean supportsFilterSelectivityCosting() {
		return true;
	}

	@Override
	public Optional<JoinOrderPlan> planJoinOrder(List<TupleExpr> args, Set<String> initiallyBoundVars,
			Algorithm algorithm) {
		if (!supportsJoinEstimation()) {
			return Optional.empty();
		}
		return sketchBasedJoinEstimator.planJoinOrder(args, initiallyBoundVars, algorithm, joinOrderWorkAdjuster);
	}

	private double adjustJoinOrderWorkRows(SketchBasedJoinEstimator.AccessShape accessShape, double defaultWorkRows) {
		if (accessShape == null) {
			return defaultWorkRows;
		}

		TripleStore.IndexPrefixSelection prefixSelection = tripleStore
				.selectBestIndexPrefix(accessShape.lookupBoundComponents());
		if (prefixSelection == null) {
			return defaultWorkRows;
		}

		double accessRows = accessShape.estimateAccessRows(prefixSelection.prefixComponents());
		if (!Double.isFinite(accessRows) || accessRows <= 0.0d) {
			return defaultWorkRows;
		}

		double adjustedWorkRows = accessRows;
		Set<Component> filterLookupComponents = accessShape.filterLookupComponents();
		if (!filterLookupComponents.isEmpty()
				&& accessShape.isDirectLookup(prefixSelection.prefixComponents())) {
			double filteredAccessRows = accessRows * accessShape.filterMultiplier();
			if (Double.isFinite(filteredAccessRows) && filteredAccessRows > 0.0d) {
				adjustedWorkRows = filteredAccessRows;
			}
		}

		return adjustedWorkRows;
	}

	public boolean isJoinEstimationReady() {
		return supportsJoinEstimation();
	}

	public Object joinEstimationDiagnostics() {
		SketchBasedJoinEstimator.Staleness staleness = sketchBasedJoinEstimator.staleness();
		Map<String, Object> diagnostics = new LinkedHashMap<>();
		diagnostics.put("estimator", "SketchBasedJoinEstimator");
		diagnostics.put("stalenessScore", staleness.stalenessScore);
		diagnostics.put("ageMillis", staleness.ageMillis);
		diagnostics.put("sampledAdds", staleness.sampledAdds);
		diagnostics.put("sampledRemoved", staleness.sampledRemoved);
		diagnostics.put("sampledReadded", staleness.sampledReadded);
		diagnostics.put("sampledRemovalRatio", staleness.sampledRemovalRatio);
		diagnostics.put("sampledReaddRatio", staleness.sampledReaddRatio);
		return diagnostics;
	}

	@Override
	protected CardinalityCalculator createCardinalityCalculator() {
		return new LmdbCardinalityCalculator();
	}

	@Override
	public double estimateFilterPassRatio(Filter filter) {
		double ratio = sketchBasedJoinEstimator.estimateFilterPassRatio(filter);
		return Double.isFinite(ratio) && ratio > 0.0d && ratio <= 1.0d ? ratio : -1.0d;
	}

	@Override
	public void recordFilterOutcome(Filter filter, long passedCount, long filteredCount) {
		if (filterSelectivityStats == null || filter == null || filter.getCondition() == null
				|| (passedCount <= 0L && filteredCount <= 0L)) {
			return;
		}

		StatementPattern pattern = basePatternForFilter(filter);
		if (pattern == null) {
			return;
		}
		PatternKey patternKey = FilterSelectivityKeys.patternKeyFor(pattern);
		if (patternKey == null) {
			return;
		}
		filterSelectivityStats.recordFilterOutcome(patternKey,
				FilterSelectivityKeys.filterKeyFor(filter.getCondition()),
				passedCount, filteredCount);
	}

	private StatementPattern basePatternForFilter(Filter filter) {
		return FilterSelectivityKeys.patternLocalBaseForFilter(filter);
	}

	protected class LmdbCardinalityCalculator extends CardinalityCalculator {

		@Override
		public void meet(Join node) {
			if (supportsJoinEstimation()) {
				double estimatedCardinality = sketchBasedJoinEstimator.cardinality(node);
				if (estimatedCardinality >= 0) {
					this.cardinality = estimatedCardinality;
					return;
				}
			}

			super.meet(node);
		}

		@Override
		public void meet(LeftJoin node) {
			if (supportsJoinEstimation()) {
				double estimatedCardinality = sketchBasedJoinEstimator.cardinality(node);
				if (estimatedCardinality >= 0) {
					this.cardinality = estimatedCardinality;
					return;
				}
			}

			super.meet(node);
		}

		@Override
		public void meet(Filter node) {
			if (supportsJoinEstimation()) {
				double estimatedCardinality = sketchBasedJoinEstimator.cardinality(node);
				if (estimatedCardinality >= 0) {
					this.cardinality = estimatedCardinality;
					return;
				}
			}

			node.getArg().visit(this);
			double inputRows = this.cardinality;

			double passRatio = LmdbEvaluationStatistics.this.estimateFilterPassRatio(node);
			if (Double.isFinite(passRatio) && passRatio > 0.0d && passRatio <= 1.0d
					&& Double.isFinite(inputRows) && inputRows >= 0.0d) {
				double filteredRows = inputRows * passRatio;
				if (Double.isFinite(filteredRows) && filteredRows >= 0.0d) {
					this.cardinality = filteredRows;
					return;
				}
			}

			this.cardinality = inputRows;
		}

		@Override
		protected double getCardinality(StatementPattern sp) {
			try {
				Value subj = getConstantValue(sp.getSubjectVar());
				if (!(subj instanceof Resource)) {
					// can happen when a previous optimizer has inlined a comparison operator.
					// this can cause, for example, the subject variable to be equated to a literal value.
					// See SES-970
					subj = null;
				}
				Value pred = getConstantValue(sp.getPredicateVar());
				if (!(pred instanceof IRI)) {
					// can happen when a previous optimizer has inlined a comparison operator. See SES-970
					pred = null;
				}
				Value obj = getConstantValue(sp.getObjectVar());
				Value context = getConstantValue(sp.getContextVar());
				if (!(context instanceof Resource)) {
					// can happen when a previous optimizer has inlined a comparison operator. See SES-970
					context = null;
				}
				return cardinality((Resource) subj, (IRI) pred, obj, (Resource) context);
			} catch (IOException e) {
				log.error("Failed to estimate statement pattern cardinality, falling back to generic implementation",
						e);
				return super.getCardinality(sp);
			}
		}

		protected Value getConstantValue(Var var) {
			return (var != null) ? var.getValue() : null;
		}
	}

	private double cardinality(Resource subj, IRI pred, Value obj, Resource context) throws IOException {
		long subjID = LmdbValue.UNKNOWN_ID;
		if (subj != null) {
			subjID = valueStore.getId(subj);
			if (subjID == LmdbValue.UNKNOWN_ID) {
				return 0;
			}
		}

		long predID = LmdbValue.UNKNOWN_ID;
		if (pred != null) {
			predID = valueStore.getId(pred);
			if (predID == LmdbValue.UNKNOWN_ID) {
				return 0;
			}
		}

		long objID = LmdbValue.UNKNOWN_ID;
		if (obj != null) {
			objID = valueStore.getId(obj);
			if (objID == LmdbValue.UNKNOWN_ID) {
				return 0;
			}
		}

		long contextID = LmdbValue.UNKNOWN_ID;
		if (context != null) {
			contextID = valueStore.getId(context);
			if (contextID == LmdbValue.UNKNOWN_ID) {
				return 0;
			}
		}

		CardinalityKey key = new CardinalityKey(subjID, predID, objID, contextID);
		Double cached = cardinalityCache.get(key);
		if (cached != null) {
			return cached;
		}

		long dataRevision = tripleStore.getDataRevision();
		SharedCardinalityKey sharedKey = new SharedCardinalityKey(tripleStoreIdentity, dataRevision, key);
		Double sharedCached = sharedCardinalityCache.get(sharedKey);
		if (sharedCached != null) {
			cardinalityCache.put(key, sharedCached);
			return sharedCached;
		}

		double cardinality = tripleStore.cardinality(subjID, predID, objID, contextID);
		cardinalityCache.put(key, cardinality);
		cacheSharedCardinality(sharedKey, cardinality);
		return cardinality;
	}

	private static void cacheSharedCardinality(SharedCardinalityKey key, double cardinality) {
		if (sharedCardinalityCache.size() >= SHARED_CACHE_MAX_ENTRIES) {
			sharedCardinalityCache.clear();
		}
		sharedCardinalityCache.put(key, cardinality);
	}

	private static final class CardinalityKey {
		private final long subjID;
		private final long predID;
		private final long objID;
		private final long contextID;

		private CardinalityKey(long subjID, long predID, long objID, long contextID) {
			this.subjID = subjID;
			this.predID = predID;
			this.objID = objID;
			this.contextID = contextID;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj) {
				return true;
			}
			if (!(obj instanceof CardinalityKey)) {
				return false;
			}
			CardinalityKey other = (CardinalityKey) obj;
			return subjID == other.subjID
					&& predID == other.predID
					&& objID == other.objID
					&& contextID == other.contextID;
		}

		@Override
		public int hashCode() {
			int result = Long.hashCode(subjID);
			result = 31 * result + Long.hashCode(predID);
			result = 31 * result + Long.hashCode(objID);
			result = 31 * result + Long.hashCode(contextID);
			return result;
		}
	}

	private static final class SharedCardinalityKey {
		private final int tripleStoreIdentity;
		private final long dataRevision;
		private final long subjID;
		private final long predID;
		private final long objID;
		private final long contextID;
		private final int hashCode;

		private SharedCardinalityKey(int tripleStoreIdentity, long dataRevision, CardinalityKey cardinalityKey) {
			this.tripleStoreIdentity = tripleStoreIdentity;
			this.dataRevision = dataRevision;
			this.subjID = cardinalityKey.subjID;
			this.predID = cardinalityKey.predID;
			this.objID = cardinalityKey.objID;
			this.contextID = cardinalityKey.contextID;
			int hash = Integer.hashCode(tripleStoreIdentity);
			hash = 31 * hash + Long.hashCode(dataRevision);
			hash = 31 * hash + Long.hashCode(subjID);
			hash = 31 * hash + Long.hashCode(predID);
			hash = 31 * hash + Long.hashCode(objID);
			hash = 31 * hash + Long.hashCode(contextID);
			this.hashCode = hash;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj) {
				return true;
			}
			if (!(obj instanceof SharedCardinalityKey)) {
				return false;
			}
			SharedCardinalityKey other = (SharedCardinalityKey) obj;
			return tripleStoreIdentity == other.tripleStoreIdentity
					&& dataRevision == other.dataRevision
					&& subjID == other.subjID
					&& predID == other.predID
					&& objID == other.objID
					&& contextID == other.contextID;
		}

		@Override
		public int hashCode() {
			return hashCode;
		}
	}
}
