/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.rdf4j.sail.lmdb.TxnManager.Txn;

/**
 * Thread-confined LMDB scanners pinned to one exact data revision. The first four retain plane-scanner compatibility;
 * additional scanners are owned by predicate-range workers. The complete transaction family is created under one
 * TxnManager read lock and then cross-checked before any scan, so neither a commit nor a map resize can split the
 * authoritative LMDB image between sibling scanners.
 */
final class LmdbAdjacencyBuildTxnFamily implements AdjacencySourceFamily {

	private static final int STREAM_COUNT = LmdbAdjacencyPlane.PLANE_COUNT;

	private final Txn[] transactions;
	private final LmdbAdjacencyTripleStoreScanner[] scanners;
	private final boolean[] activePlanes = new boolean[STREAM_COUNT];
	private final AtomicBoolean closed = new AtomicBoolean();

	private final long snapshotRevision;
	private final int activeStreamCount;

	LmdbAdjacencyBuildTxnFamily(TripleStore tripleStore) throws IOException {
		this(tripleStore, STREAM_COUNT);
	}

	LmdbAdjacencyBuildTxnFamily(TripleStore tripleStore, int requestedWorkerScanners) throws IOException {
		if (requestedWorkerScanners <= 0) {
			throw new IllegalArgumentException("requested worker scanner count must be positive: "
					+ requestedWorkerScanners);
		}
		TxnManager txnManager = tripleStore.getTxnManager();
		int availableReaders = txnManager.availableReadTxnSlots(TripleStore.MAX_READERS, 1);
		int scannerCount = Math.min(requestedWorkerScanners, availableReaders);
		if (scannerCount == 0) {
			throw new IOException("insufficient LMDB reader slots for adjacency build while preserving one foreground "
					+ "reader");
		}
		transactions = txnManager.createReadTxnPinnedFamily(scannerCount, tripleStore::getDataRevision);
		scanners = new LmdbAdjacencyTripleStoreScanner[scannerCount];
		long revision = transactions[0].snapshotRevision();
		try {
			for (int worker = 0; worker < scannerCount; worker++) {
				Txn txn = transactions[worker];
				if (txn.snapshotRevision() != revision) {
					throw new IOException("sibling adjacency transactions crossed a commit: expected revision "
							+ revision + " but worker " + worker + " pinned " + txn.snapshotRevision());
				}
				scanners[worker] = new LmdbAdjacencyTripleStoreScanner(tripleStore, txn, revision, true);
			}
			long snapshotId = scanners[0].snapshotId();
			for (int worker = 1; worker < scannerCount; worker++) {
				if (scanners[worker].snapshotId() != snapshotId) {
					throw new IOException("sibling adjacency transactions have different LMDB snapshot IDs: worker 0="
							+ snapshotId + ", worker " + worker + "=" + scanners[worker].snapshotId());
				}
			}
			activePlanes[LmdbAdjacencyPlane.PLANE_OUTGOING_EXPLICIT] = tripleStore.hasTriples(transactions[0],
					-1, -1, -1, -1, true);
			activePlanes[LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT] = activePlanes[LmdbAdjacencyPlane.PLANE_OUTGOING_EXPLICIT];
			activePlanes[LmdbAdjacencyPlane.PLANE_OUTGOING_INFERRED] = tripleStore.hasTriples(transactions[0],
					-1, -1, -1, -1, false);
			activePlanes[LmdbAdjacencyPlane.PLANE_INCOMING_INFERRED] = activePlanes[LmdbAdjacencyPlane.PLANE_OUTGOING_INFERRED];
			int streams = 0;
			for (boolean activePlane : activePlanes) {
				if (activePlane) {
					streams++;
				}
			}
			activeStreamCount = streams;
		} catch (IOException | RuntimeException | Error e) {
			for (int i = transactions.length - 1; i >= 0; i--) {
				transactions[i].close();
			}
			throw e;
		}
		snapshotRevision = revision;
	}

	@Override
	public AdjacencySourceScanner primary() {
		return scanners[0];
	}

	@Override
	public AdjacencySourceScanner scanner(int plane) {
		if (plane < 0 || plane >= STREAM_COUNT) {
			throw new IllegalArgumentException("plane out of range: " + plane);
		}
		return scanners[plane % scanners.length];
	}

	@Override
	public int workerScannerCount() {
		return scanners.length;
	}

	@Override
	public AdjacencySourceScanner workerScanner(int worker) {
		if (worker < 0 || worker >= scanners.length) {
			throw new IllegalArgumentException("worker out of range: " + worker);
		}
		return scanners[worker];
	}

	@Override
	public boolean isPlaneActive(int plane) {
		if (plane < 0 || plane >= STREAM_COUNT) {
			throw new IllegalArgumentException("plane out of range: " + plane);
		}
		return activePlanes[plane];
	}

	@Override
	public AdjacencySourceScanner.Telemetry telemetry() {
		AdjacencySourceScanner.Telemetry total = AdjacencySourceScanner.Telemetry.EMPTY;
		for (LmdbAdjacencyTripleStoreScanner scanner : scanners) {
			total = total.plus(scanner.telemetry());
		}
		return total;
	}

	@Override
	public int activeStreamCount() {
		return activeStreamCount;
	}

	@Override
	public long snapshotRevision() {
		return snapshotRevision;
	}

	@Override
	public void cancel() {
		close();
	}

	@Override
	public void close() {
		if (!closed.compareAndSet(false, true)) {
			return;
		}
		for (int worker = transactions.length - 1; worker >= 0; worker--) {
			transactions[worker].close();
		}
	}
}
