/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.math.BigInteger;
import java.util.EnumMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicLongArray;
import java.util.concurrent.atomic.LongAdder;

/**
 * Mutable direct-adjacency counters and their immutable {@link Snapshot} (plan 27). Fallback reasons are the closed
 * enum from the plan; do not log per lookup — counters are read through {@link LmdbDirectAdjacencyStore}'s metrics
 * accessor.
 */
final class LmdbAdjacencyMetrics {

	/**
	 * Closed set of reasons a lookup used LMDB instead of the direct index.
	 */
	enum FallbackReason {
		DISABLED,
		BUILDING,
		SNAPSHOT_BEFORE_BASE,
		REVISION_GAP,
		PENDING_ROW,
		PLANE_NOT_COVERED,
		INLINE_NOT_COVERED,
		PREDICATE_ENUMERATION_INCOMPLETE,
		SERIALIZABLE,
		READ_YOUR_WRITES,
		MAP_RESIZE_INVALIDATED,
		MEMORY_REFUSED,
		INDEX_ORDER_INCOMPATIBLE,
		KERNEL_REQUIRES_COMPLETE_REVISION,
		ROOT_SCAN,
		DOUBLY_BOUND,
		STATE_CHURN
	}

	private static final FallbackReason[] REASONS = FallbackReason.values();

	private final LongAdder lookupHits = new LongAdder();
	private final LongAdder plannerStatsHits = new LongAdder();
	private final LongAdder exactMisses = new LongAdder();
	private final AtomicLongArray fallbacks = new AtomicLongArray(REASONS.length);
	private final LongAdder buildsStarted = new LongAdder();
	private final LongAdder buildsCompleted = new LongAdder();
	private final LongAdder buildsAborted = new LongAdder();
	private final LongAdder shadowComparisons = new LongAdder();
	private final LongAdder shadowMismatches = new LongAdder();
	private final AtomicLong activeBuildThreads = new AtomicLong();
	private final AtomicLong lastBuildThreads = new AtomicLong();
	private final AtomicLong pass1SourceVisits = new AtomicLong();
	private final AtomicLong pass1Nanos = new AtomicLong();
	private final AtomicLong pass3SourceVisits = new AtomicLong();
	private final AtomicLong pass3Nanos = new AtomicLong();
	private final AtomicLong buildElapsedNanos = new AtomicLong();
	private final AtomicLong projectedBuildNanos = new AtomicLong(Long.MAX_VALUE);

	private static final long TARGET_20B_SOURCE_VISITS = sourceVisitsForStatements(20_000_000_000L);
	private static final BigInteger LONG_MAX = BigInteger.valueOf(Long.MAX_VALUE);

	void recordHit() {
		lookupHits.increment();
	}

	void recordPlannerStatsHit() {
		plannerStatsHits.increment();
	}

	void recordExactMiss() {
		exactMisses.increment();
	}

	void recordFallback(FallbackReason reason) {
		fallbacks.incrementAndGet(reason.ordinal());
	}

	void recordBuildStarted() {
		buildsStarted.increment();
	}

	void recordBuildCompleted() {
		buildsCompleted.increment();
	}

	void recordBuildAborted() {
		buildsAborted.increment();
	}

	void beginParallelBuild(int threads) {
		if (threads < 1 || threads > LmdbReferenceNodeLocator.PLANE_COUNT) {
			throw new IllegalArgumentException("build thread count must be between 1 and 4: " + threads);
		}
		pass1SourceVisits.set(0);
		pass1Nanos.set(0);
		pass3SourceVisits.set(0);
		pass3Nanos.set(0);
		buildElapsedNanos.set(0);
		projectedBuildNanos.set(Long.MAX_VALUE);
		lastBuildThreads.set(threads);
		activeBuildThreads.set(threads);
	}

	void recordPass1(long sourceVisits, long nanos) {
		requireNonNegative("Pass 1 source visits", sourceVisits);
		requireNonNegative("Pass 1 nanos", nanos);
		pass1SourceVisits.set(sourceVisits);
		pass1Nanos.set(nanos);
	}

	void recordPass3(long sourceVisits, long nanos) {
		requireNonNegative("Pass 3 source visits", sourceVisits);
		requireNonNegative("Pass 3 nanos", nanos);
		pass3SourceVisits.set(sourceVisits);
		pass3Nanos.set(nanos);
	}

	void finishParallelBuild(long elapsedNanos) {
		requireNonNegative("build elapsed nanos", elapsedNanos);
		buildElapsedNanos.set(elapsedNanos);
		long observedVisits = Math.addExact(pass1SourceVisits.get(), pass3SourceVisits.get());
		projectedBuildNanos.set(projectedBuildNanos(observedVisits, elapsedNanos, TARGET_20B_SOURCE_VISITS));
		activeBuildThreads.set(0);
	}

	void abortParallelBuild() {
		activeBuildThreads.set(0);
	}

	void recordShadowComparison() {
		shadowComparisons.increment();
	}

	void recordShadowMismatch() {
		shadowMismatches.increment();
	}

	Snapshot snapshot(String state, long baseRevision, long appliedRevision, long currentDataRevision,
			long gapFromRevision, long emergencyGapFromRevision, long activeViews, long baseBytes,
			long buildCounterBytes, long buildOutputBytes, long javaMetadataBytes, long totalChargedBytes,
			long highWaterBytes, long configuredMaxBytes, long detectedMemoryLimitBytes, long effectiveMaxBytes) {
		EnumMap<FallbackReason, Long> byReason = new EnumMap<>(FallbackReason.class);
		for (FallbackReason reason : REASONS) {
			long count = fallbacks.get(reason.ordinal());
			if (count > 0) {
				byReason.put(reason, count);
			}
		}
		return new Snapshot(state, baseRevision, appliedRevision, currentDataRevision, gapFromRevision,
				emergencyGapFromRevision, activeViews, baseBytes, buildCounterBytes, buildOutputBytes,
				javaMetadataBytes,
				totalChargedBytes, highWaterBytes, configuredMaxBytes, detectedMemoryLimitBytes, effectiveMaxBytes,
				lookupHits.sum(), plannerStatsHits.sum(), exactMisses.sum(), Map.copyOf(byReason), buildsStarted.sum(),
				buildsCompleted.sum(),
				buildsAborted.sum(),
				shadowComparisons.sum(), shadowMismatches.sum(), activeBuildThreads.get(), lastBuildThreads.get(),
				pass1SourceVisits.get(), pass1Nanos.get(), pass3SourceVisits.get(), pass3Nanos.get(),
				buildElapsedNanos.get(), projectedBuildNanos.get());
	}

	static long sourceVisitsForStatements(long statementCount) {
		requireNonNegative("statement count", statementCount);
		return Math.multiplyExact(statementCount, 4);
	}

	static long projectedBuildNanos(long observedSourceVisits, long elapsedNanos, long targetSourceVisits) {
		requireNonNegative("observed source visits", observedSourceVisits);
		requireNonNegative("elapsed nanos", elapsedNanos);
		requireNonNegative("target source visits", targetSourceVisits);
		if (targetSourceVisits == 0 || elapsedNanos == 0) {
			return 0;
		}
		if (observedSourceVisits == 0) {
			return Long.MAX_VALUE;
		}
		BigInteger numerator = BigInteger.valueOf(targetSourceVisits).multiply(BigInteger.valueOf(elapsedNanos));
		BigInteger[] quotientAndRemainder = numerator.divideAndRemainder(BigInteger.valueOf(observedSourceVisits));
		BigInteger projected = quotientAndRemainder[1].signum() == 0
				? quotientAndRemainder[0]
				: quotientAndRemainder[0].add(BigInteger.ONE);
		return projected.compareTo(LONG_MAX) > 0 ? Long.MAX_VALUE : projected.longValueExact();
	}

	private static void requireNonNegative(String label, long value) {
		if (value < 0) {
			throw new IllegalArgumentException(label + " must not be negative: " + value);
		}
	}

	/**
	 * One immutable point-in-time metrics view.
	 */
	static final class Snapshot {
		final String state;
		final long baseRevision;
		final long appliedRevision;
		final long currentDataRevision;
		final long gapFromRevision;
		final long emergencyGapFromRevision;
		final long activeViews;
		final long baseBytes;
		final long buildCounterBytes;
		final long buildOutputBytes;
		final long javaMetadataBytes;
		final long totalChargedBytes;
		final long highWaterBytes;
		final long configuredMaxBytes;
		final long detectedMemoryLimitBytes;
		final long effectiveMaxBytes;
		final long lookupHits;
		final long plannerStatsHits;
		final long exactMisses;
		final Map<FallbackReason, Long> fallbacksByReason;
		final long buildsStarted;
		final long buildsCompleted;
		final long buildsAborted;
		final long shadowComparisons;
		final long shadowMismatches;
		final long activeBuildThreads;
		final long lastBuildThreads;
		final long pass1SourceVisits;
		final long pass1Nanos;
		final long pass3SourceVisits;
		final long pass3Nanos;
		final long buildElapsedNanos;
		final long projectedBuildNanos;

		private Snapshot(String state, long baseRevision, long appliedRevision, long currentDataRevision,
				long gapFromRevision, long emergencyGapFromRevision, long activeViews, long baseBytes,
				long buildCounterBytes, long buildOutputBytes, long javaMetadataBytes, long totalChargedBytes,
				long highWaterBytes, long configuredMaxBytes, long detectedMemoryLimitBytes, long effectiveMaxBytes,
				long lookupHits, long plannerStatsHits, long exactMisses, Map<FallbackReason, Long> fallbacksByReason,
				long buildsStarted,
				long buildsCompleted, long buildsAborted, long shadowComparisons, long shadowMismatches,
				long activeBuildThreads, long lastBuildThreads, long pass1SourceVisits, long pass1Nanos,
				long pass3SourceVisits, long pass3Nanos, long buildElapsedNanos, long projectedBuildNanos) {
			this.state = state;
			this.baseRevision = baseRevision;
			this.appliedRevision = appliedRevision;
			this.currentDataRevision = currentDataRevision;
			this.gapFromRevision = gapFromRevision;
			this.emergencyGapFromRevision = emergencyGapFromRevision;
			this.activeViews = activeViews;
			this.baseBytes = baseBytes;
			this.buildCounterBytes = buildCounterBytes;
			this.buildOutputBytes = buildOutputBytes;
			this.javaMetadataBytes = javaMetadataBytes;
			this.totalChargedBytes = totalChargedBytes;
			this.highWaterBytes = highWaterBytes;
			this.configuredMaxBytes = configuredMaxBytes;
			this.detectedMemoryLimitBytes = detectedMemoryLimitBytes;
			this.effectiveMaxBytes = effectiveMaxBytes;
			this.lookupHits = lookupHits;
			this.plannerStatsHits = plannerStatsHits;
			this.exactMisses = exactMisses;
			this.fallbacksByReason = fallbacksByReason;
			this.buildsStarted = buildsStarted;
			this.buildsCompleted = buildsCompleted;
			this.buildsAborted = buildsAborted;
			this.shadowComparisons = shadowComparisons;
			this.shadowMismatches = shadowMismatches;
			this.activeBuildThreads = activeBuildThreads;
			this.lastBuildThreads = lastBuildThreads;
			this.pass1SourceVisits = pass1SourceVisits;
			this.pass1Nanos = pass1Nanos;
			this.pass3SourceVisits = pass3SourceVisits;
			this.pass3Nanos = pass3Nanos;
			this.buildElapsedNanos = buildElapsedNanos;
			this.projectedBuildNanos = projectedBuildNanos;
		}

		long fallbacks(FallbackReason reason) {
			return fallbacksByReason.getOrDefault(reason, 0L);
		}
	}
}
