/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude Code
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.Objects;

import org.eclipse.rdf4j.common.annotation.InternalUseOnly;

/**
 * One partition of a root scan: a raw key subrange of one member source's index. {@code member} is the ordinal of the
 * source inside a composite query source (0 for plain stores); partitions planned by one member of a same-snapshot
 * parallel source family are valid on every sibling because the family shares one snapshot.
 */
@InternalUseOnly
public final class LmdbRootScanPartition {

	private final int member;
	private final LmdbKeyRange range;

	public LmdbRootScanPartition(int member, LmdbKeyRange range) {
		this.member = member;
		this.range = Objects.requireNonNull(range, "range");
	}

	/** Ordinal of the owning source within a composite family; 0 for plain stores. */
	public int member() {
		return member;
	}

	/** Raw index range of this partition. */
	public LmdbKeyRange range() {
		return range;
	}

	/** Returns the same partition payload addressed to another composite-source member. */
	public LmdbRootScanPartition withMember(int newMember) {
		if (newMember == member) {
			return this;
		}
		return new LmdbRootScanPartition(newMember, range);
	}

	@Override
	public String toString() {
		return "LmdbRootScanPartition[member=" + member + ", " + range + "]";
	}
}
