/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.Dataset;
import org.eclipse.rdf4j.query.algebra.And;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.CompareAll;
import org.eclipse.rdf4j.query.algebra.CompareAny;
import org.eclipse.rdf4j.query.algebra.Exists;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.SameTerm;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.VariableScopeChange;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor;
import org.eclipse.rdf4j.query.explanation.TelemetryMetricNames;

final class LmdbFilterSimplifierOptimizer implements QueryOptimizer {

	private final EvaluationStatistics statistics;

	LmdbFilterSimplifierOptimizer(EvaluationStatistics statistics) {
		this.statistics = statistics;
	}

	@Override
	public void optimize(TupleExpr tupleExpr, Dataset dataset, BindingSet bindings) {
		Objects.requireNonNull(tupleExpr, "tupleExpr must not be null");
		optimizeScope(tupleExpr);
	}

	private void optimizeScope(TupleExpr expr) {
		expr.visit(new AbstractQueryModelVisitor<>() {
			final TupleExpr current = expr;

			@Override
			protected void meetNode(QueryModelNode node) {
				if (node != current && node instanceof TupleExpr && node instanceof VariableScopeChange
						&& ((VariableScopeChange) node).isVariableScopeChange()) {
					optimizeScope((TupleExpr) node);
				} else {
					super.meetNode(node);
				}
			}
		});

		expr.visit(new FilterMerger());
	}

	private final class FilterMerger extends AbstractSimpleQueryModelVisitor<RuntimeException> {

		private FilterMerger() {
			super(false);
		}

		@Override
		public void meet(Filter filter) {
			super.meet(filter);
			annotateFilter(filter);
			if (filter.getArg() instanceof Filter && canMerge(filter, (Filter) filter.getArg())) {
				Filter childFilter = (Filter) filter.getArg();
				filter.setCondition(mergeConditions(childFilter.getCondition(), filter.getCondition()));
				filter.setArg(childFilter.getArg());
				annotateFilter(filter);
			}
			rewriteSmallLiteralFilterAnchors(filter);
		}
	}

	private static boolean canMerge(Filter parent, Filter child) {
		return !isVariableScopeChange(parent) && !isVariableScopeChange(child);
	}

	private static boolean isVariableScopeChange(Filter filter) {
		return filter instanceof VariableScopeChange && ((VariableScopeChange) filter).isVariableScopeChange();
	}

	private static And mergeConditions(ValueExpr leftCondition, ValueExpr rightCondition) {
		if (conditionCostClass(leftCondition) <= conditionCostClass(rightCondition)) {
			return new And(leftCondition.clone(), rightCondition.clone());
		}
		return new And(rightCondition.clone(), leftCondition.clone());
	}

	private void rewriteSmallLiteralFilterAnchors(Filter filter) {
		if (isVariableScopeChange(filter)) {
			return;
		}

		TupleExpr arg = filter.getArg();
		List<ValueExpr> conditions = LmdbJoinPlanSupport.splitConjuncts(filter.getCondition());
		Set<String> mandatoryOptionalAnchorBindings = new HashSet<>();
		TupleExpr mandatoryArg = makeUnboundRejectingOptionalsMandatory(arg, conditions,
				mandatoryOptionalAnchorBindings);
		if (mandatoryArg != arg) {
			arg = mandatoryArg;
			filter.setArg(arg);
		}

		Set<String> assuredBindings = arg.getAssuredBindingNames();
		Map<String, LinkedHashSet<Value>> assignmentValues = collectSmallLiteralAssignmentValues(arg);
		List<BindingSetAssignment> anchors = new ArrayList<>();
		List<ValueExpr> remainingConditions = new ArrayList<>();
		for (ValueExpr condition : conditions) {
			BindingSetAssignment valuesVariableAnchor = valuesVariableFilterAnchor(condition, assignmentValues);
			if (valuesVariableAnchor != null
					&& isSelectiveSmallLiteralAnchor(filter, condition)
					&& canMaterializeSmallLiteralFilterAnchor(filter, condition, valuesVariableAnchor,
							assuredBindings)) {
				anchors.add(valuesVariableAnchor);
				remainingConditions.add(condition);
				continue;
			}

			BindingSetAssignment anchor = LmdbJoinPlanSupport.smallLiteralFilterAnchor(condition);
			if (shouldRetainMandatoryOptionalFilter(anchor, mandatoryOptionalAnchorBindings)) {
				remainingConditions.add(condition);
				continue;
			}
			if (anchor != null && canMaterializeSmallLiteralFilterAnchor(filter, condition, anchor, assuredBindings)) {
				if (equivalentSmallLiteralAssignmentExists(anchor, assignmentValues)) {
					remainingConditions.add(condition);
				} else {
					anchors.add(anchor);
					remainingConditions.add(condition);
				}
			} else {
				remainingConditions.add(condition);
			}
		}

		if (anchors.isEmpty()) {
			return;
		}

		TupleExpr anchoredArg = prependAnchors(arg, anchors);
		if (remainingConditions.isEmpty()) {
			filter.replaceWith(anchoredArg);
			return;
		}

		filter.setArg(anchoredArg);
		filter.setCondition(LmdbJoinPlanSupport.combinedCondition(remainingConditions));
		annotateFilter(filter);
	}

	private static TupleExpr makeUnboundRejectingOptionalsMandatory(TupleExpr arg, List<ValueExpr> conditions,
			Set<String> mandatoryOptionalAnchorBindings) {
		TupleExpr current = arg;
		for (ValueExpr condition : conditions) {
			BindingSetAssignment anchor = LmdbJoinPlanSupport.smallLiteralFilterAnchor(condition);
			String bindingName = singleBindingName(anchor);
			if (bindingName == null) {
				continue;
			}
			TupleExpr mandatory = makeOptionalBindingMandatory(current, bindingName, anchor);
			if (mandatory != current) {
				current = mandatory;
				mandatoryOptionalAnchorBindings.add(bindingName);
			}
		}
		return current;
	}

	private static TupleExpr makeOptionalBindingMandatory(TupleExpr arg, String bindingName,
			BindingSetAssignment anchor) {
		if (!(arg instanceof LeftJoin)) {
			return arg;
		}

		LeftJoin leftJoin = (LeftJoin) arg;
		if (leftJoin.hasCondition() || leftJoin.getLeftArg().getBindingNames().contains(bindingName)
				|| !leftJoin.getRightArg().getBindingNames().contains(bindingName)) {
			return arg;
		}
		TupleExpr hoisted = hoistMandatoryRightArgAheadOfScopedFanout(leftJoin.getLeftArg(), anchor,
				leftJoin.getRightArg());
		if (hoisted != null) {
			return hoisted;
		}
		if (finiteLeftBindingsCoverOptionalProbeInput(leftJoin, bindingName)) {
			return arg;
		}
		return new Join(leftJoin.getLeftArg(), new Join(anchor, leftJoin.getRightArg()));
	}

	private static boolean finiteLeftBindingsCoverOptionalProbeInput(LeftJoin leftJoin, String optionalBinding) {
		Set<StatementPattern> optionalPatterns = LmdbJoinPlanSupport.collectPatternIdentities(leftJoin.getRightArg());
		if (optionalPatterns.size() != 1) {
			return false;
		}

		Set<String> requiredInputBindings = unboundPatternBindingNames(optionalPatterns.iterator().next());
		requiredInputBindings.remove(optionalBinding);
		if (requiredInputBindings.isEmpty()) {
			return false;
		}

		return finiteAssignmentBindingNames(leftJoin.getLeftArg()).containsAll(requiredInputBindings);
	}

	private static Set<String> finiteAssignmentBindingNames(TupleExpr tupleExpr) {
		Set<String> bindingNames = new HashSet<>();
		tupleExpr.visit(new AbstractSimpleQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(BindingSetAssignment assignment) {
				bindingNames.addAll(plannerBindingNames(assignment.getAssuredBindingNames()));
			}
		});
		return bindingNames;
	}

	private static Set<String> unboundPatternBindingNames(StatementPattern pattern) {
		Set<String> bindingNames = new HashSet<>();
		addUnboundPatternBindingName(pattern.getSubjectVar(), bindingNames);
		addUnboundPatternBindingName(pattern.getPredicateVar(), bindingNames);
		addUnboundPatternBindingName(pattern.getObjectVar(), bindingNames);
		addUnboundPatternBindingName(pattern.getContextVar(), bindingNames);
		return bindingNames;
	}

	private static void addUnboundPatternBindingName(Var var, Set<String> bindingNames) {
		if (var != null && !var.hasValue() && var.getName() != null && !var.getName().startsWith("_const_")) {
			bindingNames.add(var.getName());
		}
	}

	private static Set<String> plannerBindingNames(Set<String> bindingNames) {
		if (bindingNames == null || bindingNames.isEmpty()) {
			return Set.of();
		}
		Set<String> plannerNames = new HashSet<>();
		for (String bindingName : bindingNames) {
			if (bindingName != null && !bindingName.startsWith("_const_")) {
				plannerNames.add(bindingName);
			}
		}
		return plannerNames;
	}

	private static TupleExpr hoistMandatoryRightArgAheadOfScopedFanout(TupleExpr leftArg, BindingSetAssignment anchor,
			TupleExpr rightArg) {
		if (!(leftArg instanceof Join)) {
			return null;
		}

		Join leftJoin = (Join) leftArg;
		TupleExpr seedArg = leftJoin.getLeftArg();
		TupleExpr fanoutArg = leftJoin.getRightArg();
		if (!(fanoutArg instanceof Union) && (!(fanoutArg instanceof VariableScopeChange)
				|| !((VariableScopeChange) fanoutArg).isVariableScopeChange())) {
			return null;
		}

		Set<String> sharedBindingNames = new HashSet<>(rightArg.getBindingNames());
		sharedBindingNames.addAll(anchor.getBindingNames());
		sharedBindingNames.retainAll(leftArg.getBindingNames());
		if (sharedBindingNames.isEmpty() || !seedArg.getAssuredBindingNames().containsAll(sharedBindingNames)) {
			return null;
		}

		TupleExpr mandatoryRightArg = new Join(anchor, rightArg);
		return new Join(new Join(seedArg, mandatoryRightArg), fanoutArg);
	}

	private static boolean shouldRetainMandatoryOptionalFilter(BindingSetAssignment anchor,
			Set<String> mandatoryOptionalAnchorBindings) {
		String bindingName = singleBindingName(anchor);
		return bindingName != null && mandatoryOptionalAnchorBindings.contains(bindingName);
	}

	private static String singleBindingName(BindingSetAssignment anchor) {
		if (anchor == null || anchor.getBindingNames().size() != 1) {
			return null;
		}
		return anchor.getBindingNames().iterator().next();
	}

	private static boolean equivalentSmallLiteralAssignmentExists(BindingSetAssignment anchor,
			Map<String, LinkedHashSet<Value>> assignmentValues) {
		String bindingName = singleBindingName(anchor);
		if (bindingName == null) {
			return false;
		}
		LinkedHashSet<Value> existingValues = assignmentValues.get(bindingName);
		if (existingValues == null) {
			return false;
		}
		LinkedHashSet<Value> anchorValues = new LinkedHashSet<>();
		for (BindingSet bindingSet : anchor.getBindingSets()) {
			Value value = bindingSet.getValue(bindingName);
			if (value == null) {
				return false;
			}
			anchorValues.add(value);
		}
		return existingValues.equals(anchorValues);
	}

	private static Map<String, LinkedHashSet<Value>> collectSmallLiteralAssignmentValues(TupleExpr tupleExpr) {
		Map<String, LinkedHashSet<Value>> valuesByBinding = new HashMap<>();
		collectSmallLiteralAssignmentValues(tupleExpr, valuesByBinding);
		return valuesByBinding;
	}

	private static void collectSmallLiteralAssignmentValues(TupleExpr tupleExpr,
			Map<String, LinkedHashSet<Value>> valuesByBinding) {
		if (tupleExpr instanceof VariableScopeChange && ((VariableScopeChange) tupleExpr).isVariableScopeChange()) {
			return;
		}
		if (tupleExpr instanceof BindingSetAssignment) {
			collectSmallLiteralAssignmentValues((BindingSetAssignment) tupleExpr, valuesByBinding);
			return;
		}
		if (tupleExpr instanceof Filter) {
			collectSmallLiteralAssignmentValues(((Filter) tupleExpr).getArg(), valuesByBinding);
			return;
		}
		if (tupleExpr instanceof Join) {
			Join join = (Join) tupleExpr;
			collectSmallLiteralAssignmentValues(join.getLeftArg(), valuesByBinding);
			collectSmallLiteralAssignmentValues(join.getRightArg(), valuesByBinding);
			return;
		}
		if (tupleExpr instanceof LeftJoin) {
			collectSmallLiteralAssignmentValues(((LeftJoin) tupleExpr).getLeftArg(), valuesByBinding);
		}
	}

	private static void collectSmallLiteralAssignmentValues(BindingSetAssignment assignment,
			Map<String, LinkedHashSet<Value>> valuesByBinding) {
		if (assignment.getBindingNames().size() != 1) {
			return;
		}
		String bindingName = assignment.getBindingNames().iterator().next();
		LinkedHashSet<Value> values = new LinkedHashSet<>();
		for (BindingSet bindingSet : assignment.getBindingSets()) {
			Value value = bindingSet.getValue(bindingName);
			if (!LmdbJoinPlanSupport.isSafeValuesAnchorValue(value)) {
				return;
			}
			values.add(value);
		}
		if (values.isEmpty()) {
			return;
		}
		valuesByBinding.computeIfAbsent(bindingName, ignored -> new LinkedHashSet<>()).addAll(values);
	}

	private static BindingSetAssignment valuesVariableFilterAnchor(ValueExpr condition,
			Map<String, LinkedHashSet<Value>> assignmentValues) {
		if (assignmentValues.isEmpty()) {
			return null;
		}

		ValuesVariableAnchorCollector collector = new ValuesVariableAnchorCollector(assignmentValues);
		if (!collectValuesVariableAnchor(condition, collector) || collector.bindingName == null
				|| collector.values.isEmpty() || assignmentValues.containsKey(collector.bindingName)) {
			return null;
		}
		return LmdbJoinPlanSupport.smallLiteralFilterAnchor(collector.bindingName, collector.values);
	}

	private static boolean collectValuesVariableAnchor(ValueExpr condition,
			ValuesVariableAnchorCollector collector) {
		if (condition instanceof Or) {
			Or or = (Or) condition;
			return collectValuesVariableAnchor(or.getLeftArg(), collector)
					&& collectValuesVariableAnchor(or.getRightArg(), collector);
		}
		if (condition instanceof Compare && ((Compare) condition).getOperator() == Compare.CompareOp.EQ) {
			Compare compare = (Compare) condition;
			return collectValuesVariableAnchorValue(compare.getLeftArg(), compare.getRightArg(), collector);
		}
		if (condition instanceof SameTerm) {
			SameTerm sameTerm = (SameTerm) condition;
			return collectValuesVariableAnchorValue(sameTerm.getLeftArg(), sameTerm.getRightArg(), collector);
		}
		return false;
	}

	private static boolean collectValuesVariableAnchorValue(ValueExpr leftArg, ValueExpr rightArg,
			ValuesVariableAnchorCollector collector) {
		if (leftArg instanceof Var && rightArg instanceof ValueConstant) {
			return collector.addLiteral((Var) leftArg, ((ValueConstant) rightArg).getValue());
		}
		if (rightArg instanceof Var && leftArg instanceof ValueConstant) {
			return collector.addLiteral((Var) rightArg, ((ValueConstant) leftArg).getValue());
		}
		if (leftArg instanceof Var && rightArg instanceof Var) {
			return collector.addVariableEquality((Var) leftArg, (Var) rightArg);
		}
		return false;
	}

	private boolean canMaterializeSmallLiteralFilterAnchor(Filter filter, ValueExpr condition,
			BindingSetAssignment anchor,
			Set<String> assuredBindings) {
		if (anchor.getBindingNames().size() != 1) {
			return false;
		}
		String bindingName = anchor.getBindingNames().iterator().next();
		return assuredBindings.contains(bindingName)
				&& !LmdbJoinPlanSupport.containsPathContextBinding(filter.getArg(), bindingName)
				&& LmdbJoinPlanSupport.canMaterializeSmallLiteralFilterAnchor(filter, condition, anchor);
	}

	private boolean isSelectiveSmallLiteralAnchor(Filter filter, ValueExpr condition) {
		return LmdbJoinPlanSupport.isSelectiveSmallLiteralFilterAnchor(statistics, filter, condition);
	}

	private static TupleExpr prependAnchors(TupleExpr arg, List<BindingSetAssignment> anchors) {
		TupleExpr anchoredArg = arg;
		for (int i = anchors.size() - 1; i >= 0; i--) {
			anchoredArg = new Join(anchors.get(i), anchoredArg);
		}
		return anchoredArg;
	}

	private static int conditionCostClass(ValueExpr condition) {
		if (condition instanceof And) {
			And and = (And) condition;
			return Math.max(conditionCostClass(and.getLeftArg()), conditionCostClass(and.getRightArg()));
		}
		if (condition instanceof Exists || condition instanceof CompareAny || condition instanceof CompareAll) {
			return 1;
		}
		if (condition instanceof Not && ((Not) condition).getArg() instanceof Exists) {
			return 1;
		}
		return 0;
	}

	private void annotateFilter(Filter filter) {
		if (statistics == null) {
			return;
		}
		double passRatio = filter.getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_FILTER_PASS_RATIO);
		EvaluationStatistics.FilterPassEstimate estimate = isValidPassRatio(passRatio)
				? null
				: statistics.estimateFilterPass(filter);
		if (estimate != null && isValidPassRatio(estimate.getPassRatio())) {
			filter.setDoubleMetricPlanned(TelemetryMetricNames.PLANNED_FILTER_PASS_RATIO, estimate.getPassRatio());
			filter.setStringMetricPlanned(TelemetryMetricNames.FILTER_SELECTIVITY_SOURCE,
					estimate.getSource().name().toLowerCase());
			if (estimate.getEvidenceCount() >= 0L) {
				filter.setLongMetricPlanned(TelemetryMetricNames.PLANNED_FILTER_EVIDENCE_COUNT,
						estimate.getEvidenceCount());
			}
		}
	}

	private static boolean isValidPassRatio(double passRatio) {
		return Double.isFinite(passRatio) && passRatio >= 0.0d && passRatio <= 1.0d;
	}

	private static final class ValuesVariableAnchorCollector {
		private final Map<String, LinkedHashSet<Value>> assignmentValues;
		private final LinkedHashSet<Value> values = new LinkedHashSet<>();
		private String bindingName;

		private ValuesVariableAnchorCollector(Map<String, LinkedHashSet<Value>> assignmentValues) {
			this.assignmentValues = assignmentValues;
		}

		private boolean addLiteral(Var filterVar, Value value) {
			String nextBindingName = unboundName(filterVar);
			if (nextBindingName == null || !LmdbJoinPlanSupport.isSafeValuesAnchorValue(value)) {
				return false;
			}
			if (!setBindingName(nextBindingName)) {
				return false;
			}
			values.add(value);
			return true;
		}

		private boolean addVariableEquality(Var left, Var right) {
			String leftName = unboundName(left);
			String rightName = unboundName(right);
			LinkedHashSet<Value> leftValues = assignmentValues.get(leftName);
			LinkedHashSet<Value> rightValues = assignmentValues.get(rightName);
			if (leftValues != null && rightValues == null) {
				return addValues(rightName, leftValues);
			}
			if (rightValues != null && leftValues == null) {
				return addValues(leftName, rightValues);
			}
			return false;
		}

		private boolean addValues(String nextBindingName, LinkedHashSet<Value> nextValues) {
			if (nextBindingName == null || nextValues == null || nextValues.isEmpty()
					|| !setBindingName(nextBindingName)) {
				return false;
			}
			for (Value value : nextValues) {
				if (!LmdbJoinPlanSupport.isSafeValuesAnchorValue(value)) {
					return false;
				}
			}
			values.addAll(nextValues);
			return true;
		}

		private boolean setBindingName(String nextBindingName) {
			if (bindingName == null) {
				bindingName = nextBindingName;
				return true;
			}
			return bindingName.equals(nextBindingName);
		}

		private static String unboundName(Var var) {
			if (var == null || var.hasValue()) {
				return null;
			}
			return var.getName();
		}
	}
}
