/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.bulk;

/**
 * Durable phases of an LMDB bulk load.
 */
public enum BulkLoadPhase {
	PREFLIGHT,
	STAGE_INPUTS,
	DISTINCT_AND_ANALYZE_VALUES,
	PLAN_VALUE_IDS,
	BUILD_MAPPED_DICTIONARY,
	RESOLVE_IDS,
	BUILD_NATIVE_RUNS,
	WRITE_GENERATION,
	VALIDATE_GENERATION,
	PUBLISH_AND_CLEAN
}
