/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.bulk;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import java.util.function.BooleanSupplier;

import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;

/**
 * Builds a new LMDB store from an RDF stream with bounded working memory.
 */
public final class LmdbBulkLoader {

	static final long MIB = 1024L * 1024L;
	static final int DEFAULT_PARTITION_COUNT = 256;
	static final int DEFAULT_MAX_OPEN_FILES = 1024;
	static final int DEFAULT_WRITE_TRANSACTION_RECORDS = 100_000;
	static final long DEFAULT_WRITE_TRANSACTION_BYTES = 64L * MIB;

	private final Path target;
	private final LmdbStoreConfig config;
	private final ParserMode parserMode;
	private final long memoryBudgetBytes;
	private final int partitionCount;
	private final int maxOpenFiles;
	private final Path temporaryDirectory;
	private final BooleanSupplier cancellationSignal;
	private final int writeTransactionRecords;
	private final long writeTransactionBytes;
	private final LmdbBulkLoadGeneration.PromotionHook publicationHook;

	private LmdbBulkLoader(Builder builder) {
		target = builder.target;
		config = builder.config;
		parserMode = builder.parserMode;
		memoryBudgetBytes = builder.memoryBudgetBytes;
		partitionCount = builder.partitionCount;
		maxOpenFiles = builder.maxOpenFiles;
		temporaryDirectory = builder.temporaryDirectory;
		cancellationSignal = builder.cancellationSignal;
		writeTransactionRecords = builder.writeTransactionRecords;
		writeTransactionBytes = builder.writeTransactionBytes;
		publicationHook = builder.publicationHook;
	}

	/**
	 * Creates a builder for a loader that will publish to {@code target}.
	 *
	 * @param target the absent or empty target directory
	 * @param config LMDB storage configuration
	 * @return a new builder
	 */
	public static Builder builder(Path target, LmdbStoreConfig config) {
		return new Builder(target, config);
	}

	/**
	 * Loads one RDF file. The loader owns and closes the file stream.
	 */
	public Result load(Path input, RDFFormat format) throws IOException {
		Objects.requireNonNull(input, "input");
		try (InputStream stream = Files.newInputStream(input)) {
			return load(stream, input.toUri().toString(), format);
		}
	}

	/**
	 * Loads one caller-owned RDF stream. This method does not close {@code input}.
	 */
	public Result load(InputStream input, String baseUri, RDFFormat format) throws IOException {
		Objects.requireNonNull(input, "input");
		Objects.requireNonNull(baseUri, "baseUri");
		Objects.requireNonNull(format, "format");
		return LmdbBulkLoaderEngine.load(this, input, baseUri, format);
	}

	Path target() {
		return target;
	}

	LmdbStoreConfig config() {
		return config;
	}

	ParserMode parserMode() {
		return parserMode;
	}

	long memoryBudgetBytes() {
		return memoryBudgetBytes;
	}

	int partitionCount() {
		return partitionCount;
	}

	int maxOpenFiles() {
		return maxOpenFiles;
	}

	Path temporaryDirectory() {
		return temporaryDirectory;
	}

	BooleanSupplier cancellationSignal() {
		return cancellationSignal;
	}

	int writeTransactionRecords() {
		return writeTransactionRecords;
	}

	long writeTransactionBytes() {
		return writeTransactionBytes;
	}

	LmdbBulkLoadGeneration.PromotionHook publicationHook() {
		return publicationHook;
	}

	/**
	 * Parser selection for one load.
	 */
	public enum ParserMode {
		AUTO,
		FAST,
		RIO
	}

	/**
	 * Summary of one completed load.
	 */
	public record Result(long parsedStatements, long storedStatements, long persistedValues, long inlineValues,
			long temporaryBytes, long elapsedMillis, long mapGrowthCount) {
	}

	/**
	 * Validates and captures loader resource limits.
	 */
	public static final class Builder {

		private final Path target;
		private final LmdbStoreConfig config;
		private ParserMode parserMode = ParserMode.AUTO;
		private long memoryBudgetBytes = defaultMemoryBudgetBytes();
		private int partitionCount = DEFAULT_PARTITION_COUNT;
		private int maxOpenFiles = DEFAULT_MAX_OPEN_FILES;
		private Path temporaryDirectory;
		private BooleanSupplier cancellationSignal = () -> false;
		private int writeTransactionRecords = DEFAULT_WRITE_TRANSACTION_RECORDS;
		private long writeTransactionBytes = DEFAULT_WRITE_TRANSACTION_BYTES;
		private LmdbBulkLoadGeneration.PromotionHook publicationHook = LmdbBulkLoadGeneration.PromotionHook.NONE;

		private Builder(Path target, LmdbStoreConfig config) {
			this.target = Objects.requireNonNull(target, "target").toAbsolutePath().normalize();
			this.config = Objects.requireNonNull(config, "config");
		}

		public Builder parserMode(ParserMode parserMode) {
			this.parserMode = Objects.requireNonNull(parserMode, "parserMode");
			return this;
		}

		public Builder memoryBudgetBytes(long memoryBudgetBytes) {
			if (memoryBudgetBytes <= 0) {
				throw new IllegalArgumentException("memoryBudgetBytes must be positive");
			}
			this.memoryBudgetBytes = memoryBudgetBytes;
			return this;
		}

		public Builder partitionCount(int partitionCount) {
			if (partitionCount <= 0 || (partitionCount & (partitionCount - 1)) != 0) {
				throw new IllegalArgumentException("partitionCount must be a positive power of two");
			}
			this.partitionCount = partitionCount;
			return this;
		}

		public Builder maxOpenFiles(int maxOpenFiles) {
			if (maxOpenFiles <= 0) {
				throw new IllegalArgumentException("maxOpenFiles must be positive");
			}
			this.maxOpenFiles = maxOpenFiles;
			return this;
		}

		public Builder temporaryDirectory(Path temporaryDirectory) {
			this.temporaryDirectory = Objects.requireNonNull(temporaryDirectory, "temporaryDirectory")
					.toAbsolutePath()
					.normalize();
			return this;
		}

		public Builder cancellationSignal(BooleanSupplier cancellationSignal) {
			this.cancellationSignal = Objects.requireNonNull(cancellationSignal, "cancellationSignal");
			return this;
		}

		public Builder writeTransactionRecords(int writeTransactionRecords) {
			if (writeTransactionRecords <= 0) {
				throw new IllegalArgumentException("writeTransactionRecords must be positive");
			}
			this.writeTransactionRecords = writeTransactionRecords;
			return this;
		}

		public Builder writeTransactionBytes(long writeTransactionBytes) {
			if (writeTransactionBytes <= 0) {
				throw new IllegalArgumentException("writeTransactionBytes must be positive");
			}
			this.writeTransactionBytes = writeTransactionBytes;
			return this;
		}

		Builder publicationHook(LmdbBulkLoadGeneration.PromotionHook publicationHook) {
			this.publicationHook = Objects.requireNonNull(publicationHook, "publicationHook");
			return this;
		}

		public LmdbBulkLoader build() {
			StatementIndexBulkRecords.parseSpecifications(config.getTripleIndexes());
			TripleTermIndexBulkRecords.specifications(config.getTripleTermIndexes());
			return new LmdbBulkLoader(this);
		}
	}

	static long defaultMemoryBudgetBytes() {
		long maxHeap = Runtime.getRuntime().maxMemory();
		long quarterHeap = maxHeap > 0 ? maxHeap / 4L : 256L * MIB;
		return Math.max(32L * MIB, Math.min(1024L * MIB, quarterHeap));
	}
}
