/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.bulk;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.EOFException;
import java.io.IOException;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.ByteOrder;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

final class PartitionValueDictionary {
	static final int ENTRY_READER_BUFFER_BYTES = 64 * 1024;
	private static final long ENTRY_RETAINED_OVERHEAD_BYTES = 16L * 1024L;

	static final int INDEX_MAGIC = 0x4c4d4449;
	static final int INDEX_VERSION = 1;
	static final int INDEX_HEADER_BYTES = 16;
	static final int INDEX_SLOT_BYTES = 16;
	static final ValueLayout.OfInt INT_BIG_ENDIAN = ValueLayout.JAVA_INT_UNALIGNED.withOrder(ByteOrder.BIG_ENDIAN);
	static final ValueLayout.OfLong LONG_BIG_ENDIAN = ValueLayout.JAVA_LONG_UNALIGNED.withOrder(ByteOrder.BIG_ENDIAN);

	private final Path directory;
	private final int partitionCount;
	private final long persistedValues;
	private final long inlineValues;

	PartitionValueDictionary(Path directory, int partitionCount, long persistedValues, long inlineValues) {
		this.directory = directory;
		this.partitionCount = partitionCount;
		this.persistedValues = persistedValues;
		this.inlineValues = inlineValues;
	}

	long persistedValues() {
		return persistedValues;
	}

	long inlineValues() {
		return inlineValues;
	}

	int partitionCount() {
		return partitionCount;
	}

	PartitionReader openPartition(int partition) throws IOException {
		if (partition < 0 || partition >= partitionCount) {
			throw new IllegalArgumentException("Value partition out of range: " + partition);
		}
		return new PartitionReader(dataPath(directory, partition), indexPath(directory, partition));
	}

	PartitionReader openPartition(int partition, BulkTaskScheduler scheduler,
			BulkTaskScheduler.ResourceLease lease) throws IOException {
		if (partition < 0 || partition >= partitionCount) {
			throw new IllegalArgumentException("Value partition out of range: " + partition);
		}
		return new PartitionReader(dataPath(directory, partition), indexPath(directory, partition), scheduler, lease);
	}

	void forEachEntry(EntryConsumer consumer) throws IOException {
		for (int partition = 0; partition < partitionCount; partition++) {
			Path path = dataPath(directory, partition);
			try (DataInputStream input = new DataInputStream(
					new BufferedInputStream(java.nio.file.Files.newInputStream(path), 64 * 1024))) {
				while (true) {
					long routeHash;
					try {
						routeHash = input.readLong();
					} catch (EOFException e) {
						break;
					}
					try {
						long id = input.readLong();
						int roles = input.readInt();
						int keyLength = input.readInt();
						if (keyLength < 0 || keyLength > PartitionReader.MAX_KEY_BYTES) {
							throw new IOException("Invalid partition dictionary key length: " + keyLength);
						}
						byte[] key = new byte[keyLength];
						input.readFully(key);
						consumer.accept(new Entry(partition, routeHash, id, roles, key));
					} catch (EOFException e) {
						throw new IOException("Truncated partition dictionary entry in partition " + partition, e);
					}
				}
			}
		}
	}

	void forEachEntry(EntryConsumer consumer, BulkTaskScheduler scheduler) throws IOException {
		if (scheduler == null) {
			forEachEntry(consumer);
			return;
		}
		BulkTaskScheduler.ResourceLease lease = scheduler.reserveExclusiveCursorBaseBlocking(
				ENTRY_READER_BUFFER_BYTES, 1);
		try (BulkTaskScheduler.FileDescriptorScope ignored = scheduler.bindResourceLease(lease)) {
			forEachEntry(consumer, scheduler, lease);
		} finally {
			lease.close();
		}
	}

	void forEachEntry(EntryConsumer consumer, BulkTaskScheduler scheduler,
			BulkTaskScheduler.ResourceLease lease) throws IOException {
		if (scheduler == null) {
			forEachEntry(consumer);
			return;
		}
		try (BulkTaskScheduler.ResourceScope readerMemory = scheduler.claimCurrentResources(
				ENTRY_READER_BUFFER_BYTES, 0)) {
			for (int partition = 0; partition < partitionCount; partition++) {
				Path path = dataPath(directory, partition);
				try (BulkTaskScheduler.OpenFileHandle ignored = scheduler.trackOpenFileHandle();
						DataInputStream input = new DataInputStream(new BufferedInputStream(Files.newInputStream(path),
								ENTRY_READER_BUFFER_BYTES))) {
					while (true) {
						long routeHash;
						try {
							routeHash = input.readLong();
						} catch (EOFException e) {
							break;
						}
						try {
							long id = input.readLong();
							int roles = input.readInt();
							int keyLength = input.readInt();
							if (keyLength < 0 || keyLength > PartitionReader.MAX_KEY_BYTES) {
								throw new IOException("Invalid partition dictionary key length: " + keyLength);
							}
							long retainedBytes = Math.addExact(Math.multiplyExact((long) keyLength, 4L),
									ENTRY_RETAINED_OVERHEAD_BYTES);
							BulkTaskScheduler.ResourceLease entryLease = scheduler.reserveAdditionalBlocking(lease,
									Math.addExact(lease.memoryBytes(), retainedBytes), lease.fileDescriptors(), true);
							try (BulkTaskScheduler.ResourceScope entryMemory = scheduler.claimResourceLeaseMemory(
									entryLease,
									retainedBytes)) {
								byte[] key = new byte[keyLength];
								input.readFully(key);
								consumer.accept(new Entry(partition, routeHash, id, roles, key));
							} finally {
								entryLease.close();
							}
						} catch (EOFException e) {
							throw new IOException("Truncated partition dictionary entry in partition " + partition, e);
						}
					}
				}
			}
		}
	}

	static Path dataPath(Path directory, int partition) {
		return directory.resolve(String.format(java.util.Locale.ROOT, "dictionary-%05d.bin", partition));
	}

	static Path indexPath(Path directory, int partition) {
		return directory.resolve(String.format(java.util.Locale.ROOT, "dictionary-%05d.idx", partition));
	}

	static final class PartitionReader implements AutoCloseable {

		private static final int DATA_HEADER_BYTES = Long.BYTES * 2 + Integer.BYTES * 2;
		private static final int MAX_KEY_BYTES = 1024 * 1024 * 1024;

		private final Arena arena;
		private final MemorySegment data;
		private final MemorySegment index;
		private final long capacity;

		private PartitionReader(Path dataPath, Path indexPath) throws IOException {
			this(dataPath, indexPath, null, null);
		}

		private PartitionReader(Path dataPath, Path indexPath, BulkTaskScheduler scheduler,
				BulkTaskScheduler.ResourceLease lease) throws IOException {
			Arena mappedArena = Arena.ofShared();
			try {
				data = mapReadonly(dataPath, mappedArena, scheduler, lease);
				index = mapReadonly(indexPath, mappedArena, scheduler, lease);
				long indexBytes = index.byteSize();
				if (indexBytes < INDEX_HEADER_BYTES) {
					throw new IOException("Truncated partition dictionary index: " + indexPath);
				}
				if (index.get(INT_BIG_ENDIAN, 0L) != INDEX_MAGIC
						|| index.get(INT_BIG_ENDIAN, Integer.BYTES) != INDEX_VERSION) {
					throw new IOException("Unsupported partition dictionary index: " + indexPath);
				}
				capacity = index.get(LONG_BIG_ENDIAN, Integer.BYTES * 2L);
				if (capacity <= 0L || (capacity & (capacity - 1L)) != 0L) {
					throw new IOException("Invalid partition dictionary capacity: " + capacity);
				}
				long expectedIndexBytes = Math.addExact(INDEX_HEADER_BYTES,
						Math.multiplyExact(capacity, INDEX_SLOT_BYTES));
				if (index.byteSize() != expectedIndexBytes) {
					throw new IOException("Partition dictionary index size mismatch: " + indexPath);
				}
				arena = mappedArena;
			} catch (IOException | RuntimeException | Error failure) {
				mappedArena.close();
				throw failure;
			}
		}

		private static MemorySegment mapReadonly(Path path, Arena arena, BulkTaskScheduler scheduler,
				BulkTaskScheduler.ResourceLease lease) throws IOException {
			if (scheduler == null) {
				try (FileChannel channel = FileChannel.open(path, StandardOpenOption.READ)) {
					long bytes = channel.size();
					return bytes == 0L ? MemorySegment.NULL
							: channel.map(FileChannel.MapMode.READ_ONLY, 0L, bytes, arena);
				}
			}
			try (BulkTaskScheduler.OpenFileHandle ignored = scheduler.trackOpenFileHandle(lease);
					FileChannel channel = FileChannel.open(path, StandardOpenOption.READ)) {
				long bytes = channel.size();
				return bytes == 0L ? MemorySegment.NULL
						: channel.map(FileChannel.MapMode.READ_ONLY, 0L, bytes, arena);
			}
		}

		long lookup(byte[] canonicalKey) throws IOException {
			long routeHash = CanonicalTermCodec.routeHash64(canonicalKey);
			long slotIndex = slotIndex(routeHash, capacity);
			for (long probes = 0; probes < capacity; probes++) {
				long slotOffset = INDEX_HEADER_BYTES + slotIndex * INDEX_SLOT_BYTES;
				long storedHash = index.get(LONG_BIG_ENDIAN, slotOffset);
				long offsetPlusOne = index.get(LONG_BIG_ENDIAN, slotOffset + Long.BYTES);
				if (offsetPlusOne == 0L) {
					return 0L;
				}
				if (storedHash == routeHash) {
					long id = matchingId(offsetPlusOne - 1L, routeHash, canonicalKey);
					if (id != 0L) {
						return id;
					}
				}
				slotIndex = slotIndex + 1L & capacity - 1L;
			}
			return 0L;
		}

		private long matchingId(long offset, long routeHash, byte[] canonicalKey) throws IOException {
			if (offset < 0L || offset > data.byteSize() - DATA_HEADER_BYTES) {
				throw new IOException("Partition dictionary index points outside the data file");
			}
			if (data.get(LONG_BIG_ENDIAN, offset) != routeHash) {
				throw new IOException("Partition dictionary index points to a different route hash");
			}
			long id = data.get(LONG_BIG_ENDIAN, offset + Long.BYTES);
			int keyLength = data.get(INT_BIG_ENDIAN, offset + Long.BYTES * 2L + Integer.BYTES);
			if (keyLength < 0 || keyLength > MAX_KEY_BYTES) {
				throw new IOException("Invalid partition dictionary key length: " + keyLength);
			}
			if (keyLength != canonicalKey.length) {
				return 0L;
			}
			long keyOffset = offset + DATA_HEADER_BYTES;
			if (keyOffset > data.byteSize() - keyLength) {
				throw new IOException("Partition dictionary key extends outside the data file");
			}
			MemorySegment storedKey = data.asSlice(keyOffset, keyLength);
			return storedKey.mismatch(MemorySegment.ofArray(canonicalKey)) == -1L ? id : 0L;
		}

		@Override
		public void close() {
			arena.close();
		}
	}

	record Entry(int partition, long routeHash, long id, int roles, byte[] key) {
	}

	@FunctionalInterface
	interface EntryConsumer {
		void accept(Entry entry) throws IOException;
	}

	static long slotIndex(long routeHash, long capacity) {
		long mixed = routeHash ^ routeHash >>> 33;
		mixed *= 0xff51afd7ed558ccdL;
		mixed ^= mixed >>> 33;
		return mixed & capacity - 1L;
	}

}
