/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.bulk;

import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.concurrent.CancellationException;
import java.util.function.BooleanSupplier;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;

/**
 * Expands datatype, namespace, and RDF-star component closure after parsing, so the fast parser never needs model
 * objects on its hot path.
 */
final class ValueDependencyCollector implements AutoCloseable {

	private static final int CACHE_CAPACITY = 16_384;
	private static final int MAX_CACHEABLE_KEY_BYTES = 512;

	private final Path directory;
	private final int partitionCount;
	private final LmdbStoreConfig config;
	private final BooleanSupplier cancellationSignal;
	private final BulkCompression compression;
	private final BoundedBucketOutputLimiter outputs;
	private final DirectCache expanded = new DirectCache(CACHE_CAPACITY);
	private final DirectCache emitted = new DirectCache(CACHE_CAPACITY);

	private ValueDependencyCollector(Path directory, int partitionCount, int maxOpenFiles, LmdbStoreConfig config,
			BulkCompression compression, BooleanSupplier cancellationSignal) throws IOException {
		this.compression = compression;
		this.directory = directory;
		this.partitionCount = partitionCount;
		this.config = config;
		this.cancellationSignal = cancellationSignal;
		this.outputs = new BoundedBucketOutputLimiter(maxOpenFiles);
		Files.createDirectories(directory);
	}

	static ValueDependencyBuckets collect(CanonicalStagedInput staged, Path workspace, int partitionCount,
			int maxOpenFiles, LmdbStoreConfig config, BulkCompression compression,
			BooleanSupplier cancellationSignal) throws IOException {
		Path directory = workspace.resolve("dependency-buckets");
		try (ValueDependencyCollector collector = new ValueDependencyCollector(directory, partitionCount, maxOpenFiles,
				config, compression, cancellationSignal)) {
			for (int partition = 0; partition < partitionCount; partition++) {
				collector.checkCancelled();
				staged.forEachPartitionValue(partition,
						(ignored, routeHash, roles, key) -> collector.expand(routeHash, key));
			}
		}
		return new ValueDependencyBuckets(directory, partitionCount, compression);
	}

	private void expand(long routeHash, byte[] canonicalKey) throws IOException {
		if (CanonicalTermCodec.isNamespace(canonicalKey) || !expanded.remember(routeHash, canonicalKey)) {
			return;
		}
		Value value = CanonicalTermCodec.decode(canonicalKey);
		if (InlineValueCodec.tryEncode(value, config) != 0L) {
			return;
		}
		switch (value) {
		case IRI iri -> emitNamespace(iri.getNamespace());
		case Literal literal -> emitValue(literal.getDatatype());
		case TripleTerm tripleTerm -> {
			emitValue(tripleTerm.getSubject());
			emitValue(tripleTerm.getPredicate());
			emitValue(tripleTerm.getObject());
		}
		default -> {
			// Blank nodes have no dependent values.
		}
		}
	}

	private void emitValue(Value value) throws IOException {
		if (InlineValueCodec.tryEncode(value, config) != 0L) {
			return;
		}
		byte[] key = CanonicalTermCodec.encode(value);
		long hash = CanonicalTermCodec.routeHash64(key);
		if (emitted.remember(hash, key)) {
			write(hash, CanonicalStatementStager.ROLE_DEPENDENCY, key);
		}
		expand(hash, key);
	}

	private void emitNamespace(String namespace) throws IOException {
		byte[] key = CanonicalTermCodec.encodeNamespace(namespace);
		long hash = CanonicalTermCodec.routeHash64(key);
		if (emitted.remember(hash, key)) {
			write(hash, CanonicalStatementStager.ROLE_NAMESPACE, key);
		}
	}

	private void write(long hash, int roles, byte[] key) throws IOException {
		checkCancelled();
		int partition = (int) hash & (partitionCount - 1);
		DataOutputStream output = outputs.output(partition,
				() -> BulkLz4.appendOutput(ValueDependencyBuckets.bucketPath(directory, partition),
						compression.codecFor(BulkArtifact.DEPENDENCY_BUCKETS)));
		output.writeLong(hash);
		output.writeByte(roles);
		output.writeInt(key.length);
		output.write(key);
	}

	private void checkCancelled() {
		if (Thread.currentThread().isInterrupted() || cancellationSignal.getAsBoolean()) {
			throw new CancellationException("LMDB bulk load was cancelled");
		}
	}

	@Override
	public void close() throws IOException {
		outputs.close();
	}

	private static final class DirectCache {

		private final long[] hashes;
		private final byte[][] keys;
		private final int mask;

		private DirectCache(int capacity) {
			hashes = new long[capacity];
			keys = new byte[capacity][];
			mask = capacity - 1;
		}

		private boolean remember(long hash, byte[] key) {
			if (key.length > MAX_CACHEABLE_KEY_BYTES) {
				return true;
			}
			int slot = (int) hash & mask;
			byte[] cached = keys[slot];
			if (cached != null && hashes[slot] == hash && Arrays.equals(cached, key)) {
				return false;
			}
			hashes[slot] = hash;
			keys[slot] = key;
			return true;
		}
	}
}
