PREFIX ex: <http://example.com/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
ex:bigCo1 a ex:Company ;
	rdfs:label "Big Co", "Big Co"@en, "Stor bedrift"@no, [].


ex:bigCo2 a ex:Company ;
	rdfs:label "Big Co", "Big Co"@en, "Stor bedrift"@no, [].


ex:bigCo3 a ex:Company ;
	rdfs:label "Big Co", "Big Co"@en, "Stor bedrift"@no, [].


ex:bigCo4 a ex:Company ;
	rdfs:label "Big Co", "Big Co"@en, "Stor bedrift"@no, [].

}
