/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.estimate;

import java.io.Closeable;
import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import org.eclipse.rdf4j.sail.lmdb.util.GroupMatcher;

/**
 * Transaction-aware facade around the bounded LMDB B+tree range counter.
 *
 * <p>
 * Callers supply the ID of the already-pinned LMDB read transaction. This class selects the newest valid meta page no
 * newer than that transaction, resolves the requested named database from that same snapshot, and shares decoded pages
 * only among estimates for that snapshot. When the transaction ID or native mapping changes, {@link #snapshot(long)}
 * installs a fresh cache. This is the boundary that keeps low-level page reads consistent with the logical query view.
 * </p>
 *
 * <p>
 * The production constructor receives the open LMDB environment so reads can be zero-copy views of LMDB's native map.
 * The file-only constructor intentionally follows the same decoder through positional channel reads and exists for
 * standalone callers and tests. Both paths must produce identical estimates.
 * </p>
 */
public final class LmdbPageCardinalityEstimator implements Closeable {

	/**
	 * Estimate and reliability evidence used by {@code TripleStore} to decide whether another physical index is worth
	 * reading.
	 *
	 * @param entries                      rounded point estimate, clamped to the hard bounds
	 * @param exact                        whether the point estimate is known exactly
	 * @param exhaustive                   whether the selected structural plan was completely measured
	 * @param hardLowerBound               records proven to match
	 * @param hardUpperBound               greatest count still permitted by exact metadata and measurements
	 * @param effectiveSampleSize          concentration-adjusted number of independent leaf observations
	 * @param effectiveSampleFraction      effective sample size divided by the number of probes
	 * @param sampledMassFraction          fraction of the estimate contributed by sampled rather than exact mass
	 * @param relativeStandardError        conservative relative sampling error estimate
	 * @param disagreement                 largest multiplicative disagreement among independent evidence streams
	 * @param physicalPilotDisagreement    physical-range estimate versus the residual pilot's range estimate
	 * @param pilotFinalDisagreement       residual pilot estimate versus the final residual estimate
	 * @param directRatioDisagreement      directly weighted matches versus physical mass times sampled match ratio
	 * @param lowEffectiveSample           whether repeated or concentrated probes weakened effective coverage
	 * @param disagreementDetected         whether any evidence streams exceeded the disagreement threshold
	 * @param additionalEvidenceUsed       whether a conditional confirmation stream was read
	 * @param secondaryEvidenceRecommended whether a separate index layout should corroborate this result
	 * @param physicalProbeBudgetUsed      requested probes for physical range mass
	 * @param residualPilotProbeBudgetUsed requested probes for the residual pilot
	 * @param residualFinalProbeBudgetUsed requested probes for the selected residual budget
	 * @param conditionalProbeBudgetUsed   requested probes for conditional confirmations
	 */
	public record Estimate(
			long entries,
			boolean exact,
			boolean exhaustive,
			long hardLowerBound,
			long hardUpperBound,
			double effectiveSampleSize,
			double effectiveSampleFraction,
			double sampledMassFraction,
			double relativeStandardError,
			double disagreement,
			double physicalPilotDisagreement,
			double pilotFinalDisagreement,
			double directRatioDisagreement,
			boolean lowEffectiveSample,
			boolean disagreementDetected,
			boolean additionalEvidenceUsed,
			boolean secondaryEvidenceRecommended,
			int physicalProbeBudgetUsed,
			int residualPilotProbeBudgetUsed,
			int residualFinalProbeBudgetUsed,
			int conditionalProbeBudgetUsed) {
	}

	private final LmdbDataFile dataFile;
	/** Most recently used snapshot; safe publication lets concurrent readers reuse its thread-safe caches. */
	private volatile SnapshotCache lastSnapshot;

	/** File-channel fallback constructor, retained for compatibility and standalone tests. */
	public LmdbPageCardinalityEstimator(File dataMdbFile) throws IOException {
		this(dataMdbFile, 0L);
	}

	/**
	 * Native-map constructor used by {@code TripleStore}. The environment handle lets page reads use LMDB's existing
	 * mapping without copying pages through {@link java.nio.channels.FileChannel}.
	 */
	public LmdbPageCardinalityEstimator(File dataMdbFile, long env) throws IOException {
		this.dataFile = new LmdbDataFile(dataMdbFile, env);
	}

	public long estimateEntries(long txnId, String dbName, byte[] minKey, int minKeyLength, byte[] maxKey,
			int maxKeyLength, GroupMatcher matcher) throws IOException {
		return estimateEntries(txnId, dbName, minKey, minKeyLength, maxKey, maxKeyLength, matcher,
				matcher == null ? 0 : 1);
	}

	public long estimateEntries(long txnId, String dbName, byte[] minKey, int minKeyLength, byte[] maxKey,
			int maxKeyLength, GroupMatcher matcher, int residualFieldCount) throws IOException {
		return estimateEntriesDetailed(txnId, dbName, minKey, minKeyLength, maxKey, maxKeyLength, matcher,
				residualFieldCount).entries;
	}

	public Estimate estimateEntriesWithQuality(long txnId, String dbName, byte[] minKey, int minKeyLength,
			byte[] maxKey, int maxKeyLength, GroupMatcher matcher, int residualFieldCount) throws IOException {
		RangeCountResult result = estimateEntriesDetailed(txnId, dbName, minKey, minKeyLength, maxKey,
				maxKeyLength, matcher, residualFieldCount);
		return new Estimate(result.entries, result.exact, result.exhaustive, result.hardLowerBound,
				result.hardUpperBound, result.effectiveSampleSize, result.effectiveSampleFraction,
				result.sampledMassFraction, result.relativeStandardError, result.disagreement,
				result.physicalPilotDisagreement, result.pilotFinalDisagreement,
				result.directRatioDisagreement, result.lowEffectiveSample, result.disagreementDetected,
				result.additionalEvidenceUsed, result.secondaryEvidenceRecommended,
				result.physicalProbeBudgetUsed, result.residualPilotProbeBudgetUsed,
				result.residualFinalProbeBudgetUsed, result.conditionalProbeBudgetUsed);
	}

	/**
	 * Resolves {@code dbName} and estimates the inclusive range {@code [minKey, maxKey]}. A null matcher means that the
	 * key range expresses the complete predicate. Otherwise, {@code residualFieldCount} describes how many bound RDF
	 * statement fields the matcher must check after the contiguous index prefix; it guides bounded evidence allocation
	 * but never changes matching semantics.
	 */
	RangeCountResult estimateEntriesDetailed(long txnId, String dbName, byte[] minKey, int minKeyLength,
			byte[] maxKey, int maxKeyLength, GroupMatcher matcher, int residualFieldCount) throws IOException {
		SnapshotCache snapshot = snapshot(txnId);
		LmdbDb db = namedDb(snapshot, dbName);
		if (db == null || db.isEmpty()) {
			RangeCountResult empty = new RangeCountResult();
			empty.exact = true;
			empty.exhaustive = true;
			empty.hardLowerBound = 0L;
			empty.hardUpperBound = 0L;
			empty.mode = RangeCountResult.Mode.EXACT_EMPTY;
			return empty;
		}

		LmdbBtreeRangeCounter counter = new LmdbBtreeRangeCounter(dataFile, snapshot.meta, snapshot.pageCache,
				stableDatabaseIdentity(dbName));
		return counter.estimateRange(db, minKey, minKeyLength, maxKey, maxKeyLength, matcher,
				Math.max(0, residualFieldCount));
	}

	public long totalEntries(long txnId, String dbName) throws IOException {
		SnapshotCache snapshot = snapshot(txnId);
		LmdbDb db = namedDb(snapshot, dbName);
		return db == null ? 0 : db.entries();
	}

	@Override
	public void close() throws IOException {
		dataFile.close();
	}

	/**
	 * Returns a cache tied to {@code txnId} and the current native mapping. Races may construct equivalent caches; the
	 * last volatile publication wins, and no cache can leak across a transaction or remap boundary.
	 */
	private SnapshotCache snapshot(long txnId) throws IOException {
		SnapshotCache cached = lastSnapshot;
		if (cached != null && cached.txnId == txnId && dataFile.isNativeMapCurrent(cached.meta)) {
			return cached;
		}
		LmdbMeta meta = dataFile.readMetaForTxn(txnId);
		SnapshotCache refreshed = new SnapshotCache(txnId, meta);
		lastSnapshot = refreshed;
		return refreshed;
	}

	/** Reads a named database descriptor from LMDB's main database, then caches it only inside this snapshot. */
	private LmdbDb namedDb(SnapshotCache snapshot, String dbName) throws IOException {
		LmdbDb cached = snapshot.namedDbs.get(dbName);
		if (cached != null) {
			return cached;
		}

		LmdbBtreeRangeCounter counter = new LmdbBtreeRangeCounter(dataFile, snapshot.meta, snapshot.pageCache,
				stableDatabaseIdentity("<main>"));
		RangeCountResult lookupStats = new RangeCountResult();
		byte[] key = dbName.getBytes(StandardCharsets.UTF_8);
		byte[] keyWithTerminator = new byte[key.length + 1];
		System.arraycopy(key, 0, keyWithTerminator, 0, key.length);

		byte[] value = counter.findValueByExactKey(snapshot.meta.mainDb(), key, key.length, lookupStats);
		if (value == null) {
			value = counter.findValueByExactKey(snapshot.meta.mainDb(), keyWithTerminator,
					keyWithTerminator.length, lookupStats);
		}
		if (value == null) {
			return null;
		}

		ByteBuffer valueBuffer = ByteBuffer.wrap(value).order(snapshot.meta.byteOrder());
		LmdbDb parsed = LmdbDb.parse(valueBuffer, 0);
		LmdbDb existing = snapshot.namedDbs.putIfAbsent(dbName, parsed);
		return existing == null ? parsed : existing;
	}

	/**
	 * Stable logical identity mixed into sampling seeds. Page numbers are deliberately excluded because LMDB
	 * copy-on-write commits can renumber physical pages without changing the requested logical range.
	 */
	private long stableDatabaseIdentity(String dbName) {
		long hash = 0xcbf29ce484222325L;
		for (int index = 0; index < dbName.length(); index++) {
			hash ^= dbName.charAt(index);
			hash *= 0x100000001b3L;
		}
		return hash;
	}

	/** All mutable caches below are valid only for one LMDB transaction ID and mapping identity. */
	private static final class SnapshotCache {
		final long txnId;
		final LmdbMeta meta;
		final LmdbPageCache pageCache = new LmdbPageCache();
		final Map<String, LmdbDb> namedDbs = new ConcurrentHashMap<>();

		SnapshotCache(long txnId, LmdbMeta meta) {
			this.txnId = txnId;
			this.meta = meta;
		}
	}
}
