/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.estimate;

import static org.lwjgl.system.MemoryStack.stackPush;
import static org.lwjgl.system.MemoryUtil.memAddress;
import static org.lwjgl.system.MemoryUtil.memByteBuffer;
import static org.lwjgl.system.MemoryUtil.memGetLong;
import static org.lwjgl.system.MemoryUtil.memGetShort;
import static org.lwjgl.system.MemoryUtil.memUTF8;
import static org.lwjgl.util.lmdb.LMDB.MDB_FIRST;
import static org.lwjgl.util.lmdb.LMDB.MDB_NOSUBDIR;
import static org.lwjgl.util.lmdb.LMDB.MDB_SUCCESS;
import static org.lwjgl.util.lmdb.LMDB.mdb_cursor_close;
import static org.lwjgl.util.lmdb.LMDB.mdb_cursor_get;
import static org.lwjgl.util.lmdb.LMDB.mdb_cursor_open;
import static org.lwjgl.util.lmdb.LMDB.mdb_dbi_open;
import static org.lwjgl.util.lmdb.LMDB.mdb_env_get_flags;
import static org.lwjgl.util.lmdb.LMDB.mdb_env_get_path;
import static org.lwjgl.util.lmdb.LMDB.mdb_env_info;
import static org.lwjgl.util.lmdb.LMDB.mdb_strerror;
import static org.lwjgl.util.lmdb.LMDB.mdb_txn_env;
import static org.lwjgl.util.lmdb.LMDB.mdb_txn_id;

import java.io.Closeable;
import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.IntBuffer;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

import org.lwjgl.PointerBuffer;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.util.lmdb.MDBEnvInfo;
import org.lwjgl.util.lmdb.MDBVal;

/**
 * Reads LMDB pages either as zero-copy views over the environment's existing native map or, for the public file-only
 * constructor and tests, through positional file reads.
 */
final class LmdbDataFile implements Closeable {

	private static final int META_PROBE_BYTES = 4096;
	private static final int META_BASE_OFFSET = LmdbFormat.PAGE_HEADER_SIZE;
	private static final int MIN_PAGE_SIZE = 512;
	private static final int MAX_PAGE_SIZE = 65_536;
	private static final long NO_NATIVE_MAP = 0L;

	private final File dataFile;
	private final FileChannel channel;
	private final long env;
	private final ByteOrder byteOrder;
	private final int pageSize;
	private final ThreadLocal<ByteBuffer> headerBuffer = ThreadLocal
			.withInitial(() -> ByteBuffer.allocateDirect(LmdbFormat.PAGE_HEADER_SIZE));

	LmdbDataFile(File dataFile) throws IOException {
		this(dataFile, 0L);
	}

	LmdbDataFile(File dataFile, long env) throws IOException {
		this.dataFile = dataFile;
		this.env = env;
		this.channel = FileChannel.open(dataFile.toPath(), StandardOpenOption.READ);
		try {
			validateEnvironmentFile();
			this.byteOrder = detectByteOrder();
			this.pageSize = probePageSize(byteOrder);
		} catch (IOException | RuntimeException | Error failure) {
			try {
				channel.close();
			} catch (IOException closeFailure) {
				failure.addSuppressed(closeFailure);
			}
			throw failure;
		}
	}

	/**
	 * Synthetic-page constructor used by package-local estimator tests. Production callers must use one of the
	 * constructors that validates the LMDB meta pages.
	 */
	LmdbDataFile(File dataFile, ByteOrder byteOrder, int pageSize) throws IOException {
		if (byteOrder == null) {
			throw new NullPointerException("byteOrder");
		}
		if (pageSize < MIN_PAGE_SIZE || pageSize > MAX_PAGE_SIZE || (pageSize & (pageSize - 1)) != 0) {
			throw new IOException("Invalid synthetic LMDB page size " + pageSize);
		}
		this.dataFile = dataFile;
		this.env = NO_NATIVE_MAP;
		this.channel = FileChannel.open(dataFile.toPath(), StandardOpenOption.READ);
		this.byteOrder = byteOrder;
		this.pageSize = pageSize;
	}

	/**
	 * Selects the newest valid meta page that is not newer than the read transaction pinned by LMDB.
	 *
	 * <p>
	 * LMDB alternates between two meta pages. Reading whichever page has the greatest transaction id would race a
	 * writer and could combine a newer tree root with the caller's older read view. The exact transaction is preferred;
	 * the newest older meta is accepted because read-only transactions can legitimately outlive later commits.
	 */
	LmdbMeta readMetaForTxn(long pinnedTxnId) throws IOException {
		LmdbMeta meta0 = readMetaPage(0);
		LmdbMeta meta1 = readMetaPage(1);

		LmdbMeta selected = null;
		for (LmdbMeta candidate : new LmdbMeta[] { meta0, meta1 }) {
			if (candidate == null) {
				continue;
			}
			if (candidate.txnId() == pinnedTxnId) {
				selected = candidate;
				break;
			}
			if (candidate.txnId() <= pinnedTxnId && (selected == null || candidate.txnId() > selected.txnId())) {
				selected = candidate;
			}
		}
		if (selected == null) {
			throw new IOException("No valid LMDB meta page for pinned txn " + pinnedTxnId + " in " + dataFile);
		}

		return selected;
	}

	/**
	 * Reads and validates a page belonging to {@code meta}. The native mapping is the zero-copy fast path; positional
	 * file IO is retained for tests and as a safe fallback when the mapping captured with the snapshot is unavailable.
	 */
	LmdbPage readPage(long pageNumber, LmdbMeta meta) throws IOException {
		long offset = checkedPageOffset(pageNumber, meta);
		ByteBuffer page;
		if (canUseNativeMap(meta, offset, meta.pageSize())) {
			long address = Math.addExact(meta.nativeMapAddress(), offset);
			page = memByteBuffer(address, meta.pageSize()).asReadOnlyBuffer().order(meta.byteOrder());
		} else {
			page = readAt(offset, meta.pageSize(), meta.byteOrder());
		}
		return LmdbPage.parse(pageNumber, page, meta.pageSize());
	}

	/** Reads only the fixed LMDB page header for matcher-free, non-DUPSORT leaf samples. */
	int readLeafEntryCount(long pageNumber, LmdbMeta meta) throws IOException {
		long offset = checkedPageOffset(pageNumber, meta);
		if (canUseNativeMap(meta, offset, LmdbFormat.PAGE_HEADER_SIZE)) {
			long address = Math.addExact(meta.nativeMapAddress(), offset);
			long storedPageNumber = nativeLong(address, meta.byteOrder());
			if (storedPageNumber != pageNumber) {
				throw new IOException("Page number mismatch: expected " + pageNumber + ", found " + storedPageNumber);
			}
			int flags = Short.toUnsignedInt(nativeShort(address + 10, meta.byteOrder()));
			if ((flags & LmdbFormat.P_LEAF) == 0 || (flags & LmdbFormat.P_LEAF2) != 0) {
				throw new IOException("Expected ordinary leaf page " + pageNumber + ", flags=0x"
						+ Integer.toHexString(flags));
			}
			int lower = Short.toUnsignedInt(nativeShort(address + 12, meta.byteOrder()));
			return checkedNodeCount(pageNumber, lower, meta.pageSize());
		}

		ByteBuffer header = headerBuffer.get();
		header.clear().limit(LmdbFormat.PAGE_HEADER_SIZE);
		readFully(header, offset);
		header.flip().order(meta.byteOrder());
		long storedPageNumber = header.getLong(0);
		if (storedPageNumber != pageNumber) {
			throw new IOException("Page number mismatch: expected " + pageNumber + ", found " + storedPageNumber);
		}
		int flags = LmdbFormat.unsignedShort(header, 10);
		if ((flags & LmdbFormat.P_LEAF) == 0 || (flags & LmdbFormat.P_LEAF2) != 0) {
			throw new IOException("Expected ordinary leaf page " + pageNumber + ", flags=0x"
					+ Integer.toHexString(flags));
		}
		return checkedNodeCount(pageNumber, LmdbFormat.unsignedShort(header, 12), meta.pageSize());
	}

	int pageSize() {
		return pageSize;
	}

	ByteOrder byteOrder() {
		return byteOrder;
	}

	@Override
	public void close() throws IOException {
		channel.close();
		headerBuffer.remove();
	}

	/** The returned views borrow {@code readTxn}; the caller must keep it pinned until all page reads finish. */
	LmdbMeta readMetaForReadTransaction(long readTxn) throws IOException {
		LmdbMeta meta = readMetaForTxn(mdb_txn_id(readTxn));
		return withNativeMap(meta, mappingAnchor(meta), readTxn);
	}

	/**
	 * Locate the first main-database key using file reads only. MDB_FIRST returns this same outer key even when its
	 * value lives in an overflow page or duplicate tree. Keep a heap copy so later mapping checks never read a stale
	 * native page. No assumption is made about OS allocation alignment or database comparator order.
	 */
	MappingAnchor mappingAnchor(LmdbMeta meta) throws IOException {
		if (env == NO_NATIVE_MAP || meta.mainDb().isEmpty()) {
			return null;
		}
		LmdbMeta fileMeta = withMap(meta, 0L, 0L);
		long pageNumber = meta.mainDb().rootPgno();
		for (int depth = meta.mainDb().depth(); depth > 0; depth--) {
			LmdbPage page = readPage(pageNumber, fileMeta);
			if (page.isBranch() && depth > 1) {
				pageNumber = page.branchPgnoAt(page.nodeOffset(0));
				continue;
			}
			if (!page.isLeaf() || depth != 1 || page.numKeys == 0) {
				throw new IOException("Invalid first-key path in LMDB main database");
			}
			int keyOffset;
			int keySize;
			if (page.isLeaf2()) {
				keyOffset = LmdbFormat.PAGE_HEADER_SIZE;
				keySize = page.pad;
			} else {
				int nodeOffset = page.nodeOffset(0);
				keyOffset = page.keyOffsetAt(nodeOffset);
				keySize = page.keySizeAt(nodeOffset);
			}
			if (keySize <= 0 || keySize > pageSize - keyOffset) {
				throw new IOException("Invalid first key in LMDB main database");
			}
			byte[] key = new byte[keySize];
			page.buffer.get(keyOffset, key);
			return new MappingAnchor(checkedPageOffset(pageNumber, meta) + keyOffset, key);
		}
		throw new IOException("Invalid depth in LMDB main database");
	}

	/**
	 * Recover LMDB's existing mapping from a documented cursor-returned key pointer and its verified file offset. Only
	 * an exact committed snapshot is eligible: write-transaction dirty pages are not necessarily mapped. The caller
	 * supplies the already-pinned read transaction; opening an extra transaction would break TLS environments. Re-run
	 * this check before reusing cached page views, since LMDB may remap without changing the transaction ID.
	 */
	LmdbMeta withNativeMap(LmdbMeta meta, MappingAnchor anchor, long readTxn) throws IOException {
		if (env == NO_NATIVE_MAP) {
			return withMap(meta, 0L, 0L);
		}
		if (readTxn == 0L || mdb_txn_env(readTxn) != env) {
			throw new IOException("Read transaction does not belong to the estimator's LMDB environment");
		}
		if (meta.txnId() != mdb_txn_id(readTxn)) {
			throw new IOException("No exact committed metadata for the pinned LMDB transaction");
		}
		if (anchor == null) {
			return withMap(meta, 0L, 0L);
		}
		try (MemoryStack stack = stackPush()) {
			MDBEnvInfo info = MDBEnvInfo.malloc(stack);
			check(mdb_env_info(env, info));
			long size;
			try {
				size = Math.multiplyExact(Math.addExact(meta.lastPage(), 1L), (long) pageSize);
			} catch (ArithmeticException overflow) {
				throw new IOException("LMDB snapshot size overflow", overflow);
			}
			if (size <= 0 || size > info.me_mapsize() || size > meta.mapSize()
					|| anchor.fileOffset < 0 || anchor.fileOffset > size - anchor.key.length) {
				throw new IOException("LMDB snapshot exceeds mapping bounds");
			}
			IntBuffer dbi = stack.mallocInt(1);
			check(mdb_dbi_open(readTxn, (ByteBuffer) null, 0, dbi));
			PointerBuffer cursorPointer = stack.mallocPointer(1);
			check(mdb_cursor_open(readTxn, dbi.get(0), cursorPointer));
			long cursor = cursorPointer.get(0);
			try {
				MDBVal key = MDBVal.malloc(stack);
				MDBVal value = MDBVal.malloc(stack);
				check(mdb_cursor_get(cursor, key, value, MDB_FIRST));
				if (key.mv_size() != anchor.key.length) {
					throw new IOException("LMDB cursor key does not match snapshot key size");
				}
				ByteBuffer mappedKey = key.mv_data();
				for (int index = 0; index < anchor.key.length; index++) {
					if (mappedKey.get(index) != anchor.key[index]) {
						throw new IOException("LMDB cursor key does not match snapshot key");
					}
				}
				long pageNumber = anchor.fileOffset / pageSize;
				int keyOffset = (int) (anchor.fileOffset % pageSize);
				if (pageNumber < 2 || keyOffset < LmdbFormat.PAGE_HEADER_SIZE) {
					throw new IOException("Invalid LMDB mapping anchor offset");
				}
				// Read at most one page backwards from a mapped outer key, stopping before the key itself.
				// This stays inside LMDB's mapping even if the file offset is stale: two metadata pages precede
				// every data page. Check the page number before constructing or dereferencing the mapping base.
				ByteBuffer header = memByteBuffer(memAddress(mappedKey) - keyOffset, LmdbFormat.PAGE_HEADER_SIZE)
						.order(meta.byteOrder());
				if (header.getLong(0) != pageNumber
						|| (LmdbFormat.unsignedShort(header, 10) & LmdbFormat.P_LEAF) == 0) {
					throw new IOException("LMDB cursor page does not match snapshot page");
				}
				long address;
				try {
					address = Math.subtractExact(memAddress(mappedKey), anchor.fileOffset);
					Math.addExact(address, size);
				} catch (ArithmeticException overflow) {
					throw new IOException("LMDB mapping address overflow", overflow);
				}
				if (address == 0L) {
					throw new IOException("Invalid LMDB mapping address");
				}
				return withMap(meta, address, size);
			} finally {
				mdb_cursor_close(cursor);
			}
		}
	}

	private static LmdbMeta withMap(LmdbMeta meta, long address, long size) {
		return new LmdbMeta(meta.metaPage(), meta.txnId(), meta.pageSize(), meta.mapSize(), meta.lastPage(),
				meta.freeDb(), meta.mainDb(), meta.byteOrder(), address, size);
	}

	/** Heap-only anchor; no memory owned by an LMDB transaction escapes through this record. */
	record MappingAnchor(long fileOffset, byte[] key) {
	}

	private void validateEnvironmentFile() throws IOException {
		if (env == NO_NATIVE_MAP) {
			return;
		}
		try (MemoryStack stack = stackPush()) {
			PointerBuffer path = stack.mallocPointer(1);
			IntBuffer flags = stack.mallocInt(1);
			check(mdb_env_get_path(env, path));
			check(mdb_env_get_flags(env, flags));
			Path location = Path.of(memUTF8(path.get(0)));
			Path expected = (flags.get(0) & MDB_NOSUBDIR) != 0 ? location : location.resolve("data.mdb");
			if (!Files.isSameFile(dataFile.toPath(), expected)) {
				throw new IOException("Data file does not belong to the estimator's LMDB environment");
			}
		}
	}

	private static void check(int result) throws IOException {
		if (result != MDB_SUCCESS) {
			throw new IOException(mdb_strerror(result));
		}
	}

	private LmdbMeta readMetaPage(int metaPage) throws IOException {
		ByteBuffer page = readAt((long) metaPage * pageSize, pageSize, byteOrder);
		int flags = LmdbFormat.unsignedShort(page, 10);
		if ((flags & LmdbFormat.P_META) == 0) {
			return null;
		}
		int magic = page.getInt(META_BASE_OFFSET + LmdbFormat.META_MAGIC_OFFSET);
		if (magic != LmdbFormat.MDB_MAGIC) {
			return null;
		}
		int version = page.getInt(META_BASE_OFFSET + LmdbFormat.META_VERSION_OFFSET);
		if (version != LmdbFormat.MDB_DATA_VERSION && version != LmdbFormat.MDB_DATA_VERSION_DEVEL) {
			return null;
		}

		long mapSize = page.getLong(META_BASE_OFFSET + LmdbFormat.META_MAP_SIZE_OFFSET);
		LmdbDb freeDb = LmdbDb.parse(page, META_BASE_OFFSET + LmdbFormat.META_DBS_OFFSET);
		LmdbDb mainDb = LmdbDb.parse(page,
				META_BASE_OFFSET + LmdbFormat.META_DBS_OFFSET + LmdbFormat.META_DB_SIZE);
		long lastPage = page.getLong(META_BASE_OFFSET + LmdbFormat.META_LAST_PG_OFFSET);
		long txnId = page.getLong(META_BASE_OFFSET + LmdbFormat.META_TXNID_OFFSET);
		return new LmdbMeta(metaPage, txnId, pageSize, mapSize, lastPage, freeDb, mainDb, byteOrder);
	}

	private int probePageSize(ByteOrder order) throws IOException {
		ByteBuffer probe = readAt(0, META_PROBE_BYTES, order);
		int detected = probe.getInt(META_BASE_OFFSET + LmdbFormat.META_DBS_OFFSET
				+ LmdbFormat.MDB_DB_PAD_OFFSET);
		if (detected < MIN_PAGE_SIZE || detected > MAX_PAGE_SIZE || (detected & (detected - 1)) != 0) {
			throw new IOException("Invalid LMDB page size " + detected + " in " + dataFile);
		}
		return detected;
	}

	private ByteOrder detectByteOrder() throws IOException {
		ByteBuffer magicBytes = readAt(0, META_PROBE_BYTES, ByteOrder.BIG_ENDIAN);
		int bigEndianMagic = magicBytes.getInt(META_BASE_OFFSET + LmdbFormat.META_MAGIC_OFFSET);
		if (bigEndianMagic == LmdbFormat.MDB_MAGIC) {
			return ByteOrder.BIG_ENDIAN;
		}
		if (Integer.reverseBytes(bigEndianMagic) == LmdbFormat.MDB_MAGIC) {
			return ByteOrder.LITTLE_ENDIAN;
		}
		throw new IOException("Unable to detect LMDB byte order for " + dataFile);
	}

	private long checkedPageOffset(long pageNumber, LmdbMeta meta) throws IOException {
		if (pageNumber < 0 || pageNumber > meta.lastPage()) {
			throw new IOException("Page " + pageNumber + " is outside snapshot page range 0.." + meta.lastPage());
		}
		long offset;
		try {
			offset = Math.multiplyExact(pageNumber, (long) meta.pageSize());
		} catch (ArithmeticException overflow) {
			throw new IOException("Page offset overflow for page " + pageNumber, overflow);
		}
		if (offset > meta.mapSize() - meta.pageSize()) {
			throw new IOException("Page " + pageNumber + " is outside map bounds (mapsize=" + meta.mapSize() + ')');
		}
		return offset;
	}

	private boolean canUseNativeMap(LmdbMeta meta, long offset, int length) {
		return meta.hasNativeMap() && offset >= 0 && length >= 0 && offset <= meta.nativeMappedSize() - length;
	}

	private int checkedNodeCount(long pageNumber, int lower, int pageSize) throws IOException {
		if (lower < LmdbFormat.PAGE_HEADER_SIZE || lower > pageSize) {
			throw new IOException("Corrupt mp_lower=" + lower + " on page " + pageNumber);
		}
		int count = LmdbFormat.numKeys(lower);
		if (count < 0 || count > (pageSize - LmdbFormat.PAGE_HEADER_SIZE) / Short.BYTES) {
			throw new IOException("Corrupt node count " + count + " on page " + pageNumber);
		}
		return count;
	}

	private short nativeShort(long address, ByteOrder order) {
		short value = memGetShort(address);
		return order == ByteOrder.nativeOrder() ? value : Short.reverseBytes(value);
	}

	private long nativeLong(long address, ByteOrder order) {
		long value = memGetLong(address);
		return order == ByteOrder.nativeOrder() ? value : Long.reverseBytes(value);
	}

	private ByteBuffer readAt(long offset, int length, ByteOrder order) throws IOException {
		ByteBuffer buffer = ByteBuffer.allocateDirect(length).order(order);
		readFully(buffer, offset);
		buffer.flip();
		return buffer;
	}

	private void readFully(ByteBuffer destination, long offset) throws IOException {
		int zeroReads = 0;
		while (destination.hasRemaining()) {
			int read = channel.read(destination, offset + destination.position());
			if (read < 0) {
				throw new IOException("Unexpected EOF while reading " + dataFile + " at "
						+ (offset + destination.position()));
			}
			if (read == 0 && ++zeroReads > 16) {
				throw new IOException("No progress while reading " + dataFile + " at "
						+ (offset + destination.position()));
			}
			if (read > 0) {
				zeroReads = 0;
			}
		}
	}

}
