/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.rio.helpers;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream;
import org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream;
import org.apache.commons.compress.compressors.lz4.FramedLZ4CompressorOutputStream;
import org.apache.commons.compress.compressors.lzma.LZMACompressorOutputStream;
import org.apache.commons.compress.compressors.snappy.FramedSnappyCompressorOutputStream;
import org.apache.commons.compress.compressors.xz.XZCompressorOutputStream;

/** Shared compressed RDF fixtures for packaged-ingestion integration tests. */
public final class RDFInputTestFixtures {

	private static final byte[] BROTLI = Base64.getDecoder()
			.decode("GyMAAERveL07Lv1LvsOnhEQ2IspEJVFHf4tR80ffvgxDG9cGAQ==");
	private static final byte[] ZSTD = Base64.getDecoder()
			.decode("KLUv/SAi9QAAsDx1cm46aW5wdXQ6enN0ZD4gcG8+IC4CACspUjuX");
	private static final byte[] UNIX_COMPRESS = Base64.getDecoder()
			.decode("H52QPOrIcaMjjRs4dejoqOMmDZ4WY960gSOnzJw5PkAEHKgDTsaNBN9kdKEA");

	private RDFInputTestFixtures() {
	}

	/** Returns one fixture for every supported codec and container form. */
	public static List<RDFInputFixture> all() throws IOException {
		byte[] gzipTar = tarBody("tar-gzip");
		byte[] bzip2Tar = tarBody("tar-bzip2");
		byte[] xzTar = tarBody("tar-xz");
		byte[] lz4Tar = tarBody("tar-lz4");
		byte[] zstdTar = tarBody("tar-zstd");

		return List.of(
				plain("plain"),
				codec("gzip", "gz", RioCompression.GZIP.compress(body("gzip")), true),
				codec("deflate", "deflate", RioCompression.DEFLATE.compress(body("deflate")), true),
				codec("brotli", "br", BROTLI, false),
				codec("zstd", "zst", ZSTD, true),
				codec("bzip2", "bz2", bzip2(body("bzip2")), true),
				codec("xz", "xz", xz(body("xz")), true),
				codec("lzma", "lzma", lzma(body("lzma")), false),
				codec("lz4", "lz4", lz4(body("lz4")), true),
				codec("snappy", "sz", snappy(body("snappy")), true),
				codec("unix-compress", "Z", UNIX_COMPRESS, true),
				archive("zip", "data.zip", zip("data.ttl", body("zip"))),
				archive("tar", "data.tar", tarBody("tar")),
				archive("tar-gzip", "data.tar.gz", RioCompression.GZIP.compress(gzipTar)),
				archive("tar-bzip2", "data.tar.bz2", bzip2(bzip2Tar)),
				archive("tar-xz", "data.tar.xz", xz(xzTar)),
				archive("tar-lz4", "data.tar.lz4", lz4(lz4Tar)),
				archive("tar-zstd", "data.tar.zst", RioCompression.ZSTD.compress(zstdTar)));
	}

	private static RDFInputFixture plain(String name) {
		byte[] body = body(name);
		return new RDFInputFixture(name, "data.ttl", body, body, subject(name));
	}

	private static RDFInputFixture codec(String name, String extension, byte[] compressed,
			boolean signatureDetectable) throws IOException {
		String sourceName = "data.ttl." + extension;
		byte[] unnamedInput = signatureDetectable ? compressed : zip(sourceName, compressed);
		return new RDFInputFixture(name, sourceName, compressed, unnamedInput, subject(name));
	}

	private static RDFInputFixture archive(String name, String sourceName, byte[] input) {
		return new RDFInputFixture(name, sourceName, input, input, subject(name));
	}

	private static byte[] body(String name) {
		return ("<" + subject(name) + "> <urn:p> <urn:o> .").getBytes(StandardCharsets.UTF_8);
	}

	private static String subject(String name) {
		return "urn:input:" + name;
	}

	private static byte[] tarBody(String name) throws IOException {
		return tar("data.ttl", body(name));
	}

	private static byte[] zip(String name, byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (ZipOutputStream zip = new ZipOutputStream(output)) {
			zip.putNextEntry(new ZipEntry(name));
			zip.write(body);
			zip.closeEntry();
		}
		return output.toByteArray();
	}

	private static byte[] tar(String name, byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (TarArchiveOutputStream tar = new TarArchiveOutputStream(output)) {
			TarArchiveEntry entry = new TarArchiveEntry(name);
			entry.setSize(body.length);
			tar.putArchiveEntry(entry);
			tar.write(body);
			tar.closeArchiveEntry();
		}
		return output.toByteArray();
	}

	private static byte[] bzip2(byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (BZip2CompressorOutputStream compressed = new BZip2CompressorOutputStream(output)) {
			compressed.write(body);
		}
		return output.toByteArray();
	}

	private static byte[] xz(byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (XZCompressorOutputStream compressed = new XZCompressorOutputStream(output)) {
			compressed.write(body);
		}
		return output.toByteArray();
	}

	private static byte[] lzma(byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (LZMACompressorOutputStream compressed = new LZMACompressorOutputStream(output)) {
			compressed.write(body);
		}
		return output.toByteArray();
	}

	private static byte[] lz4(byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (FramedLZ4CompressorOutputStream compressed = new FramedLZ4CompressorOutputStream(output)) {
			compressed.write(body);
		}
		return output.toByteArray();
	}

	private static byte[] snappy(byte[] body) throws IOException {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		try (FramedSnappyCompressorOutputStream compressed = new FramedSnappyCompressorOutputStream(output)) {
			compressed.write(body);
		}
		return output.toByteArray();
	}

	/** One input as seen with and without a submitted filename. */
	public record RDFInputFixture(String name, String sourceName, byte[] namedInput, byte[] unnamedInput,
			String subjectIri) {

		@Override
		public String toString() {
			return name;
		}
	}
}
