PREFIX ex: <http://example.com/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

INSERT DATA {
   [
    a dcat:Distribution ;
    dc:identifier "https://data.some.org/catalog/datasets/1/distribution/1" ;
    dc:title "A distribution for this dataset in CSV format" ;
    dc:description "A longer description for the distribution" ;
    dcat:downloadURL <https://data.some.org/the/actual/catalog/datasets/1/resources/1.csv> ;
    dcat:mediaType "text/csv" ;
    dc:license <https://data.some.org/link/to/license>
  ].

  [
    a dcat:Distribution ;
    dc:identifier "https://data.some.org/catalog/datasets/1/distribution/2" ;
    dc:title "A distribution for this dataset in PDF format" ;
    dc:description "A longer description for the distribution" ;
    dcat:downloadURL <https://data.some.org/the/actual/catalog/datasets/1/resources/2.pdf> ;
    dc:format [
      a dc:IMT ;
      rdf:value "application/pdf"
    ] ;
    dc:license <https://data.some.org/link/to/license>
  ].

  [
    a dcat:Distribution ;
    dc:identifier "https://data.some.org/catalog/datasets/1/distribution/3" ;
    dc:title "A distribution for this dataset as an API" ;
    dc:description "A longer description for the distribution" ;
    dcat:accessURL <https://data.some.org/the/actual/catalog/link/to/an/api>
  ] .


  [
    a dcat:Distribution ;
    dc:identifier "https://data.some.org/catalog/datasets/2/distribution/1" ;
    dc:title "A distribution for this dataset as an external website" ;
    dc:description "A longer description for the distribution" ;
    dcat:downloadURL <https://external.site.org/> ;

    dc:format "html"
  ].

  [
    a dcat:Distribution ;
    dc:identifier "https://data.some.org/catalog/datasets/2/distribution/2" ;
    dc:title "A distribution for this dataset in PDF format" ;
    dc:description "A longer description for the distribution" ;
    dcat:downloadURL <https://data.some.org/the/actual/catalog/datasets/2/resources/2.pdf> ;

    dc:format [
      a dc:IMT ;
      rdf:value "application/pdf"
    ]
  ] .

}

