/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.common.iteration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Test;

class FilterIterationTest {

	@Test
	void concurrentCloseWhileDelegateHasNextReturnsDoesNotTripInvariant() throws Exception {
		BlockingHasNextIteration delegate = new BlockingHasNextIteration();
		FilterIteration<Integer> iteration = new FilterIteration<>(delegate) {
			@Override
			protected boolean accept(Integer object) {
				return true;
			}

			@Override
			protected void handleClose() {
				// no additional resources
			}
		};
		ExecutorService executor = Executors.newSingleThreadExecutor();
		try {
			Future<Boolean> hasNext = executor.submit(iteration::hasNext);
			assertTrue(delegate.firstHasNextEntered.await(2, TimeUnit.SECONDS));

			iteration.close();
			delegate.allowFirstHasNextReturn.countDown();

			assertFalse(hasNext.get(2, TimeUnit.SECONDS));
		} finally {
			delegate.allowFirstHasNextReturn.countDown();
			iteration.close();
			executor.shutdownNow();
		}
	}

	// REINFORCE: an element accepted while another thread closes the iteration is discarded, never returned
	@Test
	void closeDuringAcceptDiscardsAcceptedElement() throws Exception {
		CountingIteration delegate = new CountingIteration(List.of(7));
		CountDownLatch acceptEntered = new CountDownLatch(1);
		CountDownLatch allowAcceptReturn = new CountDownLatch(1);
		AtomicInteger handleCloseCalls = new AtomicInteger();
		FilterIteration<Integer> iteration = new FilterIteration<>(delegate) {
			@Override
			protected boolean accept(Integer object) {
				acceptEntered.countDown();
				try {
					if (!allowAcceptReturn.await(2, TimeUnit.SECONDS)) {
						throw new AssertionError("timed out waiting to complete accept");
					}
				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
					throw new AssertionError(e);
				}
				return true;
			}

			@Override
			protected void handleClose() {
				handleCloseCalls.incrementAndGet();
			}
		};
		ExecutorService executor = Executors.newSingleThreadExecutor();
		try {
			Future<Boolean> hasNext = executor.submit(iteration::hasNext);
			assertTrue(acceptEntered.await(2, TimeUnit.SECONDS));

			iteration.close();
			allowAcceptReturn.countDown();

			assertFalse(hasNext.get(2, TimeUnit.SECONDS));
			assertThrows(NoSuchElementException.class, iteration::next);
			assertEquals(1, handleCloseCalls.get());
			assertEquals(1, delegate.closeCalls.get());
		} finally {
			allowAcceptReturn.countDown();
			iteration.close();
			executor.shutdownNow();
		}
	}

	// REINFORCE: concurrent close() calls close the delegate and run handleClose exactly once
	@Test
	void concurrentCloseRunsHandleCloseExactlyOnce() throws Exception {
		int threads = 8;
		CountingIteration delegate = new CountingIteration(List.of(1, 2, 3));
		AtomicInteger handleCloseCalls = new AtomicInteger();
		FilterIteration<Integer> iteration = new FilterIteration<>(delegate) {
			@Override
			protected boolean accept(Integer object) {
				return true;
			}

			@Override
			protected void handleClose() {
				handleCloseCalls.incrementAndGet();
			}
		};
		ExecutorService executor = Executors.newFixedThreadPool(threads);
		try {
			CountDownLatch start = new CountDownLatch(1);
			List<Future<?>> closers = new ArrayList<>();
			for (int i = 0; i < threads; i++) {
				closers.add(executor.submit(() -> {
					start.await();
					iteration.close();
					return null;
				}));
			}
			start.countDown();
			for (Future<?> closer : closers) {
				closer.get(2, TimeUnit.SECONDS);
			}
		} finally {
			executor.shutdownNow();
		}
		assertEquals(1, handleCloseCalls.get());
		assertEquals(1, delegate.closeCalls.get());
		assertFalse(iteration.hasNext());
	}

	// REINFORCE: once a rejected element has closed the iteration, the delegate is not probed again
	@Test
	void rejectedElementThatClosesIterationDoesNotProbeDelegateAgain() {
		CountingIteration delegate = new CountingIteration(List.of(1, 2));
		FilterIteration<Integer> iteration = new FilterIteration<>(delegate) {
			@Override
			protected boolean accept(Integer object) {
				close();
				return false;
			}

			@Override
			protected void handleClose() {
				// no additional resources
			}
		};

		assertFalse(iteration.hasNext());
		assertEquals(1, delegate.hasNextCalls.get());
		assertEquals(1, delegate.nextCalls.get());
		assertEquals(1, delegate.closeCalls.get());
	}

	/**
	 * Delegate that counts calls and fails loudly if it is probed after being closed.
	 */
	private static final class CountingIteration implements CloseableIteration<Integer> {
		private final Iterator<Integer> elements;
		private final AtomicBoolean closed = new AtomicBoolean();
		private final AtomicInteger hasNextCalls = new AtomicInteger();
		private final AtomicInteger nextCalls = new AtomicInteger();
		private final AtomicInteger closeCalls = new AtomicInteger();

		private CountingIteration(List<Integer> elements) {
			this.elements = elements.iterator();
		}

		@Override
		public boolean hasNext() {
			if (closed.get()) {
				throw new AssertionError("delegate hasNext() probed after close");
			}
			hasNextCalls.incrementAndGet();
			return elements.hasNext();
		}

		@Override
		public Integer next() {
			if (closed.get()) {
				throw new AssertionError("delegate next() probed after close");
			}
			nextCalls.incrementAndGet();
			return elements.next();
		}

		@Override
		public void remove() {
			throw new UnsupportedOperationException();
		}

		@Override
		public void close() {
			closed.set(true);
			closeCalls.incrementAndGet();
		}
	}

	private static final class BlockingHasNextIteration implements CloseableIteration<Integer> {
		private final CountDownLatch firstHasNextEntered = new CountDownLatch(1);
		private final CountDownLatch allowFirstHasNextReturn = new CountDownLatch(1);
		private final AtomicBoolean closed = new AtomicBoolean();
		private final AtomicInteger hasNextCalls = new AtomicInteger();

		@Override
		public boolean hasNext() {
			if (hasNextCalls.incrementAndGet() == 1) {
				firstHasNextEntered.countDown();
				try {
					if (!allowFirstHasNextReturn.await(2, TimeUnit.SECONDS)) {
						throw new AssertionError("timed out waiting to complete the first hasNext call");
					}
				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
					throw new AssertionError(e);
				}
				return true;
			}
			return !closed.get();
		}

		@Override
		public Integer next() {
			if (closed.get()) {
				throw new NoSuchElementException("iteration closed");
			}
			return 1;
		}

		@Override
		public void remove() {
			throw new UnsupportedOperationException();
		}

		@Override
		public void close() {
			closed.set(true);
		}
	}
}
