# extract all persons that have a given age

PREFIX : <http://namespace1.org/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>  

SELECT ?person ?author WHERE
{
  ?person a foaf:Person .
  ?author owl:sameAs ?person .
  FILTER (str(?person) = "http://namespace2.org/Person_7")
} 