# test for join order optimizer to re-order bound type

PREFIX ns3: <http://namespace3.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

SELECT ?project ?label WHERE {
 BIND(ns3:Project AS ?type)
 ?project rdfs:label ?label .
 ?project rdf:type ?type .
}