/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.EmptySet;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.equivalence.CheckOptions;
import org.eclipse.rdf4j.query.algebra.equivalence.EvaluationCase;
import org.eclipse.rdf4j.query.algebra.equivalence.SemanticsTarget;
import org.junit.jupiter.api.Test;

class BoundedCaseGeneratorProfileTest {
	private static final ValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void sparql11GeneratorEmitsOnlyProfileValidCases() {
		assertGeneratedCasesAreValid(SemanticsTarget.SPARQL_1_1);
	}

	@Test
	void sparql12DraftGeneratorEmitsOnlyProfileValidCases() {
		assertGeneratedCasesAreValid(SemanticsTarget.SPARQL_1_2_DRAFT);
	}

	private static void assertGeneratedCasesAreValid(SemanticsTarget target) {
		TripleTerm triple = VF.createTripleTerm(
				VF.createIRI("urn:test:s"),
				VF.createIRI("urn:test:p"),
				VF.createLiteral("o"));
		StatementPattern inputWithRdf12Constant = new StatementPattern(
				Var.of("s"),
				Var.of("p", VF.createIRI("urn:test:p")),
				Var.of("triple", triple));
		CheckOptions options = CheckOptions.builder()
				.semanticsTarget(target)
				.boundedCounterexampleSearch(true)
				.maxDatasetSize(1)
				.maxEvaluationCases(32)
				.build();
		List<EvaluationCase> cases = new BoundedCaseGenerator(options).generate(
				inputWithRdf12Constant,
				new EmptySet());
		SemanticsValidator validator = new SemanticsValidator();

		assertFalse(cases.isEmpty());
		for (EvaluationCase evaluationCase : cases) {
			assertTrue(
					validator.validate(evaluationCase, target).isSupported(),
					() -> evaluationCase.getLabel() + " contains a value outside " + target);
			if (target == SemanticsTarget.SPARQL_1_1) {
				evaluationCase.getStatements().forEach(statement -> {
					assertFalse(SparqlValueFeatures.usesSparql12(statement.getSubject()));
					assertFalse(SparqlValueFeatures.usesSparql12(statement.getPredicate()));
					assertFalse(SparqlValueFeatures.usesSparql12(statement.getObject()));
					assertFalse(SparqlValueFeatures.usesSparql12(statement.getContext()));
				});
			}
		}
	}
}
