/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.equivalence.AlgebraEquivalenceChecker;
import org.eclipse.rdf4j.query.algebra.equivalence.EquivalenceResult;
import org.eclipse.rdf4j.query.algebra.equivalence.EquivalenceStatus;
import org.eclipse.rdf4j.query.algebra.json.TupleExprJsonParser;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * Manifest-driven pinned repros promoted from fuzz artifacts. Each manifest row names a pair of JSON trees under
 * {@code fuzz-regressions/} and the verdict the checker must produce; every pair must also survive {@code check()}
 * without throwing, and the full {@link DifferentialOracle} must accept it again (so a pinned soundness find also
 * guards the runtime agreement it exposed, not just the verdict). To promote a new find: copy the shrunk
 * {@code original.json}/{@code candidate.json} from {@code target/equivalence-fuzz/} into
 * {@code fuzz-regressions/<name>.original.json} etc. and add a manifest row.
 */
class JsonTupleExprFuzzRegressionTest {
	private static final String ROOT = "/org/eclipse/rdf4j/query/algebra/equivalence/internal/fuzz-regressions/";

	@TestFactory
	List<DynamicTest> pinnedFuzzRegressions() throws IOException {
		List<DynamicTest> tests = new ArrayList<>();
		for (String line : manifestLines()) {
			String[] columns = line.split(",", 3);
			String name = columns[0].trim();
			EquivalenceStatus expected = EquivalenceStatus.valueOf(columns[1].trim());
			tests.add(DynamicTest.dynamicTest(name, () -> {
				TupleExpr original = parse(name + ".original.json");
				TupleExpr candidate = parse(name + ".candidate.json");

				EquivalenceResult result = assertDoesNotThrow(
						() -> new AlgebraEquivalenceChecker(FuzzProfile.primary(96).options())
								.check(original, candidate));

				assertEquals(expected, result.getStatus(), result::getReason);

				for (FuzzProfile profile : oracleProfiles()) {
					TreePair pair = new TreePair(name, "fuzz-regressions", 0L, List.of(),
							parse(name + ".original.json"), parse(name + ".candidate.json"),
							TreePair.Expectation.UNSPECIFIED);
					List<FuzzViolation> violations = new DifferentialOracle().judge(pair, profile);
					assertTrue(violations.isEmpty(),
							() -> "pinned pair violates the differential oracle again under " + profile.label() + ": "
									+ violations);
				}
			}));
		}
		assertFalse(tests.isEmpty(), "fuzz-regressions manifest has no entries");
		return tests;
	}

	private static List<FuzzProfile> oracleProfiles() {
		List<FuzzProfile> profiles = new ArrayList<>();
		profiles.add(FuzzProfile.primary(96));
		profiles.addAll(FuzzProfile.secondary(96));
		return profiles;
	}

	private List<String> manifestLines() throws IOException {
		try (InputStream input = getClass().getResourceAsStream(ROOT + "manifest.csv")) {
			assertTrue(input != null, "missing " + ROOT + "manifest.csv");
			List<String> rows = new ArrayList<>();
			for (String line : new String(input.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
				String trimmed = line.trim();
				if (!trimmed.isEmpty() && !trimmed.startsWith("name,")) {
					rows.add(trimmed);
				}
			}
			return rows;
		}
	}

	private TupleExpr parse(String resourceName) throws IOException {
		try (InputStream input = getClass().getResourceAsStream(ROOT + resourceName)) {
			assertTrue(input != null, "missing " + ROOT + resourceName);
			return new TupleExprJsonParser().parse(input);
		}
	}
}
