/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.Set;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Distinct;
import org.eclipse.rdf4j.query.algebra.EmptySet;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.Reduced;
import org.eclipse.rdf4j.query.algebra.SingletonSet;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.query.impl.ListBindingSet;

/** Generates pairs shaped exactly like the proof kernel's algebraic laws. */
final class RuleLawPairSource {
	static final int PAIRS_PER_ITERATION = 26;

	private final RandomTreeGenerator generator;
	private final boolean edgeOperands;

	RuleLawPairSource() {
		this(5, 25, true);
	}

	RuleLawPairSource(int maxDepth, int nodeBudget, boolean edgeOperands) {
		this.generator = new RandomTreeGenerator(maxDepth, nodeBudget);
		this.edgeOperands = edgeOperands;
	}

	List<TreePair> pairs(long seed, int iterations) {
		List<TreePair> result = new ArrayList<>(iterations * PAIRS_PER_ITERATION + 2);
		for (int i = 0; i < iterations; i++) {
			long pairSeed = seed + i;
			TupleExpr a = generated(pairSeed * 3 + 1, i % 4 == 0);
			TupleExpr b = generated(pairSeed * 3 + 2, i % 5 == 0);
			TupleExpr c = generated(pairSeed * 3 + 3, i % 6 == 0);
			ValueExpr condition = condition(pairSeed);

			add(result, i, pairSeed, "join-commute",
					new Join(a.clone(), b.clone()),
					new Join(b.clone(), a.clone()));
			add(result, i, pairSeed, "join-associate",
					new Join(new Join(a.clone(), b.clone()), c.clone()),
					new Join(a.clone(), new Join(b.clone(), c.clone())));
			add(result, i, pairSeed, "join-unit-right",
					new Join(a.clone(), new SingletonSet()), a.clone());
			add(result, i, pairSeed, "join-empty-right",
					new Join(a.clone(), new EmptySet()), new EmptySet());

			add(result, i, pairSeed, "union-commute",
					new Union(a.clone(), b.clone()),
					new Union(b.clone(), a.clone()));
			add(result, i, pairSeed, "union-associate",
					new Union(new Union(a.clone(), b.clone()), c.clone()),
					new Union(a.clone(), new Union(b.clone(), c.clone())));
			add(result, i, pairSeed, "union-empty-right",
					new Union(a.clone(), new EmptySet()), a.clone());
			add(result, i, pairSeed, "union-idempotent-set",
					new Union(a.clone(), a.clone()), a.clone());

			add(result, i, pairSeed, "filter-union-distribute",
					new Filter(new Union(a.clone(), b.clone()), condition.clone()),
					new Union(
							new Filter(a.clone(), condition.clone()),
							new Filter(b.clone(), condition.clone())));
			add(result, i, pairSeed, "filter-join-left",
					new Filter(new Join(a.clone(), b.clone()), condition.clone()),
					new Join(new Filter(a.clone(), condition.clone()), b.clone()));
			add(result, i, pairSeed, "filter-join-right",
					new Filter(new Join(a.clone(), b.clone()), condition.clone()),
					new Join(a.clone(), new Filter(b.clone(), condition.clone())));
			add(result, i, pairSeed, "filter-true",
					new Filter(a.clone(), new ValueConstant(FuzzVocabulary.VF.createLiteral(true))), a.clone());
			add(result, i, pairSeed, "filter-false",
					new Filter(a.clone(), new ValueConstant(FuzzVocabulary.VF.createLiteral(false))), new EmptySet());

			add(result, i, pairSeed, "leftjoin-empty-left",
					new LeftJoin(new EmptySet(), a.clone(), condition.clone()), new EmptySet());
			add(result, i, pairSeed, "leftjoin-empty-right",
					new LeftJoin(a.clone(), new EmptySet(), condition.clone()), a.clone());
			add(result, i, pairSeed, "leftjoin-unit-right",
					new LeftJoin(a.clone(), new SingletonSet(), condition.clone()), a.clone());
			add(result, i, pairSeed, "leftjoin-left-union-distribute",
					new LeftJoin(new Union(a.clone(), b.clone()), c.clone(), condition.clone()),
					new Union(
							new LeftJoin(a.clone(), c.clone(), condition.clone()),
							new LeftJoin(b.clone(), c.clone(), condition.clone())));

			add(result, i, pairSeed, "minus-empty-left",
					new Difference(new EmptySet(), a.clone()), new EmptySet());
			add(result, i, pairSeed, "minus-empty-right",
					new Difference(a.clone(), new EmptySet()), a.clone());
			add(result, i, pairSeed, "minus-unit-right",
					new Difference(a.clone(), new SingletonSet()), a.clone());
			add(result, i, pairSeed, "minus-left-union-distribute",
					new Difference(new Union(a.clone(), b.clone()), c.clone()),
					new Union(
							new Difference(a.clone(), c.clone()),
							new Difference(b.clone(), c.clone())));
			add(result, i, pairSeed, "minus-right-union-chain",
					new Difference(a.clone(), new Union(b.clone(), c.clone())),
					new Difference(new Difference(a.clone(), b.clone()), c.clone()));
			add(result, i, pairSeed, "minus-chain-reorder",
					new Difference(new Difference(a.clone(), b.clone()), c.clone()),
					new Difference(new Difference(a.clone(), c.clone()), b.clone()));

			add(result, i, pairSeed, "distinct-idempotent",
					new Distinct(new Distinct(a.clone())), new Distinct(a.clone()));
			add(result, i, pairSeed, "distinct-hidden-by-set",
					new Distinct(a.clone()), a.clone());
			add(result, i, pairSeed, "reduced-hidden-by-set",
					new Reduced(a.clone()), a.clone());
		}

		add(result, iterations, seed, "values-empty", emptyValues(), new EmptySet());
		add(result, iterations, seed, "values-unit", unitValues(), new SingletonSet());
		return result;
	}

	private TupleExpr generated(long seed, boolean requestPhysicalOrder) {
		TupleExpr expression = edgeOperands ? edgeExpression(seed) : generator.generate(seed);
		if (expression instanceof QueryRoot root) {
			expression = root.getArg().clone();
		}
		if (requestPhysicalOrder) {
			List<StatementPattern> patterns = MutatorLibrary.collect(expression, StatementPattern.class);
			if (!patterns.isEmpty()) {
				StatementPattern pattern = patterns.get(0);
				pattern.setOrder(pattern.getSubjectVar());
			}
		}
		return expression;
	}

	private TupleExpr edgeExpression(long seed) {
		return switch (Math.floorMod(seed, 9)) {
		case 0 -> repeatedVariablePattern(seed);
		case 1 -> contextPattern(seed, StatementPattern.Scope.NAMED_CONTEXTS);
		case 2 -> contextPattern(seed, StatementPattern.Scope.DEFAULT_CONTEXTS);
		case 3 -> valuedNonConstantPattern(seed);
		case 4 -> valuesWithUndef(seed);
		default -> generator.generate(seed);
		};
	}

	private static StatementPattern repeatedVariablePattern(long seed) {
		Random random = new Random(seed);
		return new StatementPattern(
				Var.of("v0"),
				FuzzVocabulary.constant(FuzzVocabulary.predicate(random)),
				Var.of("v0"));
	}

	private static StatementPattern contextPattern(long seed, StatementPattern.Scope scope) {
		Random random = new Random(seed);
		return new StatementPattern(
				scope,
				Var.of("v0"),
				FuzzVocabulary.constant(FuzzVocabulary.predicate(random)),
				Var.of("v1"),
				Var.of("v2"));
	}

	private static StatementPattern valuedNonConstantPattern(long seed) {
		Random random = new Random(seed);
		return new StatementPattern(
				Var.of("v0", FuzzVocabulary.S1, false, false, false),
				FuzzVocabulary.constant(FuzzVocabulary.predicate(random)),
				Var.of("v1"));
	}

	private static BindingSetAssignment valuesWithUndef(long seed) {
		Random random = new Random(seed);
		List<String> names = List.of("v0", "v1");
		List<Value> values = Arrays.asList(FuzzVocabulary.value(random), null);
		BindingSet row = new ListBindingSet(names, values);
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.copyOf(names));
		assignment.setBindingSets(List.of(row));
		return assignment;
	}

	private static ValueExpr condition(long seed) {
		Random random = new Random(seed * 17 + 11);
		return new Compare(
				FuzzVocabulary.variable(random),
				new ValueConstant(FuzzVocabulary.value(random)),
				random.nextBoolean() ? Compare.CompareOp.EQ : Compare.CompareOp.GT);
	}

	private static BindingSetAssignment emptyValues() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.of("v0"));
		assignment.setBindingSets(List.of());
		return assignment;
	}

	private static BindingSetAssignment unitValues() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.of("v0"));
		assignment.setBindingSets(List.of(EmptyBindingSet.getInstance()));
		return assignment;
	}

	private static void add(
			List<TreePair> result,
			int iteration,
			long seed,
			String law,
			TupleExpr original,
			TupleExpr candidate) {
		result.add(new TreePair(
				"law-" + iteration + "-" + law,
				"rule-law",
				seed,
				List.of(law),
				original,
				candidate,
				TreePair.Expectation.UNSPECIFIED));
	}
}
