/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.ArbitraryLengthPath;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.FunctionCall;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.Lateral;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.SingletonSet;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.equivalence.AlgebraEquivalenceChecker;
import org.eclipse.rdf4j.query.algebra.equivalence.CheckOptions;
import org.eclipse.rdf4j.query.algebra.equivalence.ContextMode;
import org.eclipse.rdf4j.query.algebra.equivalence.EquivalenceResult;
import org.eclipse.rdf4j.query.algebra.equivalence.EvaluationCase;
import org.eclipse.rdf4j.query.algebra.equivalence.EvaluationOutcome;
import org.eclipse.rdf4j.query.algebra.equivalence.ObservationMode;
import org.eclipse.rdf4j.query.algebra.evaluation.function.Function;
import org.eclipse.rdf4j.query.algebra.evaluation.function.FunctionRegistry;
import org.eclipse.rdf4j.query.impl.MapBindingSet;
import org.eclipse.rdf4j.query.impl.SimpleDataset;
import org.junit.jupiter.api.Test;

class RuntimeEquivalenceDifferentialTest {
	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI P1 = VF.createIRI("urn:test:p1");
	private static final IRI P2 = VF.createIRI("urn:test:p2");
	private static final IRI P3 = VF.createIRI("urn:test:p3");
	private static final Resource SUBJECT = VF.createIRI("urn:test:subject");
	private static final IRI GRAPH_1 = VF.createIRI("urn:test:g1");
	private static final IRI GRAPH_2 = VF.createIRI("urn:test:g2");
	private static final String INVOCATION_SENSITIVE_FILTER = "urn:test:invocation-sensitive-filter";

	@Test
	void setObservationPreservesCallsToInvocationSensitiveFilters() {
		InvocationSensitiveBooleanFunction function = new InvocationSensitiveBooleanFunction();
		withFunction(function, () -> {
			TupleExpr duplicateInput = new Filter(repeatedValues(2), new FunctionCall(function.getURI()));
			TupleExpr singleInput = new Filter(repeatedValues(1), new FunctionCall(function.getURI()));

			function.reset();
			EvaluationOutcome duplicateOutcome = evaluate(duplicateInput);
			function.reset();
			EvaluationOutcome singleOutcome = evaluate(singleInput);
			assertFalse(
					duplicateOutcome.sameAs(singleOutcome, ObservationMode.SET),
					() -> "invocation-sensitive filters produced the same SET outcome: " + duplicateOutcome);

			CheckOptions options = CheckOptions.builder()
					.observationMode(ObservationMode.SET)
					.boundedCounterexampleSearch(false)
					.build();
			EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(duplicateInput, singleInput);

			assertFalse(proof.isEquivalent(), proof::getReason);
		});
	}

	@Test
	void setObservationPreservesCallsToInvocationSensitiveLeftJoinConditions() {
		InvocationSensitiveBooleanFunction function = new InvocationSensitiveBooleanFunction();
		withFunction(function, () -> {
			TupleExpr duplicateInput = new LeftJoin(
					repeatedValues(2),
					repeatedValues("y", 1),
					new FunctionCall(function.getURI()));
			TupleExpr singleInput = new LeftJoin(
					repeatedValues(1),
					repeatedValues("y", 1),
					new FunctionCall(function.getURI()));

			function.reset();
			EvaluationOutcome duplicateOutcome = evaluate(duplicateInput);
			function.reset();
			EvaluationOutcome singleOutcome = evaluate(singleInput);
			assertFalse(
					duplicateOutcome.sameAs(singleOutcome, ObservationMode.SET),
					() -> "invocation-sensitive OPTIONAL conditions produced the same SET outcome: "
							+ duplicateOutcome);

			CheckOptions options = CheckOptions.builder()
					.observationMode(ObservationMode.SET)
					.boundedCounterexampleSearch(false)
					.build();
			EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(duplicateInput, singleInput);

			assertFalse(proof.isEquivalent(), proof::getReason);
		});
	}

	@Test
	void setObservationPreservesPerLeftJoinRightEvaluations() {
		InvocationSensitiveBooleanFunction function = new InvocationSensitiveBooleanFunction();
		withFunction(function, () -> assertSetObservesInvocationSchedule(
				function,
				new Join(repeatedValues(2), invocationSensitiveFilter(function)),
				new Join(repeatedValues(1), invocationSensitiveFilter(function))));
	}

	@Test
	void setObservationPreservesPerLeftOptionalRightEvaluations() {
		InvocationSensitiveBooleanFunction function = new InvocationSensitiveBooleanFunction();
		withFunction(function, () -> assertSetObservesInvocationSchedule(
				function,
				new LeftJoin(repeatedValues(2), invocationSensitiveFilter(function)),
				new LeftJoin(repeatedValues(1), invocationSensitiveFilter(function))));
	}

	@Test
	void setObservationPreservesPerLeftLateralRightEvaluations() {
		InvocationSensitiveBooleanFunction function = new InvocationSensitiveBooleanFunction();
		withFunction(function, () -> assertSetObservesInvocationSchedule(
				function,
				new Lateral(repeatedValues(2), invocationSensitiveFilter(function), Set.of("x")),
				new Lateral(repeatedValues(1), invocationSensitiveFilter(function), Set.of("x"))));
	}

	@Test
	void structuralEqualityDoesNotIgnoreArbitraryLengthPathMinimumLength() {
		TupleExpr zeroOrMore = fixedSelfPath(0);
		TupleExpr oneOrMore = fixedSelfPath(1);

		EvaluationOutcome zeroOrMoreOutcome = evaluate(zeroOrMore);
		EvaluationOutcome oneOrMoreOutcome = evaluate(oneOrMore);

		// On an empty graph, a zero-length path from a fixed term to itself
		// succeeds once. Requiring at least one edge produces no result.
		assertFalse(zeroOrMoreOutcome.isEmpty(), zeroOrMoreOutcome::toString);
		assertTrue(oneOrMoreOutcome.isEmpty(), oneOrMoreOutcome::toString);
		assertFalse(
				zeroOrMoreOutcome.sameAs(oneOrMoreOutcome, ObservationMode.BAG),
				() -> "different minimum path lengths unexpectedly agreed: "
						+ zeroOrMoreOutcome + " versus " + oneOrMoreOutcome);

		EquivalenceResult proof = new AlgebraEquivalenceChecker(
				CheckOptions.builder().boundedCounterexampleSearch(false).build())
						.check(zeroOrMore, oneOrMore);

		// Fails on the submitted code: ArbitraryLengthPath.equals omits minLength,
		// and ExactTreeEquality has no local-semantic check for this node.
		assertFalse(proof.isEquivalent(), () -> "unsound proof: " + proof.getReason());
		assertTrue(proof.isUnknown(), proof::toString);
	}

	@Test
	void runtimeJoinDoesNotCommuteAcrossMinusThatInheritsLeftBindings() {
		TupleExpr valuesFirst = new Join(repeatedValues("x", 1), unitMinusUnit());
		TupleExpr minusFirst = new Join(unitMinusUnit(), repeatedValues("x", 1));

		EvaluationOutcome valuesFirstOutcome = evaluate(valuesFirst);
		EvaluationOutcome minusFirstOutcome = evaluate(minusFirst);

		// With ?x inherited, both singleton mappings contain the same ?x and
		// MINUS removes the left one. At top level both mappings are empty, share
		// no variable, and MINUS keeps the left one.
		assertTrue(valuesFirstOutcome.isEmpty(), valuesFirstOutcome::toString);
		assertFalse(minusFirstOutcome.isEmpty(), minusFirstOutcome::toString);
		assertFalse(
				valuesFirstOutcome.sameAs(minusFirstOutcome, ObservationMode.BAG),
				() -> "directional join plans unexpectedly agreed: "
						+ valuesFirstOutcome + " versus " + minusFirstOutcome);

		CheckOptions options = CheckOptions.builder()
				.contextMode(ContextMode.ALL_BINDINGS)
				.boundedCounterexampleSearch(false)
				.build();
		EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(valuesFirst, minusFirst);

		// Fails on the submitted code: the checker returns EQUIVALENT.
		assertFalse(proof.isEquivalent(), () -> "unsound proof: " + proof.getReason());
	}

	@Test
	void topLevelEmptyContextDoesNotLeakIntoJoinRightOperand() {
		TupleExpr left = repeatedValues(1);
		TupleExpr original = new Join(
				left.clone(),
				new Difference(new SingletonSet(), new SingletonSet()));
		TupleExpr candidate = new Join(left.clone(), new SingletonSet());

		EvaluationOutcome originalOutcome = evaluate(original);
		EvaluationOutcome candidateOutcome = evaluate(candidate);
		assertFalse(
				originalOutcome.sameAs(candidateOutcome, ObservationMode.BAG),
				() -> "directional join operands produced the same BAG outcome: " + originalOutcome);

		CheckOptions options = CheckOptions.builder()
				.contextMode(ContextMode.TOP_LEVEL_EMPTY)
				.boundedCounterexampleSearch(false)
				.build();
		EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(original, candidate);

		assertFalse(proof.isEquivalent(), proof::getReason);
	}

	@Test
	void topLevelEmptyContextDoesNotLeakIntoLeftJoinRightOperand() {
		TupleExpr left = repeatedValues(1);
		TupleExpr original = new LeftJoin(
				left.clone(),
				new Join(
						new Difference(new SingletonSet(), new SingletonSet()),
						repeatedValues("y", 1)));
		TupleExpr candidate = new LeftJoin(left.clone(), repeatedValues("y", 1));

		EvaluationOutcome originalOutcome = evaluate(original);
		EvaluationOutcome candidateOutcome = evaluate(candidate);
		assertFalse(
				originalOutcome.sameAs(candidateOutcome, ObservationMode.BAG),
				() -> "directional OPTIONAL operands produced the same BAG outcome: " + originalOutcome);

		CheckOptions options = CheckOptions.builder()
				.contextMode(ContextMode.TOP_LEVEL_EMPTY)
				.boundedCounterexampleSearch(false)
				.build();
		EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(original, candidate);

		assertFalse(proof.isEquivalent(), proof::getReason);
	}

	@Test
	void everyTopLevelEmptyProofAgreesAcrossContextSensitivePlans() {
		List<NamedPlan> plans = contextSensitivePlans();
		List<EvaluationOutcome> outcomes = new ArrayList<>(plans.size());
		for (NamedPlan plan : plans) {
			outcomes.add(evaluate(plan.expression()));
		}
		CheckOptions options = CheckOptions.builder()
				.contextMode(ContextMode.TOP_LEVEL_EMPTY)
				.boundedCounterexampleSearch(false)
				.build();
		AlgebraEquivalenceChecker checker = new AlgebraEquivalenceChecker(options);

		for (int left = 0; left < plans.size(); left++) {
			for (int right = left + 1; right < plans.size(); right++) {
				NamedPlan leftPlan = plans.get(left);
				NamedPlan rightPlan = plans.get(right);
				EquivalenceResult proof = checker.check(leftPlan.expression(), rightPlan.expression());
				if (proof.isEquivalent()) {
					EvaluationOutcome leftOutcome = outcomes.get(left);
					EvaluationOutcome rightOutcome = outcomes.get(right);
					assertTrue(
							leftOutcome.sameAs(rightOutcome, ObservationMode.BAG),
							() -> leftPlan.label() + " and " + rightPlan.label()
									+ " were proved equivalent but evaluate as "
									+ leftOutcome + " and " + rightOutcome);
				}
			}
		}
	}

	@Test
	void everyProvedRuntimePairAgreesAcrossExactEvaluationMatrix() {
		AlgebraEquivalenceChecker checker = new AlgebraEquivalenceChecker();
		Rdf4jEvaluator evaluator = new Rdf4jEvaluator();
		List<EvaluationCase> matrix = evaluationMatrix();

		for (EquivalentPair pair : equivalentPairs()) {
			EquivalenceResult proof = checker.check(pair.original(), pair.candidate());
			assertTrue(proof.isEquivalent(), () -> pair.label() + ": " + proof.getReason());
			for (EvaluationCase evaluationCase : matrix) {
				EvaluationAttempt originalAttempt = evaluator.evaluate(pair.original(), evaluationCase, 10_000);
				EvaluationAttempt candidateAttempt = evaluator.evaluate(pair.candidate(), evaluationCase, 10_000);
				assertTrue(originalAttempt.isComplete(),
						pair.label() + " original incomplete on " + evaluationCase.getLabel());
				assertTrue(candidateAttempt.isComplete(),
						pair.label() + " candidate incomplete on " + evaluationCase.getLabel());
				EvaluationOutcome original = originalAttempt.getOutcome().orElseThrow();
				EvaluationOutcome candidate = candidateAttempt.getOutcome().orElseThrow();
				assertFalse(original.hasError(), pair.label() + " original errored on " + evaluationCase.getLabel());
				assertFalse(candidate.hasError(), pair.label() + " candidate errored on " + evaluationCase.getLabel());
				assertTrue(
						original.sameAs(candidate, ObservationMode.BAG),
						() -> pair.label() + " differs on " + evaluationCase.getLabel()
								+ ": " + original + " versus " + candidate);
			}
		}
	}

	private static List<EquivalentPair> equivalentPairs() {
		StatementPattern a = pattern(P1, "x");
		StatementPattern b = pattern(P2, "y");
		StatementPattern c = pattern(P3, "z");
		Compare condition = new Compare(
				Var.of("x"),
				new ValueConstant(VF.createIRI("urn:test:object")),
				Compare.CompareOp.EQ);
		List<EquivalentPair> result = new ArrayList<>();
		result.add(new EquivalentPair(
				"structural clone",
				a.clone(),
				a.clone()));
		result.add(new EquivalentPair(
				"independent join order",
				new Join(a.clone(), b.clone()),
				new Join(b.clone(), a.clone())));
		result.add(new EquivalentPair(
				"bag union order",
				new Union(a.clone(), b.clone()),
				new Union(b.clone(), a.clone())));
		result.add(new EquivalentPair(
				"stable filter pushdown",
				new Filter(new Join(a.clone(), b.clone()), condition.clone()),
				new Join(new Filter(a.clone(), condition.clone()), b.clone())));
		result.add(new EquivalentPair(
				"left join distribution",
				new LeftJoin(new Union(a.clone(), b.clone()), c.clone()),
				new Union(new LeftJoin(a.clone(), c.clone()), new LeftJoin(b.clone(), c.clone()))));
		result.add(new EquivalentPair(
				"minus right union chain",
				new Difference(a.clone(), new Union(b.clone(), c.clone())),
				new Difference(new Difference(a.clone(), b.clone()), c.clone())));
		result.add(new EquivalentPair(
				"join unit",
				new Join(a.clone(), new SingletonSet()),
				a.clone()));
		return result;
	}

	private static List<EvaluationCase> evaluationMatrix() {
		IRI object = VF.createIRI("urn:test:object");
		List<EvaluationCase> result = new ArrayList<>();
		result.add(EvaluationCase.builder("empty dataset").build());
		result.add(EvaluationCase.builder("default graph with duplicate-producing mappings")
				.addStatement(VF.createStatement(SUBJECT, P1, object))
				.addStatement(VF.createStatement(SUBJECT, P2, object))
				.addStatement(VF.createStatement(SUBJECT, P3, VF.createLiteral("third")))
				.build());

		SimpleDataset namedAsDefault = new SimpleDataset();
		namedAsDefault.addDefaultGraph(GRAPH_1);
		namedAsDefault.addDefaultGraph(GRAPH_2);
		result.add(EvaluationCase.builder("two named graphs merged as default")
				.dataset(namedAsDefault)
				.addStatement(VF.createStatement(SUBJECT, P1, object, GRAPH_1))
				.addStatement(VF.createStatement(SUBJECT, P2, object, GRAPH_2))
				.build());

		SimpleDataset namedOnly = new SimpleDataset();
		namedOnly.addNamedGraph(GRAPH_1);
		result.add(EvaluationCase.builder("named graph only")
				.dataset(namedOnly)
				.addStatement(VF.createStatement(SUBJECT, P1, object, GRAPH_1))
				.build());

		MapBindingSet subjectBinding = new MapBindingSet();
		subjectBinding.setBinding("s", SUBJECT);
		result.add(EvaluationCase.builder("incoming subject binding")
				.initialBindings(subjectBinding)
				.addStatement(VF.createStatement(SUBJECT, P1, object))
				.addStatement(VF.createStatement(SUBJECT, P2, object))
				.build());

		MapBindingSet partialBinding = new MapBindingSet();
		partialBinding.setBinding("x", object);
		result.add(EvaluationCase.builder("partial object mapping")
				.initialBindings(partialBinding)
				.addStatement(VF.createStatement(SUBJECT, P1, object))
				.addStatement(VF.createStatement(SUBJECT, P2, object))
				.build());

		TripleTerm triple = VF.createTripleTerm(SUBJECT, P1, object);
		result.add(EvaluationCase.builder("RDF 1.2 terms")
				.addStatement(VF.createStatement(SUBJECT, P1, triple))
				.addStatement(VF.createStatement(
						SUBJECT,
						P2,
						VF.createLiteral("directional", "en", org.eclipse.rdf4j.model.Literal.BaseDirection.RTL)))
				.build());
		return result;
	}

	private static StatementPattern pattern(IRI predicate, String objectName) {
		return new StatementPattern(
				Var.of("s"),
				Var.of("const-" + predicate.stringValue(), predicate),
				Var.of(objectName));
	}

	private static BindingSetAssignment repeatedValues(int rowCount) {
		return repeatedValues("x", rowCount);
	}

	private static BindingSetAssignment repeatedValues(String bindingName, int rowCount) {
		List<BindingSet> rows = new ArrayList<>(rowCount);
		for (int i = 0; i < rowCount; i++) {
			MapBindingSet row = new MapBindingSet();
			row.setBinding(bindingName, VF.createLiteral("value"));
			rows.add(row);
		}
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.of(bindingName));
		assignment.setBindingSets(rows);
		return assignment;
	}

	private static List<NamedPlan> contextSensitivePlans() {
		return List.of(
				new NamedPlan("unit", new SingletonSet()),
				new NamedPlan("values x", repeatedValues(1)),
				new NamedPlan("unit minus unit", unitMinusUnit()),
				new NamedPlan("values x minus unit", new Difference(repeatedValues(1), new SingletonSet())),
				new NamedPlan("minus then values", new Join(unitMinusUnit(), repeatedValues(1))),
				new NamedPlan("values then minus", new Join(repeatedValues(1), unitMinusUnit())),
				new NamedPlan(
						"left-associated productive join",
						new Join(new Join(unitMinusUnit(), repeatedValues(1)), repeatedValues("y", 1))),
				new NamedPlan(
						"right-associated productive join",
						new Join(unitMinusUnit(), new Join(repeatedValues(1), repeatedValues("y", 1)))),
				new NamedPlan(
						"left-associated blocked join",
						new Join(new Join(repeatedValues(1), unitMinusUnit()), repeatedValues("y", 1))),
				new NamedPlan(
						"right-associated blocked join",
						new Join(repeatedValues(1), new Join(unitMinusUnit(), repeatedValues("y", 1)))),
				new NamedPlan(
						"optional with contextual right",
						new LeftJoin(
								repeatedValues(1),
								new Join(unitMinusUnit(), repeatedValues("y", 1)))),
				new NamedPlan(
						"optional with values right",
						new LeftJoin(repeatedValues(1), repeatedValues("y", 1))));
	}

	private static ArbitraryLengthPath fixedSelfPath(long minLength) {
		Var start = Var.of("path-start", SUBJECT);
		Var end = Var.of("path-end", SUBJECT);
		StatementPattern step = new StatementPattern(
				start.clone(),
				Var.of("path-predicate", P1),
				end.clone());
		return new ArbitraryLengthPath(start, step, end, minLength);
	}

	private static Difference unitMinusUnit() {
		return new Difference(new SingletonSet(), new SingletonSet());
	}

	private static EvaluationOutcome evaluate(TupleExpr expression) {
		EvaluationAttempt attempt = new Rdf4jEvaluator()
				.evaluate(expression, EvaluationCase.builder("empty dataset").build(), 10);
		assertTrue(attempt.isComplete(), attempt::getIncompleteReason);
		EvaluationOutcome outcome = attempt.getOutcome().orElseThrow();
		assertFalse(outcome.hasError(), outcome::toString);
		return outcome;
	}

	private static Filter invocationSensitiveFilter(Function function) {
		return new Filter(repeatedValues("y", 1), new FunctionCall(function.getURI()));
	}

	private static void assertSetObservesInvocationSchedule(
			InvocationSensitiveBooleanFunction function,
			TupleExpr duplicateInput,
			TupleExpr singleInput) {
		function.reset();
		EvaluationOutcome duplicateOutcome = evaluate(duplicateInput);
		function.reset();
		EvaluationOutcome singleOutcome = evaluate(singleInput);
		assertFalse(
				duplicateOutcome.sameAs(singleOutcome, ObservationMode.SET),
				() -> "per-left evaluations produced the same SET outcome: " + duplicateOutcome);

		CheckOptions options = CheckOptions.builder()
				.observationMode(ObservationMode.SET)
				.boundedCounterexampleSearch(false)
				.build();
		EquivalenceResult proof = new AlgebraEquivalenceChecker(options).check(duplicateInput, singleInput);
		assertFalse(proof.isEquivalent(), proof::getReason);
	}

	private static void withFunction(Function function, Runnable action) {
		FunctionRegistry registry = FunctionRegistry.getInstance();
		Optional<Function> previous = registry.add(function);
		try {
			action.run();
		} finally {
			registry.remove(function);
			previous.ifPresent(registry::add);
		}
	}

	private static final class InvocationSensitiveBooleanFunction implements Function {
		private int invocationCount;

		@Override
		public String getURI() {
			return INVOCATION_SENSITIVE_FILTER;
		}

		@Override
		@SuppressWarnings("deprecation")
		public Value evaluate(ValueFactory valueFactory, Value... args) {
			return valueFactory.createLiteral(invocationCount++);
		}

		@Override
		public boolean mustReturnDifferentResult() {
			return true;
		}

		private void reset() {
			invocationCount = 0;
		}
	}

	private record EquivalentPair(String label, TupleExpr original, TupleExpr candidate) {
	}

	private record NamedPlan(String label, TupleExpr expression) {
	}
}
