/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.workbench.commands;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.base.RepositoryConnectionWrapper;
import org.eclipse.rdf4j.repository.base.RepositoryWrapper;
import org.eclipse.rdf4j.repository.manager.RepositoryManager;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.memory.MemoryStore;
import org.eclipse.rdf4j.workbench.support.TestServletConfig;
import org.eclipse.rdf4j.workbench.util.WorkbenchPageProtocol;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * The Clear page (plan task M6.4, mockup 08) lists what can be cleared: every graph and the default graph with their
 * statement counts, and the repository size.
 */
class ClearServletPageDataTest {

	private static final ObjectMapper JSON_MAPPER = new ObjectMapper();

	private static final String NS = "urn:test:";

	private final CountDownLatch slowCounts = new CountDownLatch(1);

	private Repository store;

	@BeforeEach
	void setUp() {
		store = new SailRepository(new MemoryStore());
		store.init();
		ValueFactory vf = store.getValueFactory();
		try (RepositoryConnection connection = store.getConnection()) {
			for (int index = 0; index < 3; index++) {
				connection.add(vf.createIRI(NS + "s" + index), vf.createIRI(NS + "p"), vf.createLiteral(index),
						vf.createIRI(NS + "graph/b"));
			}
			connection.add(vf.createIRI(NS + "s"), vf.createIRI(NS + "p"), vf.createLiteral("a"),
					vf.createIRI(NS + "graph/a"));
			connection.add(vf.createIRI(NS + "s"), vf.createIRI(NS + "p"), vf.createLiteral("default"));
		}
	}

	@AfterEach
	void tearDown() {
		slowCounts.countDown();
		store.shutDown();
	}

	@Test
	void pageDataListsEveryGraphWithItsCountAndTheRepositorySize() throws Exception {
		List<JsonNode> records = run(store);

		assertThat(vars(records)).containsExactly("context", "statements");
		assertThat(column(records, 0)).containsExactly(NS + "graph/a", NS + "graph/b", null);
		assertThat(column(records, 1)).containsExactly("1", "3", "1");
		assertThat(metadata(records).path("repository-size").asLong()).isEqualTo(5);
	}

	@Test
	void countsThatTakeLongerThanTheBudgetAreLeftEmpty() throws Exception {
		List<JsonNode> records = run(slowCountingStore());

		assertThat(slowCounts.getCount()).as("the response did not wait for the counts").isEqualTo(1);
		assertThat(column(records, 0)).containsExactly(NS + "graph/a", NS + "graph/b", null);
		assertThat(column(records, 1)).containsOnlyNulls();
		assertThat(metadata(records).has("repository-size")).isFalse();
	}

	private List<JsonNode> run(Repository repository) throws Exception {
		ClearServlet servlet = new ClearServlet();
		servlet.setRepository(repository);
		servlet.setRepositoryManager(mock(RepositoryManager.class));
		servlet.init(TestServletConfig.withParams("clear", "cookie-max-age", "300"));
		try {
			MockHttpServletRequest request = new MockHttpServletRequest("GET", "/clear");
			request.addHeader("Accept", WorkbenchPageProtocol.ACCEPT);
			MockHttpServletResponse response = new MockHttpServletResponse();
			servlet.service(request, response);
			return response.getContentAsString().lines().map(ClearServletPageDataTest::readTree).toList();
		} finally {
			servlet.destroy();
		}
	}

	/** A store whose statement sizes wait until the test ends. */
	private Repository slowCountingStore() {
		return new RepositoryWrapper(store) {
			@Override
			public RepositoryConnection getConnection() throws RepositoryException {
				return new RepositoryConnectionWrapper(this, super.getConnection()) {
					@Override
					public long size(Resource... contexts) throws RepositoryException {
						try {
							slowCounts.await(30, TimeUnit.SECONDS);
						} catch (InterruptedException e) {
							Thread.currentThread().interrupt();
						}
						return super.size(contexts);
					}
				};
			}
		};
	}

	private static JsonNode readTree(String line) {
		try {
			return JSON_MAPPER.readTree(line);
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	}

	private static List<String> vars(List<JsonNode> records) {
		List<String> names = new ArrayList<>();
		records.stream()
				.filter(record -> "vars".equals(record.path("type").asText()))
				.forEach(record -> record.path("values").forEach(name -> names.add(name.asText())));
		return names;
	}

	private static JsonNode metadata(List<JsonNode> records) {
		return records.stream()
				.filter(record -> "metadata".equals(record.path("type").asText()))
				.map(record -> record.path("values"))
				.findFirst()
				.orElse(JSON_MAPPER.createObjectNode());
	}

	private static List<String> column(List<JsonNode> records, int index) {
		List<String> values = new ArrayList<>();
		for (JsonNode record : records) {
			if ("rows".equals(record.path("type").asText())) {
				record.path("values").forEach(row -> {
					JsonNode term = row.get(index);
					values.add(term == null || term.isNull() ? null : term.path("value").asText());
				});
			}
		}
		return values;
	}
}
