/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.workbench.commands;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.RepositoryResult;
import org.eclipse.rdf4j.repository.base.RepositoryConnectionWrapper;
import org.eclipse.rdf4j.repository.base.RepositoryWrapper;
import org.eclipse.rdf4j.repository.manager.RepositoryManager;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.memory.MemoryStore;
import org.eclipse.rdf4j.workbench.support.TestServletConfig;
import org.eclipse.rdf4j.workbench.util.WorkbenchPageProtocol;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.servlet.ServletException;

/**
 * The Clear page (plan task M6.4, mockup 08) lists what can be cleared: every graph and the default graph. Their
 * statement counts and the repository size are requested separately with {@code counts=true} (plan task M13.2).
 */
class ClearServletPageDataTest {

	private static final ObjectMapper JSON_MAPPER = new ObjectMapper();

	private static final String NS = "urn:test:";

	private final CountDownLatch slowCounts = new CountDownLatch(1);

	private Repository store;

	@BeforeEach
	void setUp() {
		store = new SailRepository(new MemoryStore());
		store.init();
		ValueFactory vf = store.getValueFactory();
		try (RepositoryConnection connection = store.getConnection()) {
			for (int index = 0; index < 3; index++) {
				connection.add(vf.createIRI(NS + "s" + index), vf.createIRI(NS + "p"), vf.createLiteral(index),
						vf.createIRI(NS + "graph/b"));
			}
			connection.add(vf.createIRI(NS + "s"), vf.createIRI(NS + "p"), vf.createLiteral("a"),
					vf.createIRI(NS + "graph/a"));
			connection.add(vf.createIRI(NS + "s"), vf.createIRI(NS + "p"), vf.createLiteral("default"));
		}
	}

	@AfterEach
	void tearDown() {
		slowCounts.countDown();
		store.shutDown();
	}

	@Test
	void pageDataListsEveryGraphAtOnceWithoutCounting() throws Exception {
		long started = System.nanoTime();
		List<JsonNode> records = run(new ClearServlet(), slowCountingStore(null), false);

		assertThat(TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started))
				.as("the page answers without waiting for counts (plan task M13.2)")
				.isLessThan(1000);
		assertThat(vars(records)).containsExactly("context", "statements");
		assertThat(column(records, 0)).containsExactly(NS + "graph/a", NS + "graph/b", null);
		assertThat(column(records, 1)).containsOnlyNulls();
		assertThat(metadata(records).has("repository-size")).isFalse();
		assertThat(metadata(records).path("counts-timed-out").asBoolean()).isFalse();
		assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isTrue();
		assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isFalse();
	}

	@Test
	void countsAreAnsweredOnTheirOwnRequest() throws Exception {
		List<JsonNode> records = run(new ClearServlet(), store, true);

		assertThat(vars(records)).containsExactly("context", "statements");
		assertThat(column(records, 0)).containsExactly(NS + "graph/a", NS + "graph/b", null);
		assertThat(column(records, 1)).containsExactly("1", "3", "1");
		assertThat(metadata(records).path("repository-size").asLong()).isEqualTo(5);
		assertThat(metadata(records).path("counts-timed-out").asBoolean()).isFalse();
		assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isTrue();
		assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isFalse();
		assertThat(metadata(records).path("statement-counts-timed-out").asBoolean()).isFalse();
	}

	@Test
	void countingStopsAfterFiveSecondsAndAnswersTheCountsThatFinished() throws Exception {
		assertThat(ClearServlet.COUNT_BUDGET_MILLIS).isEqualTo(5000);
		long started = System.nanoTime();
		// A shorter budget keeps the test fast; graph/b is the count that does not finish.
		List<JsonNode> records = run(new ClearServlet(300), slowCountingStore(NS + "graph/b"), true);

		assertThat(TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started)).isLessThan(5000);
		assertThat(slowCounts.getCount()).as("the response did not wait for the slow count").isEqualTo(1);
		assertThat(column(records, 0)).containsExactly(NS + "graph/a", NS + "graph/b", null);
		assertThat(column(records, 1)).containsExactly("1", null, "1");
		assertThat(metadata(records).path("repository-size").asLong()).isEqualTo(5);
		assertThat(metadata(records).path("counts-timed-out").asBoolean()).isTrue();
		assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isTrue();
		assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isFalse();
		assertThat(metadata(records).path("statement-counts-timed-out").asBoolean()).isTrue();
	}

	@Test
	void initialContextDiscoveryStopsAtItsOwnBudget() throws Exception {
		assertThat(ClearServlet.CONTEXT_DISCOVERY_BUDGET_MILLIS).isEqualTo(60_000);
		CountDownLatch contextEnumerationStarted = new CountDownLatch(1);
		CountDownLatch allowContextEnumeration = new CountDownLatch(1);
		CountDownLatch discoveryConnectionClosed = new CountDownLatch(1);
		CountDownLatch statementCountStarted = new CountDownLatch(1);
		ExecutorService requestExecutor = Executors.newSingleThreadExecutor();
		try {
			Future<List<JsonNode>> response = requestExecutor.submit(() -> run(new ClearServlet(300, 5000),
					slowContextListingStore(contextEnumerationStarted, allowContextEnumeration,
							discoveryConnectionClosed, statementCountStarted),
					false));
			assertThat(contextEnumerationStarted.await(2, TimeUnit.SECONDS)).isTrue();

			List<JsonNode> records = response.get(2, TimeUnit.SECONDS);

			assertThat(metadata(records).has("counts-timed-out"))
					.as("the initial-list request does not enter the statement-count phase")
					.isFalse();
			assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isFalse();
			assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isTrue();
			assertThat(metadata(records).path("statement-counts-timed-out").asBoolean()).isFalse();
			assertThat(statementCountStarted.getCount())
					.as("an incomplete initial listing does not start unrequested statement counts")
					.isEqualTo(1);
		} finally {
			allowContextEnumeration.countDown();
			requestExecutor.shutdownNow();
		}
		assertThat(discoveryConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
	}

	@Test
	void countRequestDoesNotCountWhenContextDiscoveryTimesOut() throws Exception {
		CountDownLatch contextEnumerationStarted = new CountDownLatch(1);
		CountDownLatch allowContextEnumeration = new CountDownLatch(1);
		CountDownLatch discoveryConnectionClosed = new CountDownLatch(1);
		CountDownLatch statementCountStarted = new CountDownLatch(1);
		ExecutorService requestExecutor = Executors.newSingleThreadExecutor();
		try {
			Future<List<JsonNode>> response = requestExecutor.submit(() -> run(new ClearServlet(300, 5000),
					slowContextListingStore(contextEnumerationStarted, allowContextEnumeration,
							discoveryConnectionClosed, statementCountStarted),
					true));
			assertThat(contextEnumerationStarted.await(2, TimeUnit.SECONDS)).isTrue();

			List<JsonNode> records = response.get(2, TimeUnit.SECONDS);

			assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isFalse();
			assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isTrue();
			assertThat(metadata(records).path("statement-counts-timed-out").asBoolean()).isFalse();
			assertThat(metadata(records).path("counts-timed-out").asBoolean()).isTrue();
			assertThat(metadata(records).has("repository-size")).isFalse();
			assertThat(statementCountStarted.getCount())
					.as("the count phase never starts for an incomplete graph snapshot")
					.isEqualTo(1);
		} finally {
			allowContextEnumeration.countDown();
			requestExecutor.shutdownNow();
		}
		assertThat(discoveryConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
	}

	@Test
	void countDiscoveryBudgetAndStatementCountBudgetAreIndependent() throws Exception {
		CountDownLatch contextEnumerationStarted = new CountDownLatch(1);
		CountDownLatch allowContextEnumeration = new CountDownLatch(1);
		CountDownLatch discoveryConnectionClosed = new CountDownLatch(1);
		CountDownLatch statementCountStarted = new CountDownLatch(1);
		ExecutorService requestExecutor = Executors.newSingleThreadExecutor();
		try {
			Future<List<JsonNode>> response = requestExecutor.submit(() -> run(new ClearServlet(5000, 500),
					slowContextListingStore(contextEnumerationStarted, allowContextEnumeration,
							discoveryConnectionClosed, statementCountStarted),
					true));
			assertThat(contextEnumerationStarted.await(2, TimeUnit.SECONDS)).isTrue();
			assertThat(allowContextEnumeration.await(650, TimeUnit.MILLISECONDS))
					.as("discovery lasts longer than the independent statement-count budget")
					.isFalse();
			allowContextEnumeration.countDown();

			List<JsonNode> records = response.get(2, TimeUnit.SECONDS);

			assertThat(statementCountStarted.getCount()).isZero();
			assertThat(column(records, 1)).containsExactly("1", "3", "1");
			assertThat(metadata(records).path("context-discovery-complete").asBoolean()).isTrue();
			assertThat(metadata(records).path("context-discovery-timed-out").asBoolean()).isFalse();
			assertThat(metadata(records).path("statement-counts-timed-out").asBoolean()).isFalse();
		} finally {
			allowContextEnumeration.countDown();
			requestExecutor.shutdownNow();
		}
		assertThat(discoveryConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
	}

	@Test
	void cancelledRepositoryCountDoesNotStartDefaultCountAfterItClearsInterrupt() throws Exception {
		CountDownLatch repositoryCountStarted = new CountDownLatch(1);
		CountDownLatch repositoryCountInterrupted = new CountDownLatch(1);
		CountDownLatch allowRepositoryCountReturn = new CountDownLatch(1);
		CountDownLatch defaultCountStarted = new CountDownLatch(1);
		CountDownLatch countConnectionClosed = new CountDownLatch(1);

		List<JsonNode> records = run(new ClearServlet(300), repositoryCountThatClearsInterrupt(repositoryCountStarted,
				repositoryCountInterrupted, allowRepositoryCountReturn, defaultCountStarted, countConnectionClosed),
				true);

		try {
			assertThat(metadata(records).path("counts-timed-out").asBoolean()).isTrue();
			assertThat(metadata(records).has("repository-size")).isFalse();
			assertThat(repositoryCountStarted.await(1, TimeUnit.SECONDS)).isTrue();
			assertThat(repositoryCountInterrupted.await(1, TimeUnit.SECONDS)).isTrue();
		} finally {
			allowRepositoryCountReturn.countDown();
		}
		assertThat(countConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
		assertThat(defaultCountStarted.getCount())
				.as("cancellation prevents another count after repository.size returns")
				.isEqualTo(1);
	}

	@Test
	void requestInterruptionCancelsAnActiveStatementCount() throws Exception {
		CountDownLatch repositoryCountStarted = new CountDownLatch(1);
		CountDownLatch repositoryCountInterrupted = new CountDownLatch(1);
		CountDownLatch allowRepositoryCountReturn = new CountDownLatch(1);
		CountDownLatch defaultCountStarted = new CountDownLatch(1);
		CountDownLatch countConnectionClosed = new CountDownLatch(1);
		ClearServlet servlet = new ClearServlet(5000);
		Repository repository = repositoryCountThatClearsInterrupt(repositoryCountStarted,
				repositoryCountInterrupted, allowRepositoryCountReturn, defaultCountStarted, countConnectionClosed);
		servlet.setRepository(repository);
		servlet.setRepositoryManager(mock(RepositoryManager.class));
		servlet.init(TestServletConfig.withParams("clear", "cookie-max-age", "300"));
		MockHttpServletRequest request = new MockHttpServletRequest("GET", "/clear");
		request.addHeader("Accept", WorkbenchPageProtocol.ACCEPT);
		request.addParameter("counts", "true");
		MockHttpServletResponse response = new MockHttpServletResponse();
		CountDownLatch requestFinished = new CountDownLatch(1);
		AtomicReference<Throwable> failure = new AtomicReference<>();
		Thread requestThread = new Thread(() -> {
			try {
				servlet.service(request, response);
			} catch (Throwable thrown) {
				failure.set(thrown);
			} finally {
				requestFinished.countDown();
			}
		}, "clear-request-interruption-test");
		try {
			requestThread.start();
			assertThat(repositoryCountStarted.await(2, TimeUnit.SECONDS)).isTrue();
			requestThread.interrupt();

			assertThat(repositoryCountInterrupted.await(1, TimeUnit.SECONDS))
					.as("request interruption cancels the owned count worker")
					.isTrue();
			assertThat(requestFinished.await(1, TimeUnit.SECONDS)).isTrue();
			assertThat(failure.get()).isInstanceOf(ServletException.class);
			assertThat(failure.get().getCause()).isInstanceOf(InterruptedException.class);
		} finally {
			allowRepositoryCountReturn.countDown();
			requestThread.join(2000);
			servlet.destroy();
		}
		assertThat(countConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
		assertThat(defaultCountStarted.getCount()).isEqualTo(1);
	}

	@Test
	void requestInterruptionCancelsContextDiscovery() throws Exception {
		CountDownLatch contextEnumerationStarted = new CountDownLatch(1);
		CountDownLatch contextEnumerationInterrupted = new CountDownLatch(1);
		CountDownLatch allowContextEnumeration = new CountDownLatch(1);
		CountDownLatch discoveryConnectionClosed = new CountDownLatch(1);
		CountDownLatch statementCountStarted = new CountDownLatch(1);
		ClearServlet servlet = new ClearServlet(5000, 5000);
		Repository repository = slowContextListingStore(contextEnumerationStarted, allowContextEnumeration,
				discoveryConnectionClosed, statementCountStarted, contextEnumerationInterrupted);
		servlet.setRepository(repository);
		servlet.setRepositoryManager(mock(RepositoryManager.class));
		servlet.init(TestServletConfig.withParams("clear", "cookie-max-age", "300"));
		MockHttpServletRequest request = new MockHttpServletRequest("GET", "/clear");
		request.addHeader("Accept", WorkbenchPageProtocol.ACCEPT);
		MockHttpServletResponse response = new MockHttpServletResponse();
		CountDownLatch requestFinished = new CountDownLatch(1);
		AtomicReference<Throwable> failure = new AtomicReference<>();
		Thread requestThread = new Thread(() -> {
			try {
				servlet.service(request, response);
			} catch (Throwable thrown) {
				failure.set(thrown);
			} finally {
				requestFinished.countDown();
			}
		}, "clear-context-interruption-test");
		try {
			requestThread.start();
			assertThat(contextEnumerationStarted.await(2, TimeUnit.SECONDS)).isTrue();
			requestThread.interrupt();

			assertThat(contextEnumerationInterrupted.await(1, TimeUnit.SECONDS))
					.as("request interruption cancels the discovery worker")
					.isTrue();
			assertThat(requestFinished.await(1, TimeUnit.SECONDS)).isTrue();
			assertThat(failure.get()).isInstanceOf(ServletException.class);
			assertThat(failure.get().getCause()).isInstanceOf(InterruptedException.class);
		} finally {
			allowContextEnumeration.countDown();
			requestThread.join(2000);
			servlet.destroy();
		}
		assertThat(discoveryConnectionClosed.await(1, TimeUnit.SECONDS)).isTrue();
		assertThat(statementCountStarted.getCount()).isEqualTo(1);
	}

	private List<JsonNode> run(ClearServlet servlet, Repository repository, boolean counts) throws Exception {
		servlet.setRepository(repository);
		servlet.setRepositoryManager(mock(RepositoryManager.class));
		servlet.init(TestServletConfig.withParams("clear", "cookie-max-age", "300"));
		try {
			MockHttpServletRequest request = new MockHttpServletRequest("GET", "/clear");
			request.addHeader("Accept", WorkbenchPageProtocol.ACCEPT);
			if (counts) {
				request.addParameter("counts", "true");
			}
			MockHttpServletResponse response = new MockHttpServletResponse();
			servlet.service(request, response);
			return response.getContentAsString().lines().map(ClearServletPageDataTest::readTree).toList();
		} finally {
			servlet.destroy();
		}
	}

	/** A store whose statement sizes wait until the test ends: every size, or only the size of the given graph. */
	private Repository slowCountingStore(String slowGraph) {
		return new RepositoryWrapper(store) {
			@Override
			public RepositoryConnection getConnection() throws RepositoryException {
				return new RepositoryConnectionWrapper(this, super.getConnection()) {
					@Override
					public long size(Resource... contexts) throws RepositoryException {
						boolean slow = slowGraph == null || contexts.length == 1 && contexts[0] != null
								&& slowGraph.equals(contexts[0].stringValue());
						if (slow) {
							try {
								slowCounts.await(30, TimeUnit.SECONDS);
							} catch (InterruptedException e) {
								Thread.currentThread().interrupt();
							}
						}
						return super.size(contexts);
					}
				};
			}
		};
	}

	private Repository slowContextListingStore(CountDownLatch contextEnumerationStarted,
			CountDownLatch allowContextEnumeration, CountDownLatch discoveryConnectionClosed,
			CountDownLatch statementCountStarted) {
		return slowContextListingStore(contextEnumerationStarted, allowContextEnumeration,
				discoveryConnectionClosed, statementCountStarted, new CountDownLatch(0));
	}

	private Repository slowContextListingStore(CountDownLatch contextEnumerationStarted,
			CountDownLatch allowContextEnumeration, CountDownLatch discoveryConnectionClosed,
			CountDownLatch statementCountStarted, CountDownLatch contextEnumerationInterrupted) {
		return new RepositoryWrapper(store) {
			@Override
			public RepositoryConnection getConnection() throws RepositoryException {
				return new RepositoryConnectionWrapper(this, super.getConnection()) {
					@Override
					public RepositoryResult<Resource> getContextIDs() throws RepositoryException {
						contextEnumerationStarted.countDown();
						try {
							allowContextEnumeration.await();
						} catch (InterruptedException e) {
							contextEnumerationInterrupted.countDown();
							Thread.currentThread().interrupt();
						}
						return super.getContextIDs();
					}

					@Override
					public long size(Resource... contexts) throws RepositoryException {
						statementCountStarted.countDown();
						return super.size(contexts);
					}

					@Override
					public void close() throws RepositoryException {
						try {
							super.close();
						} finally {
							discoveryConnectionClosed.countDown();
						}
					}
				};
			}
		};
	}

	private Repository repositoryCountThatClearsInterrupt(CountDownLatch repositoryCountStarted,
			CountDownLatch repositoryCountInterrupted, CountDownLatch allowRepositoryCountReturn,
			CountDownLatch defaultCountStarted, CountDownLatch countConnectionClosed) {
		return new RepositoryWrapper(store) {
			@Override
			public RepositoryConnection getConnection() throws RepositoryException {
				return new RepositoryConnectionWrapper(this, super.getConnection()) {
					private final AtomicBoolean counting = new AtomicBoolean();

					@Override
					public long size(Resource... contexts) throws RepositoryException {
						counting.set(true);
						if (contexts.length == 0) {
							repositoryCountStarted.countDown();
							while (allowRepositoryCountReturn.getCount() != 0) {
								try {
									allowRepositoryCountReturn.await();
								} catch (InterruptedException e) {
									repositoryCountInterrupted.countDown();
								}
							}
						} else if (contexts.length == 1 && contexts[0] == null) {
							defaultCountStarted.countDown();
						}
						return super.size(contexts);
					}

					@Override
					public void close() throws RepositoryException {
						try {
							super.close();
						} finally {
							if (counting.get()) {
								countConnectionClosed.countDown();
							}
						}
					}
				};
			}
		};
	}

	private static JsonNode readTree(String line) {
		try {
			return JSON_MAPPER.readTree(line);
		} catch (Exception e) {
			throw new IllegalStateException(e);
		}
	}

	private static List<String> vars(List<JsonNode> records) {
		List<String> names = new ArrayList<>();
		records.stream()
				.filter(record -> "vars".equals(record.path("type").asText()))
				.forEach(record -> record.path("values").forEach(name -> names.add(name.asText())));
		return names;
	}

	private static JsonNode metadata(List<JsonNode> records) {
		return records.stream()
				.filter(record -> "metadata".equals(record.path("type").asText()))
				.map(record -> record.path("values"))
				.findFirst()
				.orElse(JSON_MAPPER.createObjectNode());
	}

	private static List<String> column(List<JsonNode> records, int index) {
		List<String> values = new ArrayList<>();
		for (JsonNode record : records) {
			if ("rows".equals(record.path("type").asText())) {
				record.path("values").forEach(row -> {
					JsonNode term = row.get(index);
					values.add(term == null || term.isNull() ? null : term.path("value").asText());
				});
			}
		}
		return values;
	}
}
