/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.commands;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.URL;
import java.util.List;

import org.eclipse.rdf4j.common.iteration.CloseableIteratorIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.impl.SimpleNamespace;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.Update;
import org.eclipse.rdf4j.query.impl.MapBindingSet;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.RepositoryResult;
import org.eclipse.rdf4j.repository.manager.RepositoryInfo;
import org.eclipse.rdf4j.repository.manager.RepositoryManager;
import org.eclipse.rdf4j.rio.RDFHandler;
import org.eclipse.rdf4j.workbench.util.TupleResultBuilder;
import org.eclipse.rdf4j.workbench.util.WorkbenchRequest;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import jakarta.servlet.ServletOutputStream;
import jakarta.servlet.WriteListener;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

class CommandServletCoverageTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void clearServletClearsRepositoryAndContextThenRedirects() throws Exception {
		ClearServlet servlet = new ClearServlet();
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		IRI context = VF.createIRI("urn:test:context");

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(request.isParameterPresent("context")).thenReturn(false, true);
		when(request.getResource("context")).thenReturn(context);

		servlet.doPost(request, response);
		servlet.doPost(request, response);

		verify(connection).clear();
		verify(connection).clear(context);
		verify(response, org.mockito.Mockito.times(2)).sendRedirect("summary");
	}

	@Test
	void clearServletRendersBadRequestDetails() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		ClearServletForTest servlet = new ClearServletForTest(builder);
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(request.isParameterPresent("context")).thenReturn(true);
		when(request.getResource("context")).thenThrow(new ClassCastException("bad context"));
		when(request.getParameter("context")).thenReturn("not-a-resource");
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.doPost(request, response);

		verify(builder).start("error-message", "context");
		verify(builder).link(List.of("info"));
		verify(builder).result("bad context", "not-a-resource");
		verify(builder).end();

		servlet.service(builder);
		verify(builder).start();
	}

	@Test
	void deleteServletDeletesRepositoryAndRedirects() throws Exception {
		DeleteServlet servlet = new DeleteServlet();
		RepositoryManager manager = mock(RepositoryManager.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);

		servlet.setRepositoryManager(manager);
		when(request.getParameter("id")).thenReturn("memory");

		servlet.doPost(request, response);

		verify(manager).removeRepository("memory");
		verify(response).sendRedirect("../");
	}

	@Test
	void deleteServletSupportsJsonSafetyCheckAndSelectionPage() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		DeleteServletForTest servlet = new DeleteServletForTest(builder);
		RepositoryManager manager = mock(RepositoryManager.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		StringWriter body = new StringWriter();
		RepositoryInfo info = repositoryInfo("memory", "Memory repo", new URL("http://example.com/memory"));

		servlet.setRepositoryManager(manager);
		when(manager.isSafeToRemove("memory")).thenReturn(true);
		when(manager.getAllRepositoryInfos()).thenReturn(List.of(info));
		when(request.getParameter("checkSafe")).thenReturn("memory", null);
		when(response.getWriter()).thenReturn(new PrintWriter(body));
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.service(request, response);
		assertThat(body.toString()).isEqualTo("{\"safe\":true}");

		servlet.service(request, response);
		verify(builder).start("readable", "writeable", "id", "description", "location");
		verify(builder).link(List.of("info"));
		verify(builder).result(true, false, "memory", "Memory repo", info.getLocation());
		verify(builder).end();
	}

	@Test
	void exportServletStreamsAcceptedFormat() throws Exception {
		ExportServlet servlet = new ExportServlet();
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(request.isParameterPresent("Accept")).thenReturn(true);
		when(request.getParameter("Accept")).thenReturn("text/turtle");
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.service(request, response);

		verify(response).setContentType("text/turtle");
		verify(response).setHeader("Content-disposition", "attachment; filename=export.ttl");
		verify(response).setCharacterEncoding("UTF-8");
		verify(connection).setParserConfig(any());
		verify(connection).export(any());
	}

	@Test
	void exportServletBuildsTupleResultsWhenNoAcceptHeaderIsProvided() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		ExportServletForTest servlet = new ExportServletForTest(builder);
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		Statement statement = VF.createStatement(VF.createIRI("urn:s"), VF.createIRI("urn:p"), VF.createLiteral("o"));

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(connection.getNamespaces()).thenReturn(repositoryResultOf(new SimpleNamespace("ex", "urn:ex:")));
		when(request.getParameter("action")).thenReturn("preview");
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("limit_export")).thenReturn(true);
		when(request.getInt("limit_export")).thenReturn(1);
		doAnswer(invocation -> {
			RDFHandler handler = invocation.getArgument(4);
			handler.startRDF();
			handler.handleStatement(statement);
			handler.endRDF();
			return null;
		}).when(connection).exportStatements(isNull(), isNull(), isNull(), eq(false), any(RDFHandler.class));
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.service(request, response);

		verify(builder).prefix("ex", "urn:ex:");
		verify(builder).start("subject", "predicate", "object", "context");
		verify(builder).link(List.of("info"));
		verify(builder).metadata("statement-preview-requested", true);
		verify(builder).result(statement.getSubject(), statement.getPredicate(), statement.getObject(),
				statement.getContext());
		verify(builder).end();
	}

	@Test
	void exportPreviewActionWinsOverSelectedDownloadFormat() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		ExportServletForTest servlet = new ExportServletForTest(builder);
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		Statement statement = VF.createStatement(VF.createIRI("urn:s"), VF.createIRI("urn:p"), VF.createLiteral("o"));

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(connection.getNamespaces()).thenReturn(repositoryResultOf());
		when(request.getParameter("action")).thenReturn("preview");
		when(request.isParameterPresent("Accept")).thenReturn(true);
		when(request.getParameter("Accept")).thenReturn("application/n-quads");
		when(request.isParameterPresent("limit_export")).thenReturn(true);
		when(request.getInt("limit_export")).thenReturn(1);
		doAnswer(invocation -> {
			RDFHandler handler = invocation.getArgument(4);
			handler.startRDF();
			handler.handleStatement(statement);
			handler.endRDF();
			return null;
		}).when(connection).exportStatements(isNull(), isNull(), isNull(), eq(false), any(RDFHandler.class));
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.service(request, response);

		verify(connection, never()).export(any());
		verify(connection).exportStatements(isNull(), isNull(), isNull(), eq(false), any(RDFHandler.class));
		verify(builder).result(statement.getSubject(), statement.getPredicate(), statement.getObject(),
				statement.getContext());
	}

	@Test
	void informationServletRendersRuntimeDetails() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		InformationServletForTest servlet = new InformationServletForTest();

		servlet.service(builder);

		verify(builder).start("version", "os", "jvm", "user", "memory-used", "maximum-memory");
		verify(builder).link(List.of("info"));
		ArgumentCaptor<Object[]> resultCaptor = ArgumentCaptor.forClass(Object[].class);
		verify(builder).result(resultCaptor.capture());
		assertThat(resultCaptor.getValue()).hasSize(6);
		assertThat(resultCaptor.getValue()[1]).asString().contains(System.getProperty("os.name"));
		assertThat(resultCaptor.getValue()[2]).asString().contains(System.getProperty("java.vm.name"));
		verify(builder).end();
	}

	@Test
	void namespacesServletUpdatesRemovesAndListsNamespaces() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		NamespacesServletForTest servlet = new NamespacesServletForTest(builder);
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(connection.getNamespaces())
				.thenAnswer(invocation -> repositoryResultOf(new SimpleNamespace("ex", "urn:ex:")));
		when(request.getParameter("prefix")).thenReturn("ex", "ex");
		when(request.getParameter("namespace")).thenReturn("urn:ex:", "");
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.doPost(request, response);
		servlet.doPost(request, response);
		servlet.service(builder);

		verify(connection).setNamespace("ex", "urn:ex:");
		verify(connection).removeNamespace("ex");
		verify(builder, org.mockito.Mockito.times(3)).start("prefix", "namespace");
		verify(builder, org.mockito.Mockito.times(3)).link(List.of("info"));
		verify(builder, org.mockito.Mockito.times(3)).result("ex", "urn:ex:");
		verify(builder, org.mockito.Mockito.times(3)).end();
	}

	@Test
	void repositoriesServletListsRepositoryInfos() throws Exception {
		RepositoriesServlet servlet = new RepositoriesServlet();
		RepositoryManager manager = mock(RepositoryManager.class);
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		RepositoryInfo info = repositoryInfo("memory", "Memory repo", new URL("http://example.com/memory"));

		servlet.setRepositoryManager(manager);
		when(manager.getAllRepositoryInfos()).thenReturn(List.of(info));

		servlet.service(builder);

		verify(builder).start("readable", "writeable", "id", "description", "location");
		verify(builder).link(List.of("info"));
		verify(builder).result(true, false, "memory", "Memory repo", "http://example.com/memory");
		verify(builder).end();
	}

	@Test
	void contextsServletEmitsEveryContext() throws Exception {
		ContextsServlet servlet = new ContextsServlet();
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		Resource context = VF.createIRI("urn:test:ctx");

		when(connection.getContextIDs()).thenReturn(repositoryResultOf(context));

		servlet.service(builder, connection);

		verify(builder).result(context);
	}

	@Test
	void typesServletEmitsEveryDistinctType() throws Exception {
		TypesServlet servlet = new TypesServlet();
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		TupleQuery query = mock(TupleQuery.class);
		TupleQueryResult result = mock(TupleQueryResult.class);
		BindingSet bindingSet = bindingSet("type", VF.createIRI("urn:test:type"));

		when(connection.prepareTupleQuery(eq(org.eclipse.rdf4j.query.QueryLanguage.SPARQL), any()))
				.thenReturn(query);
		when(query.evaluate()).thenReturn(result);
		when(result.hasNext()).thenReturn(true, false);
		when(result.next()).thenReturn(bindingSet);

		servlet.service(builder, connection);

		verify(builder).result(bindingSet.getValue("type"));
	}

	@Test
	void updateServletExecutesUpdatesRendersErrorsAndShowsEditor() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		UpdateServletForTest servlet = new UpdateServletForTest(builder);
		Repository repository = mock(Repository.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		Update update = mock(Update.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		HttpServletResponse response = mock(HttpServletResponse.class);

		servlet.setRepository(repository);
		when(repository.getConnection()).thenReturn(connection);
		when(connection.prepareUpdate(org.eclipse.rdf4j.query.QueryLanguage.SPARQL, "insert data {}"))
				.thenReturn(update);
		when(request.getParameter("update")).thenReturn("insert data {}", "broken update", "broken update");
		when(response.getOutputStream()).thenReturn(new StubServletOutputStream());

		servlet.doPost(request, response);
		verify(update).execute();
		verify(response).sendRedirect("summary");

		when(connection.prepareUpdate(org.eclipse.rdf4j.query.QueryLanguage.SPARQL, "broken update"))
				.thenThrow(new RepositoryException("bad update"));
		servlet.doPost(request, response);
		verify(builder).start("error-message", "update");
		verify(builder).link(List.of("info", "_internal/namespaces"));
		verify(builder).result("bad update", "broken update");
		verify(builder).end();

		assertThat(servlet.getCookieNames()).containsExactly("Content-Type");
		servlet.service(builder);
	}

	private static BindingSet bindingSet(String name, IRI value) {
		MapBindingSet bindingSet = new MapBindingSet();
		bindingSet.addBinding(name, value);
		return bindingSet;
	}

	private static RepositoryInfo repositoryInfo(String id, String description, URL location) {
		RepositoryInfo info = new RepositoryInfo();
		info.setId(id);
		info.setDescription(description);
		info.setLocation(location);
		info.setReadable(true);
		info.setWritable(false);
		return info;
	}

	@SafeVarargs
	private static <T> RepositoryResult<T> repositoryResultOf(T... values) {
		return new RepositoryResult<>(new CloseableIteratorIteration<>(List.of(values).iterator()));
	}

	private static final class ClearServletForTest extends ClearServlet {
		private final TupleResultBuilder builder;

		private ClearServletForTest(TupleResultBuilder builder) {
			this.builder = builder;
		}

		@Override
		protected TupleResultBuilder getTupleResultBuilder(HttpServletRequest req, HttpServletResponse resp,
				java.io.OutputStream outputStream) {
			return builder;
		}
	}

	private static final class DeleteServletForTest extends DeleteServlet {
		private final TupleResultBuilder builder;

		private DeleteServletForTest(TupleResultBuilder builder) {
			this.builder = builder;
		}

		@Override
		protected TupleResultBuilder getTupleResultBuilder(HttpServletRequest req, HttpServletResponse resp,
				java.io.OutputStream outputStream) {
			return builder;
		}
	}

	private static final class ExportServletForTest extends ExportServlet {
		private final TupleResultBuilder builder;

		private ExportServletForTest(TupleResultBuilder builder) {
			this.builder = builder;
		}

		@Override
		protected TupleResultBuilder getTupleResultBuilder(HttpServletRequest req, HttpServletResponse resp,
				java.io.OutputStream outputStream) {
			return builder;
		}
	}

	private static final class InformationServletForTest extends InformationServlet {
		private InformationServletForTest() {
			this.appConfig = new org.eclipse.rdf4j.common.app.AppConfiguration("Workbench", "RDF4J Workbench");
		}
	}

	private static final class NamespacesServletForTest extends NamespacesServlet {
		private final TupleResultBuilder builder;

		private NamespacesServletForTest(TupleResultBuilder builder) {
			this.builder = builder;
		}

		@Override
		protected TupleResultBuilder getTupleResultBuilder(HttpServletRequest req, HttpServletResponse resp,
				java.io.OutputStream outputStream) {
			return builder;
		}
	}

	private static final class UpdateServletForTest extends UpdateServlet {
		private final TupleResultBuilder builder;

		private UpdateServletForTest(TupleResultBuilder builder) {
			this.builder = builder;
		}

		@Override
		protected TupleResultBuilder getTupleResultBuilder(HttpServletRequest req, HttpServletResponse resp,
				java.io.OutputStream outputStream) {
			return builder;
		}
	}

	private static final class StubServletOutputStream extends ServletOutputStream {
		private final ByteArrayOutputStream delegate = new ByteArrayOutputStream();

		@Override
		public boolean isReady() {
			return true;
		}

		@Override
		public void setWriteListener(WriteListener writeListener) {
		}

		@Override
		public void write(int b) throws IOException {
			delegate.write(b);
		}
	}
}
