/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.commands;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Map;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.manager.RepositoryInfo;
import org.eclipse.rdf4j.workbench.exceptions.BadRequestException;
import org.eclipse.rdf4j.workbench.util.QueryStorage;
import org.eclipse.rdf4j.workbench.util.WorkbenchRequest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import jakarta.servlet.http.Cookie;

/** Save preserves legacy metadata compatibility without requiring the retired browser page-size field. */
class QueryServletBatchSaveTest {

	private static final String QUERY = "SELECT ?n WHERE { VALUES ?n { 0 1 2 } } ORDER BY ?n";

	@Test
	void savesAnUnboundedLegacyMarkerWhenTheRetiredFieldIsAbsent() throws Exception {
		assertSavedPageSize(false, null, null, 0);
	}

	@Test
	void returningUsersPageSizeCookieDoesNotControlNewSavedMetadata() throws Exception {
		assertSavedPageSize(false, null, "100", 0);
	}

	@Test
	void overwritingAlsoAcceptsTheRetiredFieldBeingAbsent() throws Exception {
		assertSavedPageSize(true, null, "100", 0);
	}

	@ParameterizedTest
	@ValueSource(ints = { 0, 10, 20, 50, 100, 200 })
	void preservesExplicitSupportedLegacyMetadata(int size) throws Exception {
		assertSavedPageSize(false, Integer.toString(size), "50", size);
	}

	@ParameterizedTest
	@ValueSource(strings = { "", "5", "-1", "1000000", "2147483648", "1.5", "NaN" })
	void rejectsInvalidExplicitLegacyPageSizesBeforeWriting(String size) throws Exception {
		QueryServlet servlet = servlet();
		QueryStorage storage = storage(servlet, false);

		assertThatThrownBy(() -> servlet.doPost(request(false, size, "100"), new MockHttpServletResponse()))
				.isInstanceOf(BadRequestException.class)
				.hasMessageContaining("limit_query");
		verify(storage, never()).saveQuery(any(), anyString(), anyString(), anyBoolean(), any(), anyString(),
				anyBoolean(), anyInt(), anyInt());
	}

	private static void assertSavedPageSize(boolean overwrite, String size, String cookie, int expected)
			throws Exception {
		QueryServlet servlet = servlet();
		QueryStorage storage = storage(servlet, overwrite);
		MockHttpServletResponse response = new MockHttpServletResponse();

		servlet.doPost(request(overwrite, size, cookie), response);

		assertThat(response.getContentAsString()).contains("\"written\":true");
		if (overwrite) {
			verify(storage).updateQuery(SimpleValueFactory.getInstance().createIRI("urn:query:existing"), "", true,
					QueryLanguage.SPARQL, QUERY, true, expected, 17);
		} else {
			verify(storage).saveQuery(any(), eq("batch-save"), eq(""), eq(true), eq(QueryLanguage.SPARQL), eq(QUERY),
					eq(true), eq(expected), eq(17));
		}
	}

	private static QueryServlet servlet() {
		QueryServlet servlet = new QueryServlet();
		Repository repository = mock(Repository.class);
		when(repository.getValueFactory()).thenReturn(SimpleValueFactory.getInstance());
		servlet.setRepository(repository);
		RepositoryInfo info = new RepositoryInfo();
		info.setId("batch-save-fixture");
		servlet.setRepositoryInfo(info);
		return servlet;
	}

	private static QueryStorage storage(QueryServlet servlet, boolean overwrite) throws Exception {
		QueryStorage storage = mock(QueryStorage.class);
		servlet.substituteQueryStorage(storage);
		when(storage.checkAccess(any())).thenReturn(true);
		when(storage.askExists(any(), eq("batch-save"), eq(""))).thenReturn(overwrite);
		IRI existing = SimpleValueFactory.getInstance().createIRI("urn:query:existing");
		when(storage.selectSavedQuery(any(), eq(""), eq("batch-save"))).thenReturn(existing);
		return storage;
	}

	private static WorkbenchRequest request(boolean overwrite, String size, String cookie) throws Exception {
		MockHttpServletRequest raw = new MockHttpServletRequest("POST", "/query");
		raw.addParameter("action", "save");
		raw.addParameter("query", QUERY);
		raw.addParameter("query-name", "batch-save");
		raw.addParameter("queryLn", "SPARQL");
		raw.addParameter("infer", "true");
		raw.addParameter("query-timeout", "17");
		raw.addParameter("overwrite", Boolean.toString(overwrite));
		raw.addParameter("save-private", "false");
		if (size != null) {
			raw.addParameter("limit_query", size);
		}
		if (cookie != null) {
			raw.setCookies(new Cookie("limit_query", cookie));
		}
		return new WorkbenchRequest(null, raw, Map.of());
	}
}
