/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.http.client;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.rdf4j.common.iteration.QueryExecutionDeadline;
import org.junit.jupiter.api.Test;

class QueryReplayWorkerScopeTest {

	private static final ThreadLocal<String> ACTIVE_WORKER_SCOPE = new ThreadLocal<>();

	@Test
	void capturedWorkerScopeRemainsUsableAfterSourceScopesClose() throws Exception {
		ExecutorService executor = Executors.newSingleThreadExecutor();
		QueryExecutionDeadline deadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		AtomicBoolean sourceScopeOpen = new AtomicBoolean(true);
		AtomicInteger captures = new AtomicInteger();
		AtomicInteger activations = new AtomicInteger();
		AtomicInteger deactivations = new AtomicInteger();
		QueryExecutionContext.ReplayContext replayContext;

		try {
			try (QueryExecutionDeadline.Scope ignored = deadline.enter();
					QueryExecutionContext.Activation source = QueryExecutionContext.activateReplaySafepoint(() -> {
					}, () -> {
						assertTrue(sourceScopeOpen.get());
						captures.incrementAndGet();
						String capturedCapability = "reader-admission";
						return () -> {
							assertFalse(sourceScopeOpen.get(), "the captured capability must outlive its source scope");
							assertEquals("reader-admission", capturedCapability);
							activations.incrementAndGet();
							return deactivations::incrementAndGet;
						};
					})) {
				replayContext = QueryExecutionContext.captureReplayContext();
			}
			sourceScopeOpen.set(false);

			executor.submit(() -> {
				assertNull(QueryExecutionDeadline.current());
				assertSame(deadline, replayContext.get(() -> QueryExecutionDeadline.current()));
				assertNull(QueryExecutionDeadline.current(), "worker deadline must be restored after captured work");
			}).get(5, TimeUnit.SECONDS);

			assertEquals(1, captures.get());
			assertEquals(1, activations.get());
			assertEquals(1, deactivations.get());
		} finally {
			deadline.close();
			executor.shutdownNow();
			assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS));
		}
	}

	@Test
	void capturedNestedScopesActivateInOrderAndCloseInReverseOrderAfterFailure() throws Exception {
		ExecutorService executor = Executors.newSingleThreadExecutor();
		List<String> events = new ArrayList<>();
		QueryExecutionContext.ReplayContext replayContext;
		IllegalStateException actionFailure = new IllegalStateException("worker action failed");

		try {
			try (QueryExecutionContext.Activation outer = QueryExecutionContext.activateReplaySafepoint(() -> {
			}, () -> () -> {
				events.add("activate outer");
				return () -> events.add("close outer");
			})) {
				try (QueryExecutionContext.Activation inner = QueryExecutionContext.activateReplaySafepoint(() -> {
				}, () -> () -> {
					events.add("activate inner");
					return () -> events.add("close inner");
				})) {
					replayContext = QueryExecutionContext.captureReplayContext();
				}
			}

			executor.submit(() -> {
				assertSame(actionFailure, assertThrows(IllegalStateException.class, () -> replayContext.get(() -> {
					throw actionFailure;
				})));
			}).get(5, TimeUnit.SECONDS);

			assertEquals(List.of("activate outer", "activate inner", "close inner", "close outer"), events);
		} finally {
			executor.shutdownNow();
			assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS));
		}
	}

	@Test
	void partialWorkerScopeActivationFailureRestoresWorkerDeadlineAndReplayScopes() throws Exception {
		ExecutorService executor = Executors.newSingleThreadExecutor();
		QueryExecutionDeadline capturedDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		QueryExecutionDeadline workerDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		AtomicInteger firstScopeCloses = new AtomicInteger();
		AtomicInteger priorCheckpoints = new AtomicInteger();
		IllegalStateException activationFailure = new IllegalStateException("admission capability expired");
		QueryExecutionContext.ReplayContext replayContext;

		try {
			try (QueryExecutionDeadline.Scope ignored = capturedDeadline.enter();
					QueryExecutionContext.Activation outer = QueryExecutionContext.activateReplaySafepoint(() -> {
					}, () -> () -> () -> firstScopeCloses.incrementAndGet())) {
				try (QueryExecutionContext.Activation inner = QueryExecutionContext.activateReplaySafepoint(() -> {
				}, () -> () -> {
					throw activationFailure;
				})) {
					replayContext = QueryExecutionContext.captureReplayContext();
				}
			}

			executor.submit(() -> {
				try (QueryExecutionDeadline.Scope priorDeadline = workerDeadline.enter();
						QueryExecutionContext.Activation priorSafepoint = QueryExecutionContext
								.activateReplaySafepoint(priorCheckpoints::incrementAndGet)) {
					try (QueryExecutionContext.Activation priorDeferral = QueryExecutionContext
							.deferReplaySafepoints()) {
						assertSame(activationFailure,
								assertThrows(IllegalStateException.class, () -> replayContext.get(() -> null)));
						assertSame(workerDeadline, QueryExecutionDeadline.current());
						QueryExecutionContext.checkpointReplaySafepoint();
						assertEquals(0, priorCheckpoints.get(), "the worker's deferral must be restored after failure");
					}
					assertSame(workerDeadline, QueryExecutionDeadline.current());
					QueryExecutionContext.checkpointReplaySafepoint();
					assertEquals(1, priorCheckpoints.get(), "the worker's safepoint must be restored after failure");
				}
				assertNull(QueryExecutionDeadline.current());
			}).get(5, TimeUnit.SECONDS);

			assertEquals(1, firstScopeCloses.get(),
					"every successfully activated scope must close after partial failure");
		} finally {
			capturedDeadline.close();
			workerDeadline.close();
			executor.shutdownNow();
			assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS));
		}
	}

	@Test
	void nestedOperationsReuseWorkerScopesUnlessADeadlineScopeChanges() throws Exception {
		ExecutorService executor = Executors.newSingleThreadExecutor();
		QueryExecutionDeadline capturedDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		QueryExecutionDeadline localDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		AtomicInteger activations = new AtomicInteger();
		AtomicInteger deactivations = new AtomicInteger();
		QueryExecutionContext.ReplayContext replayContext;

		try {
			try (QueryExecutionDeadline.Scope ignored = capturedDeadline.enter();
					QueryExecutionContext.Activation source = QueryExecutionContext.activateReplaySafepoint(() -> {
					}, () -> () -> {
						activations.incrementAndGet();
						return deactivations::incrementAndGet;
					})) {
				replayContext = QueryExecutionContext.captureReplayContext();
			}

			executor.submit(() -> {
				assertEquals(9, replayContext.get(() -> {
					assertSame(capturedDeadline, QueryExecutionDeadline.current());
					assertEquals(1, activations.get());
					assertEquals(7, replayContext.getAsInt(() -> {
						assertSame(capturedDeadline, QueryExecutionDeadline.current());
						return 7;
					}));
					assertEquals(1, activations.get(),
							"nested work in the same captured context must reuse its activation");

					try (QueryExecutionDeadline.Scope local = localDeadline.enter()) {
						assertEquals(8, replayContext.getAsInt(() -> {
							assertSame(capturedDeadline, QueryExecutionDeadline.current());
							return 8;
						}));
						assertSame(localDeadline, QueryExecutionDeadline.current(),
								"nested captured work must restore the worker's new local deadline");
					}
					assertEquals(2, activations.get(), "a changed local scope must reinstall captured capabilities");
					assertEquals(1, deactivations.get(), "the nested reinstall must close before the outer activation");
					return 9;
				}));
				assertNull(QueryExecutionDeadline.current());
				assertEquals(2, activations.get());
				assertEquals(2, deactivations.get());
			}).get(5, TimeUnit.SECONDS);
		} finally {
			capturedDeadline.close();
			localDeadline.close();
			executor.shutdownNow();
			assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS));
		}
	}

	@Test
	void reusedExecutorDoesNotRetainCapturedDeadlinesOrWorkerScopes() throws Exception {
		ExecutorService executor = Executors.newSingleThreadExecutor();
		QueryExecutionDeadline firstDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		QueryExecutionDeadline secondDeadline = QueryExecutionDeadline.start(TimeUnit.MINUTES.toMillis(2));
		QueryExecutionContext.ReplayContext firstContext;
		QueryExecutionContext.ReplayContext secondContext;

		try {
			firstContext = captureContext(firstDeadline, "first-query");
			secondContext = captureContext(secondDeadline, "second-query");
			Thread worker = executor.submit(() -> {
				return Thread.currentThread();
			}).get(5, TimeUnit.SECONDS);

			executor.submit(() -> {
				assertNull(QueryExecutionDeadline.current());
				assertNull(ACTIVE_WORKER_SCOPE.get());
				firstContext.run(() -> {
					assertSame(worker, Thread.currentThread());
					assertSame(firstDeadline, QueryExecutionDeadline.current());
					assertEquals("first-query", ACTIVE_WORKER_SCOPE.get());
				});
				assertNull(QueryExecutionDeadline.current());
				assertNull(ACTIVE_WORKER_SCOPE.get());
				assertNull(QueryExecutionContext.captureReplayContext(),
						"the reused worker must have no captured query state between tasks");

				secondContext.run(() -> {
					assertSame(worker, Thread.currentThread());
					assertSame(secondDeadline, QueryExecutionDeadline.current());
					assertEquals("second-query", ACTIVE_WORKER_SCOPE.get());
				});
				assertNull(QueryExecutionDeadline.current());
				assertNull(ACTIVE_WORKER_SCOPE.get());
				assertNull(QueryExecutionContext.captureReplayContext());
			}).get(5, TimeUnit.SECONDS);
		} finally {
			firstDeadline.close();
			secondDeadline.close();
			executor.shutdownNow();
			assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS));
			ACTIVE_WORKER_SCOPE.remove();
		}
	}

	@Test
	void capturedOwnershipValidationRunsInOrderWithoutActivatingScopes() {
		List<String> validations = new ArrayList<>();
		AtomicInteger activations = new AtomicInteger();
		AtomicBoolean closed = new AtomicBoolean();
		IllegalStateException cancellation = new IllegalStateException("captured owner closed");
		QueryExecutionContext.WorkerScope owner = new QueryExecutionContext.WorkerScope() {
			@Override
			public QueryExecutionContext.Activation activate() {
				activations.incrementAndGet();
				return () -> {
				};
			}

			@Override
			public void checkActive() {
				validations.add("outer");
				if (closed.get()) {
					throw cancellation;
				}
			}
		};
		QueryExecutionContext.WorkerScope nested = new QueryExecutionContext.WorkerScope() {
			@Override
			public QueryExecutionContext.Activation activate() {
				activations.incrementAndGet();
				return () -> {
				};
			}

			@Override
			public void checkActive() {
				validations.add("inner");
			}
		};
		try (QueryExecutionDeadline capturedDeadline = QueryExecutionDeadline.start(60000);
				QueryExecutionDeadline localDeadline = QueryExecutionDeadline.start(60000)) {
			QueryExecutionContext.ReplayContext context;
			try (QueryExecutionDeadline.Scope deadline = capturedDeadline.enter();
					QueryExecutionContext.Activation outer = QueryExecutionContext.activateReplaySafepoint(() -> {
					}, () -> owner);
					QueryExecutionContext.Activation inner = QueryExecutionContext.activateReplaySafepoint(() -> {
					}, () -> nested)) {
				context = QueryExecutionContext.captureReplayContext();
			}
			try (QueryExecutionDeadline.Scope deadline = localDeadline.enter();
					QueryExecutionContext.Activation deferral = QueryExecutionContext.deferReplaySafepoints()) {
				context.checkActive();
				assertEquals(List.of("outer", "inner"), validations);
				assertEquals(0, activations.get(), "validation must not acquire or install worker resources");
				assertSame(localDeadline, QueryExecutionDeadline.current());
				closed.set(true);
				assertSame(cancellation, assertThrows(IllegalStateException.class, context::checkActive),
						"synchronous replay deferral must never defer ownership validation");
				assertEquals(0, activations.get());
				assertSame(localDeadline, QueryExecutionDeadline.current());
			}
		}
	}

	private static QueryExecutionContext.ReplayContext captureContext(QueryExecutionDeadline deadline, String name) {
		try (QueryExecutionDeadline.Scope ignored = deadline.enter();
				QueryExecutionContext.Activation source = QueryExecutionContext.activateReplaySafepoint(() -> {
				}, () -> () -> {
					String previous = ACTIVE_WORKER_SCOPE.get();
					ACTIVE_WORKER_SCOPE.set(name);
					return () -> {
						if (previous == null) {
							ACTIVE_WORKER_SCOPE.remove();
						} else {
							ACTIVE_WORKER_SCOPE.set(previous);
						}
					};
				})) {
			return QueryExecutionContext.captureReplayContext();
		}
	}
}
