/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.explanation;

import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.rdf4j.common.annotation.InternalUseOnly;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.query.impl.MapBindingSet;

/** Compilation-scoped explanation request. It is restored even when nested compilation fails. */
@InternalUseOnly
public final class QueryExplanationContext implements AutoCloseable {
	private static final ThreadLocal<QueryExplanationContext> CURRENT = new ThreadLocal<>();
	private final QueryExplanationContext previous;
	private final boolean preview;
	private final Map<Object, Boolean> inspected = new IdentityHashMap<>();
	private final List<StrategyDecision> decisions = new ArrayList<>();
	private final BindingSet bindings;
	private String runtimeCondition;

	private QueryExplanationContext(boolean preview, BindingSet bindings) {
		previous = CURRENT.get();
		this.preview = preview;
		MapBindingSet copy = new MapBindingSet();
		if (bindings != null) {
			bindings.forEach(copy::addBinding);
		}
		this.bindings = copy;
		CURRENT.set(this);
	}

	public static QueryExplanationContext enter(Explanation.Level level) {
		return enter(level, EmptyBindingSet.getInstance());
	}

	public static QueryExplanationContext enter(Explanation.Level level, BindingSet bindings) {
		return new QueryExplanationContext(level == Explanation.Level.Optimized, bindings);
	}

	public static BindingSet bindings() {
		return isPreview() ? CURRENT.get().bindings : EmptyBindingSet.getInstance();
	}

	public static void withRuntimeCondition(String condition, Runnable inspect) {
		if (!isPreview()) {
			return;
		}
		QueryExplanationContext context = CURRENT.get();
		String previous = context.runtimeCondition;
		context.runtimeCondition = previous == null ? condition : previous + "; " + condition;
		try {
			inspect.run();
		} finally {
			context.runtimeCondition = previous;
		}
	}

	public static void record(StrategyDecision decision) {
		if (!isPreview()) {
			return;
		}
		QueryExplanationContext context = CURRENT.get();
		String condition = context.runtimeCondition;
		List<StrategyDecision.Candidate> candidates = decision.candidates();
		if (condition != null) {
			candidates = candidates.stream()
					.map(candidate -> Boolean.FALSE.equals(candidate.canAttempt()) ? candidate
							: new StrategyDecision.Candidate(
									candidate.strategy(), null, null, "Runtime dependent", null, condition))
					.toList();
		}
		context.decisions.add(new StrategyDecision("Decision " + (context.decisions.size() + 1) + ": "
				+ decision.decisionPoint(), decision.capturedAtMillis(),
				condition == null ? decision.mode() : "runtime dependent",
				condition == null ? decision.wouldSelect() : null, condition == null ? decision.fallback() : null,
				condition == null ? decision.reason() : condition, candidates));
	}

	public List<StrategyDecision> decisions() {
		return List.copyOf(decisions);
	}

	public static boolean isPreview() {
		QueryExplanationContext context = CURRENT.get();
		return context != null && context.preview;
	}

	public static boolean inspectOnce(Object plan) {
		QueryExplanationContext context = CURRENT.get();
		return context != null && context.preview && context.inspected.put(plan, Boolean.TRUE) == null;
	}

	@Override
	public void close() {
		if (previous == null)
			CURRENT.remove();
		else
			CURRENT.set(previous);
	}
}
