/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb.csf;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

import org.eclipse.rdf4j.sail.lmdb.ValueIds;
import org.junit.jupiter.api.Test;

class ImmutablePagedQuadCsfIndexTest {
	private static final String SHARD_TARGET_PAGES_PROPERTY = "org.eclipse.rdf4j.sail.lmdb.directAdjacency.csfShardTargetPages";

	@Test
	void physicalPageCursorExposesHeaderCountsAndBothColumnTraits() {
		List<Row> rows = List.of(
				new Row(id(ValueIds.T_SHORTSTRING, 1),
						new long[] { id(ValueIds.T_URI, 101), id(ValueIds.T_URI, 101) },
						new long[] { 0, id(ValueIds.T_URI, 1_001) }),
				new Row(id(ValueIds.T_SHORTSTRING, 2), new long[] { id(ValueIds.T_URI, 102) },
						new long[] { 0 }));
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			ImmutablePagedQuadCsfIndex.PageCursor pages = index.keyDomain(0, 0).pageCursor();

			assertThat(pages.advance()).isTrue();
			assertThat(pages.roots()).isEqualTo(2);
			assertThat(pages.fibers()).isEqualTo(2);
			assertThat(pages.quads()).isEqualTo(3);
			assertThat(pages.firstRoot()).isEqualTo(rows.get(0).row);
			assertThat(pages.rowsHaveUniformTermKind()).isTrue();
			assertThat(pages.rowsHaveUniformLiteralDatatype()).isTrue();
			assertThat(pages.neighborsHaveUniformTermKind()).isTrue();
			assertThat(pages.neighborsHaveUniformLiteralDatatype()).isFalse();
			assertThat(pages.rootQuadCount(0)).isEqualTo(2);
			assertThat(pages.neighborAt(0, 0)).isEqualTo(id(ValueIds.T_URI, 101));
			assertThat(pages.neighborContextCount(0, 0)).isEqualTo(2);
			assertThat(pages.advance()).isFalse();
		}
	}

	@Test
	void factorizesNeighbourAndContextFibres() {
		long neighbour = id(1, 99);
		List<Row> rows = List.of(new Row(id(1, 7),
				new long[] { neighbour, neighbour, neighbour, id(1, 100) },
				new long[] { 0, id(1, 4), id(1, 8), 0 }));
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			index.resolve(index.findLocalReference(0, 0, id(1, 7)), cursor);

			assertThat(cursor.edgeCount()).isEqualTo(4);
			assertThat(cursor.neighborAt(0)).isEqualTo(neighbour);
			assertThat(cursor.neighborAt(2)).isEqualTo(neighbour);
			assertThat(cursor.lowerBound(0, neighbour, id(1, 4))).isEqualTo(1);

			long[] neighbours = new long[4];
			long[] contexts = new long[4];
			assertThat(cursor.copy(0, 4, neighbours, 0, contexts, 0)).isEqualTo(4);
			assertThat(neighbours).containsExactly(rows.get(0).neighbours);
			assertThat(contexts).containsExactly(rows.get(0).contexts);
		}
	}

	@Test
	void repeatedLookupsReuseOneCursorAcrossHitsAndMisses() {
		List<Row> rows = new ArrayList<>();
		for (int row = 0; row < 32; row++) {
			rows.add(new Row(id(1, 10L + row * 2L), new long[] { id(1, 1_000L + row) }, new long[] { 0 }));
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			ImmutablePagedQuadCsfIndex.LookupCursor cursor = new ImmutablePagedQuadCsfIndex.LookupCursor();
			for (int round = 0; round < 3; round++) {
				for (int row = 0; row < rows.size(); row++) {
					assertThat(index.findLocalReference(0, 0, rows.get(row).row, cursor)).isNotZero();
				}
				assertThat(index.findLocalReference(0, 0, id(1, 11), cursor)).isZero();
			}
		}
	}

	@Test
	void lookupCursorRecoversFromAGapMissAfterSupernodeContinuations() {
		int count = 80_000;
		long supernode = id(1, 77);
		long[] neighbours = new long[count];
		long[] contexts = new long[count];
		for (int i = 0; i < count; i++) {
			neighbours[i] = id(1, 1_000_000L + i);
		}
		List<Row> rows = List.of(
				new Row(supernode, neighbours, contexts),
				new Row(id(1, 80), new long[] { id(1, 2_000_000) }, new long[] { 0 }));
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			assertThat(index.pageCount()).isGreaterThan(1);
			ImmutablePagedQuadCsfIndex.LookupCursor cursor = new ImmutablePagedQuadCsfIndex.LookupCursor();
			long firstReference = index.findLocalReference(0, 0, supernode, cursor);
			assertThat(firstReference).isNotZero();
			assertThat(index.findLocalReference(0, 0, id(1, 78), cursor)).isZero();
			assertThat(index.findLocalReference(0, 0, supernode, cursor)).isEqualTo(firstReference);
		}
	}

	@Test
	void lookupMatchesUnsignedExactMembershipAcrossPagesShardsAndGaps() {
		String previous = System.getProperty(SHARD_TARGET_PAGES_PROPERTY);
		System.setProperty(SHARD_TARGET_PAGES_PROPERTY, "2");
		try {
			Random random = new Random(0x5241_4449_584cL);
			long[] keys = new long[6_000];
			for (int i = 0; i < keys.length; i++) {
				keys[i] = random.nextLong();
			}
			for (int i = 0; i < keys.length; i++) {
				keys[i] ^= Long.MIN_VALUE;
			}
			Arrays.sort(keys);
			for (int i = 0; i < keys.length; i++) {
				keys[i] ^= Long.MIN_VALUE;
				if (i > 0 && keys[i] == keys[i - 1]) {
					keys[i]++;
				}
			}

			List<Row> rows = new ArrayList<>(keys.length);
			for (int i = 0; i < keys.length; i++) {
				rows.add(new Row(keys[i], new long[] { id(1, 10_000_000L + i) }, new long[] { 0 }));
			}
			try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
					ImmutablePagedQuadCsfIndex.LookupCursor cursor = new ImmutablePagedQuadCsfIndex.LookupCursor()) {
				assertThat(index.pageCount()).isGreaterThan(2);
				assertThat(index.shardCount()).isGreaterThan(1);
				for (int i = 0; i < keys.length; i += 17) {
					assertThat(index.findLocalReference(0, 0, keys[i], cursor)).isNotZero();
					assertThat(index.findLocalReference(0, 0, keys[i] ^ 1L, cursor)).isZero();
				}
				assertThat(index.findLocalReference(0, 0, keys[0], cursor)).isNotZero();
				assertThat(index.findLocalReference(0, 0, keys[keys.length - 1], cursor)).isNotZero();
			}
		} finally {
			if (previous == null) {
				System.clearProperty(SHARD_TARGET_PAGES_PROPERTY);
			} else {
				System.setProperty(SHARD_TARGET_PAGES_PROPERTY, previous);
			}
		}
	}

	@Test
	void packsTheCompleteNonDoubleLmdbTypeAndPayloadLayout() {
		long[] values = new long[600];
		for (int i = 0; i < values.length; i++) {
			values[i] = id(36, (1L << 40) + i * 7L);
		}
		byte[] encoded = PackedLongVector.encode(values, 0, values.length,
				PackedLongVector.Hint.SORTED_SEQUENTIAL_IDS);
		PackedLongVector.ArrayReader arrayReader = PackedLongVector.reader(encoded);
		for (int i : new int[] { 0, 1, 255, 256, 599 }) {
			assertThat(arrayReader.get(i)).isEqualTo(values[i]);
		}

		long address = UnsafeAccess.allocateZeroed(encoded.length + PackedLongVector.READ_TAIL_PADDING);
		try {
			UnsafeAccess.copyFromArray(encoded, 0, address, encoded.length);
			PackedLongVector.Reader nativeReader = PackedLongVector.reader(address, encoded.length);
			for (int i : new int[] { 0, 1, 255, 256, 599 }) {
				assertThat(nativeReader.get(i)).isEqualTo(values[i]);
			}
		} finally {
			UnsafeAccess.free(address);
		}
	}

	@Test
	void exposesAZeroCopyOrderedRowDomainAcrossPages() {
		List<Row> rows = new ArrayList<>();
		for (int i = 0; i < 5_000; i++) {
			rows.add(new Row(id(1, i * 3L + 1), new long[] { id(1, i + 100) }, new long[] { 0 }));
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 1, rows)) {
			ImmutablePagedQuadCsfIndex.KeyDomain keys = index.keyDomain(0, 1);
			assertThat(keys.keyCount()).isEqualTo(rows.size());
			for (int i : new int[] { 0, 1, 1_023, 2_048, 4_999 }) {
				assertThat(keys.keyAt(i)).isEqualTo(rows.get(i).row);
				assertThat(keys.contains(rows.get(i).row)).isTrue();
			}
			assertThat(keys.contains(id(1, 2))).isFalse();
		}
	}

	@Test
	void keyCursorPreservesDirectReferenceAndRunAcrossOrdinalWindows() {
		List<Row> rows = new ArrayList<>();
		for (int i = 0; i < 2_500; i++) {
			rows.add(new Row(id(1, i * 5L + 1),
					new long[] { id(1, 100_000L + i * 3L), id(1, 100_001L + i * 3L) },
					new long[] { 0, id(1, 9) }));
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			long from = 777;
			long to = 1_333;
			ImmutablePagedQuadCsfIndex.KeyCursor cursor = index.keyDomain(0, 0).cursor(from, to);
			for (long ordinal = from; ordinal < to; ordinal++) {
				assertThat(cursor.advance()).isTrue();
				Row expected = rows.get(Math.toIntExact(ordinal));
				assertThat(cursor.key()).isEqualTo(expected.row);
				assertThat(cursor.localReference()).isEqualTo(index.findLocalReference(0, 0, expected.row));
				assertThat(cursor.edgeCount()).isEqualTo(expected.neighbours.length);
				long[] neighbours = new long[expected.neighbours.length];
				long[] contexts = new long[expected.contexts.length];
				assertThat(cursor.copyPairs(0, neighbours.length, neighbours, 0, contexts, 0))
						.isEqualTo(neighbours.length);
				assertThat(neighbours).containsExactly(expected.neighbours);
				assertThat(contexts).containsExactly(expected.contexts);
			}
			assertThat(cursor.advance()).isFalse();
		}
	}

	@Test
	void keyCursorBulkRootCountsStayExactAcrossPagesWindowsAndContinuations() {
		int rowCount = 2_500;
		int supernodeOrdinal = 1_271;
		int supernodeEdges = 80_000;
		List<Row> rows = new ArrayList<>(rowCount);
		for (int row = 0; row < rowCount; row++) {
			int edges = row == supernodeOrdinal ? supernodeEdges : row % 3 + 1;
			long[] neighbors = new long[edges];
			long[] contexts = new long[edges];
			for (int edge = 0; edge < edges; edge++) {
				neighbors[edge] = id(1, 1_000_000L + row * 100_000L + edge);
				contexts[edge] = edge % 3 == 0 ? 0 : id(1, edge + 1L);
			}
			rows.add(new Row(id(1, row * 5L + 1), neighbors, contexts));
		}

		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			assertThat(index.pageCount()).isGreaterThan(2);
			long from = 733;
			long to = 1_809;
			ImmutablePagedQuadCsfIndex.KeyCursor cursor = index.keyDomain(0, 0).cursor(from, to);
			long[] roots = new long[263];
			long[] counts = new long[263];
			long expectedOrdinal = from;
			int copied;
			do {
				Arrays.fill(roots, -1L);
				Arrays.fill(counts, -1L);
				copied = cursor.fillRootCounts(roots, 3, counts, 3, 257);
				for (int lane = 0; lane < copied; lane++) {
					Row expected = rows.get(Math.toIntExact(expectedOrdinal++));
					assertThat(roots[3 + lane]).isEqualTo(expected.row);
					assertThat(counts[3 + lane]).isEqualTo(expected.neighbours.length);
				}
				assertThat(roots[2]).isEqualTo(-1L);
				assertThat(counts[2]).isEqualTo(-1L);
				assertThat(roots[3 + copied]).isEqualTo(-1L);
				assertThat(counts[3 + copied]).isEqualTo(-1L);
			} while (copied != 0);
			assertThat(expectedOrdinal).isEqualTo(to);
		}
	}

	@Test
	void keyCursorCountsDistinctNeighborsAcrossContinuationPages() {
		int repeatedContexts = 70_000;
		int trailingNeighbors = 10_000;
		long repeatedNeighbor = id(1, 1_000_000);
		long[] neighbors = new long[repeatedContexts + trailingNeighbors];
		long[] contexts = new long[neighbors.length];
		for (int i = 0; i < repeatedContexts; i++) {
			neighbors[i] = repeatedNeighbor;
			long coordinate = i + 1L;
			contexts[i] = id(1, coordinate * coordinate);
		}
		for (int i = 0; i < trailingNeighbors; i++) {
			neighbors[repeatedContexts + i] = id(1, 1_000_001L + i);
		}

		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0,
				List.of(new Row(id(1, 77), neighbors, contexts)))) {
			assertThat(index.pageCount()).isGreaterThan(1);
			ImmutablePagedQuadCsfIndex.KeyCursor cursor = index.keyDomain(0, 0).cursor();
			assertThat(cursor.advance()).isTrue();
			assertThat(cursor.edgeCount()).isEqualTo(neighbors.length);
			assertThat(cursor.distinctNeighborCount()).isEqualTo(trailingNeighbors + 1L);
			assertThat(cursor.advance()).isFalse();
		}
	}

	@Test
	void partitionLookupBatchMatchesScalarForSortedSparseDuplicateAndShuffledKeys() {
		List<Row> rows = irregularRows(2_500);
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			long[] sorted = new long[384];
			for (int i = 0; i < sorted.length; i++) {
				int row = 400 + i / 3;
				sorted[i] = i % 3 == 2 ? rows.get(row).row + 2 : rows.get(row).row;
			}
			Arrays.sort(sorted);
			assertBatchEqualsScalar(index, lookup, sorted);

			long[] sparse = new long[64];
			for (int i = 0; i < sparse.length; i++) {
				sparse[i] = rows.get(i * 37).row;
			}
			assertBatchEqualsScalar(index, lookup, sparse);

			long[] shuffled = sorted.clone();
			Random random = new Random(0x5eed);
			for (int i = shuffled.length - 1; i > 0; i--) {
				int other = random.nextInt(i + 1);
				long swap = shuffled[i];
				shuffled[i] = shuffled[other];
				shuffled[other] = swap;
			}
			assertBatchEqualsScalar(index, lookup, shuffled);
		}
	}

	@Test
	void scalarPartitionProbesNeverBuildTheEphemeralPartitionDictionary() {
		List<Row> rows = irregularRows(2_500);
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			ImmutablePagedQuadCsfIndex.LookupCursor expectedCursor = new ImmutablePagedQuadCsfIndex.LookupCursor();
			try {
				for (int repetition = 0; repetition < 20; repetition++) {
					for (Row row : rows) {
						assertThat(lookup.find(row.row))
								.isEqualTo(index.findLocalReference(0, 0, row.row, expectedCursor));
					}
				}
			} finally {
				expectedCursor.close();
			}
			assertThat(lookup.exactDictionaryReady()).isFalse();
			assertThat(lookup.affine()).isFalse();
			assertThat(lookup.observedBatchCalls()).isZero();
			assertThat(lookup.observedBatchProbes()).isZero();
		}
	}

	@Test
	void onlyRepeatedUnsortedBatchesCanPromoteThePartitionDictionary() {
		List<Row> rows = irregularRows(2_500);
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			long[] probes = new long[5_000];
			long[] references = new long[probes.length];
			for (int i = 0; i < probes.length; i++) {
				probes[i] = rows.get(i * 37 % rows.size()).row;
			}
			lookup.findBatch(probes, 0, probes.length, references, 0);
			assertThat(lookup.exactDictionaryReady()).isFalse();
			assertThat(lookup.observedBatchCalls()).isEqualTo(1);
			assertThat(lookup.observedBatchProbes()).isEqualTo(probes.length);

			long refusalsBefore = CsfAdaptiveMemory.refusals();
			lookup.findBatch(probes, 0, probes.length, references, 0);
			assertThat(lookup.exactDictionaryReady() || lookup.affine()
					|| CsfAdaptiveMemory.refusals() > refusalsBefore).isTrue();
		}
	}

	@Test
	void sortedMergeBatchesDoNotHeatThePartitionDictionary() {
		List<Row> rows = irregularRows(2_500);
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			long[] probes = new long[512];
			long[] references = new long[probes.length];
			for (int i = 0; i < probes.length; i++) {
				probes[i] = rows.get(400 + i / 4).row;
			}
			for (int repetition = 0; repetition < 32; repetition++) {
				lookup.findBatch(probes, 0, probes.length, references, 0);
			}
			assertThat(lookup.exactDictionaryReady()).isFalse();
			assertThat(lookup.observedBatchCalls()).isZero();
			assertThat(lookup.observedBatchProbes()).isZero();
		}
	}

	@Test
	void orderedBatchPlannerMergesCompactMorselsAndPointProbesSparseOnes() {
		List<Row> rows = irregularRows(12_000);
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			long[] compact = new long[9_000];
			long[] references = new long[compact.length];
			for (int i = 0; i < compact.length; i++) {
				compact[i] = rows.get(1_000 + i).row;
			}
			assertThat(lookup.findBatch(compact, 0, compact.length, references, 0)).isEqualTo(compact.length);
			assertThat(lookup.lastBatchEstimate().strategy())
					.isEqualTo(ImmutablePagedQuadCsfIndex.PartitionLookup.BatchStrategy.ORDERED_MERGE);
			assertThat(lookup.lastBatchEstimate().morsels()).isEqualTo(2);
			assertThat(lookup.lastBatchEstimate().mergeWork()).isLessThan(lookup.lastBatchEstimate().pointWork());

			long[] sparse = new long[64];
			for (int i = 0; i < sparse.length; i++) {
				sparse[i] = rows.get(i * 180).row;
			}
			assertThat(lookup.findBatch(sparse, 0, sparse.length, references, 0)).isEqualTo(sparse.length);
			assertThat(lookup.lastBatchEstimate().strategy())
					.isEqualTo(ImmutablePagedQuadCsfIndex.PartitionLookup.BatchStrategy.POINT_PROBES);
			assertThat(lookup.lastBatchEstimate().pointWork()).isLessThan(lookup.lastBatchEstimate().mergeWork());
		}
	}

	@Test
	void affinePromotionVerifiesEveryKeyBeforeActivating() {
		List<Row> rows = new ArrayList<>();
		for (int i = 0; i < 700; i++) {
			long payload = 100L + i * 4L + (i == 351 ? 1 : 0);
			rows.add(new Row(id(1, payload), new long[] { id(1, 10_000L + i) }, new long[] { 0 }));
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows);
				ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0)) {
			long[] probes = new long[4_096];
			long[] references = new long[probes.length];
			for (int i = 0; i < probes.length; i++) {
				probes[i] = rows.get(i * 37 % rows.size()).row;
			}
			lookup.findBatch(probes, 0, probes.length, references, 0);
			lookup.findBatch(probes, 0, probes.length, references, 0);
			assertThat(lookup.affine()).isFalse();
			for (Row row : rows) {
				assertThat(lookup.find(row.row)).isEqualTo(index.findLocalReference(0, 0, row.row));
			}
		}
	}

	@Test
	void partitionLookupReleasesAdaptiveClaimOnClose() {
		List<Row> rows = irregularRows(2_500);
		long before = CsfAdaptiveMemory.claimedBytes();
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			ImmutablePagedQuadCsfIndex.PartitionLookup lookup = index.partitionLookup(0, 0);
			long[] probes = new long[5_000];
			long[] references = new long[probes.length];
			for (int i = 0; i < probes.length; i++) {
				probes[i] = rows.get(i * 37 % rows.size()).row;
			}
			lookup.findBatch(probes, 0, probes.length, references, 0);
			lookup.findBatch(probes, 0, probes.length, references, 0);
			if (lookup.exactDictionaryReady()) {
				assertThat(CsfAdaptiveMemory.claimedBytes()).isGreaterThan(before);
			}
			lookup.close();
			assertThat(CsfAdaptiveMemory.claimedBytes()).isEqualTo(before);
		}
	}

	@Test
	void splitsOneSupernodeIntoLinkedFibreExtents() {
		int count = 80_000;
		long[] neighbours = new long[count];
		long[] contexts = new long[count];
		for (int i = 0; i < count; i++) {
			neighbours[i] = id(1, 1_000_000L + i);
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0,
				List.of(new Row(id(1, 77), neighbours, contexts)))) {
			assertThat(index.pageCount()).isGreaterThan(1);
			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			index.resolve(index.findLocalReference(0, 0, id(1, 77)), cursor);
			assertThat(cursor.edgeCount()).isEqualTo(count);
			assertThat(cursor.neighborAt(count - 1L)).isEqualTo(neighbours[count - 1]);
			assertThat(cursor.lowerBound(0, neighbours[70_000], 0)).isEqualTo(70_000);
		}
	}

	@Test
	void scalarAccessOnAMultiPageRunLoadsOnePageNotTheWholeChain() {
		int count = 80_000;
		long[] neighbours = new long[count];
		long[] contexts = new long[count];
		for (int i = 0; i < count; i++) {
			neighbours[i] = id(1, 1_000_000L + i);
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0,
				List.of(new Row(id(1, 77), neighbours, contexts)))) {
			assertThat(index.pageCount()).isGreaterThan(1);
			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			index.resolve(index.findLocalReference(0, 0, id(1, 77)), cursor);

			long decodesBefore = CompactCsfPageReader.DECODES.sum();
			for (long ordinal = 0; ordinal < count; ordinal += 997) {
				assertThat(cursor.neighborAt(ordinal)).isEqualTo(neighbours[(int) ordinal]);
			}
			long decodes = CompactCsfPageReader.DECODES.sum() - decodesBefore;
			assertThat(decodes)
					.as("an ascending scalar sweep must decode each extent page at most once, "
							+ "not re-walk the chain from its first page per access")
					.isLessThanOrEqualTo(index.pageCount());
		}
	}

	@Test
	void splitsOneNeighborFibreAtContextCoordinateBoundaries() {
		int count = 80_000;
		long neighbor = id(1, 1_000_000);
		long[] neighbors = new long[count];
		long[] contexts = new long[count];
		for (int i = 0; i < count; i++) {
			neighbors[i] = neighbor;
			long coordinate = i + 1L;
			contexts[i] = id(1, coordinate * coordinate);
		}
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0,
				List.of(new Row(id(1, 88), neighbors, contexts)))) {
			assertThat(index.pageCount()).isGreaterThan(1);
			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			index.resolve(index.findLocalReference(0, 0, id(1, 88)), cursor);
			assertThat(cursor.edgeCount()).isEqualTo(count);
			assertThat(cursor.neighborAt(count - 1L)).isEqualTo(neighbor);
			assertThat(cursor.contextAt(count - 1L)).isEqualTo(contexts[count - 1]);
			assertThat(cursor.lowerBound(0, neighbor, contexts[70_000])).isEqualTo(70_000);
		}
	}

	@Test
	void materializationRejectsAnyDifferenceFromTheExactSizingPass() {
		ImmutablePagedQuadCsfIndex.BuildPlan plan;
		try (ImmutablePagedQuadCsfIndex.Builder sizing = ImmutablePagedQuadCsfIndex.sizingBuilder(1)) {
			sizing.beginRow(0, 0, id(1, 1));
			sizing.pair(id(1, 10), 0);
			sizing.endRow();
			plan = sizing.finishPlan();
		}

		try (ImmutablePagedQuadCsfIndex.Builder materializing = ImmutablePagedQuadCsfIndex
				.materializingBuilder(plan)) {
			materializing.beginRow(0, 0, id(1, 1));
			materializing.pair(id(1, 10), 0);
			materializing.pair(id(1, 11), 0);
			materializing.endRow();
			assertThatThrownBy(materializing::finishIndex).isInstanceOf(IllegalStateException.class);
		}
	}

	@Test
	void randomizedRowsRoundTripAcrossSizingAndMaterializationPasses() {
		Random random = new Random(8_917_234);
		List<Row> rows = new ArrayList<>();
		for (int row = 0; row < 1_500; row++) {
			int fibres = 1 + random.nextInt(12);
			List<Long> neighbours = new ArrayList<>();
			List<Long> contexts = new ArrayList<>();
			long neighbourPayload = 1;
			for (int fibre = 0; fibre < fibres; fibre++) {
				neighbourPayload += 1 + random.nextInt(20);
				long neighbour = id(1, neighbourPayload);
				int contextCount = 1 + random.nextInt(4);
				long contextPayload = 0;
				for (int context = 0; context < contextCount; context++) {
					contextPayload += 1 + random.nextInt(7);
					neighbours.add(neighbour);
					contexts.add(context == 0 && random.nextBoolean() ? 0 : id(1, contextPayload));
				}
			}
			rows.add(new Row(id(1, 10L + row * 2L), longs(neighbours), longs(contexts)));
		}

		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 2, rows)) {
			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			for (int row = 0; row < rows.size(); row += 31) {
				Row expected = rows.get(row);
				index.resolve(index.findLocalReference(0, 2, expected.row), cursor);
				assertThat(cursor.edgeCount()).isEqualTo(expected.neighbours.length);
				for (int ordinal = 0; ordinal < expected.neighbours.length; ordinal++) {
					assertThat(cursor.neighborAt(ordinal)).isEqualTo(expected.neighbours[ordinal]);
					assertThat(cursor.contextAt(ordinal)).isEqualTo(expected.contexts[ordinal]);
				}
			}
		}
	}

	@Test
	void emptyPredicatePartitionsAllocateNoNativeMemory() {
		try (ImmutablePagedQuadCsfIndex.Builder sizing = ImmutablePagedQuadCsfIndex.sizingBuilder(3)) {
			ImmutablePagedQuadCsfIndex.BuildPlan plan = sizing.finishPlan();
			assertThat(plan.pageCount()).isZero();
			assertThat(plan.nativeBytes()).isZero();
			try (ImmutablePagedQuadCsfIndex.Builder materializing = ImmutablePagedQuadCsfIndex
					.materializingBuilder(plan);
					ImmutablePagedQuadCsfIndex index = materializing.finishIndex()) {
				assertThat(index.pageCount()).isZero();
				assertThat(index.findLocalReference(0, 0, 1)).isZero();
			}
		}
	}

	@Test
	void routesAllPlanesAndPredicatesThroughOneImmutableRoot() {
		int predicates = 2;
		List<Row> rows = irregularRows(96);
		ImmutablePagedQuadCsfIndex.BuildPlan plan;
		try (ImmutablePagedQuadCsfIndex.Builder sizing = ImmutablePagedQuadCsfIndex.sizingBuilder(predicates)) {
			for (int predicate = 0; predicate < predicates; predicate++) {
				for (int plane = 0; plane < 4; plane++) {
					feed(sizing, predicate, plane, rows);
				}
			}
			plan = sizing.finishPlan();
		}
		try (ImmutablePagedQuadCsfIndex.Builder materializing = ImmutablePagedQuadCsfIndex.materializingBuilder(plan)) {
			for (int predicate = 0; predicate < predicates; predicate++) {
				for (int plane = 0; plane < 4; plane++) {
					feed(materializing, predicate, plane, rows);
				}
			}
			try (ImmutablePagedQuadCsfIndex index = materializing.finishIndex()) {
				for (int predicate = 0; predicate < predicates; predicate++) {
					for (int plane = 0; plane < 4; plane++) {
						ImmutablePagedQuadCsfIndex.LookupCursor cursor = new ImmutablePagedQuadCsfIndex.LookupCursor();
						for (int row = 0; row < rows.size(); row += 7) {
							assertThat(index.findLocalReference(predicate, plane, rows.get(row).row, cursor))
									.isNotZero();
							assertThat(index.findLocalReference(predicate, plane, rows.get(row).row + 1, cursor))
									.isZero();
						}
					}
				}
			}
		}
	}

	@Test
	void plannedAndMaterializedRoutingBytesAreExactAndCloseEveryCharge() {
		String previous = System.getProperty(SHARD_TARGET_PAGES_PROPERTY);
		System.setProperty(SHARD_TARGET_PAGES_PROPERTY, "2");
		TrackingBudget budget = new TrackingBudget();
		try {
			List<Row> rows = irregularRows(6_000);
			ImmutablePagedQuadCsfIndex.BuildPlan plan;
			try (ImmutablePagedQuadCsfIndex.Builder sizing = ImmutablePagedQuadCsfIndex.sizingBuilder(1)) {
				feed(sizing, 0, 0, rows);
				plan = sizing.finishPlan();
			}
			assertThat(plan.pageCount()).isGreaterThan(2);
			assertThat(plan.shardCount()).isGreaterThan(1);
			try (ImmutablePagedQuadCsfIndex.Builder materializing = ImmutablePagedQuadCsfIndex
					.materializingBuilder(plan, budget)) {
				feed(materializing, 0, 0, rows);
				try (ImmutablePagedQuadCsfIndex index = materializing.finishIndex()) {
					assertThat(index.nativeBytes()).isEqualTo(plan.nativeBytes());
					assertThat(index.modeledJavaBytes())
							.isEqualTo(
									plan.modeledJavaBytes() - (long) plan.shardCount() * CsfShard.MODELED_JAVA_BYTES);
					assertThat(budget.liveBytes).hasValue(plan.totalModeledBytes());
					assertThat(index.routingDirectoryBytesForTest()).isPositive();
				}
			}
			assertThat(budget.liveBytes).hasValue(0);
		} finally {
			if (previous == null) {
				System.clearProperty(SHARD_TARGET_PAGES_PROPERTY);
			} else {
				System.setProperty(SHARD_TARGET_PAGES_PROPERTY, previous);
			}
		}
	}

	@Test
	void defaultShardRoutingLayoutStaysBelowFiveBytesPerPage() {
		long rootBytes = ImmutablePagedQuadCsfIndex.rootRoutingDirectoryBytesForTest(1,
				new int[] { 1, 0, 0, 0 });
		long nativeBytes = CsfShard.routingLayoutBytesFor(256);
		assertThat(Math.addExact(rootBytes, nativeBytes)).isLessThanOrEqualTo(5L * 256);
	}

	@Test
	void rewritesOnlyAffectedShardsAndRetainsOldSnapshot() {
		String previous = System.getProperty(SHARD_TARGET_PAGES_PROPERTY);
		System.setProperty(SHARD_TARGET_PAGES_PROPERTY, "4");
		try {
			rewritesOnlyAffectedShardsAndRetainsOldSnapshotWithSmallShards();
		} finally {
			if (previous == null) {
				System.clearProperty(SHARD_TARGET_PAGES_PROPERTY);
			} else {
				System.setProperty(SHARD_TARGET_PAGES_PROPERTY, previous);
			}
		}
	}

	@Test
	void rewriteUpdatesInsertsDeletesAndAppendsAPredicatePartition() {
		List<Row> rows = List.of(
				new Row(id(1, 100), new long[] { id(1, 1_000) }, new long[] { 0 }),
				new Row(id(1, 102), new long[] { id(1, 1_002) }, new long[] { 0 }),
				new Row(id(1, 104), new long[] { id(1, 1_004) }, new long[] { 0 }));
		TrackingBudget budget = new TrackingBudget();
		try (ImmutablePagedQuadCsfIndex oldIndex = build(1, 0, 0, rows)) {
			Updates updates = new Updates(
					new int[] { 0, 0, 0, 4 },
					new long[] { id(1, 100), id(1, 101), id(1, 102), id(1, 77) },
					new boolean[] { false, false, true, false },
					new long[][] {
							{ id(1, 9_000), id(1, 9_001) },
							{ id(1, 1_001) },
							{},
							{ id(1, 7_700) }
					},
					new long[][] {
							{ 0, id(1, 9) },
							{ 0 },
							{},
							{ id(1, 7) }
					});

			ImmutablePagedQuadCsfIndex.RewriteResult rewrite = oldIndex.rewrite(2, updates, budget);
			try (ImmutablePagedQuadCsfIndex rewritten = rewrite.index()) {
				ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
				rewritten.resolve(rewritten.findLocalReference(0, 0, id(1, 100)), cursor);
				assertThat(cursor.edgeCount()).isEqualTo(2);
				assertThat(cursor.neighborAt(1)).isEqualTo(id(1, 9_001));
				assertThat(rewritten.findLocalReference(0, 0, id(1, 101))).isNotZero();
				assertThat(rewritten.findLocalReference(0, 0, id(1, 102))).isZero();
				assertThat(rewritten.findLocalReference(0, 0, id(1, 104))).isNotZero();
				assertThat(rewritten.findLocalReference(1, 0, id(1, 77))).isNotZero();

				oldIndex.resolve(oldIndex.findLocalReference(0, 0, id(1, 102)), cursor);
				assertThat(cursor.neighborAt(0)).isEqualTo(id(1, 1_002));
			}
			assertThat(budget.liveBytes).hasValue(0);
		}
	}

	@Test
	void failedRewriteReleasesEveryCandidateReservationAndLeavesOldRootUsable() {
		List<Row> rows = new ArrayList<>();
		for (int row = 0; row < 2_000; row++) {
			rows.add(new Row(id(1, 100L + row * 2L), new long[] { id(1, 10_000L + row) }, new long[] { 0 }));
		}
		RefusingBudget budget = new RefusingBudget(2);
		try (ImmutablePagedQuadCsfIndex oldIndex = build(1, 0, 0, rows)) {
			Updates updates = new Updates(new int[] { 0 }, new long[] { rows.get(0).row }, new boolean[] { false },
					new long[][] { { id(1, 999_999) } }, new long[][] { { 0 } });

			assertThatThrownBy(() -> oldIndex.rewrite(1, updates, budget))
					.isInstanceOf(IllegalStateException.class)
					.hasMessageContaining("refused");
			assertThat(budget.liveBytes).hasValue(0);

			ImmutablePagedQuadCsfIndex.RowCursor cursor = new ImmutablePagedQuadCsfIndex.RowCursor();
			oldIndex.resolve(oldIndex.findLocalReference(0, 0, rows.get(0).row), cursor);
			assertThat(cursor.neighborAt(0)).isEqualTo(rows.get(0).neighbours[0]);
		}
	}

	@Test
	void repeatedPageRewritesFlattenShardDependencyChains() {
		List<Row> rows = new ArrayList<>();
		for (int row = 0; row < 5_000; row++) {
			rows.add(new Row(id(1, 100L + row * 2L), new long[] { id(1, 10_000L + row) }, new long[] { 0 }));
		}
		TrackingBudget budget = new TrackingBudget();
		ImmutablePagedQuadCsfIndex current = build(1, 0, 0, rows);
		try {
			for (int rewrite = 0; rewrite < 40; rewrite++) {
				Updates updates = new Updates(new int[] { 0 }, new long[] { rows.get(0).row },
						new boolean[] { false }, new long[][] { { id(1, 1_000_000L + rewrite) } },
						new long[][] { { 0 } });
				ImmutablePagedQuadCsfIndex replacement = current.rewrite(1, updates, budget).index();
				current.close();
				current = replacement;
				assertThat(current.maxShardChainDepthForTest()).isLessThanOrEqualTo(32);
			}
		} finally {
			current.close();
		}
		assertThat(budget.liveBytes).hasValue(0);
	}

	private static void rewritesOnlyAffectedShardsAndRetainsOldSnapshotWithSmallShards() {
		List<Row> rows = new ArrayList<>();
		for (int row = 0; row < 12; row++) {
			long[] neighbours = new long[8_000];
			long[] contexts = new long[neighbours.length];
			long base = 10_000_000L + (long) row * 100_000L;
			for (int i = 0; i < neighbours.length; i++) {
				neighbours[i] = id(1, base + i * 3L);
			}
			rows.add(new Row(id(1, 100L + row * 2L), neighbours, contexts));
		}
		TrackingBudget budget = new TrackingBudget();
		try (ImmutablePagedQuadCsfIndex oldIndex = build(1, 0, 0, rows)) {
			assertThat(oldIndex.shardCount()).isGreaterThanOrEqualTo(2);
			Row changed = rows.get(10);
			long[] replacementNeighbours = { id(1, 777), id(1, 888) };
			long[] replacementContexts = { 0, id(1, 9) };
			Updates updates = new Updates(new int[] { 0 }, new long[] { changed.row }, new boolean[] { false },
					new long[][] { replacementNeighbours }, new long[][] { replacementContexts });

			ImmutablePagedQuadCsfIndex.RewriteResult rewrite = oldIndex.rewrite(1, updates, budget);
			try (ImmutablePagedQuadCsfIndex newIndex = rewrite.index()) {
				assertThat(rewrite.sharedShardCount()).isPositive();
				assertThat(rewrite.replacedShardCount()).isPositive();
				assertThat(rewrite.allocatedShardCount()).isPositive();

				ImmutablePagedQuadCsfIndex.RowCursor oldCursor = new ImmutablePagedQuadCsfIndex.RowCursor();
				oldIndex.resolve(oldIndex.findLocalReference(0, 0, changed.row), oldCursor);
				assertThat(oldCursor.edgeCount()).isEqualTo(changed.neighbours.length);

				ImmutablePagedQuadCsfIndex.RowCursor newCursor = new ImmutablePagedQuadCsfIndex.RowCursor();
				newIndex.resolve(newIndex.findLocalReference(0, 0, changed.row), newCursor);
				assertThat(newCursor.edgeCount()).isEqualTo(2);
				assertThat(newCursor.neighborAt(1)).isEqualTo(replacementNeighbours[1]);
				assertThat(newCursor.contextAt(1)).isEqualTo(replacementContexts[1]);

				Row unchanged = rows.get(rows.size() - 1);
				newIndex.resolve(newIndex.findLocalReference(0, 0, unchanged.row), newCursor);
				assertThat(newCursor.edgeCount()).isEqualTo(unchanged.neighbours.length);
				assertThat(budget.liveBytes).hasPositiveValue();
			}
			assertThat(budget.liveBytes).hasValue(0);
		}
	}

	/**
	 * The key cursor's scalar path decodes the neighbor eagerly and the context lazily (a neighbor-only consumer must
	 * never pay the context prefix-sum walk), with a separate context cache ordinal so repeated and interleaved
	 * accesses stay exact. Fixtures cover multi-context fibers, a multi-page neighbor chain, a multi-page context
	 * chain, and copyPairs repositioning the shared extent page between scalar reads.
	 */
	@Test
	void keyCursorScalarNeighborAndLazyContextStayExactUnderInterleaving() {
		int supernode = 80_000;
		long[] fanNeighbours = new long[supernode];
		long[] fanContexts = new long[supernode];
		long[] contextNeighbours = new long[supernode];
		long[] contextContexts = new long[supernode];
		for (int i = 0; i < supernode; i++) {
			fanNeighbours[i] = id(1, 1_000_000L + i);
			contextNeighbours[i] = id(1, 5_000_000);
			long coordinate = i + 1L;
			contextContexts[i] = id(1, coordinate * coordinate);
		}
		long multiNeighbour = id(1, 900);
		List<Row> rows = List.of(
				new Row(id(1, 10),
						new long[] { multiNeighbour, multiNeighbour, multiNeighbour, id(1, 901) },
						new long[] { 0, id(1, 4), id(1, 8), 0 }),
				new Row(id(1, 50), fanNeighbours, fanContexts),
				new Row(id(1, 90), contextNeighbours, contextContexts),
				new Row(id(1, 120), new long[] { id(1, 7_000_000) }, new long[] { id(1, 3) }));
		try (ImmutablePagedQuadCsfIndex index = build(1, 0, 0, rows)) {
			assertThat(index.pageCount()).isGreaterThan(2);
			ImmutablePagedQuadCsfIndex.KeyCursor cursor = index.keyDomain(0, 0).cursor();
			int visited = 0;
			while (cursor.advance()) {
				Row expected = rows.get(visited++);
				assertThat(cursor.key()).isEqualTo(expected.row);
				int count = expected.neighbours.length;
				assertThat(cursor.edgeCount()).isEqualTo(count);
				long[] neighbours = new long[count];
				long[] contexts = new long[count];
				assertThat(cursor.copyPairs(0, count, neighbours, 0, contexts, 0)).isEqualTo(count);
				assertThat(neighbours).containsExactly(expected.neighbours);
				assertThat(contexts).containsExactly(expected.contexts);
				int stride = Math.max(1, count / 17);
				// Neighbor-only sweep: no contextAt call anywhere on this pass.
				for (long ordinal = 0; ordinal < count; ordinal += stride) {
					assertThat(cursor.neighborAt(ordinal)).isEqualTo(expected.neighbours[(int) ordinal]);
				}
				// Context-only sweep (context decoded on demand, no prior neighborAt at these ordinals).
				for (long ordinal = count - 1; ordinal >= 0; ordinal -= stride) {
					assertThat(cursor.contextAt(ordinal)).isEqualTo(expected.contexts[(int) ordinal]);
				}
				// Interleavings: repeat at one ordinal, jump back, and reposition the extent page via copyPairs
				// between scalar reads of the same ordinal.
				long probe = count - 1;
				assertThat(cursor.neighborAt(probe)).isEqualTo(expected.neighbours[(int) probe]);
				assertThat(cursor.contextAt(probe)).isEqualTo(expected.contexts[(int) probe]);
				assertThat(cursor.contextAt(probe)).isEqualTo(expected.contexts[(int) probe]);
				assertThat(cursor.contextAt(0)).isEqualTo(expected.contexts[0]);
				assertThat(cursor.neighborAt(0)).isEqualTo(expected.neighbours[0]);
				assertThat(cursor.copyPairs(0, Math.min(8, count), neighbours, 0, contexts, 0))
						.isEqualTo(Math.min(8, count));
				assertThat(cursor.contextAt(probe)).isEqualTo(expected.contexts[(int) probe]);
				assertThat(cursor.neighborAt(probe)).isEqualTo(expected.neighbours[(int) probe]);
			}
			assertThat(visited).isEqualTo(rows.size());
		}
	}

	private static ImmutablePagedQuadCsfIndex build(int predicates, long predicate, int plane, List<Row> rows) {
		ImmutablePagedQuadCsfIndex.BuildPlan plan;
		try (ImmutablePagedQuadCsfIndex.Builder sizing = ImmutablePagedQuadCsfIndex.sizingBuilder(predicates)) {
			feed(sizing, predicate, plane, rows);
			plan = sizing.finishPlan();
		}
		try (ImmutablePagedQuadCsfIndex.Builder materializing = ImmutablePagedQuadCsfIndex
				.materializingBuilder(plan)) {
			feed(materializing, predicate, plane, rows);
			return materializing.finishIndex();
		}
	}

	private static List<Row> irregularRows(int count) {
		List<Row> rows = new ArrayList<>(count);
		long payload = 100;
		for (int i = 0; i < count; i++) {
			payload += 2L + (i * 17L % 11L);
			rows.add(new Row(id(1, payload), new long[] { id(1, 1_000_000L + i) }, new long[] { 0 }));
		}
		return rows;
	}

	private static void assertBatchEqualsScalar(ImmutablePagedQuadCsfIndex index,
			ImmutablePagedQuadCsfIndex.PartitionLookup lookup, long[] keys) {
		long[] actual = new long[keys.length];
		int found = lookup.findBatch(keys, 0, keys.length, actual, 0);
		int expectedFound = 0;
		for (int i = 0; i < keys.length; i++) {
			long expected = index.findLocalReference(0, 0, keys[i]);
			assertThat(actual[i]).isEqualTo(expected);
			if (expected != 0) {
				expectedFound++;
			}
		}
		assertThat(found).isEqualTo(expectedFound);
	}

	private static void feed(ImmutablePagedQuadCsfIndex.Builder builder, long predicate, int plane, List<Row> rows) {
		for (Row row : rows) {
			builder.beginRow(predicate, plane, row.row);
			for (int ordinal = 0; ordinal < row.neighbours.length; ordinal++) {
				builder.pair(row.neighbours[ordinal], row.contexts[ordinal]);
			}
			builder.endRow();
		}
	}

	private static long id(int type, long payload) {
		return payload << 7 | (long) type << 1;
	}

	private static long[] longs(List<Long> source) {
		long[] values = new long[source.size()];
		for (int i = 0; i < values.length; i++) {
			values[i] = source.get(i);
		}
		return values;
	}

	private static final class TrackingBudget implements ImmutablePagedQuadCsfIndex.MemoryBudget {
		private final AtomicLong liveBytes = new AtomicLong();

		@Override
		public ImmutablePagedQuadCsfIndex.MemoryReservation reserve(long nativeBytes, long modeledJavaBytes) {
			long total = Math.addExact(nativeBytes, modeledJavaBytes);
			liveBytes.addAndGet(total);
			AtomicBoolean closed = new AtomicBoolean();
			return () -> {
				if (closed.compareAndSet(false, true)) {
					liveBytes.addAndGet(-total);
				}
			};
		}
	}

	private static final class RefusingBudget implements ImmutablePagedQuadCsfIndex.MemoryBudget {
		private final int refusedCall;
		private final AtomicLong liveBytes = new AtomicLong();
		private int calls;

		private RefusingBudget(int refusedCall) {
			this.refusedCall = refusedCall;
		}

		@Override
		public ImmutablePagedQuadCsfIndex.MemoryReservation reserve(long nativeBytes, long modeledJavaBytes) {
			if (++calls == refusedCall) {
				throw new IllegalStateException("test reservation refused");
			}
			long total = Math.addExact(nativeBytes, modeledJavaBytes);
			liveBytes.addAndGet(total);
			AtomicBoolean closed = new AtomicBoolean();
			return () -> {
				if (closed.compareAndSet(false, true)) {
					liveBytes.addAndGet(-total);
				}
			};
		}
	}

	private static final class Updates implements ImmutablePagedQuadCsfIndex.RowUpdateSource {
		private final int[] partitions;
		private final long[] rows;
		private final boolean[] tombstones;
		private final long[][] neighbours;
		private final long[][] contexts;

		private Updates(int[] partitions, long[] rows, boolean[] tombstones, long[][] neighbours, long[][] contexts) {
			this.partitions = partitions;
			this.rows = rows;
			this.tombstones = tombstones;
			this.neighbours = neighbours;
			this.contexts = contexts;
		}

		@Override
		public int size() {
			return rows.length;
		}

		@Override
		public int partitionAt(int index) {
			return partitions[index];
		}

		@Override
		public long rowAt(int index) {
			return rows[index];
		}

		@Override
		public boolean tombstoneAt(int index) {
			return tombstones[index];
		}

		@Override
		public long pairCountAt(int index) {
			return tombstones[index] ? 0 : neighbours[index].length;
		}

		@Override
		public int copyPairsAt(int index, long fromOrdinal, int length, long[] neighbourTarget, int neighbourOffset,
				long[] contextTarget, int contextOffset) {
			int from = Math.toIntExact(fromOrdinal);
			int copied = Math.min(length, neighbours[index].length - from);
			System.arraycopy(neighbours[index], from, neighbourTarget, neighbourOffset, copied);
			System.arraycopy(contexts[index], from, contextTarget, contextOffset, copied);
			return copied;
		}
	}

	private record Row(long row, long[] neighbours, long[] contexts) {
		private Row {
			if (neighbours.length == 0 || neighbours.length != contexts.length) {
				throw new IllegalArgumentException("row columns must be non-empty and aligned");
			}
		}
	}
}
