/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.helpers;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.CALLS_REAL_METHODS;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.withSettings;

import java.lang.ref.Cleaner;
import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.rdf4j.common.concurrent.locks.diagnostics.ConcurrentCleaner;
import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.sail.SailException;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.parallel.Isolated;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.junit.jupiter.api.parallel.Resources;

@Timeout(60)
@ResourceLock(Resources.SYSTEM_PROPERTIES)
@Isolated("Controls one process-wide cleaner lane")
class AbstractSailConnectionIterationCleanupTest {

	private static final String DEBUG_PROPERTY = "org.eclipse.rdf4j.repository.debug";
	private String previousDebug;

	@BeforeEach
	void disableDebug() {
		previousDebug = System.setProperty(DEBUG_PROPERTY, "false");
	}

	@AfterEach
	void restoreDebug() {
		if (previousDebug == null) {
			System.clearProperty(DEBUG_PROPERTY);
		} else {
			System.setProperty(DEBUG_PROPERTY, previousDebug);
		}
	}

	@Test
	void connectionCloseCleansAbandonedIterationsBeforeCleanerLaneRuns() throws InterruptedException {
		AbstractSailConnection connection = newConnection();
		CountingIteration delegate = new CountingIteration();
		ReferenceQueue<CloseableIteration<Integer>> collected = new ReferenceQueue<>();
		try (BlockedCleanerLane cleanerLane = new BlockedCleanerLane()) {
			WeakReference<CloseableIteration<Integer>> reference = registerAbandoned(connection, delegate, collected);
			System.gc();
			assertThat(collected.remove(TimeUnit.SECONDS.toMillis(10)))
					.as("the registered outer iteration was collected")
					.isSameAs(reference);
			assertThat(delegate.closes.get()).as("the cleaner lane cannot yet close the delegate").isZero();

			assertThatCode(connection::close).doesNotThrowAnyException();

			assertThat(delegate.closes.get()).as("owner close completes abandoned cleanup exactly once").isOne();
			assertThat(connection.hasActiveIterations()).isFalse();
			assertThat(cleanerLane.release.getCount()).as("cleanup completed while the cleaner remains blocked")
					.isOne();
		} finally {
			connection.close();
		}
	}

	@Test
	void reachableUnclosedIterationStillRejectsConnectionClose() {
		AbstractSailConnection connection = newConnection();
		CountingIteration delegate = new CountingIteration();
		CloseableIteration<Integer> iteration = connection.registerIteration(delegate);
		try {
			assertThatThrownBy(connection::close).isInstanceOf(SailException.class)
					.hasMessage("Connection closed before all iterations were closed.");
			assertThat(delegate.closes.get()).isZero();
		} finally {
			iteration.close();
			connection.close();
		}
		assertThat(delegate.closes.get()).isOne();
	}

	@Test
	void debugConnectionStillClosesAndReportsUnclosedIteration() {
		System.setProperty(DEBUG_PROPERTY, "true");
		AbstractSailConnection connection = newConnection();
		CountingIteration delegate = new CountingIteration();
		CloseableIteration<Integer> iteration = connection.registerIteration(delegate);
		try {
			assertThatThrownBy(connection::close).isInstanceOf(SailException.class)
					.hasMessageStartingWith("Connection closed before all iterations were closed: ");
			assertThat(delegate.closes.get()).isOne();
			assertThat(connection.hasActiveIterations()).isFalse();
		} finally {
			iteration.close();
			connection.close();
		}
		assertThat(delegate.closes.get()).isOne();
	}

	@Test
	void explicitCloseFailureStillCompletesIterationAccounting() {
		AbstractSailConnection connection = newConnection();
		CountingIteration delegate = new CountingIteration() {
			@Override
			public void close() {
				super.close();
				throw new IllegalStateException("delegate close failed");
			}
		};
		CloseableIteration<Integer> iteration = connection.registerIteration(delegate);
		assertThatThrownBy(iteration::close).isInstanceOf(IllegalStateException.class)
				.hasMessage("delegate close failed");
		assertThat(connection.hasActiveIterations()).isFalse();
		assertThatCode(connection::close).doesNotThrowAnyException();
		iteration.close();
		assertThat(delegate.closes.get()).isOne();
	}

	@Test
	void exhaustionCompletesIterationAccountingWithoutExplicitWrapperClose() {
		AbstractSailConnection connection = newConnection();
		CountingIteration delegate = new CountingIteration();
		CloseableIteration<Integer> iteration = connection.registerIteration(delegate);
		assertThat(iteration.hasNext()).isFalse();
		assertThat(connection.hasActiveIterations()).isFalse();
		assertThatCode(connection::close).doesNotThrowAnyException();
		iteration.close();
		assertThat(delegate.closes.get()).isOne();
	}

	@Test
	void explicitCleanupWaitsForAlreadyStartedCleanerClose() throws Exception {
		CountDownLatch closeStarted = new CountDownLatch(1);
		CountDownLatch ownerStarted = new CountDownLatch(1);
		CountDownLatch releaseClose = new CountDownLatch(1);
		AtomicBoolean closeCompleted = new AtomicBoolean();
		CountingIteration delegate = new CountingIteration() {
			@Override
			public void close() {
				if (closes.incrementAndGet() == 1) {
					closeStarted.countDown();
					await(releaseClose);
					closeCompleted.set(true);
				}
			}
		};
		CapturingCleaner cleaner = new CapturingCleaner();
		CleanerIteration<Integer> iteration = new CleanerIteration<>(delegate, cleaner);
		try (ExecutorService executor = Executors.newFixedThreadPool(2)) {
			Future<?> cleaning = executor.submit(cleaner.registration::clean);
			try {
				assertTrue(closeStarted.await(10, TimeUnit.SECONDS), "the cleaner did not start delegate close");
				Future<?> ownerClosing = executor.submit(() -> {
					ownerStarted.countDown();
					iteration.close();
					assertThat(closeCompleted.get()).as("explicit cleanup returns only after delegate close completes")
							.isTrue();
				});
				assertTrue(ownerStarted.await(10, TimeUnit.SECONDS), "the explicit cleanup task did not start");
				releaseClose.countDown();
				cleaning.get(10, TimeUnit.SECONDS);
				ownerClosing.get(10, TimeUnit.SECONDS);
				assertThat(delegate.closes.get()).as("cleaner and owner share one completed close").isOne();
			} finally {
				releaseClose.countDown();
			}
		}
	}

	private static void await(CountDownLatch latch) {
		try {
			assertTrue(latch.await(30, TimeUnit.SECONDS), "delegate close release was not signalled");
		} catch (InterruptedException interrupted) {
			Thread.currentThread().interrupt();
			throw new AssertionError(interrupted);
		}
	}

	private static final class CapturingCleaner extends ConcurrentCleaner {
		Cleaner.Cleanable registration;

		@Override
		public Cleaner.Cleanable register(Object referent, Runnable action) {
			registration = super.register(referent, action);
			return registration;
		}
	}

	private static AbstractSailConnection newConnection() {
		AbstractSail sail = mock(AbstractSail.class);
		return mock(AbstractSailConnection.class, withSettings().useConstructor(sail)
				.defaultAnswer(CALLS_REAL_METHODS));
	}

	private static WeakReference<CloseableIteration<Integer>> registerAbandoned(AbstractSailConnection connection,
			CountingIteration delegate, ReferenceQueue<CloseableIteration<Integer>> collected) {
		CloseableIteration<Integer> iteration = connection.registerIteration(delegate);
		return new WeakReference<>(iteration, collected);
	}

	private static class CountingIteration implements CloseableIteration<Integer> {
		final AtomicInteger closes = new AtomicInteger();

		@Override
		public boolean hasNext() {
			return false;
		}

		@Override
		public Integer next() {
			return 1;
		}

		@Override
		public void remove() {
			throw new UnsupportedOperationException();
		}

		@Override
		public void close() {
			closes.incrementAndGet();
		}
	}

	private static final class BlockedCleanerLane implements AutoCloseable {
		private final CountDownLatch started = new CountDownLatch(1);
		final CountDownLatch release = new CountDownLatch(1);
		private final Cleaner.Cleanable blocker;

		BlockedCleanerLane() throws InterruptedException {
			// All ConcurrentCleaner instances share the lane selected for the registering thread. Registering an
			// unrelated abandoned object here blocks that lane without replacing or accessing its internal state.
			blocker = registerBlocker(new ConcurrentCleaner(), started, release);
			System.gc();
			try {
				assertTrue(started.await(10, TimeUnit.SECONDS), "the cleaner lane did not reach the latch");
			} catch (Throwable failure) {
				release.countDown();
				blocker.clean();
				throw failure;
			}
		}

		private static Cleaner.Cleanable registerBlocker(ConcurrentCleaner cleaner, CountDownLatch started,
				CountDownLatch release) {
			return cleaner.register(new Object(), () -> {
				started.countDown();
				try {
					if (!release.await(30, TimeUnit.SECONDS)) {
						throw new AssertionError("cleaner lane release was not signalled");
					}
				} catch (InterruptedException interrupted) {
					Thread.currentThread().interrupt();
					throw new AssertionError(interrupted);
				}
			});
		}

		@Override
		public void close() {
			release.countDown();
			blocker.clean();
		}
	}
}
