/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.shacl;

import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.NoSuchElementException;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.sail.InterruptedSailException;
import org.eclipse.rdf4j.sail.SailConnection;
import org.junit.jupiter.api.Test;

class ConnectionHelperTest {

	@Test
	void transferStatementsConvertsInterruptedIterationToInterruptedSailException() {
		SailConnection connection = mock(SailConnection.class);
		@SuppressWarnings("unchecked")
		CloseableIteration<? extends Statement> statements = mock(CloseableIteration.class);
		doReturn(statements).when(connection).getStatements(isNull(), isNull(), isNull(), anyBoolean());
		when(statements.hasNext()).thenReturn(true);
		when(statements.next()).thenAnswer(invocation -> {
			Thread.currentThread().interrupt();
			throw new NoSuchElementException("The iteration has been interrupted.");
		});

		try {
			assertThatExceptionOfType(InterruptedSailException.class)
					.isThrownBy(() -> ConnectionHelper.transferStatements(connection, (subject, predicate, object,
							context) -> {
						throw new AssertionError("No statement should be transferred after interrupt");
					}))
					.withCauseInstanceOf(NoSuchElementException.class);
			verify(statements).close();
		} finally {
			Thread.interrupted();
		}
	}

	@Test
	void transferStatementsKeepsNonInterruptNoSuchElementException() {
		SailConnection connection = mock(SailConnection.class);
		@SuppressWarnings("unchecked")
		CloseableIteration<? extends Statement> statements = mock(CloseableIteration.class);
		NoSuchElementException exception = new NoSuchElementException("empty");
		doReturn(statements).when(connection).getStatements(isNull(), isNull(), isNull(), anyBoolean());
		when(statements.hasNext()).thenReturn(true);
		when(statements.next()).thenThrow(exception);

		assertThatExceptionOfType(NoSuchElementException.class)
				.isThrownBy(() -> ConnectionHelper.transferStatements(connection, (subject, predicate, object,
						context) -> {
					throw new AssertionError("No statement should be transferred");
				}))
				.isSameAs(exception);
		verify(statements).close();
		verify(statements, never()).remove();
	}
}
