/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.model.impl;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Iterator;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.model.vocabulary.RDFS;
import org.junit.jupiter.api.Test;

public class AbstractMemoryOverflowModelTest {

	@Test
	public void removeTermIterationRemovesFromMemoryBackedFilteredSubjects() {
		TestMemoryOverflowModel model = new TestMemoryOverflowModel();
		SimpleValueFactory vf = SimpleValueFactory.getInstance();

		Resource firstSubject = vf.createBNode();
		Resource secondSubject = vf.createBNode();
		IRI predicate = RDF.TYPE;

		model.add(firstSubject, predicate, RDFS.RESOURCE);
		model.add(secondSubject, predicate, RDFS.RESOURCE);

		Model filtered = model.filter(null, predicate, RDFS.RESOURCE);
		Iterator<Resource> subjectsIterator = filtered.subjects().iterator();
		Resource removedSubject = subjectsIterator.next();

		subjectsIterator.remove();

		assertThat(model.contains(removedSubject, predicate, RDFS.RESOURCE)).isFalse();
		assertThat(model.size()).isEqualTo(1);
	}

	private static final class TestMemoryOverflowModel extends AbstractMemoryOverflowModel<LinkedHashModel> {

		private static final long serialVersionUID = -1455351084169029038L;

		@Override
		protected void overflowToDiskInner(Model memory) {
			throw new AssertionError("Disk overflow not expected in this test");
		}
	}
}
