/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Co-Pilot
package org.eclipse.rdf4j.sail.lmdb.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.ByteBuffer;

import org.eclipse.rdf4j.sail.lmdb.Chunks;
import org.junit.jupiter.api.Test;

class PairChunkCodecTest {

	@Test
	void pairsRoundTripSeekAndRewind() {
		ChunkOutput output = new ChunkOutput(Chunks.MAX_CHUNK_SIZE, 4, 0);
		output.addTuple(new long[] { 1, 2, 3, 4 });
		output.reset(2, 0);
		for (int i = 0; i < Chunks.MAX_CHUNK_SIZE; i++) {
			assertTrue(output.addTuple(new long[] { 11 + i / 8, 100 + i % 8 }));
		}
		ByteBuffer key = ByteBuffer.allocate(32);
		ByteBuffer value = ByteBuffer.allocate(1024);
		output.write(key, value);
		key.flip();
		value.flip();
		for (boolean cached : new boolean[] { false, true }) {
			ChunkInput input = cached ? new ChunkInput()
					: new ChunkInput(key.duplicate(), value.duplicate(), 2, 0);
			if (cached) {
				input.reset(key.duplicate(), value.duplicate(), 2, 0);
			}
			assertEquals(0, input.seek(new long[] { 12, 103 }));
			assertEquals(12, input.next()[0]);
			input.rewind();
			for (int i = 0; i < Chunks.MAX_CHUNK_SIZE; i++) {
				long[] pair = input.next();
				assertEquals(11 + i / 8, pair[0]);
				assertEquals(100 + i % 8, pair[1]);
			}
			assertNull(input.next());
			input.reset(key.duplicate(), value.duplicate(), 2, 0);
			assertEquals(-1, input.seek(new long[] { 15, 0 }));
			assertNull(input.next());
		}
	}
}
