/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.memory;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.junit.jupiter.api.Test;

public class MemoryStoreLmdbIndexOrderTest {

	@Test
	public void testOrderByLmdbIndexFailsOutsideLmdb() {
		SimpleValueFactory vf = SimpleValueFactory.getInstance();

		SailRepository repository = new SailRepository(new MemoryStore());
		repository.init();
		try {
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(vf.createIRI("urn:s1"), RDF.TYPE, vf.createIRI("urn:type1"));
				connection.add(vf.createIRI("urn:s2"), RDF.TYPE, vf.createIRI("urn:type2"));
			}

			try (SailRepositoryConnection connection = repository.getConnection()) {
				QueryEvaluationException error = assertThrows(QueryEvaluationException.class, () -> {
					try (TupleQueryResult result = connection
							.prepareTupleQuery("select ?s ?type where { ?s a ?type. } order by STABLE_INDEX(?s)")
							.evaluate()) {
						while (result.hasNext()) {
							result.next();
						}
					}
				});
				assertTrue(error.getMessage().contains("STABLE_INDEX"));
			}
		} finally {
			repository.shutDown();
		}
	}
}
