# Temp to reduce image size
FROM ubuntu:noble AS temp

ARG OTEL_JAVAAGENT_VERSION=2.14.0

RUN  apt-get clean && apt-get update && apt-get install -y unzip curl

COPY ignore/rdf4j.zip /tmp/rdf4j.zip

WORKDIR /tmp

RUN unzip -q /tmp/rdf4j.zip

# bundle the OpenTelemetry Java agent so it is available offline at container startup;
# activated conditionally by entrypoint-tomcat.sh, see there
RUN curl -fsSL -o /tmp/opentelemetry-javaagent.jar \
	"https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/${OTEL_JAVAAGENT_VERSION}/opentelemetry-javaagent-${OTEL_JAVAAGENT_VERSION}.jar"

# Final workbench
FROM tomcat:11.0-jdk25-temurin-noble
MAINTAINER Bart Hanssens (bart.hanssens@bosa.fgov.be)

RUN apt-get clean && apt-get update && apt-get upgrade -y && apt-get clean

ENV JAVA_OPTS="-Xmx2g"
ENV CATALINA_OPTS="-Dorg.eclipse.rdf4j.appdata.basedir=/var/rdf4j -Dorg.eclipse.rdf4j.rio.jsonld_secure_mode=false -Drdf4j.query.breaker.enabled=true"

RUN adduser --system tomcat

RUN	rm -rf /usr/local/tomcat/webapps/* && \
	mkdir -p /var/rdf4j && \
	chown -R tomcat /var/rdf4j /usr/local/tomcat && \
	chmod a+x /usr/local/tomcat /usr/local/tomcat/bin /usr/local/tomcat/bin/catalina.sh

COPY --from=temp /tmp/eclipse-rdf4j*/war/*.war /usr/local/tomcat/webapps/
COPY --from=temp /tmp/opentelemetry-javaagent.jar /opt/otel/opentelemetry-javaagent.jar

COPY tomcat/web.xml /usr/local/tomcat/conf/web.xml
COPY entrypoint-tomcat.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER tomcat

WORKDIR /usr/local/tomcat/

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
CMD ["catalina.sh", "run"]

