/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.query.algebra;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.junit.jupiter.api.Test;

/**
 * {@code ?s
 *
<p>
 * * ?o} and {@code ?s
 *
<p>
 * + ?o} differ only in {@link ArbitraryLengthPath#getMinLength()}; they must never compare equal, otherwise
 * equality-authenticated caches serve one plan for the other.
 */
class ArbitraryLengthPathEqualityTest {

	private static final IRI P = SimpleValueFactory.getInstance().createIRI("urn:p");

	@Test
	void minLengthParticipatesInEquality() {
		ArbitraryLengthPath star = path(0L);
		ArbitraryLengthPath plus = path(1L);

		assertNotEquals(star, plus, "p* and p+ must not be equal");
		assertNotEquals(plus, star);
		assertNotEquals(star.hashCode(), plus.hashCode(), "hash codes must separate p* from p+");
	}

	@Test
	void sameMinLengthStaysEqual() {
		assertEquals(path(0L), path(0L));
		assertEquals(path(0L).hashCode(), path(0L).hashCode());
		assertEquals(path(1L), path(1L));
		assertEquals(path(1L).hashCode(), path(1L).hashCode());
		assertEquals(path(1L), path(1L).clone());
	}

	private static ArbitraryLengthPath path(long minLength) {
		StatementPattern step = new StatementPattern(Var.of("s"), Var.of("_const_p", P, true, true), Var.of("o"));
		return new ArbitraryLengthPath(Var.of("s"), step, Var.of("o"), minLength);
	}
}
