/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.http.server.repository.handler;

import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

import javax.servlet.AsyncContext;

import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

final class AsyncExplainRegistry {

	private static final Logger LOGGER = LoggerFactory.getLogger(AsyncExplainRegistry.class);

	private static final AtomicLong THREAD_COUNTER = new AtomicLong();

	private final ConcurrentMap<String, Handle> handles = new ConcurrentHashMap<>();

	private final ExecutorService executorService;

	AsyncExplainRegistry() {
		this(Executors.newCachedThreadPool(runnable -> {
			Thread thread = Executors.defaultThreadFactory().newThread(runnable);
			thread.setName("rdf4j-server-explain-" + THREAD_COUNTER.incrementAndGet());
			thread.setDaemon(true);
			return thread;
		}));
	}

	AsyncExplainRegistry(ExecutorService executorService) {
		this.executorService = Objects.requireNonNull(executorService, "Executor service was null");
	}

	Handle register(String explainRequestId, AsyncContext asyncContext) {
		Handle handle = new Handle(explainRequestId, asyncContext);
		Handle previous = handles.putIfAbsent(explainRequestId, handle);
		if (previous != null) {
			throw new IllegalStateException("Explain request already active: " + explainRequestId);
		}
		return handle;
	}

	void execute(Runnable runnable) {
		executorService.execute(runnable);
	}

	boolean cancel(String explainRequestId) {
		Handle handle = handles.remove(explainRequestId);
		if (handle == null) {
			return false;
		}
		handle.cancel();
		return true;
	}

	void complete(Handle handle) {
		handles.remove(handle.getExplainRequestId(), handle);
		handle.finish();
	}

	void forget(Handle handle) {
		handles.remove(handle.getExplainRequestId(), handle);
	}

	static final class Handle {
		private final String explainRequestId;
		private final AsyncContext asyncContext;
		private final AtomicBoolean active = new AtomicBoolean(true);

		private volatile Thread workerThread;
		private volatile RepositoryConnection repositoryConnection;

		private Handle(String explainRequestId, AsyncContext asyncContext) {
			this.explainRequestId = Objects.requireNonNull(explainRequestId, "Explain request id was null");
			this.asyncContext = Objects.requireNonNull(asyncContext, "Async context was null");
		}

		String getExplainRequestId() {
			return explainRequestId;
		}

		AsyncContext getAsyncContext() {
			return asyncContext;
		}

		void attach(Thread workerThread, RepositoryConnection repositoryConnection) {
			this.workerThread = workerThread;
			this.repositoryConnection = repositoryConnection;
		}

		boolean isActive() {
			return active.get();
		}

		void cancel() {
			if (!active.getAndSet(false)) {
				completeAsync();
				return;
			}

			Thread activeWorker = workerThread;
			if (activeWorker != null) {
				activeWorker.interrupt();
			}

			closeConnection();
			completeAsync();
		}

		void finish() {
			active.set(false);
			completeAsync();
		}

		private void closeConnection() {
			RepositoryConnection connection = repositoryConnection;
			if (connection == null) {
				return;
			}
			try {
				connection.close();
			} catch (Exception e) {
				LOGGER.debug("Error while closing explain repository connection", e);
			}
		}

		private void completeAsync() {
			try {
				asyncContext.complete();
			} catch (IllegalStateException e) {
				LOGGER.debug("Async context already completed for explain request {}", explainRequestId, e);
			}
		}
	}
}
