= Customization SAILs

In addition to some of the SAIL implementations we have already seen, RDF4J offers a number of additional SAILs that allow customization of of your RDF database in various ways. For example they allow improved full-text search, or custom rule-based inference and validation. In this chapter, we discuss these customization SAILs in more detail.

== Full text indexing with the Lucene SAIL

The LuceneSail enables you to add full text search of RDF literals to find subject resources to any Sail stack. It provides querying support for the following statement patterns:

 PREFIX search: <http://www.openrdf.org/contrib/lucenesail#>
	 
 ?subj search:matches [
               search:query "search terms..."; 
               search:property my:property;
               search:score ?score;
               search:snippet ?snippet ] .

The ‘virtual’ properties in the search: namespace have the following meaning:

- search:matches – links the resource to be found with the following query statements (required)
- search:query – specifies the Lucene query (required)
- search:property – specifies the property to search. If omitted all properties are searched (optional)
- search:score – specifies a variable for the score (optional)
- search:snippet – specifies a variable for a highlighted snippet (optional)

=== Configuration

The LuceneSail is a stacked Sail: To use it, simply wrap your base SAIL with it:

[source,java]
----
Sail baseSail = new NativeStore(new File("."));
LuceneSail lucenesail = new LuceneSail();
// set any parameters, this one stores the Lucene index files into memory
lucenesail.setParameter(LuceneSail.LUCENE_RAMDIR_KEY, "true");
...
// wrap base sail
lucenesail.setBaseSail(baseSail);
----

=== Full text search

Search is case-insensitive, wildcards and other modifiers can be used to broaden the search.
For example, search all literals containing words starting with "alic" (e.g. persons named "Alice"):

[source,java]
----
....
Repository repo = new SailRepository(lucenesail);
repo.initialize();

// Get the subjects and a highlighted snippet
String qry = "PREFIX search: <http://www.openrdf.org/contrib/lucenesail#> " +
			"SELECT ?subj ?text " +
			"WHERE { ?subj search:matches [" +
					" search:query ?term ; " +
					" search:snippet ?text ] } ";

List<BindingSet> results;	
try (RepositoryConnection con = repo.getConnection()) {
	ValueFactory fac = con.getValueFactory();
		 
	TupleQuery tq = con.prepareTupleQuery(QueryLanguage.SPARQL, qry);
	// add wildcard '*' to perform wildcard search
	tq.setBinding("term", fac.createLiteral("alic" + "*"));
	
	// copy the results and processs them after the connection is closed
	results = QueryResults.asList(tq.evaluate());
}

results.forEach(res -> { 
		System.out.println(res.getValue("subj").stringValue()); 
		System.out.println(res.getValue("text").stringValue());
});

----

=== SearchIndex implementations

The LuceneSail can currently be used with five SearchIndex implementations:

[options="header"]
|=========================================================================================
|                 | SearchIndex implementation                | Maven module
| Apache Lucene 5 | org.eclipse.rdf4j.sail.lucene.LuceneIndex | org.eclipse.rdf4j:rdf4j-sail-lucene
| ElasticSearch   | org.eclipse.rdf4j.sail.elasticsearch.ElasticSearchIndex | org.eclipse.rdf4j:rdf4j-sail-elasticsearch
| Apache Solr Embedded  .3+| org.eclipse.rdf4j.sail.solr.SolrIndex  .3+| org.eclipse.rdf4j:rdf4j-sail-solr
| Apache Solr HTTP Client
| Apache Solr Cloud Client
|=========================================================================================

Each SearchIndex implementation can easily be extended if you need to add extra features or store/access data with a different schema.

The following example uses a local Solr instance running on the default port 8983. Make sure that both the Apache `httpcore` and `commons-logging` jars are in the classpath, and that the Solr core uses an appropriate schema (an example can be found in RDF4J's https://github.com/eclipse/rdf4j/blob/master/core/sail/fts/solr/solr/cores/embedded/conf/schema.xml[embedded solr] source code on GitHub).

[source,java]
----
import org.eclipse.rdf4j.sail.solr.SolrIndex;
....
LuceneSail luceneSail = new LuceneSail();
luceneSail.setParameter(LuceneSail.INDEX_CLASS_KEY, SolrIndex.class.getName());
luceneSail.setParameter(SolrIndex.SERVER_KEY, "http://localhost:8983/solr/rdf4j");
----

If needed, the Solr Client can be accessed via: 

[source,java]
----
SolrIndex index = (SolrIndex) luceneSail.getLuceneIndex();
SolrClient client = index.getClient();
----

== Reasoning and Validation support with SPIN

The SPARQL Inferencing Notation (SPIN) is a way to represent a wide range of business rules on top of an RDF dataset. These rules can be anything from constraint validation to inferred property value calculation.
Configuration

The SpinSail (currently in beta) is a StackedSail component that adds a forward-chaining SPIN rule engine on top of any store. In its most basic form it can be used directly on top of a Sail:

[source,java]
----
// create a basic Sail Stack with a simple Memory Store and SPIN inferencing support
SpinSail spinSail = new SpinSail();
spinSail.setBaseSail(new MemoryStore());
// create a repository with the Sail stack:
Repository rep = new SailRepository(spinSail);
rep.initialize();
----

Alternatively, a SpinSail can be configured via the RepositoryManager:

[source,java]
----
// create the config for the sail stack
SailImplConfig spinSailConfig = new SpinSailConfig(new MemoryStoreConfig());
RepositoryImplConfig repositoryTypeSpec = new SailRepositoryConfig(spinSailConfig);
// create the config for the actual repository
String repositoryId = "spin-test";
RepositoryConfig repConfig = new RepositoryConfig(repositoryId, repositoryTypeSpec);
manager.addRepositoryConfig(repConfig);
     
// get the Repository from the manager
Repository repository = manager.getRepository(repositoryId);
----

While this configuration already allows you to do many useful things, it does not do complete SPIN reasoning: the SpinSail relies on basic RDFS inferencing to be supplied by the underlying Sail stack. This means that for use cases where you need to rely on things like transitivity of rdfs:subClassOf relations, you should configure a Sail stack that includes the SchemaCachingRDFSInferencer. In addition, a DedupingInferencer is supplied which is a small optimization for both reasoners: it takes care to filter out potential duplicate results – though at the cost of an increase in memory usage. The full configuration with both additional inferencers looks like this:

[source,java]
----
// create a basic Sail Stack with a simple Memory Store, full RDFS reasoning,
// and SPIN inferencing support
SpinSail spinSail = new SpinSail();
spinSail.setBaseSail(
        new SchemaCachingRDFSInferencer(
               new DedupingInferencr(new MemoryStore())
        )
);
// create a repository with the Sail stack:
Repository rep = new SailRepository(spinSail);
rep.init();
----

or using configuration via the RepositoryManager:

[source,java]
----
// create the config for the sail stack
SailImplConfig spinSailConfig = new SpinSailConfig(
           new SchemaCachingRDFSInferencerConfig(
                 new DedupingInferencerConfig(new MemoryStoreConfig())
           )
);
RepositoryImplConfig repositoryTypeSpec = new SailRepositoryConfig(spinSailConfig);
// create the config for the actual repository
String repositoryId = "spin-test";
RepositoryConfig repConfig = new RepositoryConfig(repositoryId, repositoryTypeSpec);
manager.addRepositoryConfig(repConfig);
     
// get the Repository from the manager
Repository repository = manager.getRepository(repositoryId);
----

=== Adding rules

Once your repository is set up with SPIN support, you can add rules by simply uploading an RDF document contain SPIN rules (which are expressed in RDF using the SPIN vocabulary).  The SpinSail will automatically execute these rules on the data.

As an example, consider the following data:

 @prefix ex: <http://example.org/>.
 
 ex:John a ex:Father ;
         ex:parentOf ex:Lucy .
 
 ex:Lucy a ex:Person .

Now assume we wish to introduce a rule that defines persons who are the object of the ex:parentOf relation to be subject of an ex:childOf relation (in other words, we want to infer the inverse relationship for the parent-child relation). In SPIN, this could be done with the following rule:

 @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
 @prefix sp: <http://spinrdf.org/sp#>.
 @prefix spin: <http://spinrdf.org/spin#>.
 @prefix ex: <http://example.org/>.

 // every person who has a parent is a child of that parent.
 ex:Person a rdfs:Class ;
 	spin:rule [
 		a sp:Construct ;
		sp:text """PREFIX ex: <http://example.org/> 
		           CONSTRUCT { ?this ex:childOf ?parent . }
		           WHERE { ?parent ex:parentOf ?this . }"""
	] .

To get the SpinSail to execute this rule, all you need to do is upload both above RDF datasets to the Repository. The relation will be automatically inferred at data upload time, so the query:

 SELECT ?child WHERE { ?child ex:childOf ?parent }

will give this result:

[options="header"]
|========
|child
| ex:Lucy
|========

=== Further reading

Here are some useful links to learn more about SPIN:

- http://spinrdf.org/spinsquare.html[SPIN Primer]
- http://www.topquadrant.com/spin/tutorial/[Getting Started with SPIN] (by Topquadrant)

== Validation with SHACL

NOTE: new in RDF4J 2.5

The SHapes Constraint Language (SHACL) is a language for validating RDF graphs.

This documentation is for RDF4J 2.5 and onwards, as the SHACL engine was experimental
until this release.

=== How does the SHACL engine work

The SHACL engine works by analyzing the changes made in a transaction and creating a
set of validation plans (similar to query plans) and executing these as part of the transactions
`commit()` call.

In many cases the SHACL engine can validate your changes based on your changes alone. In
some cases your changes may affect or be affected by data already in the database, in which
case the engine will query the database for that particular data.

Here is an example of when data in the database affects the validation plans:

[source,turtle]
----
ex:PersonShape
	a sh:NodeShape  ;
	sh:targetClass ex:Person ;
	sh:property [
		sh:path ex:age ;
		sh:datatype xsd:integer ;
	] .
----

Initial data in the database.
[source,turtle]
----
ex:pete a ex:Person.
----

Data added by a transaction.

[source,turtle]
----
ex:pete ex:age "eighteen".
----

For this example the SHACL engine will match the predicate `ex:age` with `ex:PersonShape`
and realise that `ex:pete` might already be defined as a `ex:Person` in the database. The
validation plan will then include checking if `ex:pete` is type `ex:Person`.

=== How to load SHACL shapes

The ShaclSail uses a reserved graph (`http://rdf4j.org/schema/rdf4j#SHACLShapeGraph`) for
storing the SHACL shapes. Utilize a normal connection to load your shapes into this
graph.

[source,java]
----
ShaclSail shaclSail = new ShaclSail(new MemoryStore());
SailRepository sailRepository = new SailRepository(shaclSail);
sailRepository.init();

try (SailRepositoryConnection connection = sailRepository.getConnection()) {

        connection.begin();

        Reader shaclRules = ....

        connection.add(shaclRules, "", RDFFormat.TURTLE, RDF4J.SHACL_SHAPE_GRAPH);

        connection.commit();
}
----

At this time there is no way of updating your shapes once they have been loaded. Further
more the ShaclSail will throw an exception if you try to add data before loading any shapes,
this is merely thrown to educate and warn the user and should not be relied upon for any code.
To disable this check call `shaclSail.setIgnoreNoShapesLoadedException(true)`.

=== Supported SHACL features

The SHACL W3C Recommendation defines the SHACL features that should be supported and
RDF4J is working hard to support them all. At the moment a fairly large subset of these features
are supported by the ShaclSail, however quite a few are not yet implemented.

An always-up-to-date list of features can be found by calling the static method
`ShaclSail.getSupportedShaclPredicates()`.

As of writing this documentation the following features are supported.

 - `sh:targetClass`
 - `sh:path`
 - `sh:property`
 - `sh:or`
 - `sh:minCount`
 - `sh:maxCount`
 - `sh:minLength`
 - `sh:maxLength`
 - `sh:pattern` and `sh:flags`
 - `sh:nodeKind`
 - `sh:languageIn`
 - `sh:datatype`
 - `sh:class`

Implicit `sh:targetClass` is supported for nodes that are `rdfs:Class` and either of `sh:PropertyShape` or `sh:NodeShape`.
Validation for all nodes, equivalent to `owl:Thing` in an environment with a reasoner, can be enabled by setting
`setUndefinedTargetValidatesAllSubjects(true)`.

`sh:path` is limited to single predicate paths, eg. `ex:age`. Sequence paths,
alternative paths, inverse paths and the like are not supported.

`sh:or` is limited to statement based restrictions, such as `sh:datatype`, or aggregate based restrictions, such as `sh:minCount`,
but not both at the same time.

Predicates that are not supported are logged at the `DEBUG` logging level.

=== Validation results

On `commit()` the ShaclSail will validate your changes and throw an exception if there are
violations. The exception contains a validation report and can be retrieved like this:

[source,java]
----
try {
        connection.commit();
} catch (RepositoryException exception) {
        Throwable cause = exception.getCause();
        if (cause instanceof ShaclSailValidationException) {
                ValidationReport validationReport = ((ShaclSailValidationException) cause).getValidationReport();
                Model validationReportModel = ((ShaclSailValidationException) cause).validationReportAsModel();
                // use validationReport or validationReportModel to understand validation violations

                Rio.write(validationReportModel, System.out, RDFFormat.TURTLE);
        }
        throw exception;
}
----

The validationReportModel follows the report format specified by the W3C SHACL
recommendation. It does not provide all the information specified in the recommendation.
Example report:

[source,turtle]
----
[]
  a sh:ValidationReport ;
  sh:conforms false ;
  sh:result [
  	a sh:ValidationResult ;
  	sh:focusNode <http://example.com/ns#pete> ;
  	sh:resultPath <http://example.com/ns#age> ;
  	sh:sourceConstraintComponent sh:DatatypeConstraintComponent ;
  	sh:sourceShape <http://example.com/ns#PersonShapeAgeProperty> ;
  ] .
----

The ValidationReport class provides the same information as the validationReportModel, but
as a Java object with getters for accessing the report data.

There is no support for `sh:severity`, all violations will trigger an exception.

=== Logging and debugging

By default there is very little logging enabled in the ShaclSail. There are three methods for enabling
logging:

 - `shaclSail.setLogValidationPlans(true);`
 - `shaclSail.setGlobalLogValidationExecution(true);`
 - `shaclSail.setLogValidationViolations(true);`

All these will log as `INFO`.

First step to debugging and understanding an unexpected violation is to enable `shaclSail.setLogValidationViolations(true);`.

Logging for unsupported SHACL features and for internal processes in the SHACL sail are logged at `DEBUG`.

==== Log validation plans

Validation plans are logged as Graphviz DOT. Validations plans are a form of query plan.

Here is the validation plan for the example above:
link:https://dreampuf.github.io/GraphvizOnline/#digraph%20%20%7B%0Alabelloc%3Dt%3B%0Afontsize%3D30%3B%0Alabel%3D%22DatatypePropertyShape%22%3B%0A1866229258%20%5Blabel%3D%22Base%20sail%22%20nodeShape%3Dpentagon%20fillcolor%3Dlightblue%20style%3Dfilled%5D%3B%0A1555990397%20%5Blabel%3D%22Added%20statements%22%20nodeShape%3Dpentagon%20fillcolor%3Dlightblue%20style%3Dfilled%5D%3B%0A1544078442%20%5Blabel%3D%22Removed%20statements%22%20nodeShape%3Dpentagon%20fillcolor%3Dlightblue%20style%3Dfilled%5D%3B%0A1337866219%20%5Blabel%3D%22Previous%20state%20connection%22%20nodeShape%3Dpentagon%20fillcolor%3Dlightblue%20style%3Dfilled%5D%3B%0A1291367132%20%5Blabel%3D%22DirectTupleFromFilter%22%5D%3B%0A1887699190%20%5Blabel%3D%22DatatypeFilter%7Bdatatype%3Dhttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%7D%22%5D%3B%0A1479140596%20-%3E%201887699190%0A1887699190%20-%3E%201291367132%20%5Blabel%3D%22false%20values%22%5D%0A1479140596%20%5Blabel%3D%22UnionNode%22%5D%3B%0A1108889615%20-%3E%201479140596%0A1108889615%20%5Blabel%3D%22UnionNode%22%5D%3B%0A1275028674%20-%3E%201108889615%0A455888635%20%5Blabel%3D%22BufferedSplitter%22%5D%3B%0A204805934%20-%3E%20455888635%0A204805934%20%5Blabel%3D%22TrimTuple%7BnewLength%3D1%7D%22%5D%3B%0A204322447%20-%3E%20204805934%0A204322447%20%5Blabel%3D%22Select%7Bquery%3D'select%20*%20where%20%7B%20BIND(rdf%3Atype%20as%20%3Fb)%20%5Cn%20BIND(%3Chttp%3A%2F%2Fexample.com%2Fns%23Person%3E%20as%20%3Fc)%20%5Cn%20%3Fa%20%3Fb%20%3Fc.%7D%20order%20by%20%3Fa'%7D%22%5D%3B%0A1555990397%20-%3E%20204322447%0A1275028674%20%5Blabel%3D%22InnerJoin%22%5D%3B%0A455888635%20-%3E%201275028674%20%5Blabel%3D%22left%22%5D%3B%0A1019484860%20-%3E%201275028674%20%5Blabel%3D%22right%22%5D%3B%0A1019484860%20%5Blabel%3D%22DirectTupleFromFilter%22%5D%3B%0A1164365897%20%5Blabel%3D%22DatatypeFilter%7Bdatatype%3Dhttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%7D%22%5D%3B%0A1640899500%20-%3E%201164365897%0A1164365897%20-%3E%201019484860%20%5Blabel%3D%22false%20values%22%5D%0A1640899500%20%5Blabel%3D%22Select%7Bquery%3D'select%20*%20where%20%7B%20%3Fa%20%3Chttp%3A%2F%2Fexample.com%2Fns%23age%3E%20%3Fc.%20%7D%20order%20by%20%3Fa'%7D%22%5D%3B%0A1555990397%20-%3E%201640899500%0A1275028674%20-%3E%203565780%20%5Blabel%3D%22discardedRight%22%5D%3B%0A473666452%20-%3E%201108889615%0A473666452%20%5Blabel%3D%22ExternalTypeFilterNode%7BfilterOnType%3Dhttp%3A%2F%2Fexample.com%2Fns%23Person%7D%22%5D%3B%0A3565780%20-%3E%20473666452%0A1337866219%20-%3E%20473666452%20%5Blabel%3D%22filter%20source%22%5D%0A3565780%20%5Blabel%3D%22BufferedTupleFromFilter%22%5D%3B%0A1865219266%20-%3E%201479140596%0A1865219266%20%5Blabel%3D%22BulkedExternalInnerJoin%7Bpredicate%3Dnull%2C%20query%3D'%3Fa%20%3Chttp%3A%2F%2Fexample.com%2Fns%23age%3E%20%3Fc.%20'%7D%22%5D%3B%0A455888635%20-%3E%201865219266%20%5Blabel%3D%22left%22%5D%0A1337866219%20-%3E%201865219266%20%5Blabel%3D%22right%22%5D%0A%7D%0A8[Link]

The structure of this log and its contents may change in the future, without warning.

==== Log validation execution

The execution of the validation plan shows what data was requested during the exeuction and
how that data was joined together and filtered.

Enabling this logging will enable it for all ShaclSails on all threads.

Enabling this logging will make your validation considerably slower and take up considerably
more memory.

Following on from the example above
[source,log]
----
01. [main] INFO   Select.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
02. [main] INFO    DatatypeFilter;falseNode:  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
03. [main] INFO     DirectTupleFromFilter.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
04. [main] INFO      InnerJoin;discardedRight:  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
05. [main] INFO       BufferedTupleFromFilter.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
06. [main] INFO         ExternalTypeFilterNode.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
07. [main] INFO           UnionNode.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
08. [main] INFO             UnionNode.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
09. [main] INFO              DatatypeFilter;falseNode:  Tuple{line=[http://example.com/ns#pete, "eighteen"]}
10. [main] INFO               DirectTupleFromFilter.next():  Tuple{line=[http://example.com/ns#pete, "eighteen"]}

----

The log is best read in conjunction with the validation plan. By taking the bottom log line (10.)
as the bottom node in the plan and for each indentation following the plan upwards. Multiple
lines at a given indentation mean that that node produced multiple tuples.

Line 6 shows a query to the underlying database. Line 1 is the query for everything matching
the path (ex:age) against the added data in the transaction.

The indentation is best-effort.

The structure of this log and its contents may change in the future, without warning.

==== Log validation violations

As the `commit()` call iterates over the shapes it can log the results (tuples) from the execution
of each validation plan.

Following on from the example above:

[source,log]
----
1. [main] INFO  SHACL not valid. The following experimental debug results were produced:
2. 	NodeShape: http://example.com/ns#PersonShape
3. 		Tuple{line=[http://example.com/ns#pete, "eighteen"], propertyShapes= DatatypePropertyShape <_:node1d285h2ktx1>} -cause->  [ Tuple{line=[http://example.com/ns#pete, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://example.com/ns#Person]} ]
----

Line 2 shows the shape that triggered this violation. Line 3 shows the ultimate tuple produced
and which PropertyShape produced the exception followed by a cause listing other tuples that
caused the violation. In this case the existing type statement.

The structure of this log and its contents may change in the future, without warning.

=== Full working example

[source,java]
----
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.vocabulary.RDF4J;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.sail.memory.MemoryStore;
import org.eclipse.rdf4j.sail.shacl.ShaclSail;
import org.eclipse.rdf4j.sail.shacl.ShaclSailValidationException;
import org.eclipse.rdf4j.sail.shacl.results.ValidationReport;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.StringReader;

public class ShaclSampleCode {

        public static void main(String[] args) throws IOException {

                ShaclSail shaclSail = new ShaclSail(new MemoryStore());

                //Logger root = (Logger) LoggerFactory.getLogger(ShaclSail.class.getName());
                //root.setLevel(Level.INFO);

                //shaclSail.setLogValidationPlans(true);
                //shaclSail.setGlobalLogValidationExecution(true);
                //shaclSail.setLogValidationViolations(true);

                SailRepository sailRepository = new SailRepository(shaclSail);
                sailRepository.init();

                try (SailRepositoryConnection connection = sailRepository.getConnection()) {

                        connection.begin();

                        StringReader shaclRules = new StringReader(
                                String.join("\n", "",
                                        "@prefix ex: <http://example.com/ns#> .",
                                        "@prefix sh: <http://www.w3.org/ns/shacl#> .",
                                        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
                                        "@prefix foaf: <http://xmlns.com/foaf/0.1/>.",

                                        "ex:PersonShape",
                                        "  a sh:NodeShape  ;",
                                        "  sh:targetClass foaf:Person ;",
                                        "  sh:property ex:PersonShapeProperty .",

                                        "ex:PersonShapeProperty ",
                                        "  sh:path foaf:age ;",
                                        "  sh:datatype xsd:int ;",
                                        "  sh:maxCount 1 ;",
                                        "  sh:minCount 1 ."
                                ));

                        connection.add(shaclRules, "", RDFFormat.TURTLE, RDF4J.SHACL_SHAPE_GRAPH);
                        connection.commit();

                        connection.begin();

                        StringReader invalidSampleData = new StringReader(
                                String.join("\n", "",
                                        "@prefix ex: <http://example.com/ns#> .",
                                        "@prefix foaf: <http://xmlns.com/foaf/0.1/>.",
                                        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",

                                        "ex:peter a foaf:Person ;",
                                        "  foaf:age 20, \"30\"^^xsd:int  ."

                                ));

                        connection.add(invalidSampleData, "", RDFFormat.TURTLE);
                        try {
                                connection.commit();
                        } catch (RepositoryException exception) {
                                Throwable cause = exception.getCause();
                                if (cause instanceof ShaclSailValidationException) {
                                        ValidationReport validationReport = ((ShaclSailValidationException) cause).getValidationReport();
                                        Model validationReportModel = ((ShaclSailValidationException) cause).validationReportAsModel();
                                        // use validationReport or validationReportModel to understand validation violations

                                        Rio.write(validationReportModel, System.out, RDFFormat.TURTLE);
                                }
                                throw exception;
                        }
                }
        }
}
----

=== Further reading

Here are some useful links to learn more about SHACL:

- http://www.w3.org/TR/shacl/[W3C SHACL specification]
- http://book.validatingrdf.com[Validating RDF Data] (various authors)

