/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatIllegalArgumentException;

import java.lang.reflect.Constructor;
import java.util.function.ToLongBiFunction;

import org.junit.jupiter.api.Test;

class ConcurrentCacheByteBudgetTest {

	@Test
	void byteBudgetEvictsTheOldestEntry() throws Exception {
		Constructor<ConcurrentCache> constructor = ConcurrentCache.class.getConstructor(int.class, long.class,
				ToLongBiFunction.class);
		ToLongBiFunction<String, String> weight = (key, value) -> value.length();
		@SuppressWarnings("unchecked")
		ConcurrentCache<String, String> cache = constructor.newInstance(16, 8L, weight);

		cache.put("first", "123456");
		cache.put("second", "abcdef");

		assertThat(cache.get("first")).isNull();
		assertThat(cache.get("second")).isEqualTo("abcdef");
		assertThat(ConcurrentCache.class.getDeclaredMethod("usedBytes").invoke(cache)).isEqualTo(6L);
	}

	@Test
	void oversizedReplacementIsNotRetained() {
		ConcurrentCache<String, String> cache = new ConcurrentCache<>(16, 8L,
				(key, value) -> value.length());

		cache.put("key", "1234");
		assertThat(cache.put("key", "123456789")).isEqualTo("1234");

		assertThat(cache.get("key")).isNull();
		assertThat(cache.usedBytes()).isZero();
	}

	@Test
	void replacementAndClearKeepExactByteAccounting() {
		ConcurrentCache<String, String> cache = new ConcurrentCache<>(16, 8L,
				(key, value) -> value.length());

		cache.put("key", "1234");
		cache.put("key", "1234567");

		assertThat(cache.get("key")).isEqualTo("1234567");
		assertThat(cache.usedBytes()).isEqualTo(7L);

		cache.clear();
		assertThat(cache.get("key")).isNull();
		assertThat(cache.usedBytes()).isZero();
	}

	@Test
	void negativeEntryWeightsAreRejected() {
		ConcurrentCache<String, String> cache = new ConcurrentCache<>(16, 8L, (key, value) -> -1L);

		assertThatIllegalArgumentException().isThrownBy(() -> cache.put("key", "value"))
				.withMessage("cache entry weight must not be negative");
		assertThat(cache.get("key")).isNull();
		assertThat(cache.usedBytes()).isZero();
	}
}
