/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.io.IOException;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.sail.base.SailDataset;
import org.eclipse.rdf4j.sail.lmdb.evaluation.NativeLmdbQuerySource;

/** Test-scope bridge that deterministically warms one subject-keyed CSR entry from another predicate's subjects. */
public final class CsrProbeWarmupAccess {

	private CsrProbeWarmupAccess() {
	}

	public static void warmBySubject(LmdbStore sail, IRI rootPredicate, IRI probePredicate) throws IOException {
		LmdbSailStore backingStore = sail.getBackingStore();
		try (SailDataset dataset = backingStore.getExplicitSailSource().dataset(IsolationLevels.NONE)) {
			NativeLmdbQuerySource source = (NativeLmdbQuerySource) dataset;
			long rootPredicateId = source.idOf(rootPredicate);
			long probePredicateId = source.idOf(probePredicate);
			try (RecordIterator roots = source.statements(-1L, rootPredicateId, -1L, -1L);
					NativeLmdbQuerySource.NativeProbe probe = source.newProbe()) {
				long[] root;
				while ((root = roots.next()) != null) {
					RecordIterator matches = probe.open(root[TripleIndex.SUBJ_IDX], probePredicateId, -1L, -1L);
					while (matches.next() != null) {
						// Exhaust each retained probe before re-aiming it at the next root subject.
					}
				}
			}
		}
	}
}
