/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

import org.junit.jupiter.api.Test;

class DerivedStateBuildExecutorTest {

	@Test
	void resolvesUnsetSerialInvalidAndCappedThreadCounts() {
		ArrayList<String> warnings = new ArrayList<>();

		assertEquals(7, DerivedStateBuildExecutor.resolveThreads(null, 8, warnings::add));
		assertEquals(1, DerivedStateBuildExecutor.resolveThreads("1", 8, warnings::add));
		assertEquals(8, DerivedStateBuildExecutor.resolveThreads("99", 8, warnings::add));
		assertEquals(7, DerivedStateBuildExecutor.resolveThreads("zero", 8, warnings::add));
		assertEquals(7, DerivedStateBuildExecutor.resolveThreads("0", 8, warnings::add));
		assertEquals(7, DerivedStateBuildExecutor.resolveThreads("-2", 8, warnings::add));
		assertEquals(3, warnings.size());
	}

	@Test
	void limitsParallelismByEveryAvailableResource() {
		try (DerivedStateBuildExecutor executor = DerivedStateBuildExecutor.create("derived-limits-", 8)) {
			assertEquals(8, executor.effectiveParallelism(100, 100, 100));
			assertEquals(3, executor.effectiveParallelism(3, 100, 100));
			assertEquals(2, executor.effectiveParallelism(100, 2, 100));
			assertEquals(1, executor.effectiveParallelism(100, 0, 100));
			assertEquals(4, executor.effectiveParallelism(100, 100, 4));
			assertEquals(1, executor.effectiveParallelism(0, 0, 0));
		}
	}

	@Test
	void usesNamedDaemonWorkersAndPreservesResultOrder() throws Exception {
		try (DerivedStateBuildExecutor executor = DerivedStateBuildExecutor.create("derived-test-", 2)) {
			List<String> results = executor.invokeAll(List.of(
					() -> Thread.currentThread().getName() + ":" + Thread.currentThread().isDaemon(),
					() -> "second"));

			assertTrue(results.get(0).startsWith("derived-test-"), results::toString);
			assertTrue(results.get(0).endsWith(":true"), results::toString);
			assertEquals("second", results.get(1));
		}
	}

	@Test
	void firstWorkerFailureCancelsBlockedSiblings() throws Exception {
		AtomicBoolean interrupted = new AtomicBoolean();
		CountDownLatch entered = new CountDownLatch(1);
		try (DerivedStateBuildExecutor executor = DerivedStateBuildExecutor.create("derived-failure-", 2)) {
			IOException failure = assertThrows(IOException.class, () -> executor.runAll(List.of(
					() -> {
						entered.countDown();
						try {
							Thread.currentThread().join();
						} catch (InterruptedException expected) {
							interrupted.set(true);
							Thread.currentThread().interrupt();
						}
						return null;
					},
					() -> {
						entered.await();
						throw new IOException("injected worker failure");
					})));

			assertEquals("injected worker failure", failure.getMessage());
			for (int spin = 0; spin < 1_000 && !interrupted.get(); spin++) {
				Thread.onSpinWait();
			}
			assertTrue(interrupted.get());
		}
	}

	@Test
	void reportsOnlyAtTenSecondPageBoundariesWithStableRatesAndEta() {
		AtomicLong now = new AtomicLong(100L);
		DerivedStateBuildProgress progress = new DerivedStateBuildProgress(2_000L, now::get);

		now.addAndGet(DerivedStateBuildProgress.REPORT_INTERVAL_NANOS - 1L);
		assertNull(progress.pageCompleted(999L));
		now.incrementAndGet();
		DerivedStateBuildProgress.Sample first = progress.pageCompleted(1_000L);
		assertEquals(100.0d, first.currentRate(), 0.0d);
		assertEquals(100.0d, first.averageRate(), 0.0d);
		assertEquals(10_000L, first.etaMillis());

		now.addAndGet(DerivedStateBuildProgress.REPORT_INTERVAL_NANOS);
		DerivedStateBuildProgress.Sample finished = progress.finish(2_000L);
		assertEquals(100.0d, finished.currentRate(), 0.0d);
		assertEquals(100.0d, finished.averageRate(), 0.0d);
		assertEquals(0L, finished.etaMillis());
	}

	@Test
	void telemetryArithmeticSaturatesWithoutAffectingCorrectness() {
		AtomicLong now = new AtomicLong(Long.MAX_VALUE - 5L);
		DerivedStateBuildProgress progress = new DerivedStateBuildProgress(Long.MAX_VALUE, now::get);
		now.set(Long.MIN_VALUE + DerivedStateBuildProgress.REPORT_INTERVAL_NANOS);

		DerivedStateBuildProgress.Sample sample = progress.pageCompleted(Long.MAX_VALUE);

		assertTrue(Double.isFinite(sample.currentRate()));
		assertTrue(Double.isFinite(sample.averageRate()));
		assertEquals(0L, sample.etaMillis());
	}
}
