/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;

import org.junit.jupiter.api.Test;

class LeoPlusOutOfDistributionTest {

	private static final LogicalLearningKey LOGICAL = LogicalLearningKey.of("join", "expr-a", "children-a",
			"predicates-a", "v0,v1", "none", "bag", "store-defaults");
	private static final PhysicalResidualKey PHYSICAL = PhysicalResidualKey.of("streaming", "direct", "spoc",
			"dependent-reopen", "none", "none", "none", "layout-a");
	private static final LearningApplicability APPLICABILITY = new LearningApplicability(11L, 0L,
			"input:unbound", 19L, 23L, 1L);
	private static final LearningFeatureEnvelope PHYSICAL_FEATURES = LearningFeatureEnvelope.conventionalRows(100.0d);

	@Test
	void outOfDistributionContextFallsBackToConventionalVector() {
		FrontierLearningModel model = new FrontierLearningModel();
		for (int observation = 0; observation < 32; observation++) {
			model.observeLogical(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
					100.0d + observation % 3, 400.0d, observation + 1L);
		}

		assertNotNull(model.logicalEstimate(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS, 101.0d),
				"A calibrated in-distribution context may use the learned posterior");
		assertNull(model.logicalEstimate(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS, 1.0e9d),
				"An OOD context must leave the conventional cost vector unchanged");
		assertEquals(LearningGateDecision.Outcome.OUT_OF_DISTRIBUTION,
				model.logicalDecision(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
						LearningFeatureEnvelope.conventionalRows(1.0e9d), 1.0e9d)
						.gate()
						.outcome());
	}

	@Test
	void insufficientSupportLeavesTheConventionalVectorUntouched() {
		FrontierLearningModel model = new FrontierLearningModel();
		model.observeLogical(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS, 100.0d, 400.0d, 1L);
		model.observeLogical(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS, 101.0d, 400.0d, 2L);

		FrontierLearningModel.DimensionDecision decision = model.logicalDecision(LOGICAL, APPLICABILITY,
				FrontierCostDimension.OUTPUT_ROWS, LearningFeatureEnvelope.conventionalRows(100.0d), 100.0d);

		assertEquals(LearningGateDecision.Outcome.INSUFFICIENT_SUPPORT, decision.gate().outcome());
		assertNull(decision.estimate());
		assertEquals(2L, decision.gate().exactCellObservations());
	}

	@Test
	void applicablePhysicalCorrectionSaturatesAtLargestFiniteCost() {
		FrontierLearningModel model = calibratedPhysicalModel(1.0d, 4.0d);

		FrontierLearningModel.DimensionDecision decision = model.physicalDecision(LOGICAL, PHYSICAL, APPLICABILITY,
				FrontierCostDimension.SOURCE_ROWS_SCANNED, PHYSICAL_FEATURES, Double.MAX_VALUE);

		assertEquals(LearningGateDecision.Outcome.APPLICABLE, decision.gate().outcome());
		assertNotNull(decision.estimate());
		assertEquals(Double.MAX_VALUE, decision.estimate().correctedValue());
		assertEquals(Double.POSITIVE_INFINITY, decision.estimate().upperValue());
	}

	@Test
	void applicablePhysicalReductionFromLargestFiniteCostKeepsAnOrderedInterval() {
		FrontierLearningModel model = calibratedPhysicalModel(4.0d, 1.0d);

		FrontierLearningModel.DimensionDecision decision = model.physicalDecision(LOGICAL, PHYSICAL, APPLICABILITY,
				FrontierCostDimension.SOURCE_ROWS_SCANNED, PHYSICAL_FEATURES, Double.MAX_VALUE);

		assertEquals(LearningGateDecision.Outcome.APPLICABLE, decision.gate().outcome());
		assertNotNull(decision.estimate());
		assertTrue(Double.isFinite(decision.estimate().correctedValue()));
		assertTrue(decision.estimate().correctedValue() < Double.MAX_VALUE);
		assertTrue(decision.estimate().lowerValue() <= decision.estimate().correctedValue());
		assertTrue(decision.estimate().upperValue() >= decision.estimate().correctedValue());
	}

	@Test
	void hardApplicabilityMismatchIsNotTreatedAsNumericDrift() {
		FrontierLearningModel model = calibratedModel();
		LearningApplicability correlated = new LearningApplicability(11L, 29L,
				"input:correlated|range:unknown", 19L, 23L, 1L);

		FrontierLearningModel.DimensionDecision decision = model.logicalDecision(LOGICAL, correlated,
				FrontierCostDimension.OUTPUT_ROWS, LearningFeatureEnvelope.conventionalRows(101.0d), 101.0d);

		assertEquals(LearningGateDecision.Outcome.INAPPLICABLE, decision.gate().outcome());
		assertNull(decision.estimate());
	}

	@Test
	void knownAndUnknownRangeContextsAreDifferentApplicabilityCategories() {
		FrontierLearningModel model = new FrontierLearningModel();
		LearningFeatureEnvelope knownRange = LearningFeatureEnvelope.of(100.0d, 1.0d, 0.0d, 0.25d, 2.0d);
		for (int observation = 0; observation < 32; observation++) {
			model.observeLogical(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
					knownRange, 400.0d, observation + 1L);
		}

		FrontierLearningModel.DimensionDecision decision = model.logicalDecision(LOGICAL, APPLICABILITY,
				FrontierCostDimension.OUTPUT_ROWS,
				LearningFeatureEnvelope.of(100.0d, 1.0d, 0.0d, Double.NaN, 2.0d), 100.0d);

		assertEquals(LearningGateDecision.Outcome.INAPPLICABLE, decision.gate().outcome());
		assertNull(decision.estimate());
	}

	@Test
	void censoredObservationNarrowsOnlyThePredictiveInterval() {
		FrontierLearningModel model = calibratedModel();
		FrontierLearningModel.DimensionEstimate before = model.logicalEstimate(LOGICAL, APPLICABILITY,
				FrontierCostDimension.OUTPUT_ROWS, 101.0d);
		double censoredLower = (before.lowerValue() + before.correctedValue()) * 0.5d;

		model.observeLogicalCensored(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
				CensoredObservationBounds.lower(censoredLower));
		FrontierLearningModel.DimensionEstimate after = model.logicalEstimate(LOGICAL, APPLICABILITY,
				FrontierCostDimension.OUTPUT_ROWS, 101.0d);

		assertEquals(before.posteriorLogMean(), after.posteriorLogMean(), 0.0d,
				"A censored count must not enter NIG point statistics");
		assertEquals(before.exactEvidenceCount(), after.exactEvidenceCount());
		assertTrue(after.lowerValue() > before.lowerValue());
		assertEquals(before.correctedValue(), after.correctedValue(), 0.0d);
	}

	@Test
	void calibrationAndCensoringRoundTripWithoutChangingTheDecision() throws Exception {
		FrontierLearningModel model = calibratedModel();
		FrontierLearningModel.DimensionEstimate estimate = model.logicalEstimate(LOGICAL, APPLICABILITY,
				FrontierCostDimension.OUTPUT_ROWS, 101.0d);
		model.observeLogicalCensored(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
				CensoredObservationBounds.lower((estimate.lowerValue() + estimate.correctedValue()) * 0.5d));
		ByteArrayOutputStream bytes = new ByteArrayOutputStream();
		try (DataOutputStream out = new DataOutputStream(bytes)) {
			model.writeTo(out);
		}

		FrontierLearningModel restored;
		try (DataInputStream in = new DataInputStream(new ByteArrayInputStream(bytes.toByteArray()))) {
			restored = FrontierLearningModel.readFrom(in);
		}

		assertEquals(LearningGateDecision.Outcome.APPLICABLE,
				restored.logicalDecision(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
						LearningFeatureEnvelope.conventionalRows(101.0d), 101.0d)
						.gate()
						.outcome());
		assertEquals(LearningGateDecision.Outcome.OUT_OF_DISTRIBUTION,
				restored.logicalDecision(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
						LearningFeatureEnvelope.conventionalRows(1.0e9d), 1.0e9d)
						.gate()
						.outcome());
		assertTrue(restored.logicalEstimate(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS, 101.0d)
				.lowerValue() > estimate.lowerValue());
	}

	private static FrontierLearningModel calibratedModel() {
		FrontierLearningModel model = new FrontierLearningModel();
		for (int observation = 0; observation < 32; observation++) {
			model.observeLogical(LOGICAL, APPLICABILITY, FrontierCostDimension.OUTPUT_ROWS,
					100.0d + observation % 3, 400.0d, observation + 1L);
		}
		return model;
	}

	private static FrontierLearningModel calibratedPhysicalModel(double predicted, double actual) {
		FrontierLearningModel model = new FrontierLearningModel();
		for (int observation = 0; observation < 32; observation++) {
			model.observePhysical(LOGICAL, PHYSICAL, APPLICABILITY, FrontierCostDimension.SOURCE_ROWS_SCANNED,
					PHYSICAL_FEATURES, predicted, actual, observation + 1L);
		}
		return model;
	}
}
