/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.model.vocabulary.XMLSchema;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbQueryResultResolutionAfterShutdownTest {

	private static final String NS = "http://example.com/resolved/";
	private static final String QUERY = """
			PREFIX ex: <http://example.com/resolved/>
			SELECT ?person ?name ?age WHERE {
			  ?person a ex:Person ;
			          ex:name ?name ;
			          ex:age ?age .
			}
			ORDER BY ?name
			""";

	@Test
	void queryRowsStoredInAListRemainPrintableAfterConnectionCloseAndRepositoryShutdown(@TempDir Path tempDir) {
		SailRepository repository = new SailRepository(
				LmdbTestUtil.newStoreWithLmdbEvaluationStrategy(tempDir.toFile()));
		repository.init();

		List<BindingSet> rows = new ArrayList<>();
		try {
			loadPeople(repository);
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.begin(IsolationLevels.READ_COMMITTED);
				try (TupleQueryResult result = connection.prepareTupleQuery(QueryLanguage.SPARQL, QUERY).evaluate()) {
					while (result.hasNext()) {
						rows.add(result.next());
					}
				}
				connection.commit();
			}
		} finally {
			repository.shutDown();
		}

		List<String> printableRows = rows.stream()
				.map(LmdbQueryResultResolutionAfterShutdownTest::printableRow)
				.toList();
		printableRows.forEach(row -> System.out.println("resolved LMDB query row after shutdown: " + row));

		assertThat(printableRows).containsExactly(
				NS + "alice | Alice | 41",
				NS + "bob | Bob | 42");
	}

	private static void loadPeople(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.READ_COMMITTED);
			ValueFactory vf = connection.getValueFactory();
			IRI person = vf.createIRI(NS, "Person");
			IRI name = vf.createIRI(NS, "name");
			IRI age = vf.createIRI(NS, "age");
			IRI alice = vf.createIRI(NS, "alice");
			IRI bob = vf.createIRI(NS, "bob");

			connection.add(alice, RDF.TYPE, person);
			connection.add(alice, name, vf.createLiteral("Alice"));
			connection.add(alice, age, vf.createLiteral(41));
			connection.add(bob, RDF.TYPE, person);
			connection.add(bob, name, vf.createLiteral("Bob"));
			connection.add(bob, age, vf.createLiteral(42));
			connection.commit();
		}
	}

	private static String printableRow(BindingSet row) {
		assertThat(row.getValue("age")).isInstanceOf(Literal.class);
		assertThat(((Literal) row.getValue("age")).getDatatype()).isEqualTo(XMLSchema.INT);
		return row.getValue("person").stringValue() + " | "
				+ row.getValue("name").stringValue() + " | "
				+ row.getValue("age").stringValue();
	}
}
