/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.model.vocabulary.RDFS;
import org.eclipse.rdf4j.sail.NotifyingSailConnection;
import org.eclipse.rdf4j.sail.base.SailSink;
import org.eclipse.rdf4j.sail.lmdb.LmdbStore.LmdbStats;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;

class LmdbStatsLoggingTest {

	@TempDir
	File dataDir;

	private final Logger logger = (Logger) LoggerFactory.getLogger(LmdbSailStore.class);
	private final ListAppender<ILoggingEvent> appender = new ListAppender<>();
	private Level previousLevel;
	private boolean previousAdditive;

	@BeforeEach
	void captureLogging() {
		previousLevel = logger.getLevel();
		previousAdditive = logger.isAdditive();
		logger.setLevel(Level.TRACE);
		logger.setAdditive(false);
		appender.start();
		logger.addAppender(appender);
	}

	@AfterEach
	void restoreLogging() {
		logger.detachAppender(appender);
		appender.stop();
		logger.setLevel(previousLevel);
		logger.setAdditive(previousAdditive);
	}

	@Test
	void logsStatsAtInfoOnStartupAndShutdown() {
		logger.setLevel(Level.INFO);
		LmdbStore store = new LmdbStore(dataDir, config());
		store.init();
		LmdbStats committed;
		try {
			assertThat(snapshots(Level.INFO)).containsExactly(store.getLmdbStats());
			assertThat(events(Level.INFO).getFirst().getFormattedMessage()).contains("startup", dataDir.toString());
			try (NotifyingSailConnection connection = store.getConnection()) {
				connection.begin();
				connection.addStatement(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				connection.commit();
			}
			committed = store.getLmdbStats();
			assertThat(snapshots(Level.INFO)).hasSize(1);
		} finally {
			store.shutDown();
		}
		assertThat(snapshots(Level.INFO)).hasSize(2).last().isEqualTo(committed);
		assertThat(events(Level.INFO).getLast().getFormattedMessage()).contains("shutdown", dataDir.toString());
		assertThat(snapshots(Level.TRACE)).isEmpty();

		appender.list.clear();
		store.init();
		try {
			assertThat(snapshots(Level.INFO)).containsExactly(committed);
		} finally {
			store.shutDown();
		}
	}

	@ParameterizedTest
	@ValueSource(booleans = { false, true })
	void logsBeforeNativeWritesAndAfterCommit(boolean threaded) throws IOException {
		try (LmdbSailStore store = new LmdbSailStore(dataDir, new StoreProperties(), config(), false)) {
			store.enableMultiThreading = threaded;
			LmdbStats before = store.getLmdbStats();
			try (SailSink sink = store.getExplicitSailSource().sink(IsolationLevels.NONE)) {
				sink.approve(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				sink.approve(RDFS.LABEL, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				assertThat(snapshots(Level.TRACE)).containsExactly(before);
				assertThat(events(Level.TRACE).getFirst().getFormattedMessage())
						.contains("before writes", dataDir.toString());
				sink.prepare();
				assertThat(snapshots(Level.TRACE)).containsExactly(before);
				sink.flush();
				LmdbStats after = store.getLmdbStats();
				assertThat(snapshots(Level.TRACE)).containsExactly(before, after);
				assertThat(after.valueDatabases().get("main").entries())
						.isGreaterThan(before.valueDatabases().get("main").entries());
				assertThat(after.tripleDatabases().get("contexts").entries()).isEqualTo(1);
				assertThat(events(Level.TRACE).getLast().getFormattedMessage()).contains("after commit");

				// A reused sink starts a new native transaction and needs a fresh pair of snapshots.
				sink.approve(RDFS.COMMENT, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				assertThat(snapshots(Level.TRACE)).containsExactly(before, after, after);
				sink.flush();
				assertThat(snapshots(Level.TRACE)).containsExactly(before, after, after, store.getLmdbStats());
			}
		}
	}

	@ParameterizedTest
	@EnumSource(value = IsolationLevels.class, names = { "NONE", "READ_COMMITTED", "SNAPSHOT_READ", "SNAPSHOT",
			"SERIALIZABLE" })
	void logsWritesAcrossIsolationLevels(IsolationLevels isolation) {
		LmdbStore store = new LmdbStore(dataDir, config());
		store.init();
		try (LmdbStoreConnection connection = (LmdbStoreConnection) store.getConnection()) {
			LmdbStats before = store.getLmdbStats();
			connection.begin(isolation);
			connection.addStatement(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
			connection.addInferredStatement(RDFS.LABEL, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
			connection.prepare();
			connection.commit();
			assertWriteSnapshots(before, store.getLmdbStats());

			appender.list.clear();
			before = store.getLmdbStats();
			connection.begin(isolation);
			connection.removeStatements(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
			connection.clearInferred();
			connection.commit();
			assertWriteSnapshots(before, store.getLmdbStats());

			appender.list.clear();
			before = store.getLmdbStats();
			connection.begin(isolation);
			connection.setNamespace("rdf", RDF.NAMESPACE);
			connection.commit();
			assertWriteSnapshots(before, store.getLmdbStats());

			appender.list.clear();
			connection.begin(isolation);
			assertThat(connection.hasStatement(null, null, null, true)).isFalse();
			assertThat(connection.getNamespace("rdf")).isEqualTo(RDF.NAMESPACE);
			connection.prepare();
			connection.commit();
			assertThat(snapshots(Level.TRACE)).isEmpty();
		} finally {
			store.shutDown();
		}
	}

	@Test
	void rollbackDoesNotLogACommittedSnapshot() throws IOException {
		try (LmdbSailStore store = new LmdbSailStore(dataDir, new StoreProperties(), config(), false)) {
			store.enableMultiThreading = false;
			LmdbStats before = store.getLmdbStats();
			try (SailSink sink = store.getExplicitSailSource().sink(IsolationLevels.NONE)) {
				sink.approve(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				store.rollback();
				assertThat(snapshots(Level.TRACE)).containsExactly(before);
				assertThat(store.getLmdbStats()).isEqualTo(before);

				sink.approve(RDFS.LABEL, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
				sink.flush();
				assertThat(snapshots(Level.TRACE)).containsExactly(before, before, store.getLmdbStats());
			}
		}
	}

	@Test
	void disabledLoggingDoesNotCollectStats() throws IOException {
		logger.setLevel(Level.WARN);
		CountingStatsStore store = new CountingStatsStore(dataDir);
		try (store; SailSink sink = store.getExplicitSailSource().sink(IsolationLevels.NONE)) {
			sink.approve(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
			sink.flush();
		}
		assertThat(store.statsCalls).isZero();
	}

	@Test
	void statsFailureDoesNotFailWritesOrShutdown() throws IOException {
		CountingStatsStore store = new CountingStatsStore(dataDir);
		store.failStats = true;
		try (store; SailSink sink = store.getExplicitSailSource().sink(IsolationLevels.NONE)) {
			sink.approve(RDF.TYPE, RDF.TYPE, RDF.PROPERTY, RDFS.RESOURCE);
			sink.flush();
			assertThat(events(Level.WARN)).hasSize(2).allSatisfy(event -> {
				assertThat(event.getFormattedMessage()).contains("Unable to read native LMDB statistics");
				assertThat(event.getThrowableProxy().getMessage()).isEqualTo("Stats unavailable for test");
			});
			store.failStats = false;
			assertThat(store.getLmdbStats().tripleDatabases().get("contexts").entries()).isEqualTo(1);
			store.failStats = true;
		}
		assertThat(events(Level.WARN)).hasSize(3);
	}

	private void assertWriteSnapshots(LmdbStats before, LmdbStats after) {
		List<LmdbStats> snapshots = snapshots(Level.TRACE);
		assertThat(snapshots).isNotEmpty();
		assertThat(snapshots.size() % 2).isZero();
		assertThat(snapshots.getFirst()).isEqualTo(before);
		assertThat(snapshots.getLast()).isEqualTo(after);
	}

	private List<ILoggingEvent> events(Level level) {
		return appender.list.stream().filter(event -> event.getLevel().equals(level)).toList();
	}

	private List<LmdbStats> snapshots(Level level) {
		return events(level).stream()
				.filter(event -> event.getArgumentArray() != null)
				.flatMap(event -> Arrays.stream(event.getArgumentArray()))
				.filter(LmdbStats.class::isInstance)
				.map(LmdbStats.class::cast)
				.toList();
	}

	private static LmdbStoreConfig config() {
		return new LmdbStoreConfig("spoc,posc").setSketchEstimatorEnabled(false);
	}

	private static class CountingStatsStore extends LmdbSailStore {

		private int statsCalls;
		private boolean failStats;

		CountingStatsStore(File dataDir) throws IOException {
			super(dataDir, new StoreProperties(), config(), false);
		}

		@Override
		LmdbStats getLmdbStats() throws IOException {
			statsCalls++;
			if (failStats) {
				throw new IOException("Stats unavailable for test");
			}
			return super.getLmdbStats();
		}
	}
}
