/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Constructor;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Bound;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Distinct;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RewriteAssumption;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RewriteCertificate;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.RewriteSafety;
import org.junit.jupiter.api.Test;

class LmdbRewriteProofTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void negatedBoundOptionalAntiJoinCarriesLogicalBagProof() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional),
				new Not(new Bound(new Var("optName")))));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		Difference difference = assertInstanceOf(Difference.class, root.getArg(), () -> root.getArg().toString());
		assertProof(difference.getStringMetricPlanned("optimizer.negatedBoundOptionalAlternative"),
				"OPTIONAL_NEGATED_BOUND_ANTI_JOIN", "LOGICAL_BAG_EQUIVALENT", "rhsFreshAssuredBinding=optName");
	}

	@Test
	void optionalRhsAnchoringCarriesPhysicalProof() {
		StatementPattern left = statementPattern("person", "type", "type");
		StatementPattern right = statementPattern("person", "name", "name");
		QueryRoot root = new QueryRoot(new LeftJoin(left, right));

		new LmdbSketchJoinOptimizer(new OptionalAnchoringCostModel(right, 100.0d, 5.0d), false).optimize(root, null,
				null);

		assertProof(right.getStringMetricPlanned("optimizer.optionalRhsAnchoring"), "OPTIONAL_RHS_ANCHORING",
				"PHYSICAL_EQUIVALENT", "leftAssuredSharedBindings=person");
	}

	@Test
	void distinctIdempotentJoinCarriesSetProof() {
		StatementPattern pattern = statementPattern("person", "type", "type");
		QueryRoot root = new QueryRoot(new Distinct(new Join(pattern, pattern.clone())));

		new LmdbSetSemanticsOptimizer().optimize(root, null, null);

		Distinct distinct = assertInstanceOf(Distinct.class, root.getArg(), () -> root.getArg().toString());
		StatementPattern replacement = assertInstanceOf(StatementPattern.class, distinct.getArg(),
				() -> root.getArg().toString());
		assertProof(replacement.getStringMetricPlanned("optimizer.rewriteProof"), "SET_JOIN_IDEMPOTENCE",
				"SET_EQUIVALENT", "setContext=distinct");
	}

	@Test
	void metricFragmentIncludesGenericCertificateSafety() throws Exception {
		RewriteCertificate certificate = new RewriteCertificate("lmdb-test", "old", "new", RewriteSafety.builder()
				.preservedMultiplicity(false)
				.build(), Set.of(RewriteAssumption.STANDARD_SPARQL_SEMANTICS));
		Constructor<LmdbRewriteProof> constructor = LmdbRewriteProof.class.getDeclaredConstructor(
				LmdbRewriteProof.RewriteKind.class, LmdbRewriteProof.EquivalenceScope.class, Set.class,
				String.class, RewriteCertificate.class);
		constructor.setAccessible(true);
		LmdbRewriteProof proof = constructor.newInstance(LmdbRewriteProof.RewriteKind.SET_UNION_IDEMPOTENCE,
				LmdbRewriteProof.EquivalenceScope.SET_EQUIVALENT, Set.of("setContext=distinct"), "reason",
				certificate);

		String fragment = proof.metricFragment();

		assertTrue(fragment.contains("proofKind=SET_UNION_IDEMPOTENCE"), fragment);
		assertTrue(fragment.contains("preservedVisibleVars=true"), fragment);
		assertTrue(fragment.contains("preservedMultiplicity=false"), fragment);
		assertTrue(fragment.contains("preservedOrder=true"), fragment);
		assertTrue(fragment.contains("preservedErrors=true"), fragment);
		assertTrue(fragment.contains("preservedGraphScope=true"), fragment);
	}

	private static void assertProof(String metric, String kind, String scope, String fact) {
		assertTrue(metric != null && metric.contains("proofKind=" + kind), () -> String.valueOf(metric));
		assertTrue(metric.contains("proofScope=" + scope), () -> metric);
		assertTrue(metric.contains(fact), () -> metric);
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName));
	}

	private static final class OptionalAnchoringCostModel extends EvaluationStatistics
			implements JoinFactorCostModel {

		private final TupleExpr rightArg;
		private final double unanchoredWorkRows;
		private final double anchoredWorkRows;

		private OptionalAnchoringCostModel(TupleExpr rightArg, double unanchoredWorkRows, double anchoredWorkRows) {
			this.rightArg = rightArg;
			this.unanchoredWorkRows = unanchoredWorkRows;
			this.anchoredWorkRows = anchoredWorkRows;
		}

		@Override
		public Optional<JoinFactorCostModel.FactorCostEstimate> estimateFactorCost(TupleExpr factor,
				Set<String> currentlyBoundVars) {
			if (factor == rightArg || factor.equals(rightArg)) {
				return Optional.of(new JoinFactorCostModel.FactorCostEstimate(
						currentlyBoundVars.contains("person") ? anchoredWorkRows : unanchoredWorkRows, 1.0d));
			}
			return Optional.of(new JoinFactorCostModel.FactorCostEstimate(1.0d, 1.0d));
		}
	}
}
