/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalLong;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Stream;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.base.SailDataset;
import org.eclipse.rdf4j.sail.base.SailDatasetTripleTermSource;
import org.eclipse.rdf4j.sail.lmdb.LmdbFiniteJoinSurfaceEstimator.SurfaceEstimate;
import org.eclipse.rdf4j.sail.lmdb.TxnManager.Txn;
import org.eclipse.rdf4j.sail.lmdb.config.FrontierEstimatorMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Planner-time storage reads must reuse the query's own pinned dataset lease instead of taking nested reader leases.
 *
 * <p>
 * The LMDB reader pool hands out {@link TxnManager#POOL_SIZE} leases: {@code POOL_SIZE - 1} ordinary slots plus one
 * reserved slot for short priority callbacks, with a 30 s admission timeout. A default query already holds two ordinary
 * leases (explicit and inferred dataset). These tests leave exactly those dataset slots free and occupy the reserved
 * slot as well, so any nested lease taken while planning blocks for the full admission timeout and the query cannot
 * finish within the assertion window.
 * </p>
 */
class LmdbPlannerReaderLeaseTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final String NS = "http://ex/";
	private static final long QUERY_TIMEOUT_MILLIS = 8_000L;

	private static final String REPEATED_VARIABLE_QUERY = "SELECT (COUNT(?s) AS ?c) WHERE { ?s <http://ex/p> ?s }";
	private static final String PLAIN_QUERY = "SELECT (COUNT(?s) AS ?c) WHERE { ?s <http://ex/p> ?o }";
	private static final String FILTER_QUERY = "SELECT (COUNT(?s) AS ?c) WHERE { ?s <http://ex/p> ?o . "
			+ "?s <http://ex/q> ?n FILTER(?n > 150) }";
	/** Unrelated warm-up query: initialises lazy planner structures without caching the pressured query's plan. */
	private static final String WARMUP_QUERY = "SELECT (COUNT(?x) AS ?c) WHERE { ?x <http://ex/q> ?y }";
	private static final String VALUES_JOIN_QUERY = "SELECT (COUNT(?s) AS ?c) WHERE { "
			+ "VALUES ?s { <http://ex/s0> <http://ex/s2> <http://ex/s4> } ?s <http://ex/p> ?o . ?s <http://ex/q> ?n }";

	static TripleStore tripleStore(LmdbStore store) throws Exception {
		Field field = LmdbSailStore.class.getDeclaredField("tripleStore");
		field.setAccessible(true);
		return (TripleStore) field.get(store.getBackingStore());
	}

	static ValueStore valueStore(LmdbStore store) throws Exception {
		Field field = LmdbSailStore.class.getDeclaredField("valueStore");
		field.setAccessible(true);
		return (ValueStore) field.get(store.getBackingStore());
	}

	static SailRepository repository(Path dir, FrontierEstimatorMode mode) {
		LmdbStoreConfig config = new LmdbStoreConfig();
		if (mode != null) {
			config.setFrontierEstimatorMode(mode);
		}
		SailRepository repository = new SailRepository(new LmdbStore(dir.toFile(), config));
		repository.init();
		return repository;
	}

	/** 200 {@code :p} rows (every even subject is a self-loop) and one {@code :q} literal per subject. */
	static void loadSelfLoops(SailRepository repository) {
		try (SailRepositoryConnection conn = repository.getConnection()) {
			conn.begin();
			IRI p = VF.createIRI(NS, "p");
			IRI q = VF.createIRI(NS, "q");
			for (int i = 0; i < 200; i++) {
				IRI s = VF.createIRI(NS, "s" + i);
				conn.add(s, p, i % 2 == 0 ? s : VF.createIRI(NS, "o" + i));
				conn.add(s, q, VF.createLiteral(i));
			}
			conn.commit();
		}
	}

	static List<Txn> hold(TxnManager manager, int count) throws Exception {
		List<Txn> held = new ArrayList<>();
		for (int i = 0; i < count; i++) {
			held.add(manager.createReadTxn());
		}
		return held;
	}

	static void release(List<Txn> held) {
		for (Txn txn : held) {
			txn.close();
		}
		held.clear();
	}

	/**
	 * Occupies the single reserved (priority) reader slot on a helper thread until {@link #release()} is called. Every
	 * ordinary slot must already be taken when this starts, otherwise the priority callback prefers an ordinary slot.
	 */
	static final class ReservedSlotHolder implements AutoCloseable {

		private final CountDownLatch started = new CountDownLatch(1);
		private final CountDownLatch release = new CountDownLatch(1);
		private final Thread thread;
		private final AtomicReference<Throwable> failure = new AtomicReference<>();

		ReservedSlotHolder(TxnManager manager) throws InterruptedException {
			thread = new Thread(() -> {
				try {
					manager.doWithPriority((stack, txn) -> {
						started.countDown();
						try {
							release.await();
						} catch (InterruptedException e) {
							Thread.currentThread().interrupt();
						}
						return null;
					});
				} catch (Throwable t) {
					failure.set(t);
					started.countDown();
				}
			}, "reserved-slot-holder");
			thread.setDaemon(true);
			thread.start();
			assertTrue(started.await(10, TimeUnit.SECONDS), "reserved slot holder did not start");
			assertNull(failure.get(), "reserved slot holder failed: " + failure.get());
		}

		@Override
		public void close() throws InterruptedException {
			release.countDown();
			thread.join(TimeUnit.SECONDS.toMillis(30));
		}
	}

	static Stream<Arguments> pressureCases() {
		List<Arguments> cases = new ArrayList<>();
		for (FrontierEstimatorMode mode : new FrontierEstimatorMode[] { null, FrontierEstimatorMode.OFF }) {
			cases.add(Arguments.of("repeated variable", REPEATED_VARIABLE_QUERY, 100, mode));
			cases.add(Arguments.of("plain", PLAIN_QUERY, 200, mode));
			cases.add(Arguments.of("filter", FILTER_QUERY, 49, mode));
			cases.add(Arguments.of("values join", VALUES_JOIN_QUERY, 3, mode));
		}
		return cases.stream();
	}

	/**
	 * End-to-end: all ordinary slots but the two dataset slots are taken and the reserved slot is held by another
	 * thread. Planning must complete without any nested reader lease.
	 */
	@ParameterizedTest(name = "{0} query, frontier mode {3}")
	@MethodSource("pressureCases")
	void queryPlansWithoutNestedReaderLeases(String label, String query, int expectedCount,
			FrontierEstimatorMode mode, @TempDir Path dir) throws Exception {
		runUnderReaderPressure(dir, mode, query, true, expectedCount, 2, conn -> {
		});
	}

	/** An explicit-only query holds a single dataset lease; planning must not take a second one. */
	@ParameterizedTest(name = "frontier mode {0}")
	@MethodSource("frontierModes")
	void explicitOnlyQueryPlansWithoutNestedReaderLeases(FrontierEstimatorMode mode, @TempDir Path dir)
			throws Exception {
		runUnderReaderPressure(dir, mode, FILTER_QUERY, false, 49, 1, conn -> {
		});
	}

	/**
	 * Inside an active transaction the dataset is an uncommitted overlay over the committed LMDB snapshot; planning
	 * reads must still bind to that snapshot's lease.
	 */
	@ParameterizedTest(name = "frontier mode {0}")
	@MethodSource("frontierModes")
	void activeTransactionQueryPlansWithoutNestedReaderLeases(FrontierEstimatorMode mode, @TempDir Path dir)
			throws Exception {
		runUnderReaderPressure(dir, mode, FILTER_QUERY, true, 50, 2, conn -> {
			conn.begin();
			IRI s = VF.createIRI(NS, "s999");
			conn.add(s, VF.createIRI(NS, "p"), s);
			conn.add(s, VF.createIRI(NS, "q"), VF.createLiteral(999));
		});
	}

	static Stream<FrontierEstimatorMode> frontierModes() {
		return Stream.of(null, FrontierEstimatorMode.OFF);
	}

	interface ConnectionSetup {
		void prepare(SailRepositoryConnection conn);
	}

	private void runUnderReaderPressure(Path dir, FrontierEstimatorMode mode, String query,
			boolean includeInferred, int expectedCount, int datasetSlots, ConnectionSetup setup) throws Exception {
		SailRepository repository = repository(dir, mode);
		List<Txn> held = new ArrayList<>();
		AtomicReference<Throwable> failure = new AtomicReference<>();
		AtomicReference<String> result = new AtomicReference<>();
		Thread worker = null;
		ReservedSlotHolder reserved = null;
		try {
			loadSelfLoops(repository);
			// warm-up on committed data without pressure initialises lazy planner structures; a different query is
			// used so the pressured query is planned cold instead of served from the pipeline plan cache
			assertEquals(200, count(repository, WARMUP_QUERY, includeInferred, conn -> {
			}));
			LmdbStore store = (LmdbStore) repository.getSail();
			TxnManager manager = tripleStore(store).getTxnManager();
			held.addAll(hold(manager, TxnManager.POOL_SIZE - 1));
			reserved = new ReservedSlotHolder(manager);
			for (int i = 0; i < datasetSlots; i++) {
				held.remove(held.size() - 1).close();
			}
			worker = new Thread(() -> {
				try {
					result.set(Integer.toString(count(repository, query, includeInferred, setup)));
				} catch (Throwable t) {
					failure.set(t);
				}
			}, "planner-lease-query");
			worker.start();
			worker.join(QUERY_TIMEOUT_MILLIS);
			boolean done = !worker.isAlive();
			StringBuilder blockedAt = new StringBuilder();
			if (!done) {
				// The worker's stack names the planner read that is waiting on the reader pool.
				for (StackTraceElement element : worker.getStackTrace()) {
					blockedAt.append("\n\tat ").append(element);
				}
			}
			assertTrue(done, "query did not finish within " + QUERY_TIMEOUT_MILLIS + " ms while only its "
					+ datasetSlots + " dataset slot(s) were free: a planner read took a nested reader lease"
					+ blockedAt);
			assertNull(failure.get(), "query failed: " + failure.get());
			assertEquals(Integer.toString(expectedCount), result.get());
		} finally {
			if (reserved != null) {
				reserved.close();
			}
			release(held);
			if (worker != null) {
				worker.join(60_000);
			}
			repository.shutDown();
		}
	}

	private static int count(SailRepository repository, String query, boolean includeInferred,
			ConnectionSetup setup) {
		try (SailRepositoryConnection conn = repository.getConnection()) {
			setup.prepare(conn);
			TupleQuery tupleQuery = conn.prepareTupleQuery(query);
			tupleQuery.setIncludeInferred(includeInferred);
			int count = -1;
			try (TupleQueryResult res = tupleQuery.evaluate()) {
				for (BindingSet bs : res) {
					count = Integer.parseInt(bs.getValue("c").stringValue());
				}
			}
			if (conn.isActive()) {
				conn.rollback();
			}
			return count;
		}
	}

	// ---------------------------------------------------------------------------------------------
	// Direct TripleStore-level tests of the pinned planning lease
	// ---------------------------------------------------------------------------------------------

	private static final long UNBOUND = -1L;
	private static final long P = 2L;
	private static final long Q = 3L;

	/** A bare TripleStore with {@code spoc,posc}; subjects 10..209 with {@code :p} rows (even ones self-loops). */
	private static TripleStore openTripleStore(File tempFolder) throws Exception {
		File dataDir = new File(tempFolder, "triplestore");
		dataDir.mkdir();
		TripleStore tripleStore = new TripleStore(dataDir,
				new LmdbStoreConfig("spoc,posc").setPageCardinalityEstimator(true), null);
		tripleStore.startTransaction();
		for (long s = 10L; s < 210L; s++) {
			tripleStore.storeTriple(s, P, s % 2 == 0 ? s : 1_000L + s, 4L, true);
			tripleStore.storeTriple(s, Q, 2_000L + s, 4L, true);
		}
		tripleStore.commit();
		return tripleStore;
	}

	private static StatementPattern distinctSubjectPattern() {
		StatementPattern pattern = new StatementPattern(new Var("s"), new Var("p", VF.createIRI(NS, "p")),
				new Var("o"));
		new LmdbDistinctRequirement(Set.of("s"), Set.of(), Set.of(), "planner-lease-test").annotate(pattern);
		return pattern;
	}

	/** Every converted planner read, sampled with no pin and no pressure: the values the pinned run must match. */
	private record PlannerReads(double cardinality, double planning, double repeated, double exact,
			OptionalLong boundedExact, double randomSeekWork, int stratified, OptionalLong distinct) {

		static PlannerReads capture(TripleStore tripleStore) throws Exception {
			int mask = TripleStore.repeatedComponentPairMask(TripleStore.SUBJ_IDX, TripleStore.OBJ_IDX);
			int[] delivered = { 0 };
			int stratified = tripleStore.sampleTriplesStratified(UNBOUND, P, UNBOUND, UNBOUND, true, 4, 8, row -> {
				delivered[0]++;
				return true;
			});
			return new PlannerReads(
					tripleStore.cardinality(UNBOUND, P, UNBOUND, UNBOUND),
					tripleStore.planningCardinalityEstimate(UNBOUND, P, UNBOUND, UNBOUND).entries(),
					tripleStore.repeatedVariableCardinality(UNBOUND, P, UNBOUND, UNBOUND, mask, 4_096L).rows(),
					tripleStore.exactCardinality(UNBOUND, P, UNBOUND, UNBOUND, 4_096L).orElseThrow(),
					tripleStore.boundedExactCardinality(10L, P, UNBOUND, UNBOUND, 100L),
					tripleStore.indexCostProfile("spoc", true).randomSeekWork(),
					stratified,
					tripleStore.boundedDistinctCursorSkipCardinality(distinctSubjectPattern(), UNBOUND, P, UNBOUND,
							UNBOUND, 1_000));
		}
	}

	/**
	 * With a pin present and both the ordinary and the reserved slot exhausted by other holders, every planner-time
	 * read completes on the pinned transaction, returns the unpressured value and takes no admission at all.
	 */
	@Test
	void pinnedPlannerReadsTakeNoNestedLease(@TempDir File tempFolder) throws Exception {
		TripleStore tripleStore = openTripleStore(tempFolder);
		TxnManager manager = tripleStore.getTxnManager();
		List<Txn> held = new ArrayList<>();
		ExecutorService executor = Executors.newSingleThreadExecutor();
		ReservedSlotHolder reserved = null;
		try {
			PlannerReads expected = PlannerReads.capture(tripleStore);
			assertEquals(200.0d, expected.exact(), 0.0d);
			assertEquals(100.0d, expected.repeated(), 0.0d);
			assertEquals(OptionalLong.of(1L), expected.boundedExact());
			assertTrue(expected.stratified() > 0);

			Txn pinned = manager.createReadTxn();
			held.add(pinned);
			held.addAll(hold(manager, TxnManager.POOL_SIZE - 2));
			assertEquals(0, manager.availableOrdinaryPermits());
			reserved = new ReservedSlotHolder(manager);
			assertEquals(0, manager.availableReservedPermits());
			long ordinaryBefore = manager.ordinaryAdmissions();
			long reservedBefore = manager.reservedAdmissions();

			PlannerReads pinnedReads = executor.submit(() -> {
				try (TripleStore.PlanningReadPin pin = tripleStore.pinPlanningTxn(pinned)) {
					assertTrue(tripleStore.planningReadsPinned());
					return PlannerReads.capture(tripleStore);
				}
			}).get(10, TimeUnit.SECONDS);

			assertEquals(expected, pinnedReads);
			assertEquals(ordinaryBefore, manager.ordinaryAdmissions(), "pinned planner reads took an ordinary lease");
			assertEquals(reservedBefore, manager.reservedAdmissions(), "pinned planner reads took the reserved slot");
		} finally {
			if (reserved != null) {
				reserved.close();
			}
			release(held);
			executor.shutdownNow();
			tripleStore.close();
		}
	}

	/**
	 * The finite join surface estimator opens a planning transaction and, inside it, asks for planning cardinalities of
	 * the seed candidates. Converting the outer read to the reserved slot alone would self-deadlock on the nested read;
	 * with the pin both reads share the query's transaction and no admission is needed.
	 */
	@Test
	void finiteSurfaceEstimateWithNestedPlanningReadCompletesWhilePinned(@TempDir Path dir) throws Exception {
		SailRepository repository = repository(dir, null);
		List<Txn> held = new ArrayList<>();
		ExecutorService executor = Executors.newSingleThreadExecutor();
		ReservedSlotHolder reserved = null;
		SailDataset dataset = null;
		try {
			loadSelfLoops(repository);
			LmdbStore store = (LmdbStore) repository.getSail();
			TripleStore tripleStore = tripleStore(store);
			TxnManager manager = tripleStore.getTxnManager();
			LmdbFiniteJoinSurfaceEstimator estimator = new LmdbFiniteJoinSurfaceEstimator(valueStore(store),
					tripleStore);
			StatementPattern prefix = new StatementPattern(new Var("s"), new Var("q", VF.createIRI(NS, "q")),
					new Var("n"));
			StatementPattern factor = new StatementPattern(new Var("s"), new Var("p", VF.createIRI(NS, "p")),
					new Var("o"));
			Callable<Optional<SurfaceEstimate>> estimate = () -> estimator.estimate(List.of(prefix.clone()),
					factor.clone(), Map.of());
			Optional<SurfaceEstimate> unpressured = estimate.call();
			assertTrue(unpressured.isPresent(), "the unpressured finite surface estimate must be available");

			dataset = store.getBackingStore().getExplicitSailSource().dataset(IsolationLevels.SNAPSHOT_READ);
			Txn datasetTxn = ((LmdbPinnedReadTxnSource) dataset).pinnedReadTxn().orElseThrow();
			assertTrue(datasetTxn.isTracked());
			held.addAll(hold(manager, manager.availableOrdinaryPermits()));
			reserved = new ReservedSlotHolder(manager);
			long ordinaryBefore = manager.ordinaryAdmissions();
			long reservedBefore = manager.reservedAdmissions();

			Optional<SurfaceEstimate> pinned = executor.submit(() -> {
				try (TripleStore.PlanningReadPin pin = tripleStore.pinPlanningTxn(datasetTxn)) {
					return estimate.call();
				}
			}).get(10, TimeUnit.SECONDS);

			assertTrue(pinned.isPresent(), "pinned finite surface estimate was declined");
			assertEquals(unpressured.get().surfaceRows(), pinned.get().surfaceRows(), 0.0d);
			assertEquals(ordinaryBefore, manager.ordinaryAdmissions());
			assertEquals(reservedBefore, manager.reservedAdmissions());
		} finally {
			if (reserved != null) {
				reserved.close();
			}
			release(held);
			if (dataset != null) {
				dataset.close();
			}
			executor.shutdownNow();
			repository.shutDown();
		}
	}

	/** Nested pins keep the outermost transaction and the pin is gone once the outermost one closes. */
	@Test
	void pinLifetimeIsStructurallyNested(@TempDir File tempFolder) throws Exception {
		TripleStore tripleStore = openTripleStore(tempFolder);
		TxnManager manager = tripleStore.getTxnManager();
		try (Txn outer = manager.createReadTxn(); Txn inner = manager.createReadTxn()) {
			assertFalse(tripleStore.planningReadsPinned());
			try (TripleStore.PlanningReadPin first = tripleStore.pinPlanningTxn(outer)) {
				assertTrue(tripleStore.planningReadsPinned());
				try (TripleStore.PlanningReadPin second = tripleStore.pinPlanningTxn(inner)) {
					assertTrue(tripleStore.planningReadsPinned());
					try (Txn view = tripleStore.planningReadTxn()) {
						assertTrue(view.isView());
						assertEquals(outer.get(), view.get(), "the outermost pin wins");
					}
				}
				assertTrue(tripleStore.planningReadsPinned(), "closing an inner pin must not unpin the outer one");
			}
			assertFalse(tripleStore.planningReadsPinned());
			long ordinaryBefore = manager.ordinaryAdmissions();
			try (Txn fresh = tripleStore.planningReadTxn()) {
				assertFalse(fresh.isView());
				assertEquals(ordinaryBefore + 1, manager.ordinaryAdmissions(), "unpinned reads take a fresh lease");
			}
		} finally {
			tripleStore.close();
		}
	}

	/**
	 * After the pipeline returns, the query thread carries no pin: a later direct planning read takes its own lease.
	 */
	@Test
	void pipelinePinIsReleasedBeforeTheQueryReturns(@TempDir Path dir) throws Exception {
		SailRepository repository = repository(dir, null);
		try {
			loadSelfLoops(repository);
			TripleStore tripleStore = tripleStore((LmdbStore) repository.getSail());
			AtomicBoolean pinnedAfterQuery = new AtomicBoolean(true);
			AtomicReference<Throwable> failure = new AtomicReference<>();
			Thread worker = new Thread(() -> {
				try {
					assertEquals(49, count(repository, FILTER_QUERY, true, conn -> {
					}));
					pinnedAfterQuery.set(tripleStore.planningReadsPinned());
				} catch (Throwable t) {
					failure.set(t);
				}
			}, "planner-pin-lifetime");
			worker.start();
			worker.join(60_000);
			assertNull(failure.get());
			assertFalse(pinnedAfterQuery.get(), "the pipeline left its planning pin on the query thread");
		} finally {
			repository.shutDown();
		}
	}

	/**
	 * Unpinned callers hold no dataset slot: a bounded scan takes one ordinary lease (never the reserved slot, which
	 * must stay free for short nested reads), and a short read exhausted of ordinary slots falls back to the reserved
	 * slot exactly as develop's estimator does.
	 */
	@Test
	void unpinnedFallbacksKeepDevelopLeaseDiscipline(@TempDir File tempFolder) throws Exception {
		TripleStore tripleStore = openTripleStore(tempFolder);
		TxnManager manager = tripleStore.getTxnManager();
		List<Txn> held = new ArrayList<>();
		ExecutorService executor = Executors.newSingleThreadExecutor();
		try {
			long ordinaryBefore = manager.ordinaryAdmissions();
			long reservedBefore = manager.reservedAdmissions();
			int delivered = tripleStore.sampleTriplesStratified(UNBOUND, P, UNBOUND, UNBOUND, true, 4, 8,
					row -> true);
			assertTrue(delivered > 0);
			assertEquals(ordinaryBefore + 1, manager.ordinaryAdmissions(), "a scan takes one ordinary lease");
			assertEquals(reservedBefore, manager.reservedAdmissions(), "a scan must not use the reserved slot");

			held.addAll(hold(manager, TxnManager.POOL_SIZE - 1));
			reservedBefore = manager.reservedAdmissions();
			double cardinality = executor.submit(() -> tripleStore.cardinality(UNBOUND, P, UNBOUND, UNBOUND))
					.get(5, TimeUnit.SECONDS);
			assertTrue(cardinality > 0.0d);
			assertEquals(reservedBefore + 1, manager.reservedAdmissions(),
					"an unpinned short read with no ordinary slot left uses the reserved slot");
		} finally {
			release(held);
			executor.shutdownNow();
			tripleStore.close();
		}
	}

	/**
	 * In {@link TxnManager.Mode#RESET} a closed transaction keeps a live native handle, is parked in the reuse pool and
	 * may be handed to another caller. A pin on such a transaction must be treated as dead: planning reads fall back to
	 * a fresh lease instead of reading through somebody else's transaction.
	 */
	@Test
	void closedOrRecycledPinFallsBackToAFreshLease(@TempDir File tempFolder) throws Exception {
		TripleStore tripleStore = openTripleStore(tempFolder);
		TxnManager manager = tripleStore.getTxnManager();
		ExecutorService other = Executors.newSingleThreadExecutor();
		Txn recycled = null;
		try {
			Txn pinned = manager.createReadTxn();
			long pinnedLease = pinned.leaseId();
			try (TripleStore.PlanningReadPin pin = tripleStore.pinPlanningTxn(pinned)) {
				assertTrue(tripleStore.planningReadsPinned());
				// the dataset is closed (from any thread) while the pin is still held
				other.submit(pinned::close).get(5, TimeUnit.SECONDS);
				assertFalse(pinned.isLive(pinnedLease));
				assertFalse(tripleStore.planningReadsPinned(), "a closed transaction must not stay pinned");
				long ordinaryBefore = manager.ordinaryAdmissions();
				try (Txn fresh = tripleStore.planningReadTxn()) {
					assertFalse(fresh.isView());
					assertEquals(ordinaryBefore + 1, manager.ordinaryAdmissions());
					// the fresh lease may legitimately recycle the pooled object, but under a new lease id
					assertTrue(fresh.isLive(fresh.leaseId()));
					assertTrue(fresh != pinned || fresh.leaseId() != pinnedLease,
							"a recycled transaction must carry a new lease id");
				}
				// another caller recycles the pooled transaction under a new lease
				recycled = other.submit(manager::createReadTxn).get(5, TimeUnit.SECONDS);
				if (recycled == pinned) {
					assertTrue(recycled.isLive(recycled.leaseId()));
					assertFalse(pinned.isLive(pinnedLease), "a recycled lease must not match the pinned lease");
				}
				assertFalse(tripleStore.planningReadsPinned(), "a recycled transaction must not revive the pin");
			}
		} finally {
			if (recycled != null) {
				recycled.close();
			}
			other.shutdownNow();
			tripleStore.close();
		}
	}

	/**
	 * Untracked readers keep their pre-commit snapshot, while the revision-keyed shared planning caches assume every
	 * planning read sees the committed head. Pinning an untracked transaction is therefore refused: a planning read
	 * after a commit sees the new rows even though the untracked snapshot still does not.
	 */
	@Test
	void untrackedSnapshotIsNeverPinned(@TempDir File tempFolder) throws Exception {
		TripleStore tripleStore = openTripleStore(tempFolder);
		TxnManager manager = tripleStore.getTxnManager();
		try (Txn untracked = manager.createReadTxnUntracked()) {
			assertFalse(untracked.isTracked());
			try (TripleStore.PlanningReadPin pin = tripleStore.pinPlanningTxn(untracked)) {
				assertFalse(tripleStore.planningReadsPinned(), "an untracked snapshot must never be pinned");
				assertSame(TripleStore.PlanningReadPin.NONE, pin);

				tripleStore.startTransaction();
				tripleStore.storeTriple(5_000L, P, 5_001L, 4L, true);
				tripleStore.commit();

				assertEquals(201.0d, tripleStore.exactCardinality(UNBOUND, P, UNBOUND, UNBOUND, 4_096L).orElseThrow(),
						0.0d, "planning reads must see the committed head");
				int snapshotRows = 0;
				try (RecordIterator rows = tripleStore.getTriples(untracked, UNBOUND, P, UNBOUND, UNBOUND, true)) {
					while (rows.next() != null) {
						snapshotRows++;
					}
				}
				assertEquals(200, snapshotRows, "the untracked snapshot itself still predates the commit");
			}
		} finally {
			tripleStore.close();
		}
	}

	/**
	 * An LMDB dataset lends its tracked read transaction while open and nothing once closed. Resolution through the
	 * explicit+inferred union and through uncommitted overlays is exercised end-to-end by the pressure cases above
	 * (default include-inferred queries and the active-transaction case), and the wrapper forwarding itself by
	 * {@code SailDatasetUnwrapTest} in sail-base.
	 */
	@Test
	void datasetUnwrapResolvesThePinnedTransaction(@TempDir Path dir) throws Exception {
		SailRepository repository = repository(dir, null);
		SailDataset explicit = null;
		try {
			loadSelfLoops(repository);
			LmdbSailStore backing = ((LmdbStore) repository.getSail()).getBackingStore();
			explicit = backing.getExplicitSailSource().dataset(IsolationLevels.SNAPSHOT_READ);
			SailDatasetTripleTermSource source = new SailDatasetTripleTermSource(VF, explicit);
			Optional<LmdbPinnedReadTxnSource> resolved = source.unwrapDataset(LmdbPinnedReadTxnSource.class);
			assertTrue(resolved.isPresent(), "the LMDB dataset did not expose itself as a pinned txn source");
			assertSame(explicit, resolved.get());
			assertTrue(resolved.get().pinnedReadTxn().orElseThrow().isTracked());
			assertTrue(source.unwrapDataset(String.class).isEmpty());

			explicit.close();
			assertTrue(resolved.get().pinnedReadTxn().isEmpty(), "a closed dataset lends no transaction");
		} finally {
			if (explicit != null) {
				explicit.close();
			}
			repository.shutDown();
		}
	}
}
