/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.eclipse.rdf4j.benchmark.common.ThemeQueryCatalog;
import org.eclipse.rdf4j.benchmark.rio.util.ThemeDataSetGenerator;
import org.eclipse.rdf4j.benchmark.rio.util.ThemeDataSetGenerator.Theme;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.query.explanation.GenericPlanNode;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.repository.util.RDFInserter;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Capability gate for the kernel (Janino code generation) tier: <em>no theme query may decline</em>.
 * <p>
 * Every query in the theme catalog is executed at {@link Explanation.Level#Telemetry}, which runs the query and records
 * each strategy rung that refused the plan on the explain tree. The kernel rungs record themselves as {@code irKernel:}
 * and {@code irAggregate:}; this test collects those reasons across all themes and fails while any remain.
 * <p>
 * Two decline reasons are deliberately <b>not</b> capability failures and are excluded:
 * {@code below-threshold-or-pending} (the compile service admits a shape only after it has been seen enough, and
 * compiles asynchronously) and {@code adjacency-unavailable} for stores that genuinely have no view. Each query is
 * warmed repeatedly so the former resolves; if it still appears it is reported separately rather than counted as a
 * capability gap.
 * <p>
 * The dataset is a scaled-down generation of every theme, loaded into one store, mirroring the benchmark store's
 * cross-theme shape (the ANALYTICS theme queries span the other themes' data and generate nothing of their own).
 * Scaling keeps the gate fast; declines recorded here are structural — they come from plan node kinds the lowering does
 * not recognise, which the query's algebra determines, not the data volume.
 */
public class LmdbNativeKernelDeclineCensusTest {

	/** Matches the decline reasons the two kernel rungs record on the explain tree. */
	private static final Pattern KERNEL_DECLINE = Pattern
			.compile("(irKernelInterpreted|irKernel|irAggregateInterpreted|irAggregate):([^ ,)|]+)");

	/** Matches the winning-strategy metric, whose value is a pipe-separated list of tags per plan node. */
	private static final Pattern EXECUTION_PATH = Pattern.compile("nativeExecutionPath=([^,)]+)");

	/**
	 * Declines that mean something other than "cannot do this", and so are not capability gaps.
	 * <p>
	 * {@code below-threshold-or-pending} means "not warmed up yet". {@code no-fusion-opportunity} means the shape has a
	 * single scan, so whole-stage code generation has nothing to fuse and the bulk batch cursor serves it better.
	 * {@code higher-cost} and {@code outranked} are common-arbiter decisions over eligible proposals, not lowering
	 * failures.
	 */
	private static final Set<String> NON_CAPABILITY_REASONS = Set.of("below-threshold-or-pending",
			"no-fusion-opportunity", "higher-cost", "outranked", "probe-trial-lost", "adaptive-higher-cost",
			"blocking-semantic-row");
	/** The only non-capability outcome another warmup execution can actually clear. */
	private static final Set<String> RETRYABLE_REASONS = Set.of("below-threshold-or-pending");

	/** Repeats per query, so an asynchronous compile has landed before the reading run. */
	private static final int WARMUP_RUNS = 6;
	private static final String SYNCHRONOUS_CODEGEN_PROPERTY = "rdf4j.lmdb.janinoCodegen.synchronous";

	/**
	 * Per-run wall-clock cap. {@code explain} defaults to sixty seconds per query
	 * ({@code AbstractParserQuery.DEFAULT_EXPLANATION_EXECUTION_TIMEOUT}); a declining query is by definition one
	 * running its slow interpreted path, so without a cap the census is dominated by the very queries it exists to
	 * find. Declines are recorded when a rung refuses at open time, so a truncated run still reports them.
	 */
	private static final int QUERY_TIMEOUT_SECONDS = 5;
	/**
	 * Minimal non-aggregate two-pattern join retained as a reachability witness for the set-at-a-time chunk pipeline.
	 * The chunk pipeline is the semantic successor to the legacy batch route and owns this row-producing shape.
	 */
	private static final String ROW_JOIN_WITNESS_QUERY = "SELECT ?s ?p ?o ?q ?v WHERE { "
			+ "?s ?p ?o . ?s ?q ?v . } LIMIT 1";

	@TempDir
	static File dataDir;

	private static LmdbStore store;
	private static SailRepository repository;
	private static String previousThreshold;
	private static String previousSynchronous;

	@BeforeAll
	static void setUp() {
		previousThreshold = System.getProperty("rdf4j.lmdb.janinoCodegen.thresholdRows");
		previousSynchronous = System.getProperty(SYNCHRONOUS_CODEGEN_PROPERTY);
		System.setProperty("rdf4j.lmdb.janinoCodegen.thresholdRows", "0");
		System.setProperty(SYNCHRONOUS_CODEGEN_PROPERTY, "true");
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc,ospc")
				.setDirectAdjacencyBuildOnStart(false);
		store = new LmdbStore(dataDir, config);
		repository = new SailRepository(store);
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			RDFInserter inserter = new RDFInserter(connection);
			ThemeDataSetGenerator.generateMedicalRecords(
					ThemeDataSetGenerator.medicalConfig().withPatientCount(600).withPractitionerCount(600), inserter);
			ThemeDataSetGenerator.generateSocialMedia(
					ThemeDataSetGenerator.socialMediaConfig().withUserCount(900).withPostsPerUser(6), inserter);
			ThemeDataSetGenerator.generateLibrary(
					ThemeDataSetGenerator.libraryConfig()
							.withBookCount(4000)
							.withAuthorCount(1200)
							.withMemberCount(500),
					inserter);
			ThemeDataSetGenerator.generateEngineering(
					ThemeDataSetGenerator.engineeringConfig().withComponentCount(5000).withAssemblyCount(150),
					inserter);
			// Scaled harder than the other themes on purpose. HIGHLY_CONNECTED q12 is `SELECT DISTINCT *` over a
			// two-hop expansion, whose row count grows with the sum over edges of the far endpoint's out-degree — hubs
			// make that superlinear, and the materializing DISTINCT above the kernel then exhausts the fork's heap
			// before the per-query timeout can stop it. Plan shape, which is all this census reads, does not depend on
			// the counts.
			ThemeDataSetGenerator.generateHighlyConnected(
					ThemeDataSetGenerator.highlyConnectedConfig()
							.withNodeCount(400)
							.withHubCount(3)
							.withEdgesPerNode(4),
					inserter);
			ThemeDataSetGenerator.generateTrain(
					ThemeDataSetGenerator.trainConfig()
							.withStationCount(2000)
							.withRouteCount(400)
							.withTrainCount(800),
					inserter);
			ThemeDataSetGenerator.generateElectricalGrid(
					ThemeDataSetGenerator.electricalGridConfig().withSubstationCount(700), inserter);
			ThemeDataSetGenerator.generatePharma(
					ThemeDataSetGenerator.pharmaConfig().withDrugCount(500).withMoleculeCount(750), inserter);
			ThemeDataSetGenerator.generateAdaptiveFilterPlacement(
					ThemeDataSetGenerator.adaptiveFilterPlacementConfig()
							.withProbeCount(2048)
							.withDecoyRouteCount(4096),
					inserter);
			ThemeDataSetGenerator.generateRealEstate(
					ThemeDataSetGenerator.realEstateConfig()
							.withPropertyCount(3000)
							.withAgentCount(300)
							.withDistrictCount(40)
							.withAmenityCount(60),
					inserter);
			connection.commit();
		}
		JaninoCeilingKernels.buildDirectAdjacency(store);
	}

	@AfterAll
	static void tearDown() {
		if (repository != null) {
			repository.shutDown();
		}
		if (previousThreshold == null) {
			System.clearProperty("rdf4j.lmdb.janinoCodegen.thresholdRows");
		} else {
			System.setProperty("rdf4j.lmdb.janinoCodegen.thresholdRows", previousThreshold);
		}
		if (previousSynchronous == null) {
			System.clearProperty(SYNCHRONOUS_CODEGEN_PROPERTY);
		} else {
			System.setProperty(SYNCHRONOUS_CODEGEN_PROPERTY, previousSynchronous);
		}
	}

	@Test
	void noThemeQueryDeclinesTheKernel() throws IOException {
		Map<String, Set<String>> capabilityDeclines = new TreeMap<>();
		Map<String, Set<String>> warmupDeclines = new TreeMap<>();
		Map<String, List<String>> declinesByPair = new LinkedHashMap<>();
		List<String> failures = new ArrayList<>();

		int pairCount = 0;
		for (Theme theme : Theme.values()) {
			List<String> queries = ThemeQueryCatalog.queriesFor(theme);
			for (int index = 0; index < queries.size(); index++) {
				pairCount++;
				String pair = theme + " q" + index;
				String query = queries.get(index);
				Set<String> reasons;
				long started = System.nanoTime();
				try {
					reasons = declineReasons(query);
				} catch (RuntimeException problem) {
					failures.add(pair + ": " + problem);
					System.out.println(String.format("%-28s FAILED  %s", pair, problem));
					continue;
				}
				System.out.println(String.format("%-28s %5d ms  %s", pair,
						(System.nanoTime() - started) / 1_000_000L,
						reasons.isEmpty() ? "engaged" : String.join(", ", reasons)));
				for (String reason : reasons) {
					String bare = reason.substring(reason.indexOf(':') + 1);
					Map<String, Set<String>> target = NON_CAPABILITY_REASONS.contains(bare) ? warmupDeclines
							: capabilityDeclines;
					target.computeIfAbsent(reason, key -> new LinkedHashSet<>()).add(pair);
					if (target == capabilityDeclines) {
						declinesByPair.computeIfAbsent(pair, key -> new ArrayList<>()).add(reason);
					}
				}
			}
		}

		String census = renderCensus(pairCount, capabilityDeclines, warmupDeclines, declinesByPair, failures);
		System.out.println(census);
		Files.writeString(censusFile(), census);

		assertThat(failures).as("theme queries that failed to execute").isEmpty();
		assertThat(declinesByPair)
				.as("theme query/kernel pairs still declining (census written to %s):%n%s", censusFile(), census)
				.isEmpty();
	}

	@Test
	void medicalOptionalNameAndNotExistsEngagesKernel() {
		Set<String> capabilityReasons = new LinkedHashSet<>(declineReasons(
				ThemeQueryCatalog.queryFor(Theme.MEDICAL_RECORDS, 10)));
		capabilityReasons.removeIf(reason -> NON_CAPABILITY_REASONS
				.contains(reason.substring(reason.indexOf(':') + 1)));
		assertThat(capabilityReasons)
				.as("MEDICAL_RECORDS q10 must lower its optional-name condition and nested NOT EXISTS")
				.isEmpty();
	}

	@Test
	void pharmaUncorrelatedWitnessStaysOnSemanticNativeAggregateTier() {
		Set<String> capabilityReasons = new LinkedHashSet<>(declineReasons(
				ThemeQueryCatalog.queryFor(Theme.PHARMA, 10)));
		capabilityReasons.removeIf(reason -> NON_CAPABILITY_REASONS
				.contains(reason.substring(reason.indexOf(':') + 1)));
		assertThat(capabilityReasons)
				.as("PHARMA q10 must keep an uncorrelated EXISTS witness on the native aggregate tier")
				.isEmpty();
	}

	@Test
	void pharmaQ11RetainsTheRequiredSemanticNestedLoopFallback() {
		for (int index = 0; index < 11; index++) {
			declineReasons(ThemeQueryCatalog.queryFor(Theme.PHARMA, index));
		}
		assertThatCode(() -> executionPaths(ThemeQueryCatalog.queryFor(Theme.PHARMA, 11)))
				.as("every speculative PHARMA q11 strategy may decline without removing the semantic native fallback")
				.doesNotThrowAnyException();
	}

	@Test
	void highlyConnectedDenormalizedViewCancelsBlockingKernelWithoutHeapExhaustion() {
		Set<String> capabilityReasons = new LinkedHashSet<>(declineReasons(
				ThemeQueryCatalog.queryFor(Theme.HIGHLY_CONNECTED, 11)));
		capabilityReasons.removeIf(reason -> NON_CAPABILITY_REASONS
				.contains(reason.substring(reason.indexOf(':') + 1)));
		assertThat(capabilityReasons)
				.as("HIGHLY_CONNECTED q11 must remain native while its blocking DISTINCT observes the query timeout")
				.isEmpty();
	}

	@Test
	void declineParserReadsOnlyTheNamedMetricAcrossThePlanTree() {
		GenericPlanNode root = new GenericPlanNode("root");
		root.setStringMetricActual("nativeAdaptiveCostDecision",
				"irKernel:0:kind=PROBE_COMPLETED;source=STRATEGY_FAMILY");
		GenericPlanNode child = new GenericPlanNode("child");
		child.setStringMetricActual("nativeStrategyDeclines",
				"irKernel:child:EmptyPlan | irAggregate:probe-trial-lost");
		root.setPlans(List.of(child));

		Set<String> reasons = new LinkedHashSet<>();
		collectDeclineReasons(root, reasons);

		assertThat(reasons).containsExactly("irKernel:child:EmptyPlan", "irAggregate:probe-trial-lost");
	}

	/**
	 * Dispatch reachability census: every strategy the engine still ships must win at least one production-shaped
	 * engagement case.
	 * <p>
	 * This is the anti-tautology gate for cost-based dispatch. The characteristic failure mode of ranking strategies —
	 * whether by a specialization order or by a cost model — is not that the wrong one wins, but that one of them stops
	 * winning anything at all and quietly becomes dead code that nobody notices until the day it was needed. Both
	 * guards added for the 2026-07-26 regressions (subordinating the IR kernels to prefix runs and worst-case-optimal
	 * joins, and refusing single-scan shapes with {@code no-fusion-opportunity}) carry exactly that risk: a guard that
	 * fires too broadly turns a subordinate strategy into an unreachable one.
	 * <p>
	 * The census is written beside the decline census for humans; the assertion is only that each listed strategy is
	 * reachable, which does not depend on which particular query it wins and so does not drift with the corpus.
	 */
	@Test
	void everyShippedStrategyWinsTheEngagementCensus() throws IOException {
		Map<String, Set<String>> winners = new TreeMap<>();
		for (Theme theme : Theme.values()) {
			List<String> queries = ThemeQueryCatalog.queriesFor(theme);
			for (int index = 0; index < queries.size(); index++) {
				String pair = theme + " q" + index;
				for (String path : executionPaths(queries.get(index))) {
					// Parameterized labels such as `factorizedRows(flatPrefix=1, ...)` collapse to their base tag.
					int paren = path.indexOf('(');
					winners.computeIfAbsent(paren > 0 ? path.substring(0, paren) : path,
							key -> new LinkedHashSet<>()).add(pair);
				}
			}
		}
		for (String path : executionPaths(ROW_JOIN_WITNESS_QUERY)) {
			int paren = path.indexOf('(');
			winners.computeIfAbsent(paren > 0 ? path.substring(0, paren) : path,
					key -> new LinkedHashSet<>()).add("chunk-pipeline row-join witness");
		}

		StringBuilder out = new StringBuilder("=== Dispatch reachability census ===\n");
		winners.forEach((tag, pairs) -> out
				.append(String.format("%4d  %-32s %s%n", pairs.size(), tag, String.join(", ", pairs))));
		System.out.println(out);
		Files.writeString(Paths.get("target", "dispatch-reachability-census.txt"), out.toString());

		// Deliberately a small, hand-picked set: the strategies whose reachability this session's dispatch changes
		// could plausibly have destroyed. Asserting over the whole vocabulary would fail on tags the scaled-down
		// census corpus simply never exercises, which would be a fixture complaint rather than a dispatch defect.
		assertThat(winners.keySet())
				.as("a strategy that never wins is dead code; census written to target/dispatch-reachability-census.txt:%n%s",
						out)
				.contains("chunkPipeline", "irKernel");
	}

	@Test
	void chunkPipelineWinsTheTwoPatternRowJoinWitness() {
		assertThat(executionPaths(ROW_JOIN_WITNESS_QUERY))
				.anyMatch(path -> path.startsWith("chunkPipeline("));
	}

	/** Distinct {@code nativeExecutionPath} tags a query records, across the whole explain tree. */
	private static Set<String> executionPaths(String query) {
		Set<String> paths = new LinkedHashSet<>();
		// Synchronous code generation removes the compiler warmup window, but it does not remove the adaptive
		// dispatch model's observation window. Keep the production calibration repetitions for this reachability gate;
		// otherwise the census describes only cold-start winners and can falsely declare a shipped strategy dead.
		for (int run = 0; run < WARMUP_RUNS; run++) {
			paths.clear();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				org.eclipse.rdf4j.query.TupleQuery prepared = connection.prepareTupleQuery(query);
				prepared.setMaxExecutionTime(QUERY_TIMEOUT_SECONDS);
				Matcher matcher = EXECUTION_PATH
						.matcher(prepared.explain(Explanation.Level.Telemetry).toString());
				while (matcher.find()) {
					for (String tag : matcher.group(1).split("\\|")) {
						String trimmed = tag.trim();
						if (!trimmed.isEmpty()) {
							paths.add(trimmed);
						}
					}
				}
			}
		}
		return paths;
	}

	/**
	 * Runs a query at telemetry level and returns the distinct kernel decline reasons it recorded.
	 * <p>
	 * A run is repeated only while the reasons are <em>all</em> warmup reasons, which is the only condition repeating
	 * can clear; a structural decline is returned on the first run rather than paid for {@link #WARMUP_RUNS} times.
	 * Each run is capped by {@link #QUERY_TIMEOUT_SECONDS} because {@code explain} otherwise inherits a sixty-second
	 * default per query, and a census that declines is by construction a census of queries running their slow path.
	 */
	private static Set<String> declineReasons(String query) {
		Set<String> reasons = new LinkedHashSet<>();
		for (int run = 0; run < warmupRuns(); run++) {
			reasons.clear();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				org.eclipse.rdf4j.query.TupleQuery prepared = connection.prepareTupleQuery(query);
				prepared.setMaxExecutionTime(QUERY_TIMEOUT_SECONDS);
				collectDeclineReasons(prepared.explain(Explanation.Level.Telemetry).toGenericPlanNode(), reasons);
			}
			boolean onlyWarmup = !reasons.isEmpty() && reasons.stream()
					.allMatch(reason -> RETRYABLE_REASONS.contains(reason.substring(reason.indexOf(':') + 1)));
			if (!onlyWarmup) {
				return reasons;
			}
		}
		return reasons;
	}

	private static void collectDeclineReasons(GenericPlanNode node, Set<String> reasons) {
		if (node == null) {
			return;
		}
		String declines = node.getStringMetricActual("nativeStrategyDeclines");
		if (declines != null) {
			Matcher matcher = KERNEL_DECLINE.matcher(declines);
			while (matcher.find()) {
				reasons.add(matcher.group(1) + ":" + matcher.group(2));
			}
		}
		if (node.getPlans() != null) {
			for (GenericPlanNode child : node.getPlans()) {
				collectDeclineReasons(child, reasons);
			}
		}
	}

	private static int warmupRuns() {
		// Synchronous validation has no compile-pending window to warm through; repeating every telemetry query would
		// only execute the same already-compiled shape six times and make the strict full-suite profile needlessly
		// slow.
		return Boolean.getBoolean(SYNCHRONOUS_CODEGEN_PROPERTY) ? 1 : WARMUP_RUNS;
	}

	private static String renderCensus(int pairCount, Map<String, Set<String>> capabilityDeclines,
			Map<String, Set<String>> warmupDeclines, Map<String, List<String>> declinesByPair,
			List<String> failures) {
		StringBuilder out = new StringBuilder();
		out.append("=== Kernel decline census ===\n");
		out.append("themes=")
				.append(Theme.values().length)
				.append(" pairs=")
				.append(pairCount)
				.append(" declining pairs=")
				.append(declinesByPair.size())
				.append('\n');
		out.append("\n-- capability declines by reason (pair count, then pairs) --\n");
		capabilityDeclines.entrySet()
				.stream()
				.sorted((a, b) -> Integer.compare(b.getValue().size(), a.getValue().size()))
				.forEach(entry -> out.append(String.format("%4d  %-52s %s%n", entry.getValue().size(), entry.getKey(),
						String.join(", ", entry.getValue()))));
		if (capabilityDeclines.isEmpty()) {
			out.append("      (none)\n");
		}
		out.append("\n-- warmup-only declines (not capability gaps) --\n");
		warmupDeclines.forEach((reason, pairs) -> out
				.append(String.format("%4d  %-52s %s%n", pairs.size(), reason, String.join(", ", pairs))));
		if (warmupDeclines.isEmpty()) {
			out.append("      (none)\n");
		}
		if (!failures.isEmpty()) {
			out.append("\n-- queries that failed to execute --\n");
			failures.forEach(failure -> out.append("      ").append(failure).append('\n'));
		}
		return out.toString();
	}

	private static Path censusFile() {
		Path target = Paths.get("target");
		return target.toFile().isDirectory() ? target.resolve("kernel-decline-census.txt")
				: Paths.get("kernel-decline-census.txt");
	}
}
