/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.Projection;
import org.eclipse.rdf4j.query.algebra.ProjectionElem;
import org.eclipse.rdf4j.query.algebra.ProjectionElemList;
import org.eclipse.rdf4j.query.algebra.QueryModelVisitor;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.UnaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Fail-safe planning in the LMDB optimizer: any planner {@link RuntimeException} (not only
 * {@link IllegalStateException}) degrades to the already-correct pipeline-normalized tree.
 */
class LmdbCascadesPlanningFailSafeTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void unsupportedOperatorFallsBackToThePipelineTree(@TempDir File dataDir) {
		LmdbStore store = new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc"));
		store.init();
		try {
			TupleExpr query = new Projection(new OpaqueTuple(new Join(sp("a", "urn:p", "b"), sp("b", "urn:q", "c"))),
					new ProjectionElemList(new ProjectionElem("a")));
			LmdbCascadesOptimizer optimizer = new LmdbCascadesOptimizer(
					store.getBackingStore().getEvaluationStatistics(), false);
			long fallbacksBefore = LmdbCascadesOptimizer.cascadesFallbackCount();

			LmdbCascadesOptimizer.PlanningOutcome outcome = optimizer.optimizeWithResult(query, null,
					EmptyBindingSet.getInstance());

			assertEquals(fallbacksBefore + 1, LmdbCascadesOptimizer.cascadesFallbackCount(),
					"the fallback must be counted so benchmarks can assert zero fallbacks");
			assertNull(outcome.cascadesPlan(), "an unsupported operator cannot produce a packed plan");
			assertSame(query, outcome.installedPlan(), "the pipeline-normalized tree is the executable fallback");
			assertEquals("true", query.getStringMetricPlanned("optimizer.cascadesFallback"));
			assertTrue(query.getStringMetricPlanned("optimizer.cascadesFallbackReason")
					.contains("UnsupportedCascadesOperatorException"),
					query.getStringMetricPlanned("optimizer.cascadesFallbackReason"));
		} finally {
			store.shutDown();
		}
	}

	// Cancellation is not a planner failure: a planning failure observed while the query thread is interrupted must
	// abort the query instead of executing the fallback plan, and must not be counted as a fallback.
	@Test
	void planningFailureWhileInterruptedAbortsInsteadOfFallingBack(@TempDir File dataDir) {
		LmdbStore store = new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc"));
		store.init();
		try {
			TupleExpr query = new Projection(new OpaqueTuple(new Join(sp("a", "urn:p", "b"), sp("b", "urn:q", "c"))),
					new ProjectionElemList(new ProjectionElem("a")));
			LmdbCascadesOptimizer optimizer = new LmdbCascadesOptimizer(
					store.getBackingStore().getEvaluationStatistics(), false);
			long fallbacksBefore = LmdbCascadesOptimizer.cascadesFallbackCount();

			Thread.currentThread().interrupt();
			try {
				assertThrows(RuntimeException.class,
						() -> optimizer.optimizeWithResult(query, null, EmptyBindingSet.getInstance()),
						"an interrupted query must not degrade to the fallback plan");
			} finally {
				Thread.interrupted();
			}

			assertEquals(fallbacksBefore, LmdbCascadesOptimizer.cascadesFallbackCount(),
					"a cancellation must not be counted as a planner fallback");
			assertNull(query.getStringMetricPlanned("optimizer.cascadesFallback"));
		} finally {
			store.shutDown();
		}
	}

	private static StatementPattern sp(String subject, String predicate, String object) {
		return new StatementPattern(Var.of(subject), Var.of("_const_" + predicate.substring(4), VF.createIRI(
				predicate), false, true), Var.of(object));
	}

	private static final class OpaqueTuple extends UnaryTupleOperator {

		private static final long serialVersionUID = 1L;

		private OpaqueTuple(TupleExpr argument) {
			super(argument);
		}

		@Override
		public <X extends Exception> void visit(QueryModelVisitor<X> visitor) throws X {
			visitor.meetOther(this);
		}
	}
}
