/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryResults;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.evaluation.JoinDispatchTestAccess;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Milestone 3 parity fix (three-tier parity plan): the row-side factorized {@code TailBranch} must consult
 * {@code adjacencyCacheBacked()} like its aggregate twin and skip its per-key value memo when the probe is served from
 * the shared adjacency cache — the memo would only duplicate runs the cache already holds in process memory.
 */
public class LmdbNativeFactorizedAdjacencyMemoTest {

	private static final String EX = "http://example.com/";
	private static final String NATIVE_FLAG = "rdf4j.lmdb.nativeQueryEngine.enabled";

	@TempDir
	File dataDir;

	private SailRepository repository;
	private LmdbStore sail;

	@BeforeEach
	public void setUp() throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc,ospc")
				.setDirectAdjacencyMode(DirectAdjacencyMode.PREFER)
				.setDirectAdjacencyMaxBytes(1L << 30);
		sail = new LmdbStore(dataDir, config);
		repository = new SailRepository(sail);
		repository.init();
		try (SailRepositoryConnection conn = repository.getConnection()) {
			ValueFactory vf = conn.getValueFactory();
			IRI p1 = vf.createIRI(EX, "p1");
			IRI p2 = vf.createIRI(EX, "p2");
			// 64 sources fan into 8 hubs, so the middle depth re-probes each hub key repeatedly; every hub
			// enumerates several leaves so the branch runs in ENUM role with a value payload worth memoizing
			for (int i = 0; i < 64; i++) {
				conn.add(vf.createIRI(EX, "s" + i), p1, vf.createIRI(EX, "hub" + i % 8));
			}
			for (int j = 0; j < 8; j++) {
				IRI hub = vf.createIRI(EX, "hub" + j);
				for (int k = 0; k < 3; k++) {
					conn.add(hub, p2, vf.createIRI(EX, "leaf" + j + "x" + k));
				}
			}
		}
		LmdbSailStore backing = sail.getBackingStore();
		LmdbDirectAdjacencyStore direct = backing.directAdjacencyStore();
		assertThat(direct).isNotNull();
		assertThat(direct.buildNowForTest()).isTrue();
	}

	@AfterEach
	public void tearDown() {
		repository.shutDown();
		System.clearProperty(NATIVE_FLAG);
		System.clearProperty("rdf4j.lmdb.chunkPipeline.enabled");
		System.clearProperty("rdf4j.lmdb.parallel.enabled");
	}

	@Test
	void tailBranchSkipsValueMemoWhenProbeIsCacheBacked() {
		System.setProperty(NATIVE_FLAG, "true");
		// steer dispatch to the factorized rows path: the chunk pipeline and parallel pipelines sit above it
		System.setProperty("rdf4j.lmdb.chunkPipeline.enabled", "false");
		System.setProperty("rdf4j.lmdb.parallel.enabled", "false");
		long engagedBefore = JoinDispatchTestAccess.factorizedEngaged();
		long skipsBefore = JoinDispatchTestAccess.factorizedCacheBackedMemoSkips();
		List<String> rows;
		try (SailRepositoryConnection conn = repository.getConnection()) {
			rows = QueryResults
					.asList(conn.prepareTupleQuery("PREFIX ex: <" + EX + ">\nSELECT ?s ?y WHERE {\n"
							+ "  ?s ex:p1 ?a .\n"
							+ "  ?a ex:p2 ?y .\n"
							+ "}").evaluate())
					.stream()
					.map(LmdbNativeFactorizedAdjacencyMemoTest::canonical)
					.sorted()
					.collect(Collectors.toList());
		}
		assertThat(rows).hasSize(64 * 3);
		assertThat(JoinDispatchTestAccess.factorizedEngaged())
				.as("the factorized rows path must engage for this shape")
				.isGreaterThan(engagedBefore);
		assertThat(JoinDispatchTestAccess.factorizedCacheBackedMemoSkips())
				.as("a cache-backed tail branch must skip its per-key value memo")
				.isGreaterThan(skipsBefore);
	}

	private static String canonical(BindingSet bindings) {
		return bindings.getBindingNames()
				.stream()
				.sorted()
				.filter(name -> bindings.getValue(name) != null)
				.map(name -> name + "=" + bindings.getValue(name))
				.collect(Collectors.joining(";", "[", "]"));
	}
}
