/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayDeque;
import java.util.List;
import java.util.Set;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.query.impl.MapBindingSet;
import org.junit.jupiter.api.Test;

class LmdbDeferredFilterPlacerSoundnessTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void undefDoesNotCloseBindingCoverBeforeLaterValues() {
		BindingSetAssignment partlyBound = new BindingSetAssignment();
		partlyBound.setBindingNames(Set.of("x", "y"));
		partlyBound.setBindingSets(List.of(row("x", VF.createLiteral(1))));
		BindingSetAssignment laterY = new BindingSetAssignment();
		laterY.setBindingNames(Set.of("y"));
		laterY.setBindingSets(List.of(row("y", VF.createLiteral(1))));

		Compare condition = new Compare(new Var("x"), new Var("y"), Compare.CompareOp.EQ);
		DeferredFilter filter = new DeferredFilter(condition, Set.of("x", "y"),
				JoinOrderPlanner.FILTER_COST_CHEAP, 0, null, Set.of(),
				new EvaluationStatistics.FilterPassEstimate(-1.0d,
						EvaluationStatistics.FilterPassEstimate.Source.UNKNOWN));
		LmdbDeferredFilterPlacer placer = new LmdbDeferredFilterPlacer((tupleExpr, bound) -> tupleExpr,
				Join::new, (root, filters, scope) -> new Filter(root,
						LmdbJoinPlanSupport.combinedCondition(filters.stream()
								.map(deferredFilter -> deferredFilter.condition)
								.toList())));

		TupleExpr placed = placer.buildSegmentRoot(new ArrayDeque<>(List.of(partlyBound, laterY)), List.of(filter),
				Set.of());

		StrictEvaluationStrategy strategy = new StrictEvaluationStrategy(new EmptyTripleSource(), null);
		try (CloseableIteration<BindingSet> results = strategy.precompile(placed)
				.evaluate(EmptyBindingSet.getInstance())) {
			assertThat(results.stream().toList()).singleElement().satisfies(result -> {
				assertThat(result.getValue("x")).isEqualTo(VF.createLiteral(1));
				assertThat(result.getValue("y")).isEqualTo(VF.createLiteral(1));
			});
		}
	}

	@Test
	void fullyBoundValuesStillCloseAndMaterializeTheEarliestFilterWindow() {
		BindingSetAssignment fullyBound = new BindingSetAssignment();
		fullyBound.setBindingNames(Set.of("x", "y"));
		fullyBound.setBindingSets(List.of(
				row("x", VF.createLiteral(1), "y", VF.createLiteral(1)),
				row("x", VF.createLiteral(1), "y", VF.createLiteral(2))));
		BindingSetAssignment unrelated = new BindingSetAssignment();
		unrelated.setBindingNames(Set.of("z"));
		unrelated.setBindingSets(List.of(row("z", VF.createLiteral(3))));

		Compare condition = new Compare(new Var("x"), new Var("y"), Compare.CompareOp.EQ);
		DeferredFilter filter = new DeferredFilter(condition, Set.of("x", "y"),
				JoinOrderPlanner.FILTER_COST_CHEAP, 0, null, Set.of(),
				new EvaluationStatistics.FilterPassEstimate(-1.0d,
						EvaluationStatistics.FilterPassEstimate.Source.UNKNOWN));
		LmdbDeferredFilterPlacer placer = new LmdbDeferredFilterPlacer((tupleExpr, bound) -> tupleExpr,
				Join::new, (root, filters, scope) -> new Filter(root,
						LmdbJoinPlanSupport.combinedCondition(filters.stream()
								.map(deferredFilter -> deferredFilter.condition)
								.toList())));

		TupleExpr placed = placer.buildSegmentRoot(new ArrayDeque<>(List.of(fullyBound, unrelated)), List.of(filter),
				Set.of());

		assertThat(placed).isInstanceOfSatisfying(Join.class, join -> {
			assertThat(join.getLeftArg()).isInstanceOfSatisfying(BindingSetAssignment.class,
					materialized -> assertThat(materialized.getBindingSets()).singleElement().satisfies(result -> {
						assertThat(result.getValue("x")).isEqualTo(VF.createLiteral(1));
						assertThat(result.getValue("y")).isEqualTo(VF.createLiteral(1));
					}));
			assertThat(join.getRightArg()).isSameAs(unrelated);
		});
	}

	private static BindingSet row(String name, Value value) {
		MapBindingSet row = new MapBindingSet(1);
		row.addBinding(name, value);
		return row;
	}

	private static BindingSet row(String firstName, Value firstValue, String secondName, Value secondValue) {
		MapBindingSet row = new MapBindingSet(2);
		row.addBinding(firstName, firstValue);
		row.addBinding(secondName, secondValue);
		return row;
	}

	private static final class EmptyTripleSource implements TripleSource {

		@Override
		public CloseableIteration<? extends Statement> getStatements(Resource subject, IRI predicate, Value object,
				Resource... contexts) throws QueryEvaluationException {
			return EMPTY_ITERATION;
		}

		@Override
		public ValueFactory getValueFactory() {
			return VF;
		}
	}
}
