/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.VariableScopeChange;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.impl.MapBindingSet;
import org.junit.jupiter.api.Test;

class LmdbSketchJoinOptimizerTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void reordersJoinSegmentsUsingJoinOrderPlanner() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern third = statementPattern("s3", "p3", "o3");
		QueryRoot root = new QueryRoot(new Join(first, new Join(second, third)));
		PlanningStatistics statistics = PlanningStatistics.withPlan(List.of(third, first, second));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(third, first, second), joinArgs(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void leavesJoinSegmentOrderUnchangedWhenPlannerRejects() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern third = statementPattern("s3", "p3", "o3");
		QueryRoot root = new QueryRoot(new Join(first, new Join(second, third)));
		PlanningStatistics statistics = PlanningStatistics.rejected();

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(first, second, third), joinArgs(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void movesLeftJoinLocalFilterIntoPlannedLeftSegment() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern optional = statementPattern("s1", "p3", "opt");
		Filter filter = new Filter(new LeftJoin(new Join(first, second), optional),
				new Compare(new Var("o1"), new Var("o2"), Compare.CompareOp.NE));
		QueryRoot root = new QueryRoot(filter);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		LeftJoin leftJoin = assertInstanceOf(LeftJoin.class, root.getArg());
		Filter movedFilter = assertInstanceOf(Filter.class, leftJoin.getLeftArg());
		assertTrue(containsFilter(leftJoin.getLeftArg()));
		assertEquals(List.of(first, second), joinArgs(movedFilter.getArg()));
	}

	@Test
	void duplicatesValuesAndFilterIntoUnionBranches() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		StatementPattern conditionType = statementPattern("entity", "type", "condition");
		StatementPattern conditionCode = statementPattern("entity", "code", "code");
		StatementPattern medicationType = statementPattern("entity", "type", "medication");
		StatementPattern medicationCode = statementPattern("entity", "code", "code");
		Union union = new Union(new Join(conditionType, conditionCode), new Join(medicationType, medicationCode));
		Filter filter = new Filter(new Join(values, union),
				new Or(new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ),
						new Compare(new Var("code"), new ValueConstant(VF.createLiteral("DX-202")),
								Compare.CompareOp.EQ)));
		QueryRoot root = new QueryRoot(filter);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union distributed = assertInstanceOf(Union.class, root.getArg());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void duplicatesValuesAndFilterAcrossParserScopedUnion() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		Union union = new Union(new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code")),
				new Join(statementPattern("entity", "type", "medication"),
						statementPattern("entity", "code", "code")));
		union.setVariableScopeChange(true);
		QueryRoot root = new QueryRoot(new Filter(new Join(values, union),
				new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union distributed = assertInstanceOf(Union.class, root.getArg());
		assertTrue(distributed.isVariableScopeChange());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void duplicatesValuesAndFilterBeforeOptionalAcrossParserScopedUnion() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		Join conditionBranch = new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code"));
		Join medicationBranch = new Join(statementPattern("entity", "type", "medication"),
				statementPattern("entity", "code", "code"));
		conditionBranch.setVariableScopeChange(true);
		medicationBranch.setVariableScopeChange(true);
		Union union = new Union(conditionBranch, medicationBranch);
		union.setVariableScopeChange(true);
		LeftJoin optional = new LeftJoin(new Join(values, union), statementPattern("entity", "code", "alt"));
		QueryRoot root = new QueryRoot(new Filter(optional,
				new Or(new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ),
						new Compare(new Var("code"), new ValueConstant(VF.createLiteral("DX-202")),
								Compare.CompareOp.EQ))));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		LeftJoin optimizedOptional = assertInstanceOf(LeftJoin.class, root.getArg());
		Union distributed = assertInstanceOf(Union.class, optimizedOptional.getLeftArg());
		assertTrue(distributed.isVariableScopeChange());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void placesDuplicatedValuesAfterScopedUnionBranchGraph() {
		Join conditionBranch = new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code"));
		Join medicationBranch = new Join(statementPattern("entity", "type", "medication"),
				statementPattern("entity", "code", "code"));
		conditionBranch.setVariableScopeChange(true);
		medicationBranch.setVariableScopeChange(true);
		Union union = new Union(
				new Filter(new Join(values("target", "DX-200", "DX-201"), conditionBranch),
						new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)),
				new Filter(new Join(values("target", "DX-200", "DX-201"), medicationBranch),
						new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)));
		QueryRoot root = new QueryRoot(union);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union optimized = assertInstanceOf(Union.class, root.getArg());
		assertScopedBranchBeforeValues(optimized.getLeftArg());
		assertScopedBranchBeforeValues(optimized.getRightArg());
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName));
	}

	private static BindingSetAssignment values(String bindingName, String... values) {
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.of(bindingName));
		List<BindingSet> bindingSets = new ArrayList<>(values.length);
		for (String value : values) {
			MapBindingSet bindingSet = new MapBindingSet(1);
			bindingSet.addBinding(bindingName, VF.createLiteral(value));
			bindingSets.add(bindingSet);
		}
		assignment.setBindingSets(bindingSets);
		return assignment;
	}

	private static List<TupleExpr> joinArgs(TupleExpr tupleExpr) {
		List<TupleExpr> args = new ArrayList<>();
		collectJoinArgs(tupleExpr, args);
		return args;
	}

	private static void collectJoinArgs(TupleExpr tupleExpr, List<TupleExpr> args) {
		if (tupleExpr instanceof Join) {
			Join join = (Join) tupleExpr;
			collectJoinArgs(join.getLeftArg(), args);
			collectJoinArgs(join.getRightArg(), args);
			return;
		}
		args.add(tupleExpr);
	}

	private static boolean containsFilter(TupleExpr tupleExpr) {
		if (tupleExpr instanceof Filter) {
			return true;
		}
		if (tupleExpr instanceof Join) {
			Join join = (Join) tupleExpr;
			return containsFilter(join.getLeftArg()) || containsFilter(join.getRightArg());
		}
		return false;
	}

	private static boolean containsBindingSetAssignment(TupleExpr tupleExpr, String bindingName) {
		if (tupleExpr instanceof BindingSetAssignment
				&& tupleExpr.getBindingNames().contains(bindingName)) {
			return true;
		}
		if (tupleExpr instanceof Filter) {
			return containsBindingSetAssignment(((Filter) tupleExpr).getArg(), bindingName);
		}
		if (tupleExpr instanceof Join) {
			Join join = (Join) tupleExpr;
			return containsBindingSetAssignment(join.getLeftArg(), bindingName)
					|| containsBindingSetAssignment(join.getRightArg(), bindingName);
		}
		return false;
	}

	private static void assertScopedBranchBeforeValues(TupleExpr tupleExpr) {
		Join join = assertInstanceOf(Join.class, tupleExpr);
		assertTrue(assertInstanceOf(VariableScopeChange.class, join.getLeftArg()).isVariableScopeChange());
		assertTrue(containsBindingSetAssignment(join.getRightArg(), "target"));
		assertTrue(containsFilter(join.getRightArg()));
	}

	private static final class PlanningStatistics extends EvaluationStatistics implements JoinOrderPlanner {

		private final List<TupleExpr> plan;
		private int planningAttempts;

		private PlanningStatistics(List<TupleExpr> plan) {
			this.plan = plan;
		}

		static PlanningStatistics withPlan(List<TupleExpr> plan) {
			return new PlanningStatistics(plan);
		}

		static PlanningStatistics rejected() {
			return new PlanningStatistics(null);
		}

		@Override
		public Optional<JoinOrderPlan> planJoinOrder(List<TupleExpr> args, Set<String> initiallyBoundVars,
				Algorithm algorithm) {
			planningAttempts++;
			if (plan == null) {
				return Optional.empty();
			}
			return Optional.of(new JoinOrderPlan(plan, 1.0d, 1.0d));
		}
	}
}
