/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.rdf4j.sail.lmdb.TxnManager.Txn;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.evaluation.NativeLmdbQuerySource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Gate A milestone A4 of the node-to-predicate projection ExecPlan
 * ({@code .agent/node-predicate-projection-execplan.md}), lifetime and transaction half.
 *
 * <p>
 * The differential parity suite compares answers at four points in the structure's life. What it cannot see is the four
 * things this class covers, because each of them is about <em>when</em> a structure is valid rather than about what it
 * says: a reference resolved against one published base and then used against another; native memory released while a
 * reader still holds it; two workers sharing cursor state they should not share; and a read taken inside a write
 * transaction that has uncommitted changes in flight.
 *
 * <p>
 * Native memory is freed by reference count, so the second of those is a process crash rather than an exception if it
 * regresses. That is the reason it is worth a test of its own even though nothing here looks like a query.
 */
class LmdbNodePredicateLifetimeTest {

	private TripleStore tripleStore;
	private LmdbDirectAdjacencyStore store;

	private static long uri(long payload) {
		return ValueIds.createId(ValueIds.T_URI, payload);
	}

	private static final long S1 = uri(1);
	private static final long S2 = uri(2);
	private static final long P_A = uri(100);
	private static final long P_B = uri(101);
	/** Introduced only after the base is built, so folding it in genuinely rewrites the projection. */
	private static final long P_LATE = uri(102);
	private static final long O1 = uri(200);
	private static final long O2 = uri(201);

	@BeforeEach
	void setUp(@TempDir File dataDir) throws Exception {
		tripleStore = new TripleStore(dataDir, new LmdbStoreConfig("spoc,posc"), null);
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setDirectAdjacencyMode(DirectAdjacencyMode.PREFER)
				.setDirectAdjacencyMaxBytes(1L << 30);
		LmdbDirectAdjacencyOptions options = LmdbDirectAdjacencyOptions.resolve(config, 8L << 30,
				name -> LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_PROPERTY.equals(name) ? "true" : null, 4);
		System.setProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY, "true");
		store = new LmdbDirectAdjacencyStore(tripleStore, null, new AtomicBoolean(false), options);
		tripleStore.setDirectAdjacencyCommitHooks(store.commitListener(), store.newCommitDelta());

		commit(() -> {
			tripleStore.storeTriple(S1, P_A, O1, 0, true);
			tripleStore.storeTriple(S1, P_B, O2, 0, true);
			tripleStore.storeTriple(S2, P_A, O2, 0, true);
		});
		assertThat(store.buildNowForTest()).isTrue();
		assertThat(store.publishedStateForTest().base().nodePredicateIndexOrNull()).isNotNull();
	}

	@AfterEach
	void tearDown() throws Exception {
		System.clearProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY);
		if (store != null) {
			store.close();
		}
		if (tripleStore != null) {
			tripleStore.close();
		}
	}

	// ------------------------------------------------------------------

	/**
	 * A reference is valid only against the root it came from. A view pinned before a fold-down must keep answering
	 * from the base it pinned — not silently start reading the new one, and not resolve a stale reference against it,
	 * which is the shape of bug that reads freed or reused native memory.
	 */
	@Test
	void anOldViewKeepsAnsweringFromTheBaseItPinned() throws Exception {
		long pinnedRevision = tripleStore.getDataRevision();
		try (LmdbAdjacencyReadView pinned = store.acquire(pinnedRevision)) {
			List<long[]> before = rows(pinned, S1);
			assertThat(before).as("the pinned view must serve before anything changes").isNotNull();

			LmdbInMemoryAdjacencyIndex pinnedBase = pinned.state().base();
			commit(() -> tripleStore.storeTriple(S1, P_LATE, O1, 0, true));
			foldDown();
			assertThat(store.publishedStateForTest().base())
					.as("the fold-down must have published a different base, or this test proves nothing")
					.isNotSameAs(pinnedBase);

			// The pinned view still reads its own base: same rows, same order, no late predicate.
			assertThat(rows(pinned, S1))
					.as("a pinned view must not observe a change published after it was acquired")
					.usingElementComparator(ROW_ORDER)
					.containsExactlyElementsOf(before);
			assertThat(rows(pinned, S1).stream().map(row -> row[1]).toList()).doesNotContain(P_LATE);

			// A view acquired now reads the new base, and agrees with the disk trees.
			try (LmdbAdjacencyReadView fresh = store.acquire(tripleStore.getDataRevision())) {
				List<long[]> after = rows(fresh, S1);
				assertThat(after).as("the fresh view must serve from the new base").isNotNull();
				assertThat(after.stream().map(row -> row[1]).toList()).contains(P_LATE);
				assertThat(after).usingElementComparator(ROW_ORDER)
						.containsExactlyElementsOf(diskRows(S1));
			}

			// ...and the old view is still intact after the new one has come and gone.
			assertThat(rows(pinned, S1)).usingElementComparator(ROW_ORDER).containsExactlyElementsOf(before);
		}
	}

	/**
	 * A retired base is freed only when the last lease on it ends. The observable is the memory account: the charge for
	 * the retired structure stays on the books while any reader still holds it, and comes off only when the last one
	 * lets go. Releasing early would not raise here — it would hand a reader a pointer into freed native memory, which
	 * is a crash rather than a failed assertion, so the accounting is the only thing that can be asserted before the
	 * fact rather than after it.
	 */
	@Test
	void aRetiredBaseIsFreedOnlyAfterTheLastLeaseEnds() throws Exception {
		long revision = tripleStore.getDataRevision();
		LmdbAdjacencyReadView first = store.acquire(revision);
		LmdbAdjacencyReadView second = store.acquire(revision);
		boolean released = false;
		try {
			assertThat(first.state().base()).as("both leases must be on the same base").isSameAs(second.state().base());

			commit(() -> tripleStore.storeTriple(S1, P_LATE, O1, 0, true));
			foldDown();
			long whileBothHeld = store.memoryAccount().totalChargedBytes();
			assertThat(whileBothHeld).isPositive();

			second.close();
			assertThat(store.memoryAccount().totalChargedBytes())
					.as("releasing one of two leases must free nothing")
					.isEqualTo(whileBothHeld);

			// The remaining reader still sees its own base while it is alive.
			assertThat(rows(first, S1)).isNotNull();

			first.close();
			released = true;
			assertThat(store.memoryAccount().totalChargedBytes())
					.as("the retired base must be released once its last lease ends")
					.isLessThan(whileBothHeld);
		} finally {
			if (!released) {
				first.close();
				second.close();
			}
		}
	}

	/**
	 * Two workers running the same logical request each get their own view object, because the cursors inside are
	 * mutable. If they shared one, interleaved lookups would return each other's rows — so the two threads below
	 * deliberately probe different nodes in lockstep and check that neither sees the other's predicates.
	 */
	@Test
	void twoWorkersDoNotShareCursorState() throws Exception {
		ExecutorService pool = Executors.newFixedThreadPool(2);
		try (LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			CyclicBarrier lockstep = new CyclicBarrier(2);
			Future<List<Long>> one = pool.submit(worker(view, S1, lockstep));
			Future<List<Long>> two = pool.submit(worker(view, S2, lockstep));
			assertThat(one.get(60, TimeUnit.SECONDS)).containsExactly(P_A, P_B, P_A, P_B, P_A, P_B, P_A, P_B);
			assertThat(two.get(60, TimeUnit.SECONDS)).containsExactly(P_A, P_A, P_A, P_A);
		} finally {
			pool.shutdownNow();
		}
	}

	@Test
	void completedOverlaysRemainEligibleForExactNodePredicateViews() throws Exception {
		commit(() -> tripleStore.storeTriple(S1, P_LATE, O1, 0, true));
		commit(() -> tripleStore.removeTriplesByContext(S1, P_A, O1, 0, true, removed -> {
		}));
		commit(() -> tripleStore.storeTriple(S2, P_B, O1, 0, true));
		assertThat(store.publishedStateForTest().overlays()).as("the test requires completed overlays").isNotNull();

		try (LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			NativeLmdbQuerySource.NodePredicates predicates = store.bindNodePredicates(view, true, true, null);
			assertThat(predicates)
					.as("completed immutable overlays must not disable exact predicate routing")
					.isNotNull();
			assertThat(predicateRow(predicates, S1)).containsExactly(P_B, P_LATE);
			assertThat(predicateRow(predicates, S2)).containsExactly(P_A, P_B);
		}
	}

	private static List<Long> predicateRow(NativeLmdbQuerySource.NodePredicates predicates, long node) {
		long row = predicates.find(node);
		if (row == NativeLmdbQuerySource.NodePredicates.NOT_FOUND) {
			return List.of();
		}
		assertThat(row).isPositive();
		int size = Math.toIntExact(predicates.rowSize(row));
		long[] predicateIds = new long[size];
		long[] runs = new long[size];
		assertThat(predicates.copyRow(node, row, 0, size, predicateIds, 0, runs, 0)).isEqualTo(size);
		List<Long> result = new ArrayList<>(size);
		for (int i = 0; i < size; i++) {
			assertThat(runs[i]).isPositive();
			assertThat(predicates.size(runs[i])).isPositive();
			result.add(predicateIds[i]);
		}
		return result;
	}

	private Callable<List<Long>> worker(LmdbAdjacencyReadView view, long node, CyclicBarrier lockstep) {
		return () -> {
			// One view per worker: each parallel worker owns its probe, which is what makes confinement structural.
			NativeLmdbQuerySource.NodePredicates predicates = store.bindNodePredicates(view, true, true, null);
			assertThat(predicates).as("the worker view must bind").isNotNull();
			List<Long> seen = new ArrayList<>();
			long[] buffer = new long[8];
			long[] runs = new long[8];
			for (int round = 0; round < 4; round++) {
				lockstep.await(60, TimeUnit.SECONDS);
				long row = predicates.find(node);
				assertThat(row).isPositive();
				int copied = predicates.copyRow(node, row, 0, buffer.length, buffer, 0, runs, 0);
				lockstep.await(60, TimeUnit.SECONDS);
				for (int i = 0; i < copied; i++) {
					// Resolving the run in between is the interleaving that would corrupt a shared cursor.
					assertThat(predicates.size(runs[i])).isPositive();
					seen.add(buffer[i]);
				}
			}
			return seen;
		};
	}

	/**
	 * A read taken inside a write transaction that has uncommitted changes in flight must either honour those changes
	 * exactly — read-your-own-writes — or decline to the disk trees, which are the authority. Anything in between is a
	 * view of the store that never existed. The transaction is exercised through both of its endings, because a
	 * rollback restores a state the adjacency index was never told about.
	 */
	@Test
	void aReadInsideAWriteTransactionEitherMatchesItExactlyOrDeclines() throws Exception {
		assertInFlightReadIsHonest(true);
		assertInFlightReadIsHonest(false);
	}

	private void assertInFlightReadIsHonest(boolean commit) throws IOException {
		tripleStore.startTransaction();
		tripleStore.storeTriple(S1, P_LATE, O2, 0, true);
		tripleStore.removeTriplesByContext(S1, P_A, O1, 0, true, removed -> {
		});

		try (Txn txn = tripleStore.getTxnManager().createReadTxn();
				LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			RecordIterator served = store.tryOpen(view, txn, S1, -1, -1, -1, true);
			if (served != null) {
				List<long[]> adjacency = drain(served);
				assertThat(adjacency)
						.as("an in-flight read that serves must match the transaction's own view exactly")
						.usingElementComparator(ROW_ORDER)
						.containsExactlyElementsOf(diskRows(txn, S1));
			}
		}

		if (commit) {
			tripleStore.commit();
			store.applyCommitted(tripleStore.drainDirectAdjacencyCommitDelta());
			store.pauseApplierForTest(false);
			// Undo, so the two halves of this test start from the same fixture.
			commit(() -> {
				tripleStore.removeTriplesByContext(S1, P_LATE, O2, 0, true, removed -> {
				});
				tripleStore.storeTriple(S1, P_A, O1, 0, true);
			});
		} else {
			tripleStore.rollback();
		}

		try (Txn txn = tripleStore.getTxnManager().createReadTxn();
				LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			RecordIterator served = store.tryOpen(view, txn, S1, -1, -1, -1, true);
			if (served != null) {
				assertThat(drain(served))
						.as("after the transaction ends, a served answer must match the disk trees")
						.usingElementComparator(ROW_ORDER)
						.containsExactlyElementsOf(diskRows(txn, S1));
			}
		}
	}

	// ------------------------------------------------------------------

	private interface Body {
		void run() throws IOException;
	}

	private void commit(Body body) throws IOException {
		tripleStore.startTransaction();
		body.run();
		tripleStore.commit();
		store.applyCommitted(tripleStore.drainDirectAdjacencyCommitDelta());
		store.pauseApplierForTest(false);
	}

	/** Folds every live overlay generation into a new base, adding a second generation if one is needed to merge. */
	private void foldDown() throws IOException {
		if (store.publishedStateForTest().overlays() == null) {
			return;
		}
		if (store.publishedStateForTest().overlays().generationCount() < 2) {
			commit(() -> tripleStore.storeTriple(S2, P_B, O1, 0, true));
		}
		store.consolidateNowForTest();
		assertThat(store.publishedStateForTest().overlays()).isNull();
	}

	private List<long[]> rows(LmdbAdjacencyReadView view, long node) throws IOException {
		RecordIterator it = store.tryOpen(view, null, node, -1, -1, -1, true);
		return it == null ? null : drain(it);
	}

	private List<long[]> diskRows(long node) throws IOException {
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			return diskRows(txn, node);
		}
	}

	private List<long[]> diskRows(Txn txn, long node) throws IOException {
		try (RecordIterator it = tripleStore.getTriples(txn, node, -1, -1, -1, true)) {
			return drain(it);
		}
	}

	private static List<long[]> drain(RecordIterator it) throws IOException {
		List<long[]> rows = new ArrayList<>();
		try {
			long[] quad;
			while ((quad = it.next()) != null) {
				rows.add(new long[] { quad[TripleIndex.SUBJ_IDX], quad[TripleIndex.PRED_IDX],
						quad[TripleIndex.OBJ_IDX], Math.max(0, quad[TripleIndex.CONTEXT_IDX]) });
			}
		} finally {
			it.close();
		}
		rows.sort(ROW_ORDER);
		return rows;
	}

	private static final Comparator<long[]> ROW_ORDER = (a, b) -> {
		for (int i = 0; i < 4; i++) {
			int comparison = Long.compareUnsigned(a[i], b[i]);
			if (comparison != 0) {
				return comparison;
			}
		}
		return 0;
	};
}
