/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.file.Path;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.sail.NotifyingSailConnection;
import org.eclipse.rdf4j.sail.lmdb.config.FrontierEstimatorMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierLeafEstimate;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierLeafProbe;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierStatisticsStatus;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierStatisticsTier;
import org.eclipse.rdf4j.sail.lmdb.frontier.LmdbStatisticsService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Frontier Statistics V2 background scheduling: a required base rebuild must eventually run under steady small commits
 * (debounce with a deadline), and delta publication that can never fit its persistent envelope, or that can never be
 * applied to the current base layout, must escalate to a base rebuild instead of retrying forever.
 */
class LmdbFrontierRebuildSchedulingTest {

	private static final String PREFIX = "urn:frontier:schedule:";
	private static final long MIB = 1024L * 1024L;

	/**
	 * A transaction larger than the bounded delta batch requires a base rebuild. Every commit resets the one-second
	 * quiet period, so a modest steady write rate (one small commit every 250 ms) must not starve that rebuild: the
	 * base rebuild must start once the pending rebuild reaches its five-second deferral deadline even though the quiet
	 * period never elapses, and the 20,000-row predicate must become covered (and estimable) while the commits
	 * continue. How long the rebuild itself takes depends on machine load, so only its start is bounded tightly.
	 */
	@Test
	void steadySmallCommitsDoNotStarveARequiredBaseRebuild(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), config(32L * MIB));
		try {
			store.init();
			LmdbSailStore backing = store.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			long initialBaseEpoch = status(backing).baseEpoch();
			ValueFactory vf = store.getValueFactory();
			IRI big = vf.createIRI(PREFIX + "big");
			try (NotifyingSailConnection connection = store.getConnection()) {
				connection.begin();
				for (int i = 0; i < 20_000; i++) {
					connection.addStatement(vf.createIRI(PREFIX + "s" + i), big, vf.createIRI(PREFIX + "o" + i));
				}
				connection.commit();
			}
			long bigSequence = latestSequence(backing);
			IRI small = vf.createIRI(PREFIX + "small");
			long started = System.nanoTime();
			long deadline = started + 60_000_000_000L;
			int commits = 0;
			boolean caughtUp = false;
			long rebuildStartedAfterMillis = -1L;
			FrontierLeafEstimate lastEstimate = null;
			StringBuilder trace = new StringBuilder();
			while (System.nanoTime() < deadline) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					connection.addStatement(vf.createIRI(PREFIX + "t" + commits), small,
							vf.createLiteral(commits));
					connection.commit();
				}
				commits++;
				lastEstimate = predicateEstimate(backing, big);
				FrontierStatisticsStatus observed = status(backing);
				long elapsedMillis = (System.nanoTime() - started) / 1_000_000L;
				trace.append("\n  +")
						.append(elapsedMillis)
						.append("ms commit=")
						.append(commits)
						.append(" phase=")
						.append(observed.buildPhase())
						.append(" gen=")
						.append(observed.generationId())
						.append(" baseEpoch=")
						.append(observed.baseEpoch())
						.append(" covered=")
						.append(observed.coveredSequence())
						.append(" etaMillis=")
						.append(observed.buildEtaMillis())
						.append(" lastFailure=")
						.append(observed.lastFailure());
				boolean caught = observed.coveredSequence() >= bigSequence;
				if (rebuildStartedAfterMillis < 0L
						&& (caught || observed.baseEpoch() > initialBaseEpoch || baseRebuildPhase(observed))) {
					rebuildStartedAfterMillis = elapsedMillis;
				}
				if (caught) {
					caughtUp = true;
					break;
				}
				Thread.sleep(250L);
			}
			FrontierStatisticsStatus status = status(backing);
			String detail = "commits=" + commits + " covered=" + status.coveredSequence() + " < " + bigSequence
					+ " fallback=" + status.fallbackReason() + ", leaf estimate for the 20k-row predicate stayed "
					+ lastEstimate + trace;
			assertTrue(rebuildStartedAfterMillis >= 0L && rebuildStartedAfterMillis <= 8_000L,
					"the required base rebuild must start within its 5 s deferral deadline (plus one scheduler tick "
							+ "and slack) although a commit every 250 ms keeps resetting the quiet period; started "
							+ "after " + rebuildStartedAfterMillis + " ms; " + detail);
			assertTrue(caughtUp, "a 20k-statement transaction must be covered while commits continue at 4/s; "
					+ detail);
		} finally {
			store.shutDown();
		}
	}

	/**
	 * The deadline must not regress the debounce: a burst of small commits followed by silence is served by signed
	 * deltas on the existing base; it must never be answered with one base rebuild per commit.
	 */
	@Test
	void burstOfCommitsIsCoalescedIntoOneDeltaGeneration(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), config(32L * MIB));
		try {
			store.init();
			LmdbSailStore backing = store.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			FrontierStatisticsStatus base = status(backing);
			ValueFactory vf = store.getValueFactory();
			IRI predicate = vf.createIRI(PREFIX + "burst");
			for (int commit = 0; commit < 5; commit++) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					connection.addStatement(vf.createIRI(PREFIX + "b" + commit), predicate,
							vf.createLiteral(commit));
					connection.commit();
				}
				Thread.sleep(50L);
			}
			long latest = latestSequence(backing);
			assertTrue(awaitCovered(backing, latest, 15_000L));
			FrontierStatisticsStatus covered = status(backing);
			assertEquals(base.baseEpoch(), covered.baseEpoch(), "small commits must not force a base rebuild");
			assertTrue(covered.generationId() > base.generationId()
					&& covered.generationId() <= base.generationId() + 5L,
					"five small commits publish between one and five signed deltas, never more; generation went from "
							+ base.generationId() + " to " + covered.generationId());
			assertEquals("", covered.lastFailure());
		} finally {
			store.shutDown();
		}
	}

	/**
	 * At a 16 MiB synopsis budget the persistent delta envelope is 1 MiB. Insert-only 4,000-statement commits must
	 * never leave the generation stale: once the delta tier cannot absorb another signed delta the store must fold the
	 * deltas into a fresh base instead of retrying an impossible delta publication forever.
	 */
	@Test
	void exhaustedDeltaEnvelopeEscalatesToABaseRebuild(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), config(16L * MIB));
		try {
			store.init();
			LmdbSailStore backing = store.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			FrontierStatisticsStatus initial = status(backing);
			ValueFactory vf = store.getValueFactory();
			IRI predicate = vf.createIRI(PREFIX + "grow");
			long latest = -1L;
			boolean stalled = false;
			int batch = 0;
			StringBuilder trace = new StringBuilder();
			for (; batch < 8 && !stalled; batch++) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					for (int i = 0; i < 4_000; i++) {
						int id = batch * 4_000 + i;
						connection.addStatement(vf.createIRI(PREFIX + "s" + id), predicate,
								vf.createIRI(PREFIX + "o" + id));
					}
					connection.commit();
				}
				latest = latestSequence(backing);
				stalled = !awaitCovered(backing, latest, 15_000L);
				FrontierStatisticsStatus status = status(backing);
				trace.append("\n  batch=")
						.append(batch)
						.append(" latest=")
						.append(latest)
						.append(" covered=")
						.append(status.coveredSequence())
						.append(" gen=")
						.append(status.generationId())
						.append(" baseEpoch=")
						.append(status.baseEpoch())
						.append(" deltaBytes=")
						.append(deltaTierBytes(status))
						.append(" lastFailure=")
						.append(status.lastFailure());
			}
			boolean recovered = !stalled || awaitCovered(backing, latest, 20_000L);
			FrontierStatisticsStatus status = status(backing);
			assertTrue(recovered, "after writes stop, Frontier must catch up (base rebuild) instead of retrying a "
					+ "delta that can never fit; lastFailure=" + status.lastFailure() + trace);
			assertTrue(!stalled, "insert-only growth must never stall delta coverage for 15 s; lastFailure="
					+ status.lastFailure() + trace);
			assertTrue(status.baseEpoch() > initial.baseEpoch(),
					"32k inserted statements exceed the 1 MiB delta envelope, so a fresh base must have been "
							+ "published" + trace);
			assertTrue(deltaTierBytes(status) <= MIB, "the delta tier must respect its envelope after recovery"
					+ trace);
		} finally {
			store.shutDown();
		}
	}

	/**
	 * Adversarial coupling: a base rebuild triggered by delta-tier debt must not stop delta publication while small
	 * commits keep arriving. Coverage must keep advancing while the rebuild is pending (deferred by the quiet period),
	 * the base must be republished, and no failure may be recorded. Only the rebuild's own execution, which occupies
	 * the single-threaded scheduler for a load-dependent time, may leave commits uncovered for longer.
	 */
	@Test
	void deltaTierDebtRebuildsBaseWhileSmallCommitsContinue(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), config(16L * MIB));
		try {
			store.init();
			LmdbSailStore backing = store.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			FrontierStatisticsStatus initial = status(backing);
			ValueFactory vf = store.getValueFactory();
			IRI bulk = vf.createIRI(PREFIX + "bulk");
			IRI trickle = vf.createIRI(PREFIX + "trickle");
			for (int batch = 0; batch < 2; batch++) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					for (int i = 0; i < 4_000; i++) {
						int id = batch * 4_000 + i;
						connection.addStatement(vf.createIRI(PREFIX + "bs" + id), bulk,
								vf.createIRI(PREFIX + "bo" + id));
					}
					connection.commit();
				}
			}
			long started = System.nanoTime();
			long deadline = started + 40_000_000_000L;
			int commits = 0;
			long maximumUncoveredMillis = 0L;
			long uncoveredSinceNanos = -1L;
			boolean uncoveredWindowSpansBaseRebuild = false;
			boolean rebuilt = false;
			StringBuilder trace = new StringBuilder();
			while (System.nanoTime() < deadline) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					connection.addStatement(vf.createIRI(PREFIX + "tr" + commits), trickle,
							vf.createLiteral(commits));
					connection.commit();
				}
				commits++;
				FrontierStatisticsStatus status = status(backing);
				long latestNow = latestSequence(backing);
				trace.append("\n  +")
						.append((System.nanoTime() - started) / 1_000_000L)
						.append("ms commit=")
						.append(commits)
						.append(" phase=")
						.append(status.buildPhase())
						.append(" gen=")
						.append(status.generationId())
						.append(" baseEpoch=")
						.append(status.baseEpoch())
						.append(" covered=")
						.append(status.coveredSequence())
						.append(" latest=")
						.append(latestNow)
						.append(" deltaBytes=")
						.append(deltaTierBytes(status))
						.append(" lastFailure=")
						.append(status.lastFailure());
				if (status.coveredSequence() >= latestNow - 1L) {
					uncoveredSinceNanos = -1L;
					uncoveredWindowSpansBaseRebuild = false;
				} else {
					uncoveredWindowSpansBaseRebuild |= baseRebuildPhase(status);
					if (uncoveredSinceNanos < 0L) {
						uncoveredSinceNanos = System.nanoTime();
					} else if (!uncoveredWindowSpansBaseRebuild) {
						// While the rebuild is merely pending, signed deltas must keep publishing.
						maximumUncoveredMillis = Math.max(maximumUncoveredMillis,
								(System.nanoTime() - uncoveredSinceNanos) / 1_000_000L);
					}
				}
				if (status.baseEpoch() > initial.baseEpoch() && commits >= 12) {
					rebuilt = true;
					break;
				}
				Thread.sleep(250L);
			}
			long latest = latestSequence(backing);
			boolean caughtUp = awaitCovered(backing, latest, 15_000L);
			FrontierStatisticsStatus status = status(backing);
			assertTrue(rebuilt, "8,000 bulk rows exceed 75% of the 1 MiB delta envelope, so a base rebuild must be "
					+ "published within 40 s while commits continue; commits=" + commits + " baseEpoch="
					+ status.baseEpoch() + " initialBaseEpoch=" + initial.baseEpoch() + " lastFailure="
					+ status.lastFailure() + trace);
			assertTrue(caughtUp, "coverage must catch up with the trickle after the base rebuild; covered="
					+ status.coveredSequence() + " latest=" + latest + " lastFailure=" + status.lastFailure()
					+ trace);
			assertEquals("", status.lastFailure(), "a debt-triggered base rebuild must not surface a failure"
					+ trace);
			assertTrue(maximumUncoveredMillis < 10_000L,
					"delta publication must keep advancing while a base rebuild is pending (only the rebuild's own "
							+ "execution may leave commits uncovered); longest uncovered window without a running "
							+ "base rebuild was " + maximumUncoveredMillis + " ms" + trace);
		} finally {
			store.shutDown();
		}
	}

	/**
	 * At the default 512 MiB synopsis budget (32 MiB delta envelope), insert-only growth used to stop publishing after
	 * roughly 112,000 statements. Ten 16,000-statement commits must stay covered and must have folded the deltas into
	 * at least one fresh base well before the envelope is exhausted.
	 */
	@Test
	void defaultBudgetInsertOnlyGrowthKeepsFrontierCurrent(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), config(LmdbStoreConfig.FRONTIER_SYNOPSIS_BUDGET_BYTES));
		try {
			store.init();
			LmdbSailStore backing = store.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			FrontierStatisticsStatus initial = status(backing);
			ValueFactory vf = store.getValueFactory();
			IRI[] predicates = new IRI[8];
			for (int p = 0; p < predicates.length; p++) {
				predicates[p] = vf.createIRI(PREFIX + "d" + p);
			}
			long latest = -1L;
			boolean stalled = false;
			int batch = 0;
			StringBuilder trace = new StringBuilder();
			for (; batch < 10 && !stalled; batch++) {
				try (NotifyingSailConnection connection = store.getConnection()) {
					connection.begin();
					for (int i = 0; i < 16_000; i++) {
						int id = batch * 16_000 + i;
						connection.addStatement(vf.createIRI(PREFIX + "s" + id), predicates[id & 7],
								vf.createIRI(PREFIX + "o" + (id % 50_000)));
					}
					connection.commit();
				}
				latest = latestSequence(backing);
				stalled = !awaitCovered(backing, latest, 30_000L);
				FrontierStatisticsStatus status = status(backing);
				trace.append("\n  batch=")
						.append(batch)
						.append(" statements=")
						.append(latest)
						.append(" covered=")
						.append(status.coveredSequence())
						.append(" deltaBytes=")
						.append(deltaTierBytes(status))
						.append(" baseEpoch=")
						.append(status.baseEpoch())
						.append(" lastFailure=")
						.append(status.lastFailure());
			}
			FrontierStatisticsStatus status = status(backing);
			assertTrue(!stalled, "default-budget Frontier stalled permanently after " + latest
					+ " inserted statements: " + status.lastFailure() + trace);
			assertTrue(status.baseEpoch() > initial.baseEpoch(),
					"160,000 inserted statements must have folded the signed deltas into a fresh base before the "
							+ "32 MiB envelope is exhausted" + trace);
			assertEquals("", status.lastFailure(), "insert-only growth must never record a publication failure"
					+ trace);
		} finally {
			store.shutDown();
		}
	}

	/**
	 * Budget drift: the Omni cell width follows the configured budgets (16 MiB -> 16 cells, 32 MiB -> 32 cells; a
	 * smaller heap halves the width at larger budgets). Reopening a store whose base was built with different
	 * dimensions must publish a fresh base instead of failing every delta with a dimension mismatch forever.
	 */
	@Test
	void budgetDriftAcrossRestartRebuildsBaseInsteadOfRetryingForever(@TempDir Path dataDirectory)
			throws Exception {
		long firstBaseEpoch;
		LmdbStore narrow = new LmdbStore(dataDirectory.toFile(), config(16L * MIB));
		try {
			narrow.init();
			LmdbSailStore backing = narrow.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			ValueFactory vf = narrow.getValueFactory();
			IRI predicate = vf.createIRI(PREFIX + "drift");
			try (NotifyingSailConnection connection = narrow.getConnection()) {
				connection.begin();
				for (int i = 0; i < 500; i++) {
					connection.addStatement(vf.createIRI(PREFIX + "ds" + i), predicate, vf.createLiteral(i));
				}
				connection.commit();
			}
			assertTrue(awaitCovered(backing, latestSequence(backing), 15_000L));
			firstBaseEpoch = status(backing).baseEpoch();
		} finally {
			narrow.shutDown();
		}

		LmdbStore wide = new LmdbStore(dataDirectory.toFile(), config(32L * MIB));
		try {
			wide.init();
			LmdbSailStore backing = wide.getBackingStore();
			assertTrue(awaitReady(backing, 20_000L));
			ValueFactory vf = wide.getValueFactory();
			try (NotifyingSailConnection connection = wide.getConnection()) {
				connection.begin();
				connection.addStatement(vf.createIRI(PREFIX + "after-restart"), vf.createIRI(PREFIX + "drift"),
						vf.createLiteral("one more row"));
				connection.commit();
			}
			long latest = latestSequence(backing);
			boolean covered = awaitCovered(backing, latest, 20_000L);
			FrontierStatisticsStatus status = status(backing);
			assertTrue(covered, "a commit after a budget change must be covered by a fresh base instead of a "
					+ "permanently failing delta; covered=" + status.coveredSequence() + " latest=" + latest
					+ " lastFailure=" + status.lastFailure());
			assertTrue(status.baseEpoch() > firstBaseEpoch,
					"the base must be rebuilt with the current Omni dimensions; baseEpoch=" + status.baseEpoch());
		} finally {
			wide.shutDown();
		}
	}

	/** Phases only the base builder reports; signed deltas report {@code APPLYING_DELTAS}. */
	private static boolean baseRebuildPhase(FrontierStatisticsStatus status) {
		return switch (status.buildPhase()) {
		case PASS_ONE, PASS_TWO, COMPACTING, PUBLISHING -> true;
		case IDLE, APPLYING_DELTAS, FAILED -> false;
		};
	}

	private static LmdbStoreConfig config(long synopsisBudget) {
		return new LmdbStoreConfig("spoc,posc")
				.setFrontierEstimatorMode(FrontierEstimatorMode.AUTHORITATIVE)
				.setFrontierSynopsisBudgetBytes(synopsisBudget);
	}

	private static long deltaTierBytes(FrontierStatisticsStatus status) {
		return status.diskBytesByTier().getOrDefault(FrontierStatisticsTier.DELTAS_AND_MANIFESTS, 0L);
	}

	private static FrontierLeafEstimate predicateEstimate(LmdbSailStore backing, IRI predicate) throws Exception {
		LmdbStatisticsService service = (LmdbStatisticsService) field(backing, "statisticsService");
		ValueStore valueStore = (ValueStore) field(backing, "valueStore");
		long predicateId = valueStore.getId(predicate);
		return service.estimateLeafCurrent(new FrontierLeafProbe(FrontierLeafProbe.BOTH_PLANES,
				FrontierLeafProbe.PREDICATE, 0L, predicateId, 0L, 0L));
	}

	private static long latestSequence(LmdbSailStore backing) throws Exception {
		Method method = LmdbSailStore.class.getDeclaredMethod("statementMutationStamp");
		method.setAccessible(true);
		return (long) method.invoke(backing);
	}

	private static boolean awaitReady(LmdbSailStore backing, long timeoutMillis) {
		return backing.awaitFrontierStatisticsReady(timeoutMillis);
	}

	private static boolean awaitCovered(LmdbSailStore backing, long sequence, long timeoutMillis) {
		return backing.awaitFrontierStatisticsCoveredSequence(sequence, timeoutMillis);
	}

	private static FrontierStatisticsStatus status(LmdbSailStore backing) {
		return backing.frontierStatisticsStatus();
	}

	private static Object field(LmdbSailStore backing, String name) throws Exception {
		Field field = LmdbSailStore.class.getDeclaredField(name);
		field.setAccessible(true);
		return field.get(backing);
	}
}
