/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.evaluation;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryResults;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.LmdbStore;
import org.eclipse.rdf4j.sail.lmdb.RecordIterator;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbNativeBatchExecutionTest {

	private static final String EX = "http://example.com/";
	private static final String NATIVE_FLAG = "rdf4j.lmdb.nativeQueryEngine.enabled";

	@TempDir
	File dataDir;

	SailRepository repository;

	@BeforeEach
	void setUp() {
		repository = new SailRepository(new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc,ospc")));
		try (SailRepositoryConnection connection = repository.getConnection()) {
			ValueFactory vf = connection.getValueFactory();
			IRI value = vf.createIRI(EX, "value");
			IRI self = vf.createIRI(EX, "self");
			IRI graph = vf.createIRI(EX, "graph");
			for (int i = 0; i < 40; i++) {
				IRI subject = vf.createIRI(EX, "s" + i);
				connection.add(subject, value, vf.createLiteral(i));
				if ((i & 1) == 0) {
					connection.add(subject, self, subject, graph);
					connection.add(subject, self, vf.createIRI(EX, "other" + i), graph);
				}
			}
		}
	}

	@AfterEach
	void tearDown() {
		System.clearProperty(NativeBatch.ENABLED_PROPERTY);
		System.clearProperty(NativeBatch.ROWS_PROPERTY);
		System.clearProperty(NATIVE_FLAG);
		repository.shutDown();
	}

	@Test
	void scanFilterProjectionMatchesGenericAcrossBatchSizes() {
		String query = "PREFIX ex: <" + EX + ">\n"
				+ "SELECT ?s ?v WHERE { ?s ex:value ?v . FILTER(?v >= 10 && ?v < 30) }";
		List<String> generic = genericRows(query);

		for (int capacity : new int[] { 1, 7, 64 }) {
			resetCounters();
			System.setProperty(NativeBatch.ENABLED_PROPERTY, "true");
			System.setProperty(NativeBatch.ROWS_PROPERTY, Integer.toString(capacity));

			assertThat(rows(query)).as("batch size " + capacity).isEqualTo(generic);
			assertThat(NativeBatch.ROOT_ITERATIONS.get()).isPositive();
			assertThat(NativeBatch.DIRECT_PATTERN_FILLS.get()).isPositive();
			assertThat(NativeBatch.FILTER_BATCHES.get()).isPositive();
		}
	}

	@Test
	void directPatternBatchPreservesRepeatedVariablesAndNamedGraphs() throws Exception {
		NativeSlotLayout layout = new NativeSlotLayout(Map.of("s", 0, "g", 1), null);
		layout.freeze(List.of("s", "g"));
		BatchTestSource source = new BatchTestSource();
		RowState row = new RowState(source, layout, EmptyBindingSet.getInstance());
		assertThat(LmdbNativeAggregateCompiler.initializeRow(row, EmptyBindingSet.getInstance(), source, layout))
				.isTrue();
		PatternPlan pattern = new PatternPlan(Term.slot(0), Term.constant(2), Term.slot(0), Term.slot(1),
				ContextConstraint.UNRESTRICTED, true, 3);
		resetCounters();

		NativeBatch batch = new NativeBatch(2, 7);
		try (BatchCursor cursor = pattern.openBatch(row, batch.capacity)) {
			assertThat(cursor.fill(batch)).isOne();
			assertThat(batch.get(0, 0)).isEqualTo(10);
			assertThat(batch.get(1, 0)).isEqualTo(100);
			assertThat(cursor.fill(batch)).isZero();
		}
		assertThat(NativeBatch.DIRECT_PATTERN_FILLS.get()).isPositive();
	}

	@Test
	void disabledBatchUsesTheExistingRowCursor() {
		String query = "PREFIX ex: <" + EX + ">\nSELECT ?s ?v WHERE { ?s ex:value ?v }";
		List<String> generic = genericRows(query);
		resetCounters();
		System.setProperty(NativeBatch.ENABLED_PROPERTY, "false");

		assertThat(rows(query)).isEqualTo(generic);
		assertThat(NativeBatch.ROOT_ITERATIONS.get()).isZero();
		assertThat(NativeBatch.DIRECT_PATTERN_FILLS.get()).isZero();
	}

	private List<String> genericRows(String query) {
		System.setProperty(NATIVE_FLAG, "false");
		try {
			return rows(query);
		} finally {
			System.clearProperty(NATIVE_FLAG);
		}
	}

	private List<String> rows(String query) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			return QueryResults.asList(connection.prepareTupleQuery(query).evaluate())
					.stream()
					.map(LmdbNativeBatchExecutionTest::canonical)
					.sorted()
					.collect(Collectors.toList());
		}
	}

	private static String canonical(BindingSet bindings) {
		return bindings.getBindingNames()
				.stream()
				.sorted()
				.map(name -> name + "=" + bindings.getValue(name))
				.collect(Collectors.joining(";", "[", "]"));
	}

	private static void resetCounters() {
		NativeBatch.ROOT_ITERATIONS.set(0);
		NativeBatch.DIRECT_PATTERN_FILLS.set(0);
		NativeBatch.DIRECT_VALUES_FILLS.set(0);
		NativeBatch.FILTER_BATCHES.set(0);
	}

	private static final class BatchTestSource implements NativeLmdbQuerySource {

		@Override
		public long idOf(Value value) {
			return UNKNOWN_ID;
		}

		@Override
		public Value lazyValue(long id) {
			throw new UnsupportedOperationException();
		}

		@Override
		public Object idSpace() {
			return this;
		}

		@Override
		public RecordIterator statements(long subj, long pred, long obj, long context) {
			return new RecordIterator() {
				final long[][] rows = {
						{ 10, 2, 10, 100 },
						{ 11, 2, 12, 100 },
						{ 13, 2, 13, 0 }
				};
				int index;

				@Override
				public long[] next() {
					return index < rows.length ? rows[index++] : null;
				}

				@Override
				public void close() {
					index = rows.length;
				}
			};
		}

		@Override
		public long count(long subj, long pred, long obj, long context) {
			return 3;
		}

		@Override
		public boolean has(long subj, long pred, long obj, long context) {
			return true;
		}

		@Override
		public double estimate(long subj, long pred, long obj, long context) {
			return 3;
		}

		@Override
		public boolean hasStatementsInSource() {
			return true;
		}
	}
}
