/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.io.StringReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Differential run develop vs branch (WP9 3.11.6, Layer 3): planning these tiny queries on the branch's LmdbStore never
 * finishes; the packed planner keeps deriving facts ({@code PackedQueryCodec$Builder.deriveFactsAndSaturateRules} ->
 * {@code PackedLogicalRuleProgram.addPayloadTerms} / {@code addRelationOutputs}) until the heap is exhausted. The
 * shapes share an equality (or IN) filter on a variable whose predicate has typed-literal objects (xsd:int,
 * xsd:decimal, xsd:date, xsd:boolean), inside a LATERAL or an OPTIONAL condition; with IRI or plain-string objects they
 * plan fine. Develop's LmdbStore and the branch's MemoryStore answer in milliseconds. Each query runs in a child JVM
 * (512 MiB heap, 60 s limit) so the runaway planner cannot destabilise this fork.
 */
public class LmdbPackedPlanningBlowupTest {

	private static final String PREFIX = "PREFIX : <http://ex/>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n";

	@TempDir
	File dataDir;

	@Test
	public void lateralWithEqualityFilterOverNumericObjectPlansInBoundedMemory() throws Exception {
		assertEquals("rows=0", runInChildJvm(":c :r \"01\"^^xsd:int .",
				"SELECT * WHERE { LATERAL { :c :r ?s . } FILTER(?s = \"b\") }"));
	}

	@Test
	public void graphOptionalLateralWithEqualityFilterPlansInBoundedMemory() throws Exception {
		// expected: GRAPH :g over a graph that does not exist; RDF4J (develop and the branch's MemoryStore) returns the
		// single empty solution of the OPTIONAL's left side
		assertEquals("rows=1", runInChildJvm(":b :p 1.0 .\n:b :r \"2\"^^xsd:integer .",
				"SELECT * WHERE { GRAPH :g { OPTIONAL { LATERAL { :a :p ?z . } FILTER(?z = \"b\") } } }"));
	}

	@Test
	public void optionalConditionWithInAndEqualityOverBooleanObjectPlansInBoundedMemory() throws Exception {
		// no :r triples, so the GROUP BY ?z has no groups
		assertEquals("rows=0", runInChildJvm(":c :q \"true\"^^xsd:boolean .",
				"SELECT ?z (MAX(?o) AS ?agg) WHERE { ?x :r ?y . OPTIONAL { ?o :q ?s ."
						+ " FILTER((?s IN (:d, \"b\") && ?y = :a)) } } GROUP BY ?z"));
	}

	private String runInChildJvm(String data, String query) throws Exception {
		Path dataFile = dataDir.toPath().resolve("data.ttl");
		Path queryFile = dataDir.toPath().resolve("query.rq");
		Files.writeString(dataFile, data, StandardCharsets.UTF_8);
		Files.writeString(queryFile, query, StandardCharsets.UTF_8);
		String java = Path.of(System.getProperty("java.home"), "bin", "java").toString();
		ProcessBuilder builder = new ProcessBuilder(List.of(java, "-Xmx512m", "--enable-native-access=ALL-UNNAMED",
				"-cp", System.getProperty("java.class.path"), Child.class.getName(),
				new File(dataDir, "store").getAbsolutePath(), dataFile.toString(), queryFile.toString()))
						.redirectErrorStream(true);
		Process process = builder.start();
		boolean finished = process.waitFor(60, TimeUnit.SECONDS);
		if (!finished) {
			process.destroyForcibly().waitFor(10, TimeUnit.SECONDS);
		}
		String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
		assertTrue(finished, "planning did not finish within 60 s\n" + tail(output));
		String last = output.lines().filter(line -> line.startsWith("rows=")).reduce((a, b) -> b).orElse(null);
		assertEquals(0, process.exitValue(), "child JVM failed\n" + tail(output));
		return last;
	}

	private static String tail(String output) {
		return output.length() > 4000 ? output.substring(output.length() - 4000) : output;
	}

	/** Child JVM entry point: loads the data, evaluates the query once and prints the row count. */
	public static final class Child {
		public static void main(String[] args) throws Exception {
			SailRepository repository = new SailRepository(
					new LmdbStore(new File(args[0]), new LmdbStoreConfig("spoc,posc")));
			repository.init();
			try (SailRepositoryConnection conn = repository.getConnection()) {
				conn.add(new StringReader(
						"@prefix : <http://ex/> .\n@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n"
								+ Files.readString(Path.of(args[1]))),
						"http://ex/", RDFFormat.TURTLE);
				int rows = 0;
				try (TupleQueryResult result = conn.prepareTupleQuery(PREFIX + Files.readString(Path.of(args[2])))
						.evaluate()) {
					while (result.hasNext()) {
						result.next();
						rows++;
					}
				}
				System.out.println("rows=" + rows);
			} finally {
				repository.shutDown();
			}
		}
	}
}
