/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Group;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryBindingSet;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.explanation.TelemetryMetricNames;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbFiniteValuesJoinSurfacePlanningTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI RDF_TYPE = VF.createIRI("http://www.w3.org/1999/02/22-rdf-syntax-ns#type");
	private static final IRI ENG_ASSEMBLY = VF.createIRI("http://example.com/theme/engineering/Assembly");
	private static final IRI ENG_NAME = VF.createIRI("http://example.com/theme/engineering/name");
	private static final IRI ENG_PART_OF = VF.createIRI("http://example.com/theme/engineering/partOf");
	private static final IRI MED_VALUE = VF.createIRI("http://example.com/theme/medical/value");
	private static final IRI MED_HAS_OBSERVATION = VF.createIRI("http://example.com/theme/medical/hasObservation");
	private static final int ASSEMBLY_COUNT = 3;
	private static final int COMPONENTS_PER_ASSEMBLY = 140;
	private static final int OBSERVATIONS_PER_VALUE = 300;

	@Test
	void valuesNameBindingEstimatesDerivedAssemblyPartOfSurface(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticEngineeringAssemblies(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment assemblyNames = assemblyNameBindings();
			StatementPattern name = new StatementPattern(Var.of("assembly"), Var.of("namePredicate", ENG_NAME),
					Var.of("assemblyName"));
			StatementPattern type = new StatementPattern(Var.of("assembly"), Var.of("rdfType", RDF_TYPE),
					Var.of("assemblyType", ENG_ASSEMBLY));
			StatementPattern partOf = new StatementPattern(Var.of("component"), Var.of("partOfPredicate", ENG_PART_OF),
					Var.of("assembly"));
			assertDirectFiniteDerivedPartOfSurface(store, assemblyNames, name, type, partOf);
			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinOrderPlanner.JoinOrderPlan plan = planner
					.estimateJoinOrder(List.of(assemblyNames, name, type, partOf), Set.of(),
							JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING, List.of())
					.orElseThrow();

			assertEstimatedWorkMatchesStepSum(plan);
			assertEquals(partOf, plan.getOrderedArgs().get(3),
					"The fixed-order estimate should preserve the requested partOf step position");

			JoinOrderPlanner.PlanStep partOfStep = plan.getSteps().get(3);
			double expectedSurfaceRows = ASSEMBLY_COUNT * COMPONENTS_PER_ASSEMBLY;
			double plannedAccessRows = partOfStep.getDoubleMetrics()
					.getOrDefault(TelemetryMetricNames.PLANNED_ACCESS_ROWS, partOfStep.getStepWorkRows());
			assertEquals(COMPONENTS_PER_ASSEMBLY, plannedAccessRows, COMPONENTS_PER_ASSEMBLY * 0.25d,
					"The VALUES-derived ?assembly surface should keep the partOf lookup on a single-assembly "
							+ "access path while repeated invocations account for the finite branches. "
							+ "expectedAccessRows=" + COMPONENTS_PER_ASSEMBLY
							+ ", metrics=" + partOfStep.getStringMetrics() + partOfStep.getDoubleMetrics()
							+ ", stepWork=" + partOfStep.getStepWorkRows());
			assertTrue(partOfStep.getStepWorkRows() <= expectedSurfaceRows * 2.25d,
					"The step work should stay near access plus emitted rows for the finite partOf surface. "
							+ "expectedSurfaceRows="
							+ expectedSurfaceRows + ", metrics=" + partOfStep.getStringMetrics()
							+ partOfStep.getDoubleMetrics() + ", stepWork=" + partOfStep.getStepWorkRows());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void optionalPartOfEstimateUsesFiniteDerivedAssemblySurface(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticEngineeringAssemblies(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment assemblyNames = assemblyNameBindings();
			StatementPattern name = new StatementPattern(Var.of("assembly"), Var.of("namePredicate", ENG_NAME),
					Var.of("assemblyName"));
			StatementPattern type = new StatementPattern(Var.of("assembly"), Var.of("rdfType", RDF_TYPE),
					Var.of("assemblyType", ENG_ASSEMBLY));
			StatementPattern partOf = new StatementPattern(Var.of("component"), Var.of("partOfPredicate", ENG_PART_OF),
					Var.of("assembly"));
			QueryRoot root = new QueryRoot(new LeftJoin(new Join(new Join(assemblyNames, name), type), partOf));

			new LmdbSketchJoinOptimizer(store.getBackingStore().getEvaluationStatistics(), true)
					.optimize(root, null, null);

			LeftJoin leftJoin = (LeftJoin) root.getArg();
			double expectedSurfaceRows = ASSEMBLY_COUNT * COMPONENTS_PER_ASSEMBLY;
			double plannedAccessRows = partOf.getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_ACCESS_ROWS);
			assertEquals(COMPONENTS_PER_ASSEMBLY, plannedAccessRows, COMPONENTS_PER_ASSEMBLY * 0.25d,
					"The optional partOf lookup should use the bounded per-assembly access path from the left side. "
							+ "expectedSurfaceRows=" + expectedSurfaceRows + ", plannedAccessRows="
							+ plannedAccessRows + ", plannedWorkRows="
							+ partOf.getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_WORK_ROWS)
							+ ", source="
							+ partOf.getStringMetricPlanned(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE));
			assertTrue(partOf.getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_WORK_ROWS) <= expectedSurfaceRows,
					"The optional partOf work should stay bounded by the finite ?assembly surface. expectedSurfaceRows="
							+ expectedSurfaceRows + ", plannedAccessRows=" + plannedAccessRows
							+ ", plannedWorkRows="
							+ partOf.getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_WORK_ROWS)
							+ ", optionalBoundInvocations="
							+ partOf.getDoubleMetricPlanned("plannedOptionalBoundInvocations")
							+ ", repeatedInvocations="
							+ partOf.getDoubleMetricPlanned("plannedRepeatedInvocations")
							+ ", distinctLookupBindings="
							+ partOf.getDoubleMetricPlanned("plannedDistinctLookupBindings")
							+ ", source="
							+ partOf.getStringMetricPlanned(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE));
			assertTrue(leftJoin.getResultSizeEstimate() <= expectedSurfaceRows * ASSEMBLY_COUNT,
					"The optional left join should keep a finite result surface upward instead of "
							+ "keeping a broad synthetic cardinality. expectedSurfaceRows=" + expectedSurfaceRows
							+ ", leftJoinRows=" + leftJoin.getResultSizeEstimate() + ", leftJoinWork="
							+ leftJoin.getCostEstimate());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void groupedOptionalPartOfEstimateUsesFiniteDerivedAssemblySurface(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticEngineeringAssemblies(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment assemblyNames = assemblyNameBindings();
			StatementPattern name = new StatementPattern(Var.of("assembly"), Var.of("namePredicate", ENG_NAME),
					Var.of("assemblyName"));
			StatementPattern type = new StatementPattern(Var.of("assembly"), Var.of("rdfType", RDF_TYPE),
					Var.of("assemblyType", ENG_ASSEMBLY));
			StatementPattern partOf = new StatementPattern(Var.of("component"), Var.of("partOfPredicate", ENG_PART_OF),
					Var.of("assembly"));
			LeftJoin leftJoin = new LeftJoin(new Join(new Join(assemblyNames, name), type), partOf);
			Group group = new Group(leftJoin);
			group.addGroupBindingName("assembly");
			QueryRoot root = new QueryRoot(group);

			new LmdbSketchJoinOptimizer(store.getBackingStore().getEvaluationStatistics(), true)
					.optimize(root, null, null);

			double expectedSurfaceRows = ASSEMBLY_COUNT * COMPONENTS_PER_ASSEMBLY;
			assertTrue(leftJoin.getResultSizeEstimate() <= expectedSurfaceRows * ASSEMBLY_COUNT,
					"The grouped optional left join should expose a finite result surface in its own "
							+ "printed estimate. expectedSurfaceRows=" + expectedSurfaceRows + ", leftJoinRows="
							+ leftJoin.getResultSizeEstimate() + ", leftJoinWork=" + leftJoin.getCostEstimate()
							+ ", originalRightSource="
							+ partOf.getStringMetricPlanned(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE)
							+ ", ownedRightSource="
							+ leftJoin.getRightArg()
									.getStringMetricPlanned(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE)
							+ ", ownedAccessRows="
							+ leftJoin.getRightArg().getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_ACCESS_ROWS)
							+ ", ownedRepeatedInvocations="
							+ leftJoin.getRightArg().getDoubleMetricPlanned("plannedRepeatedInvocations")
							+ ", ownedDistinctLookupBindings="
							+ leftJoin.getRightArg().getDoubleMetricPlanned("plannedDistinctLookupBindings")
							+ ", sameRight=" + (leftJoin.getRightArg() == partOf));
			assertEquals(COMPONENTS_PER_ASSEMBLY,
					leftJoin.getRightArg().getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_ACCESS_ROWS),
					COMPONENTS_PER_ASSEMBLY * 0.25d,
					"The grouped optional right side should remain a bounded per-assembly lookup: "
							+ leftJoin.getRightArg()
									.getStringMetricPlanned(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE)
							+ leftJoin.getRightArg().getDoubleMetricPlanned(TelemetryMetricNames.PLANNED_WORK_ROWS));
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void valuesObjectBindingEstimatesDerivedObservationEncounterSurface(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticMedicalObservations(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment values = observationValueBindings();
			StatementPattern value = new StatementPattern(Var.of("obs"), Var.of("valuePredicate", MED_VALUE),
					Var.of("value"));
			StatementPattern hasObservation = new StatementPattern(Var.of("enc"),
					Var.of("hasObservationPredicate", MED_HAS_OBSERVATION), Var.of("obs"));
			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinOrderPlanner.JoinOrderPlan plan = planner
					.estimateJoinOrder(List.of(values, value, hasObservation), Set.of(),
							JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING, List.of())
					.orElseThrow();

			assertEstimatedWorkMatchesStepSum(plan);
			int hasObservationIndex = plan.getOrderedArgs().indexOf(hasObservation);
			assertTrue(hasObservationIndex >= 0, "Expected hasObservation in the selected plan: " + plan);
			JoinOrderPlanner.PlanStep hasObservationStep = plan.getSteps().get(hasObservationIndex);

			double expectedSurfaceRows = 3.0d * OBSERVATIONS_PER_VALUE;
			assertTrue(!"lmdb-finite-derived-surface".equals(hasObservationStep.getStringMetrics()
					.get(TelemetryMetricNames.PLANNED_ESTIMATE_SOURCE)),
					"Standard planning must not derive an exact finite ?obs surface while costing hasObservation. plan="
							+ plan.getOrderedArgs() + ", metrics=" + hasObservationStep.getStringMetrics()
							+ hasObservationStep.getDoubleMetrics() + ", work="
							+ hasObservationStep.getStepWorkRows());
			assertTrue(hasObservationStep.getDoubleMetrics()
					.get("plannedLookupDomainAverageOutputRows") <= expectedSurfaceRows * 1.25d,
					"The planning-safe lookup-domain estimate should stay near the finite ?obs surface. "
							+ "expected=" + expectedSurfaceRows + ", metrics="
							+ hasObservationStep.getStringMetrics() + hasObservationStep.getDoubleMetrics()
							+ ", work=" + hasObservationStep.getStepWorkRows());
			assertTrue(hasObservationStep.getDoubleMetrics()
					.get(TelemetryMetricNames.PLANNED_ACCESS_ROWS) <= expectedSurfaceRows * 1.25d,
					"The derived hasObservation lookup should expose access rows near the finite ?obs surface. "
							+ "expected=" + expectedSurfaceRows + ", metrics="
							+ hasObservationStep.getStringMetrics() + hasObservationStep.getDoubleMetrics()
							+ ", work=" + hasObservationStep.getStepWorkRows());
			assertTrue(hasObservationStep.getStepWorkRows() <= expectedSurfaceRows * 2.25d,
					"The derived hasObservation step should stay near access plus emitted rows for the finite "
							+ "?obs surface. expected=" + expectedSurfaceRows + ", metrics="
							+ hasObservationStep.getStringMetrics() + hasObservationStep.getDoubleMetrics()
							+ ", work=" + hasObservationStep.getStepWorkRows());
		} finally {
			repository.shutDown();
		}
	}

	private static void loadSyntheticEngineeringAssemblies(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 1; i <= ASSEMBLY_COUNT; i++) {
				Resource assembly = assembly(i);
				connection.add(assembly, ENG_NAME, VF.createLiteral("Assembly " + i));
				connection.add(assembly, RDF_TYPE, ENG_ASSEMBLY);
				for (int componentIndex = 0; componentIndex < COMPONENTS_PER_ASSEMBLY; componentIndex++) {
					connection.add(VF.createIRI("urn:test:engineering:component:" + i + ":" + componentIndex),
							ENG_PART_OF, assembly);
				}
			}
			for (int i = 0; i < 2_000; i++) {
				Resource assembly = VF.createIRI("urn:test:engineering:noise-assembly:" + i);
				connection.add(assembly, ENG_NAME, VF.createLiteral("Noise Assembly " + i));
				connection.add(assembly, RDF_TYPE, ENG_ASSEMBLY);
			}
			connection.commit();
		}
	}

	private static void loadSyntheticMedicalObservations(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			int[] selectedValues = { 50, 60, 70 };
			for (int value : selectedValues) {
				for (int i = 0; i < OBSERVATIONS_PER_VALUE; i++) {
					Resource observation = VF.createIRI("urn:test:medical:observation:" + value + ":" + i);
					Resource encounter = VF.createIRI("urn:test:medical:encounter:" + value + ":" + i);
					connection.add(observation, MED_VALUE, VF.createLiteral(String.valueOf(value), XSD.INTEGER));
					connection.add(encounter, MED_HAS_OBSERVATION, observation);
				}
			}
			for (int i = 0; i < 2_000; i++) {
				Resource observation = VF.createIRI("urn:test:medical:noise-observation:" + i);
				connection.add(observation, MED_VALUE, VF.createLiteral(String.valueOf(1_000 + i), XSD.INTEGER));
			}
			connection.commit();
		}
	}

	private static Resource assembly(int index) {
		return VF.createIRI("urn:test:engineering:assembly:" + index);
	}

	private static BindingSetAssignment assemblyNameBindings() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		List<BindingSet> bindingSets = new ArrayList<>();
		for (int i = 1; i <= ASSEMBLY_COUNT; i++) {
			QueryBindingSet bindingSet = new QueryBindingSet();
			bindingSet.addBinding("assemblyName", VF.createLiteral("Assembly " + i));
			bindingSets.add(bindingSet);
		}
		assignment.setBindingSets(bindingSets);
		return assignment;
	}

	private static void assertDirectFiniteDerivedPartOfSurface(LmdbStore store, BindingSetAssignment assemblyNames,
			StatementPattern name, StatementPattern type, StatementPattern partOf) {
		JoinFactorCostModel costModel = (JoinFactorCostModel) store.getBackingStore().getEvaluationStatistics();
		Optional<JoinFactorCostModel.FactorCostEstimate> estimate = costModel.estimateFactorCost(partOf,
				JoinFactorCostModel.CostContext.of(Set.of("assemblyName", "assembly"), 3.0d, 3.0d, true, true,
						Map.of("assemblyName", Set.of(VF.createLiteral("Assembly 1"),
								VF.createLiteral("Assembly 2"), VF.createLiteral("Assembly 3"))),
						List.of(assemblyNames, name, type)));
		assertTrue(estimate.isPresent(), "Expected a direct cost-model estimate for the derived partOf surface");
		assertEquals(COMPONENTS_PER_ASSEMBLY,
				estimate.get().getDoubleMetrics().get(TelemetryMetricNames.PLANNED_ACCESS_ROWS),
				COMPONENTS_PER_ASSEMBLY * 0.25d,
				"The direct cost-model path should use the per-assembly partOf access path. metrics="
						+ estimate.get().getStringMetrics() + estimate.get().getDoubleMetrics());
		assertEquals(ASSEMBLY_COUNT, estimate.get().getDoubleMetrics().get("plannedRepeatedInvocations"), 0.0d,
				"The direct cost-model path should account for each finite assembly lookup. metrics="
						+ estimate.get().getStringMetrics() + estimate.get().getDoubleMetrics());
		assertEquals(ASSEMBLY_COUNT * COMPONENTS_PER_ASSEMBLY,
				estimate.get().getDoubleMetrics().get(TelemetryMetricNames.PLANNED_WORK_ROWS),
				COMPONENTS_PER_ASSEMBLY * 0.25d,
				"The direct cost-model path should keep total work near the finite partOf surface. metrics="
						+ estimate.get().getStringMetrics() + estimate.get().getDoubleMetrics());
	}

	private static BindingSetAssignment observationValueBindings() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		List<BindingSet> bindingSets = new ArrayList<>();
		for (int value : new int[] { 50, 60, 70 }) {
			QueryBindingSet bindingSet = new QueryBindingSet();
			bindingSet.addBinding("value", VF.createLiteral(String.valueOf(value), XSD.INTEGER));
			bindingSets.add(bindingSet);
		}
		assignment.setBindingSets(bindingSets);
		return assignment;
	}

	private static void assertEstimatedWorkMatchesStepSum(JoinOrderPlanner.JoinOrderPlan plan) {
		double stepWorkSum = plan.getSteps()
				.stream()
				.mapToDouble(JoinOrderPlanner.PlanStep::getStepWorkRows)
				.sum();
		assertEquals(stepWorkSum, plan.getEstimatedTotalWork(), 1.0e-9,
				"Planner total work should equal sum(stepWorkRows)");
		for (TupleExpr orderedArg : plan.getOrderedArgs()) {
			assertTrue(plan.getSteps().size() == plan.getOrderedArgs().size(),
					"Expected one planner step per factor: " + orderedArg);
		}
	}
}
