/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertInstanceOf;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.algebra.Bound;
import org.eclipse.rdf4j.query.algebra.EmptySet;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryOptimizer;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.junit.jupiter.api.Test;

class LmdbBoundSimplifierOptimizerTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void preSketchRemovesAssuredBoundFilter() {
		QueryRoot root = optimizeBeforeSketch(new Filter(statementPattern("s", "p", "o"), new Bound(new Var("o"))));

		assertInstanceOf(StatementPattern.class, root.getArg(), () -> root.getArg().toString());
	}

	@Test
	void preSketchReplacesImpossibleBoundFilterWithEmptySet() {
		QueryRoot root = optimizeBeforeSketch(
				new Filter(statementPattern("s", "p", "o"), new Bound(new Var("missing"))));

		assertInstanceOf(EmptySet.class, root.getArg(), () -> root.getArg().toString());
	}

	@Test
	void preSketchRemovesNegatedImpossibleBoundFilter() {
		QueryRoot root = optimizeBeforeSketch(
				new Filter(statementPattern("s", "p", "o"), new Not(new Bound(new Var("missing")))));

		assertInstanceOf(StatementPattern.class, root.getArg(), () -> root.getArg().toString());
	}

	@Test
	void preSketchSimplifiesBoundInsideOptionalRightSide() {
		StatementPattern required = statementPattern("s", "type", "type");
		StatementPattern optional = statementPattern("s", "name", "optName");
		QueryRoot root = optimizeBeforeSketch(new LeftJoin(required, new Filter(optional, new Bound(new Var(
				"optName")))));

		LeftJoin leftJoin = assertInstanceOf(LeftJoin.class, root.getArg(), () -> root.getArg().toString());
		assertInstanceOf(StatementPattern.class, leftJoin.getRightArg(), () -> root.getArg().toString());
	}

	private static QueryRoot optimizeBeforeSketch(TupleExpr tupleExpr) {
		QueryRoot root = new QueryRoot(tupleExpr);
		TripleSource tripleSource = new EmptyTripleSource();
		StrictEvaluationStrategy strategy = new StrictEvaluationStrategy(tripleSource, null);
		for (QueryOptimizer optimizer : new LmdbQueryOptimizerPipeline(strategy, tripleSource,
				new EvaluationStatistics()).getOptimizers()) {
			if (optimizer instanceof LmdbCascadesOptimizer) {
				break;
			}
			optimizer.optimize(root, null, EmptyBindingSet.getInstance());
		}
		return root;
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName));
	}

	private static final class EmptyTripleSource implements TripleSource {

		@Override
		public CloseableIteration<? extends Statement> getStatements(Resource subj, IRI pred, Value obj,
				Resource... contexts) throws QueryEvaluationException {
			return EMPTY_ITERATION;
		}

		@Override
		public ValueFactory getValueFactory() {
			return VF;
		}
	}
}
