/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.TreeSet;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.DefaultEvaluationStrategyFactory;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.rio.helpers.NTriplesUtil;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * End-to-end guards for language-tag case handling in the LMDB store: RDF4J's {@code Literal.equals} compares language
 * tags case-insensitively (RDF 1.1 Concepts 3.3 puts them in lower case in the value space), so {@code "abc"@en} and
 * {@code "abc"@EN} are the same term and must resolve to one value id whether or not the value-id cache is warm.
 * <p>
 * Every case evaluates the same query over the same data on two LMDB stores: one with the automatic LMDB optimizer
 * pipeline and one with RDF4J's {@link DefaultEvaluationStrategyFactory} (the standard pipeline MemoryStore uses). Both
 * are compared with a hand-computed SPARQL 1.1 answer bag, warm (right after loading) and cold (after closing and
 * reopening the store so every value-id cache is empty).
 */
class LmdbLanguageTagTermIdentityTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final String NS = "http://example.org/";
	private static final String PREFIX = "PREFIX : <" + NS + ">\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n";
	private static final String S1 = "s=<http://example.org/s1>";
	private static final String S2 = "s=<http://example.org/s2>";

	@TempDir
	File tempDir;

	// ---------------------------------------------------------------------------------------------------------
	// FILTER equality on a case-variant tag (VALUES anchor / literal anchor path of the LMDB pipeline)
	// ---------------------------------------------------------------------------------------------------------

	@Test
	void filterEqualityWithCaseVariantTagWarm() {
		check(List.of(st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"abc\"@EN) }", List.of(S1));
	}

	@Test
	void filterEqualityWithCaseVariantTagMultiPatternWarm() {
		check(List.of(st("s1", "label", VF.createLiteral("abc", "en")), st("s1", "type", iri("T"))),
				"SELECT ?s WHERE { ?s :type :T . ?s :label ?o FILTER(?o = \"abc\"@EN) }", List.of(S1));
	}

	@Test
	void filterEqualityWithCaseVariantTagColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"abc\"@EN) }", List.of(S1));
	}

	@Test
	void filterEqualityWithCaseVariantTagViaOptionalColdStore() {
		checkCold(List.of(st("s1", "type", iri("T")), st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :type :T OPTIONAL { ?s :label ?o } FILTER(?o = \"abc\"@EN) }", List.of(S1));
	}

	@Test
	void filterEqualityWithLowercaseTagOverUppercaseDataColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "EN"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"abc\"@en) }", List.of(S1));
	}

	@Test
	void filterEqualityWithRegionSubtagCaseVariantColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "en-US"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"abc\"@EN-us) }", List.of(S1));
	}

	@Test
	void filterEqualityWithLongLabelAndCaseVariantTagColdStore() {
		// long label: the value id is resolved through the hash path of the value store, not the short-key path
		String label = "a long label that does not fit into a short LMDB key ".repeat(3);
		checkCold(List.of(st("s1", "label", VF.createLiteral(label, "en"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"" + label + "\"@EN) }", List.of(S1));
	}

	@Test
	void sameTermWithCaseVariantTagColdStore() {
		// RDF4J term equality (Literal.equals) is case-insensitive on the language tag; both pipelines must agree.
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :label ?o FILTER(sameTerm(?o, \"abc\"@EN)) }", List.of(S1));
	}

	// ---------------------------------------------------------------------------------------------------------
	// Plain statement pattern with a constant case-variant tag (both pipelines resolve it through ValueStore.getId)
	// ---------------------------------------------------------------------------------------------------------

	@Test
	void plainPatternWithCaseVariantTagWarm() {
		check(List.of(st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :label \"abc\"@EN }", List.of(S1));
	}

	@Test
	void plainPatternWithCaseVariantTagColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "en"))),
				"SELECT ?s WHERE { ?s :label \"abc\"@EN }", List.of(S1));
	}

	@Test
	void plainPatternWithLowercaseTagOverUppercaseDataColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "EN"))),
				"SELECT ?s WHERE { ?s :label \"abc\"@en }", List.of(S1));
	}

	@Test
	void plainPatternWithDirectionalCaseVariantTagColdStore() {
		checkCold(List.of(st("s1", "label", VF.createLiteral("abc", "en", Literal.BaseDirection.LTR))),
				"SELECT ?s WHERE { ?s :label \"abc\"@EN--ltr }", List.of(S1));
	}

	// ---------------------------------------------------------------------------------------------------------
	// Create path: case variants written across a restart must be ONE term
	// ---------------------------------------------------------------------------------------------------------

	@Test
	void caseVariantsWrittenAcrossRestartAreOneTerm() {
		for (boolean standardPipeline : new boolean[] { false, true }) {
			File dataDir = new File(tempDir, standardPipeline ? "oracle" : "lmdb");
			add(dataDir, standardPipeline, List.of(st("s1", "label", VF.createLiteral("abc", "en"))));
			// cold cache: a byte-exact value store would create a second id for the case variant here
			add(dataDir, standardPipeline, List.of(st("s2", "label", VF.createLiteral("abc", "EN"))));

			SailRepository repository = open(dataDir, standardPipeline);
			try (RepositoryConnection connection = repository.getConnection()) {
				String pipeline = standardPipeline ? "standard pipeline" : "LMDB pipeline";
				assertEquals(List.of(S1, S2),
						rows(connection, PREFIX + "SELECT ?s WHERE { ?s :label ?o FILTER(?o = \"abc\"@en) }"),
						pipeline + ": FILTER(= \"abc\"@en) must see both rows");
				assertEquals(List.of(S1, S2), rows(connection, PREFIX + "SELECT ?s WHERE { ?s :label \"abc\"@en }"),
						pipeline + ": plain pattern \"abc\"@en must see both rows");
				assertEquals(List.of(S1, S2), rows(connection, PREFIX + "SELECT ?s WHERE { ?s :label \"abc\"@EN }"),
						pipeline + ": plain pattern \"abc\"@EN must see both rows");
				assertEquals(List.of("c=\"1\"^^<http://www.w3.org/2001/XMLSchema#integer>"),
						rows(connection, PREFIX + "SELECT (COUNT(DISTINCT ?o) AS ?c) WHERE { ?s :label ?o }"),
						pipeline + ": both rows must carry the same term");
				assertEquals(List.of("l=\"en\"", "l=\"en\""),
						rows(connection, PREFIX + "SELECT (LANG(?o) AS ?l) WHERE { ?s :label ?o }"),
						pipeline + ": the first written spelling of the tag is preserved for the shared term");
			} finally {
				repository.shutDown();
			}
		}
	}

	// ---------------------------------------------------------------------------------------------------------
	// Harness
	// ---------------------------------------------------------------------------------------------------------

	private void check(List<Statement> data, String queryBody, List<String> expected) {
		scenario(data, false, queryBody, expected);
	}

	/** Same as {@link #check} but closes and reopens both stores before querying, so value-id caches are cold. */
	private void checkCold(List<Statement> data, String queryBody, List<String> expected) {
		scenario(data, true, queryBody, expected);
	}

	private void scenario(List<Statement> data, boolean reopen, String queryBody, List<String> expected) {
		String query = PREFIX + queryBody;
		List<String> sortedExpected = sorted(expected);
		Result lmdb = evaluate(new File(tempDir, "lmdb"), false, data, reopen, query);
		Result oracle = evaluate(new File(tempDir, "oracle"), true, data, reopen, query);
		String report = "\nquery=" + query + "\nreopen=" + reopen + "\nexpected=" + sortedExpected + "\nlmdb="
				+ lmdb.rows() + "\noracle=" + oracle.rows() + "\nLMDB optimized plan:\n" + lmdb.plan();
		assertEquals(sortedExpected, lmdb.rows(), () -> "LMDB pipeline vs SPARQL spec" + report);
		assertEquals(sortedExpected, oracle.rows(), () -> "standard-pipeline oracle vs SPARQL spec" + report);
	}

	private static List<String> sorted(List<String> rows) {
		List<String> copy = new ArrayList<>(rows);
		Collections.sort(copy);
		return copy;
	}

	private static SailRepository open(File dataDir, boolean standardPipeline) {
		LmdbStore store = new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc"));
		if (standardPipeline) {
			store.setEvaluationStrategyFactory(new DefaultEvaluationStrategyFactory());
		}
		SailRepository repository = new SailRepository(store);
		repository.init();
		return repository;
	}

	private static void add(File dataDir, boolean standardPipeline, List<Statement> data) {
		SailRepository repository = open(dataDir, standardPipeline);
		try {
			try (RepositoryConnection connection = repository.getConnection()) {
				connection.add(data);
			}
		} finally {
			repository.shutDown();
		}
	}

	private static Result evaluate(File dataDir, boolean standardPipeline, List<Statement> data, boolean reopen,
			String query) {
		SailRepository repository = open(dataDir, standardPipeline);
		try {
			try (RepositoryConnection connection = repository.getConnection()) {
				connection.add(data);
			}
			if (reopen) {
				repository.shutDown();
				repository = open(dataDir, standardPipeline);
			}
			List<String> rows;
			String plan;
			try (RepositoryConnection connection = repository.getConnection()) {
				rows = rows(connection, query);
				plan = connection.prepareTupleQuery(query).explain(Explanation.Level.Optimized).toString();
			}
			if (standardPipeline) {
				LmdbStore store = (LmdbStore) repository.getSail();
				DefaultEvaluationStrategyFactory factory = assertInstanceOf(DefaultEvaluationStrategyFactory.class,
						store.getEvaluationStrategyFactory());
				assertTrue(factory.getOptimizerPipeline().isEmpty(), "oracle must use the standard pipeline");
			}
			return new Result(rows, plan);
		} finally {
			repository.shutDown();
		}
	}

	private static List<String> rows(RepositoryConnection connection, String query) {
		List<String> rows = new ArrayList<>();
		try (TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
			while (result.hasNext()) {
				rows.add(render(result.next()));
			}
		}
		Collections.sort(rows);
		return rows;
	}

	private static String render(BindingSet bindingSet) {
		List<String> parts = new ArrayList<>();
		for (String name : new TreeSet<>(bindingSet.getBindingNames())) {
			Value value = bindingSet.getValue(name);
			if (value != null) {
				parts.add(name + "=" + (value.isBNode() ? "_:b" : NTriplesUtil.toNTriplesString(value)));
			}
		}
		return String.join("|", parts);
	}

	private static IRI iri(String local) {
		return VF.createIRI(NS + local);
	}

	private static Statement st(String subject, String predicate, Value object) {
		return VF.createStatement(iri(subject), iri(predicate), object);
	}

	private record Result(List<String> rows, String plan) {
	}
}
