/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.FN;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import org.eclipse.rdf4j.query.algebra.And;
import org.eclipse.rdf4j.query.algebra.Bound;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Count;
import org.eclipse.rdf4j.query.algebra.Datatype;
import org.eclipse.rdf4j.query.algebra.Exists;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.FunctionCall;
import org.eclipse.rdf4j.query.algebra.Group;
import org.eclipse.rdf4j.query.algebra.GroupElem;
import org.eclipse.rdf4j.query.algebra.IsLiteral;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.Lang;
import org.eclipse.rdf4j.query.algebra.LangMatches;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.ListMemberOperator;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.Regex;
import org.eclipse.rdf4j.query.algebra.SameTerm;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Str;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.UnaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.junit.jupiter.api.Test;

class LmdbSketchJoinOptimizerOptionalRewriteTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void rewritesNullRejectingOptionalSameTermAgainstConstant() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		SameTerm condition = new SameTerm(new Var("optName"), new ValueConstant(VF.createLiteral("person/42")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalCompareAgainstAssuredBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Compare condition = new Compare(new Var("optName"), new Var("friend"), Compare.CompareOp.EQ);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalSameTermAgainstAssuredBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		SameTerm condition = new SameTerm(new Var("optName"), new Var("friend"));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalBoundDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional),
				new Bound(new Var("optName"))));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalRegexOnStringifiedDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Regex condition = new Regex(new Str(new Var("optName")), new ValueConstant(VF.createLiteral("^person/\\d+$")),
				new ValueConstant(VF.createLiteral("i")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalRegexAgainstAssuredPatternBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern pattern = statementPattern("person", "namePattern", "namePattern");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Regex condition = new Regex(new Str(new Var("optName")), new Var("namePattern"),
				new ValueConstant(VF.createLiteral("i")));
		QueryRoot root = new QueryRoot(
				new Filter(new LeftJoin(new Join(new Join(person, follows), pattern), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalContainsOnLowerCaseStringifiedDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		FunctionCall lowerCase = new FunctionCall(FN.LOWER_CASE.stringValue(), new Str(new Var("optName")));
		FunctionCall condition = new FunctionCall(FN.CONTAINS.stringValue(), lowerCase,
				new ValueConstant(VF.createLiteral("ada")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalTermKindPredicateOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional),
				new IsLiteral(new Var("optName"))));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalLanguageMatchOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		LangMatches condition = new LangMatches(new Lang(new Var("optName")),
				new ValueConstant(VF.createLiteral("en")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalLanguageMatchAgainstAssuredBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern languageRange = statementPattern("person", "languageRange", "langRange");
		StatementPattern optional = statementPattern("person", "name", "optName");
		LangMatches condition = new LangMatches(new Lang(new Var("optName")), new Var("langRange"));
		QueryRoot root = new QueryRoot(
				new Filter(new LeftJoin(new Join(new Join(person, follows), languageRange), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalDatatypeCompareOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Compare condition = new Compare(new Datatype(new Var("optName")), new ValueConstant(XSD.STRING),
				Compare.CompareOp.EQ);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalStringCompareOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Compare condition = new Compare(new Str(new Var("optName")), new ValueConstant(VF.createLiteral("Ada")),
				Compare.CompareOp.EQ);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalStringLengthCompareOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		FunctionCall length = new FunctionCall(FN.STRING_LENGTH.stringValue(), new Str(new Var("optName")));
		Compare condition = new Compare(length, new ValueConstant(VF.createLiteral(3)), Compare.CompareOp.GT);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalNumericAbsCompareOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "score", "optScore");
		FunctionCall absolute = new FunctionCall(FN.NUMERIC_ABS.stringValue(), new Var("optScore"));
		Compare condition = new Compare(absolute, new ValueConstant(VF.createLiteral(3)), Compare.CompareOp.GT);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNegatedNullRejectingOptionalStringCompareOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Compare inner = new Compare(new Str(new Var("optName")), new ValueConstant(VF.createLiteral("Ada")),
				Compare.CompareOp.EQ);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), new Not(inner)));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalStringSameTermOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		SameTerm condition = new SameTerm(new Str(new Var("optName")), new ValueConstant(VF.createLiteral("Ada")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalStringListMemberOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		ListMemberOperator condition = new ListMemberOperator();
		condition.addArgument(new Str(new Var("optName")));
		condition.addArgument(new ValueConstant(VF.createLiteral("Ada")));
		condition.addArgument(new ValueConstant(VF.createLiteral("Bob")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalConjunctWithNestedExists() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "title", "optTitle");
		StatementPattern nested = statementPattern("person", "dueDate", "dueDate");
		ValueExpr condition = new And(
				new Compare(new Var("optTitle"), new ValueConstant(VF.createLiteral("")), Compare.CompareOp.NE),
				new Not(new Exists(nested)));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void keepsHavingCountPositiveOptionalAsLeftJoin() {
		StatementPattern assembly = statementPattern("assembly", "type", "assemblyType");
		StatementPattern optional = statementPattern("component", "partOf", "assembly");
		Group group = new Group(new LeftJoin(assembly, optional));
		group.addGroupBindingName("assembly");
		group.addGroupElement(new GroupElem("componentCount", new Count(new Var("component"))));
		Compare having = new Compare(new Var("componentCount"), new ValueConstant(VF.createLiteral(0)),
				Compare.CompareOp.GT);
		QueryRoot root = new QueryRoot(new Filter(group, having));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		assertTrue(containsLeftJoin(root.getArg()), () -> root.getArg().toString());
	}

	@Test
	void keepsHavingCountNonRejectingOptionalAsLeftJoin() {
		StatementPattern assembly = statementPattern("assembly", "type", "assemblyType");
		StatementPattern optional = statementPattern("component", "partOf", "assembly");
		Group group = new Group(new LeftJoin(assembly, optional));
		group.addGroupBindingName("assembly");
		group.addGroupElement(new GroupElem("componentCount", new Count(new Var("component"))));
		Compare having = new Compare(new Var("componentCount"), new ValueConstant(VF.createLiteral(0)),
				Compare.CompareOp.GE);
		QueryRoot root = new QueryRoot(new Filter(group, having));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		assertTrue(containsLeftJoin(root.getArg()), () -> root.getArg().toString());
	}

	@Test
	void rewritesNullRejectingOptionalLanguageFallbackDisjunctionOnDirectBinding() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		ValueExpr condition = new Or(
				new LangMatches(new Lang(new Var("optName")), new ValueConstant(VF.createLiteral("nl"))),
				new Or(new LangMatches(new Lang(new Var("optName")), new ValueConstant(VF.createLiteral("en"))),
						new Compare(new Lang(new Var("optName")), new ValueConstant(VF.createLiteral("")),
								Compare.CompareOp.EQ)));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(new EvaluationStatistics(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName));
	}

	private static boolean containsLeftJoin(TupleExpr tupleExpr) {
		if (tupleExpr instanceof LeftJoin) {
			return true;
		}
		if (tupleExpr instanceof Filter) {
			return containsLeftJoin(((Filter) tupleExpr).getArg());
		}
		if (tupleExpr instanceof UnaryTupleOperator unary) {
			return containsLeftJoin(unary.getArg());
		}
		if (tupleExpr instanceof Join join) {
			return containsLeftJoin(join.getLeftArg()) || containsLeftJoin(join.getRightArg());
		}
		return false;
	}
}
