/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Field;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.ForkJoinTask;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.ValueExprEvaluationException;
import org.eclipse.rdf4j.query.algebra.evaluation.function.Function;
import org.eclipse.rdf4j.query.algebra.evaluation.function.FunctionRegistry;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.SailConflictException;
import org.eclipse.rdf4j.sail.SailConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;

class LmdbMapGrowthReplayLifecycleTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI FIRST_SUBJECT = VF.createIRI("urn:lmdb:replay-lifecycle:first-subject");
	private static final IRI SECOND_SUBJECT = VF.createIRI("urn:lmdb:replay-lifecycle:second-subject");
	private static final IRI FIRST_PREDICATE = VF.createIRI("urn:lmdb:replay-lifecycle:first-predicate");
	private static final IRI SECOND_PREDICATE = VF.createIRI("urn:lmdb:replay-lifecycle:second-predicate");
	private static final IRI GROWTH_PREDICATE = VF.createIRI("urn:lmdb:replay-lifecycle:growth-predicate");
	private static final long INITIAL_MAP_SIZE = 4096L * 10L;
	private static final int PARALLEL_SORT_INPUT_ROWS = 10_000;

	@Test
	@Timeout(value = 30, unit = TimeUnit.SECONDS)
	void unconsumedSnapshotResultsShareOneReplacementGeneration(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = newStore(dataDirectory);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			try (SailConnection seed = store.getConnection()) {
				seed.begin(IsolationLevels.SNAPSHOT);
				seed.addStatement(FIRST_SUBJECT, FIRST_PREDICATE, VF.createLiteral("before-first"));
				seed.addStatement(SECOND_SUBJECT, SECOND_PREDICATE, VF.createLiteral("before-second"));
				seed.commit();
			}

			TripleStore tripleStore = tripleStoreOf(store);
			long initialMapSize = mapSize(tripleStore);
			try (RepositoryConnection reader = repository.getConnection()) {
				reader.begin(IsolationLevels.SNAPSHOT);
				TupleQueryResult first = reader.prepareTupleQuery(selectValues(FIRST_SUBJECT, FIRST_PREDICATE))
						.evaluate();
				TupleQueryResult second = reader.prepareTupleQuery(selectValues(SECOND_SUBJECT, SECOND_PREDICATE))
						.evaluate();
				try (first; second) {
					try (SailConnection writer = store.getConnection()) {
						writer.begin(IsolationLevels.SNAPSHOT);
						addGrowthStatements(writer);
						writer.addStatement(FIRST_SUBJECT, FIRST_PREDICATE, VF.createLiteral("after-growth-first"));
						writer.addStatement(SECOND_SUBJECT, SECOND_PREDICATE, VF.createLiteral("after-growth-second"));
						writer.commit();
					}
					assertTrue(mapSize(tripleStore) > initialMapSize,
							"the writer must force real TripleStore growth with both results still unconsumed");

					assertThat(readValues(first)).containsExactlyInAnyOrder("before-first", "after-growth-first");
					long replacementMapSize = mapSize(tripleStore);

					try (SailConnection laterWriter = store.getConnection()) {
						laterWriter.begin(IsolationLevels.SNAPSHOT);
						laterWriter.addStatement(SECOND_SUBJECT, SECOND_PREDICATE,
								VF.createLiteral("after-replay-second"));
						laterWriter.commit();
					}
					assertEquals(replacementMapSize, mapSize(tripleStore),
							"the intervening publication must not start another map generation");

					assertThat(readValues(second)).containsExactlyInAnyOrder("before-second", "after-growth-second");
				}
				reader.rollback();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 30, unit = TimeUnit.SECONDS)
	void serializableReplayRetainsObservationForPrepareValidation(@TempDir Path dataDirectory) throws Exception {
		LmdbStore store = newStore(dataDirectory);
		store.init();
		IRI observedSubject = VF.createIRI("urn:lmdb:replay-lifecycle:observed-subject");
		IRI localWriteSubject = VF.createIRI("urn:lmdb:replay-lifecycle:local-write-subject");
		IRI localWritePredicate = VF.createIRI("urn:lmdb:replay-lifecycle:local-write-predicate");
		try {
			try (SailConnection seed = store.getConnection()) {
				seed.begin(IsolationLevels.SNAPSHOT);
				seed.addStatement(observedSubject, FIRST_PREDICATE, VF.createLiteral("seed"));
				seed.commit();
			}

			TripleStore tripleStore = tripleStoreOf(store);
			long initialMapSize = mapSize(tripleStore);
			try (SailConnection reader = store.getConnection()) {
				reader.begin(IsolationLevels.SERIALIZABLE);
				try (CloseableIteration<? extends Statement> results = reader.getStatements(observedSubject,
						FIRST_PREDICATE, null, false)) {
					try (SailConnection growthWriter = store.getConnection()) {
						growthWriter.begin(IsolationLevels.SNAPSHOT);
						addGrowthStatements(growthWriter);
						growthWriter.commit();
					}
					assertTrue(mapSize(tripleStore) > initialMapSize,
							"the unobserved SERIALIZABLE result must span actual TripleStore growth");

					assertTrue(results.hasNext(), "the replayed statement pattern must find its seeded row");
					assertEquals("seed", results.next().getObject().stringValue());
					assertFalse(results.hasNext());
				}

				reader.addStatement(localWriteSubject, localWritePredicate, VF.createLiteral("reader-write"));
				try (SailConnection conflictingWriter = store.getConnection()) {
					conflictingWriter.begin(IsolationLevels.SNAPSHOT);
					conflictingWriter.addStatement(observedSubject, FIRST_PREDICATE,
							VF.createLiteral("concurrent-write"));
					conflictingWriter.commit();
				}

				assertThrows(SailConflictException.class, () -> {
					reader.prepare();
					reader.commit();
				}, "replay must preserve the SERIALIZABLE read pattern for prepare-time validation");
				if (reader.isActive()) {
					reader.rollback();
				}
			}
		} finally {
			store.shutDown();
		}
	}

	@Test
	@Timeout(value = 45, unit = TimeUnit.SECONDS)
	void activeSnapshotSortReplaysAfterGracefulGrowthBeforeFirstResultEscapes(@TempDir Path dataDirectory)
			throws Exception {
		String functionIri = "urn:lmdb:replay-lifecycle:sort-barrier:" + UUID.randomUUID();
		SortReplayBarrierFunction function = new SortReplayBarrierFunction(functionIri);
		FunctionRegistry functionRegistry = FunctionRegistry.getInstance();
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), new LmdbStoreConfig("spoc,posc")
				.setForceSync(true)
				.setTripleDBSize(INITIAL_MAP_SIZE)
				.setValueDBSize(64L * 1024L * 1024L)
				.setMapGrowthReadDrainTimeoutMillis(10_000)
				.setAutoGrow(true));
		SailRepository repository = new SailRepository(store);
		ExecutorService executor = Executors.newFixedThreadPool(2);
		try {
			functionRegistry.add(function);
			repository.init();
			try (SailConnection seed = store.getConnection()) {
				seed.begin(IsolationLevels.SNAPSHOT);
				seed.addStatement(FIRST_SUBJECT, FIRST_PREDICATE, VF.createLiteral("a-before"));
				seed.addStatement(FIRST_SUBJECT, FIRST_PREDICATE, VF.createLiteral("b-before"));
				seed.commit();
			}

			LmdbSailStore backingStore = store.getBackingStore();
			TripleStore tripleStore = tripleStoreOf(store);
			long initialMapSize = mapSize(tripleStore);
			MapGrowthMetrics.Snapshot before = backingStore.growthMetricsSnapshot();
			assertFalse(backingStore.growthAdmissionClosed(), "the store must start outside a growth episode");
			Future<List<String>> query = executor.submit(() -> {
				try (RepositoryConnection reader = repository.getConnection()) {
					reader.begin(IsolationLevels.SNAPSHOT);
					TupleQuery tupleQuery = reader.prepareTupleQuery(QueryLanguage.SPARQL,
							"SELECT ?value WHERE { <" + FIRST_SUBJECT.stringValue() + "> <"
									+ FIRST_PREDICATE.stringValue() + "> ?value } ORDER BY <" + functionIri
									+ ">(?value)");
					List<String> values = new ArrayList<>();
					try (TupleQueryResult results = tupleQuery.evaluate()) {
						while (results.hasNext()) {
							values.add(results.next().getValue("value").stringValue());
						}
					}
					reader.commit();
					return values;
				}
			});

			assertTrue(function.awaitFirstInvocation(), "ORDER BY must block while the result is still unobserved");
			Future<?> writer = executor.submit(() -> {
				try (SailConnection growthWriter = store.getConnection()) {
					growthWriter.begin(IsolationLevels.SNAPSHOT);
					addGrowthStatements(growthWriter);
					growthWriter.addStatement(FIRST_SUBJECT, FIRST_PREDICATE, VF.createLiteral("z-after"));
					growthWriter.commit();
				}
				return null;
			});
			awaitStartedGrowthAdmissionClosure(backingStore, before, writer);
			awaitReplayAccepted(backingStore, before, writer);
			function.releaseFirstInvocation();

			writer.get(20, TimeUnit.SECONDS);
			List<String> values = query.get(20, TimeUnit.SECONDS);
			MapGrowthMetrics.Snapshot after = backingStore.growthMetricsSnapshot();
			assertTrue(mapSize(tripleStore) > initialMapSize, "the writer must complete real TripleStore map growth");
			assertThat(values).containsExactlyInAnyOrder("a-before", "b-before", "z-after");
			assertEquals(before.replayAccepted() + 1, after.replayAccepted(),
					"the active snapshot sort must be accepted for exactly one whole-transaction replay");
			assertEquals(before.forcedInvalidationEpisodes(), after.forcedInvalidationEpisodes(),
					"the sort must release its old read view before bounded drain fallback");
			assertEquals(before.forcedInvalidatedViews(), after.forcedInvalidatedViews(),
					"graceful replay must not force-invalidate a read view");
			assertTrue(function.invocationCount() > 2,
					"the ORDER BY expression must execute again after publication on the replacement snapshot");
			assertFalse(backingStore.growthAdmissionClosed(), "completed publication must reopen read admission");
		} finally {
			function.releaseFirstInvocation();
			executor.shutdownNow();
			try {
				assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS), "sort and growth workers must terminate");
			} finally {
				functionRegistry.remove(function);
				repository.shutDown();
			}
		}
	}

	@Test
	@Timeout(value = 45, unit = TimeUnit.SECONDS)
	void activePreResultParallelSortStopsOldAttemptAndReplaysAfterGrowth(@TempDir Path dataDirectory)
			throws Exception {
		prestartCommonPoolWorkers();
		String functionIri = "urn:lmdb:replay-lifecycle:cooperative-sort:" + UUID.randomUUID();
		AtomicBoolean growthStarted = new AtomicBoolean();
		AtomicBoolean writerFinished = new AtomicBoolean();
		SortReplayBarrierFunction function = new SortReplayBarrierFunction(functionIri, growthStarted, writerFinished);
		FunctionRegistry functionRegistry = FunctionRegistry.getInstance();
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), new LmdbStoreConfig("spoc,posc")
				.setForceSync(true)
				.setTripleDBSize(INITIAL_MAP_SIZE)
				.setValueDBSize(64L * 1024L * 1024L)
				.setMapGrowthReadDrainTimeoutMillis(5_000)
				.setAutoGrow(true));
		SailRepository repository = new SailRepository(store);
		ExecutorService executor = Executors.newFixedThreadPool(2);
		try {
			functionRegistry.add(function);
			repository.init();
			try (SailConnection seed = store.getConnection()) {
				seed.begin(IsolationLevels.SNAPSHOT);
				for (int i = 0; i < PARALLEL_SORT_INPUT_ROWS; i++) {
					seed.addStatement(VF.createIRI("urn:lmdb:replay-lifecycle:cooperative:" + i), FIRST_PREDICATE,
							VF.createLiteral("value-" + i));
				}
				seed.commit();
			}

			LmdbSailStore backingStore = store.getBackingStore();
			TripleStore tripleStore = tripleStoreOf(store);
			long initialMapSize = mapSize(tripleStore);
			MapGrowthMetrics.Snapshot before = backingStore.growthMetricsSnapshot();
			Future<List<String>> query = executor.submit(() -> {
				try (RepositoryConnection reader = repository.getConnection()) {
					reader.begin(IsolationLevels.SNAPSHOT);
					TupleQuery tupleQuery = reader.prepareTupleQuery(QueryLanguage.SPARQL,
							"SELECT ?value WHERE { ?subject <" + FIRST_PREDICATE.stringValue() + "> ?value } ORDER BY <"
									+ functionIri + ">(?value)");
					List<String> values = new ArrayList<>();
					try (TupleQueryResult results = tupleQuery.evaluate()) {
						while (results.hasNext()) {
							values.add(results.next().getValue("value").stringValue());
						}
					}
					reader.commit();
					return values;
				}
			});

			assertTrue(function.awaitFirstInvocation(), "the sort must block before its first result escapes");
			Future<?> writer = executor.submit(() -> {
				try (SailConnection growthWriter = store.getConnection()) {
					growthWriter.begin(IsolationLevels.SNAPSHOT);
					addGrowthStatements(growthWriter, 50_000);
					growthWriter.addStatement(VF.createIRI("urn:lmdb:replay-lifecycle:cooperative:after-growth"),
							FIRST_PREDICATE, VF.createLiteral("after-growth"));
					growthWriter.commit();
					writerFinished.set(true);
				}
				return null;
			});
			awaitStartedGrowthAdmissionClosure(backingStore, before, writer);
			awaitReplayAccepted(backingStore, before, writer);
			growthStarted.set(true);
			function.releaseFirstInvocation();

			writer.get(20, TimeUnit.SECONDS);
			List<String> values = query.get(20, TimeUnit.SECONDS);
			MapGrowthMetrics.Snapshot after = backingStore.growthMetricsSnapshot();
			assertTrue(mapSize(tripleStore) > initialMapSize, "the writer must complete real TripleStore map growth");
			assertEquals(PARALLEL_SORT_INPUT_ROWS + 1, values.size(),
					"the replacement result must contain the published row exactly once");
			assertTrue(values.contains("after-growth"), "the replayed snapshot must include the growth publication");
			int inFlightComparatorBound = Math.max(8, ForkJoinPool.getCommonPoolParallelism() * 2);
			assertTrue(function.callbacksDuringGrowth() <= inFlightComparatorBound,
					"after one in-flight comparator reaches its checkpoint, only the concurrently active sort workers "
							+ "may finish callbacks before the replacement starts; bound=" + inFlightComparatorBound
							+ ", callbacks=" + function.callbacksDuringGrowth());
			assertEquals(before.forcedInvalidationEpisodes(), after.forcedInvalidationEpisodes(),
					"the parallel sort must complete before the bounded reader invalidation fallback");
			assertEquals(before.forcedInvalidatedViews(), after.forcedInvalidatedViews(),
					"the completed sort must release its active read view without forced invalidation");
			assertEquals(before.replayAccepted() + 1, after.replayAccepted(),
					"the active snapshot sort must be accepted for exactly one whole-transaction replay");
		} finally {
			function.releaseFirstInvocation();
			executor.shutdownNow();
			try {
				assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS), "query and growth workers must terminate");
			} finally {
				functionRegistry.remove(function);
				repository.shutDown();
			}
		}
	}

	@RepeatedTest(20)
	@Timeout(value = 45, unit = TimeUnit.SECONDS)
	void activePreResultAggregateCooperativelyStopsReadingAfterGrowthIsAccepted(@TempDir Path dataDirectory)
			throws Exception {
		String functionIri = "urn:lmdb:replay-lifecycle:cooperative-aggregate:" + UUID.randomUUID();
		AtomicBoolean growthStarted = new AtomicBoolean();
		AtomicBoolean writerFinished = new AtomicBoolean();
		CooperativeFilterFunction function = new CooperativeFilterFunction(functionIri, growthStarted, writerFinished);
		FunctionRegistry functionRegistry = FunctionRegistry.getInstance();
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), new LmdbStoreConfig("spoc,posc")
				.setForceSync(true)
				.setTripleDBSize(INITIAL_MAP_SIZE)
				.setValueDBSize(64L * 1024L * 1024L)
				.setMapGrowthReadDrainTimeoutMillis(5_000)
				.setAutoGrow(true));
		SailRepository repository = new SailRepository(store);
		ExecutorService executor = Executors.newFixedThreadPool(2);
		try {
			functionRegistry.add(function);
			repository.init();
			try (SailConnection seed = store.getConnection()) {
				seed.begin(IsolationLevels.SNAPSHOT);
				for (int i = 0; i < 2_000; i++) {
					seed.addStatement(VF.createIRI("urn:lmdb:replay-lifecycle:aggregate:" + i), FIRST_PREDICATE,
							VF.createLiteral("value-" + i));
				}
				seed.commit();
			}

			LmdbSailStore backingStore = store.getBackingStore();
			TripleStore tripleStore = tripleStoreOf(store);
			long initialMapSize = mapSize(tripleStore);
			MapGrowthMetrics.Snapshot before = backingStore.growthMetricsSnapshot();
			Future<String> query = executor.submit(() -> {
				try (RepositoryConnection reader = repository.getConnection()) {
					reader.begin(IsolationLevels.SNAPSHOT);
					TupleQuery tupleQuery = reader.prepareTupleQuery(QueryLanguage.SPARQL,
							"SELECT (COUNT(?value) AS ?count) WHERE { ?subject <" + FIRST_PREDICATE.stringValue()
									+ "> ?value . FILTER(<" + functionIri + ">(?value)) }");
					String count;
					try (TupleQueryResult results = tupleQuery.evaluate()) {
						assertTrue(results.hasNext());
						count = results.next().getValue("count").stringValue();
					}
					reader.commit();
					return count;
				}
			});

			assertTrue(function.awaitFirstInvocation(), "the aggregate must block before its first result escapes");
			Future<?> writer = executor.submit(() -> {
				try (SailConnection growthWriter = store.getConnection()) {
					growthWriter.begin(IsolationLevels.SNAPSHOT);
					addGrowthStatements(growthWriter);
					growthWriter.addStatement(VF.createIRI("urn:lmdb:replay-lifecycle:aggregate:after-growth"),
							FIRST_PREDICATE, VF.createLiteral("after-growth"));
					growthWriter.commit();
					writerFinished.set(true);
				}
				return null;
			});
			awaitStartedGrowthAdmissionClosure(backingStore, before, writer);
			// Admission closes before replay is asynchronously accepted; count callbacks only after that handoff.
			awaitReplayAccepted(backingStore, before, writer);
			assertTrue(backingStore.growthMetricsSnapshot().replayAccepted() > before.replayAccepted(),
					"the aggregate must be accepted for replay before post-growth callbacks are counted");
			growthStarted.set(true);
			function.releaseFirstInvocation();

			writer.get(20, TimeUnit.SECONDS);
			String count = query.get(20, TimeUnit.SECONDS);
			MapGrowthMetrics.Snapshot after = backingStore.growthMetricsSnapshot();
			assertTrue(mapSize(tripleStore) > initialMapSize, "the writer must complete real TripleStore map growth");
			assertEquals("2001", count, "the replacement aggregate must include the published row once");
			assertTrue(function.nestedReadCompletedAfterGrowth(),
					"the custom function's nested read must return naturally before replay is checked");
			assertTrue(function.callbacksAfterGrowthStartedBeforeWriterFinished() <= 1,
					"the old aggregate must stop its next input scan at a cooperative safepoint");
			assertEquals(before.forcedInvalidationEpisodes(), after.forcedInvalidationEpisodes(),
					"cooperative aggregate retirement must finish before bounded reader invalidation");
			assertEquals(before.forcedInvalidatedViews(), after.forcedInvalidatedViews(),
					"the aggregate must release its old read view cooperatively");
			assertEquals(before.replayAccepted() + 1, after.replayAccepted(),
					"the aggregate must be accepted for exactly one whole-transaction replay");
		} finally {
			function.releaseFirstInvocation();
			executor.shutdownNow();
			try {
				assertTrue(executor.awaitTermination(5, TimeUnit.SECONDS),
						"aggregate and growth workers must terminate");
			} finally {
				functionRegistry.remove(function);
				repository.shutDown();
			}
		}
	}

	private static LmdbStore newStore(Path dataDirectory) {
		return new LmdbStore(dataDirectory.toFile(), new LmdbStoreConfig("spoc,posc")
				.setForceSync(true)
				.setTripleDBSize(INITIAL_MAP_SIZE)
				.setMapGrowthReadDrainTimeoutMillis(150)
				.setAutoGrow(true));
	}

	private static void addGrowthStatements(SailConnection writer) throws Exception {
		addGrowthStatements(writer, 10_000);
	}

	private static void addGrowthStatements(SailConnection writer, int count) throws Exception {
		for (int i = 0; i < count; i++) {
			writer.addStatement(VF.createIRI("urn:lmdb:replay-lifecycle:growth:" + i), GROWTH_PREDICATE,
					VF.createLiteral("filler"));
		}
	}

	private static void awaitStartedGrowthAdmissionClosure(LmdbSailStore backingStore,
			MapGrowthMetrics.Snapshot before, Future<?> writer) throws Exception {
		long deadlineNanos = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
		while (true) {
			MapGrowthMetrics.Snapshot current = backingStore.growthMetricsSnapshot();
			if (current.growthEpisodes() > before.growthEpisodes() && backingStore.growthAdmissionClosed()) {
				return;
			}
			if (writer.isDone()) {
				writer.get();
				throw new AssertionError("the writer completed without starting a growth episode");
			}
			if (System.nanoTime() >= deadlineNanos) {
				throw new AssertionError("timed out waiting for a started growth episode with admission closed");
			}
			Thread.yield();
		}
	}

	private static void awaitReplayAccepted(LmdbSailStore backingStore, MapGrowthMetrics.Snapshot before,
			Future<?> writer) throws Exception {
		long deadlineNanos = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
		while (backingStore.growthMetricsSnapshot().replayAccepted() == before.replayAccepted()) {
			if (writer.isDone()) {
				writer.get();
				throw new AssertionError("the writer completed before the query replay was accepted");
			}
			if (System.nanoTime() >= deadlineNanos) {
				throw new AssertionError("timed out waiting for the query replay to be accepted");
			}
			Thread.yield();
		}
	}

	private static String selectValues(IRI subject, IRI predicate) {
		return "SELECT ?value WHERE { <" + subject.stringValue() + "> <" + predicate.stringValue() + "> ?value }";
	}

	private static List<String> readValues(TupleQueryResult result) throws Exception {
		List<String> values = new ArrayList<>();
		while (result.hasNext()) {
			BindingSet bindings = result.next();
			values.add(bindings.getValue("value").stringValue());
		}
		return values;
	}

	private static TripleStore tripleStoreOf(LmdbStore store) throws ReflectiveOperationException {
		Field field = LmdbSailStore.class.getDeclaredField("tripleStore");
		field.setAccessible(true);
		return (TripleStore) field.get(store.getBackingStore());
	}

	private static long mapSize(TripleStore tripleStore) throws ReflectiveOperationException {
		Field field = TripleStore.class.getDeclaredField("mapSize");
		field.setAccessible(true);
		return field.getLong(tripleStore);
	}

	private static void prestartCommonPoolWorkers() throws InterruptedException {
		int workerCount = Math.min(8, ForkJoinPool.getCommonPoolParallelism());
		CountDownLatch workersStarted = new CountDownLatch(workerCount);
		CountDownLatch releaseWorkers = new CountDownLatch(1);
		List<ForkJoinTask<?>> workers = new ArrayList<>(workerCount);
		for (int i = 0; i < workerCount; i++) {
			workers.add(ForkJoinPool.commonPool().submit(() -> {
				workersStarted.countDown();
				try {
					releaseWorkers.await();
				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
				}
			}));
		}
		assertTrue(workersStarted.await(10, TimeUnit.SECONDS), "the common-pool sort workers must be prestarted");
		releaseWorkers.countDown();
		workers.forEach(ForkJoinTask::join);
	}

	private static final class SortReplayBarrierFunction implements Function {
		private final String functionIri;
		private final AtomicBoolean growthStarted;
		private final AtomicBoolean writerFinished;
		private final CountDownLatch firstInvocation = new CountDownLatch(1);
		private final CountDownLatch releaseFirstInvocation = new CountDownLatch(1);
		private final AtomicInteger invocationCount = new AtomicInteger();
		private final AtomicInteger callbacksDuringGrowth = new AtomicInteger();

		private SortReplayBarrierFunction(String functionIri) {
			this(functionIri, new AtomicBoolean(), new AtomicBoolean());
		}

		private SortReplayBarrierFunction(String functionIri, AtomicBoolean growthStarted,
				AtomicBoolean writerFinished) {
			this.functionIri = functionIri;
			this.growthStarted = growthStarted;
			this.writerFinished = writerFinished;
		}

		@Override
		public String getURI() {
			return functionIri;
		}

		@Override
		public Value evaluate(ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException {
			return valueFactory.createLiteral(true);
		}

		@Override
		public Value evaluate(TripleSource tripleSource, Value... args) throws ValueExprEvaluationException {
			int invocation = invocationCount.incrementAndGet();
			if (growthStarted.get() && !writerFinished.get()) {
				callbacksDuringGrowth.incrementAndGet();
			}
			if (invocation == 1) {
				firstInvocation.countDown();
				try {
					if (!releaseFirstInvocation.await(20, TimeUnit.SECONDS)) {
						throw new ValueExprEvaluationException(
								"Timed out waiting to release the ORDER BY replay barrier");
					}
				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
					throw new ValueExprEvaluationException("Interrupted at the ORDER BY replay barrier", e);
				}
			}
			return tripleSource.getValueFactory().createLiteral(true);
		}

		private boolean awaitFirstInvocation() throws InterruptedException {
			return firstInvocation.await(10, TimeUnit.SECONDS);
		}

		private int invocationCount() {
			return invocationCount.get();
		}

		private int callbacksDuringGrowth() {
			return callbacksDuringGrowth.get();
		}

		private void releaseFirstInvocation() {
			releaseFirstInvocation.countDown();
		}
	}

	private static final class CooperativeFilterFunction implements Function {
		private final String functionIri;
		private final AtomicBoolean growthStarted;
		private final AtomicBoolean writerFinished;
		private final CountDownLatch firstInvocation = new CountDownLatch(1);
		private final CountDownLatch releaseFirstInvocation = new CountDownLatch(1);
		private final AtomicInteger callbacksAfterGrowthStarted = new AtomicInteger();
		private final AtomicBoolean nestedReadCompletedAfterGrowth = new AtomicBoolean();

		private CooperativeFilterFunction(String functionIri, AtomicBoolean growthStarted,
				AtomicBoolean writerFinished) {
			this.functionIri = functionIri;
			this.growthStarted = growthStarted;
			this.writerFinished = writerFinished;
		}

		@Override
		public String getURI() {
			return functionIri;
		}

		@Override
		public Value evaluate(ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException {
			return valueFactory.createLiteral(true);
		}

		@Override
		public Value evaluate(TripleSource tripleSource, Value... args) throws ValueExprEvaluationException {
			boolean releasedGrowthBarrier = false;
			if (firstInvocation.getCount() > 0L) {
				firstInvocation.countDown();
				try {
					if (!releaseFirstInvocation.await(20, TimeUnit.SECONDS)) {
						throw new ValueExprEvaluationException(
								"Timed out waiting to release the cooperative aggregate barrier");
					}
				} catch (InterruptedException e) {
					Thread.currentThread().interrupt();
					throw new ValueExprEvaluationException("Interrupted at the cooperative aggregate barrier", e);
				}
				releasedGrowthBarrier = growthStarted.get();
			} else if (growthStarted.get() && !writerFinished.get()) {
				callbacksAfterGrowthStarted.incrementAndGet();
			}
			if (releasedGrowthBarrier) {
				try (CloseableIteration<? extends Statement> nestedRead = tripleSource.getStatements(null,
						FIRST_PREDICATE, null)) {
					if (nestedRead.hasNext()) {
						nestedRead.next();
					}
				}
				nestedReadCompletedAfterGrowth.set(true);
			}
			return tripleSource.getValueFactory().createLiteral(true);
		}

		private boolean awaitFirstInvocation() throws InterruptedException {
			return firstInvocation.await(10, TimeUnit.SECONDS);
		}

		private int callbacksAfterGrowthStartedBeforeWriterFinished() {
			return callbacksAfterGrowthStarted.get();
		}

		private boolean nestedReadCompletedAfterGrowth() {
			return nestedReadCompletedAfterGrowth.get();
		}

		private void releaseFirstInvocation() {
			releaseFirstInvocation.countDown();
		}
	}
}
