/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * LMDB end-to-end guards for the {@code QueryModelNormalizerOptimizer} VALUES-through-scoped-BIND push; the LMDB
 * pipeline runs the same normalizer before the packed planner consumes the pushed shape.
 */
public class LmdbScopedBindValuesPushSoundnessTest {

	private static final String PREFIX = "PREFIX : <http://ex/>\n";
	private static final String ONE = "\"1\"^^<http://www.w3.org/2001/XMLSchema#integer>";

	@TempDir
	File dataDir;

	private SailRepository repository;

	@BeforeEach
	public void setUp() {
		repository = new SailRepository(new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc")));
		repository.init();
	}

	@AfterEach
	public void tearDown() {
		repository.shutDown();
	}

	private void load(String trig) throws Exception {
		try (SailRepositoryConnection conn = repository.getConnection()) {
			conn.add(new StringReader("@prefix : <http://ex/> .\n" + trig), "http://ex/", RDFFormat.TRIG);
		}
	}

	private List<String> rows(String query, String... vars) {
		try (SailRepositoryConnection conn = repository.getConnection()) {
			TupleQuery tupleQuery = conn.prepareTupleQuery(PREFIX + query);
			List<String> result = new ArrayList<>();
			try (TupleQueryResult res = tupleQuery.evaluate()) {
				for (BindingSet bs : res) {
					StringBuilder sb = new StringBuilder();
					for (String var : vars) {
						sb.append(var).append('=').append(bs.getValue(var)).append(' ');
					}
					result.add(sb.toString().trim());
				}
			}
			return result.stream().sorted().collect(Collectors.toList());
		}
	}

	// The negative shapes (a Filter observing !BOUND / NOT EXISTS of a pushed variable that is only possibly bound)
	// need a VALUES ... UNDEF row inside the group. Any LMDB query with VALUES ... UNDEF currently fails with an NPE
	// in LmdbPipelinePlanCache (review 3.9, owned by the plan-cache work package), so those shapes are covered on
	// MemoryStore (ScopedBindValuesPushSoundnessTest) and at algebra level (QueryModelNormalizerScopedBindPushTest)
	// until that defect is fixed.

	@Test
	public void valuesPushedThroughScopedBindWhenInnerPatternAssuresTheVariableKeepsResults() throws Exception {
		load(":g { :a :p :o1 . :b :p :o2 . :c :p :o3 . :a :q :c . }\n");
		String query = "SELECT ?x ?o ?one WHERE {\n"
				+ "  VALUES ?x { :a :b }\n"
				+ "  { GRAPH :g { ?x :p ?o FILTER NOT EXISTS { ?x :q ?z } } BIND(1 AS ?one) }\n"
				+ "}";
		assertEquals(List.of("x=http://ex/b o=http://ex/o2 one=" + ONE), rows(query, "x", "o", "one"));
	}
}
