/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.rdf4j.sail.lmdb.TxnManager.Txn;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Gate A milestone A4: the answers served out of the node-predicate projection are the answers the authoritative disk
 * trees produce.
 * <p>
 * The claim discharged here, stated precisely: for every node in the fixture, every context selection, and both the
 * explicit and inferred selections, restricted to the <em>outgoing</em> planes, the multiset of statements the node
 * iterator produces equals the multiset the disk trees produce for the same pattern. The restriction to outgoing planes
 * is deliberate — incoming behaviour does not exist yet, so a claim covering all four planes could not be discharged
 * and must not be written as though it were.
 * <p>
 * The fixture is built deliberately rather than randomly because several branches are reachable only from specific
 * shapes: a one-predicate node is the only way to exercise the iterator's reuse of an otherwise-idle two-element
 * buffer, and a node with more than {@code CHUNK_EDGES} predicates is the only way to exercise chunk refill and buffer
 * growth. The comparison runs at four lifecycle points because the structure is materially different at each.
 */
class LmdbNodePredicateEnumerationParityTest {

	/** Must exceed LmdbDirectNodeIterator.CHUNK_EDGES (256) so the predicate row spans several chunks. */
	private static final int WIDE_NODE_PREDICATES = 300;

	private TripleStore tripleStore;
	private LmdbDirectAdjacencyStore store;

	private static long uri(long payload) {
		return ValueIds.createId(ValueIds.T_URI, payload);
	}

	private static final long S_ONE_PREDICATE = uri(1);
	private static final long S_WIDE = uri(2);
	private static final long S_MIXED = uri(3);
	private static final long S_INFERRED_ONLY = uri(4);
	private static final long S_TOMBSTONED = uri(5);
	private static final long S_OVERLAY_ONLY = uri(6);
	private static final long S_ABSENT = uri(7);

	private static final long P_ONLY = uri(1000);
	private static final long P_A = uri(1001);
	private static final long P_B = uri(1002);
	private static final long P_INFERRED = uri(1003);
	private static final long P_TOMBSTONED = uri(1004);
	/** First seen only after the base was built, so its ordinal is appended rather than sorted in. */
	private static final long P_POST_BASE = uri(500);

	private static final long O1 = uri(2000);
	private static final long O2 = uri(2001);
	private static final long O_INLINE = ValueIds.createId(ValueIds.T_INTEGER, 42);

	private static final long G1 = uri(9001);
	private static final long G2 = uri(9002);

	private static final long[] NODES = { S_ONE_PREDICATE, S_WIDE, S_MIXED, S_INFERRED_ONLY, S_TOMBSTONED,
			S_OVERLAY_ONLY, S_ABSENT };
	/** -1 is "any context"; 0 is the default graph; G1/G2 are named graphs; G_ABSENT is in no statement. */
	private static final long[] CONTEXTS = { -1, 0, G1, G2, uri(9999) };

	private File dataDir;

	@BeforeEach
	void setUp(@TempDir File dataDir) throws Exception {
		this.dataDir = dataDir;
		openStore(false);
	}

	/** Opens the store with the outgoing projection on and the incoming planes gated by {@code incoming}. */
	private void openStore(boolean incoming) throws Exception {
		if (store != null) {
			store.close();
			store = null;
		}
		if (tripleStore != null) {
			tripleStore.close();
		}
		tripleStore = new TripleStore(dataDir, new LmdbStoreConfig("spoc,posc"), null);
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setDirectAdjacencyMode(DirectAdjacencyMode.PREFER)
				.setDirectAdjacencyMaxBytes(1L << 30);
		LmdbDirectAdjacencyOptions options = LmdbDirectAdjacencyOptions.resolve(config, 8L << 30, name -> {
			if (LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_PROPERTY.equals(name)) {
				return "true";
			}
			if (LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_INCOMING_PROPERTY.equals(name)) {
				return String.valueOf(incoming);
			}
			return null;
		}, 4);
		System.setProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY, "true");
		store = new LmdbDirectAdjacencyStore(tripleStore, null, new AtomicBoolean(false), options);
		tripleStore.setDirectAdjacencyCommitHooks(store.commitListener(), store.newCommitDelta());
	}

	@AfterEach
	void tearDown() throws Exception {
		System.clearProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY);
		if (store != null) {
			store.close();
		}
		if (tripleStore != null) {
			tripleStore.close();
		}
	}

	// ------------------------------------------------------------------
	// fixture
	// ------------------------------------------------------------------

	private interface Commit {
		void apply() throws IOException;
	}

	private void commit(Commit body) throws IOException {
		tripleStore.startTransaction();
		body.apply();
		tripleStore.commit();
		store.applyCommitted(tripleStore.drainDirectAdjacencyCommitDelta());
		store.pauseApplierForTest(false);
	}

	private void add(long s, long p, long o, long c, boolean explicit) throws IOException {
		tripleStore.storeTriple(s, p, o, c, explicit);
	}

	private void remove(long s, long p, long o, long c, boolean explicit) throws IOException {
		tripleStore.removeTriplesByContext(s, p, o, c, explicit, removed -> {
		});
	}

	private void loadBaseFixture() throws IOException {
		commit(() -> {
			// exactly one predicate: the iterator's two-element buffer reuse
			add(S_ONE_PREDICATE, P_ONLY, O1, 0, true);

			// more than one chunk of predicates: chunk refill and buffer growth
			for (int i = 0; i < WIDE_NODE_PREDICATES; i++) {
				add(S_WIDE, uri(10_000 + i), O1, 0, true);
			}

			// named graphs, the default graph, an inlined literal object, and multiplicity across graphs
			add(S_MIXED, P_A, O1, 0, true);
			add(S_MIXED, P_A, O1, G1, true);
			add(S_MIXED, P_A, O2, G2, true);
			add(S_MIXED, P_B, O_INLINE, 0, true);
			add(S_MIXED, P_B, O2, G1, true);
			// the same node also carries inferred statements, which live in a different plane
			add(S_MIXED, P_INFERRED, O1, 0, false);

			// a node that exists only in the inferred plane
			add(S_INFERRED_ONLY, P_INFERRED, O2, G1, false);

			// a node whose only predicate is removed later
			add(S_TOMBSTONED, P_TOMBSTONED, O1, 0, true);
		});
	}

	// ------------------------------------------------------------------
	// differential comparison
	// ------------------------------------------------------------------

	private List<long[]> fromAdjacency(Txn txn, long node, long context, boolean explicit) throws IOException {
		try (LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			RecordIterator it = store.tryOpen(view, txn, node, -1, -1, context, explicit);
			if (it == null) {
				return null;
			}
			return drain(it);
		}
	}

	private List<long[]> fromDiskTrees(Txn txn, long node, long context, boolean explicit) throws IOException {
		try (RecordIterator it = tripleStore.getTriples(txn, node, -1, -1, context, explicit)) {
			return drain(it);
		}
	}

	private static List<long[]> drain(RecordIterator it) throws IOException {
		List<long[]> rows = new ArrayList<>();
		try {
			long[] quad;
			while ((quad = it.next()) != null) {
				rows.add(new long[] { quad[TripleIndex.SUBJ_IDX], quad[TripleIndex.PRED_IDX],
						quad[TripleIndex.OBJ_IDX], Math.max(0, quad[TripleIndex.CONTEXT_IDX]) });
			}
		} finally {
			it.close();
		}
		rows.sort(ROW_ORDER);
		return rows;
	}

	private static final Comparator<long[]> ROW_ORDER = (a, b) -> {
		for (int i = 0; i < 4; i++) {
			int comparison = Long.compareUnsigned(a[i], b[i]);
			if (comparison != 0) {
				return comparison;
			}
		}
		return 0;
	};

	/**
	 * Compares every node, context and explicit/inferred selection. A decline is not a failure — LMDB is always the
	 * authority — but a served answer that differs from the disk trees is, and so is a served answer that is missing
	 * rows the disk trees have.
	 *
	 * @return how many of the compared cells the adjacency path actually served, so a caller can assert that the
	 *         comparison was not vacuous.
	 */
	private int assertParity(String lifecyclePoint) throws IOException {
		int served = 0;
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			for (long node : NODES) {
				for (long context : CONTEXTS) {
					for (boolean explicit : new boolean[] { true, false }) {
						List<long[]> adjacency = fromAdjacency(txn, node, context, explicit);
						if (adjacency == null) {
							continue;
						}
						served++;
						List<long[]> disk = fromDiskTrees(txn, node, context, explicit);
						assertThat(adjacency)
								.as("%s: node=%s context=%s explicit=%s", lifecyclePoint,
										Long.toUnsignedString(node), Long.toUnsignedString(context), explicit)
								.usingElementComparator(ROW_ORDER)
								.containsExactlyElementsOf(disk);
					}
				}
			}
		}
		return served;
	}

	// ------------------------------------------------------------------
	// the four lifecycle points
	// ------------------------------------------------------------------

	@Test
	void answersMatchTheDiskTreesAtEveryLifecyclePoint() throws Exception {
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		assertThat(store.publishedStateForTest().base().nodePredicateIndexOrNull()).isNotNull();

		// 1. Freshly built base, no overlays: answers come straight out of the projection.
		assertThat(store.publishedStateForTest().overlays()).isNull();
		int servedAtBase = assertParity("freshly built base");
		assertThat(servedAtBase).as("the comparison must not be vacuous").isPositive();

		// 2. Live overlay generations: the iterator merges base rows with every applicable generation.
		commit(() -> add(S_OVERLAY_ONLY, P_A, O1, G2, true));
		commit(() -> add(S_MIXED, P_POST_BASE, O2, 0, true));
		commit(() -> remove(S_TOMBSTONED, P_TOMBSTONED, O1, 0, true));
		commit(() -> add(S_ONE_PREDICATE, P_ONLY, O2, G1, true));
		assertThat(store.publishedStateForTest().overlays()).as("overlays must still be live").isNotNull();
		assertThat(store.publishedStateForTest().overlays().generationCount())
				.as("the merge inside the iterator needs more than one generation to be exercised")
				.isGreaterThan(1);
		assertThat(assertParity("live overlays")).isPositive();

		// 3. Forced fold-down: the projection is rewritten, including a predicate first seen after the base.
		foldDown();
		assertThat(store.publishedStateForTest().overlays()).isNull();
		assertThat(assertParity("after fold-down")).isPositive();
		assertThat(store.publishedStateForTest().base().predicateCatalog().ordinalForRaw(P_POST_BASE))
				.as("the post-base predicate must have been folded into the catalog")
				.isNotNegative();

		// 4. A fold-down whose changes are all object/context changes under predicates that were already present.
		// This is the no-change fast path: the projection is shared rather than rewritten, so a bug there would show
		// up as a stale row rather than as a crash.
		commit(() -> add(S_MIXED, P_A, uri(3000), G1, true));
		commit(() -> remove(S_MIXED, P_A, O1, G1, true));
		commit(() -> add(S_MIXED, P_B, uri(3001), 0, true));
		foldDown();
		assertThat(store.publishedStateForTest().overlays()).isNull();
		assertThat(assertParity("after an object-only fold-down")).isPositive();
	}

	/**
	 * Folds every live overlay generation into a new base. Automatic consolidation only fires when the generation count
	 * crosses the configured threshold, and it needs at least two generations to have anything to merge, so the
	 * fold-down is requested explicitly rather than inferred from a commit count.
	 */
	private void foldDown() throws IOException {
		if (store.publishedStateForTest().overlays() == null) {
			return;
		}
		if (store.publishedStateForTest().overlays().generationCount() < 2) {
			commit(() -> add(S_ABSENT, P_A, uri(4999), 0, true));
		}
		store.consolidateNowForTest();
		assertThat(store.publishedStateForTest().overlays())
				.as("the fold-down must have absorbed every generation")
				.isNull();
	}

	/**
	 * The wide node is the reason the iterator chunks its predicate row instead of materialising it. A regression that
	 * silently truncated at the chunk boundary would still pass every other cell in this class, so it is asserted
	 * explicitly rather than left to the sweep.
	 */
	@Test
	void aNodeWiderThanOneChunkEnumeratesEveryPredicate() throws Exception {
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			List<long[]> adjacency = fromAdjacency(txn, S_WIDE, -1, true);
			assertThat(adjacency).as("the wide node must be served, not declined").isNotNull();
			assertThat(adjacency).hasSize(WIDE_NODE_PREDICATES);
			long[] predicates = adjacency.stream().mapToLong(row -> row[1]).distinct().toArray();
			assertThat(predicates).hasSize(WIDE_NODE_PREDICATES);
			assertThat(adjacency).usingElementComparator(ROW_ORDER)
					.containsExactlyElementsOf(fromDiskTrees(txn, S_WIDE, -1, true));
		}
	}

	/**
	 * A one-predicate node takes the branch that reuses the legacy two-long entry buffer rather than allocating a chunk
	 * array. It is the overwhelmingly common shape, so a fault there would be a fault almost everywhere.
	 */
	@Test
	void aOnePredicateNodeUsesTheReusedBufferAndStillAgrees() throws Exception {
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			List<long[]> adjacency = fromAdjacency(txn, S_ONE_PREDICATE, -1, true);
			assertThat(adjacency).isNotNull().hasSize(1);
			assertThat(adjacency).usingElementComparator(ROW_ORDER)
					.containsExactlyElementsOf(fromDiskTrees(txn, S_ONE_PREDICATE, -1, true));
		}
	}

	/**
	 * Gate D milestone D1: with the incoming switch on, the reverse direction {@code ?s ?p <o>} is served and agrees
	 * with the disk trees, including for an inlined literal object.
	 * <p>
	 * The inlined object is the interesting case and the plan predicted it would have to stay declining. It does not: a
	 * paged base has no separate inline incoming structure, so its incoming planes are keyed by the raw object id
	 * whether or not that id is inlined, and the projection covers them uniformly. See {@code Surprises & Discoveries}.
	 */
	@Test
	void incomingPlanesAgreeWithTheDiskTreesWhenEnabled() throws Exception {
		openStore(true);
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		LmdbNodePredicateIndex projection = store.publishedStateForTest().base().nodePredicateIndexOrNull();
		assertThat(projection).isNotNull();
		assertThat(projection.supportsPlane(LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT)).isTrue();
		assertThat(projection.supportsPlane(LmdbAdjacencyPlane.PLANE_INCOMING_INFERRED)).isTrue();

		int served = 0;
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			for (long object : new long[] { O1, O2, O_INLINE, uri(4242) }) {
				for (long context : CONTEXTS) {
					for (boolean explicit : new boolean[] { true, false }) {
						List<long[]> adjacency = fromAdjacencyIncoming(txn, object, context, explicit);
						if (adjacency == null) {
							continue;
						}
						served++;
						assertThat(adjacency)
								.as("object=%s context=%s explicit=%s", Long.toUnsignedString(object),
										Long.toUnsignedString(context), explicit)
								.usingElementComparator(ROW_ORDER)
								.containsExactlyElementsOf(fromDiskTreesIncoming(txn, object, context, explicit));
					}
				}
			}
			assertThat(served).as("the incoming comparison must not be vacuous").isPositive();
			assertThat(fromAdjacencyIncoming(txn, O_INLINE, -1, true))
					.as("an inlined literal object must be served, not declined")
					.isNotNull()
					.isNotEmpty();
		}
	}

	/**
	 * With the incoming switch off the incoming planes must cost nothing at all — not merely go unpublished. A plane
	 * outside the mask is skipped before any key-domain cursor, merge pass or page is created, so the whole projection
	 * is strictly smaller than the same fixture with incoming on. The general predicate sweep still serves the reverse
	 * direction from the primary incoming adjacency planes, so disabling this specialization cannot remove adjacency.
	 */
	@Test
	void incomingProjectionCostsNothingWhenDisabledButGeneralTraversalRemains() throws Exception {
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		LmdbNodePredicateIndex outgoingOnly = store.publishedStateForTest().base().nodePredicateIndex();
		assertThat(outgoingOnly.supportsPlane(LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT)).isFalse();
		assertThat(outgoingOnly.rowCount(LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT)).isZero();
		assertThat(outgoingOnly.incidenceCount(LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT)).isZero();
		long outgoingOnlyBytes = store.memoryAccount()
				.chargedBytes(LmdbAdjacencyMemoryAccount.MemoryKind.NODE_PREDICATE_NATIVE);
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			assertThat(fromAdjacencyIncoming(txn, O1, -1, true))
					.as("the universal incoming traversal remains available")
					.usingElementComparator(ROW_ORDER)
					.containsExactlyElementsOf(fromDiskTreesIncoming(txn, O1, -1, true));
		}

		openStore(true);
		assertThat(store.buildNowForTest()).isTrue();
		long withIncomingBytes = store.memoryAccount()
				.chargedBytes(LmdbAdjacencyMemoryAccount.MemoryKind.NODE_PREDICATE_NATIVE);
		assertThat(withIncomingBytes)
				.as("the incoming planes must add real bytes, so their absence is a real saving")
				.isGreaterThan(outgoingOnlyBytes);
	}

	private List<long[]> fromAdjacencyIncoming(Txn txn, long object, long context, boolean explicit)
			throws IOException {
		try (LmdbAdjacencyReadView view = store.acquire(tripleStore.getDataRevision())) {
			RecordIterator it = store.tryOpen(view, txn, -1, -1, object, context, explicit);
			return it == null ? null : drain(it);
		}
	}

	private List<long[]> fromDiskTreesIncoming(Txn txn, long object, long context, boolean explicit)
			throws IOException {
		try (RecordIterator it = tripleStore.getTriples(txn, -1, -1, object, context, explicit)) {
			return drain(it);
		}
	}

	/**
	 * A predicate that exists on a node only outside the requested named graph must not appear in that graph's answer.
	 * The projection records that a predicate exists <em>somewhere</em> on a node, with no memory of which context it
	 * came from, so this is the exact shape a context-blind shortcut would get wrong.
	 */
	@Test
	void aContextRestrictionHidesPredicatesThatExistOnlyElsewhere() throws Exception {
		loadBaseFixture();
		assertThat(store.buildNowForTest()).isTrue();
		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			List<long[]> inG2 = fromAdjacency(txn, S_MIXED, G2, true);
			assertThat(inG2).isNotNull();
			assertThat(inG2).usingElementComparator(ROW_ORDER)
					.containsExactlyElementsOf(fromDiskTrees(txn, S_MIXED, G2, true));
			// P_B exists on S_MIXED, but not in G2.
			assertThat(inG2).allSatisfy(row -> assertThat(row[1]).isEqualTo(P_A));
			// ...while the unrestricted answer has both.
			assertThat(Arrays.stream(fromAdjacency(txn, S_MIXED, -1, true).stream()
					.mapToLong(row -> row[1])
					.distinct()
					.toArray()).boxed().toList()).contains(P_A, P_B);
		}
	}
}
