/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.And;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Exists;
import org.eclipse.rdf4j.query.algebra.Extension;
import org.eclipse.rdf4j.query.algebra.ExtensionElem;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.ListMemberOperator;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.VariableScopeChange;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.impl.MapBindingSet;
import org.junit.jupiter.api.Test;

class LmdbSketchJoinOptimizerTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void reordersJoinSegmentsUsingJoinOrderPlanner() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern third = statementPattern("s3", "p3", "o3");
		QueryRoot root = new QueryRoot(new Join(first, new Join(second, third)));
		PlanningStatistics statistics = PlanningStatistics.withPlan(List.of(third, first, second));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(third, first, second), joinArgs(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void acceptedPlannerOrderIsFinal() {
		BindingSetAssignment boundObjects = values("knownObject", "DX-200", "DX-201");
		StatementPattern guard = new StatementPattern(new Var("s"), new Var("_type", RDF.TYPE),
				new Var("_person", VF.createIRI("urn:Person")));
		StatementPattern lookup = statementPattern("s", "hasKnownObject", "knownObject");
		QueryRoot root = new QueryRoot(new Join(boundObjects, new Join(guard, lookup)));
		PlanningStatistics statistics = PlanningStatistics.withPlan(List.of(boundObjects, guard, lookup));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(boundObjects, guard, lookup), joinArgs(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void keepsPlannerOrderWhenLocalFilterPrefixCandidateIsMoreExpensive() {
		StatementPattern cheapSeed = statementPattern("seed", "type", "seedType");
		StatementPattern connector = new StatementPattern(new Var("entity"),
				new Var("_connectorPredicate", VF.createIRI("urn:connectsTo")),
				new Var("_connectorObject", VF.createIRI("urn:fixedEndpoint")));
		StatementPattern filteredPattern = statementPattern("entity", "score", "score");
		QueryRoot root = new QueryRoot(new Filter(new Join(cheapSeed, new Join(connector, filteredPattern)),
				new Compare(new Var("score"), new ValueConstant(VF.createLiteral(5)), Compare.CompareOp.GT)));
		PlanningStatistics statistics = PlanningStatistics
				.withMoreExpensiveLocalFilterPrefixPlan(List.of(cheapSeed, connector, filteredPattern));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(cheapSeed, connector, filteredPattern), statementPatterns(root.getArg()),
				"A valid local-filter-prefix candidate must not replace a cheaper planner-selected order");
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void keepsFiniteAnchorOrderWhenLocalFilterPrefixCandidateIsMoreExpensive() {
		BindingSetAssignment boundObjects = values("knownObject", "DX-200", "DX-201");
		StatementPattern lookup = statementPattern("entity", "hasKnownObject", "knownObject");
		StatementPattern connector = new StatementPattern(new Var("entity"),
				new Var("_connectorPredicate", VF.createIRI("urn:connectsTo")),
				new Var("_connectorObject", VF.createIRI("urn:fixedEndpoint")));
		StatementPattern filteredPattern = statementPattern("entity", "score", "score");
		QueryRoot root = new QueryRoot(new Filter(
				new Join(boundObjects, new Join(lookup, new Join(connector, filteredPattern))),
				new Compare(new Var("score"), new ValueConstant(VF.createLiteral(5)), Compare.CompareOp.GT)));
		PlanningStatistics statistics = PlanningStatistics.withMoreExpensiveLocalFilterPrefixPlanAndJoinEstimation(
				List.of(connector, boundObjects, lookup, filteredPattern));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(lookup, connector, filteredPattern), statementPatterns(root.getArg()),
				"Rejecting an expensive local-filter-prefix candidate must not suppress the finite-anchor order");
		assertEquals(boundObjects, joinArgs(root.getArg()).getFirst());
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void acceptedPlannerOrderSurvivesDeferredFilterPlacement() {
		BindingSetAssignment boundB = values("b", "user-3", "user-4", "user-5", "user-6");
		StatementPattern aFollowsB = statementPattern("a", "follows", "b");
		StatementPattern bFollowsC = statementPattern("b", "follows", "c");
		StatementPattern dFollowsA = statementPattern("d", "follows", "a");
		StatementPattern cFollowsD = statementPattern("c", "follows", "d");
		QueryRoot root = new QueryRoot(new Filter(
				new Join(boundB, new Join(aFollowsB, new Join(bFollowsC, new Join(dFollowsA, cFollowsD)))),
				and(notEqual("a", "b"), notEqual("b", "c"), notEqual("c", "d"), notEqual("d", "a"))));
		PlanningStatistics statistics = PlanningStatistics.withPlan(
				List.of(boundB, aFollowsB, bFollowsC, cFollowsD, dFollowsA));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(aFollowsB, bFollowsC, cFollowsD, dFollowsA), statementPatterns(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void materializesAcceptedPlannerOrderAsLeftDeepPrefixPipeline() {
		BindingSetAssignment boundA = values("a", "user-7", "user-8");
		BindingSetAssignment boundB = values("b", "user-7", "user-8");
		StatementPattern aFollowsB = statementPattern("a", "follows", "b");
		StatementPattern bFollowsC = statementPattern("b", "follows", "c");
		QueryRoot root = new QueryRoot(new Join(boundA, new Join(boundB, new Join(aFollowsB, bFollowsC))));
		PlanningStatistics statistics = PlanningStatistics.withPlan(List.of(boundA, boundB, aFollowsB, bFollowsC));

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		Join finalJoin = assertInstanceOf(Join.class, root.getArg());
		assertEquals(bFollowsC, finalJoin.getRightArg());
		Join edgeJoin = assertInstanceOf(Join.class, finalJoin.getLeftArg());
		assertEquals(aFollowsB, edgeJoin.getRightArg());
		Join valueJoin = assertInstanceOf(Join.class, edgeJoin.getLeftArg());
		assertEquals(boundA, valueJoin.getLeftArg());
		assertEquals(boundB, valueJoin.getRightArg());
		assertEquals(List.of(boundA, boundB, aFollowsB, bFollowsC), joinArgs(root.getArg()));
	}

	@Test
	void finiteAnchorMaterializationDoesNotReplanSyntheticJoinsForCardinality() {
		BindingSetAssignment boundDisease = values("disease", "disease-0", "disease-1");
		StatementPattern studiesDisease = statementPattern("trial", "studiesDisease", "disease");
		StatementPattern trialType = statementPattern("trial", "type", "trialType");
		StatementPattern hasArm = statementPattern("trial", "hasArm", "arm");
		StatementPattern armDrug = statementPattern("arm", "armDrug", "drug");
		QueryRoot root = new QueryRoot(new Join(boundDisease,
				new Join(studiesDisease, new Join(trialType, new Join(hasArm, armDrug)))));
		PlanningStatistics statistics = PlanningStatistics.supportingJoinEstimation();

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(0, statistics.planningAttempts);
		assertEquals(0, statistics.joinCardinalityRequests);
		List<TupleExpr> orderedArgs = joinArgs(root.getArg());
		assertEquals(boundDisease, orderedArgs.get(0));
		assertEquals(studiesDisease, orderedArgs.get(1));
		assertEquals(5, orderedArgs.size());
		assertTrue(orderedArgs.containsAll(List.of(boundDisease, studiesDisease, trialType, hasArm, armDrug)));
	}

	@Test
	void leavesJoinSegmentOrderUnchangedWhenPlannerRejects() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern third = statementPattern("s3", "p3", "o3");
		QueryRoot root = new QueryRoot(new Join(first, new Join(second, third)));
		PlanningStatistics statistics = PlanningStatistics.rejected();

		new LmdbSketchJoinOptimizer(statistics, false).optimize(root, null, null);

		assertEquals(List.of(first, second, third), joinArgs(root.getArg()));
		assertEquals(1, statistics.planningAttempts);
	}

	@Test
	void movesLeftJoinLocalFilterIntoPlannedLeftSegment() {
		StatementPattern first = statementPattern("s1", "p1", "o1");
		StatementPattern second = statementPattern("s2", "p2", "o2");
		StatementPattern optional = statementPattern("s1", "p3", "opt");
		Filter filter = new Filter(new LeftJoin(new Join(first, second), optional),
				new Compare(new Var("o1"), new Var("o2"), Compare.CompareOp.NE));
		QueryRoot root = new QueryRoot(filter);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		LeftJoin leftJoin = assertInstanceOf(LeftJoin.class, root.getArg());
		Filter movedFilter = assertInstanceOf(Filter.class, leftJoin.getLeftArg());
		assertTrue(containsFilter(leftJoin.getLeftArg()));
		assertEquals(List.of(first, second), joinArgs(movedFilter.getArg()));
	}

	@Test
	void keepsVariableVariableOptionalCompareAsLeftJoin() {
		StatementPattern section = statementPattern("section", "type", "sectionType");
		StatementPattern track = statementPattern("section", "hasTrack", "track");
		Extension optional = new Extension(statementPattern("section", "connectsOperationalPoint", "op"),
				new ExtensionElem(new Var("op"), "optOp"));
		Compare condition = new Compare(new Var("optOp"), new Var("section"), Compare.CompareOp.NE);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(section, track), optional), condition));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Filter optimizedFilter = assertInstanceOf(Filter.class, root.getArg());
		assertInstanceOf(LeftJoin.class, optimizedFilter.getArg());
		assertTrue(containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalCompareAgainstConstant() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		Compare condition = new Compare(new Var("optName"), new ValueConstant(VF.createLiteral("person/42")),
				Compare.CompareOp.EQ);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNullRejectingOptionalListMemberAgainstConstants() {
		StatementPattern person = statementPattern("person", "type", "personType");
		StatementPattern follows = statementPattern("person", "follows", "friend");
		StatementPattern optional = statementPattern("person", "name", "optName");
		ListMemberOperator condition = new ListMemberOperator();
		condition.addArgument(new Var("optName"));
		condition.addArgument(new ValueConstant(VF.createLiteral("person/42")));
		condition.addArgument(new ValueConstant(VF.createLiteral("person/43")));
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(new Join(person, follows), optional), condition));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		TupleExpr optimized = root.getArg();
		TupleExpr rewritten = optimized instanceof Filter ? ((Filter) optimized).getArg() : optimized;
		assertInstanceOf(Join.class, rewritten);
		assertTrue(!containsLeftJoin(root.getArg()));
	}

	@Test
	void keepsOptionalCompareAgainstConstantWhenFilterUsesOptionalAlias() {
		StatementPattern node = statementPattern("node", "type", "nodeType");
		Extension optional = new Extension(statementPattern("node", "weight", "w"), new ExtensionElem(new Var("w"),
				"optWeight"));
		Compare condition = new Compare(new Var("optWeight"), new ValueConstant(VF.createLiteral(5)),
				Compare.CompareOp.GT);
		QueryRoot root = new QueryRoot(new Filter(new LeftJoin(node, optional), condition));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Filter optimizedFilter = assertInstanceOf(Filter.class, root.getArg());
		assertInstanceOf(LeftJoin.class, optimizedFilter.getArg());
		assertTrue(containsLeftJoin(root.getArg()));
	}

	@Test
	void removesNoNewBindingOptionalDirectProbe() {
		BindingSetAssignment graph = values("graph", "ctx");
		StatementPattern type = statementPattern("node", "type", "nodeType");
		StatementPattern connects = statementPattern("node", "connectsTo", "neighbor");
		StatementPattern reverseProbe = statementPattern("neighbor", "connectsTo", "node", "graph");
		QueryRoot root = new QueryRoot(new LeftJoin(new Join(graph, new Join(type, connects)), reverseProbe));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(!containsLeftJoin(root.getArg()));
		assertEquals(List.of(graph, type, connects), joinArgs(root.getArg()));
	}

	@Test
	void keepsNoNewBindingOptionalProbeWithoutFixedContext() {
		StatementPattern type = statementPattern("node", "type", "nodeType");
		StatementPattern connects = statementPattern("node", "connectsTo", "neighbor");
		StatementPattern reverseProbe = statementPattern("neighbor", "connectsTo", "node");
		QueryRoot root = new QueryRoot(new LeftJoin(new Join(type, connects), reverseProbe));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(containsLeftJoin(root.getArg()));
	}

	@Test
	void rewritesNoNewBindingExistsDirectProbeToJoinFactor() {
		StatementPattern hasTrack = statementPattern("section", "hasTrack", "track");
		StatementPattern trackType = new StatementPattern(new Var("track"),
				new Var("_const_type", VF.createIRI("urn:type")),
				new Var("_const_trackType", VF.createIRI("urn:TrackSection")),
				new Var("_const_context", VF.createIRI("urn:ctx")));
		QueryRoot root = new QueryRoot(new Filter(hasTrack, new Exists(trackType)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(!containsFilter(root.getArg()));
		assertEquals(List.of(hasTrack, trackType), joinArgs(root.getArg()));
	}

	@Test
	void keepsNoNewBindingExistsProbeWithoutFixedContext() {
		StatementPattern hasTrack = statementPattern("section", "hasTrack", "track");
		StatementPattern trackType = new StatementPattern(new Var("track"),
				new Var("_const_type", VF.createIRI("urn:type")),
				new Var("_const_trackType", VF.createIRI("urn:TrackSection")));
		QueryRoot root = new QueryRoot(new Filter(hasTrack, new Exists(trackType)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(containsExistsFilter(root.getArg()));
	}

	@Test
	void rewritesNoNewBindingExistsProbeAboveOptionalFilterToJoinFactor() {
		StatementPattern sectionType = statementPattern("section", "type", "sectionType");
		StatementPattern hasTrack = statementPattern("section", "hasTrack", "track");
		Extension optional = new Extension(statementPattern("section", "connectsOperationalPoint", "op"),
				new ExtensionElem(new Var("op"), "optOp"));
		Compare optionalFilter = new Compare(new Var("optOp"), new Var("section"), Compare.CompareOp.NE);
		StatementPattern trackType = new StatementPattern(new Var("track"),
				new Var("_const_type", VF.createIRI("urn:type")),
				new Var("_const_trackType", VF.createIRI("urn:TrackSection")),
				new Var("_const_context", VF.createIRI("urn:ctx")));
		QueryRoot root = new QueryRoot(
				new Filter(new Filter(new LeftJoin(new Join(sectionType, hasTrack), optional), optionalFilter),
						new Exists(trackType)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(!containsExistsFilter(root.getArg()));
		assertTrue(containsLeftJoin(root.getArg()));
		assertTrue(joinArgs(root.getArg()).contains(trackType));
	}

	@Test
	void keepsNoNewBindingExistsProbeAboveOptionalFilterWithoutFixedContext() {
		StatementPattern sectionType = statementPattern("section", "type", "sectionType");
		StatementPattern hasTrack = statementPattern("section", "hasTrack", "track");
		Extension optional = new Extension(statementPattern("section", "connectsOperationalPoint", "op"),
				new ExtensionElem(new Var("op"), "optOp"));
		Compare optionalFilter = new Compare(new Var("optOp"), new Var("section"), Compare.CompareOp.NE);
		StatementPattern trackType = new StatementPattern(new Var("track"),
				new Var("_const_type", VF.createIRI("urn:type")),
				new Var("_const_trackType", VF.createIRI("urn:TrackSection")));
		QueryRoot root = new QueryRoot(
				new Filter(new Filter(new LeftJoin(new Join(sectionType, hasTrack), optional), optionalFilter),
						new Exists(trackType)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		assertTrue(containsExistsFilter(root.getArg()));
		assertTrue(containsLeftJoin(root.getArg()));
	}

	@Test
	void duplicatesValuesAndFilterIntoUnionBranches() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		StatementPattern conditionType = statementPattern("entity", "type", "condition");
		StatementPattern conditionCode = statementPattern("entity", "code", "code");
		StatementPattern medicationType = statementPattern("entity", "type", "medication");
		StatementPattern medicationCode = statementPattern("entity", "code", "code");
		Union union = new Union(new Join(conditionType, conditionCode), new Join(medicationType, medicationCode));
		Filter filter = new Filter(new Join(values, union),
				new Or(new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ),
						new Compare(new Var("code"), new ValueConstant(VF.createLiteral("DX-202")),
								Compare.CompareOp.EQ)));
		QueryRoot root = new QueryRoot(filter);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union distributed = assertInstanceOf(Union.class, root.getArg());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void duplicatesValuesAndFilterAcrossParserScopedUnion() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		Union union = new Union(new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code")),
				new Join(statementPattern("entity", "type", "medication"),
						statementPattern("entity", "code", "code")));
		union.setVariableScopeChange(true);
		QueryRoot root = new QueryRoot(new Filter(new Join(values, union),
				new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union distributed = assertInstanceOf(Union.class, root.getArg());
		assertTrue(distributed.isVariableScopeChange());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void duplicatesValuesAndFilterBeforeOptionalAcrossParserScopedUnion() {
		BindingSetAssignment values = values("target", "DX-200", "DX-201");
		Join conditionBranch = new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code"));
		Join medicationBranch = new Join(statementPattern("entity", "type", "medication"),
				statementPattern("entity", "code", "code"));
		conditionBranch.setVariableScopeChange(true);
		medicationBranch.setVariableScopeChange(true);
		Union union = new Union(conditionBranch, medicationBranch);
		union.setVariableScopeChange(true);
		LeftJoin optional = new LeftJoin(new Join(values, union), statementPattern("entity", "code", "alt"));
		QueryRoot root = new QueryRoot(new Filter(optional,
				new Or(new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ),
						new Compare(new Var("code"), new ValueConstant(VF.createLiteral("DX-202")),
								Compare.CompareOp.EQ))));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		LeftJoin optimizedOptional = assertInstanceOf(LeftJoin.class, root.getArg());
		Union distributed = assertInstanceOf(Union.class, optimizedOptional.getLeftArg());
		assertTrue(distributed.isVariableScopeChange());
		assertTrue(containsFilter(distributed.getLeftArg()));
		assertTrue(containsFilter(distributed.getRightArg()));
		assertTrue(containsBindingSetAssignment(distributed.getLeftArg(), "target"));
		assertTrue(containsBindingSetAssignment(distributed.getRightArg(), "target"));
	}

	@Test
	void placesDuplicatedValuesAfterScopedUnionBranchGraph() {
		Join conditionBranch = new Join(statementPattern("entity", "type", "condition"),
				statementPattern("entity", "code", "code"));
		Join medicationBranch = new Join(statementPattern("entity", "type", "medication"),
				statementPattern("entity", "code", "code"));
		conditionBranch.setVariableScopeChange(true);
		medicationBranch.setVariableScopeChange(true);
		Union union = new Union(
				new Filter(new Join(values("target", "DX-200", "DX-201"), conditionBranch),
						new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)),
				new Filter(new Join(values("target", "DX-200", "DX-201"), medicationBranch),
						new Compare(new Var("code"), new Var("target"), Compare.CompareOp.EQ)));
		QueryRoot root = new QueryRoot(union);

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		Union optimized = assertInstanceOf(Union.class, root.getArg());
		assertScopedBranchBeforeValues(optimized.getLeftArg());
		assertScopedBranchBeforeValues(optimized.getRightArg());
	}

	@Test
	void keepsUnionIndependentFiniteSuffixAfterScopedUnion() {
		BindingSetAssignment users = values("u", "user7", "user8");
		BindingSetAssignment names = values("optName", "user7", "user8");
		StatementPattern nameLookup = statementPattern("u", "name", "optName");
		Union union = new Union(
				new Extension(new Join(statementPattern("u", "follows", "v"), statementPattern("v", "follows", "u")),
						new ExtensionElem(new Var("v"), "activity")),
				new Extension(statementPattern("post", "authored", "u"), new ExtensionElem(new Var("post"),
						"activity")));
		union.setVariableScopeChange(true);
		QueryRoot root = new QueryRoot(new Join(users, new Join(names, new Join(nameLookup, union))));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		List<TupleExpr> args = joinArgs(root.getArg());
		assertEquals(3, args.size());
		Union distributedUnion = assertInstanceOf(Union.class, args.getFirst());
		assertTrue(containsBindingSetAssignment(distributedUnion.getLeftArg(), "u"));
		assertTrue(containsBindingSetAssignment(distributedUnion.getRightArg(), "u"));
		assertFalse(containsBindingSetAssignment(distributedUnion, "optName"));
		assertFalse(statementPatterns(distributedUnion).stream()
				.anyMatch(pattern -> "optName".equals(pattern.getObjectVar().getName())));
		assertTrue(containsBindingSetAssignment(args.get(1), "optName"));
		assertEquals("optName", assertInstanceOf(StatementPattern.class, args.get(2)).getObjectVar().getName());
	}

	@Test
	void keepsMinusWhenRhsExtensionCreatesLeftBindingName() {
		StatementPattern left = statementPattern("x", "p", "v");
		Extension right = new Extension(statementPattern("x", "q", "rv"), new ExtensionElem(new Var("rv"), "v"));
		QueryRoot root = new QueryRoot(new Difference(left, right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.cheapCorrelatedAntiJoin(), false).optimize(root, null, null);

		assertInstanceOf(Difference.class, root.getArg(),
				"RHS BIND to a left-side variable must keep MINUS compatibility semantics");
	}

	@Test
	void removesMinusWhenRhsFilterRequiresUnavailableBinding() {
		StatementPattern left = statementPattern("x", "p", "v");
		Filter right = new Filter(statementPattern("meter", "measures", "load"),
				new Compare(new Var("load"), new Var("substation"), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(left, right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, null);

		StatementPattern replacement = assertInstanceOf(StatementPattern.class, root.getArg(),
				"MINUS RHS filter cannot match when it needs a binding outside the RHS and outside initial bindings");
		assertEquals("p", replacement.getPredicateVar().getName());
	}

	@Test
	void keepsMinusWhenRhsFilterUnavailableBindingIsInitiallyBound() {
		StatementPattern left = statementPattern("x", "p", "v");
		Filter right = new Filter(statementPattern("meter", "measures", "load"),
				new Compare(new Var("load"), new Var("substation"), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(left, right));
		MapBindingSet bindings = new MapBindingSet();
		bindings.addBinding("substation", VF.createIRI("urn:substation"));

		new LmdbSketchJoinOptimizer(PlanningStatistics.rejected(), false).optimize(root, null, bindings);

		assertInstanceOf(Difference.class, root.getArg(),
				"Initial bindings can make the RHS filter match, so MINUS must retain compatibility semantics");
	}

	@Test
	void rewritesBoundKeyPatternMinusFilterWhenCorrelatedProbeIsCheaper() {
		StatementPattern medicationType = statementPattern("med", "type", "medication");
		StatementPattern medicationCode = statementPattern("med", "code", "code");
		Filter right = new Filter(statementPattern("med", "dosage", "dose"),
				new Compare(new Var("dose"), new ValueConstant(VF.createLiteral("10x")), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(new Join(medicationType, medicationCode), right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.cheapCorrelatedPatternFilterMinus(), false)
				.optimize(root, null, null);

		TupleExpr replacement = root.getArg();
		assertFalse(containsDifference(replacement),
				"Assured left key plus cheap single-pattern RHS should not retain materialized MINUS");
		assertTrue(containsNotExistsFilter(replacement),
				"Assured left key plus cheap single-pattern RHS should use correlated NOT EXISTS");
	}

	@Test
	void keepsMinusWhenRepeatedFiniteAntiProbeCostsMoreThanMaterialized() {
		BindingSetAssignment boundMedications = values("med", "med-0", "med-1", "med-2", "med-3");
		Filter right = new Filter(statementPattern("med", "dosage", "dose"),
				new Compare(new Var("dose"), new ValueConstant(VF.createLiteral("10x")), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(boundMedications, right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.repeatedFiniteAntiProbeMoreExpensive(), false)
				.optimize(root, null, null);

		TupleExpr retained = root.getArg();
		assertInstanceOf(Difference.class, retained,
				"Finite left bindings alone should not justify repeating a filtered anti-probe when materializing "
						+ "the MINUS RHS has lower estimated work");
		assertFalse(containsNotExistsFilter(retained),
				"Repeated filtered anti-probes should require stronger proof than a bounded left seed");
	}

	@Test
	void keepsMinusWhenLowPassFilteredAntiProbeLacksRepeatedWorkProof() {
		StatementPattern nodeType = statementPattern("node", "type", "nodeType");
		StatementPattern nodeWeight = statementPattern("node", "weight", "weight");
		Filter right = new Filter(statementPattern("node", "connectsTo", "neighbor"),
				new Compare(new Var("neighbor"), new Var("node"), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(new Join(nodeType, nodeWeight), right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.lowPassFilteredAntiProbeLacksWorkProof(), false)
				.optimize(root, null, null);

		TupleExpr retained = root.getArg();
		assertInstanceOf(Difference.class, retained,
				"Low-pass filtered anti-probes should not use sampled selectivity as proof that repeated RHS "
						+ "access work is cheaper than materializing MINUS");
		assertFalse(containsNotExistsFilter(retained),
				"Filtered anti-probe rewrite needs stronger evidence when RHS access repeats per left row");
	}

	@Test
	void rewritesHighPassFilteredAntiProbeWhenCorrelatedWorkIsCheaper() {
		StatementPattern medicationType = statementPattern("med", "type", "medication");
		StatementPattern medicationCode = statementPattern("med", "code", "code");
		Filter right = new Filter(statementPattern("med", "dosage", "dose"),
				new Compare(new Var("dose"), new ValueConstant(VF.createLiteral("10x")), Compare.CompareOp.EQ));
		QueryRoot root = new QueryRoot(new Difference(new Join(medicationType, medicationCode), right));

		new LmdbSketchJoinOptimizer(PlanningStatistics.highPassFilteredAntiProbeCheaper(), false)
				.optimize(root, null, null);

		TupleExpr replacement = root.getArg();
		assertFalse(containsDifference(replacement),
				"High-pass filtered RHS should still use a correlated anti-probe when total correlated work is lower");
		assertTrue(containsNotExistsFilter(replacement),
				"Cheaper high-pass filtered anti-probe should not be forced into materialized MINUS");
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName));
	}

	private static StatementPattern statementPattern(String subjectName, String predicateName, String objectName,
			String contextName) {
		return new StatementPattern(new Var(subjectName), new Var(predicateName, VF.createIRI("urn:" + predicateName)),
				new Var(objectName), new Var(contextName));
	}

	private static BindingSetAssignment values(String bindingName, String... values) {
		BindingSetAssignment assignment = new BindingSetAssignment();
		assignment.setBindingNames(Set.of(bindingName));
		List<BindingSet> bindingSets = new ArrayList<>(values.length);
		for (String value : values) {
			MapBindingSet bindingSet = new MapBindingSet(1);
			bindingSet.addBinding(bindingName, VF.createLiteral(value));
			bindingSets.add(bindingSet);
		}
		assignment.setBindingSets(bindingSets);
		return assignment;
	}

	private static ValueExpr and(ValueExpr first, ValueExpr second, ValueExpr... rest) {
		ValueExpr result = new And(first, second);
		for (ValueExpr condition : rest) {
			result = new And(result, condition);
		}
		return result;
	}

	private static Compare notEqual(String leftName, String rightName) {
		return new Compare(new Var(leftName), new Var(rightName), Compare.CompareOp.NE);
	}

	private static List<TupleExpr> joinArgs(TupleExpr tupleExpr) {
		List<TupleExpr> args = new ArrayList<>();
		collectJoinArgs(tupleExpr, args);
		return args;
	}

	private static List<StatementPattern> statementPatterns(TupleExpr tupleExpr) {
		List<StatementPattern> patterns = new ArrayList<>();
		collectStatementPatterns(tupleExpr, patterns);
		return patterns;
	}

	private static void collectJoinArgs(TupleExpr tupleExpr, List<TupleExpr> args) {
		if (tupleExpr instanceof Join join) {
			collectJoinArgs(join.getLeftArg(), args);
			collectJoinArgs(join.getRightArg(), args);
			return;
		}
		args.add(tupleExpr);
	}

	private static void collectStatementPatterns(TupleExpr tupleExpr, List<StatementPattern> patterns) {
		if (tupleExpr instanceof StatementPattern) {
			patterns.add((StatementPattern) tupleExpr);
			return;
		}
		if (tupleExpr instanceof Filter) {
			collectStatementPatterns(((Filter) tupleExpr).getArg(), patterns);
			return;
		}
		if (tupleExpr instanceof Extension) {
			collectStatementPatterns(((Extension) tupleExpr).getArg(), patterns);
			return;
		}
		if (tupleExpr instanceof Union union) {
			collectStatementPatterns(union.getLeftArg(), patterns);
			collectStatementPatterns(union.getRightArg(), patterns);
			return;
		}
		if (tupleExpr instanceof Join join) {
			collectStatementPatterns(join.getLeftArg(), patterns);
			collectStatementPatterns(join.getRightArg(), patterns);
		}
	}

	private static boolean containsFilter(TupleExpr tupleExpr) {
		if (tupleExpr instanceof Filter) {
			return true;
		}
		if (tupleExpr instanceof Join join) {
			return containsFilter(join.getLeftArg()) || containsFilter(join.getRightArg());
		}
		return false;
	}

	private static boolean containsExistsFilter(TupleExpr tupleExpr) {
		if (tupleExpr instanceof Filter filter) {
			return filter.getCondition() instanceof Exists || containsExistsFilter(filter.getArg());
		}
		if (tupleExpr instanceof Extension) {
			return containsExistsFilter(((Extension) tupleExpr).getArg());
		}
		if (tupleExpr instanceof LeftJoin leftJoin) {
			return containsExistsFilter(leftJoin.getLeftArg()) || containsExistsFilter(leftJoin.getRightArg());
		}
		if (tupleExpr instanceof Join join) {
			return containsExistsFilter(join.getLeftArg()) || containsExistsFilter(join.getRightArg());
		}
		return false;
	}

	private static boolean containsNotExistsFilter(TupleExpr tupleExpr) {
		if (tupleExpr instanceof Filter filter) {
			if (filter.getCondition()instanceof Not not && not.getArg() instanceof Exists) {
				return true;
			}
			return containsNotExistsFilter(filter.getArg());
		}
		if (tupleExpr instanceof Extension) {
			return containsNotExistsFilter(((Extension) tupleExpr).getArg());
		}
		if (tupleExpr instanceof LeftJoin leftJoin) {
			return containsNotExistsFilter(leftJoin.getLeftArg()) || containsNotExistsFilter(leftJoin.getRightArg());
		}
		if (tupleExpr instanceof Union union) {
			return containsNotExistsFilter(union.getLeftArg()) || containsNotExistsFilter(union.getRightArg());
		}
		if (tupleExpr instanceof Join join) {
			return containsNotExistsFilter(join.getLeftArg()) || containsNotExistsFilter(join.getRightArg());
		}
		return false;
	}

	private static boolean containsDifference(TupleExpr tupleExpr) {
		if (tupleExpr instanceof Difference) {
			return true;
		}
		if (tupleExpr instanceof Filter) {
			return containsDifference(((Filter) tupleExpr).getArg());
		}
		if (tupleExpr instanceof Extension) {
			return containsDifference(((Extension) tupleExpr).getArg());
		}
		if (tupleExpr instanceof LeftJoin leftJoin) {
			return containsDifference(leftJoin.getLeftArg()) || containsDifference(leftJoin.getRightArg());
		}
		if (tupleExpr instanceof Union union) {
			return containsDifference(union.getLeftArg()) || containsDifference(union.getRightArg());
		}
		if (tupleExpr instanceof Join join) {
			return containsDifference(join.getLeftArg()) || containsDifference(join.getRightArg());
		}
		return false;
	}

	private static boolean containsLeftJoin(TupleExpr tupleExpr) {
		if (tupleExpr instanceof LeftJoin) {
			return true;
		}
		if (tupleExpr instanceof Filter) {
			return containsLeftJoin(((Filter) tupleExpr).getArg());
		}
		if (tupleExpr instanceof Extension) {
			return containsLeftJoin(((Extension) tupleExpr).getArg());
		}
		if (tupleExpr instanceof Join join) {
			return containsLeftJoin(join.getLeftArg()) || containsLeftJoin(join.getRightArg());
		}
		return false;
	}

	private static boolean containsBindingSetAssignment(TupleExpr tupleExpr, String bindingName) {
		if (tupleExpr instanceof BindingSetAssignment
				&& tupleExpr.getBindingNames().contains(bindingName)) {
			return true;
		}
		if (tupleExpr instanceof Filter) {
			return containsBindingSetAssignment(((Filter) tupleExpr).getArg(), bindingName);
		}
		if (tupleExpr instanceof Extension) {
			return containsBindingSetAssignment(((Extension) tupleExpr).getArg(), bindingName);
		}
		if (tupleExpr instanceof Union union) {
			return containsBindingSetAssignment(union.getLeftArg(), bindingName)
					|| containsBindingSetAssignment(union.getRightArg(), bindingName);
		}
		if (tupleExpr instanceof Join join) {
			return containsBindingSetAssignment(join.getLeftArg(), bindingName)
					|| containsBindingSetAssignment(join.getRightArg(), bindingName);
		}
		return false;
	}

	private static void assertScopedBranchBeforeValues(TupleExpr tupleExpr) {
		assertTrue(containsFilter(tupleExpr));
		TupleExpr joinRoot = tupleExpr instanceof Filter ? ((Filter) tupleExpr).getArg() : tupleExpr;
		Join join = assertInstanceOf(Join.class, joinRoot);
		assertTrue(assertInstanceOf(VariableScopeChange.class, join.getLeftArg()).isVariableScopeChange());
		assertTrue(containsBindingSetAssignment(join.getRightArg(), "target"));
	}

	private static final class PlanningStatistics extends EvaluationStatistics implements JoinOrderPlanner,
			JoinFactorCostModel {

		private final List<TupleExpr> plan;
		private int planningAttempts;
		private int joinCardinalityRequests;
		private boolean supportsJoinEstimation;
		private boolean cheapCorrelatedAntiJoin;
		private boolean cheapCorrelatedPatternFilterMinus;
		private boolean repeatedFiniteAntiProbeMoreExpensive;
		private boolean lowPassFilteredAntiProbeLacksWorkProof;
		private boolean highPassFilteredAntiProbeCheaper;
		private boolean moreExpensiveLocalFilterPrefixPlan;

		private PlanningStatistics(List<TupleExpr> plan) {
			this.plan = plan;
		}

		static PlanningStatistics withPlan(List<TupleExpr> plan) {
			return new PlanningStatistics(plan);
		}

		static PlanningStatistics rejected() {
			return new PlanningStatistics(null);
		}

		static PlanningStatistics supportingJoinEstimation() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.supportsJoinEstimation = true;
			return statistics;
		}

		static PlanningStatistics cheapCorrelatedAntiJoin() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.cheapCorrelatedAntiJoin = true;
			return statistics;
		}

		static PlanningStatistics cheapCorrelatedPatternFilterMinus() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.cheapCorrelatedPatternFilterMinus = true;
			return statistics;
		}

		static PlanningStatistics repeatedFiniteAntiProbeMoreExpensive() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.repeatedFiniteAntiProbeMoreExpensive = true;
			return statistics;
		}

		static PlanningStatistics lowPassFilteredAntiProbeLacksWorkProof() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.lowPassFilteredAntiProbeLacksWorkProof = true;
			return statistics;
		}

		static PlanningStatistics highPassFilteredAntiProbeCheaper() {
			PlanningStatistics statistics = new PlanningStatistics(null);
			statistics.highPassFilteredAntiProbeCheaper = true;
			return statistics;
		}

		static PlanningStatistics withMoreExpensiveLocalFilterPrefixPlan(List<TupleExpr> plan) {
			PlanningStatistics statistics = new PlanningStatistics(plan);
			statistics.moreExpensiveLocalFilterPrefixPlan = true;
			return statistics;
		}

		static PlanningStatistics withMoreExpensiveLocalFilterPrefixPlanAndJoinEstimation(List<TupleExpr> plan) {
			PlanningStatistics statistics = withMoreExpensiveLocalFilterPrefixPlan(plan);
			statistics.supportsJoinEstimation = true;
			return statistics;
		}

		@Override
		public double getCardinality(TupleExpr expr) {
			if (expr instanceof Join) {
				joinCardinalityRequests++;
			}
			return 1.0d;
		}

		@Override
		public boolean supportsJoinEstimation() {
			return supportsJoinEstimation;
		}

		@Override
		public Optional<JoinOrderPlan> planJoinOrder(List<TupleExpr> args, Set<String> initiallyBoundVars,
				Algorithm algorithm) {
			planningAttempts++;
			if (plan == null) {
				return Optional.empty();
			}
			return Optional.of(new JoinOrderPlan(plan, 1.0d, 1.0d));
		}

		@Override
		public Optional<JoinOrderPlan> estimateJoinOrder(List<TupleExpr> orderedArgs, Set<String> initiallyBoundVars,
				Algorithm algorithm, List<FilterConstraint> deferredFilters) {
			if (moreExpensiveLocalFilterPrefixPlan) {
				return Optional.of(new JoinOrderPlan(orderedArgs, 1.0d, 100.0d));
			}
			return Optional.empty();
		}

		@Override
		public FilterPassEstimate estimateFilterPass(Filter filter) {
			if (moreExpensiveLocalFilterPrefixPlan) {
				return new FilterPassEstimate(0.10d, FilterPassEstimate.Source.HEURISTIC, 1_000L);
			}
			return super.estimateFilterPass(filter);
		}

		@Override
		public Optional<FactorCostEstimate> estimateFactorCost(TupleExpr factor, Set<String> currentlyBoundVars) {
			if (lowPassFilteredAntiProbeLacksWorkProof) {
				if (factor.getBindingNames().contains("neighbor")) {
					if (currentlyBoundVars.contains("node")) {
						return Optional.of(accessPathEstimate(1.0d, 0.0d, 7.0d));
					}
					return Optional.of(accessPathEstimate(300_000.0d, 0.0d, 900_000.0d));
				}
				if (factor.getBindingNames().contains("node")) {
					return Optional.of(new FactorCostEstimate(80_000.0d, 40_000.0d));
				}
				return Optional.of(new FactorCostEstimate(100.0d, 100.0d));
			}
			if (highPassFilteredAntiProbeCheaper) {
				if (factor.getBindingNames().contains("dose")) {
					if (currentlyBoundVars.contains("med")) {
						return Optional.of(accessPathEstimate(1.0d, 1.0d, 1.0d));
					}
					return Optional.of(accessPathEstimate(16_700.0d, 16_700.0d, 16_700.0d));
				}
				if (factor.getBindingNames().contains("med")) {
					return Optional.of(new FactorCostEstimate(82_950.0d, 13_800.0d));
				}
				return Optional.of(new FactorCostEstimate(100.0d, 100.0d));
			}
			if (repeatedFiniteAntiProbeMoreExpensive) {
				if (factor.getBindingNames().contains("dose")) {
					if (currentlyBoundVars.contains("med")) {
						return Optional.of(new FactorCostEstimate(4.0d, 1.0d));
					}
					return Optional.of(new FactorCostEstimate(1_000.0d, 1_000.0d));
				}
				if (factor.getBindingNames().contains("med")) {
					return Optional.of(new FactorCostEstimate(4_000.0d, 4_000.0d));
				}
				return Optional.of(new FactorCostEstimate(100.0d, 100.0d));
			}
			if (cheapCorrelatedPatternFilterMinus) {
				if (factor.getBindingNames().contains("dose")) {
					if (currentlyBoundVars.contains("med")) {
						return Optional.of(new FactorCostEstimate(1.0d, 1.0d));
					}
					return Optional.of(new FactorCostEstimate(250_000.0d, 250_000.0d));
				}
				if (factor.getBindingNames().contains("med")) {
					return Optional.of(new FactorCostEstimate(82_950.0d, 13_800.0d));
				}
				return Optional.of(new FactorCostEstimate(100.0d, 100.0d));
			}
			if (!cheapCorrelatedAntiJoin) {
				return Optional.empty();
			}
			if (factor.getBindingNames().contains("rv")) {
				if (currentlyBoundVars.containsAll(Set.of("x", "v"))) {
					return Optional.of(new FactorCostEstimate(1.0d, 1.0d));
				}
				return Optional.of(new FactorCostEstimate(1_000.0d, 1_000.0d));
			}
			return Optional.of(new FactorCostEstimate(100.0d, 100.0d));
		}

		private static FactorCostEstimate accessPathEstimate(double workRows, double outputRows,
				double accessRowsBeforeFilter) {
			return new FactorCostEstimate(workRows, outputRows, Map.of(), Map.of(), true, false, 0, 0,
					accessRowsBeforeFilter);
		}
	}
}
