/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Distinct;
import org.eclipse.rdf4j.query.algebra.EmptySet;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.ListMemberOperator;
import org.eclipse.rdf4j.query.algebra.Not;
import org.eclipse.rdf4j.query.algebra.Or;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.SameTerm;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.UnaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryBindingSet;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinFactorCostModel;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.eclipse.rdf4j.query.algebra.evaluation.sketch.SketchBasedJoinEstimator;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.query.explanation.TelemetryMetricNames;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbIndexAwareJoinOrderPlanningTest {

	private static final int TEST_RERUN_ATTEMPTS = 10;
	private static final long RETRY_PAUSE_MILLIS = TimeUnit.SECONDS.toMillis(1L);

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI RDF_TYPE = VF.createIRI("http://www.w3.org/1999/02/22-rdf-syntax-ns#type");
	private static final IRI GRID_SUBSTATION = VF.createIRI("http://example.com/theme/grid/Substation");
	private static final IRI GRID_GENERATOR = VF.createIRI("http://example.com/theme/grid/Generator");
	private static final IRI GRID_TRANSFORMER = VF.createIRI("http://example.com/theme/grid/Transformer");
	private static final IRI GRID_FEEDS = VF.createIRI("http://example.com/theme/grid/feeds");
	private static final IRI GRID_NAME = VF.createIRI("http://example.com/theme/grid/name");
	private static final IRI GRID_ALIAS = VF.createIRI("http://example.com/theme/grid/alias");
	private static final IRI SOCIAL_FOLLOWS = VF.createIRI("http://example.com/theme/social/follows");
	private static final IRI SOCIAL_NAME = VF.createIRI("http://example.com/theme/social/name");
	private static final IRI MED_CODE = VF.createIRI("http://example.com/theme/medical/code");
	private static final IRI MED_MEDICATION = VF.createIRI("http://example.com/theme/medical/Medication");
	private static final IRI LIB_NAME = VF.createIRI("http://example.com/theme/library/name");
	private static final IRI LIB_WRITTEN_BY = VF.createIRI("http://example.com/theme/library/writtenBy");
	private static final IRI LIB_HAS_COPY = VF.createIRI("http://example.com/theme/library/hasCopy");
	private static final IRI LIB_LOANED_COPY = VF.createIRI("http://example.com/theme/library/loanedCopy");
	private static final IRI LIB_BORROWED_BY = VF.createIRI("http://example.com/theme/library/borrowedBy");
	private static final IRI LIB_TITLE = VF.createIRI("http://example.com/theme/library/title");
	private static final IRI LIB_BOOK = VF.createIRI("http://example.com/theme/library/Book");
	private static final IRI LIB_COPY = VF.createIRI("http://example.com/theme/library/Copy");
	private static final IRI LIB_LOAN = VF.createIRI("http://example.com/theme/library/Loan");
	private static final IRI LIB_MEMBER = VF.createIRI("http://example.com/theme/library/Member");
	private static final IRI GUARANTEE_IRI_LEFT = VF.createIRI("http://example.com/p/iri-left");
	private static final IRI GUARANTEE_IRI_RIGHT = VF.createIRI("http://example.com/p/iri-right");
	private static final IRI GUARANTEE_LITERAL_OBJECT = VF.createIRI("http://example.com/p/literal-object");
	private static final IRI GUARANTEE_INT_OBJECT = VF.createIRI("http://example.com/p/int-object");
	private static final int SUBSTATION_COUNT = 300;
	private static final int GENERATOR_COUNT = 120;
	private static final int TRANSFORMER_COUNT = 5_000;
	private static final int NOISE_COUNT = 600;
	private static final int MEDICATIONS_PER_QUERY_CODE = 300;
	private static final int SELECTIVE_MEDICATION_COUNT = 1_500;
	private static final int LIBRARY_AUTHOR_NOISE_COUNT = 90_000;

	@Test
	void plannerAlgorithmUsesDynamicProgrammingAtConfiguredLimit() {
		assertEquals(JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING,
				LmdbSketchJoinOptimizer.plannerAlgorithmForSegment(
						JoinOrderPlanner.DEFAULT_DYNAMIC_PROGRAMMING_JOIN_ARG_LIMIT),
				"The exact DP limit should still use the memo planner");
		assertEquals(JoinOrderPlanner.Algorithm.GREEDY,
				LmdbSketchJoinOptimizer.plannerAlgorithmForSegment(
						JoinOrderPlanner.DEFAULT_DYNAMIC_PROGRAMMING_JOIN_ARG_LIMIT + 1),
				"Only segments above the DP limit should fall back to greedy");
	}

	@Test
	void plannerPrefersFeedsBeforeFilteredNameWithoutPosc(@TempDir File dataDir) throws Exception {
		PlannedBranch plannedBranch = planGeneratorBranch(dataDir, "spoc,ospc,psoc");
		Optional<JoinOrderPlanner.JoinOrderPlan> plan = plannedBranch.plan();

		assertTrue(plan.isPresent(), "Expected LMDB planner to produce a plan for the generator branch");
		assertEstimatedWorkMatchesStepSum(plan.get());
		List<TupleExpr> orderedArgs = plan.get().getOrderedArgs();
		assertEquals(4, orderedArgs.size(), "Expected four join factors in the generator branch");
		assertTrue(orderedArgs.contains(plannedBranch.feedsPattern()));
		assertTrue(orderedArgs.contains(plannedBranch.filteredNamePattern()));
	}

	@Test
	void plannerCostsTargetBoundFilteredNameLookupWhenPoscExists(@TempDir File dataDir) throws Exception {
		PlannedBranch plannedBranch = planGeneratorBranch(dataDir, "spoc,ospc,psoc,posc");
		Optional<JoinOrderPlanner.JoinOrderPlan> plan = plannedBranch.plan();

		assertTrue(plan.isPresent(), "Expected LMDB planner to produce a plan for the generator branch");
		assertEstimatedWorkMatchesStepSum(plan.get());
		List<TupleExpr> orderedArgs = plan.get().getOrderedArgs();
		assertEquals(4, orderedArgs.size(), "Expected four join factors in the generator branch");
		JoinFactorCostModel.FactorCostEstimate filteredNameCost = plannedBranch.targetBoundFilteredNameCost();
		assertEquals("directLookup",
				filteredNameCost.getStringMetrics().get(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE),
				"Expected posc to provide a direct target-bound grid:name lookup: "
						+ filteredNameCost.getStringMetrics() + filteredNameCost.getDoubleMetrics());
		assertTrue(filteredNameCost.getWorkRows() < GENERATOR_COUNT,
				"Expected posc to make target-bound grid:name cheaper than generator type scan: "
						+ filteredNameCost.getStringMetrics() + filteredNameCost.getDoubleMetrics());
	}

	@Test
	void optimizedElectricalGridQueryKeepsFeedsBeforeNameInGeneratorBranch(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticGridData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(electricalGridQuery())
						.explain(Explanation.Level.Optimized);
				TupleExpr optimized = (TupleExpr) explanation.tupleExpr();
				Union union = findFirst(optimized, Union.class);
				List<StatementPattern> generatorPatterns = new ArrayList<>();
				collectStatementPatterns(union.getRightArg(), generatorPatterns);
				List<String> generatorPredicates = generatorPatterns.stream()
						.map(LmdbIndexAwareJoinOrderPlanningTest::predicateValue)
						.toList();
				int feedsIndex = generatorPredicates.indexOf(GRID_FEEDS.stringValue());
				int nameIndex = generatorPredicates.indexOf(GRID_NAME.stringValue());

				assertTrue(feedsIndex >= 0, "Expected generator branch to contain grid:feeds");
				assertTrue(nameIndex >= 0, "Expected generator branch to contain grid:name");
				assertTrue(feedsIndex < nameIndex,
						"Optimized electrical-grid explanation should keep grid:feeds before grid:name");
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void optimizedPlanIncludesLmdbPlannedIndexMetrics(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticGridData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(plannedIndexMetricsQuery())
						.explain(Explanation.Level.Optimized);
				String optimizedPlan = explanation.toString();

				assertTrue(optimizedPlan.contains(TelemetryMetricNames.PLANNER_ID + "="), optimizedPlan);
				assertTrue(optimizedPlan.contains(TelemetryMetricNames.PLANNED_INDEX_NAME + "="), optimizedPlan);
				assertTrue(optimizedPlan.contains(TelemetryMetricNames.PLANNED_INDEX_PREFIX_LENGTH + "="),
						optimizedPlan);
				assertTrue(optimizedPlan.contains(TelemetryMetricNames.PLANNED_ACCESS_PATH_CANDIDATES + "="),
						optimizedPlan);
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void unboundLocalFilterDoesNotReducePhysicalAccessWork(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticTransformerData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			JoinFactorCostModel costModel = (JoinFactorCostModel) store.getBackingStore().getEvaluationStatistics();
			JoinFactorCostModel.FactorCostEstimate filteredNameCost = costModel
					.estimateFactorCost(filteredNameListMemberPattern(), Set.of())
					.orElseThrow();

			assertEquals("[P]",
					filteredNameCost.getStringMetrics().get(TelemetryMetricNames.PLANNED_LOOKUP_COMPONENTS),
					"An unbound filter value must not be counted as a physical lookup component: "
							+ filteredNameCost.getStringMetrics() + filteredNameCost.getDoubleMetrics());
			double plannedAccessRows = filteredNameCost.getDoubleMetrics()
					.get(TelemetryMetricNames.PLANNED_ACCESS_ROWS);
			assertTrue(filteredNameCost.getWorkRows() >= plannedAccessRows,
					"Work should track rows accessed before local filtering: "
							+ filteredNameCost.getDoubleMetrics());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void plannerStartsElectricalQ2WithFilteredSubstationNameWhenOnlyPredicatePrefixIsAvailable(@TempDir File dataDir)
			throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticTransformerData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			StatementPattern typePattern = transformerTypePattern();
			StatementPattern feedsPattern = transformerFeedsPattern();
			Filter filteredNamePattern = filteredNameListMemberPattern();
			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinOrderPlanner.PlanningAttempt attempt = planner.planJoinOrderAttempt(
					List.of(typePattern, feedsPattern, filteredNamePattern),
					Set.of(),
					JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING,
					List.of());
			Optional<JoinOrderPlanner.JoinOrderPlan> plan = attempt.getPlan();

			assertTrue(plan.isPresent(), "Expected LMDB planner to produce an electrical q2-style plan");
			assertEstimatedWorkMatchesStepSum(plan.get());
			List<TupleExpr> orderedArgs = plan.get().getOrderedArgs();
			assertTrue(orderedArgs.contains(filteredNamePattern),
					"Electrical q2 plan should include the selective substation-name predicate-prefix scan\nDiagnostics: "
							+ attempt.getDiagnostics());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void plannerAcceptsGeneralSegmentShapesAndReportsAdditiveWork(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticTransformerData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();

			StatementPattern multiVarFactor = new StatementPattern(Var.of("s"), Var.of("p"), Var.of("o"));
			assertPlannedWithAdditiveWork(planner, List.of(multiVarFactor, transformerFeedsPattern(),
					transformerTypePattern()), "multi-variable statement pattern");

			StatementPattern cycleLeft = new StatementPattern(Var.of("a"), Var.of("feedsPredicate", GRID_FEEDS),
					Var.of("b"));
			StatementPattern cycleMiddle = new StatementPattern(Var.of("b"), Var.of("feedsPredicate2", GRID_FEEDS),
					Var.of("c"));
			StatementPattern cycleRight = new StatementPattern(Var.of("c"), Var.of("feedsPredicate3", GRID_FEEDS),
					Var.of("a"));
			assertPlannedWithAdditiveWork(planner, List.of(cycleLeft, cycleMiddle, cycleRight), "cyclic segment");

			StatementPattern disconnectedType = new StatementPattern(Var.of("other"), Var.of("rdfType", RDF_TYPE),
					Var.of("transformerType", GRID_TRANSFORMER));
			assertPlannedWithAdditiveWork(planner, List.of(generatorTypePattern(), disconnectedType),
					"disconnected cross join");

			assertPlannedWithAdditiveWork(planner, List.of(new Distinct(transformerFeedsPattern()),
					transformerTypePattern()), "wrapped distinct factor");
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void optimizedSocialMediaQ4StartsWithUSideRestrictionBeforeFollowsProbe(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticSocialMediaQ4Data(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(socialMediaQ4Query())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
			}

			List<String> mandatoryLeafOrder = collectSocialMediaQ4MandatoryLeafOrder(optimized);
			int uRestrictionIndex = mandatoryLeafOrder.indexOf("u-restriction");
			int followsIndex = mandatoryLeafOrder.indexOf("follows");
			Filter uRestriction = findFirstNotExistsFilter(optimized);

			assertTrue(uRestrictionIndex >= 0, "Expected q4 plan to retain the u-side NOT EXISTS restriction");
			assertTrue(followsIndex >= 0, "Expected q4 plan to retain the social:follows probe");
			assertTrue(uRestrictionIndex < followsIndex,
					"Optimized q4 should run the u-side restriction before probing ?u social:follows ?v: "
							+ mandatoryLeafOrder);
			assertTrue(uRestriction.getArg().getBindingNames().contains("u"),
					"Expected q4 u-side restriction to evaluate with ?u bound");
			assertTrue(!uRestriction.getArg().getBindingNames().contains("v"),
					"Expected q4 u-side restriction before expanding ?v bindings: " + uRestriction);

			JoinFactorCostModel costModel = (JoinFactorCostModel) store.getBackingStore().getEvaluationStatistics();
			StatementPattern followsByObject = new StatementPattern(Var.of("u"),
					Var.of("followsPredicate", SOCIAL_FOLLOWS), Var.of("v"));
			JoinFactorCostModel.FactorCostEstimate prefixScanCost = costModel
					.estimateFactorCost(followsByObject, Set.of("v"))
					.orElseThrow();
			assertEquals("prefixScan",
					prefixScanCost.getStringMetrics().get(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE));
			double plannedAccessRows = prefixScanCost.getDoubleMetrics()
					.getOrDefault(TelemetryMetricNames.PLANNED_ACCESS_ROWS, prefixScanCost.getWorkRows());
			assertTrue(prefixScanCost.getWorkRows() <= plannedAccessRows,
					"Expected prefix scan work to track access rows rather than an inflated factor-row floor: "
							+ prefixScanCost.getDoubleMetrics());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void predicateOnlyAccessIsCostedAsPrefixScan(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticSocialMediaQ4Data(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			JoinFactorCostModel costModel = (JoinFactorCostModel) store.getBackingStore().getEvaluationStatistics();
			StatementPattern followsByPredicate = new StatementPattern(Var.of("u"),
					Var.of("followsPredicate", SOCIAL_FOLLOWS), Var.of("v"));
			JoinFactorCostModel.FactorCostEstimate predicateOnlyCost = costModel
					.estimateFactorCost(followsByPredicate, Set.of())
					.orElseThrow();

			assertEquals("prefixScan",
					predicateOnlyCost.getStringMetrics().get(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE),
					"Predicate-only LMDB access walks the predicate prefix and must not be treated as a direct lookup: "
							+ predicateOnlyCost.getStringMetrics() + predicateOnlyCost.getDoubleMetrics());
			assertTrue(predicateOnlyCost.getWorkRows() > 1.0d,
					"Predicate-only prefix scan should pay rows walked before filters: "
							+ predicateOnlyCost.getStringMetrics() + predicateOnlyCost.getDoubleMetrics());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void directLookupChainFromFiniteUserTuplesDoesNotExpandEstimate(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticSocialMediaChainData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment tuples = socialChainTupleBindings();
			StatementPattern followsAB = followsPattern("a", "b");
			StatementPattern followsBC = followsPattern("b", "c");
			StatementPattern followsCD = followsPattern("c", "d");
			StatementPattern followsDE = followsPattern("d", "e");
			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinOrderPlanner.PlanningAttempt attempt = planner.planJoinOrderAttempt(
					List.of(tuples, followsAB, followsBC, followsCD, followsDE),
					Set.of(),
					JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING,
					List.of());
			Optional<JoinOrderPlanner.JoinOrderPlan> plan = attempt.getPlan();

			assertTrue(plan.isPresent(), "Expected LMDB planner to produce a finite social-chain plan: "
					+ attempt.getDiagnostics());
			assertEstimatedWorkMatchesStepSum(plan.get());
			List<TupleExpr> orderedArgs = plan.get().getOrderedArgs();
			assertEquals(tuples, orderedArgs.getFirst(),
					"Finite tuple domain should seed the social-chain plan before direct lookups");

			double finiteTupleRows = bindingSetRows(tuples);
			for (int i = 1; i < plan.get().getSteps().size(); i++) {
				JoinOrderPlanner.PlanStep step = plan.get().getSteps().get(i);
				assertEquals("directLookup",
						step.getStringMetrics().get(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE),
						"Expected follows step " + i + " to be a bound direct lookup: "
								+ step.getStringMetrics() + step.getDoubleMetrics());
				assertTrue(step.getPrefixOutputRows() <= finiteTupleRows,
						"Bound follows direct lookup should not expand beyond finite tuple rows. finiteRows="
								+ finiteTupleRows + ", step=" + i + ", metrics="
								+ step.getStringMetrics() + step.getDoubleMetrics());
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void valuesBoundObjectLookupUsesPredicateObjectPageEstimate(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticMedicalCodeData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			BindingSetAssignment codes = medicalCodeBindings();
			StatementPattern codePattern = new StatementPattern(Var.of("med"), Var.of("codePredicate", MED_CODE),
					Var.of("code"));
			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinOrderPlanner.JoinOrderPlan plan = planner
					.estimateJoinOrder(List.of(codes, codePattern), Set.of(),
							JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING, List.of())
					.orElseThrow();

			JoinOrderPlanner.PlanStep codeStep = plan.getSteps().get(1);
			assertEquals("[P, O]",
					codeStep.getStringMetrics().get(TelemetryMetricNames.PLANNED_LOOKUP_COMPONENTS),
					"VALUES-bound object lookups with a constant predicate should be costed as P,O lookups: "
							+ codeStep.getStringMetrics() + codeStep.getDoubleMetrics());
			assertEquals("directLookup",
					codeStep.getStringMetrics().get(TelemetryMetricNames.PLANNED_INDEX_ACCESS_MODE),
					"VALUES-bound object lookups with a constant predicate should use the direct posc prefix: "
							+ codeStep.getStringMetrics() + codeStep.getDoubleMetrics());
			assertTrue(
					codeStep.getDoubleMetrics()
							.getOrDefault(TelemetryMetricNames.PLANNED_ACCESS_ROWS, 0.0d) >= MEDICATIONS_PER_QUERY_CODE
									* 2.0d,
					"Access rows should be the summed page-walk estimate for both VALUES bindings: "
							+ codeStep.getStringMetrics() + codeStep.getDoubleMetrics());
			assertTrue(codeStep.getStepWorkRows() >= MEDICATIONS_PER_QUERY_CODE * 2.0d,
					"Step work should include the page-walked rows for both VALUES bindings: "
							+ codeStep.getStringMetrics() + codeStep.getDoubleMetrics());
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void highFanoutMedicalCodeFilterKeepsOriginalAndFiniteAnchorCandidates(@TempDir File dataDir) throws Exception {
		assertTestPassesWithinAttempts(dataDir, "highFanoutMedicalCodeFilterKeepsOriginalAndFiniteAnchorCandidates",
				attemptDir -> {
					LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
					LmdbStore store = new LmdbStore(attemptDir, config);
					SailRepository repository = new SailRepository(store);
					repository.init();

					try {
						loadSyntheticMedicalCodeData(repository);
						store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

						TupleExpr optimized;
						String optimizedPlan;
						try (SailRepositoryConnection connection = repository.getConnection()) {
							Explanation explanation = connection.prepareTupleQuery(medicalCodeFilterQuery())
									.explain(Explanation.Level.Optimized);
							optimized = (TupleExpr) explanation.tupleExpr();
							optimizedPlan = explanation.toString();
						}

						assertTrue(optimizedPlan.contains("optimizer.guaranteeOptionCandidates="),
								"High-fanout literal filters should expose the costed guarantee option set:\n"
										+ optimizedPlan);
						assertTrue(optimizedPlan.contains("original[lower-bound")
								|| optimizedPlan.contains("original-fixed[fixed-order")
								|| optimizedPlan.contains("original[baseline"),
								"High-fanout literal filters should keep an original FILTER alternative available:\n"
										+ optimizedPlan);
						assertTrue(optimizedPlan.contains("finite-anchor:code"),
								"High-fanout literal filters should also expose the finite-anchor option when it is sound:\n"
										+ optimizedPlan);
					} finally {
						repository.shutDown();
					}
				});
	}

	@Test
	void selectiveMedicalCodeFilterChoosesFiniteAnchorOption(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSelectiveMedicalCodeData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			String optimizedPlan;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(medicalCodeFilterQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
				optimizedPlan = explanation.toString();
			}

			assertTrue(containsBindingSetAssignmentFor(optimized, "code"),
					"Selective finite literal filters should have a planner-selected VALUES anchor option: "
							+ optimized);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void selectedFiniteAnchorShowsGuaranteeDiagnostics(@TempDir File dataDir) throws Exception {
		assertTestPassesWithinAttempts(dataDir, "selectedFiniteAnchorShowsGuaranteeDiagnostics", attemptDir -> {
			LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
			LmdbStore store = new LmdbStore(attemptDir, config);
			SailRepository repository = new SailRepository(store);
			repository.init();

			try {
				loadSelectiveMedicalCodeData(repository);
				store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

				TupleExpr optimized;
				String optimizedPlan;
				try (SailRepositoryConnection connection = repository.getConnection()) {
					Explanation explanation = connection.prepareTupleQuery(medicalCodeFilterQuery())
							.explain(Explanation.Level.Optimized);
					optimized = (TupleExpr) explanation.tupleExpr();
					optimizedPlan = explanation.toString();
				}

				BindingSetAssignment anchor = findBindingSetAssignment(optimized, "code")
						.orElseThrow(() -> new AssertionError("Expected selected code VALUES anchor: " + optimized));
				assertEquals("finite-anchor:code", anchor.getStringMetricPlanned("optimizer.guaranteeOption"),
						"Selected finite anchors should expose the chosen guarantee option on the VALUES node: "
								+ optimized);
				assertEquals(MED_CODE.stringValue(),
						anchor.getStringMetricPlanned("optimizer.guaranteeAnchorPredicate"),
						"Selected finite anchors should show the known predicate that made the option sound: "
								+ optimized);
				assertTrue(anchor.getStringMetricPlanned("optimizer.guaranteeAnchorDomain")
						.contains("LITERAL"),
						"Selected finite anchors should show the narrowed finite object domain: " + optimized);
				assertTrue(optimizedPlan.contains("optimizer.guaranteeOptionCandidates="),
						"Plan should show generated guarantee option candidates:\n" + optimizedPlan);
				assertTrue(optimizedPlan.contains("finite-anchor:code"),
						"Plan should identify the finite-anchor option that produced the VALUES clause:\n"
								+ optimizedPlan);
			} finally {
				repository.shutDown();
			}
		});
	}

	@Test
	void knownPredicateObjectVarsShowGuaranteeDiagnostics(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSelectiveMedicalCodeData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			String optimizedPlan;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(medicalCodeFilterQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
				optimizedPlan = explanation.toString();
			}

			StatementPattern codePattern = findStatementPatternByPredicate(optimized, MED_CODE)
					.orElseThrow(() -> new AssertionError("Expected med:code statement pattern: " + optimized));
			assertTrue(codePattern.getStringMetricPlanned("optimizer.objectGuarantee")
					.contains("LITERAL"),
					"Known-predicate statement patterns should expose their object guarantee: " + optimized);
			assertTrue(optimizedPlan.lines()
					.anyMatch(line -> line.contains("Var (name=code")
							&& line.contains("optimizer.objectGuarantee=")
							&& line.contains("LITERAL")),
					"Known-predicate object var explain lines should expose their predicate object domain:\n"
							+ optimizedPlan);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void valuesVariableObjectFilterChoosesFiniteAnchorOption(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticLibraryNameData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(libraryValuesVariableNameQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
			}

			BindingSetAssignment authorNameAnchor = findBindingSetAssignment(optimized, "authorName")
					.orElseThrow(() -> new AssertionError(
							"Finite VALUES-bound equality should add an object anchor for the name lookup: "
									+ optimized));
			assertTrue(authorNameAnchor.getBindingNames().contains("target"),
					"The finite equality should be satisfied by one materialized assignment: " + optimized);
			assertEquals(4, countBindingSets(authorNameAnchor),
					"The materialized equality rows should retain only the compatible target/name pairs: "
							+ optimized);
			assertFalse(containsCompare(optimized, "authorName", "target"),
					"The materialized equality rows should satisfy the original filter without runtime comparison: "
							+ optimized);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void libraryQ9ValuesVariableFilterChoosesAuthorNameAnchorOption(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticLibraryQ9Data(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			String optimizedPlan;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(libraryQ9ValuesVariableNameQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
				optimizedPlan = explanation.toString();
			}

			BindingSetAssignment authorNameAnchor = findBindingSetAssignment(optimized, "authorName")
					.orElseThrow(() -> new AssertionError(
							"LIBRARY q9 shape should select the inferred authorName object anchor: " + optimized));
			assertTrue(authorNameAnchor.getBindingNames().contains("target"),
					"LIBRARY q9 should materialize the finite authorName/target filter into one assignment: "
							+ optimized);
			assertEquals(4, countBindingSets(authorNameAnchor),
					"LIBRARY q9 should only keep the four finite rows that satisfy the OR filter: " + optimized);
			assertFalse(containsCompare(optimized, "authorName", "target"),
					"The materialized authorName/target rows should satisfy the finite filter without runtime "
							+ "comparison: " + optimized);
			assertTrue(optimizedPlan.contains("optimizer.guaranteeOptions=generated=1, "
					+ "selected=finite-anchor:authorName"),
					"LIBRARY q9's inferred finite object domain should enter the Pareto option set and select "
							+ "the authorName anchor:\n" + optimizedPlan);
			assertTrue(optimizedPlan.contains("optimizer.guaranteeOptionCandidates=original[skipped-preselected")
					&& optimizedPlan.contains("finite-anchor:authorName[valid"),
					"LIBRARY q9 should preselect the exact finite-anchor candidate without costing the original "
							+ "baseline DP plan:\n"
							+ optimizedPlan);
			assertTrue(optimizedPlan.contains("optimizer.logicalExploration=mode=fixed-order"),
					"LIBRARY q9's inferred finite object domain should be selected by fixed connected costing "
							+ "before the expensive native Pareto planner option path:\n" + optimizedPlan);
			assertEquals(1, countOccurrences(optimizedPlan, "optimizer.logicalExploration=mode=fixed-order"),
					"Default optimized explanations should stamp fixed-order planner-summary diagnostics once "
							+ "instead of repeating them on every q9 plan node:\n" + optimizedPlan);
			assertFalse(optimizedPlan.contains("finalFrontier=[{order="),
					"Default optimized explanations should not rebuild the verbose final-frontier order string "
							+ "on the fixed-order hot path:\n" + optimizedPlan);
			assertFalse(optimizedPlan.contains("stepFactors=") || optimizedPlan.contains("fixed-connectedOrder="),
					"Default optimized explanations should not rebuild verbose guarantee-option step/order "
							+ "diagnostics on the fixed-order hot path:\n" + optimizedPlan);
			assertFalse(optimizedPlan.contains("bounded-greedy selected"),
					"LIBRARY q9 should compare bounded greedy with the full planner instead of selecting it "
							+ "early:\n" + optimizedPlan);
			assertFalse(optimizedPlan.contains("optimizer.logicalExploration=mode=finite-anchor-fastpath"),
					"LIBRARY q9 should not bypass the Pareto planner with the removed finite-anchor fast path:\n"
							+ optimizedPlan);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void iriObjectEqualityChoosesSameTermFilterOption(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticIriEqualityData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(iriEqualityQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
			}

			assertTrue(containsSameTerm(optimized, "a", "b"),
					"IRI object equality should have a planner-selected SameTerm variant: " + optimized);
			assertFalse(containsCompare(optimized, "a", "b"),
					"The selected IRI equality variant should not keep the original Compare: " + optimized);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void disjointObjectEqualityChoosesEmptySetOption(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticDisjointEqualityData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			TupleExpr optimized;
			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(disjointEqualityQuery())
						.explain(Explanation.Level.Optimized);
				optimized = (TupleExpr) explanation.tupleExpr();
			}

			assertTrue(containsEmptySet(optimized),
					"IRI-vs-literal equality over assured domains should select EmptySet: " + optimized);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void typeAndDatatypeFiltersUseGuaranteeOptions(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,ospc,psoc,posc");
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticTypeFilterData(repository);
			store.getBackingStore().getSketchBasedJoinEstimator().rebuild();

			try (SailRepositoryConnection connection = repository.getConnection()) {
				TupleExpr iriFilter = (TupleExpr) connection.prepareTupleQuery(iriTypeFilterQuery())
						.explain(Explanation.Level.Optimized)
						.tupleExpr();
				StatementPattern iriPattern = findStatementPatternByPredicate(iriFilter, GUARANTEE_IRI_LEFT)
						.orElseThrow();
				assertTrue(iriPattern.getStringMetricPlanned("optimizer.objectGuarantee").contains("IRI"),
						"Assured IRI object domain should stay attached to the access path: " + iriFilter);
				assertEquals(40, countResults(connection, iriTypeFilterQuery()),
						"The retained isIRI filter should preserve the assured IRI results");

				TupleExpr impossibleLiteralFilter = (TupleExpr) connection.prepareTupleQuery(iriAsLiteralFilterQuery())
						.explain(Explanation.Level.Optimized)
						.tupleExpr();
				StatementPattern literalPattern = findStatementPatternByPredicate(impossibleLiteralFilter,
						GUARANTEE_IRI_LEFT).orElseThrow();
				assertTrue(literalPattern.getStringMetricPlanned("optimizer.objectGuarantee").contains("IRI"),
						"Assured IRI object domain should stay attached before the isLiteral filter: "
								+ impossibleLiteralFilter);
				assertEquals(0, countResults(connection, iriAsLiteralFilterQuery()),
						"The retained isLiteral filter should reject the assured IRI results");

				TupleExpr datatypeFilter = (TupleExpr) connection.prepareTupleQuery(intDatatypeFilterQuery())
						.explain(Explanation.Level.Optimized)
						.tupleExpr();
				StatementPattern datatypePattern = findStatementPatternByPredicate(datatypeFilter,
						GUARANTEE_INT_OBJECT).orElseThrow();
				assertTrue(datatypePattern.getStringMetricPlanned("optimizer.objectGuarantee").contains("INT"),
						"Single xsd:int object domain should stay attached to the access path: " + datatypeFilter);
				assertEquals(40, countResults(connection, intDatatypeFilterQuery()),
						"The retained datatype filter should preserve the assured xsd:int results");
			}
		} finally {
			repository.shutDown();
		}
	}

	private static PlannedBranch planGeneratorBranch(File dataDir, String indexes) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig(indexes);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();

		try {
			loadSyntheticGridData(repository);
			SketchBasedJoinEstimator estimator = store.getBackingStore().getSketchBasedJoinEstimator();
			estimator.rebuild();

			StatementPattern typePattern = generatorTypePattern();
			StatementPattern feedsPattern = feedsPattern();
			Filter filteredNamePattern = filteredNamePattern();
			BindingSetAssignment targets = targetBindings();

			JoinOrderPlanner planner = (JoinOrderPlanner) store.getBackingStore().getEvaluationStatistics();
			JoinFactorCostModel.FactorCostEstimate targetBoundFilteredNameCost = ((JoinFactorCostModel) planner)
					.estimateFactorCost(filteredNamePattern, Set.of("target"))
					.orElseThrow();
			return new PlannedBranch(
					planner.planJoinOrder(List.of(targets, typePattern, feedsPattern, filteredNamePattern),
							java.util.Set.of(),
							JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING),
					targets,
					typePattern,
					feedsPattern,
					filteredNamePattern,
					targetBoundFilteredNameCost);
		} finally {
			repository.shutDown();
		}
	}

	private static void assertPlannedWithAdditiveWork(JoinOrderPlanner planner, List<TupleExpr> factors,
			String shapeDescription) {
		JoinOrderPlanner.PlanningAttempt attempt = planner.planJoinOrderAttempt(factors, Set.of(),
				JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING, List.of());
		assertTrue(attempt.getPlan().isPresent(),
				"Expected LMDB planner to accept " + shapeDescription + ": " + attempt.getDiagnostics());
		assertEstimatedWorkMatchesStepSum(attempt.getPlan().get());
		assertTrue(attempt.getPlan()
				.get()
				.getSummaryStringMetrics()
				.get(TelemetryMetricNames.OPTIMIZER_PHYSICAL_REFINEMENT)
				.contains("costModel=lmdb"),
				"Expected LMDB physical refinement diagnostics: "
						+ attempt.getPlan().get().getSummaryStringMetrics());
	}

	private static void assertEstimatedWorkMatchesStepSum(JoinOrderPlanner.JoinOrderPlan plan) {
		assertEquals(plan.getOrderedArgs().size(), plan.getSteps().size(),
				"Expected one planner step per ordered factor");
		double stepWorkSum = plan.getSteps()
				.stream()
				.mapToDouble(JoinOrderPlanner.PlanStep::getStepWorkRows)
				.sum();
		assertEquals(stepWorkSum, plan.getEstimatedTotalWork(), 1.0e-9,
				"Planner total work should equal sum(stepWorkRows)");
		plan.getSteps().forEach(step -> {
			assertTrue(Double.isFinite(step.getFactorOutputRows()) && step.getFactorOutputRows() >= 0.0d,
					"Expected finite factor rows for " + step.getStringMetrics());
			assertTrue(Double.isFinite(step.getPrefixOutputRows()) && step.getPrefixOutputRows() >= 0.0d,
					"Expected finite prefix rows for " + step.getStringMetrics());
			assertTrue(Double.isFinite(step.getStepWorkRows()) && step.getStepWorkRows() >= 0.0d,
					"Expected finite step work for " + step.getStringMetrics());
		});
	}

	private static void loadSyntheticGridData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < SUBSTATION_COUNT; i++) {
				Resource substation = VF.createIRI("urn:test:substation:" + i);
				connection.add(substation, RDF_TYPE, GRID_SUBSTATION);
				connection.add(substation, GRID_NAME, VF.createLiteral("Substation " + i));
			}
			for (int i = 0; i < GENERATOR_COUNT; i++) {
				Resource generator = VF.createIRI("urn:test:generator:" + i);
				Resource substation = VF.createIRI("urn:test:substation:" + (i % 12));
				connection.add(generator, RDF_TYPE, GRID_GENERATOR);
				connection.add(generator, GRID_FEEDS, substation);
			}
			for (int i = 0; i < NOISE_COUNT; i++) {
				Resource aliasHolder = VF.createIRI("urn:test:alias-holder:" + i);
				connection.add(aliasHolder, GRID_ALIAS, VF.createLiteral("Substation " + (1 + (i % 3))));
			}
			connection.commit();
		}
	}

	private static void loadSyntheticMedicalCodeData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < MEDICATIONS_PER_QUERY_CODE; i++) {
				Resource medication = VF.createIRI("urn:test:medication:1000:" + i);
				connection.add(medication, RDF_TYPE, MED_MEDICATION);
				connection.add(medication, MED_CODE, VF.createLiteral("MED-1000"));
			}
			for (int i = 0; i < MEDICATIONS_PER_QUERY_CODE; i++) {
				Resource medication = VF.createIRI("urn:test:medication:1001:" + i);
				connection.add(medication, RDF_TYPE, MED_MEDICATION);
				connection.add(medication, MED_CODE, VF.createLiteral("MED-1001"));
			}
			connection.commit();
		}
	}

	private static void loadSelectiveMedicalCodeData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < SELECTIVE_MEDICATION_COUNT; i++) {
				Resource medication = VF.createIRI("urn:test:selective-medication:" + i);
				connection.add(medication, RDF_TYPE, MED_MEDICATION);
				connection.add(medication, MED_CODE, VF.createLiteral("MED-" + i));
			}
			connection.commit();
		}
	}

	private static void loadSyntheticLibraryNameData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < LIBRARY_AUTHOR_NOISE_COUNT; i++) {
				Resource author = VF.createIRI("urn:test:library-author:noise:" + i);
				connection.add(author, LIB_NAME, VF.createLiteral("Noise Author " + i));
			}
			connection.add(VF.createIRI("urn:test:library-author:1"), LIB_NAME, VF.createLiteral("Author 1"));
			connection.add(VF.createIRI("urn:test:library-author:2"), LIB_NAME, VF.createLiteral("Author 2"));
			connection.add(VF.createIRI("urn:test:library-author:3"), LIB_NAME, VF.createLiteral("Author 3"));
			connection.commit();
		}
	}

	private static void loadSyntheticLibraryQ9Data(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < LIBRARY_AUTHOR_NOISE_COUNT; i++) {
				Resource author = VF.createIRI("urn:test:library-q9-author:noise:" + i);
				connection.add(author, LIB_NAME, VF.createLiteral("Noise Author " + i));
			}
			for (int i = 1; i <= 3; i++) {
				Resource author = VF.createIRI("urn:test:library-q9-author:" + i);
				Resource book = VF.createIRI("urn:test:library-q9-book:" + i);
				Resource copy = VF.createIRI("urn:test:library-q9-copy:" + i);
				Resource loan = VF.createIRI("urn:test:library-q9-loan:" + i);
				Resource member = VF.createIRI("urn:test:library-q9-member:" + i);
				connection.add(author, LIB_NAME, VF.createLiteral("Author " + i));
				connection.add(book, RDF_TYPE, LIB_BOOK);
				connection.add(book, LIB_WRITTEN_BY, author);
				connection.add(book, LIB_HAS_COPY, copy);
				connection.add(book, LIB_TITLE, VF.createLiteral("Book " + i));
				connection.add(copy, RDF_TYPE, LIB_COPY);
				connection.add(loan, RDF_TYPE, LIB_LOAN);
				connection.add(loan, LIB_LOANED_COPY, copy);
				connection.add(loan, LIB_BORROWED_BY, member);
				connection.add(member, RDF_TYPE, LIB_MEMBER);
			}
			connection.commit();
		}
	}

	private static void loadSyntheticIriEqualityData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < 40; i++) {
				Resource object = VF.createIRI("urn:test:iri-object:" + i);
				connection.add(VF.createIRI("urn:test:iri-left:" + i), GUARANTEE_IRI_LEFT, object);
				connection.add(VF.createIRI("urn:test:iri-right:" + i), GUARANTEE_IRI_RIGHT, object);
			}
			connection.commit();
		}
	}

	private static void loadSyntheticDisjointEqualityData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < 40; i++) {
				connection.add(VF.createIRI("urn:test:disjoint-iri:" + i), GUARANTEE_IRI_LEFT,
						VF.createIRI("urn:test:iri-object:" + i));
				connection.add(VF.createIRI("urn:test:disjoint-literal:" + i), GUARANTEE_LITERAL_OBJECT,
						VF.createLiteral("literal " + i));
			}
			connection.commit();
		}
	}

	private static void loadSyntheticTypeFilterData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < 40; i++) {
				connection.add(VF.createIRI("urn:test:type-filter-iri:" + i), GUARANTEE_IRI_LEFT,
						VF.createIRI("urn:test:iri-object:" + i));
				connection.add(VF.createIRI("urn:test:type-filter-int:" + i), GUARANTEE_INT_OBJECT,
						VF.createLiteral(String.valueOf(i), XSD.INT));
			}
			connection.commit();
		}
	}

	private static void loadSyntheticSocialMediaQ4Data(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			List<Resource> queryUsers = new ArrayList<>();
			for (int i = 7; i <= 11; i++) {
				Resource user = socialUser(i);
				queryUsers.add(user);
				connection.add(user, SOCIAL_NAME, VF.createLiteral("user" + i));
				if (i != 7) {
					connection.add(user, SOCIAL_FOLLOWS, user);
				}
			}
			connection.add(socialUser(7), SOCIAL_FOLLOWS, socialUser(8));
			connection.add(socialUser(7), SOCIAL_FOLLOWS, socialUser(9));

			for (int i = 0; i < 120; i++) {
				Resource follower = socialUser(1000 + i);
				Resource target = queryUsers.get(i % queryUsers.size());
				connection.add(follower, SOCIAL_FOLLOWS, target);
			}
			connection.commit();
		}
	}

	private static void loadSyntheticSocialMediaChainData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (BindingSet bindingSet : socialChainTupleBindings().getBindingSets()) {
				connection.add((Resource) bindingSet.getValue("a"), SOCIAL_FOLLOWS,
						bindingSet.getValue("b"));
				connection.add((Resource) bindingSet.getValue("b"), SOCIAL_FOLLOWS,
						bindingSet.getValue("c"));
				connection.add((Resource) bindingSet.getValue("c"), SOCIAL_FOLLOWS,
						bindingSet.getValue("d"));
				connection.add((Resource) bindingSet.getValue("d"), SOCIAL_FOLLOWS,
						bindingSet.getValue("e"));
			}
			for (int i = 0; i < 4_000; i++) {
				Resource follower = socialUser(10_000 + i);
				Resource target = socialUser(20_000 + (i % 1_000));
				connection.add(follower, SOCIAL_FOLLOWS, target);
			}
			connection.commit();
		}
	}

	private static void loadSyntheticTransformerData(SailRepository repository) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.begin(IsolationLevels.NONE);
			for (int i = 0; i < SUBSTATION_COUNT; i++) {
				Resource substation = VF.createIRI("urn:test:substation:" + i);
				connection.add(substation, GRID_NAME, VF.createLiteral("Substation " + i));
			}
			for (int i = 0; i < TRANSFORMER_COUNT; i++) {
				Resource transformer = VF.createIRI("urn:test:transformer:" + i);
				Resource substation = VF.createIRI("urn:test:substation:" + (i % SUBSTATION_COUNT));
				connection.add(transformer, RDF_TYPE, GRID_TRANSFORMER);
				connection.add(transformer, GRID_FEEDS, substation);
			}
			connection.commit();
		}
	}

	private static Resource socialUser(int index) {
		return VF.createIRI("http://example.com/theme/social/user/" + index);
	}

	private static StatementPattern followsPattern(String subjectName, String objectName) {
		return new StatementPattern(Var.of(subjectName), Var.of("followsPredicate", SOCIAL_FOLLOWS),
				Var.of(objectName));
	}

	private static StatementPattern generatorTypePattern() {
		return new StatementPattern(Var.of("entity"), Var.of("rdfType", RDF_TYPE),
				Var.of("generatorType", GRID_GENERATOR));
	}

	private static StatementPattern feedsPattern() {
		return new StatementPattern(Var.of("entity"), Var.of("feedsPredicate", GRID_FEEDS), Var.of("substation"));
	}

	private static StatementPattern transformerTypePattern() {
		return new StatementPattern(Var.of("transformer"), Var.of("rdfType", RDF_TYPE),
				Var.of("transformerType", GRID_TRANSFORMER));
	}

	private static StatementPattern transformerFeedsPattern() {
		return new StatementPattern(Var.of("transformer"), Var.of("feedsPredicate", GRID_FEEDS),
				Var.of("substation"));
	}

	private static Filter filteredNamePattern() {
		StatementPattern namePattern = new StatementPattern(Var.of("substation"), Var.of("namePredicate", GRID_NAME),
				Var.of("name"));
		return new Filter(namePattern,
				new Or(
						new Compare(Var.of("name"), Var.of("target"), Compare.CompareOp.EQ),
						new Compare(Var.of("name"), new ValueConstant(VF.createLiteral("Substation 3")),
								Compare.CompareOp.EQ)));
	}

	private static Filter filteredNameListMemberPattern() {
		StatementPattern namePattern = new StatementPattern(Var.of("substation"), Var.of("namePredicate", GRID_NAME),
				Var.of("name"));
		ListMemberOperator condition = new ListMemberOperator();
		condition.addArgument(Var.of("name"));
		condition.addArgument(new ValueConstant(VF.createLiteral("Substation 0")));
		condition.addArgument(new ValueConstant(VF.createLiteral("Substation 1")));
		condition.addArgument(new ValueConstant(VF.createLiteral("Substation 2")));
		return new Filter(namePattern, condition);
	}

	private static BindingSetAssignment targetBindings() {
		BindingSetAssignment bindingSetAssignment = new BindingSetAssignment();
		QueryBindingSet first = new QueryBindingSet();
		first.addBinding("target", VF.createLiteral("Substation 1"));
		QueryBindingSet second = new QueryBindingSet();
		second.addBinding("target", VF.createLiteral("Substation 2"));
		bindingSetAssignment.setBindingSets(List.<BindingSet>of(first, second));
		return bindingSetAssignment;
	}

	private static BindingSetAssignment socialChainTupleBindings() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		List<BindingSet> bindingSets = new ArrayList<>();
		for (int i = 0; i < 25; i++) {
			QueryBindingSet bindingSet = new QueryBindingSet();
			bindingSet.addBinding("a", socialUser(i % 5));
			bindingSet.addBinding("b", socialUser(100 + (i / 5)));
			bindingSet.addBinding("c", socialUser(200 + (i % 5)));
			bindingSet.addBinding("d", socialUser(300 + (i / 5)));
			bindingSet.addBinding("e", socialUser(400 + (i % 5)));
			bindingSets.add(bindingSet);
		}
		assignment.setBindingSets(bindingSets);
		return assignment;
	}

	private static BindingSetAssignment medicalCodeBindings() {
		BindingSetAssignment assignment = new BindingSetAssignment();
		QueryBindingSet first = new QueryBindingSet();
		first.addBinding("code", VF.createLiteral("MED-1000"));
		QueryBindingSet second = new QueryBindingSet();
		second.addBinding("code", VF.createLiteral("MED-1001"));
		assignment.setBindingSets(List.<BindingSet>of(first, second));
		return assignment;
	}

	private static double bindingSetRows(BindingSetAssignment assignment) {
		double rows = 0.0d;
		for (BindingSet ignored : assignment.getBindingSets()) {
			rows += 1.0d;
		}
		return rows;
	}

	private static String electricalGridQuery() {
		return String.join("\n",
				"SELECT (COUNT(DISTINCT ?entity) AS ?count) WHERE {",
				"  {",
				"    VALUES ?target { \"Substation 1\" \"Substation 2\" }",
				"    ?entity a <http://example.com/theme/grid/Substation> .",
				"    ?entity <http://example.com/theme/grid/name> ?name .",
				"    FILTER ((?name = ?target) || (?name = \"Substation 3\"))",
				"  }",
				"  UNION",
				"  {",
				"    VALUES ?target { \"Substation 1\" \"Substation 2\" }",
				"    ?entity a <http://example.com/theme/grid/Generator> .",
				"    ?entity <http://example.com/theme/grid/feeds> ?substation .",
				"    ?substation <http://example.com/theme/grid/name> ?name .",
				"    FILTER ((?name = ?target) || (?name = \"Substation 3\"))",
				"  }",
				"  OPTIONAL {",
				"    ?entity <http://example.com/theme/grid/feeds> ?substation2 .",
				"  }",
				"}");
	}

	private static String plannedIndexMetricsQuery() {
		return String.join("\n",
				"SELECT (COUNT(DISTINCT ?entity) AS ?count) WHERE {",
				"  VALUES ?target { \"Substation 1\" \"Substation 2\" }",
				"  ?entity <http://example.com/theme/grid/feeds> ?substation .",
				"  ?entity a <http://example.com/theme/grid/Generator> .",
				"  ?substation <http://example.com/theme/grid/name> ?name .",
				"  FILTER ((?name = ?target) || (?name = \"Substation 3\"))",
				"}");
	}

	private static String socialMediaQ4Query() {
		return String.join("\n",
				"PREFIX social: <http://example.com/theme/social/>",
				"SELECT (COUNT(DISTINCT ?u) AS ?count) WHERE {",
				"  VALUES ?u { <http://example.com/theme/social/user/7>",
				"              <http://example.com/theme/social/user/8>",
				"              <http://example.com/theme/social/user/9>",
				"              <http://example.com/theme/social/user/10>",
				"              <http://example.com/theme/social/user/11> }",
				"  VALUES ?v { <http://example.com/theme/social/user/7>",
				"              <http://example.com/theme/social/user/8>",
				"              <http://example.com/theme/social/user/9>",
				"              <http://example.com/theme/social/user/10>",
				"              <http://example.com/theme/social/user/11> }",
				"  FILTER(?u != ?v)",
				"  ?u social:follows ?v .",
				"  FILTER NOT EXISTS { ?u social:follows ?u . }",
				"  OPTIONAL { ?v social:name ?optName . }",
				"  FILTER(?optName != \"\")",
				"}");
	}

	private static String medicalCodeFilterQuery() {
		return String.join("\n",
				"PREFIX med: <http://example.com/theme/medical/>",
				"SELECT (COUNT(DISTINCT ?med) AS ?count) WHERE {",
				"  ?med a med:Medication ; med:code ?code .",
				"  FILTER(?code = \"MED-1000\" || ?code = \"MED-1001\")",
				"}");
	}

	private static String libraryValuesVariableNameQuery() {
		return String.join("\n",
				"PREFIX lib: <http://example.com/theme/library/>",
				"SELECT (COUNT(DISTINCT ?author) AS ?count) WHERE {",
				"  VALUES ?target { \"Author 1\" \"Author 2\" }",
				"  ?author lib:name ?authorName .",
				"  FILTER(?authorName = ?target || ?authorName = \"Author 3\")",
				"}");
	}

	private static String libraryQ9ValuesVariableNameQuery() {
		return String.join("\n",
				"PREFIX lib: <http://example.com/theme/library/>",
				"SELECT (COUNT(DISTINCT ?member) AS ?count) WHERE {",
				"  VALUES ?target { \"Author 1\" \"Author 2\" }",
				"  ?author lib:name ?authorName .",
				"  FILTER(?authorName = ?target || ?authorName = \"Author 3\")",
				"  ?book lib:writtenBy ?author .",
				"  ?book lib:hasCopy ?copy .",
				"  ?loan lib:loanedCopy ?copy .",
				"  ?loan a lib:Loan .",
				"  ?loan lib:borrowedBy ?member .",
				"  ?member a lib:Member .",
				"  OPTIONAL { ?book lib:title ?optTitle . }",
				"  FILTER(?optTitle != \"\" && NOT EXISTS {",
				"    ?loan lib:dueDate ?due .",
				"    FILTER(?due < \"2024-01-10\"^^<http://www.w3.org/2001/XMLSchema#date>)",
				"  })",
				"}");
	}

	private static String iriEqualityQuery() {
		return String.join("\n",
				"SELECT * WHERE {",
				"  ?left <" + GUARANTEE_IRI_LEFT + "> ?a .",
				"  ?right <" + GUARANTEE_IRI_RIGHT + "> ?b .",
				"  FILTER (?a = ?b)",
				"}");
	}

	private static String disjointEqualityQuery() {
		return String.join("\n",
				"SELECT * WHERE {",
				"  ?left <" + GUARANTEE_IRI_LEFT + "> ?a .",
				"  ?right <" + GUARANTEE_LITERAL_OBJECT + "> ?b .",
				"  FILTER (?a = ?b)",
				"}");
	}

	private static String iriTypeFilterQuery() {
		return String.join("\n",
				"SELECT * WHERE {",
				"  ?left <" + GUARANTEE_IRI_LEFT + "> ?a .",
				"  FILTER (isIRI(?a))",
				"}");
	}

	private static String iriAsLiteralFilterQuery() {
		return String.join("\n",
				"SELECT * WHERE {",
				"  ?left <" + GUARANTEE_IRI_LEFT + "> ?a .",
				"  FILTER (isLiteral(?a))",
				"}");
	}

	private static String intDatatypeFilterQuery() {
		return String.join("\n",
				"PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>",
				"SELECT * WHERE {",
				"  ?left <" + GUARANTEE_INT_OBJECT + "> ?a .",
				"  FILTER (datatype(?a) = xsd:int)",
				"}");
	}

	private record PlannedBranch(Optional<JoinOrderPlanner.JoinOrderPlan> plan, BindingSetAssignment targets,
			StatementPattern typePattern, StatementPattern feedsPattern, Filter filteredNamePattern,
			JoinFactorCostModel.FactorCostEstimate targetBoundFilteredNameCost) {
	}

	private static String predicateValue(StatementPattern statementPattern) {
		return statementPattern.getPredicateVar().getValue().stringValue();
	}

	private static List<String> collectSocialMediaQ4MandatoryLeafOrder(TupleExpr optimized) {
		List<String> leaves = new ArrayList<>();
		TupleExpr mandatoryRoot = optimized;
		Optional<LeftJoin> leftJoin = findOptional(optimized, LeftJoin.class);
		if (leftJoin.isPresent()) {
			mandatoryRoot = leftJoin.get().getLeftArg();
		}
		collectSocialMediaQ4MandatoryLeafOrder(mandatoryRoot, leaves);
		return leaves;
	}

	private static void collectSocialMediaQ4MandatoryLeafOrder(TupleExpr tupleExpr, List<String> leaves) {
		if (tupleExpr instanceof Join join) {
			collectSocialMediaQ4MandatoryLeafOrder(join.getLeftArg(), leaves);
			collectSocialMediaQ4MandatoryLeafOrder(join.getRightArg(), leaves);
			return;
		}
		if (tupleExpr instanceof Filter filter) {
			if (containsNotExists(filter.getCondition())) {
				leaves.add("u-restriction");
				return;
			}
			collectSocialMediaQ4MandatoryLeafOrder(filter.getArg(), leaves);
			return;
		}
		if (tupleExpr instanceof StatementPattern statementPattern) {
			if (SOCIAL_FOLLOWS.equals(statementPattern.getPredicateVar().getValue())) {
				leaves.add("follows");
			}
			return;
		}
		if (tupleExpr instanceof UnaryTupleOperator) {
			collectSocialMediaQ4MandatoryLeafOrder(((UnaryTupleOperator) tupleExpr).getArg(), leaves);
		}
	}

	private static boolean containsNotExists(QueryModelNode node) {
		List<Not> matches = new ArrayList<>(1);
		node.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Not node) {
				matches.add(node);
			}
		});
		return !matches.isEmpty();
	}

	private static Filter findFirstNotExistsFilter(TupleExpr tupleExpr) {
		List<Filter> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Filter node) {
				if (matches.isEmpty() && containsNotExists(node.getCondition())) {
					matches.add(node);
				}
				super.meet(node);
			}
		});
		assertTrue(!matches.isEmpty(), "Expected a FILTER NOT EXISTS in optimized q4 plan");
		return matches.getFirst();
	}

	private static void collectStatementPatterns(TupleExpr tupleExpr, List<StatementPattern> patterns) {
		if (tupleExpr instanceof StatementPattern) {
			patterns.add((StatementPattern) tupleExpr);
			return;
		}
		if (tupleExpr instanceof Join join) {
			collectStatementPatterns(join.getLeftArg(), patterns);
			collectStatementPatterns(join.getRightArg(), patterns);
			return;
		}
		if (tupleExpr instanceof Filter filter) {
			collectStatementPatterns(filter.getArg(), patterns);
			return;
		}
		if (tupleExpr instanceof UnaryTupleOperator unaryTupleOperator) {
			collectStatementPatterns(unaryTupleOperator.getArg(), patterns);
		}
	}

	private static boolean containsBindingSetAssignmentFor(TupleExpr tupleExpr, String bindingName) {
		return findBindingSetAssignment(tupleExpr, bindingName).isPresent();
	}

	private static Optional<BindingSetAssignment> findBindingSetAssignment(TupleExpr tupleExpr, String bindingName) {
		List<BindingSetAssignment> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(BindingSetAssignment node) {
				if (node.getBindingNames().contains(bindingName)) {
					matches.add(node);
				}
				super.meet(node);
			}
		});
		return matches.stream().findFirst();
	}

	private static int countBindingSets(BindingSetAssignment assignment) {
		int count = 0;
		for (BindingSet ignored : assignment.getBindingSets()) {
			count++;
		}
		return count;
	}

	private static int countResults(SailRepositoryConnection connection, String query) {
		try (TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
			int count = 0;
			while (result.hasNext()) {
				result.next();
				count++;
			}
			return count;
		}
	}

	private static int countOccurrences(String value, String needle) {
		int count = 0;
		int index = 0;
		while ((index = value.indexOf(needle, index)) >= 0) {
			count++;
			index += needle.length();
		}
		return count;
	}

	private static Optional<StatementPattern> findStatementPatternByPredicate(TupleExpr tupleExpr, IRI predicate) {
		List<StatementPattern> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(StatementPattern node) {
				if (node.getPredicateVar() != null && predicate.equals(node.getPredicateVar().getValue())) {
					matches.add(node);
				}
				super.meet(node);
			}
		});
		return matches.stream().findFirst();
	}

	private static boolean containsCodeEqualityFilter(TupleExpr tupleExpr) {
		List<Compare> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Compare node) {
				if (node.getOperator() == Compare.CompareOp.EQ && compareReferencesCodeConstant(node)) {
					matches.add(node);
				}
				super.meet(node);
			}
		});
		return !matches.isEmpty();
	}

	private static boolean containsSameTerm(TupleExpr tupleExpr, String left, String right) {
		return containsBinaryValueOperator(tupleExpr, SameTerm.class, left, right);
	}

	private static boolean containsCompare(TupleExpr tupleExpr, String left, String right) {
		return containsBinaryValueOperator(tupleExpr, Compare.class, left, right);
	}

	private static boolean containsEmptySet(TupleExpr tupleExpr) {
		List<EmptySet> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(EmptySet node) {
				matches.add(node);
				super.meet(node);
			}
		});
		return !matches.isEmpty();
	}

	private static boolean containsBinaryValueOperator(TupleExpr tupleExpr,
			Class<? extends org.eclipse.rdf4j.query.algebra.BinaryValueOperator> type, String left, String right) {
		List<org.eclipse.rdf4j.query.algebra.BinaryValueOperator> matches = new ArrayList<>(1);
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			protected void meetNode(QueryModelNode node) {
				if (type.isInstance(node)) {
					org.eclipse.rdf4j.query.algebra.BinaryValueOperator operator = type.cast(node);
					if (sameVars(operator.getLeftArg(), operator.getRightArg(), left, right)) {
						matches.add(operator);
					}
				}
				super.meetNode(node);
			}
		});
		return !matches.isEmpty();
	}

	private static boolean sameVars(ValueExpr leftArg, ValueExpr rightArg, String left, String right) {
		return varName(leftArg).filter(left::equals).isPresent()
				&& varName(rightArg).filter(right::equals).isPresent()
				|| varName(leftArg).filter(right::equals).isPresent()
						&& varName(rightArg).filter(left::equals).isPresent();
	}

	private static Optional<String> varName(ValueExpr valueExpr) {
		if (valueExpr instanceof Var var && !var.hasValue()) {
			return Optional.of(var.getName());
		}
		return Optional.empty();
	}

	private static boolean compareReferencesCodeConstant(Compare compare) {
		return valueExprReferencesCodeConstant(compare.getLeftArg())
				|| valueExprReferencesCodeConstant(compare.getRightArg());
	}

	private static boolean valueExprReferencesCodeConstant(QueryModelNode node) {
		return node instanceof ValueConstant valueConstant
				&& ("MED-1000".equals(valueConstant.getValue().stringValue())
						|| "MED-1001".equals(valueConstant.getValue().stringValue()));
	}

	private static <T extends QueryModelNode> T findFirst(QueryModelNode root, Class<T> type) {
		return findOptional(root, type).orElseThrow();
	}

	private static <T extends QueryModelNode> Optional<T> findOptional(QueryModelNode root, Class<T> type) {
		List<T> matches = new ArrayList<>(1);
		root.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			protected void meetNode(QueryModelNode node) throws RuntimeException {
				if (matches.isEmpty() && type.isInstance(node)) {
					matches.add(type.cast(node));
				}
				super.meetNode(node);
			}
		});
		return matches.stream().findFirst();
	}

	private static void assertTestPassesWithinAttempts(File dataDir, String testName, TestAttempt testAttempt)
			throws Exception {
		Throwable lastFailure = null;
		for (int attempt = 1; attempt <= TEST_RERUN_ATTEMPTS; attempt++) {
			File attemptDir = new File(dataDir, "attempt-" + attempt);
			Files.createDirectories(attemptDir.toPath());
			try {
				testAttempt.run(attemptDir);
				return;
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				throw e;
			} catch (AssertionError | RuntimeException e) {
				lastFailure = e;
			} catch (Exception e) {
				lastFailure = e;
			}
			if (attempt < TEST_RERUN_ATTEMPTS) {
				Thread.sleep(RETRY_PAUSE_MILLIS);
			}
		}
		failAfterRetries("Test \"" + testName + "\" did not pass within " + TEST_RERUN_ATTEMPTS
				+ " full attempts", lastFailure);
	}

	private static void failAfterRetries(String message, Throwable failure) throws Exception {
		if (failure instanceof AssertionError assertionError) {
			AssertionError error = new AssertionError(message);
			error.addSuppressed(assertionError);
			throw error;
		}
		if (failure instanceof RuntimeException runtimeException) {
			throw new RuntimeException(message, runtimeException);
		}
		if (failure instanceof Exception exception) {
			throw exception;
		}
		throw new AssertionError(message);
	}

	@FunctionalInterface
	private interface TestAttempt {
		void run(File attemptDir) throws Exception;
	}
}
