/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedQueue;

import org.junit.jupiter.api.Test;

/**
 * Tests the builder's own predicate partitioning: when the source can weigh its predicates, the contiguous chunks it
 * cuts must carry roughly equal statement counts instead of equal numbers of predicates.
 */
class LmdbPagedCsfWeightedPredicateSplitTest {

	private static final int PREDICATE_COUNT = 20;
	private static final int HEAVY_ORDINAL = 10;
	private static final int HEAVY_STATEMENTS = 400;
	private static final int LIGHT_STATEMENTS = 2;
	private static final int BUILD_THREADS = 2;

	@Test
	void theHeavyPredicateGetsAChunkOfItsOwn() throws Exception {
		LmdbAdjacencyMemoryAccount account = new LmdbAdjacencyMemoryAccount(1L << 30);
		List<long[]> chunks;
		try (SkewedFamily family = new SkewedFamily(true);
				LmdbInMemoryAdjacencyIndex index = LmdbPagedCsfBaseBuilder.build(family,
						LmdbAdjacencyCoverage.full(), account, 1L << 20, 1L << 16, BUILD_THREADS, null)) {
			assertThat(index.statementCount()).isEqualTo(totalStatements());
			chunks = family.distinctChunks();
		}
		assertThat(account.totalChargedBytes()).isZero();

		assertThat(chunks).hasSizeGreaterThan(1);
		assertCoversEveryPredicateOnce(chunks);

		long[] heavyChunk = chunks.stream()
				.filter(chunk -> Arrays.stream(chunk).anyMatch(p -> p == predicate(HEAVY_ORDINAL)))
				.findFirst()
				.orElseThrow();
		assertThat(heavyChunk)
				.as("the predicate holding %s of %s statements must not share a chunk", HEAVY_STATEMENTS,
						totalStatements())
				.hasSize(1);
	}

	/**
	 * The behaviour this replaces: without weights the catalog is cut into equal counts of predicates, so the heavy
	 * predicate is bundled with its neighbours. Keeping that path exercised proves the weighting is an optional
	 * refinement rather than a new requirement.
	 */
	@Test
	void withoutWeightsTheSplitStaysEvenByPredicateCount() throws Exception {
		LmdbAdjacencyMemoryAccount account = new LmdbAdjacencyMemoryAccount(1L << 30);
		List<long[]> chunks;
		try (SkewedFamily family = new SkewedFamily(false);
				LmdbInMemoryAdjacencyIndex index = LmdbPagedCsfBaseBuilder.build(family,
						LmdbAdjacencyCoverage.full(), account, 1L << 20, 1L << 16, BUILD_THREADS, null)) {
			assertThat(index.statementCount()).isEqualTo(totalStatements());
			chunks = family.distinctChunks();
		}
		assertThat(account.totalChargedBytes()).isZero();

		assertCoversEveryPredicateOnce(chunks);
		long[] heavyChunk = chunks.stream()
				.filter(chunk -> Arrays.stream(chunk).anyMatch(p -> p == predicate(HEAVY_ORDINAL)))
				.findFirst()
				.orElseThrow();
		assertThat(heavyChunk).hasSizeGreaterThan(1);
	}

	private static void assertCoversEveryPredicateOnce(List<long[]> chunks) {
		Set<Long> seen = new LinkedHashSet<>();
		for (long[] chunk : chunks) {
			for (long predicate : chunk) {
				assertThat(seen.add(predicate)).as("predicate %s appears in two chunks", predicate).isTrue();
			}
		}
		assertThat(seen).hasSize(PREDICATE_COUNT);
	}

	private static int totalStatements() {
		return HEAVY_STATEMENTS + (PREDICATE_COUNT - 1) * LIGHT_STATEMENTS;
	}

	private static long predicate(int ordinal) {
		return ValueIds.createId(ValueIds.T_URI, 10 + ordinal);
	}

	private static int statementsOf(int ordinal) {
		return ordinal == HEAVY_ORDINAL ? HEAVY_STATEMENTS : LIGHT_STATEMENTS;
	}

	private static final class SkewedFamily implements AdjacencySourceFamily {

		private final SkewedScanner[] scanners;
		private final ConcurrentLinkedQueue<long[]> observedChunks = new ConcurrentLinkedQueue<>();

		private SkewedFamily(boolean weighed) {
			scanners = new SkewedScanner[BUILD_THREADS];
			for (int i = 0; i < scanners.length; i++) {
				scanners[i] = new SkewedScanner(this, weighed);
			}
		}

		private void observe(LmdbAdjacencyCoverage coverage) {
			int count = coverage.selectedPredicateCount();
			long[] chunk = new long[count];
			for (int i = 0; i < count; i++) {
				chunk[i] = coverage.selectedPredicateAt(i);
			}
			observedChunks.add(chunk);
		}

		/** The distinct predicate chunks the builder asked for, in first-seen order. */
		private List<long[]> distinctChunks() {
			List<long[]> distinct = new ArrayList<>();
			for (long[] chunk : observedChunks) {
				if (distinct.stream().noneMatch(seen -> Arrays.equals(seen, chunk))) {
					distinct.add(chunk);
				}
			}
			return distinct;
		}

		@Override
		public AdjacencySourceScanner primary() {
			return scanners[0];
		}

		@Override
		public AdjacencySourceScanner scanner(int plane) {
			return scanners[plane % scanners.length];
		}

		@Override
		public int workerScannerCount() {
			return scanners.length;
		}

		@Override
		public AdjacencySourceScanner workerScanner(int worker) {
			return scanners[worker];
		}

		@Override
		public boolean isPlaneActive(int plane) {
			return plane < 2;
		}

		@Override
		public int activeStreamCount() {
			return 2;
		}

		@Override
		public long snapshotRevision() {
			return 7;
		}

		@Override
		public void cancel() {
		}

		@Override
		public void close() {
		}
	}

	private static final class SkewedScanner implements AdjacencySourceScanner {

		private final SkewedFamily family;
		private final boolean weighed;

		private SkewedScanner(SkewedFamily family, boolean weighed) {
			this.family = family;
			this.weighed = weighed;
		}

		@Override
		public void scanPredicates(PredicateConsumer consumer) {
			for (int ordinal = 0; ordinal < PREDICATE_COUNT; ordinal++) {
				consumer.predicate(predicate(ordinal));
			}
		}

		@Override
		public void scanContexts(ContextConsumer consumer) {
		}

		@Override
		public boolean supportsPredicatePartitionedScan(boolean outgoing) {
			return true;
		}

		@Override
		public long[] approximatePredicateStatementCounts(int plane, long[] sortedPredicates) {
			if (!weighed) {
				return null;
			}
			long[] weights = new long[sortedPredicates.length];
			for (int ordinal = 0; ordinal < weights.length; ordinal++) {
				weights[ordinal] = statementsOf(ordinal);
			}
			return weights;
		}

		@Override
		public void scanOutgoing(boolean explicit, GroupConsumer consumer) {
			scanOutgoing(explicit, LmdbAdjacencyCoverage.full(), consumer);
		}

		@Override
		public void scanOutgoing(boolean explicit, LmdbAdjacencyCoverage coverage, GroupConsumer consumer) {
			scan(true, explicit, coverage, consumer);
		}

		@Override
		public void scanIncoming(boolean explicit, GroupConsumer consumer) {
			scanIncoming(explicit, LmdbAdjacencyCoverage.full(), consumer);
		}

		@Override
		public void scanIncoming(boolean explicit, LmdbAdjacencyCoverage coverage, GroupConsumer consumer) {
			scan(false, explicit, coverage, consumer);
		}

		private void scan(boolean outgoing, boolean explicit, LmdbAdjacencyCoverage coverage,
				GroupConsumer consumer) {
			family.observe(coverage);
			int plane = outgoing
					? explicit ? LmdbAdjacencyPlane.PLANE_OUTGOING_EXPLICIT
							: LmdbAdjacencyPlane.PLANE_OUTGOING_INFERRED
					: explicit ? LmdbAdjacencyPlane.PLANE_INCOMING_EXPLICIT
							: LmdbAdjacencyPlane.PLANE_INCOMING_INFERRED;
			for (int ordinal = 0; ordinal < PREDICATE_COUNT; ordinal++) {
				long predicate = predicate(ordinal);
				if (!coverage.covers(predicate)) {
					continue;
				}
				int statements = statementsOf(ordinal);
				for (int i = 0; i < statements; i++) {
					consumer.begin(ValueIds.createId(ValueIds.T_URI, 100_000 + i), predicate, plane);
					consumer.pair(ValueIds.createId(ValueIds.T_URI, 900_000 + i), 0);
					consumer.end();
				}
			}
		}

		@Override
		public long snapshotRevision() {
			return 7;
		}

		@Override
		public long snapshotId() {
			return 11;
		}

		@Override
		public void ensureSnapshotValid() {
		}

		@Override
		public void close() {
		}
	}
}
