/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.iteration.QueryExecutionDeadline;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.http.client.QueryExecutionContext;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryInterruptedException;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.ValueExprEvaluationException;
import org.eclipse.rdf4j.query.algebra.evaluation.function.Function;
import org.eclipse.rdf4j.query.algebra.evaluation.function.FunctionRegistry;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.SailConnection;
import org.eclipse.rdf4j.sail.SailException;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;

class LmdbReplayContextAdmissionTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI QUERY_SUBJECT_ONE = VF.createIRI("urn:lmdb:worker-context:query-one");
	private static final IRI QUERY_SUBJECT_TWO = VF.createIRI("urn:lmdb:worker-context:query-two");
	private static final IRI QUERY_PREDICATE = VF.createIRI("urn:lmdb:worker-context:query-predicate");
	private static final IRI PROBE_SUBJECT = VF.createIRI("urn:lmdb:worker-context:probe");
	private static final IRI PROBE_PREDICATE = VF.createIRI("urn:lmdb:worker-context:probe-predicate");

	@Test
	@Timeout(value = 60, unit = TimeUnit.SECONDS)
	void capturedReadContextAdmitsOnlyItsDescendantOnAReusedWorker(@TempDir Path dataDirectory) throws Exception {
		String functionIri = "urn:lmdb:worker-context:function:" + UUID.randomUUID();
		AtomicBoolean writerFinished = new AtomicBoolean();
		FunctionRegistry registry = FunctionRegistry.getInstance();
		LmdbStore store = new LmdbStore(dataDirectory.toFile(), new LmdbStoreConfig("spoc,posc")
				.setForceSync(true)
				.setTripleDBSize(2L * 1024L * 1024L)
				.setValueDBSize(64L * 1024L * 1024L)
				.setMapGrowthReadDrainTimeoutMillis(15_000)
				.setAutoGrow(true));
		store.setDefaultIsolationLevel(IsolationLevels.READ_COMMITTED);
		SailRepository repository = new SailRepository(store);
		ExecutorService queryExecutor = Executors.newSingleThreadExecutor();
		ExecutorService workerExecutor = Executors.newSingleThreadExecutor();
		ExecutorService writerExecutor = Executors.newSingleThreadExecutor();
		WorkerReadFunction function = new WorkerReadFunction(functionIri, workerExecutor, writerFinished);
		Future<?> queryFuture = null;
		Future<Void> writerFuture = null;
		CountDownLatch queryResultClosed = new CountDownLatch(1);
		CountDownLatch allowReaderConnectionClose = new CountDownLatch(1);
		CountDownLatch writerWarningStarted = new CountDownLatch(1);
		CountDownLatch allowWriterCommit = new CountDownLatch(1);
		try {
			repository.init();
			function.setBackingStore(store.getBackingStore());
			registry.add(function);
			try (RepositoryConnection seed = repository.getConnection()) {
				seed.add(QUERY_SUBJECT_ONE, QUERY_PREDICATE, VF.createLiteral("query-one"));
				seed.add(QUERY_SUBJECT_TWO, QUERY_PREDICATE, VF.createLiteral("query-two"));
				seed.add(PROBE_SUBJECT, PROBE_PREDICATE, VF.createLiteral("before"));
			}

			LmdbSailStore backingStore = store.getBackingStore();
			MapGrowthMetrics.Snapshot before = backingStore.growthMetricsSnapshot();
			String queryString = "SELECT ?value WHERE { ?subject <" + QUERY_PREDICATE.stringValue()
					+ "> ?value . FILTER(<" + functionIri + ">(?value)) }";
			queryFuture = queryExecutor.submit(() -> {
				Throwable queryFailure = null;
				try (RepositoryConnection reader = repository.getConnection()) {
					function.setConnection(((SailRepositoryConnection) reader).getSailConnection());
					TupleQuery tupleQuery = reader.prepareTupleQuery(QueryLanguage.SPARQL, queryString);
					tupleQuery.setMaxExecutionTime(20);
					try (TupleQueryResult results = tupleQuery.evaluate()) {
						if (!results.hasNext()) {
							throw new AssertionError("the query must expose its first row before growth starts");
						}
						BindingSet first = results.next();
						assertNotNull(first.getValue("value"));
						function.firstQueryResultObserved.countDown();
						while (results.hasNext()) {
							results.next();
						}
					} catch (Throwable failure) {
						queryFailure = failure;
					} finally {
						queryResultClosed.countDown();
					}
					if (!allowReaderConnectionClose.await(30, TimeUnit.SECONDS)) {
						throw new AssertionError("the test did not release the reader connection");
					}
				} catch (Throwable failure) {
					if (queryFailure == null) {
						queryFailure = failure;
					}
					queryResultClosed.countDown();
				}
				return queryFailure;
			});

			assertTrue(function.firstQueryResultObserved.await(10, TimeUnit.SECONDS),
					"the first output must be observed before the worker callback starts");
			assertTrue(function.secondFunctionInvocation.await(10, TimeUnit.SECONDS),
					"the next function callback must run inside the admitted query read");

			writerFuture = writerExecutor.submit(() -> {
				try (SailConnection writer = store.getConnection()) {
					writer.begin(IsolationLevels.SNAPSHOT);
					writer.clear();
					writerWarningStarted.countDown();
					if (!allowWriterCommit.await(30, TimeUnit.SECONDS)) {
						throw new AssertionError("the test did not release the warning writer");
					}
					writer.commit();
				} finally {
					writerFinished.set(true);
				}
				return null;
			});
			assertTrue(writerWarningStarted.await(10, TimeUnit.SECONDS),
					"the snapshot clear must establish its advisory growth warning");
			awaitStartedGrowthAdmissionClosure(backingStore, before, writerFuture);
			assertTrue(backingStore.growthAdmissionClosed(), "the writer must close read admission");
			assertFalse(writerFinished.get(), "the writer must remain active while the query owns its read attempt");
			function.allowWorkerRead.countDown();

			assertTrue(function.capturedReadCompleted.await(3, TimeUnit.SECONDS),
					"a captured-context descendant must finish while growth admission remains closed");
			assertTrue(function.captureHadContext.get(), "the active query callback must capture its replay context");
			assertTrue(function.captureHadDeadline.get(), "the captured replay context must retain the query deadline");
			assertEquals(Set.of("before"), function.capturedValues.get(),
					"the descendant must read from the exact epoch admitted by the query");
			assertTrue(function.capturedReadDuringGrowth.get(),
					"the descendant must finish before the independently admitted writer completes");
			assertTrue(function.unrelatedReadCompleted.await(3, TimeUnit.SECONDS),
					"the reused worker must finish its unrelated deadline-bound read");
			WorkerReadResult unrelatedRead = function.unrelatedRead.get();
			assertNotNull(unrelatedRead);
			assertNotNull(unrelatedRead.capturedWorkerThread());
			assertSame(unrelatedRead.capturedWorkerThread(), unrelatedRead.unrelatedWorkerThread(),
					"the captured and unrelated operations must use the same worker thread");
			assertTrue(unrelatedRead.interruptedByDeadline(),
					"the unrelated operation must time out instead of inheriting the captured read admission");
			assertTrue(unrelatedRead.growthStillActive(),
					"the unrelated read must time out while the growth gate is still shut");
			assertTrue(unrelatedRead.admissionWaitCountDelta() > 0,
					"the unrelated read must actually wait for admission before timing out");
			assertTrue(unrelatedRead.admissionTimeoutCountDelta() > 0,
					"the deadline timeout must be recorded by LMDB admission");
			assertEquals(2, function.invocationCount.get(),
					"the already-observed query row must not cause its function callback to be replayed");

			assertTrue(queryResultClosed.await(10, TimeUnit.SECONDS), "the query result must close after its callback");
			allowWriterCommit.countDown();
			writerFuture.get(20, TimeUnit.SECONDS);
			assertTrue(backingStore.growthMetricsSnapshot().growthEpisodes() > before.growthEpisodes(),
					"the clear warning must register a bounded LMDB growth episode");
			Future<Set<String>> postCommitRead = workerExecutor.submit(() -> readProbeValues(function.connection()));
			assertEquals(Set.of(), postCommitRead.get(10, TimeUnit.SECONDS),
					"a later independent read on the reused worker must observe the committed clear");
			allowReaderConnectionClose.countDown();
			assertNull(queryFuture.get(10, TimeUnit.SECONDS), "the query must complete without callback failures");
		} finally {
			function.allowWorkerRead.countDown();
			allowReaderConnectionClose.countDown();
			allowWriterCommit.countDown();
			queryExecutor.shutdown();
			assertTrue(queryExecutor.awaitTermination(25, TimeUnit.SECONDS), "the query worker must terminate");
			if (writerFuture != null) {
				writerFuture.get(20, TimeUnit.SECONDS);
			}
			workerExecutor.shutdown();
			if (!workerExecutor.awaitTermination(15, TimeUnit.SECONDS)) {
				workerExecutor.shutdownNow();
				assertTrue(workerExecutor.awaitTermination(5, TimeUnit.SECONDS),
						"the captured read worker must terminate");
			}
			writerExecutor.shutdown();
			assertTrue(writerExecutor.awaitTermination(10, TimeUnit.SECONDS), "the writer worker must terminate");
			registry.remove(function);
			repository.shutDown();
		}
	}

	private static void awaitStartedGrowthAdmissionClosure(LmdbSailStore backingStore,
			MapGrowthMetrics.Snapshot before, Future<?> writer) throws Exception {
		long deadlineNanos = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
		while (true) {
			if (backingStore.growthMetricsSnapshot().growthEpisodes() > before.growthEpisodes()
					&& backingStore.growthAdmissionClosed()) {
				return;
			}
			if (writer.isDone()) {
				writer.get();
				throw new AssertionError("the writer completed without closing growth admission");
			}
			if (System.nanoTime() >= deadlineNanos) {
				throw new AssertionError("timed out waiting for growth admission to close");
			}
			Thread.yield();
		}
	}

	private static Set<String> readProbeValues(SailConnection connection) {
		Set<String> values = new HashSet<>();
		try (CloseableIteration<? extends Statement> statements = connection.getStatements(PROBE_SUBJECT,
				PROBE_PREDICATE, null, false)) {
			while (statements.hasNext()) {
				Value value = statements.next().getObject();
				values.add(value.stringValue());
			}
			return values;
		} catch (SailException failure) {
			throw new RuntimeException(failure);
		}
	}

	private static boolean hasCause(Throwable failure, Class<? extends Throwable> type) {
		for (Throwable current = failure; current != null; current = current.getCause()) {
			if (type.isInstance(current)) {
				return true;
			}
		}
		return false;
	}

	private record WorkerReadResult(Thread capturedWorkerThread, Thread unrelatedWorkerThread,
			boolean interruptedByDeadline, boolean growthStillActive, long admissionWaitCountDelta,
			long admissionTimeoutCountDelta) {
	}

	private static final class WorkerReadFunction implements Function {
		private final String functionIri;
		private final ExecutorService workerExecutor;
		private final AtomicBoolean writerFinished;
		private volatile LmdbSailStore backingStore;
		private final CountDownLatch firstQueryResultObserved = new CountDownLatch(1);
		private final CountDownLatch secondFunctionInvocation = new CountDownLatch(1);
		private final CountDownLatch allowWorkerRead = new CountDownLatch(1);
		private final CountDownLatch capturedReadCompleted = new CountDownLatch(1);
		private final CountDownLatch unrelatedReadCompleted = new CountDownLatch(1);
		private final AtomicInteger invocationCount = new AtomicInteger();
		private final AtomicBoolean captureHadContext = new AtomicBoolean();
		private final AtomicBoolean captureHadDeadline = new AtomicBoolean();
		private final AtomicBoolean capturedReadDuringGrowth = new AtomicBoolean();
		private final AtomicReference<Thread> capturedWorkerThread = new AtomicReference<>();
		private final AtomicReference<Set<String>> capturedValues = new AtomicReference<>();
		private final AtomicReference<WorkerReadResult> unrelatedRead = new AtomicReference<>();
		private volatile SailConnection connection;

		private WorkerReadFunction(String functionIri, ExecutorService workerExecutor, AtomicBoolean writerFinished) {
			this.functionIri = functionIri;
			this.workerExecutor = workerExecutor;
			this.writerFinished = writerFinished;
		}

		private void setBackingStore(LmdbSailStore backingStore) {
			this.backingStore = backingStore;
		}

		private SailConnection connection() {
			return connection;
		}

		private void setConnection(SailConnection connection) {
			this.connection = connection;
		}

		@Override
		public String getURI() {
			return functionIri;
		}

		@Override
		public Value evaluate(ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException {
			return valueFactory.createLiteral(true);
		}

		@Override
		public Value evaluate(TripleSource tripleSource, Value... args) throws ValueExprEvaluationException {
			int invocation = invocationCount.incrementAndGet();
			if (invocation == 1) {
				return tripleSource.getValueFactory().createLiteral(true);
			}
			if (invocation != 2) {
				return tripleSource.getValueFactory().createLiteral(true);
			}

			try {
				if (!firstQueryResultObserved.await(10, TimeUnit.SECONDS)) {
					throw new ValueExprEvaluationException(
							"The first query result was not observed before the next callback");
				}
			} catch (InterruptedException failure) {
				Thread.currentThread().interrupt();
				throw new ValueExprEvaluationException("Interrupted while awaiting the first query result", failure);
			}

			QueryExecutionContext.ReplayContext context = QueryExecutionContext.captureReplayContext();
			captureHadContext.set(context != null);
			captureHadDeadline.set(QueryExecutionDeadline.current() != null);
			secondFunctionInvocation.countDown();
			try {
				if (!allowWorkerRead.await(15, TimeUnit.SECONDS) || context == null) {
					return tripleSource.getValueFactory().createLiteral(true);
				}

				Future<Set<String>> captured = workerExecutor.submit(() -> {
					capturedWorkerThread.set(Thread.currentThread());
					Set<String> values = context.get(() -> readProbeValues(connection));
					capturedValues.set(values);
					capturedReadDuringGrowth.set(backingStore.growthAdmissionClosed() && !writerFinished.get());
					capturedReadCompleted.countDown();
					return values;
				});
				try {
					captured.get(4, TimeUnit.SECONDS);
				} catch (TimeoutException | ExecutionException failure) {
					return tripleSource.getValueFactory().createLiteral(true);
				}

				MapGrowthMetrics.Snapshot beforeUnrelatedRead = backingStore.growthMetricsSnapshot();
				Future<WorkerReadResult> unrelated = workerExecutor.submit(() -> {
					Thread unrelatedWorkerThread = Thread.currentThread();
					Throwable failure = null;
					try (QueryExecutionDeadline deadline = QueryExecutionDeadline.start(250);
							QueryExecutionDeadline.Scope ignored = deadline.enter()) {
						readProbeValues(connection);
					} catch (Throwable readFailure) {
						failure = readFailure;
					}
					MapGrowthMetrics.Snapshot afterUnrelatedRead = backingStore.growthMetricsSnapshot();
					return new WorkerReadResult(capturedWorkerThread.get(), unrelatedWorkerThread,
							hasCause(failure, QueryInterruptedException.class),
							backingStore.growthAdmissionClosed() && !writerFinished.get(),
							afterUnrelatedRead.admissionWaitCount() - beforeUnrelatedRead.admissionWaitCount(),
							afterUnrelatedRead.admissionTimeouts() - beforeUnrelatedRead.admissionTimeouts());
				});
				unrelatedRead.set(unrelated.get(3, TimeUnit.SECONDS));
				unrelatedReadCompleted.countDown();
			} catch (InterruptedException failure) {
				Thread.currentThread().interrupt();
				throw new ValueExprEvaluationException("Interrupted while waiting for worker read completion", failure);
			} catch (ExecutionException | TimeoutException failure) {
				throw new ValueExprEvaluationException("Worker read did not complete within the test bound", failure);
			}
			return tripleSource.getValueFactory().createLiteral(true);
		}
	}
}
