/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.util.Values;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;

/** Standalone observational startup/commit workload; use scripts/run-single-benchmark.sh --main-class. */
public final class LmdbAsyncStartupProfile {
	private LmdbAsyncStartupProfile() {
	}

	public static void main(String[] args) throws Exception {
		int statements = args.length == 0 ? 100_000 : Integer.parseInt(args[0]);
		int commits = args.length < 2 ? 2_000 : Integer.parseInt(args[1]);
		boolean preallocated = args.length > 2 && args[2].equals("preallocated");
		Path directory = Files.createTempDirectory("rdf4j-async-startup-profile-");
		System.out
				.println("PROFILE directory=" + directory + ", seedStatements=" + statements + ", commits=" + commits);
		LmdbStoreConfig seedConfig = configuration(preallocated).setDirectAdjacencyMode(DirectAdjacencyMode.DISABLED);
		SailRepository seed = new SailRepository(new LmdbStore(directory.toFile(), seedConfig));
		seed.init();
		try (var connection = seed.getConnection()) {
			connection.begin();
			for (int i = 0; i < statements; i++) {
				connection.add(Values.iri("urn:seed:" + i), Values.iri("urn:predicate:" + i % 16),
						Values.iri("urn:object:" + i % 1024));
			}
			connection.commit();
		} finally {
			seed.shutDown();
		}
		LmdbStore sail = new LmdbStore(directory.toFile(), configuration(preallocated)
				.setDirectAdjacencyMaxBytes(512L << 20));
		SailRepository repository = new SailRepository(sail);
		long start = System.nanoTime();
		repository.init();
		long initialized = System.nanoTime();
		try {
			LmdbDirectAdjacencyStore adjacency = sail.getBackingStore().directAdjacencyStore();
			AtomicInteger preparing = new AtomicInteger();
			AtomicInteger overlappingPhysicalCommits = new AtomicInteger();
			adjacency.beforePreparationForTest = preparing::incrementAndGet;
			adjacency.afterPreparationForTest = preparing::decrementAndGet;
			adjacency.beforePreparedFinalizeWaitForTest = () -> {
				if (preparing.get() > 0) {
					overlappingPhysicalCommits.incrementAndGet();
				}
			};
			write(repository, "startup", commits);
			if (!sail.awaitDirectAdjacencyReady(120, TimeUnit.SECONDS)) {
				throw new IllegalStateException(sail.getDirectAdjacencyReadinessDescription());
			}
			System.out.println("PROFILE startup.initMillis=" + (initialized - start) / 1_000_000.0
					+ ", startup.writesAndReadinessMillis=" + (System.nanoTime() - initialized) / 1_000_000.0);
			System.out.println("PROFILE startup " + sail.getDirectAdjacencyReadinessDescription());
			System.out.println("PROFILE cutover.millis=" + adjacency.lastCutoverNanos() / 1_000_000.0
					+ ", cutover.revisions=" + adjacency.lastCutoverRevisions());
			long steadyStarted = System.nanoTime();
			write(repository, "steady", commits);
			System.out
					.println("PROFILE steady.transactionMicros="
							+ (System.nanoTime() - steadyStarted) / 1_000.0 / commits);
			System.out.println("PROFILE steady " + sail.getDirectAdjacencyReadinessDescription());
			System.out.println("PROFILE overlap.physicalCommitsFinishingDuringPreparation="
					+ overlappingPhysicalCommits.get());
			System.out.println("PROFILE phases " + adjacency.phaseTimings());
		} finally {
			repository.shutDown();
		}
	}

	private static LmdbStoreConfig configuration(boolean preallocated) {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc,ospc");
		if (preallocated) {
			config.setTripleDBSize(256L << 20);
			config.setValueDBSize(128L << 20);
		}
		return config;
	}

	private static void write(SailRepository repository, String phase, int commits) {
		IRI predicate = Values.iri("urn:predicate:0");
		IRI object = Values.iri("urn:object:0");
		try (var connection = repository.getConnection()) {
			for (int i = 0; i < commits; i++) {
				connection.begin();
				connection.add(Values.iri("urn:" + phase + ":" + i), predicate, object);
				connection.commit();
			}
		}
	}
}
