/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.doCallRealMethod;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.File;
import java.lang.reflect.Field;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.rdf4j.http.client.QueryExecutionContext;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.base.SailSource;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;

class LmdbGrowthCapacityTest {
	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void cleanupFailurePreventsResizeConflictReplay() {
		LmdbSailStore.MapResizeConflictException resizeConflict = new LmdbSailStore.MapResizeConflictException(
				LmdbSailStore.MapResizeKind.TRIPLE_STORE, "test resize conflict");
		RuntimeException replaySignal = assertThrows(QueryExecutionContext.ReplaySafepointException.class, () -> {
			try (QueryExecutionContext.Activation ignored = QueryExecutionContext.activateReplaySafepoint(
					() -> {
						throw resizeConflict;
					})) {
				QueryExecutionContext.checkpointReplaySafepoint();
			}
		});
		replaySignal.addSuppressed(new IllegalStateException("the returned result could not be closed"));

		assertTrue(QueryExecutionContext.isReplaySafepointFailure(replaySignal));
		assertTrue(LmdbStoreConnection.isMapResizeConflict(resizeConflict));
		assertFalse(LmdbStoreConnection.isMapResizeConflict(replaySignal),
				"transparent replay must not discard a failure to release the abandoned result");
	}

	@Test
	void mapGrowthLeavesTheEstimatedWriteAndReserveBelowTheEightyPercentThreshold() {
		long pageSize = 4096L;
		long currentMapSize = 1024L * 1024L;
		long estimatedUsedBytesAfterWrite = 16L * LmdbUtil.MIN_FREE_SPACE;

		long grownMapSize = LmdbUtil.autoGrowMapSize(currentMapSize, pageSize, estimatedUsedBytesAfterWrite);
		long estimatedWithReserve = estimatedUsedBytesAfterWrite + LmdbUtil.MIN_FREE_SPACE;

		assertEquals(0L, grownMapSize % pageSize, "the final map size must align to the native page size");
		assertTrue(estimatedWithReserve * 100L < grownMapSize * LmdbUtil.PERCENTAGE_FULL_TRIGGERS_RESIZE,
				"the predicted write and recent-allocation reserve must remain below the resize threshold");
	}

	@Test
	void namespacePreflightEstimatesTheCompleteResultingSnapshot() throws Exception {
		Map<String, String> existingNamespaces = new LinkedHashMap<>();
		for (int index = 0; index < 512; index++) {
			existingNamespaces.put("prefix-" + index + "-ø", "https://example.org/" + "語".repeat(96) + index);
		}

		String replacedPrefix = "prefix-0-ø";
		String replacementNamespace = "https://example.net/" + "雪".repeat(128);
		Map<String, String> resultingNamespaces = new LinkedHashMap<>(existingNamespaces);
		resultingNamespaces.put(replacedPrefix, replacementNamespace);
		SailSource.WritePreflight preflight = new SailSource.WritePreflight(List.of(),
				List.of(new SailSource.NamespaceUpdate(replacedPrefix, replacementNamespace)), Set.of(), Set.of(),
				false,
				false);

		TripleStore tripleStore = mock(TripleStore.class);
		when(tripleStore.readNamespaceSnapshot()).thenReturn(existingNamespaces);
		when(tripleStore.estimateWriteBytes(anyList())).thenReturn(0L);
		doCallRealMethod().when(tripleStore).estimateWriteBytes(any(SailSource.WritePreflight.class));
		NamespaceStore namespaceStore = new NamespaceStore(new File("unused"), tripleStore);

		long estimatedWriteBytes = LmdbUtil.saturatedAdd(tripleStore.estimateWriteBytes(preflight),
				namespaceStore.estimateEncodedSnapshotBytes(preflight));
		long encodedSnapshotBytes = NamespaceStore.encodeSnapshot(resultingNamespaces).length;
		assertTrue(estimatedWriteBytes >= encodedSnapshotBytes,
				"preflight must include the complete encoded namespace snapshot, not only the updated prefix");

		SailSource.WritePreflight removal = new SailSource.WritePreflight(List.of(), List.of(), Set.of(replacedPrefix),
				Set.of(), false, false);
		Map<String, String> afterRemoval = new LinkedHashMap<>(existingNamespaces);
		afterRemoval.remove(replacedPrefix);
		assertTrue(
				namespaceStore
						.estimateEncodedSnapshotBytes(removal) >= NamespaceStore.encodeSnapshot(afterRemoval).length,
				"removal preflight may overestimate, but must cover the resulting snapshot");

		SailSource.NamespaceUpdate clearedUpdate = new SailSource.NamespaceUpdate("清除", "urn:雪");
		SailSource.WritePreflight clearAndAdd = new SailSource.WritePreflight(List.of(), List.of(clearedUpdate),
				Set.of(),
				Set.of(), false, true);
		Map<String, String> afterClear = Map.of(clearedUpdate.prefix(), clearedUpdate.name());
		assertTrue(
				namespaceStore
						.estimateEncodedSnapshotBytes(clearAndAdd) >= NamespaceStore.encodeSnapshot(afterClear).length,
				"clear and replacement namespace intents must size the post-clear snapshot");

		SailSource.WritePreflight explicit = new SailSource.WritePreflight(List.of(),
				List.of(new SailSource.NamespaceUpdate("explicit", "urn:explicit")), Set.of(), Set.of(), false, false);
		SailSource.WritePreflight inferred = new SailSource.WritePreflight(List.of(),
				List.of(new SailSource.NamespaceUpdate("inferred", "urn:inferred")), Set.of(), Set.of(), false, false);
		SailSource.WritePreflight merged = explicit.merge(inferred);
		Map<String, String> afterMerged = new LinkedHashMap<>(existingNamespaces);
		afterMerged.put("explicit", "urn:explicit");
		afterMerged.put("inferred", "urn:inferred");
		assertTrue(
				namespaceStore
						.estimateEncodedSnapshotBytes(merged) >= NamespaceStore.encodeSnapshot(afterMerged).length,
				"merged explicit and inferred namespace updates must both be included");

		SailSource.WritePreflight statementsOnly = new SailSource.WritePreflight(List.of(), List.of(), Set.of(),
				Set.of(),
				false, false);
		assertEquals(0L, namespaceStore.estimateEncodedSnapshotBytes(statementsOnly),
				"ordinary statement-only writes must not pay for namespace snapshot growth");

		namespaceStore.setNamespace("later", "urn:後");
		assertEquals(NamespaceStore.encodeSnapshot(namespaceStore.snapshot()).length,
				namespaceStore.estimateEncodedSnapshotBytes(removal),
				"adding a namespace must update the cached base snapshot size");
		namespaceStore.setNamespace("later", "urn:改訂");
		assertEquals(NamespaceStore.encodeSnapshot(namespaceStore.snapshot()).length,
				namespaceStore.estimateEncodedSnapshotBytes(removal),
				"replacing a namespace must update the cached encoded size");
		namespaceStore.removeNamespace("later");
		assertEquals(NamespaceStore.encodeSnapshot(namespaceStore.snapshot()).length,
				namespaceStore.estimateEncodedSnapshotBytes(removal),
				"removing a namespace must update the cached encoded size");
		namespaceStore.clear();
		assertEquals(Integer.BYTES, NamespaceStore.encodeSnapshot(namespaceStore.snapshot()).length);
		assertEquals(Integer.BYTES, namespaceStore.estimateEncodedSnapshotBytes(removal),
				"clearing the namespace map must reset the cached encoded size to its header");
		namespaceStore.restore(existingNamespaces);
		assertEquals(NamespaceStore.encodeSnapshot(existingNamespaces).length,
				namespaceStore.estimateEncodedSnapshotBytes(removal),
				"restoring a namespace snapshot must restore its cached encoded size");
	}

	@Test
	void bufferedWholeWritePreflightGrowsBothMapsBeforeBranchPreparation(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(0);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			LmdbSailStore backingStore = store.getBackingStore();
			long initialTripleMapSize = mapSize(backingStore, "tripleStore");
			long initialValueMapSize = mapSize(backingStore, "valueStore");

			try (RepositoryConnection connection = repository.getConnection()) {
				connection.begin();
				for (int index = 0; index < 10_000; index++) {
					connection.add(VF.createIRI("urn:growth-subject:" + index),
							VF.createIRI("urn:growth-predicate"),
							VF.createLiteral("growth-object:" + index));
				}

				connection.prepare();

				assertTrue(mapSize(backingStore, "tripleStore") > initialTripleMapSize,
						"preparing the complete buffered branch write must grow the TripleStore map first");
				assertTrue(mapSize(backingStore, "valueStore") > initialValueMapSize,
						"preparing the complete buffered branch write must grow the ValueStore map first");
				connection.rollback();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 10, unit = TimeUnit.SECONDS)
	void bufferedGrowthWarningBeginsBeforeExplicitPrepareAndRollbackClosesTheEpisode(@TempDir File dataDir)
			throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(30_000);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			LmdbSailStore backingStore = store.getBackingStore();
			long initialTripleMapSize = mapSize(backingStore, "tripleStore");
			long initialValueMapSize = mapSize(backingStore, "valueStore");
			try (RepositoryConnection connection = repository.getConnection()) {
				connection.begin();
				for (int index = 0; index < 10_000; index++) {
					connection.add(VF.createIRI("urn:early-growth-subject:" + index),
							VF.createIRI("urn:early-growth-predicate"),
							VF.createLiteral("early-growth-object:" + index));
				}

				assertTrue(backingStore.growthAdmissionClosed(),
						"buffering a write beyond the warning threshold must close admission and start growth before prepare");
				assertEquals(initialTripleMapSize, mapSize(backingStore, "tripleStore"),
						"the early warning must not resize the TripleStore before validation and preflight");
				assertEquals(initialValueMapSize, mapSize(backingStore, "valueStore"),
						"the early warning must not resize the ValueStore before validation and preflight");
				ExecutorService arrivalExecutor = Executors.newSingleThreadExecutor();
				Future<Boolean> arrival;
				try {
					arrival = arrivalExecutor.submit(() -> {
						try (RepositoryConnection arrivingReader = repository.getConnection()) {
							return arrivingReader.getStatements(null, null, null).hasNext();
						}
					});
					awaitCurrentAdmissionWaiter(backingStore);
					assertTrue(backingStore.growthMetricsSnapshot().currentAdmissionWaiters() > 0,
							"a read arriving after the warning must wait for the writer's shared growth episode");
					connection.rollback();
					assertFalse(arrival.get(5, TimeUnit.SECONDS),
							"the arriving read must continue after the buffered writer rolls back");
				} finally {
					arrivalExecutor.shutdownNow();
					assertTrue(arrivalExecutor.awaitTermination(5, TimeUnit.SECONDS),
							"admission-wait test worker must terminate");
				}
				assertEquals(0, backingStore.growthMetricsSnapshot().currentAdmissionWaiters(),
						"rollback must release every blocked admission");
				assertFalse(backingStore.growthAdmissionClosed(), "rollback must close the growth episode");
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 8, unit = TimeUnit.SECONDS)
	void staleBufferedWarningReopensAdmissionWhileWriterRemainsActive(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(250);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			LmdbSailStore backingStore = store.getBackingStore();
			try (RepositoryConnection writer = repository.getConnection()) {
				writer.begin();
				writer.add(VF.createIRI("urn:warning-expiry:subject"), VF.createIRI("urn:warning-expiry:predicate"),
						VF.createLiteral("x".repeat(1024 * 1024)));
				assertTrue(backingStore.growthAdmissionClosed(),
						"the oversized buffered write must initially close admission");

				awaitGrowthAdmissionOpen(backingStore);
				assertFalse(backingStore.growthAdmissionClosed(),
						"warning expiry must reopen admission before the writer prepares or rolls back");
				assertTrue(writer.isActive(), "warning expiry must not roll back the still-open writer");
				try (RepositoryConnection reader = repository.getConnection()) {
					assertFalse(reader.getStatements(null, null, null).hasNext(),
							"new reads must be admitted after the bounded warning expires");
				}
				writer.rollback();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 8, unit = TimeUnit.SECONDS)
	void expiredBufferedWarningCanBeStartedAgainAfterMoreWrites(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(250);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			LmdbSailStore backingStore = store.getBackingStore();
			try (RepositoryConnection writer = repository.getConnection()) {
				writer.begin();
				writer.add(VF.createIRI("urn:warning-restart:subject:1"),
						VF.createIRI("urn:warning-restart:predicate"),
						VF.createLiteral("x".repeat(1024 * 1024)));
				assertTrue(backingStore.growthAdmissionClosed(),
						"the first oversized buffered write must start an admission warning");

				awaitGrowthAdmissionOpen(backingStore);
				assertFalse(backingStore.growthAdmissionClosed(),
						"the first warning must expire before more writes are added");

				writer.add(VF.createIRI("urn:warning-restart:subject:2"),
						VF.createIRI("urn:warning-restart:predicate"),
						VF.createLiteral("y".repeat(1024 * 1024)));
				assertTrue(backingStore.growthAdmissionClosed(),
						"crossing a later buffered-write threshold must start a fresh warning after expiry");
				writer.rollback();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 8, unit = TimeUnit.SECONDS)
	void laterWriteRenewsWarningWithoutAnInterveningAdmissionProbe(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(250);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try (RepositoryConnection writer = repository.getConnection()) {
			writer.begin();
			writer.add(VF.createIRI("urn:warning-no-probe:subject:1"),
					VF.createIRI("urn:warning-no-probe:predicate"), VF.createLiteral("x".repeat(1024 * 1024)));

			// Let the bounded warning expire without querying coordinator admission or metrics, both of which perform
			// lazy expiry as a side effect.
			TimeUnit.MILLISECONDS.sleep(350);

			writer.add(VF.createIRI("urn:warning-no-probe:subject:2"),
					VF.createIRI("urn:warning-no-probe:predicate"), VF.createLiteral("y".repeat(1024 * 1024)));
			assertTrue(store.getBackingStore().growthAdmissionClosed(),
					"the later write must start a fresh warning even when no reader probes admission after expiry");
			writer.rollback();
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 15, unit = TimeUnit.SECONDS)
	void connectionsOnTheSameThreadKeepDistinctWarningOwners(@TempDir File dataDir) throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L)
				.setMapGrowthReadDrainTimeoutMillis(2_000);
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			LmdbSailStore backingStore = store.getBackingStore();
			try (RepositoryConnection firstWriter = repository.getConnection();
					RepositoryConnection secondWriter = repository.getConnection()) {
				firstWriter.begin();
				secondWriter.begin();
				firstWriter.add(VF.createIRI("urn:warning-owner:first"), VF.createIRI("urn:warning-owner:predicate"),
						VF.createLiteral("x".repeat(1024 * 1024)));
				assertTrue(backingStore.growthAdmissionClosed(),
						"the first connection must start its warning before the second writer buffers data");

				long startNanos = System.nanoTime();
				secondWriter.add(VF.createIRI("urn:warning-owner:second"),
						VF.createIRI("urn:warning-owner:predicate"), VF.createLiteral("y".repeat(1024 * 1024)));
				long elapsedMillis = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - startNanos);
				assertTrue(elapsedMillis < 1_500,
						"a second connection on the same thread must not be mistaken for the first writer until warning expiry");
				secondWriter.rollback();
				firstWriter.rollback();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	@Timeout(value = 15, unit = TimeUnit.SECONDS)
	void sameThreadExplicitWriterPromotesItsWarningBeforeTheDefaultDrainDeadline(@TempDir File dataDir)
			throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L);
		assertEquals(5_000L, config.getMapGrowthReadDrainTimeoutMillis());
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		ExecutorService writerExecutor = Executors.newSingleThreadExecutor();
		try {
			Future<?> preparation = writerExecutor.submit(() -> {
				try (RepositoryConnection writer = repository.getConnection()) {
					writer.begin();
					writer.add(VF.createIRI("urn:warning-owner:same-thread"),
							VF.createIRI("urn:warning-owner:predicate"),
							VF.createLiteral("x".repeat(1024 * 1024)));
					assertTrue(store.getBackingStore().growthAdmissionClosed(),
							"the explicit transaction must begin a warning while buffering its write");
					writer.prepare();
					writer.rollback();
				}
			});
			assertCompletesPromptly(preparation,
					"preparing on the buffering thread must promote that writer's existing warning");
		} finally {
			writerExecutor.shutdownNow();
			boolean writerTerminated = writerExecutor.awaitTermination(5, TimeUnit.SECONDS);
			repository.shutDown();
			assertTrue(writerTerminated, "the cancellable writer worker must terminate");
		}
	}

	@Test
	@Timeout(value = 15, unit = TimeUnit.SECONDS)
	void handedOffExplicitWriterPromotesItsWarningBeforeTheDefaultDrainDeadline(@TempDir File dataDir)
			throws Exception {
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setTripleDBSize(4096L * 64L)
				.setValueDBSize(4096L * 64L);
		assertEquals(5_000L, config.getMapGrowthReadDrainTimeoutMillis());
		LmdbStore store = new LmdbStore(dataDir, config);
		SailRepository repository = new SailRepository(store);
		repository.init();
		ExecutorService bufferExecutor = Executors.newSingleThreadExecutor();
		ExecutorService prepareExecutor = Executors.newSingleThreadExecutor();
		try {
			AtomicReference<Thread> bufferingThread = new AtomicReference<>();
			Future<RepositoryConnection> bufferedConnection = bufferExecutor.submit(() -> {
				bufferingThread.set(Thread.currentThread());
				RepositoryConnection writer = repository.getConnection();
				boolean handedOff = false;
				try {
					writer.begin();
					writer.add(VF.createIRI("urn:warning-owner:thread-handoff"),
							VF.createIRI("urn:warning-owner:predicate"),
							VF.createLiteral("x".repeat(1024 * 1024)));
					assertTrue(store.getBackingStore().growthAdmissionClosed(),
							"the explicit transaction must begin a warning while buffering its write");
					handedOff = true;
					return writer;
				} finally {
					if (!handedOff) {
						writer.close();
					}
				}
			});
			RepositoryConnection writer = bufferedConnection.get(5, TimeUnit.SECONDS);
			bufferExecutor.shutdown();
			assertTrue(bufferExecutor.awaitTermination(5, TimeUnit.SECONDS),
					"the buffering thread must finish before the sequential handoff");

			Future<?> preparation = prepareExecutor.submit(() -> {
				assertFalse(Thread.currentThread() == bufferingThread.get(),
						"prepare must run on a different thread from the buffering operation");
				try (writer) {
					writer.prepare();
					writer.rollback();
				}
			});
			assertCompletesPromptly(preparation,
					"a sequential thread handoff must preserve the explicit writer's warning ownership");
		} finally {
			bufferExecutor.shutdownNow();
			prepareExecutor.shutdownNow();
			boolean bufferTerminated = bufferExecutor.awaitTermination(5, TimeUnit.SECONDS);
			boolean prepareTerminated = prepareExecutor.awaitTermination(5, TimeUnit.SECONDS);
			repository.shutDown();
			assertTrue(bufferTerminated, "the buffer worker must terminate");
			assertTrue(prepareTerminated, "the cancellable prepare worker must terminate");
		}
	}

	private static void assertCompletesPromptly(Future<?> operation, String failureMessage) throws Exception {
		try {
			operation.get(5, TimeUnit.SECONDS);
		} catch (TimeoutException timeout) {
			operation.cancel(true);
			throw new AssertionError(failureMessage, timeout);
		}
	}

	private static void awaitCurrentAdmissionWaiter(LmdbSailStore store) throws InterruptedException {
		long deadlineNanos = System.nanoTime() + TimeUnit.SECONDS.toNanos(5);
		while (store.growthMetricsSnapshot().currentAdmissionWaiters() == 0) {
			if (System.nanoTime() >= deadlineNanos) {
				throw new AssertionError("No reader entered the closed map-growth admission gate");
			}
			TimeUnit.MILLISECONDS.sleep(1);
		}
	}

	private static void awaitGrowthAdmissionOpen(LmdbSailStore store) throws InterruptedException {
		long deadlineNanos = System.nanoTime() + TimeUnit.SECONDS.toNanos(3);
		while (store.growthAdmissionClosed()) {
			if (System.nanoTime() >= deadlineNanos) {
				throw new AssertionError("The expired buffered warning did not reopen admission");
			}
			TimeUnit.MILLISECONDS.sleep(1);
		}
	}

	private static long mapSize(LmdbSailStore backingStore, String storeFieldName) throws ReflectiveOperationException {
		Field storeField = LmdbSailStore.class.getDeclaredField(storeFieldName);
		storeField.setAccessible(true);
		Object mapStore = storeField.get(backingStore);
		Field mapSizeField = mapStore.getClass().getDeclaredField("mapSize");
		mapSizeField.setAccessible(true);
		return mapSizeField.getLong(mapStore);
	}
}
