/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.OptionalDouble;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.eclipse.rdf4j.common.order.StatementOrder;
import org.eclipse.rdf4j.common.transaction.IsolationLevels;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.base.SailSink;
import org.eclipse.rdf4j.sail.lmdb.LmdbAdjacencyMetrics.FallbackReason;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyCoverage;
import org.eclipse.rdf4j.sail.lmdb.config.DirectAdjacencyMode;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.evaluation.JoinDispatchTestAccess;
import org.eclipse.rdf4j.sail.lmdb.evaluation.KernelExecutionTestAccess;
import org.eclipse.rdf4j.sail.lmdb.evaluation.NativeLmdbQuerySource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;

/**
 * Plan 27 Milestone 5: bound-probe integration through {@link LmdbSailStore} arbitration. Every direct answer must
 * equal the LMDB result for the same probe, exact-empty must be served (not declined), and every ineligible shape must
 * fall back with its closed-enum reason while results stay correct.
 */
class LmdbDirectAdjacencyQueryTest {

	private static final ValueFactory F = SimpleValueFactory.getInstance();

	private static final IRI S1 = F.createIRI("http://example.org/s1");
	private static final IRI S2 = F.createIRI("http://example.org/s2");
	private static final IRI P1 = F.createIRI("http://example.org/p1");
	private static final IRI P2 = F.createIRI("http://example.org/p2");
	private static final IRI P3 = F.createIRI("http://example.org/p3");
	private static final IRI O1 = F.createIRI("http://example.org/o1");
	private static final IRI O2 = F.createIRI("http://example.org/o2");
	private static final IRI G1 = F.createIRI("http://example.org/g1");
	private static final IRI G2 = F.createIRI("http://example.org/g2");

	private static final String IR_AGGREGATE_QUERY = """
			SELECT ?patient (COUNT(?med) AS ?medCount) WHERE {
			  { ?patient <http://example.org/p1> <http://example.org/o1> . }
			  UNION
			  { ?patient <http://example.org/p2> ?enc . }
			  OPTIONAL {
			    ?patient <http://example.org/p1> ?med .
			    BIND(?med AS ?optMed)
			  }
			  FILTER(?optMed != ?patient)
			}
			GROUP BY ?patient
			HAVING(COUNT(?med) > 0)
			""";

	private static final Map<String, String> IR_AGGREGATE_PROPERTIES = Map.of(
			"rdf4j.lmdb.nativeQueryEngine.enabled", "true",
			"rdf4j.lmdb.wcoj.enabled", "false",
			"rdf4j.lmdb.janinoCodegen.enabled", "true",
			"rdf4j.lmdb.janinoCodegen.thresholdRows", "0",
			"rdf4j.lmdb.janinoCodegen.unionSources", "true",
			"rdf4j.lmdb.janinoCodegen.scanSources", "true");

	@TempDir
	File dataDir;

	private Repository repo;
	private LmdbStore sail;
	private LmdbSailStore backing;
	private LmdbDirectAdjacencyStore direct;

	// resolved raw ids
	private long s1;
	private long s2;
	private long p1;
	private long p2;
	private long p3;
	private long o1;
	private long o2;
	private long g1;
	private long inline42;

	@AfterEach
	void tearDown() {
		if (repo != null) {
			repo.shutDown();
		}
		System.clearProperty(LmdbDirectAdjacencyOptions.SHADOW_SAMPLE_EVERY_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.BOUND_PROBE_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.CLEAN_TXN_READS_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.PARALLEL_ROW_PATH_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.PLANNER_STATS_PROPERTY);
		System.clearProperty("rdf4j.lmdb.nativeQueryEngine.enabled");
		System.clearProperty(LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_INCOMING_PROPERTY);
		System.clearProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY);
	}

	private void openStore(DirectAdjacencyMode mode, DirectAdjacencyCoverage coverage, List<IRI> selected)
			throws IOException {
		// The node-predicate projection ships off by default (both the build-time and the per-call switch), so every
		// test in this class that exercises bound-node/unbound-predicate serving turns it on here rather than
		// individually. Tests that need it off set the properties themselves after this helper returns.
		System.setProperty(LmdbDirectAdjacencyOptions.NODE_PREDICATE_PROJECTION_PROPERTY, "true");
		System.setProperty(LmdbDirectAdjacencyStore.NODE_PREDICATE_SERVE_PROPERTY, "true");
		LmdbStoreConfig config = new LmdbStoreConfig("spoc,posc")
				.setDirectAdjacencyMode(mode)
				.setDirectAdjacencyMaxBytes(1L << 30);
		if (coverage != null) {
			config.setDirectAdjacencyCoverage(coverage);
		}
		if (selected != null) {
			config.setDirectAdjacencyPredicates(selected);
		}
		sail = new LmdbStore(dataDir, config);
		repo = new SailRepository(sail);
		repo.init();
		try (RepositoryConnection conn = repo.getConnection()) {
			conn.add(S1, P1, O1);
			conn.add(S1, P1, O2, G1);
			conn.add(S1, P2, O1);
			conn.add(S2, P1, O1);
			conn.add(S1, P3, F.createLiteral(42));
		}
		backing = sail.getBackingStore();
		direct = backing.directAdjacencyStore();
		assertThat(direct).isNotNull();
		assertThat(direct.buildNowForTest()).isTrue();

		try (var dataset = dataset()) {
			s1 = dataset.idOf(S1);
			s2 = dataset.idOf(S2);
			p1 = dataset.idOf(P1);
			p2 = dataset.idOf(P2);
			p3 = dataset.idOf(P3);
			o1 = dataset.idOf(O1);
			o2 = dataset.idOf(O2);
			g1 = dataset.idOf(G1);
			inline42 = dataset.idOf(F.createLiteral(42));
		}
		assertThat(ValueIds.isReference(inline42)).as("42 must be an inlined object id").isFalse();
	}

	private void openPreferStore() throws IOException {
		openStore(DirectAdjacencyMode.PREFER, null, null);
	}

	@Test
	void exactFullAccessReportsCandidateAndArbiterSelection() throws Exception {
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		NativeLmdbQuerySource.AdjacencyAccessObserver observer = new NativeLmdbQuerySource.AdjacencyAccessObserver() {
			@Override
			public void access(boolean used, String reason, StatementOrder order, long subj, long pred, long obj,
					long context) {
				outcomes.add(reason);
			}

			@Override
			public void candidate(String source, String reason, StatementOrder order, long subj, long pred, long obj,
					long context) {
				outcomes.add(reason);
			}
		};
		try (CloseableDataset dataset = dataset()) {
			try (RecordIterator iterator = dataset.source.statements(-1, -1, -1, -1, observer)) {
				while (iterator.next() != null) {
					// exhaust so the selected arm contributes completed, rather than censored, evidence
				}
			}
		}

		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));
		assertThat(outcomes).anyMatch(reason -> reason.startsWith("SELECTED_ADJACENCY"));
		assertThat(outcomes).noneMatch(reason -> reason.startsWith("INELIGIBLE_ADJACENCY"));
	}

	@Test
	void exactFullParallelAccessUsesTheSameArbiterContract() throws Exception {
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		NativeLmdbQuerySource.AdjacencyAccessObserver observer = recordingObserver(outcomes);
		try (CloseableDataset dataset = dataset()) {
			NativeLmdbQuerySource.ParallelSource[] sources = dataset.source.openParallelSources(1);
			assertThat(sources).hasSize(1);
			try (NativeLmdbQuerySource.ParallelSource source = sources[0];
					RecordIterator iterator = source.statements(-1, -1, -1, -1, observer)) {
				while (iterator.next() != null) {
					// exhaust the selected arm
				}
			}
		}

		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));
		assertThat(outcomes).anyMatch(reason -> reason.startsWith("SELECTED_ADJACENCY"));
	}

	@Test
	void exactFullRangeOffersAdjacencyCandidate() throws Exception {
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		NativeLmdbQuerySource.AdjacencyAccessObserver observer = recordingObserver(outcomes);
		try (CloseableDataset dataset = dataset()) {
			String indexName = dataset.source.indexName(-1, -1, -1, -1);
			LmdbKeyRange completeRange = new LmdbKeyRange(null, null, indexName);
			try (RecordIterator iterator = dataset.source.statements(-1, -1, -1, -1, completeRange, observer)) {
				while (iterator.next() != null) {
					// exhaust the selected arm
				}
			}
		}

		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));
		assertThat(outcomes).noneMatch(reason -> reason.startsWith("INELIGIBLE_ADJACENCY"));
	}

	@Test
	void boundedAdjacencyRangeMatchesNativeIndexSequence() throws Exception {
		openPreferStore();
		String indexName = backing.getTripleStore().getIndexName(-1, -1, -1, -1);
		long lowSubject = Long.compareUnsigned(s1, s2) < 0 ? s1 : s2;
		long highSubject = lowSubject == s1 ? s2 : s1;
		LmdbKeyRange range = new LmdbKeyRange(
				TripleIndex.encodeKey(indexName, lowSubject, 0, 0, 0),
				TripleIndex.encodeKey(indexName, highSubject, 0, 0, 0), indexName);

		List<long[]> expected;
		try (TxnManager.Txn txn = backing.getTripleStore().getTxnManager().createReadTxn()) {
			expected = CloseableDataset.collect(
					backing.getTripleStore().getTriplesRange(txn, -1, -1, -1, -1, true, range));
		}
		List<long[]> actual;
		try (LmdbAdjacencyReadView view = direct.acquire(backing.getTripleStore().getDataRevision())) {
			actual = CloseableDataset.collect(direct.tryOpenRange(view, range, -1, -1, -1, -1, true));
		}

		assertThat(actual).usingElementComparator(ROW_ORDER).containsExactlyElementsOf(expected);
	}

	@Test
	void opaqueRangeRetainsExactRawResidual() throws Exception {
		openPreferStore();
		String indexName = backing.getTripleStore().getIndexName(-1, -1, -1, -1);
		byte[] exactKey = TripleIndex.encodeKey(indexName, s1, p1, o1, 0);
		byte[] nonCanonicalLow = Arrays.copyOf(exactKey, exactKey.length + 1);
		LmdbKeyRange range = new LmdbKeyRange(nonCanonicalLow, null, indexName);
		assertThat(range.decodedBounds()).isNull();

		List<long[]> expected;
		try (TxnManager.Txn txn = backing.getTripleStore().getTxnManager().createReadTxn()) {
			expected = CloseableDataset.collect(
					backing.getTripleStore().getTriplesRange(txn, -1, -1, -1, -1, true, range));
		}
		List<long[]> actual;
		try (LmdbAdjacencyReadView view = direct.acquire(backing.getTripleStore().getDataRevision())) {
			actual = CloseableDataset.collect(direct.tryOpenRange(view, range, -1, -1, -1, -1, true));
		}

		assertThat(actual).usingElementComparator(ROW_ORDER).containsExactlyElementsOf(expected);
	}

	@Test
	void exactFullParallelRangeOffersAdjacencyCandidate() throws Exception {
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		NativeLmdbQuerySource.AdjacencyAccessObserver observer = recordingObserver(outcomes);
		try (CloseableDataset dataset = dataset()) {
			String indexName = backing.getTripleStore().getIndexName(-1, -1, -1, -1);
			LmdbKeyRange completeRange = new LmdbKeyRange(null, null, indexName);
			NativeLmdbQuerySource.ParallelSource[] sources = dataset.source.openParallelSources(1);
			try (NativeLmdbQuerySource.ParallelSource source = sources[0];
					RecordIterator iterator = source.statements(-1, -1, -1, -1, completeRange, observer)) {
				while (iterator.next() != null) {
					// exhaust the selected arm
				}
			}
		}

		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));
		assertThat(outcomes).noneMatch(reason -> reason.startsWith("INELIGIBLE_ADJACENCY"));
	}

	@Test
	void exactFullReusableProbeOffersBothCandidates() throws Exception {
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		try (CloseableDataset dataset = dataset();
				NativeLmdbQuerySource.NativeProbe probe = dataset.source.newProbe();
				RecordIterator iterator = probe.open(-1, -1, -1, -1, recordingObserver(outcomes))) {
			while (iterator.next() != null) {
				// exhaust the selected arm
			}
		}

		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));
		assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_LMDB"));
	}

	@Test
	void exactFullExistenceCanUseUniversalAdjacencyCandidate() throws Exception {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (CloseableDataset dataset = dataset()) {
			assertThat(dataset.source.has(-1, -1, -1, -1)).isTrue();
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void exactFullExistenceOffersAdjacencyForEveryBindingMask() throws Exception {
		openPreferStore();
		try (CloseableDataset dataset = dataset()) {
			for (int mask = 0; mask < 16; mask++) {
				long subject = (mask & 1) == 0 ? -1L : s1;
				long predicate = (mask & 2) == 0 ? -1L : p1;
				long object = (mask & 4) == 0 ? -1L : o1;
				long context = (mask & 8) == 0 ? -1L : 0L;
				boolean expected = !dataset.rows(subject, predicate, object, context).isEmpty();
				List<String> outcomes = new ArrayList<>();

				assertThat(dataset.source.has(subject, predicate, object, context, recordingObserver(outcomes)))
						.as("existence binding mask %s", Integer.toBinaryString(mask))
						.isEqualTo(expected);
				assertThat(outcomes)
						.as("existence binding mask %s candidates", Integer.toBinaryString(mask))
						.anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"))
						.noneMatch(reason -> reason.startsWith("INELIGIBLE_ADJACENCY"));
			}
		}
	}

	@Test
	void exactFullParallelSourceOffersAdjacencyForEveryMaskAndOrder() throws Exception {
		openPreferStore();
		try (CloseableDataset dataset = dataset()) {
			NativeLmdbQuerySource.ParallelSource[] sources = dataset.source.openParallelSources(1);
			assertThat(sources).hasSize(1);
			try (NativeLmdbQuerySource.ParallelSource source = sources[0]) {
				for (int mask = 0; mask < 16; mask++) {
					long subject = (mask & 1) == 0 ? -1L : s1;
					long predicate = (mask & 2) == 0 ? -1L : p1;
					long object = (mask & 4) == 0 ? -1L : o1;
					long context = (mask & 8) == 0 ? -1L : 0L;
					for (StatementOrder order : StatementOrder.values()) {
						List<String> outcomes = new ArrayList<>();
						try (RecordIterator iterator = source.statements(order, subject, predicate, object, context,
								recordingObserver(outcomes))) {
							while (iterator.next() != null) {
								// exhaust the selected arm
							}
						}
						assertThat(outcomes)
								.as("parallel mask %s in %s order", Integer.toBinaryString(mask), order)
								.anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"))
								.noneMatch(reason -> reason.startsWith("INELIGIBLE_ADJACENCY"));
					}
				}
			}
		}
	}

	private static NativeLmdbQuerySource.AdjacencyAccessObserver recordingObserver(List<String> outcomes) {
		return new NativeLmdbQuerySource.AdjacencyAccessObserver() {
			@Override
			public void access(boolean used, String reason, StatementOrder order, long subj, long pred, long obj,
					long context) {
				outcomes.add(reason);
			}

			@Override
			public void candidate(String source, String reason, StatementOrder order, long subj, long pred, long obj,
					long context) {
				outcomes.add(reason);
			}
		};
	}

	@Test
	void directAdjacencyBuildLogsMemoryLifecycle() throws Exception {
		Logger logger = (Logger) LoggerFactory.getLogger(LmdbDirectAdjacencyStore.class);
		ListAppender<ILoggingEvent> appender = new ListAppender<>();
		appender.start();
		Level previousLevel = logger.getLevel();
		logger.setLevel(Level.INFO);
		logger.addAppender(appender);
		try {
			openPreferStore();

			List<String> messages = appender.list.stream()
					.map(ILoggingEvent::getFormattedMessage)
					.toList();
			assertThat(messages).anyMatch(message -> message.contains("Creating in-memory adjacency structures"));
			assertThat(messages).anyMatch(message -> message.contains("Published in-memory adjacency structures"));
			assertThat(messages.stream()
					.filter(message -> message.contains("in-memory adjacency structures"))
					.allMatch(message -> message.contains("memoryUsedBytes=") && message.contains("highWaterBytes=")))
							.isTrue();
		} finally {
			logger.detachAppender(appender);
			logger.setLevel(previousLevel);
			appender.stop();
		}
	}

	@Test
	void unpinnedDatasetWaitsForRevisionPublicationAfterTrackedReaderReset() throws Exception {
		openPreferStore();
		TripleStore tripleStore = backing.getTripleStore();
		TripleStore.DirectAdjacencyCommitListener delegate = direct.commitListener();
		CountDownLatch commitReachedPublicationWindow = new CountDownLatch(1);
		CountDownLatch allowRevisionPublication = new CountDownLatch(1);
		tripleStore.setDirectAdjacencyCommitHooks((delta, nextRevision) -> {
			delegate.beforeRevisionBump(delta, nextRevision);
			commitReachedPublicationWindow.countDown();
			try {
				allowRevisionPublication.await();
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				throw new IllegalStateException("interrupted in commit publication test hook", e);
			}
		}, direct.newCommitDelta());

		ExecutorService executor = Executors.newFixedThreadPool(2);
		Future<?> commit = executor.submit(() -> {
			try (RepositoryConnection connection = repo.getConnection()) {
				connection.begin();
				connection.add(S2, P2, O2);
				connection.commit();
			}
		});
		Future<org.eclipse.rdf4j.sail.base.SailDataset> dataset = null;
		try {
			assertThat(commitReachedPublicationWindow.await(5, TimeUnit.SECONDS)).isTrue();
			CountDownLatch datasetOpened = new CountDownLatch(1);
			dataset = executor.submit(() -> {
				org.eclipse.rdf4j.sail.base.SailDataset opened = backing.getExplicitSailSource()
						.dataset(IsolationLevels.NONE);
				datasetOpened.countDown();
				return opened;
			});

			assertThat(datasetOpened.await(100, TimeUnit.MILLISECONDS))
					.as("dataset acquisition must wait until the revision matching its LMDB snapshot is published")
					.isFalse();
		} finally {
			allowRevisionPublication.countDown();
			if (dataset != null) {
				dataset.get(5, TimeUnit.SECONDS).close();
			}
			commit.get(5, TimeUnit.SECONDS);
			executor.shutdownNow();
		}
	}

	private CloseableDataset dataset() {
		return new CloseableDataset(backing.getExplicitSailSource().dataset(IsolationLevels.SNAPSHOT));
	}

	/** Typed wrapper: the dataset class is private, but its query surface is {@link NativeLmdbQuerySource}. */
	private static final class CloseableDataset implements AutoCloseable {
		final NativeLmdbQuerySource source;
		final org.eclipse.rdf4j.sail.base.SailDataset dataset;

		CloseableDataset(org.eclipse.rdf4j.sail.base.SailDataset dataset) {
			this.dataset = dataset;
			this.source = (NativeLmdbQuerySource) dataset;
		}

		long idOf(org.eclipse.rdf4j.model.Value value) {
			return source.idOf(value);
		}

		List<long[]> rows(long subj, long pred, long obj, long context) throws IOException {
			return collect(source.statements(subj, pred, obj, context));
		}

		List<long[]> rows(StatementOrder order, long subj, long pred, long obj, long context) throws IOException {
			return collect(source.statements(order, subj, pred, obj, context));
		}

		private static List<long[]> collect(RecordIterator it) {
			List<long[]> rows = new ArrayList<>();
			try {
				long[] quad;
				while ((quad = it.next()) != null) {
					rows.add(new long[] { quad[TripleIndex.SUBJ_IDX], quad[TripleIndex.PRED_IDX],
							quad[TripleIndex.OBJ_IDX], Math.max(0, quad[TripleIndex.CONTEXT_IDX]) });
				}
			} finally {
				it.close();
			}
			return rows;
		}

		@Override
		public void close() {
			dataset.close();
		}
	}

	private static final Comparator<long[]> ROW_ORDER = (a, b) -> {
		for (int i = 0; i < 4; i++) {
			int cmp = Long.compareUnsigned(a[i], b[i]);
			if (cmp != 0) {
				return cmp;
			}
		}
		return 0;
	};

	private static List<long[]> sorted(List<long[]> rows) {
		List<long[]> copy = new ArrayList<>(rows);
		copy.sort(ROW_ORDER);
		return copy;
	}

	private static void assertSameRows(List<long[]> actual, List<long[]> expected) {
		assertThat(sorted(actual)).usingElementComparator(ROW_ORDER).containsExactlyElementsOf(sorted(expected));
	}

	private List<String> queryRows(String query) {
		try (RepositoryConnection connection = repo.getConnection();
				TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
			List<String> rows = new ArrayList<>();
			while (result.hasNext()) {
				var row = result.next();
				rows.add(row.getValue("patient").stringValue() + "=" + row.getValue("medCount").stringValue());
			}
			rows.sort(String::compareTo);
			return rows;
		}
	}

	private List<String> queryRows(String query, String... bindingNames) {
		try (RepositoryConnection connection = repo.getConnection();
				TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
			List<String> rows = new ArrayList<>();
			while (result.hasNext()) {
				var row = result.next();
				StringBuilder rendered = new StringBuilder();
				for (String bindingName : bindingNames) {
					if (!rendered.isEmpty()) {
						rendered.append('=');
					}
					rendered.append(row.getValue(bindingName).stringValue());
				}
				rows.add(rendered.toString());
			}
			rows.sort(String::compareTo);
			return rows;
		}
	}

	private static void restoreProperties(Map<String, String> previous) {
		previous.forEach((property, value) -> {
			if (value == null) {
				System.clearProperty(property);
			} else {
				System.setProperty(property, value);
			}
		});
	}

	// ------------------------------------------------------------------
	// vectors
	// ------------------------------------------------------------------

	@Test
	void nativeProbeCloseReleasesDirectIteratorLease() throws IOException {
		openPreferStore();
		RecordIterator iterator = null;
		try {
			try (var dataset = dataset();
					NativeLmdbQuerySource.NativeProbe probe = dataset.source.newProbe()) {
				iterator = probe.open(s1, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
			}
			assertThat(direct.snapshotMetrics().activeViews).isZero();
		} finally {
			// Keep the intentional red test from hanging repository shutdown before the ownership fix.
			if (iterator != null) {
				iterator.close();
			}
		}
	}

	@Test
	void interruptedDatasetCloseReleasesAdjacencyView() throws IOException {
		openPreferStore();
		CloseableDataset dataset = dataset();
		try {
			Thread.currentThread().interrupt();
			assertThatCode(dataset::close).doesNotThrowAnyException();
			assertThat(Thread.currentThread().isInterrupted()).isTrue();
			assertThat(direct.snapshotMetrics().activeViews).isZero();
		} finally {
			Thread.interrupted();
			if (direct.snapshotMetrics().activeViews != 0) {
				// The failed close made the private dataset view unreachable. Avoid repeating the intentional
				// unbounded shutdown wait on the red path; the isolated Surefire process reclaims the resources.
				repo = null;
			} else {
				dataset.close();
			}
		}
	}

	@Test
	void datasetConstructorClosesTxnWhenAdjacencyAcquireFails() throws IOException {
		openPreferStore();
		RuntimeException acquireFailure = new IllegalStateException("synthetic adjacency acquisition failure");
		TxnManager txnManager = backing.getTripleStore().getTxnManager();
		int availableReadersBefore = txnManager.availableReadTxnSlots(1_024, 0);
		direct.beforeExactViewReturnForTest = () -> {
			throw acquireFailure;
		};
		try {
			assertThatThrownBy(() -> backing.getExplicitSailSource().dataset(IsolationLevels.SNAPSHOT))
					.isSameAs(acquireFailure);
		} finally {
			direct.beforeExactViewReturnForTest = null;
		}

		assertThat(direct.snapshotMetrics().activeViews)
				.as("the failed adjacency acquisition releases its provisional view")
				.isZero();
		assertThat(txnManager.availableReadTxnSlots(1_024, 0))
				.as("the dataset constructor closes the read transaction acquired before the adjacency view")
				.isEqualTo(availableReadersBefore);
	}

	@Test
	void plannerStatsHoldNativeReadLockAgainstConcurrentClose() throws Exception {
		openPreferStore();
		CloseableDataset dataset = dataset();
		CountDownLatch statsPassedOpenCheck = new CountDownLatch(1);
		CountDownLatch allowStatsRead = new CountDownLatch(1);
		CountDownLatch closeStarted = new CountDownLatch(1);
		backing.afterPlannerStatsOpenCheckForTest = () -> {
			statsPassedOpenCheck.countDown();
			try {
				if (!allowStatsRead.await(5, TimeUnit.SECONDS)) {
					throw new IllegalStateException("planner statistics test hook timed out");
				}
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
				throw new IllegalStateException("planner statistics test hook interrupted", e);
			}
		};
		ExecutorService executor = Executors.newFixedThreadPool(2);
		Future<OptionalDouble> stats = null;
		Future<?> close = null;
		try {
			stats = executor.submit(() -> dataset.source.meanFanOut(p1, true));
			assertThat(statsPassedOpenCheck.await(5, TimeUnit.SECONDS)).isTrue();
			close = executor.submit(() -> {
				closeStarted.countDown();
				dataset.close();
			});
			assertThat(closeStarted.await(5, TimeUnit.SECONDS)).isTrue();
			Future<?> closeWhileStatsRead = close;
			assertThatThrownBy(() -> closeWhileStatsRead.get(1, TimeUnit.SECONDS))
					.as("dataset close must wait for the in-flight planner statistics read")
					.isInstanceOf(TimeoutException.class);

			allowStatsRead.countDown();
			assertThat(stats.get(5, TimeUnit.SECONDS)).isPresent();
			close.get(5, TimeUnit.SECONDS);
		} finally {
			allowStatsRead.countDown();
			backing.afterPlannerStatsOpenCheckForTest = null;
			executor.shutdownNow();
			executor.awaitTermination(5, TimeUnit.SECONDS);
			dataset.close();
		}
	}

	@Test
	void nativeProbeRetainsOwnershipAcrossUniversalShapeTransitions() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "false");
		openPreferStore();
		RecordIterator firstDirect = null;
		RecordIterator secondDirect = null;
		RecordIterator callerClosedDirect = null;
		try {
			try (var dataset = dataset();
					NativeLmdbQuerySource.NativeProbe probe = dataset.source.newProbe()) {
				firstDirect = probe.open(s1, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(firstDirect.next()).isNotNull();

				secondDirect = probe.open(s2, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(secondDirect).as("one resettable direct iterator belongs to the retained probe")
						.isSameAs(firstDirect);

				RecordIterator universalRoot = probe.open(-1, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(universalRoot).as("disabling the root specialization retains the probe-owned wrapper")
						.isSameAs(firstDirect);
				assertThat(universalRoot.next()).isNotNull();

				callerClosedDirect = probe.open(s1, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(callerClosedDirect).as("the direct iterator survives a universal traversal transition")
						.isSameAs(firstDirect);
				callerClosedDirect.close();

				RecordIterator reusedUniversalRoot = probe.open(-1, p1, -1, -1);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(reusedUniversalRoot).isSameAs(universalRoot);
				assertThat(CloseableDataset.collect(reusedUniversalRoot)).hasSize(3);
			}
			assertThat(direct.snapshotMetrics().activeViews).isZero();
		} finally {
			if (callerClosedDirect != null) {
				callerClosedDirect.close();
			}
			if (secondDirect != null) {
				secondDirect.close();
			}
			if (firstDirect != null) {
				firstDirect.close();
			}
		}
	}

	@Test
	void parallelWorkerRowSurfaceServesDirectAdjacency() throws Exception {
		System.setProperty(LmdbDirectAdjacencyStore.PARALLEL_ROW_PATH_PROPERTY, "true");
		openPreferStore();
		int workerCount = 2;
		ExecutorService workers = Executors.newFixedThreadPool(workerCount);
		NativeLmdbQuerySource.ParallelSource[] sources = null;
		try (var dataset = dataset()) {
			sources = dataset.source.openParallelSources(workerCount);
			assertThat(sources).hasSize(workerCount).doesNotContainNull();
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			CountDownLatch start = new CountDownLatch(1);
			List<Future<?>> tasks = new ArrayList<>(workerCount);
			for (NativeLmdbQuerySource.ParallelSource source : sources) {
				tasks.add(workers.submit(() -> {
					start.await();
					assertThat(CloseableDataset.collect(source.statements(s1, p1, -1, -1))).hasSize(2);
					assertThat(CloseableDataset.collect(
							source.statements(StatementOrder.O, s1, p1, -1, -1))).hasSize(2);
					try (NativeLmdbQuerySource.NativeProbe probe = source.newProbe()) {
						assertThat(CloseableDataset.collect(probe.open(s1, p1, -1, -1))).hasSize(2);
						assertThat(probe.adjacencyCacheBacked()).isTrue();
					}
					assertThat(source.count(s1, p1, -1, -1)).isEqualTo(2);
					assertThat(source.has(s1, p1, o1, -1)).isTrue();
					assertThat(source.exactDegree(p1, s1, true)).hasValue(2);
					return null;
				}));
			}
			start.countDown();
			for (Future<?> task : tasks) {
				task.get(5, TimeUnit.SECONDS);
			}
			assertThat(direct.snapshotMetrics().lookupHits)
					.isGreaterThanOrEqualTo(hitsBefore + 6L * workerCount);
		} finally {
			if (sources != null) {
				for (NativeLmdbQuerySource.ParallelSource source : sources) {
					if (source != null) {
						source.close();
					}
				}
			}
			workers.shutdownNow();
		}
		assertThat(direct.snapshotMetrics().activeViews).isZero();
	}

	@Test
	void disabledParallelRowSpecializationKeepsUniversalCandidateAvailable() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.PARALLEL_ROW_PATH_PROPERTY, "false");
		openPreferStore();
		List<String> outcomes = new ArrayList<>();
		try (var dataset = dataset()) {
			NativeLmdbQuerySource.ParallelSource[] sources = dataset.source.openParallelSources(1);
			assertThat(sources).hasSize(1).doesNotContainNull();
			try (NativeLmdbQuerySource.ParallelSource source = sources[0];
					NativeLmdbQuerySource.NativeProbe probe = source.newProbe()) {
				long hitsBefore = direct.snapshotMetrics().lookupHits;
				assertThat(CloseableDataset.collect(source.statements(-1, -1, -1, -1,
						recordingObserver(outcomes)))).hasSize(5);
				assertThat(CloseableDataset.collect(probe.open(s1, p1, -1, -1,
						recordingObserver(outcomes)))).hasSize(2);
				assertThat(probe.adjacencyCacheBacked()).isTrue();
				assertThat(source.count(s1, p1, -1, -1)).isEqualTo(2);
				assertThat(source.has(s1, p1, o1, -1)).isTrue();
				assertThat(source.exactDegree(p1, s1, true)).isEmpty();
				assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
				assertThat(outcomes).anyMatch(reason -> reason.startsWith("CANDIDATE_ADJACENCY"));

				NativeLmdbQuerySource.NativeAdjacency adjacency = probe.adjacency(p1, true);
				assertThat(adjacency).isNotNull();
				assertThat(adjacency.size(adjacency.find(s1))).isEqualTo(2);
				assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
			}
		}
		assertThat(direct.snapshotMetrics().activeViews).isZero();
	}

	@Test
	void parallelWorkerRowPathServesByDefault() throws IOException {
		openPreferStore();
		try (var dataset = dataset()) {
			NativeLmdbQuerySource.ParallelSource[] sources = dataset.source.openParallelSources(1);
			assertThat(sources).hasSize(1).doesNotContainNull();
			try (NativeLmdbQuerySource.ParallelSource source = sources[0]) {
				long hitsBefore = direct.snapshotMetrics().lookupHits;
				assertThat(CloseableDataset.collect(source.statements(s1, p1, -1, -1))).hasSize(2);
				assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
			}
		}
		assertThat(direct.snapshotMetrics().activeViews).isZero();
	}

	@Test
	void irAggregateQueryReleasesDirectProbeViews() throws IOException {
		Map<String, String> previous = new HashMap<>();
		IR_AGGREGATE_PROPERTIES.forEach((property, value) -> {
			previous.put(property, System.getProperty(property));
			System.setProperty(property, value);
		});
		try {
			openPreferStore();
			System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "false");
			List<String> expected = queryRows(IR_AGGREGATE_QUERY);
			assertThat(expected).containsExactly(S1.stringValue() + "=4", S2.stringValue() + "=1");

			System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
			KernelExecutionTestAccess.resetMetrics();
			long hitsBefore = direct.snapshotMetrics().lookupHits;

			for (int round = 0; round < 300 && KernelExecutionTestAccess.aggOpened() == 0; round++) {
				List<String> actual = queryRows(IR_AGGREGATE_QUERY);
				long activeViews = direct.snapshotMetrics().activeViews;
				if (activeViews != 0) {
					// A leaked iterator is no longer reachable. Avoid entering the store's intentional unbounded
					// shutdown wait on the failure path; the isolated Surefire process will reclaim native resources.
					repo = null;
				}
				assertThat(actual).containsExactlyElementsOf(expected);
				assertThat(activeViews).isZero();
			}

			assertThat(KernelExecutionTestAccess.aggOpened()).isGreaterThan(0);
			assertThat(KernelExecutionTestAccess.aggRows()).isGreaterThan(0);
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		} finally {
			restoreProperties(previous);
		}
	}

	@Test
	void subjectBoundProbeServesAndRecordsHit() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void objectBoundProbeServesIncomingRows() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(-1, p1, o1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s2, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void boundSubjectUnboundPredicateEnumeratesEveryGroup() throws IOException {
		openPreferStore();
		long fallbackBefore = direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE);
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s1, -1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 },
					new long[] { s1, p2, o1, 0 },
					new long[] { s1, p3, inline42, 0 }));
		}
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE))
				.isEqualTo(fallbackBefore);
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void unboundPredicateInlineObjectUsesUniversalSweepWithoutIncomingProjection() throws IOException {
		openPreferStore();
		long fallbackBefore = direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE);
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(-1, -1, inline42, -1), List.of(
					new long[] { s1, p3, inline42, 0 }));
		}
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE))
				.isEqualTo(fallbackBefore);
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void boundContextFiltersExactly() throws IOException {
		openPreferStore();
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s1, p1, -1, g1), List.of(new long[] { s1, p1, o2, g1 }));
			assertSameRows(dataset.rows(s1, p1, -1, 0), List.of(new long[] { s1, p1, o1, 0 }));
			// a bound context id that is not in the context catalog proves emptiness
			assertThat(dataset.rows(s1, p1, -1, o2)).isEmpty();
		}
	}

	@Test
	void exactEmptyIsServedNotDeclined() throws IOException {
		openPreferStore();
		long missesBefore = direct.snapshotMetrics().exactMisses;
		try (var dataset = dataset()) {
			assertThat(dataset.rows(s2, p2, -1, -1)).isEmpty();
		}
		assertThat(direct.snapshotMetrics().exactMisses).isGreaterThan(missesBefore);
	}

	@Test
	void countHasAndExactDegreeServeFromDirect() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertThat(dataset.source.count(s1, p1, -1, -1)).isEqualTo(2);
			assertThat(dataset.source.count(s1, p1, o1, 0)).isEqualTo(1);
			assertThat(dataset.source.count(s1, p1, o1, g1)).isZero();
			assertThat(dataset.source.has(s1, p1, o1, -1)).isTrue();
			assertThat(dataset.source.has(s1, p1, o2, g1)).isTrue();
			assertThat(dataset.source.has(s1, p1, o2, 0)).isFalse();
			assertThat(dataset.source.has(s2, p1, o2, -1)).isFalse();
			assertThat(dataset.source.exactDegree(p1, s1, true)).hasValue(2);
			assertThat(dataset.source.exactDegree(p1, o1, false)).hasValue(2);
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void flaggedPlaneCountTracksBaseDeltasAndPinnedSnapshots() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		openPreferStore();

		try (var pinned = dataset()) {
			long hitsBeforeBaseCount = direct.snapshotMetrics().lookupHits;
			assertThat(pinned.source.count(-1, p1, -1, -1)).isEqualTo(3);
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBeforeBaseCount);

			try (RepositoryConnection connection = repo.getConnection()) {
				connection.add(S2, P1, O2);
			}
			direct.pauseApplierForTest(false);
			try (var afterAdd = dataset()) {
				long hitsBeforeAddCount = direct.snapshotMetrics().lookupHits;
				assertThat(afterAdd.source.count(-1, p1, -1, -1)).isEqualTo(4);
				assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBeforeAddCount);
			}
			assertThat(pinned.source.count(-1, p1, -1, -1)).isEqualTo(3);

			try (RepositoryConnection connection = repo.getConnection()) {
				connection.remove(S1, P1, O1);
			}
			direct.pauseApplierForTest(false);
			try (var afterRemove = dataset()) {
				long hitsBeforeRemoveCount = direct.snapshotMetrics().lookupHits;
				assertThat(afterRemove.source.count(-1, p1, -1, -1)).isEqualTo(3);
				assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBeforeRemoveCount);
			}
			assertThat(pinned.source.count(-1, p1, -1, -1)).isEqualTo(3);
		}
	}

	@Test
	void plannerFanOutIsExactByDefaultAndFalseRestoresSampledStatistics() throws Exception {
		openPreferStore();
		assertThat(sail.awaitDirectAdjacencyReady(0, TimeUnit.MILLISECONDS)).isTrue();

		try (var enabledByDefault = dataset()) {
			assertThat(enabledByDefault.source.meanFanOut(p1, true).orElseThrow()).isEqualTo(1.5);
		}

		System.setProperty(LmdbDirectAdjacencyStore.PLANNER_STATS_PROPERTY, "false");
		try (var disabled = dataset()) {
			assertThat(disabled.source.meanFanOut(p1, true).orElseThrow()).isNotEqualTo(1.5);
		}
	}

	@Test
	void cachedPlannerFanOutRespectsDirtyWriterBypass() throws Exception {
		openPreferStore();
		assertThat(sail.awaitDirectAdjacencyReady(0, TimeUnit.MILLISECONDS)).isTrue();

		try (var dataset = dataset()) {
			assertThat(dataset.source.meanFanOut(p1, true).orElseThrow()).isEqualTo(1.5);
			direct.storeTxnStartedFlag().set(true);
			direct.storeTxnDirtyFlag().set(true);
			try {
				assertThat(dataset.source.meanFanOut(p1, true).orElseThrow()).isNotEqualTo(1.5);
			} finally {
				direct.storeTxnDirtyFlag().set(false);
				direct.storeTxnStartedFlag().set(false);
			}
		}
	}

	@Test
	void flaggedPlannerFanOutUsesExactPlaneCounts() throws Exception {
		System.setProperty(LmdbDirectAdjacencyStore.PLANNER_STATS_PROPERTY, "true");
		openPreferStore();
		assertThat(sail.awaitDirectAdjacencyReady(0, TimeUnit.MILLISECONDS)).isTrue();
		long plannerStatsHitsBefore = sail.getDirectAdjacencyPlannerStatsHitCount();

		try (var pinned = dataset()) {
			assertThat(pinned.source.meanFanOut(p1, true).orElseThrow()).isEqualTo(1.5);
			assertThat(pinned.source.meanFanOut(p1, true).orElseThrow()).isEqualTo(1.5);
			assertThat(pinned.source.meanFanOut(p1, false).orElseThrow()).isEqualTo(1.5);

			System.setProperty(LmdbDirectAdjacencyStore.PLANNER_STATS_PROPERTY, "false");
			try (var fallback = dataset()) {
				assertThat(fallback.source.meanFanOut(p1, true).orElseThrow()).isNotEqualTo(1.5);
			}
			System.setProperty(LmdbDirectAdjacencyStore.PLANNER_STATS_PROPERTY, "true");

			IRI p4Value = F.createIRI("http://example.org/fanOut");
			try (RepositoryConnection connection = repo.getConnection()) {
				connection.begin();
				connection.add(S1, p4Value, F.createIRI("http://example.org/fanOut/o1"));
				connection.add(S1, p4Value, F.createIRI("http://example.org/fanOut/o2"));
				connection.add(S1, p4Value, F.createIRI("http://example.org/fanOut/o3"));
				connection.add(S2, p4Value, F.createIRI("http://example.org/fanOut/o4"));
				connection.commit();
			}
			direct.pauseApplierForTest(false);
			try (var current = dataset()) {
				long p4 = current.idOf(p4Value);
				assertThat(current.source.meanFanOut(p4, true).orElseThrow()).isEqualTo(2.0);
				assertThat(current.source.meanFanOut(p4, false).orElseThrow()).isEqualTo(1.0);
				assertThat(pinned.source.meanFanOut(p4, true).orElseThrow()).isZero();
			}
		}
		assertThat(sail.getDirectAdjacencyPlannerStatsHitCount()).isEqualTo(plannerStatsHitsBefore + 2);
	}

	@Test
	void flaggedSubjectAggregatesUseAdjacencyKeyDomainsAcrossDeltas() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		IRI s3Value = F.createIRI("http://example.org/s3");
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			connection.add(s3Value, P1, O2);
			connection.remove(S2, P1, O1);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		LmdbPrefixRunPlan.resetMetrics();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		assertThat(queryRows("SELECT DISTINCT ?s WHERE { ?s <" + P1 + "> ?o }", "s"))
				.containsExactly(S1.stringValue(), s3Value.stringValue());
		assertThat(queryRows("SELECT ?s (COUNT(?o) AS ?degree) WHERE { ?s <" + P1
				+ "> ?o } GROUP BY ?s", "s", "degree"))
						.containsExactly(S1.stringValue() + "=2", s3Value.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.OPENED.get()).isGreaterThan(0);
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void flaggedCountAggregateUsesExactPlaneTotal() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT (COUNT(*) AS ?count) WHERE { ?s <" + P1 + "> ?o }", "count"))
				.containsExactly("3");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isGreaterThan(0);
		assertThat(LmdbPrefixRunPlan.RUN_ROWS_COUNTED.get()).isEqualTo(3);
	}

	@Test
	void scanAggregatesDefaultOnWithExplicitFalseKillSwitch() throws IOException {
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT ?s (COUNT(?o) AS ?degree) WHERE { ?s <" + P1
				+ "> ?o } GROUP BY ?s", "s", "degree"))
						.containsExactly(S1.stringValue() + "=2", S2.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isGreaterThan(0);

		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "false");
		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT ?s (COUNT(?o) AS ?degree) WHERE { ?s <" + P1
				+ "> ?o } GROUP BY ?s", "s", "degree"))
						.containsExactly(S1.stringValue() + "=2", S2.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isZero();
	}

	@Test
	void flaggedPredicateAnalyticsUseFullCoveragePlaneCatalog() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		IRI p4Value = F.createIRI("http://example.org/p4");
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			connection.remove(S1, P2, O1);
			connection.add(S1, p4Value, O1);
			connection.add(S2, p4Value, O2);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT DISTINCT ?p WHERE { ?s ?p ?o }", "p"))
				.containsExactly(P1.stringValue(), P3.stringValue(), p4Value.stringValue());
		assertThat(queryRows("SELECT ?p (COUNT(*) AS ?count) WHERE { ?s ?p ?o } GROUP BY ?p", "p", "count"))
				.containsExactly(P1.stringValue() + "=3", P3.stringValue() + "=1", p4Value.stringValue() + "=2");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isGreaterThan(0);
		assertThat(LmdbPrefixRunPlan.RUN_ROWS_COUNTED.get()).isEqualTo(6);
	}

	@Test
	void flaggedObjectAggregatesDeclineAdjacencyForInlineKeyDomains() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT DISTINCT ?o WHERE { ?s <" + P3 + "> ?o }", "o"))
				.containsExactly("42");
		assertThat(queryRows("SELECT ?o (COUNT(?s) AS ?degree) WHERE { ?s <" + P3
				+ "> ?o } GROUP BY ?o", "o", "degree")).containsExactly("42=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isZero();
	}

	@Test
	void flaggedPredicateAnalyticsDeclineSelectedCoverage() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openStore(DirectAdjacencyMode.PREFER, DirectAdjacencyCoverage.SELECTED, List.of(P1));

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT DISTINCT ?p WHERE { ?s ?p ?o }", "p"))
				.containsExactly(P1.stringValue(), P2.stringValue(), P3.stringValue());
		assertThat(queryRows("SELECT ?p (COUNT(*) AS ?count) WHERE { ?s ?p ?o } GROUP BY ?p", "p", "count"))
				.containsExactly(P1.stringValue() + "=3", P2.stringValue() + "=1", P3.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isZero();
	}

	@Test
	void flaggedPredicateAnalyticsMergeExplicitAndInferredPlaneTotals() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		IRI p4Value = F.createIRI("http://example.org/p4");
		try (LmdbStoreConnection connection = (LmdbStoreConnection) sail.getConnection()) {
			connection.begin();
			connection.addInferredStatement(S2, P1, O2);
			connection.addInferredStatement(S2, p4Value, O1);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT DISTINCT ?p WHERE { ?s ?p ?o }", "p"))
				.containsExactly(P1.stringValue(), P2.stringValue(), P3.stringValue(), p4Value.stringValue());
		assertThat(queryRows("SELECT ?p (COUNT(*) AS ?count) WHERE { ?s ?p ?o } GROUP BY ?p", "p", "count"))
				.containsExactly(P1.stringValue() + "=4", P2.stringValue() + "=1", P3.stringValue() + "=1",
						p4Value.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isGreaterThan(0);
		assertThat(LmdbPrefixRunPlan.RUN_ROWS_COUNTED.get()).isEqualTo(7);
	}

	@Test
	void flaggedEmptyPlaneCountUsesExactZeroWithoutScanningLmdb() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.remove(S1, P2, O1);
		}
		direct.pauseApplierForTest(false);

		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertThat(dataset.source.count(-1, p2, -1, -1)).isZero();
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT (COUNT(*) AS ?count) WHERE { ?s <" + P2 + "> ?o }", "count"))
				.containsExactly("0");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get())
				.as("the optimizer prunes an exactly empty pattern before opening a prefix cursor")
				.isZero();
		assertThat(LmdbPrefixRunPlan.RUN_ROWS_COUNTED.get()).isZero();
		assertThat(direct.snapshotMetrics().activeViews).isZero();
	}

	@Test
	void pagedBaseServesExactCountAndPredicateAnalytics() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.SCAN_AGGREGATES_PROPERTY, "true");
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		try (var pinnedDataset = dataset();
				var unpinnedDataset = new CloseableDataset(
						backing.getExplicitSailSource().dataset(IsolationLevels.NONE))) {
			LmdbPrefixRunPlan predicateRuns = pinnedDataset.source.prefixRunPlan(
					new int[] { TripleIndex.PRED_IDX }, -1, -1, -1, -1);
			assertThat(predicateRuns).isNotNull();
			assertThat(predicateRuns.usesAdjacency()).isTrue();
			LmdbPrefixRunPlan unpinnedPredicateRuns = unpinnedDataset.source.prefixRunPlan(
					new int[] { TripleIndex.PRED_IDX }, -1, -1, -1, -1);
			assertThat(unpinnedPredicateRuns).isNotNull();
			assertThat(unpinnedPredicateRuns.usesAdjacency()).isTrue();
			Map<Long, Long> predicateCounts = new HashMap<>();
			try (LmdbPrefixRunCursor cursor = unpinnedDataset.source.prefixRuns(
					unpinnedPredicateRuns, -1, -1, -1, -1, true)) {
				assertThat(cursor).isNotNull();
				while (cursor.next()) {
					predicateCounts.put(cursor.quad()[TripleIndex.PRED_IDX], cursor.runRowCount());
				}
			}
			assertThat(predicateCounts).containsExactlyInAnyOrderEntriesOf(Map.of(p1, 3L, p2, 1L, p3, 1L));
		}

		LmdbPrefixRunPlan.resetMetrics();
		assertThat(queryRows("SELECT (COUNT(*) AS ?count) WHERE { ?s <" + P1 + "> ?o }", "count"))
				.containsExactly("3");
		assertThat(queryRows("SELECT ?p (COUNT(*) AS ?count) WHERE { ?s ?p ?o } GROUP BY ?p", "p", "count"))
				.containsExactly(P1.stringValue() + "=3", P2.stringValue() + "=1", P3.stringValue() + "=1");
		assertThat(LmdbPrefixRunPlan.ADJACENCY_OPENED.get()).isGreaterThan(0);
		assertThat(LmdbPrefixRunPlan.RUN_ROWS_COUNTED.get()).isEqualTo(8);
		assertThat(direct.snapshotMetrics().activeViews).isZero();
	}

	@Test
	void inlineIncomingProbeServes() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(-1, p3, inline42, -1), List.of(new long[] { s1, p3, inline42, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void nodeEnumerationDecodesAcrossReusableBatchBoundaries() throws IOException {
		openPreferStore();
		IRI widePredicate = F.createIRI("http://example.org/wide");
		try (RepositoryConnection connection = repo.getConnection()) {
			for (int i = 0; i < 600; i++) {
				connection.add(S2, widePredicate, F.createIRI("http://example.org/wide/object/" + i));
			}
		}
		assertThat(direct.buildNowForTest()).isTrue();
		try (var dataset = dataset()) {
			long widePredicateId = dataset.idOf(widePredicate);
			assertThat(dataset.rows(s2, -1, -1, -1)).hasSize(601);
			assertThat(dataset.rows(s2, widePredicateId, -1, -1)).hasSize(600);
		}
	}

	@Test
	void disabledRootScanSpecializationRetainsUniversalCandidate() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "false");
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		FallbackReason rootScan = FallbackReason.valueOf("ROOT_SCAN");
		long fallbacksBefore = direct.snapshotMetrics().fallbacks(rootScan);
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(-1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 },
					new long[] { s2, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(rootScan)).isEqualTo(fallbacksBefore);
	}

	@Test
	void rootScanServesFromDirectAdjacencyByDefault() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long fallbacksBefore = direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN);
		try (var dataset = dataset()) {
			assertThat(dataset.source.indexName(-1, p1, -1, -1)).isEqualTo("direct-spoc");
			assertSameRows(dataset.rows(-1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 },
					new long[] { s2, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN)).isEqualTo(fallbacksBefore);
	}

	@Test
	void flaggedRootScanMergesDeltaOnlyKeysAndTombstones() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		IRI s3Value = F.createIRI("http://example.org/s3");
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			connection.add(s3Value, P1, O2);
			connection.remove(S1, P1, O1);
			connection.remove(S2, P1, O1);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			long s3 = dataset.idOf(s3Value);
			assertSameRows(dataset.rows(-1, p1, -1, -1), List.of(
					new long[] { s1, p1, o2, g1 },
					new long[] { s3, p1, o2, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void flaggedRootScanPreservesContextMultiplicity() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			connection.add(S1, P1, O1, G1);
			connection.add(S1, P1, O1, G2);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		try (var dataset = dataset()) {
			long g2 = dataset.idOf(G2);
			assertSameRows(dataset.rows(-1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o1, g1 },
					new long[] { s1, p1, o1, g2 },
					new long[] { s1, p1, o2, g1 },
					new long[] { s2, p1, o1, 0 }));
		}
	}

	@Test
	void flaggedRootScanDeclinesDirtyWriter() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long writesBefore = direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES);
		try (var dataset = dataset()) {
			direct.storeTxnStartedFlag().set(true);
			direct.storeTxnDirtyFlag().set(true);
			try {
				assertThat(dataset.rows(-1, p1, -1, -1)).hasSize(3);
			} finally {
				direct.storeTxnDirtyFlag().set(false);
				direct.storeTxnStartedFlag().set(false);
			}
		}
		assertThat(direct.snapshotMetrics().lookupHits).isEqualTo(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES)).isEqualTo(writesBefore + 1);
	}

	@Test
	void flaggedRootScanServesBoundContext() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long rootBefore = direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN);
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(-1, p1, -1, g1), List.of(new long[] { s1, p1, o2, g1 }));
			assertSameRows(dataset.rows(-1, p1, -1, 0), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s2, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits)
				.as("bound-context root scans must be served from the adjacency planes")
				.isGreaterThan(hitsBefore + 1);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN)).isEqualTo(rootBefore);
	}

	@Test
	void flaggedRootScanBoundContextAbsentFromCatalogIsExactEmpty() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		long missesBefore = direct.snapshotMetrics().exactMisses;
		long rootBefore = direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN);
		try (var dataset = dataset()) {
			// o2 is a valid id that never occurs as a context: the catalog proves the scan empty
			assertThat(dataset.rows(-1, p1, -1, o2)).isEmpty();
		}
		assertThat(direct.snapshotMetrics().exactMisses)
				.as("a context absent from the catalog must be an exact-empty answer, not a fallback")
				.isGreaterThan(missesBefore);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.ROOT_SCAN)).isEqualTo(rootBefore);
	}

	@Test
	void flaggedRootScanServesObjectOrder() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long orderBefore = direct.snapshotMetrics().fallbacks(FallbackReason.INDEX_ORDER_INCOMPATIBLE);
		try (var dataset = dataset()) {
			List<long[]> ordered = dataset.rows(StatementOrder.O, -1, p1, -1, -1);
			assertThat(ordered).hasSize(3);
			for (int i = 1; i < ordered.size(); i++) {
				assertThat(Long.compareUnsigned(ordered.get(i - 1)[2], ordered.get(i)[2]))
						.as("object-ordered root scan must be unsigned non-decreasing on the object")
						.isLessThanOrEqualTo(0);
			}
		}
		assertThat(direct.snapshotMetrics().lookupHits)
				.as("object-ordered root scans must be served from the incoming plane")
				.isGreaterThan(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.INDEX_ORDER_INCOMPATIBLE))
				.isEqualTo(orderBefore);
	}

	@Test
	void flaggedExactEmptyPruningKillsJoinSubtreeBeforeExecution() throws IOException {
		System.setProperty("rdf4j.lmdb.nativeQueryEngine.enabled", "true");
		openPreferStore();
		long prunesBefore = JoinDispatchTestAccess.exactEmptyPrunes();
		// s2 has no p3 edges: the adjacency NOT_FOUND proof must fold the whole join to an empty plan
		List<String> rows = queryRows("SELECT ?x ?y WHERE { <" + S2 + "> <" + P3 + "> ?x . ?x <" + P1 + "> ?y }",
				"x", "y");
		assertThat(rows).isEmpty();
		assertThat(JoinDispatchTestAccess.exactEmptyPrunes())
				.as("the compile-time NOT_FOUND proof must prune the pattern before execution")
				.isGreaterThan(prunesBefore);
	}

	@Test
	void flaggedRootScanServesSubjectOrderAndExactEmpty() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.remove(S1, P2, O1);
		}
		direct.pauseApplierForTest(false);

		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			List<long[]> ordered = dataset.rows(StatementOrder.S, -1, p1, -1, -1);
			assertThat(ordered).hasSize(3);
			assertThat(Long.compareUnsigned(ordered.get(0)[0], ordered.get(1)[0])).isLessThanOrEqualTo(0);
			assertThat(Long.compareUnsigned(ordered.get(1)[0], ordered.get(2)[0])).isLessThanOrEqualTo(0);
			assertThat(dataset.rows(-1, p2, -1, -1)).isEmpty();
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore + 1);
	}

	@Test
	void flaggedRootScanBulkDecodesSupernodeRun() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.ROOT_SCAN_PROPERTY, "true");
		openPreferStore();
		IRI widePredicate = F.createIRI("http://example.org/root-wide");
		int edgeCount = 65_537;
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			for (int edge = 0; edge < edgeCount; edge++) {
				connection.add(S2, widePredicate, F.createIRI("http://example.org/root-wide/object/" + edge));
			}
			connection.commit();
		}
		assertThat(direct.buildNowForTest()).isTrue();

		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			long predicate = dataset.idOf(widePredicate);
			assertThat(dataset.rows(-1, predicate, -1, -1)).hasSize(edgeCount);
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void disabledDoublyBoundSpecializationRetainsUniversalCandidate() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.BOUND_PROBE_PROPERTY, "false");
		openPreferStore();
		FallbackReason doublyBound = FallbackReason.valueOf("DOUBLY_BOUND");
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long fallbacksBefore = direct.snapshotMetrics().fallbacks(doublyBound);
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s1, p1, o1, -1), List.of(new long[] { s1, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(doublyBound)).isEqualTo(fallbacksBefore);
	}

	@Test
	void doublyBoundProbeServesFromDirectAdjacencyByDefault() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long fallbacksBefore = direct.snapshotMetrics().fallbacks(FallbackReason.DOUBLY_BOUND);
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s1, p1, o1, -1), List.of(new long[] { s1, p1, o1, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.DOUBLY_BOUND)).isEqualTo(fallbacksBefore);
	}

	@Test
	void flaggedDoublyBoundProbePreservesContextsExactEmptyAndInlineObjects() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.BOUND_PROBE_PROPERTY, "true");
		openPreferStore();
		try (RepositoryConnection connection = repo.getConnection()) {
			connection.begin();
			connection.add(S1, P1, O1, G1);
			connection.add(S1, P1, O1, G2);
			connection.commit();
		}
		direct.pauseApplierForTest(false);

		long hitsBefore = direct.snapshotMetrics().lookupHits;
		long fallbacksBefore = direct.snapshotMetrics().fallbacks(FallbackReason.DOUBLY_BOUND);
		try (var dataset = dataset()) {
			long g2 = dataset.idOf(G2);
			assertSameRows(dataset.rows(s1, p1, o1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o1, g1 },
					new long[] { s1, p1, o1, g2 }));
			assertSameRows(dataset.rows(s1, p1, o1, g1), List.of(new long[] { s1, p1, o1, g1 }));
			assertThat(dataset.rows(s2, p1, o2, -1)).isEmpty();
			assertSameRows(dataset.rows(s1, p3, inline42, -1),
					List.of(new long[] { s1, p3, inline42, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThanOrEqualTo(hitsBefore + 4);
		assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.DOUBLY_BOUND)).isEqualTo(fallbacksBefore);
	}

	@Test
	void orderedShapesUseCompatibleFastPathOrUniversalCandidate() throws IOException {
		openPreferStore();
		try (var dataset = dataset()) {
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			List<long[]> byObject = dataset.rows(StatementOrder.O, s1, p1, -1, -1);
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
			assertThat(byObject).hasSize(2);
			assertThat(Long.compareUnsigned(byObject.get(0)[2], byObject.get(1)[2])).isNegative();

			long incompatibleBefore = direct.snapshotMetrics().fallbacks(FallbackReason.INDEX_ORDER_INCOMPATIBLE);
			long universalBefore = direct.snapshotMetrics().lookupHits;
			assertSameRows(dataset.rows(StatementOrder.S, s1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 }));
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.INDEX_ORDER_INCOMPATIBLE))
					.isEqualTo(incompatibleBefore);
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(universalBefore);

			long subjectOrderIncoming = direct.snapshotMetrics().lookupHits;
			List<long[]> bySubject = dataset.rows(StatementOrder.S, -1, p1, o1, -1);
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(subjectOrderIncoming);
			assertThat(bySubject).hasSize(2);
			assertThat(Long.compareUnsigned(bySubject.get(0)[0], bySubject.get(1)[0])).isNegative();
		}
	}

	@Test
	void flaggedCleanWriteTransactionServesDirectLookup() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.CLEAN_TXN_READS_PROPERTY, "true");
		assertCleanWriteTransactionServesDirectLookup();
	}

	@Test
	void cleanWriteTransactionServesDirectLookupByDefault() throws IOException {
		assertCleanWriteTransactionServesDirectLookup();
	}

	private void assertCleanWriteTransactionServesDirectLookup() throws IOException {
		openPreferStore();
		backing.enableMultiThreading = false;
		SailSink sink = backing.getExplicitSailSource().sink(IsolationLevels.READ_COMMITTED);
		try {
			sink.approve(S1, P1, O1, null);
			assertThat(direct.storeTxnStartedFlag()).isTrue();

			long hitsBefore = direct.snapshotMetrics().lookupHits;
			long bypassBefore = direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES);
			try (var dataset = dataset()) {
				assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
						new long[] { s1, p1, o1, 0 },
						new long[] { s1, p1, o2, g1 }));
			}
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES))
					.isEqualTo(bypassBefore);
		} finally {
			sink.flush();
			sink.close();
		}
	}

	@Test
	void flaggedDirtyWriteTransactionFallsBackAndReadsItsOwnAddAndRemove() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.CLEAN_TXN_READS_PROPERTY, "true");
		openPreferStore();
		backing.enableMultiThreading = false;
		IRI uncommitted = F.createIRI("http://example.org/uncommitted");
		SailSink sink = backing.getExplicitSailSource().sink(IsolationLevels.READ_COMMITTED);
		try {
			sink.approve(S1, P1, uncommitted, null);
			sink.deprecate(F.createStatement(S1, P1, O1));
			assertThat(direct.storeTxnStartedFlag()).isTrue();
			assertThat(direct.storeTxnDirtyFlag()).isTrue();

			TripleStore tripleStore = backing.getTripleStore();
			var writerTxn = tripleStore.getTxnManager().createTxn(tripleStore.writeTxn);
			List<long[]> writerRows = CloseableDataset
					.collect(tripleStore.getTriples(writerTxn, s1, p1, -1, -1, true));
			assertThat(writerRows).hasSize(2);
			assertThat(writerRows.stream().anyMatch(row -> row[2] == o1)).isFalse();
			assertThat(writerRows.stream().anyMatch(row -> row[2] == o2)).isTrue();

			long hitsBefore = direct.snapshotMetrics().lookupHits;
			long bypassBefore = direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES);
			try (var dataset = dataset()) {
				assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
						new long[] { s1, p1, o1, 0 },
						new long[] { s1, p1, o2, g1 }));
			}
			assertThat(direct.snapshotMetrics().lookupHits).isEqualTo(hitsBefore);
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES))
					.isGreaterThan(bypassBefore);
		} finally {
			backing.rollback();
			sink.close();
		}
	}

	@Test
	void flaggedRollbackResetsDirtyStateAndSameConnectionServesAgain() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.CLEAN_TXN_READS_PROPERTY, "true");
		openPreferStore();
		backing.enableMultiThreading = false;
		IRI rolledBack = F.createIRI("http://example.org/rolled-back");
		SailSink sink = backing.getExplicitSailSource().sink(IsolationLevels.READ_COMMITTED);
		try {
			sink.approve(S1, P1, rolledBack, null);
			assertThat(direct.storeTxnDirtyFlag()).isTrue();
			backing.rollback();
			assertThat(direct.storeTxnStartedFlag()).isFalse();
			assertThat(direct.storeTxnDirtyFlag()).isFalse();

			sink.approve(S1, P1, O1, null);
			assertThat(direct.storeTxnStartedFlag()).isTrue();
			assertThat(direct.storeTxnDirtyFlag()).isFalse();
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			try (var dataset = dataset()) {
				assertThat(dataset.source.has(s1, p1, o1, -1)).isTrue();
			}
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
			backing.rollback();
		} finally {
			if (direct.storeTxnStartedFlag().get()) {
				backing.rollback();
			}
			sink.close();
		}
	}

	@Test
	void disabledCleanTransactionReadsRestoresConservativeBypass() throws IOException {
		System.setProperty(LmdbDirectAdjacencyStore.CLEAN_TXN_READS_PROPERTY, "false");
		openPreferStore();
		try (var dataset = dataset()) {
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			long bypassBefore = direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES);
			direct.storeTxnStartedFlag().set(true);
			try {
				assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
						new long[] { s1, p1, o1, 0 },
						new long[] { s1, p1, o2, g1 }));
			} finally {
				direct.storeTxnStartedFlag().set(false);
			}
			assertThat(direct.snapshotMetrics().lookupHits).isEqualTo(hitsBefore);
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.READ_YOUR_WRITES))
					.isGreaterThan(bypassBefore);
		}
	}

	@Test
	void serializableIsolationBypassesDirectAdjacency() throws IOException {
		openPreferStore();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		var dataset = backing.getExplicitSailSource().dataset(IsolationLevels.SERIALIZABLE);
		try {
			List<long[]> rows = CloseableDataset.collect(
					((NativeLmdbQuerySource) dataset).statements(s1, p1, -1, -1));
			assertThat(rows).hasSize(2);
		} finally {
			dataset.close();
		}
		assertThat(direct.snapshotMetrics().lookupHits).isEqualTo(hitsBefore);
	}

	@Test
	void snapshotAfterCommitFallsBackUntilRebuildAndOldSnapshotKeepsServing() throws IOException {
		openPreferStore();
		try (var pinnedBeforeCommit = dataset()) {
			try (RepositoryConnection conn = repo.getConnection()) {
				conn.add(S2, P2, O2);
			}
			// the old pinned snapshot equals the base revision: it must keep serving exactly (invariant I3)
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			assertSameRows(pinnedBeforeCommit.rows(s1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 }));
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
		}
		// a rebuild at the new revision serves new snapshots again
		assertThat(direct.buildNowForTest()).isTrue();
		long hitsBefore = direct.snapshotMetrics().lookupHits;
		try (var dataset = dataset()) {
			assertSameRows(dataset.rows(s2, p2, -1, -1), List.of(new long[] { s2, p2, o2, 0 }));
		}
		assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);
	}

	@Test
	void selectedCoverageServesSelectedAndFallsBackForUnselected() throws IOException {
		openStore(DirectAdjacencyMode.PREFER, DirectAdjacencyCoverage.SELECTED, List.of(P1));
		try (var dataset = dataset()) {
			long hitsBefore = direct.snapshotMetrics().lookupHits;
			assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 }));
			assertThat(direct.snapshotMetrics().lookupHits).isGreaterThan(hitsBefore);

			long uncoveredBefore = direct.snapshotMetrics().fallbacks(FallbackReason.PLANE_NOT_COVERED);
			assertSameRows(dataset.rows(s1, p2, -1, -1), List.of(new long[] { s1, p2, o1, 0 }));
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.PLANE_NOT_COVERED))
					.isGreaterThan(uncoveredBefore);

			// SELECTED cannot answer ?predicate completely: falls back before the first result
			long enumBefore = direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE);
			assertThat(dataset.rows(s1, -1, -1, -1)).hasSize(4);
			assertThat(direct.snapshotMetrics().fallbacks(FallbackReason.PREDICATE_ENUMERATION_INCOMPLETE))
					.isGreaterThan(enumBefore);
		}
	}

	@Test
	void shadowComparesButNeverServes() throws IOException {
		System.setProperty(LmdbDirectAdjacencyOptions.SHADOW_SAMPLE_EVERY_PROPERTY, "1");
		openStore(DirectAdjacencyMode.SHADOW, null, null);
		try (var dataset = dataset()) {
			long comparisonsBefore = direct.snapshotMetrics().shadowComparisons;
			assertSameRows(dataset.rows(s1, p1, -1, -1), List.of(
					new long[] { s1, p1, o1, 0 },
					new long[] { s1, p1, o2, g1 }));
			LmdbAdjacencyMetrics.Snapshot metrics = direct.snapshotMetrics();
			assertThat(metrics.shadowComparisons).isGreaterThan(comparisonsBefore);
			assertThat(metrics.shadowMismatches).isZero();
			assertThat(metrics.lookupHits).isZero();
		}
	}
}
