/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.evaluation.TripleSource;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.EvaluationStatistics;
import org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategy;
import org.eclipse.rdf4j.query.impl.EmptyBindingSet;
import org.eclipse.rdf4j.query.parser.sparql.SPARQLParser;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class LmdbFilterSimplifierBoundaryTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();
	private SailRepository repository;
	private SailRepositoryConnection connection;

	@BeforeEach
	void setUp(@TempDir File dataDir) {
		repository = new SailRepository(new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc")));
		repository.init();
		connection = repository.getConnection();
		connection.begin();
		connection.add(VF.createIRI("urn:a"), VF.createIRI("urn:scope:p"), VF.createLiteral("literal"));
		connection.add(VF.createIRI("urn:b"), VF.createIRI("urn:scope:p"), VF.createIRI("urn:object"));
		connection.add(VF.createBNode("subject"), VF.createIRI("urn:minus:p"), VF.createLiteral("object"));
		connection.add(VF.createIRI("urn:keep"), VF.createIRI("urn:minus:p"), VF.createLiteral("object"));
		connection.add(VF.createIRI("urn:exclude"), VF.createIRI("urn:minus:p"), VF.createLiteral("object"));
		connection.commit();
	}

	@AfterEach
	void tearDown() {
		connection.close();
		repository.shutDown();
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"{ SELECT ?s WHERE { ?s <urn:scope:p> ?x } }",
			"{ SELECT ?s WHERE { { SELECT ?s WHERE { ?s <urn:scope:p> ?x } } } }" })
	void idFilterDoesNotConstrainHiddenSubqueryBinding(String subquery) {
		String query = """
				SELECT ?s ?x WHERE {
				  %s
				  BIND(IRI(STR(?s)) AS ?x)
				  FILTER(isIRI(?x))
				} ORDER BY ?s
				""".formatted(subquery);
		assertEquals(List.of(VF.createIRI("urn:a"), VF.createIRI("urn:b")), values(query, "s"));
	}

	@Test
	void idFilterDoesNotMoveBeforeSubqueryLimit() {
		String query = """
				SELECT ?s WHERE {
				  { SELECT ?s ?x WHERE { ?s <urn:scope:p> ?x } ORDER BY ?s LIMIT 1 }
				  FILTER(isIRI(?x))
				}
				""";
		assertEquals(List.of(), values(query, "s"));
	}

	@Test
	void idFilterDoesNotConstrainAggregateInputWithSameName() {
		String query = """
				SELECT ?s WHERE {
				  { SELECT ?s (COUNT(*) AS ?x) WHERE { ?s <urn:scope:p> ?x } GROUP BY ?s }
				  FILTER(isNumeric(?x))
				} ORDER BY ?s
				""";
		assertEquals(List.of(VF.createIRI("urn:a"), VF.createIRI("urn:b")), values(query, "s"));
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"CONTAINS(STR(?s), \"exclude\")",
			"CONTAINS(STR(?s), \"exclude\") && CONTAINS(STR(?o), \"object\")",
			"CONTAINS(STR(?o), \"object\") && CONTAINS(STR(?s), \"exclude\")" })
	void minusPreservesRowsWhenRightFilterErrors(String condition) {
		String query = """
				SELECT ?s WHERE {
				  ?s <urn:minus:p> ?o
				  MINUS { ?s <urn:minus:p> ?o FILTER(%s) }
				}
				""".formatted(condition);
		List<Value> subjects = values(query, "s");
		assertEquals(2, subjects.size(), subjects::toString);
		assertTrue(subjects.contains(VF.createBNode("subject")), subjects::toString);
		assertTrue(subjects.contains(VF.createIRI("urn:keep")), subjects::toString);
	}

	@Test
	void minusWithNoSharedVariablesPreservesConstantPattern() {
		assertTrue(connection.prepareBooleanQuery("""
				ASK {
				  <urn:keep> <urn:minus:p> "object"
				  MINUS { <urn:keep> <urn:minus:p> "object" FILTER(CONTAINS("a", "a")) }
				}
				""").evaluate());
	}

	@Test
	void standaloneSimplifierPreservesMinusWithNoSharedVariables() {
		assertEquals(1, simplifiedResults("""
				SELECT * WHERE {
				  <urn:keep> <urn:minus:p> "object"
				  MINUS { <urn:keep> <urn:minus:p> "object" FILTER(CONTAINS("a", "a")) }
				}
				""").size());
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"CONTAINS(STR(?s), \"exclude\") && CONTAINS(STR(?o), \"object\")",
			"CONTAINS(STR(?o), \"object\") && CONTAINS(STR(?s), \"exclude\")" })
	void standaloneSimplifierPreservesErrorsAcrossConjunctions(String condition) {
		assertEquals(2, simplifiedResults("""
				SELECT ?s WHERE {
				  ?s <urn:minus:p> ?o
				  MINUS { ?s <urn:minus:p> ?o FILTER(%s) }
				}
				""".formatted(condition)).size());
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"{ SELECT ?s WHERE { ?s <urn:minus:p> ?o MINUS { ?s <urn:minus:p> ?o FILTER(CONTAINS(STR(?s), \"exclude\")) } } }",
			"?s <urn:minus:p> ?o FILTER EXISTS { ?s <urn:minus:p> ?o MINUS { ?s <urn:minus:p> ?o FILTER(CONTAINS(STR(?s), \"exclude\")) } }" })
	void minusPreservesErrorSemanticsInsideNestedScopes(String pattern) {
		List<Value> subjects = values("SELECT ?s WHERE { " + pattern + " }", "s");
		assertEquals(2, subjects.size(), subjects::toString);
		assertTrue(subjects.contains(VF.createBNode("subject")), subjects::toString);
		assertTrue(subjects.contains(VF.createIRI("urn:keep")), subjects::toString);
	}

	private List<BindingSet> simplifiedResults(String query) {
		QueryRoot root = new QueryRoot(new SPARQLParser().parseQuery(query, "urn:test:").getTupleExpr());
		new LmdbFilterSimplifierOptimizer(new EvaluationStatistics()).optimize(root, null,
				EmptyBindingSet.getInstance());
		TripleSource source = new TripleSource() {
			@Override
			public CloseableIteration<? extends Statement> getStatements(Resource subject, IRI predicate, Value object,
					Resource... contexts) {
				return connection.getStatements(subject, predicate, object, false, contexts);
			}

			@Override
			public ValueFactory getValueFactory() {
				return VF;
			}
		};
		List<BindingSet> rows = new ArrayList<>();
		try (CloseableIteration<BindingSet> result = new StrictEvaluationStrategy(source, null).precompile(root)
				.evaluate(EmptyBindingSet.getInstance())) {
			while (result.hasNext()) {
				rows.add(result.next());
			}
		}
		return rows;
	}

	private List<Value> values(String query, String name) {
		List<Value> values = new ArrayList<>();
		try (TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
			while (result.hasNext()) {
				values.add(result.next().getValue(name));
			}
		}
		return values;
	}
}
