/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.ArbitraryLengthPath;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.UnaryTupleOperator;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.benchmark.AASGenerator;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;

@Timeout(60)
class LmdbAASQuery2CascadesHypergraphPlanningTest {

	private static final String QUERY = """
			PREFIX aas: <https://admin-shell.io/aas/3/>
			SELECT (COUNT(*) AS ?c)
			WHERE {
			  ?aas a aas:AssetAdministrationShell ;
			    aas:assetInformation/aas:specificAssetId [ aas:value "DriveUnit" ] ;
			    aas:submodel/aas:submodelElement/(aas:value)* ?p1 .
			  ?p1 aas:idShort "ratedPower" ;
			      aas:value ?v1 .
			  FILTER (?v1 > 15.0)
			}
			""";

	private static final String QUERY_3 = """
			PREFIX aas: <https://admin-shell.io/aas/3/>
			PREFIX aas-ext: <https://admin-shell.io/aas/3/extended/>
			PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
			SELECT ?lineAAS (COUNT(DISTINCT ?compAAS) AS ?numDrives) (AVG(xsd:double(?val)) AS ?avgPower)
			WHERE {
			  ?lineAAS a aas:AssetAdministrationShell ;
			           aas:submodel / aas:submodelElement ?rel .
			  ?rel a aas:RelationshipElement ;
			       aas:second / aas-ext:resolvesTo ?compAAS .
			  ?compAAS aas:submodel / aas:submodelElement / (aas:value)* ?prop .
			  ?prop aas:idShort "ratedPower" ;
			        aas:value ?val .
			}
			GROUP BY ?lineAAS
			""";

	@Test
	void query2UsesConnectedEndpointBoundPathWithBoundedWork(@TempDir File dataDir) throws Exception {
		String previousMode = System.setProperty(LmdbCascadesOptimizer.MODE_PROPERTY, "budgeted");
		String previousBudget = System.setProperty(LmdbCascadesOptimizer.BUDGET_PROPERTY, "256");
		LmdbStore store = new LmdbStore(dataDir, new LmdbStoreConfig("spoc,ospc,psoc"));
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			try (SailRepositoryConnection connection = repository.getConnection()) {
				new AASGenerator().generateAndAdd(connection, 100, 100, 100);
			}

			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(QUERY)
						.explain(Explanation.Level.Optimized);
				TupleExpr optimized = (TupleExpr) explanation.tupleExpr();
				String plan = explanation.toString();
				List<TupleExpr> factors = leftDeepFactors(optimized);
				int ratedPower = indexOfRatedPowerAnchor(factors);
				int p1Value = indexOfP1ValueFilter(factors);
				int path = indexOfPath(factors);

				assertTrue(ratedPower >= 0, () -> "Missing ratedPower idShort anchor in plan factors: " + factors);
				assertTrue(p1Value >= 0, () -> "Missing threshold value filter in plan factors: " + factors);
				assertTrue(path >= 0, () -> "Missing property path in plan factors: " + factors);
				assertTrue(plan.contains(LmdbCascadesConnectedJoinPlanner.RULE_ID),
						() -> "The connected island must use the DPhyp implementation:\n" + plan);
				assertTrue(plan.contains("plannedPropertyPathEndpointMode=toEnd"),
						() -> "The property path must be parameterized from the selective ?p1 endpoint:\n" + plan);
				assertTrue(optimized.getDoubleMetricPlanned("plannedCostCartesianWorkRows") == 0.0d,
						() -> "The connected query must not introduce Cartesian work:\n" + plan);
				double plannedWork = optimized.getDoubleMetricPlanned("plannedCostWorkRows");
				assertTrue(plannedWork > 0.0d && plannedWork < 2_000_000.0d,
						() -> "The generated AAS query must retain bounded planned work, found " + plannedWork);
				assertTrue(singleLong(connection, QUERY, "c") > 0L,
						"The endpoint-bound DPhyp plan must preserve the aggregate result");
			}
		} finally {
			repository.shutDown();
			restoreProperty(LmdbCascadesOptimizer.MODE_PROPERTY, previousMode);
			restoreProperty(LmdbCascadesOptimizer.BUDGET_PROPERTY, previousBudget);
		}
	}

	@Test
	void query3UsesConnectedBoundedPlanWithDirectPropertyValueLookup(@TempDir File dataDir) throws Exception {
		String previousMode = System.setProperty(LmdbCascadesOptimizer.MODE_PROPERTY, "budgeted");
		String previousBudget = System.setProperty(LmdbCascadesOptimizer.BUDGET_PROPERTY, "256");
		LmdbStore store = new LmdbStore(dataDir, new LmdbStoreConfig("spoc,ospc,psoc"));
		SailRepository repository = new SailRepository(store);
		repository.init();
		try {
			try (SailRepositoryConnection connection = repository.getConnection()) {
				new AASGenerator().generateAndAdd(connection, 100, 100, 100);
			}

			try (SailRepositoryConnection connection = repository.getConnection()) {
				Explanation explanation = connection.prepareTupleQuery(QUERY_3)
						.explain(Explanation.Level.Optimized);
				TupleExpr optimized = (TupleExpr) explanation.tupleExpr();
				String plan = explanation.toString();
				List<TupleExpr> factors = leftDeepFactors(optimized);
				int ratedPower = indexOfRatedPowerAnchor(factors);
				int propValue = indexOfPropValueLookup(factors);
				int path = indexOfPath(factors);

				assertTrue(ratedPower >= 0, () -> "Missing ratedPower idShort anchor in plan factors: " + factors);
				assertTrue(propValue >= 0, () -> "Missing direct prop value lookup in plan factors: " + factors);
				assertTrue(path >= 0, () -> "Missing property path in plan factors: " + factors);
				TupleExpr propertyValue = unwrapUnary(factors.get(propValue));
				assertTrue(propertyValue instanceof StatementPattern,
						() -> "Property value factor must remain a statement lookup: " + propertyValue);
				assertTrue("directLookup".equals(propertyValue.getStringMetricPlanned("plannedIndexAccessMode")),
						() -> "Property value factor must retain direct-lookup costing: " + propertyValue);
				assertTrue(propertyValue.getDoubleMetricPlanned("plannedAccessRows") <= 1.0d,
						() -> "Bound property value access must stay constant-work: " + propertyValue);
				assertTrue(plan.contains(LmdbCascadesConnectedJoinPlanner.RULE_ID),
						() -> "The connected island must use the DPhyp implementation:\n" + plan);
				assertTrue(optimized.getDoubleMetricPlanned("plannedCostCartesianWorkRows") == 0.0d,
						() -> "The connected query must not introduce Cartesian work:\n" + plan);
				double plannedWork = optimized.getDoubleMetricPlanned("plannedCostWorkRows");
				assertTrue(plannedWork > 0.0d && plannedWork < 2_000_000.0d,
						() -> "The generated AAS query must retain bounded planned work, found " + plannedWork);
			}
		} finally {
			repository.shutDown();
			restoreProperty(LmdbCascadesOptimizer.MODE_PROPERTY, previousMode);
			restoreProperty(LmdbCascadesOptimizer.BUDGET_PROPERTY, previousBudget);
		}
	}

	private static List<TupleExpr> leftDeepFactors(TupleExpr root) {
		TupleExpr joinIsland = unwrapUnary(root);
		List<TupleExpr> factors = new ArrayList<>();
		collectJoinFactors(joinIsland, factors);
		return List.copyOf(factors);
	}

	private static void collectJoinFactors(TupleExpr tupleExpr, List<TupleExpr> factors) {
		TupleExpr unwrapped = unwrapUnary(tupleExpr);
		if (unwrapped instanceof Join join) {
			collectJoinFactors(join.getLeftArg(), factors);
			collectJoinFactors(join.getRightArg(), factors);
		} else if (unwrapped != null) {
			factors.add(unwrapped);
		}
	}

	private static TupleExpr unwrapUnary(TupleExpr tupleExpr) {
		TupleExpr current = tupleExpr;
		while (current instanceof UnaryTupleOperator unary) {
			current = unary.getArg();
		}
		return current;
	}

	private static int indexOfPath(List<TupleExpr> factors) {
		for (int i = 0; i < factors.size(); i++) {
			if (factors.get(i) instanceof ArbitraryLengthPath) {
				return i;
			}
		}
		return -1;
	}

	private static int indexOfRatedPowerAnchor(List<TupleExpr> factors) {
		for (int i = 0; i < factors.size(); i++) {
			if (factors.get(i)instanceof StatementPattern pattern
					&& predicateLocalName(pattern).equals("idShort")
					&& pattern.getObjectVar() != null
					&& pattern.getObjectVar().getValue()instanceof Literal literal
					&& "ratedPower".equals(literal.getLabel())) {
				return i;
			}
		}
		return -1;
	}

	private static int indexOfP1ValueFilter(List<TupleExpr> factors) {
		for (int i = 0; i < factors.size(); i++) {
			TupleExpr factor = unwrapUnary(factors.get(i));
			if (factor instanceof StatementPattern pattern
					&& predicateLocalName(pattern).equals("value")
					&& pattern.getSubjectVar() != null
					&& "p1".equals(pattern.getSubjectVar().getName())
					&& pattern.getObjectVar() != null
					&& "v1".equals(pattern.getObjectVar().getName())) {
				return i;
			}
		}
		return -1;
	}

	private static int indexOfPropValueLookup(List<TupleExpr> factors) {
		for (int i = 0; i < factors.size(); i++) {
			TupleExpr factor = unwrapUnary(factors.get(i));
			if (factor instanceof StatementPattern pattern
					&& predicateLocalName(pattern).equals("value")
					&& pattern.getSubjectVar() != null
					&& "prop".equals(pattern.getSubjectVar().getName())
					&& pattern.getObjectVar() != null
					&& "val".equals(pattern.getObjectVar().getName())) {
				return i;
			}
		}
		return -1;
	}

	private static String predicateLocalName(StatementPattern pattern) {
		if (pattern.getPredicateVar() == null || !(pattern.getPredicateVar().getValue()instanceof IRI iri)) {
			return "";
		}
		String value = iri.stringValue();
		int slash = value.lastIndexOf('/');
		return slash >= 0 ? value.substring(slash + 1) : value;
	}

	private static long singleLong(SailRepositoryConnection connection, String query, String bindingName) {
		try (var result = connection.prepareTupleQuery(query).evaluate()) {
			if (!result.hasNext()) {
				return 0L;
			}
			BindingSet bindingSet = result.next();
			if (bindingSet.getValue(bindingName)instanceof Literal literal) {
				return literal.longValue();
			}
			return 0L;
		}
	}

	private static void restoreProperty(String property, String previousValue) {
		if (previousValue == null) {
			System.clearProperty(property);
		} else {
			System.setProperty(property, previousValue);
		}
	}
}
