/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;

import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.junit.jupiter.api.Test;

/**
 * Hard semantic dependencies of a cached plan family (predicate-guarantee identity, committed data revision) must not
 * only force a replan on mismatch; the replacement plan built for the current dependencies must also be publishable so
 * the family does not degrade to replanning on every invocation.
 */
class LmdbPlanDecisionCacheHardDependencyTest {

	private static final TupleExpr TEMPLATE = new StatementPattern(Var.of("subject"), Var.of("predicate"),
			Var.of("object"));

	@Test
	void hardDependencyMismatchAllowsReplacementBuild() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dependencies(1L, "guarantee-identity-1");
		LmdbPlanDecisionCache.SemanticDependencies current = dependencies(1L, "guarantee-identity-2");

		assertTrue(cache.publishBuild(publication(stored)));
		assertReplan(cache.lookupExact(exactKey(), request(current)), "semantic-dependency-mismatch");

		assertTrue(cache.publishBuild(publication(current)),
				"the plan built for the current hard dependencies must replace the stale version");
		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(current)));
		assertEquals(current, currentDependencies(cache));
	}

	@Test
	void hardDependencyMismatchOnGenerationAllowsReplacementBuild() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dependencies(17L, "guarantee-identity");
		LmdbPlanDecisionCache.SemanticDependencies current = dependencies(18L, "guarantee-identity");

		assertTrue(cache.publishBuild(publication(stored)));
		assertReplan(cache.lookupExact(exactKey(), request(current)), "semantic-dependency-mismatch");
		assertTrue(cache.publishBuild(publication(current)),
				"a hard generation mismatch must let the current build replace the stale version");
		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(current)));
		assertReplan(cache.lookupExact(exactKey(), request(stored)), "semantic-dependency-mismatch");
	}

	@Test
	void matchingHardDependencyStillRefusesToReplaceAValidVersion() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dependencies(1L, "guarantee-identity");

		assertTrue(cache.publishBuild(publication(stored)));
		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(stored)));
		LmdbPlanDecisionCache.BuildPublication different = new LmdbPlanDecisionCache.BuildPublication(familyKey(),
				exactKey(), stored, evidence(), evidence(), TEMPLATE.clone(), "other-physical",
				LmdbPlanDecisionCache.EstimatedCostInterval.unbounded(), certificate(), 1024L, 1L);
		assertFalse(cache.publishBuild(different),
				"a build is not refresh authority while the retained version still matches its dependencies");
	}

	@Test
	void refreshPublicationKeepsHardIndexDependency() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dependencies(1L, "guarantee-identity-1");
		assertTrue(cache.publishBuild(publication(stored)));
		LmdbPlanDecisionCache.Use use = assertInstanceOf(LmdbPlanDecisionCache.Use.class,
				cache.lookupExact(exactKey(), request(stored)));

		assertTrue(cache.publishRefresh(new LmdbPlanDecisionCache.RefreshPublication(familyKey(),
				use.familyVersion(), stored, evidence(), evidence(), use.variantId(), TEMPLATE.clone(),
				"physical-fingerprint", new LmdbPlanDecisionCache.EstimatedCostInterval(1.0d, 1.0d), null,
				certificate(), LmdbPlanDecisionCache.PlanStabilityEnvelope.exact(evidence()), 1024L, 1L, true, true,
				1L, "guarantee-identity-1", null)));

		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(stored)));
		assertReplan(cache.lookupExact(exactKey(), request(dependencies(1L, "guarantee-identity-2"))),
				"semantic-dependency-mismatch");
	}

	@Test
	void dataRevisionDependentVersionReplansAtAnotherRevisionAndIsReplaced() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dataDependencies(17L);
		LmdbPlanDecisionCache.SemanticDependencies current = dataDependencies(18L);

		assertTrue(cache.publishBuild(publication(stored)));
		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(stored)));
		assertReplan(cache.lookupExact(exactKey(), request(current)), "semantic-dependency-mismatch");
		assertTrue(cache.publishBuild(publication(current)),
				"the plan built at the current data revision must replace the stale version");
		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(current)));
		assertEquals(current, currentDependencies(cache));
	}

	@Test
	void versionWithoutDataRevisionDependencyIgnoresTheDataRevision() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dependencies(1L, "guarantee-identity");

		assertTrue(cache.publishBuild(publication(stored)));

		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(),
				request(new LmdbPlanDecisionCache.SemanticDependencies("dataset", "bindings", "unordered", "standard",
						1L, "guarantee-identity", true, 1L, 1L, 1L, 1L, "config", "provider", 18L, true))));
	}

	@Test
	void refreshPublicationKeepsHardDataRevisionDependency() {
		LmdbPlanDecisionCache cache = new LmdbPlanDecisionCache(8, 1024 * 1024L);
		LmdbPlanDecisionCache.SemanticDependencies stored = dataDependencies(17L);
		assertTrue(cache.publishBuild(publication(stored)));
		LmdbPlanDecisionCache.Use use = assertInstanceOf(LmdbPlanDecisionCache.Use.class,
				cache.lookupExact(exactKey(), request(stored)));

		assertTrue(cache.publishRefresh(new LmdbPlanDecisionCache.RefreshPublication(familyKey(),
				use.familyVersion(), stored, evidence(), evidence(), use.variantId(), TEMPLATE.clone(),
				"physical-fingerprint", new LmdbPlanDecisionCache.EstimatedCostInterval(1.0d, 1.0d), null,
				certificate(), LmdbPlanDecisionCache.PlanStabilityEnvelope.exact(evidence()), 1024L, 1L, true, false,
				0L, null, true, 17L, null)));

		assertInstanceOf(LmdbPlanDecisionCache.Use.class, cache.lookupExact(exactKey(), request(stored)));
		assertReplan(cache.lookupExact(exactKey(), request(dataDependencies(18L))), "semantic-dependency-mismatch");
	}

	private static LmdbPlanDecisionCache.SemanticDependencies dataDependencies(long dataRevision) {
		return new LmdbPlanDecisionCache.SemanticDependencies("dataset", "bindings", "unordered", "standard", 0L,
				null, false, 1L, 1L, 1L, 1L, "config", "provider", dataRevision, true);
	}

	private static LmdbPlanDecisionCache.SemanticDependencies currentDependencies(LmdbPlanDecisionCache cache) {
		try {
			var field = LmdbPlanDecisionCache.class.getDeclaredField("families");
			field.setAccessible(true);
			@SuppressWarnings("unchecked")
			var families = (java.util.Map<LmdbPlanDecisionCache.PlanFamilyKey, LmdbPlanDecisionCache.PlanFamily>) field
					.get(cache);
			return families.get(familyKey()).current().get().semanticDependencies();
		} catch (ReflectiveOperationException failure) {
			throw new AssertionError(failure);
		}
	}

	private static void assertReplan(LmdbPlanDecisionCache.LookupDecision decision, String reason) {
		LmdbPlanDecisionCache.ReplanBeforeUse replan = assertInstanceOf(
				LmdbPlanDecisionCache.ReplanBeforeUse.class, decision);
		assertEquals(reason, replan.reason());
	}

	private static LmdbPlanDecisionCache.SemanticDependencies dependencies(long indexGeneration,
			Object indexIdentity) {
		return new LmdbPlanDecisionCache.SemanticDependencies("dataset", "bindings", "unordered", "standard",
				indexGeneration, indexIdentity, true, 1L, 1L, 1L, 1L, "config", "provider");
	}

	private static LmdbPlanDecisionCache.PlanFamilyKey familyKey() {
		return new LmdbPlanDecisionCache.PlanFamilyKey("canonical-family", "dataset", "bindings", "unordered",
				"standard", 1L, 1L, "environment");
	}

	private static LmdbPlanDecisionCache.ExactInvocationKey exactKey() {
		return new LmdbPlanDecisionCache.ExactInvocationKey(familyKey(), "complete-source", "semantic-context");
	}

	private static LmdbPlanDecisionCache.EvidenceSnapshot evidence() {
		return new LmdbPlanDecisionCache.EvidenceSnapshot(1L, 1L, 1L, 1L, 1L, 1L, Set.of(
				new LmdbPlanDecisionCache.EvidenceDependency(LmdbPlanDecisionCache.EvidenceKind.PHYSICAL_CAPABILITY,
						"spo-index", 1L)));
	}

	private static LmdbPlanDecisionCache.SearchCertificate certificate() {
		return new LmdbPlanDecisionCache.SearchCertificate(LmdbPlanDecisionCache.SearchCompletion.EXACT_COMPLETE,
				LmdbPlanDecisionCache.BoundKind.BEST_KNOWN_UNBOUNDED, Double.NaN, 1L, 1L, 0.0d, 10L);
	}

	private static LmdbPlanDecisionCache.LookupRequest request(
			LmdbPlanDecisionCache.SemanticDependencies dependencies) {
		return new LmdbPlanDecisionCache.LookupRequest(dependencies, evidence(),
				LmdbPlanDecisionCache.InvocationFeatures.empty(), 0.01d, true, false, false);
	}

	private static LmdbPlanDecisionCache.BuildPublication publication(
			LmdbPlanDecisionCache.SemanticDependencies dependencies) {
		return new LmdbPlanDecisionCache.BuildPublication(familyKey(), exactKey(), dependencies, evidence(),
				evidence(), TEMPLATE.clone(), "physical-fingerprint",
				LmdbPlanDecisionCache.EstimatedCostInterval.unbounded(), certificate(), 1024L, 1L);
	}
}
