/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryResults;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbNativeHashJoinBatchTest {

	private static final String EX = "http://example.com/";
	private static final String NATIVE_FLAG = "rdf4j.lmdb.nativeQueryEngine.enabled";
	private static final String QUERY = "PREFIX ex: <" + EX + ">\n"
			+ "SELECT ?left ?key ?right WHERE { ?left ex:key ?key . ?right ex:key ?key }";

	@TempDir
	File dataDir;

	SailRepository repository;

	@BeforeEach
	void setUp() {
		repository = new SailRepository(new LmdbStore(dataDir, new LmdbStoreConfig("spoc,posc,ospc")));
		try (SailRepositoryConnection connection = repository.getConnection()) {
			ValueFactory vf = connection.getValueFactory();
			IRI predicate = vf.createIRI(EX, "key");
			for (int i = 0; i < 200; i++) {
				connection.add(vf.createIRI(EX, "row" + i), predicate, vf.createIRI(EX, "key" + (i % 20)));
			}
		}
		System.setProperty(NativeBatch.ENABLED_PROPERTY, "true");
		System.setProperty(LmdbNativeHashJoin.MIN_ROWS_PROPERTY, "0");
		System.setProperty(NativeBatch.ROWS_PROPERTY, "31");
	}

	@AfterEach
	void tearDown() {
		System.clearProperty(NATIVE_FLAG);
		System.clearProperty(NativeBatch.ENABLED_PROPERTY);
		System.clearProperty(NativeBatch.ROWS_PROPERTY);
		System.clearProperty(LmdbNativeHashJoin.ENABLED_PROPERTY);
		System.clearProperty(LmdbNativeHashJoin.MIN_ROWS_PROPERTY);
		System.clearProperty(LmdbNativeHashJoin.MAX_BUILD_ROWS_PROPERTY);
		repository.shutDown();
	}

	@Test
	void primitiveHashJoinMatchesGenericBagSemantics() {
		List<String> generic = genericRows();
		resetCounters();

		assertThat(rows()).isEqualTo(generic).hasSize(2000);
		assertThat(LmdbNativeHashJoin.BUILDS.get()).isOne();
		assertThat(LmdbNativeHashJoin.PROBE_BATCHES.get()).isPositive();
		assertThat(LmdbNativeHashJoin.CAP_FALLBACKS.get()).isZero();
	}

	@Test
	void buildCapFallsBackBeforeEmittingRows() {
		List<String> generic = genericRows();
		resetCounters();
		System.setProperty(LmdbNativeHashJoin.MAX_BUILD_ROWS_PROPERTY, "5");

		assertThat(rows()).isEqualTo(generic).hasSize(2000);
		assertThat(LmdbNativeHashJoin.BUILDS.get()).isZero();
		assertThat(LmdbNativeHashJoin.CAP_FALLBACKS.get()).isOne();
	}

	@Test
	void disabledHashJoinKeepsExistingFactorizedOrNestedLoopPath() {
		List<String> generic = genericRows();
		resetCounters();
		System.setProperty(LmdbNativeHashJoin.ENABLED_PROPERTY, "false");

		assertThat(rows()).isEqualTo(generic).hasSize(2000);
		assertThat(LmdbNativeHashJoin.BUILDS.get()).isZero();
		assertThat(LmdbNativeHashJoin.PROBE_BATCHES.get()).isZero();
	}

	private List<String> genericRows() {
		System.setProperty(NATIVE_FLAG, "false");
		try {
			return rows();
		} finally {
			System.clearProperty(NATIVE_FLAG);
		}
	}

	private List<String> rows() {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			return QueryResults.asList(connection.prepareTupleQuery(QUERY).evaluate())
					.stream()
					.map(LmdbNativeHashJoinBatchTest::canonical)
					.sorted()
					.collect(Collectors.toList());
		}
	}

	private static String canonical(BindingSet bindings) {
		return bindings.getBindingNames()
				.stream()
				.sorted()
				.map(name -> name + "=" + bindings.getValue(name))
				.collect(Collectors.joining(";", "[", "]"));
	}

	private static void resetCounters() {
		LmdbNativeHashJoin.BUILDS.set(0);
		LmdbNativeHashJoin.PROBE_BATCHES.set(0);
		LmdbNativeHashJoin.CAP_FALLBACKS.set(0);
	}
}
