/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryResults;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.query.explanation.GenericPlanNode;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.repository.sail.SailRepositoryConnection;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class LmdbNativeOrderedDistinctTest {

	private static final String EX = "urn:ordered-distinct:";
	private static final String NATIVE_FLAG = "rdf4j.lmdb.nativeQueryEngine.enabled";

	@TempDir
	File dataDir;

	@Test
	void completeBirthdayPersonOrderUsesAdjacentDistinct() {
		SailRepository repository = repository("complete", "ospc,spoc");
		try {
			addPeople(repository);
			String query = "SELECT DISTINCT ?birthday ?person WHERE { ?person <" + EX
					+ "birthday> ?birthday . OPTIONAL { ?person <" + EX + "name> ?name . } }";

			assertThat(explain(repository, query)).contains("distinctStrategy=ADJACENT");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void repeatedBirthdayPartitionUsesResidualHash() {
		SailRepository repository = repository("partitioned", "ospc,spoc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI birthday = vf.createIRI(EX, "birthday/1");
			IRI p1 = vf.createIRI(EX, "person/1");
			IRI p2 = vf.createIRI(EX, "person/2");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(vf.createIRI(EX, "event/1"), vf.createIRI(EX, "onBirthday"), birthday);
				connection.add(vf.createIRI(EX, "event/2"), vf.createIRI(EX, "onBirthday"), birthday);
				connection.add(vf.createIRI(EX, "event/3"), vf.createIRI(EX, "onBirthday"), birthday);
				connection.add(vf.createIRI(EX, "event/1"), vf.createIRI(EX, "person"), p1);
				connection.add(vf.createIRI(EX, "event/2"), vf.createIRI(EX, "person"), p2);
				connection.add(vf.createIRI(EX, "event/3"), vf.createIRI(EX, "person"), p1);
			}
			String query = "SELECT DISTINCT ?birthday ?person WHERE { ?event <" + EX
					+ "onBirthday> ?birthday ; <" + EX + "person> ?person . }";

			assertThat(explain(repository, query)).contains("distinctStrategy=PARTITIONED_HASH");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void unrelatedNameBeforeDistinctKeyKeepsGlobalHash() {
		SailRepository repository = repository("unsafe", "spoc");
		try {
			ValueFactory vf = repository.getValueFactory();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(vf.createIRI(EX, "name/1"), vf.createIRI(EX, "birthday/1"),
						vf.createIRI(EX, "person/1"));
				connection.add(vf.createIRI(EX, "name/2"), vf.createIRI(EX, "birthday/1"),
						vf.createIRI(EX, "person/1"));
			}
			String query = "SELECT DISTINCT ?person ?birthday WHERE { ?name ?birthday ?person . }";

			assertThat(explain(repository, query)).contains("distinctStrategy=GLOBAL_HASH");
			assertNativeMatchesGeneric(repository, query, 1);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void groupArgumentOrderStreamsGroupAndUsesMonotonicChannel() {
		SailRepository repository = repository("group-argument", "spoc");
		try {
			addNumericGroups(repository);
			String query = "SELECT ?group (COUNT(DISTINCT ?value) AS ?count) WHERE { ?group <" + EX
					+ "value> ?value . } GROUP BY ?group";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=1");
			assertNativeMatchesGeneric(repository, query, 2);
			assertThat(strategy(repository, query)).isEqualTo("orderedDistinctGroups");
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void floatingSumDisablesOrderedDistinctExecutionOnlyAtRuntime() {
		SailRepository repository = repository("floating-aggregate", "spoc,ospc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI value = vf.createIRI(EX, "floating-value");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				for (int group = 1; group <= 2; group++) {
					IRI subject = vf.createIRI(EX, "floating-group/" + group);
					connection.add(subject, value, vf.createLiteral(0.1d));
					connection.add(subject, value, vf.createLiteral(0.2d));
					connection.add(subject, value, vf.createLiteral(0.3d));
				}
			}
			String query = "SELECT ?group (COUNT(DISTINCT ?value) AS ?count) (SUM(?value) AS ?sum) "
					+ "WHERE { ?group <" + EX + "floating-value> ?value } GROUP BY ?group";

			assertThat(explain(repository, query))
					.as("the ordered DISTINCT plan remains a valid speculative candidate")
					.contains("distinctChannels=[MONOTONIC]");
			assertNativeMatchesGeneric(repository, query, 2);
			assertThat(strategy(repository, query))
					.as("floating SUM must restart from the ordinary encounter-order row chain")
					.isEqualTo("singleSlotGroups");
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void argumentGroupOrderUsesMonotonicChannelWithGroupMap() {
		SailRepository repository = repository("argument-group", "ospc");
		try {
			addNumericGroups(repository);
			String query = "SELECT ?group (COUNT(DISTINCT ?value) AS ?count) WHERE { ?group <" + EX
					+ "value> ?value . } GROUP BY ?group";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=0");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void multiKeyGroupOrderMayFollowIndexPermutation() {
		SailRepository repository = repository("group-permutation", "ospc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI subject1 = vf.createIRI(EX, "subject/1");
			IRI subject2 = vf.createIRI(EX, "subject/2");
			IRI object = vf.createIRI(EX, "object/1");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(subject1, vf.createIRI(EX, "predicate/1"), object);
				connection.add(subject1, vf.createIRI(EX, "predicate/2"), object);
				connection.add(subject2, vf.createIRI(EX, "predicate/1"), object);
			}
			String query = "SELECT ?subject ?object (COUNT(DISTINCT ?predicate) AS ?count) WHERE { "
					+ "?subject ?predicate ?object } GROUP BY ?subject ?object";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=2")
					.contains("indexName=ospc");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void partialGroupPrefixFlushesOnlyCurrentPartition() {
		SailRepository repository = repository("partial-group-prefix", "spoc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI group2Predicate = vf.createIRI(EX, "group2");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				for (int first = 1; first <= 2; first++) {
					IRI group1 = vf.createIRI(EX, "group1/" + first);
					connection.add(group1, vf.createIRI(EX, "value/1"), vf.createIRI(EX, "name/1"));
					connection.add(group1, vf.createIRI(EX, "value/1"), vf.createIRI(EX, "name/2"));
					connection.add(group1, vf.createIRI(EX, "value/2"), vf.createIRI(EX, "name/3"));
					connection.add(group1, group2Predicate, vf.createIRI(EX, "group2/a"));
					connection.add(group1, group2Predicate, vf.createIRI(EX, "group2/b"));
				}
			}
			String query = "SELECT ?group1 ?group2 (COUNT(DISTINCT ?value) AS ?count) WHERE { "
					+ "?group1 ?value ?name . FILTER(?value != <" + EX + "group2>) "
					+ "?group1 <" + EX + "group2> ?group2 } GROUP BY ?group1 ?group2";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=1")
					.contains("indexName=spoc");
			assertNativeMatchesGeneric(repository, query, 4);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void groupOnlyOrderDoesNotMakeLaterArgumentMonotonic() {
		SailRepository repository = repository("group-only", "spoc");
		try {
			ValueFactory vf = repository.getValueFactory();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(vf.createIRI(EX, "group/1"), vf.createIRI(EX, "name/1"), vf.createLiteral(10));
				connection.add(vf.createIRI(EX, "group/1"), vf.createIRI(EX, "name/2"), vf.createLiteral(10));
			}
			String query = "SELECT ?group (COUNT(DISTINCT ?value) AS ?count) WHERE { ?group ?name ?value . } "
					+ "GROUP BY ?group";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[HASH]")
					.contains("groupOrderPrefix=0");
			assertNativeMatchesGeneric(repository, query, 1);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void distinctGroupKeyUsesConstantOnceChannel() {
		SailRepository repository = repository("group-key-channel", "ospc");
		try {
			addNumericGroups(repository);
			String query = "SELECT ?group (COUNT(DISTINCT ?group) AS ?count) WHERE { ?group <" + EX
					+ "value> ?value . } GROUP BY ?group";

			assertThat(explain(repository, query)).contains("distinctChannels=[CONSTANT_ONCE]");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void sharedAndIndependentAggregateArgumentsUseOneChannelEach() {
		SailRepository repository = repository("shared", "sopc");
		try {
			ValueFactory vf = repository.getValueFactory();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(vf.createIRI(EX, "group/1"), vf.createIRI(EX, "1"), vf.createLiteral(10));
				connection.add(vf.createIRI(EX, "group/1"), vf.createIRI(EX, "2"), vf.createLiteral(20));
			}
			String query = "SELECT ?group (COUNT(DISTINCT ?first) AS ?count) "
					+ "(SUM(DISTINCT ?first) AS ?sum) (AVG(DISTINCT ?first) AS ?avg) "
					+ "(COUNT(DISTINCT ?second) AS ?secondCount) WHERE { ?group ?second ?first . } GROUP BY ?group";

			assertThat(explain(repository, query))
					.contains("distinctChannelCount=2")
					.contains("distinctChannels=[MONOTONIC, HASH]");
			assertNativeMatchesGeneric(repository, query, 1);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void overlappingUnionBranchesUseOrderedMerge() {
		SailRepository repository = repository("overlapping-union", "ospc,spoc");
		try {
			addPeople(repository);
			String query = "SELECT DISTINCT ?birthday ?person WHERE { "
					+ "{ ?person <" + EX + "birthday> ?birthday } UNION "
					+ "{ ?person <" + EX + "birthday> ?birthday . FILTER(?person = <" + EX + "person/1>) } }";

			assertThat(explain(repository, query))
					.contains("distinctStrategy=ADJACENT")
					.contains("OrderedUnion");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void unboundUnionArgumentKeepsMonotonicAggregate() {
		SailRepository repository = repository("unbound-union", "spoc,ospc");
		try {
			addNumericGroups(repository);
			ValueFactory vf = repository.getValueFactory();
			try (SailRepositoryConnection connection = repository.getConnection()) {
				for (int group = 1; group <= 2; group++) {
					connection.add(vf.createIRI(EX, "group/" + group), vf.createIRI(EX, "kind"),
							vf.createIRI(EX, "Group"));
				}
			}
			String query = "SELECT ?group (COUNT(DISTINCT ?value) AS ?count) WHERE { "
					+ "{ ?group <" + EX + "value> ?value } UNION { ?group <" + EX + "kind> <" + EX
					+ "Group> } } GROUP BY ?group";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=1")
					.contains("OrderedUnion");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void directAliasPreservesCompleteDistinctOrder() {
		SailRepository repository = repository("alias", "ospc");
		try {
			addPeople(repository);
			String query = "SELECT DISTINCT ?birthdayAlias ?person WHERE { ?person <" + EX
					+ "birthday> ?birthday . BIND(?birthday AS ?birthdayAlias) }";

			assertThat(explain(repository, query)).contains("distinctStrategy=ADJACENT");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void chainedDirectAliasesPreserveCompleteDistinctOrder() {
		SailRepository repository = repository("alias-chain", "ospc");
		try {
			addPeople(repository);
			String query = "SELECT DISTINCT ?birthdayAlias ?person WHERE { ?person <" + EX
					+ "birthday> ?birthday . BIND(?birthday AS ?firstAlias) "
					+ "BIND(?firstAlias AS ?birthdayAlias) }";

			assertThat(explain(repository, query)).contains("distinctStrategy=ADJACENT");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void multipleFixedContextsUseMergedExactOrder() {
		SailRepository repository = repository("fixed-contexts", "spoc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI subject1 = vf.createIRI(EX, "subject/1");
			IRI subject2 = vf.createIRI(EX, "subject/2");
			IRI predicate = vf.createIRI(EX, "predicate");
			IRI graph1 = vf.createIRI(EX, "graph/1");
			IRI graph2 = vf.createIRI(EX, "graph/2");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(subject1, predicate, vf.createIRI(EX, "object/1"), graph1);
				connection.add(subject2, predicate, vf.createIRI(EX, "object/2"), graph1);
				connection.add(subject1, predicate, vf.createIRI(EX, "object/3"), graph2);
			}
			String query = "SELECT DISTINCT ?subject FROM <" + EX + "graph/1> FROM <" + EX
					+ "graph/2> WHERE { ?subject <" + EX + "predicate> ?object }";

			assertThat(explain(repository, query)).contains("distinctStrategy=ADJACENT");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void orderedUnionCanBeClosedAfterFirstRow() {
		SailRepository repository = repository("early-close", "ospc,spoc");
		try {
			addPeople(repository);
			String query = "SELECT DISTINCT ?birthday ?person WHERE { "
					+ "{ ?person <" + EX + "birthday> ?birthday } UNION "
					+ "{ ?person <" + EX + "birthday> ?birthday } }";
			assertThat(explain(repository, query)).contains("OrderedUnion");
			try (SailRepositoryConnection connection = repository.getConnection();
					TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
				assertThat(result.hasNext()).isTrue();
				assertThat(result.next()).isNotEmpty();
			}
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void libraryUnionShapeOrdersMemberThenLoan() {
		SailRepository repository = repository("library-shape", "spoc,ospc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI loan = vf.createIRI(EX, "loan/1");
			IRI member = vf.createIRI(EX, "member/1");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(loan, vf.createIRI(EX, "type"), vf.createIRI(EX, "Loan"));
				connection.add(loan, vf.createIRI(EX, "borrowedBy"), member);
				connection.add(member, vf.createIRI(EX, "type"), vf.createIRI(EX, "Member"));
				connection.add(loan, vf.createIRI(EX, "loanedCopy"), vf.createIRI(EX, "copy/1"));
			}
			String query = "SELECT ?member (COUNT(DISTINCT ?loan) AS ?count) WHERE { "
					+ "{ ?loan <" + EX + "type> <" + EX + "Loan> ; <" + EX + "borrowedBy> ?member } UNION "
					+ "{ ?member <" + EX + "type> <" + EX + "Member> } "
					+ "OPTIONAL { ?loan <" + EX + "loanedCopy> ?copy . BIND(?copy AS ?optionalCopy) } "
					+ "} GROUP BY ?member";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=1")
					.contains("OrderedUnion")
					.contains("indexName=ospc");
			assertNativeMatchesGeneric(repository, query, 1);
		} finally {
			repository.shutDown();
		}
	}

	@Test
	void highlyConnectedUnionShapeOrdersNodeThenNeighbor() {
		SailRepository repository = repository("connected-shape", "spoc,ospc");
		try {
			ValueFactory vf = repository.getValueFactory();
			IRI n1 = vf.createIRI(EX, "node/1");
			IRI n2 = vf.createIRI(EX, "node/2");
			IRI n3 = vf.createIRI(EX, "node/3");
			try (SailRepositoryConnection connection = repository.getConnection()) {
				connection.add(n1, vf.createIRI(EX, "type"), vf.createIRI(EX, "Node"));
				connection.add(n1, vf.createIRI(EX, "connectsTo"), n2);
				connection.add(n3, vf.createIRI(EX, "connectsTo"), n1);
				connection.add(n1, vf.createIRI(EX, "weight"), vf.createLiteral(4));
			}
			String query = "SELECT ?node (COUNT(DISTINCT ?neighbor) AS ?count) WHERE { "
					+ "{ ?node <" + EX + "type> <" + EX + "Node> ; <" + EX + "connectsTo> ?neighbor } UNION "
					+ "{ ?neighbor <" + EX + "connectsTo> ?node } "
					+ "OPTIONAL { ?node <" + EX + "weight> ?weight } } GROUP BY ?node";

			assertThat(explain(repository, query))
					.contains("distinctChannels=[MONOTONIC]")
					.contains("groupOrderPrefix=1")
					.contains("OrderedUnion")
					.contains("indexName=spoc")
					.contains("indexName=ospc");
			assertNativeMatchesGeneric(repository, query, 2);
		} finally {
			repository.shutDown();
		}
	}

	private SailRepository repository(String name, String indexes) {
		SailRepository repository = new SailRepository(
				new LmdbStore(new File(dataDir, name), new LmdbStoreConfig(indexes)));
		repository.init();
		return repository;
	}

	private void addPeople(SailRepository repository) {
		ValueFactory vf = repository.getValueFactory();
		IRI birthday = vf.createIRI(EX, "birthday/1");
		IRI p1 = vf.createIRI(EX, "person/1");
		IRI p2 = vf.createIRI(EX, "person/2");
		try (SailRepositoryConnection connection = repository.getConnection()) {
			connection.add(p1, vf.createIRI(EX, "birthday"), birthday);
			connection.add(p2, vf.createIRI(EX, "birthday"), birthday);
			connection.add(p1, vf.createIRI(EX, "name"), vf.createLiteral("alpha"));
			connection.add(p1, vf.createIRI(EX, "name"), vf.createLiteral("omega"));
			connection.add(p2, vf.createIRI(EX, "name"), vf.createLiteral("beta"));
		}
	}

	private void addNumericGroups(SailRepository repository) {
		ValueFactory vf = repository.getValueFactory();
		try (SailRepositoryConnection connection = repository.getConnection()) {
			for (int group = 1; group <= 2; group++) {
				IRI subject = vf.createIRI(EX, "group/" + group);
				connection.add(subject, vf.createIRI(EX, "value"), vf.createLiteral(10));
				connection.add(subject, vf.createIRI(EX, "value"), vf.createLiteral(20));
			}
		}
	}

	private String explain(SailRepository repository, String query) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			return connection.prepareTupleQuery(query).explain(Explanation.Level.Optimized).toString();
		}
	}

	private String strategy(SailRepository repository, String query) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			String strategy = findStrategy(connection.prepareTupleQuery(query)
					.explain(Explanation.Level.Telemetry)
					.toGenericPlanNode());
			assertThat(strategy).as("expected a nativeExecutionPath metric in the explanation").isNotNull();
			return strategy;
		}
	}

	private static String findStrategy(GenericPlanNode node) {
		if (node == null) {
			return null;
		}
		String value = node.getStringMetricActual("nativeExecutionPath");
		if (value != null) {
			return value;
		}
		if (node.getPlans() != null) {
			for (GenericPlanNode child : node.getPlans()) {
				String found = findStrategy(child);
				if (found != null) {
					return found;
				}
			}
		}
		return null;
	}

	private void assertNativeMatchesGeneric(SailRepository repository, String query, int expectedRows) {
		List<String> nativeRows = rows(repository, query);
		String previous = System.getProperty(NATIVE_FLAG);
		List<String> genericRows;
		try {
			System.setProperty(NATIVE_FLAG, "false");
			genericRows = rows(repository, query);
		} finally {
			if (previous == null) {
				System.clearProperty(NATIVE_FLAG);
			} else {
				System.setProperty(NATIVE_FLAG, previous);
			}
		}
		assertThat(nativeRows).hasSize(expectedRows).isEqualTo(genericRows);
	}

	private List<String> rows(SailRepository repository, String query) {
		try (SailRepositoryConnection connection = repository.getConnection()) {
			ArrayList<String> rows = new ArrayList<>();
			for (BindingSet row : QueryResults.asList(connection.prepareTupleQuery(query).evaluate())) {
				ArrayList<String> names = new ArrayList<>(row.getBindingNames());
				names.sort(String::compareTo);
				StringBuilder canonical = new StringBuilder();
				for (String name : names) {
					canonical.append(name).append('=').append(row.getValue(name)).append(';');
				}
				rows.add(canonical.toString());
			}
			rows.sort(String::compareTo);
			return rows;
		}
	}
}
