/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.eclipse.rdf4j.sail.lmdb.sketch.JoinFrequencyEstimate;
import org.junit.jupiter.api.Test;

class LmdbCountMinEvidenceApiTest {

	@Test
	void joinFrequencyEstimateIsPublicForLmdbCosting() {
		JoinFrequencyEstimate estimate = new JoinFrequencyEstimate(100.0d, 25.0d, 0.75d,
				"countmin-sketch-surface", 0.25d);

		assertEquals(100.0d, estimate.upperBoundRows(), 0.0d);
		assertEquals(25.0d, estimate.calibratedRows(), 0.0d);
		assertEquals(0.75d, estimate.confidence(), 0.0d);
		assertEquals("countmin-sketch-surface", estimate.source());
		assertEquals(0.25d, estimate.calibrationFactor(), 0.0d);
	}
}
