/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.junit.jupiter.api.Test;

class PreparedStatementBatchTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();

	@Test
	void copyOfReadsTheIterableAndEachStatementFieldOnce() {
		ReadCounter reads = new ReadCounter();
		List<Statement> statements = new ArrayList<>();
		for (int i = 0; i < 8; i++) {
			Statement statement = VF.createStatement(VF.createIRI("urn:s:" + i), VF.createIRI("urn:p"),
					VF.createLiteral(i), VF.createIRI("urn:c"));
			statements.add(new CountingStatement(statement, reads));
		}
		int[] iteratorRequests = { 0 };
		Iterable<Statement> singlePass = () -> {
			assertEquals(1, ++iteratorRequests[0]);
			return statements.iterator();
		};
		List<Resource> contexts = new ArrayList<>();

		PreparedStatementBatch prepared = PreparedStatementBatch.copyOf(singlePass, statements.size(),
				contexts::add);

		assertEquals(statements.size(), prepared.size());
		assertEquals(statements.size(), reads.subjects);
		assertEquals(statements.size(), reads.predicates);
		assertEquals(statements.size(), reads.objects);
		assertEquals(statements.size(), reads.contexts);
		assertEquals(statements.size(), contexts.size());
	}

	@Test
	void equalButNonidenticalValuesShareLocalIds() {
		Resource firstSubject = VF.createIRI("urn:equal-subject");
		Resource equalSubject = VF.createIRI("urn:equal-subject");
		IRI firstPredicate = VF.createIRI("urn:equal-predicate");
		IRI equalPredicate = VF.createIRI("urn:equal-predicate");
		Value firstObject = VF.createLiteral("equal-object");
		Value equalObject = VF.createLiteral("equal-object");
		assertNotSame(firstSubject, equalSubject);
		assertNotSame(firstPredicate, equalPredicate);
		assertNotSame(firstObject, equalObject);

		PreparedStatementBatch.Builder builder = PreparedStatementBatch.builder();
		builder.add(firstSubject, firstPredicate, firstObject, null);
		builder.add(equalSubject, equalPredicate, equalObject, null);
		PreparedStatementBatch prepared = builder.build();

		assertEquals(3, prepared.values().length);
		assertArrayEquals(new int[] { 0, 1, 2, -1, 0, 1, 2, -1 }, prepared.quads());
	}

	@Test
	void tripleTermDependenciesPrecedeTheTripleLocalId() {
		Resource subject = VF.createIRI("urn:statement-subject");
		IRI predicate = VF.createIRI("urn:statement-predicate");
		Resource tripleSubject = VF.createIRI("urn:triple-subject");
		IRI triplePredicate = VF.createIRI("urn:triple-predicate");
		Value tripleObject = VF.createLiteral("triple-object");
		TripleTerm triple = VF.createTripleTerm(tripleSubject, triplePredicate, tripleObject);
		Statement statement = VF.createStatement(subject, predicate, triple, tripleSubject);

		PreparedStatementBatch prepared = PreparedStatementBatch.copyOf(List.of(statement), 1, ignored -> {
		});

		assertArrayEquals(new int[] { 0, 1, 5, 2 }, prepared.quads());
		assertSame(tripleSubject, prepared.values()[2]);
		assertSame(triplePredicate, prepared.values()[3]);
		assertSame(tripleObject, prepared.values()[4]);
		assertSame(triple, prepared.values()[5]);
		assertEquals(statement, prepared.getFirst());
	}

	@Test
	void predicateValueIndexesAreDistinctAndOrderedByFirstStatementUse() {
		IRI firstPredicate = VF.createIRI("urn:predicate:first");
		IRI secondPredicate = VF.createIRI("urn:predicate:second");
		PreparedStatementBatch prepared = PreparedStatementBatch.copyOf(
				List.of(VF.createStatement(VF.createIRI("urn:subject:1"), firstPredicate, VF.createLiteral("one")),
						VF.createStatement(VF.createIRI("urn:subject:2"), secondPredicate, VF.createLiteral("two")),
						VF.createStatement(VF.createIRI("urn:subject:3"), firstPredicate, VF.createLiteral("three"))),
				3, ignored -> {
				});

		assertArrayEquals(new int[] { 1, 4 }, prepared.predicateValueIndexes());
	}

	@Test
	void transactionBufferCoalescesLaterScalarAdditionsAndDuplicates() {
		Statement first = VF.createStatement(VF.createIRI("urn:s:1"), VF.createIRI("urn:p"),
				VF.createLiteral("one"));
		Statement equalButDistinct = VF.createStatement(VF.createIRI("urn:s:1"), VF.createIRI("urn:p"),
				VF.createLiteral("one"));
		Statement second = VF.createStatement(VF.createIRI("urn:s:2"), VF.createIRI("urn:p"),
				VF.createLiteral("two"));
		PreparedStatementBatch prepared = PreparedStatementBatch.copyOf(List.of(first), 1, ignored -> {
		});

		assertFalse(prepared.add(equalButDistinct));
		assertTrue(prepared.add(second));
		assertEquals(List.of(first, second), prepared);
	}

	private static final class ReadCounter {
		private int subjects;
		private int predicates;
		private int objects;
		private int contexts;
	}

	private static final class CountingStatement implements Statement {

		private static final long serialVersionUID = 1L;

		private final Statement delegate;
		private final ReadCounter reads;

		private CountingStatement(Statement delegate, ReadCounter reads) {
			this.delegate = delegate;
			this.reads = reads;
		}

		@Override
		public Resource getSubject() {
			reads.subjects++;
			return delegate.getSubject();
		}

		@Override
		public IRI getPredicate() {
			reads.predicates++;
			return delegate.getPredicate();
		}

		@Override
		public Value getObject() {
			reads.objects++;
			return delegate.getObject();
		}

		@Override
		public Resource getContext() {
			reads.contexts++;
			return delegate.getContext();
		}

		@Override
		public boolean equals(Object other) {
			return delegate.equals(other instanceof CountingStatement counting ? counting.delegate : other);
		}

		@Override
		public int hashCode() {
			return delegate.hashCode();
		}
	}
}
