/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Claude Code
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.api.parallel.ResourceLock;
import org.junit.jupiter.api.parallel.Resources;

/** The automatic startup value-overlay warm-up must not block Sail/ValueStore initialization. */
@ResourceLock(Resources.SYSTEM_PROPERTIES)
class ValueStoreAsyncOverlayWarmupTest {

	private static final String BUDGET_PROPERTY = "rdf4j.lmdb.valueOverlay.maxBytes";

	private String previousBudget;

	@BeforeEach
	void saveProperty() {
		previousBudget = System.getProperty(BUDGET_PROPERTY);
	}

	@AfterEach
	void restoreProperty() {
		if (previousBudget == null) {
			System.clearProperty(BUDGET_PROPERTY);
		} else {
			System.setProperty(BUDGET_PROPERTY, previousBudget);
		}
	}

	private void seed(File dir) throws Exception {
		var factory = SimpleValueFactory.getInstance();
		var store = new ValueStore(dir, new LmdbStoreConfig());
		try {
			store.startTransaction(true);
			for (int i = 0; i < 32; i++) {
				store.storeValue(factory.createIRI("https://example.org/items/" + i));
			}
			store.commit();
		} finally {
			store.close();
		}
	}

	@Test
	@Timeout(30)
	void automaticWarmupRunsOffTheConstructorThreadAndBecomesReadyAfterAwait(@TempDir File dataDir) throws Exception {
		File dir = new File(dataDir, "values");
		seed(dir);
		System.setProperty(BUDGET_PROPERTY, "33554432");

		CountDownLatch scanStarted = new CountDownLatch(1);
		CountDownLatch releaseScan = new CountDownLatch(1);
		Runnable hook = () -> {
			scanStarted.countDown();
			try {
				releaseScan.await(20, TimeUnit.SECONDS);
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
			}
		};

		var store = new ValueStore(dir, new StoreProperties(dir), new LmdbStoreConfig(), false, hook);
		try {
			assertTrue(scanStarted.await(10, TimeUnit.SECONDS),
					"constructor must return control before the background scan finishes");
			assertTrue(store.isValueOverlayWarmupInProgress());
			assertNull(store.compressedValueOverlayStats());

			releaseScan.countDown();
			assertTrue(store.awaitValueOverlayReady(20, TimeUnit.SECONDS));

			Value expected = SimpleValueFactory.getInstance().createIRI("https://example.org/items/0");
			assertEquals(expected, store.getValue(store.getId(expected)));
		} finally {
			store.close();
		}
	}

	@Test
	@Timeout(30)
	void closeWaitsForAnInFlightAutomaticWarmupBeforeClosingTheNativeEnvironment(@TempDir File dataDir)
			throws Exception {
		File dir = new File(dataDir, "values");
		seed(dir);
		System.setProperty(BUDGET_PROPERTY, "33554432");

		CountDownLatch scanStarted = new CountDownLatch(1);
		CountDownLatch releaseScan = new CountDownLatch(1);
		Runnable hook = () -> {
			scanStarted.countDown();
			try {
				releaseScan.await(20, TimeUnit.SECONDS);
			} catch (InterruptedException e) {
				Thread.currentThread().interrupt();
			}
		};

		var store = new ValueStore(dir, new StoreProperties(dir), new LmdbStoreConfig(), false, hook);
		assertTrue(scanStarted.await(10, TimeUnit.SECONDS));

		Thread closer = new Thread(() -> {
			try {
				store.close();
			} catch (Exception e) {
				throw new RuntimeException(e);
			}
		});
		closer.start();
		releaseScan.countDown();
		closer.join(TimeUnit.SECONDS.toMillis(20));
		assertFalse(closer.isAlive(), "close() must complete once the in-flight warm-up is cancelled");

		var reopened = new ValueStore(dir, new LmdbStoreConfig());
		try {
			Value expected = SimpleValueFactory.getInstance().createIRI("https://example.org/items/0");
			assertEquals(expected, reopened.getValue(reopened.getId(expected)));
		} finally {
			reopened.close();
		}
	}

	@Test
	@Timeout(30)
	void disablingTheBudgetPropertySchedulesNoBackgroundThreadOrExecutor(@TempDir File dataDir) throws Exception {
		File dir = new File(dataDir, "values");
		seed(dir);
		System.clearProperty(BUDGET_PROPERTY);

		var store = new ValueStore(dir, new LmdbStoreConfig());
		try {
			assertFalse(store.isValueOverlayWarmupInProgress());
			boolean anyWarmupThread = Thread.getAllStackTraces()
					.keySet()
					.stream()
					.anyMatch(t -> t.getName().equals("rdf4j-value-overlay-warmup"));
			assertFalse(anyWarmupThread, "no warm-up thread should be created when the feature is disabled");
		} finally {
			store.close();
		}
	}
}
