/*******************************************************************************
 * Copyright (c) 2023 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Co-Pilot
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.Set;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.util.ModelBuilder;
import org.eclipse.rdf4j.model.util.Values;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import org.eclipse.rdf4j.model.vocabulary.RDFS;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreSchema;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbBNode;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbIRI;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbLiteral;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbTripleTerm;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.Assert;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Low-level tests for {@link ValueStore}.
 */
public class ValueStoreTest {

	private static final IRI INLINE_LITERALS = Values.iri(LmdbStoreSchema.NAMESPACE + "inlineLiterals");

	private ValueStore valueStore;
	private File dataDir;

	@BeforeEach
	public void before(@TempDir File dataDir) throws Exception {
		this.dataDir = dataDir;
		this.valueStore = createValueStore();
	}

	private ValueStore createValueStore() throws IOException {
		return createValueStore(new LmdbStoreConfig());
	}

	private ValueStore createValueStore(LmdbStoreConfig config) throws IOException {
		return new ValueStore(new File(dataDir, "values"), config);
	}

	private LmdbStoreConfig hashCacheEnabledConfig() {
		return new LmdbStoreConfig().setValueHashCacheEnabled(true);
	}

	@Test
	public void reopenRecoversCompactNextIdCounter() throws Exception {
		valueStore.startTransaction(true);
		long firstId = valueStore.storeValue(valueStore.createIRI("urn:test:recover:first"));
		valueStore.commit();
		long firstValue = ValueIds.getValue(firstId);

		valueStore.close();
		valueStore = createValueStore();

		valueStore.startTransaction(true);
		long secondId = valueStore.storeValue(valueStore.createIRI("urn:test:recover:second"));
		valueStore.commit();
		long secondValue = ValueIds.getValue(secondId);

		// the reopen scan must recover the max assigned VALUE counter (compound id >> 7), not a
		// partially-shifted compound id: an inflated counter multiplies the consumed id space ~32x
		// per reopen and would exhaust the 57-bit value space after a few dozen reopen cycles
		assertTrue("value counter must continue compactly across reopen: first=" + firstValue + " second="
				+ secondValue, secondValue <= firstValue + 16);
	}

	@Test
	public void storeValuesStoresMultipleValuesWithSingleReadTransaction() throws Exception {
		CountingValueStore countingValueStore = new CountingValueStore(new File(dataDir, "store-values"),
				new LmdbStoreConfig());
		try {
			Value[] values = {
					countingValueStore.createBNode("batch-store-first"),
					countingValueStore.createBNode("batch-store-second"),
					countingValueStore.createBNode("batch-store-third")
			};
			long[] ids = new long[values.length];

			countingValueStore.startTransaction(true);
			countingValueStore.readTransactionCount = 0;
			invokeStoreValues(countingValueStore, values, ids, values.length);
			assertEquals("batch store should use one read transaction", 1,
					countingValueStore.readTransactionCount);
			countingValueStore.commit();

			for (int i = 0; i < values.length; i++) {
				assertNotEquals(LmdbValue.UNKNOWN_ID, ids[i]);
				assertEquals(values[i], countingValueStore.getValue(ids[i]));
			}
		} finally {
			countingValueStore.close();
		}
	}

	@Test
	public void transactionRetainsResolvedValueIdsAfterRegularCacheEviction() throws Exception {
		CountingValueStore countingValueStore = new CountingValueStore(new File(dataDir, "transaction-value-cache"),
				new LmdbStoreConfig());
		try {
			SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
			Value firstValue = valueFactory.createBNode("transaction-repeated-value");

			countingValueStore.startTransaction(true);
			long firstId = countingValueStore.storeValue(firstValue);
			countingValueStore.clearCaches();
			int lookupsBeforeRepeat = countingValueStore.readTransactionCount;

			long repeatedId = countingValueStore
					.storeValue(valueFactory.createBNode("transaction-repeated-value"));

			assertEquals(firstId, repeatedId);
			assertEquals("an active transaction should retain the resolved ID", lookupsBeforeRepeat,
					countingValueStore.readTransactionCount);
			countingValueStore.commit();
		} finally {
			countingValueStore.close();
		}
	}

	@Test
	public void freshPreparedValuesPreserveInlineIdsHashCollisionsAndTripleTerms() throws Exception {
		SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
		Literal inlined = valueFactory.createLiteral(true);
		Literal firstCollision = valueFactory.createLiteral("plumless--fresh-collision-value");
		Literal secondCollision = valueFactory.createLiteral("buckeroo--fresh-collision-value");
		TripleTerm triple = valueFactory.createTripleTerm(valueFactory.createIRI("urn:fresh:subject"),
				valueFactory.createIRI("urn:fresh:predicate"), firstCollision);
		Value[] values = { inlined, firstCollision, secondCollision, triple };

		valueStore.startTransaction(true);
		ValueStore.FreshValueSession session = valueStore.startFreshValueSessionIfEmpty();
		assertNotNull(session);
		ValueStore.PreparedValueBatch prepared = valueStore.prepareFreshValues(session, values);
		long[] ids = prepared.ids();
		assertEquals(ValueIds.createId(ValueIds.T_BOOLEAN, 1L), ids[0]);
		assertNotEquals(ids[1], ids[2]);
		valueStore.persistPreparedValues(prepared);
		valueStore.commit();
		valueStore.commitFreshValueTransaction(session);
		valueStore.publishPreparedValues(prepared);

		assertEquals(firstCollision, valueStore.getValue(ids[1]));
		assertEquals(secondCollision, valueStore.getValue(ids[2]));
		assertEquals(triple, valueStore.getValue(ids[3]));

		valueStore.close();
		valueStore = createValueStore();
		assertEquals(ids[1], valueStore.getId(firstCollision));
		assertEquals(ids[2], valueStore.getId(secondCollision));
		assertEquals(ids[3], valueStore.getId(triple));
		assertEquals(triple, valueStore.getValue(ids[3]));
	}

	@Test
	public void assignedFreshValuesPreserveEqualityInlineIdsHashCollisionsAndTripleTerms() throws Exception {
		SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
		Literal inlined = valueFactory.createLiteral(true);
		Literal firstCollision = valueFactory.createLiteral("plumless--fresh-collision-value");
		Literal equalButNonidentical = valueFactory.createLiteral("plumless--fresh-collision-value");
		Literal secondCollision = valueFactory.createLiteral("buckeroo--fresh-collision-value");
		TripleTerm triple = valueFactory.createTripleTerm(valueFactory.createIRI("urn:fresh:subject"),
				valueFactory.createIRI("urn:fresh:predicate"), firstCollision);
		Value[] values = { inlined, firstCollision, equalButNonidentical, secondCollision, triple };

		valueStore.startTransaction(true);
		ValueStore.FreshValueSession session = valueStore.startFreshValueSessionIfEmpty();
		assertNotNull(session);
		ValueStore.FreshValueAssignment assignment = valueStore.assignFreshValues(session, values);
		long[] ids = assignment.ids();
		assertEquals(ValueIds.createId(ValueIds.T_BOOLEAN, 1L), ids[0]);
		assertEquals(ids[1], ids[2]);
		assertNotEquals(ids[1], ids[3]);
		List<ValueStore.PreparedValueBatch> preparedBatches = new LinkedList<>();
		ValueStore.FreshValueEncoder encoder = valueStore.freshValueEncoder(session, assignment);
		ValueStore.PreparedValueBatch prepared;
		while ((prepared = encoder.next(2)) != null) {
			valueStore.persistPreparedValues(prepared);
			prepared.releasePersistenceData();
			preparedBatches.add(prepared);
		}
		valueStore.commit();
		valueStore.commitFreshValueTransaction(session);
		valueStore.publishPreparedValues(assignment.publication());
		preparedBatches.forEach(valueStore::publishPreparedValues);

		assertEquals(firstCollision, valueStore.getValue(ids[1]));
		assertEquals(secondCollision, valueStore.getValue(ids[3]));
		assertEquals(triple, valueStore.getValue(ids[4]));

		valueStore.close();
		valueStore = createValueStore();
		assertEquals(ids[1], valueStore.getId(firstCollision));
		assertEquals(ids[3], valueStore.getId(secondCollision));
		assertEquals(ids[4], valueStore.getId(triple));
		assertEquals(triple, valueStore.getValue(ids[4]));
	}

	@Test
	public void assignedFreshValuesReserveLowUriIdsForPredicatesAcrossCommits() throws Exception {
		SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
		IRI firstSubject = valueFactory.createIRI("urn:reserved:subject:1");
		IRI firstPredicate = valueFactory.createIRI("urn:reserved:predicate:1");
		IRI firstObject = valueFactory.createIRI("urn:reserved:object:1");
		IRI secondPredicate = valueFactory.createIRI("urn:reserved:predicate:2");
		Value[] firstValues = { firstSubject, firstPredicate, firstObject, secondPredicate };

		valueStore.startTransaction(true);
		ValueStore.FreshValueSession session = valueStore.startFreshValueSessionIfEmpty();
		assertNotNull(session);
		ValueStore.FreshValueAssignment firstAssignment = valueStore.assignFreshValues(session, firstValues,
				new int[] { 1, 3 });
		long[] firstIds = firstAssignment.ids();
		assertEquals(1, ValueIds.getValue(firstIds[1]));
		assertEquals(2, ValueIds.getValue(firstIds[3]));
		assertEquals(65, ValueIds.getValue(firstIds[0]));
		assertEquals(66, ValueIds.getValue(firstIds[2]));
		persistFreshAssignment(session, firstAssignment);

		IRI secondSubject = valueFactory.createIRI("urn:reserved:subject:2");
		IRI thirdPredicate = valueFactory.createIRI("urn:reserved:predicate:3");
		Value[] secondValues = { secondSubject, thirdPredicate };
		valueStore.startTransaction(true);
		ValueStore.FreshValueAssignment secondAssignment = valueStore.assignFreshValues(session, secondValues,
				new int[] { 1 });
		long[] secondIds = secondAssignment.ids();
		assertEquals(3, ValueIds.getValue(secondIds[1]));
		assertEquals(67, ValueIds.getValue(secondIds[0]));
		persistFreshAssignment(session, secondAssignment);

		valueStore.close();
		valueStore = createValueStore();
		assertEquals(firstIds[1], valueStore.getId(firstPredicate));
		assertEquals(firstIds[3], valueStore.getId(secondPredicate));
		assertEquals(secondIds[1], valueStore.getId(thirdPredicate));
		assertEquals(firstIds[0], valueStore.getId(firstSubject));
		assertEquals(secondIds[0], valueStore.getId(secondSubject));
	}

	@Test
	public void assignedFreshPredicateIdsOverflowIntoTheRegularUriSequence() throws Exception {
		SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
		Value[] values = new Value[67];
		int[] predicateValueIndexes = new int[66];
		values[0] = valueFactory.createIRI("urn:reserved:subject");
		for (int i = 0; i < predicateValueIndexes.length; i++) {
			values[i + 1] = valueFactory.createIRI("urn:reserved:predicate:" + i);
			predicateValueIndexes[i] = i + 1;
		}

		valueStore.startTransaction(true);
		ValueStore.FreshValueSession session = valueStore.startFreshValueSessionIfEmpty();
		assertNotNull(session);
		long[] ids = valueStore.assignFreshValues(session, values, predicateValueIndexes).ids();

		assertEquals(1, ValueIds.getValue(ids[1]));
		assertEquals(64, ValueIds.getValue(ids[64]));
		assertEquals(65, ValueIds.getValue(ids[65]));
		assertEquals(66, ValueIds.getValue(ids[66]));
		assertEquals(67, ValueIds.getValue(ids[0]));

		valueStore.rollback();
		valueStore.rollbackFreshValueTransaction(session);
		valueStore.discardFreshValueSession(session);
	}

	private void persistFreshAssignment(ValueStore.FreshValueSession session,
			ValueStore.FreshValueAssignment assignment) throws IOException {
		List<ValueStore.PreparedValueBatch> preparedBatches = new LinkedList<>();
		ValueStore.FreshValueEncoder encoder = valueStore.freshValueEncoder(session, assignment);
		ValueStore.PreparedValueBatch prepared;
		while ((prepared = encoder.next(2)) != null) {
			valueStore.persistPreparedValues(prepared);
			prepared.releasePersistenceData();
			preparedBatches.add(prepared);
		}
		valueStore.commit();
		valueStore.commitFreshValueTransaction(session);
		valueStore.publishPreparedValues(assignment.publication());
		preparedBatches.forEach(valueStore::publishPreparedValues);
	}

	@Test
	public void transactionRetainsNamespaceIdsAfterRegularCacheEviction() throws Exception {
		CountingValueStore countingValueStore = new CountingValueStore(
				new File(dataDir, "transaction-namespace-cache"), new LmdbStoreConfig());
		try {
			SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
			String namespace = "urn:transaction:shared-namespace:";

			countingValueStore.startTransaction(true);
			countingValueStore.storeValue(valueFactory.createIRI(namespace, "first"));
			countingValueStore.clearCaches();
			int lookupsBeforeSecondIri = countingValueStore.readTransactionCount;

			countingValueStore.storeValue(valueFactory.createIRI(namespace, "second"));

			assertEquals("only the new IRI should require a native lookup", lookupsBeforeSecondIri + 1,
					countingValueStore.readTransactionCount);
			countingValueStore.commit();
		} finally {
			countingValueStore.close();
		}
	}

	@Test
	public void transactionValueCacheLimitScalesWithHeap() {
		assertEquals(4 * 1024, ValueStore.calculateTransactionValueCacheLimit(1));
		assertEquals(128 * 1024, ValueStore.calculateTransactionValueCacheLimit(512L * 1024 * 1024));
		assertEquals(512 * 1024, ValueStore.calculateTransactionValueCacheLimit(2L * 1024 * 1024 * 1024));
		assertEquals(1024 * 1024, ValueStore.calculateTransactionValueCacheLimit(Long.MAX_VALUE));
	}

	@Test
	public void testDisableInlineLiteralsUsesStoredIds() throws Exception {
		valueStore.close();

		LmdbStoreConfig config = new LmdbStoreConfig();
		Resource implNode = Values.bnode();
		Model configModel = new ModelBuilder()
				.add(implNode, INLINE_LITERALS, Values.literal(false))
				.build();

		config.parse(configModel, implNode);
		assertFalse("inline literals should be disabled after parsing config",
				config.getInlineLiterals());

		valueStore = createValueStore(config);

		Literal literal = Values.literal("inline");
		valueStore.startTransaction(true);
		long id = valueStore.storeValue(literal);
		valueStore.commit();

		assertFalse("small literals should not be inlined when disabled", ValueIds.isInlined(id));
		assertEquals(literal, valueStore.getValue(id));
	}

	@Test
	public void testGcValues() throws Exception {
		Value[] values = new Value[] {
				RDF.TYPE, RDFS.CLASS,
				Values.iri("some:iri"),
				Values.literal("This is a literal."),
				Values.tripleTerm(Values.iri("other:iri"), RDF.TYPE, RDFS.CLASS)
		};
		long[] ids = new long[values.length];
		valueStore.startTransaction(true);
		for (int i = 0; i < values.length; i++) {
			ids[i] = valueStore.storeValue(values[i]);
		}
		valueStore.commit();

		ValueStoreRevision revBefore = valueStore.getRevision();

		valueStore.startTransaction(true);
		Set<Long> idsToGc = Arrays.stream(ids).boxed().collect(Collectors.toSet());
		Set<Long> nextIds = new HashSet<>();
		valueStore.gcIds(idsToGc, nextIds);
		valueStore.gcIds(nextIds, new HashSet<>());
		valueStore.commit();

		ValueStoreRevision revAfter = valueStore.getRevision();
		assertNotEquals("revisions must change after gc of IDs", revBefore, revAfter);

		for (int i = 0; i < values.length; i++) {
			Assert.assertEquals("Value should be removed:" + values[i], LmdbValue.UNKNOWN_ID,
					valueStore.getId(values[i]));
			// access to value must be ensured as long as revision is not invalidated
			assertNotNull(valueStore.getValue(ids[i]));
		}

		// simulate GC of unused revisions
		valueStore.unusedRevisionIds.add(revBefore.getRevisionId());

		valueStore.forceEvictionOfValues();
		valueStore.startTransaction(true);
		valueStore.commit();

		for (int i = 0; i < values.length; i++) {
			Assert.assertEquals("Value should be removed:" + values[i], LmdbValue.UNKNOWN_ID,
					valueStore.getId(values[i]));
			// value should be removed after invalidating the revision
			assertNull(valueStore.getValue(ids[i]));
		}

		valueStore.startTransaction(true);
		for (Value value : values) {
			// this ID should have been reused
			idsToGc.remove(valueStore.storeValue(value));
		}
		valueStore.commit();

		assertEquals("IDs should have been reused", Collections.emptySet(), idsToGc);
	}

	@Test
	public void testGcValuesAfterRestart() throws Exception {
		Random random = new Random(1337);
		LmdbValue[] values = new LmdbValue[1000];
		valueStore.startTransaction(true);
		for (int i = 0; i < values.length; i++) {
			values[i] = valueStore.createLiteral("This is a random literal:" + random.nextLong());
			valueStore.storeValue(values[i]);
		}
		valueStore.commit();

		valueStore.startTransaction(true);
		Set<Long> ids = new HashSet<>();
		for (int i = 0; i < 30; i++) {
			ids.add(values[i].getInternalID());
		}
		valueStore.gcIds(ids, new HashSet<>());
		valueStore.commit();

		// close and recreate store
		valueStore.close();
		valueStore = createValueStore();

		valueStore.startTransaction(true);
		for (int i = 0; i < 30; i++) {
			LmdbValue value = valueStore.createLiteral("This is a random literal:" + random.nextLong());
			values[i] = value;
			valueStore.storeValue(value);
			// this ID should have been reused
			ids.remove(value.getInternalID());
		}
		valueStore.commit();

		assertEquals("IDs should have been reused", Collections.emptySet(), ids);
	}

	@Test
	public void testGcDatatypes() throws Exception {
		IRI[] types = new IRI[] { XSD.STRING, XSD.INTEGER, XSD.LONG, XSD.DECIMAL };
		LmdbValue[] values = new LmdbValue[types.length];
		valueStore.startTransaction(true);
		for (int i = 0; i < values.length; i++) {
			// use a value that is large enough to not being inlined
			values[i] = valueStore.createLiteral(Long.toString(Long.MAX_VALUE - 1), types[i]);
			valueStore.storeValue(values[i]);
		}
		valueStore.commit();

		valueStore.startTransaction(true);
		List<Long> datatypeIds = new LinkedList<>();
		for (int i = 0; i < types.length; i++) {
			datatypeIds.add(valueStore.storeValue(types[i]));
		}
		valueStore.commit();

		valueStore.startTransaction(true);
		valueStore.gcIds(Collections.singleton(values[0].getInternalID()), new HashSet<>());
		valueStore.gcIds(datatypeIds.subList(1, datatypeIds.size() - 1), new HashSet<>());
		valueStore.commit();

		// close and recreate store
		valueStore.close();
		valueStore = createValueStore();

		// the first value is directly GCed
		assertNull(valueStore.getValue(values[0].getInternalID()));
		// the first datatype is not directly GCed and must not be
		// removed from the store if the related literal is removed
		assertNotNull(valueStore.getValue(datatypeIds.removeFirst()));

		for (int i = 1; i < values.length; i++) {
			Value v = valueStore.getValue(values[i].getInternalID());
			IRI datatype = ((Literal) v).getDatatype();
			assertEquals(types[i], datatype);
			assertNotNull(valueStore.getValue(((LmdbValue) datatype).getInternalID()));
			datatypeIds.remove(((LmdbValue) datatype).getInternalID());
		}

		assertTrue("Datatype IDs should not have been deleted", datatypeIds.isEmpty());
	}

	@Test
	public void testGcURIs() throws Exception {
		for (boolean storeAndGcUri : List.of(false, true)) {
			valueStore.startTransaction(true);
			// use a value that is large enough to not being inlined
			LmdbLiteral literal = valueStore.createLiteral("123".repeat(5), XSD.STRING);
			valueStore.storeValue(literal);
			if (storeAndGcUri) {
				valueStore.storeValue(XSD.STRING);
			}
			valueStore.commit();

			long typeId = valueStore.getId(XSD.STRING);
			assertTrue(typeId != 0);

			Set<Long> nextGcIds = new HashSet<>();
			valueStore.startTransaction(true);
			valueStore.gcIds(Collections.singleton(literal.getInternalID()), nextGcIds);
			assertEquals(1, nextGcIds.size());
			assertTrue(nextGcIds.contains(typeId));

			if (storeAndGcUri) {
				valueStore.gcIds(nextGcIds, new HashSet<>());
			}

			valueStore.commit();

			// close and recreate store
			valueStore.close();
			valueStore = createValueStore();

			assertNull(valueStore.getValue(literal.getInternalID()));
			if (!storeAndGcUri) {
				assertNotNull(valueStore.getValue(typeId));
			} else {
				assertNull(valueStore.getValue(typeId));
			}
		}
	}

	@Test
	public void testDisableGc() throws Exception {
		final Random random = new Random(1337);
		final LmdbValue[] values = new LmdbValue[1000];

		ValueStore disabledGcValueStore = new ValueStore(
				new File(dataDir, "values"), new LmdbStoreConfig().setValueEvictionInterval(-1));
		try {
			disabledGcValueStore.startTransaction(true);
			for (int i = 0; i < values.length; i++) {
				values[i] = disabledGcValueStore.createLiteral("This is a random literal:" + random.nextLong());
				disabledGcValueStore.storeValue(values[i]);
			}
			disabledGcValueStore.commit();

			final ValueStoreRevision revBefore = disabledGcValueStore.getRevision();

			disabledGcValueStore.startTransaction(true);
			Set<Long> ids = new HashSet<>();
			for (int i = 0; i < 30; i++) {
				ids.add(values[i].getInternalID());
			}
			disabledGcValueStore.gcIds(ids, new HashSet<>());
			disabledGcValueStore.commit();

			final ValueStoreRevision revAfter = disabledGcValueStore.getRevision();

			assertEquals("revisions must NOT change since GC is disabled", revBefore, revAfter);

			Arrays.fill(values, null);
			disabledGcValueStore.unusedRevisionIds.add(revBefore.getRevisionId());

			disabledGcValueStore.forceEvictionOfValues();
			disabledGcValueStore.startTransaction(true);
			disabledGcValueStore.commit();

			disabledGcValueStore.startTransaction(true);
			for (int i = 0; i < 30; i++) {
				LmdbValue value = disabledGcValueStore.createLiteral("This is a random literal:" + random.nextLong());
				values[i] = value;
				disabledGcValueStore.storeValue(value);
				ids.remove(value.getInternalID());
			}
			disabledGcValueStore.commit();

			assertNotEquals("IDs should NOT have been reused since GC is disabled", Collections.emptySet(), ids);
		} finally {
			disabledGcValueStore.close();
			valueStore = createValueStore();
		}
	}

	@Test
	public void testLazyIriHashCodeDoesNotInitializeAfterRestart() throws Exception {
		IRI iri = Values.iri("urn:hash:iri");
		int expectedHash = iri.hashCode();
		long id = storeValueAndReopen(iri, hashCacheEnabledConfig());

		LmdbIRI lazyValue = (LmdbIRI) valueStore.getLazyValue(id);
		assertFalse(isInitialized(lazyValue));
		assertEquals(expectedHash, lazyValue.hashCode());
		assertFalse("hashCode should not initialize lazy IRIs after restart", isInitialized(lazyValue));
	}

	@Test
	public void testLazyLiteralHashCodeDoesNotInitializeAfterRestart() throws Exception {
		Literal literal = Values.literal("literal-hash");
		int expectedHash = literal.hashCode();
		long id = storeValueAndReopen(literal, hashCacheEnabledConfig());

		LmdbLiteral lazyValue = (LmdbLiteral) valueStore.getLazyValue(id);
		assertFalse(isInitialized(lazyValue));
		assertEquals(expectedHash, lazyValue.hashCode());
		assertFalse("hashCode should not initialize lazy literals after restart", isInitialized(lazyValue));
	}

	@Test
	public void testDirectedLanguageLiteralRoundTripsAfterRestart() throws Exception {
		Literal literal = SimpleValueFactory.getInstance()
				.createLiteral("directed literal ".repeat(20), "en", Literal.BaseDirection.LTR);
		long id = storeValueAndReopen(literal, new LmdbStoreConfig());

		Literal resolved = (Literal) valueStore.getValue(id);

		assertEquals(literal, resolved);
		assertEquals(Literal.BaseDirection.LTR, resolved.getBaseDirection());
		assertEquals(RDF.DIRLANGSTRING, resolved.getDatatype());
	}

	@Test
	public void testDirectedLanguageLiteralLazyResolvePreservesBaseDirection() throws Exception {
		Literal literal = SimpleValueFactory.getInstance()
				.createLiteral("directed cached literal ".repeat(20), "en", Literal.BaseDirection.RTL);
		long id = storeValueAndReopen(literal, new LmdbStoreConfig());

		Literal lazy = (Literal) valueStore.getLazyValue(id);
		assertFalse(isInitialized(lazy));

		Literal cached = (Literal) valueStore.getValue(id);
		assertEquals(Literal.BaseDirection.RTL, cached.getBaseDirection());

		assertEquals(Literal.BaseDirection.RTL, lazy.getBaseDirection());
		assertEquals(literal, lazy);
	}

	@Test
	public void testLazyBNodeHashCodeDoesNotInitializeAfterRestart() throws Exception {
		valueStore.close();
		valueStore = createValueStore(hashCacheEnabledConfig());

		LmdbBNode bNode = valueStore.createBNode("hash-bnode");
		int expectedHash = bNode.hashCode();
		long id = storeValueAndReopen(bNode, hashCacheEnabledConfig());

		LmdbBNode lazyValue = (LmdbBNode) valueStore.getLazyValue(id);
		assertFalse(isInitialized(lazyValue));
		assertEquals(expectedHash, lazyValue.hashCode());
		assertFalse("hashCode should not initialize lazy bnodes after restart", isInitialized(lazyValue));
	}

	@Test
	public void testRecycledIdsClearCachedHash() throws Exception {
		valueStore.close();
		valueStore = createValueStore(hashCacheEnabledConfig());

		LmdbBNode first = valueStore.createBNode("hash-first");
		int firstHash = first.hashCode();
		long firstId;
		valueStore.startTransaction(true);
		firstId = valueStore.storeValue(first);
		valueStore.commit();
		valueStore.getLazyValue(firstId).hashCode();

		valueStore.startTransaction(true);
		valueStore.gcIds(Collections.singleton(firstId), new HashSet<>());
		valueStore.commit();

		reopenValueStore(hashCacheEnabledConfig());

		LmdbBNode second = valueStore.createBNode("hash-second");
		int secondHash = second.hashCode();
		long secondId;
		valueStore.startTransaction(true);
		secondId = valueStore.storeValue(second);
		valueStore.commit();

		assertEquals("ID should have been recycled", firstId, secondId);
		assertNotEquals("test values must not share the same hash", firstHash, secondHash);

		reopenValueStore(hashCacheEnabledConfig());

		LmdbBNode lazyValue = (LmdbBNode) valueStore.getLazyValue(secondId);
		assertFalse(isInitialized(lazyValue));
		assertEquals(secondHash, lazyValue.hashCode());
		assertNotEquals("recycled IDs must not keep the previous hash", firstHash, lazyValue.hashCode());
		assertFalse("hashCode should not initialize recycled lazy bnodes after restart", isInitialized(lazyValue));
	}

	@Test
	public void testStaleBNodeHashCodeIgnoresReusedIdAfterClear() throws Exception {
		valueStore.close();
		valueStore = createValueStore(hashCacheEnabledConfig());

		LmdbBNode first = valueStore.createBNode("hash-first");
		int firstHash = first.hashCode();
		long firstId;
		valueStore.startTransaction(true);
		firstId = valueStore.storeValue(first);
		valueStore.commit();

		ValueStoreRevision firstRevision = valueStore.getRevision();

		valueStore.startTransaction(true);
		valueStore.gcIds(Collections.singleton(firstId), new HashSet<>());
		valueStore.commit();

		valueStore.unusedRevisionIds.add(firstRevision.getRevisionId());
		valueStore.forceEvictionOfValues();
		valueStore.startTransaction(true);
		valueStore.commit();

		LmdbBNode second = valueStore.createBNode("hash-second");
		int secondHash = second.hashCode();
		long secondId;
		valueStore.startTransaction(true);
		secondId = valueStore.storeValue(second);
		valueStore.commit();

		assertEquals("GC should make the old ID reusable", firstId, secondId);
		assertNotEquals("test values must not share the same hash", firstHash, secondHash);
		assertEquals("stale values must keep their original hash after a revision change", firstHash, first.hashCode());
	}

	@Test
	public void testCreateTripleTermReturnsLmdbTripleTerm() {
		TripleTerm tripleTerm = valueStore.createTripleTerm(RDF.TYPE, RDFS.SUBCLASSOF, RDFS.CLASS);

		assertEquals("org.eclipse.rdf4j.sail.lmdb.model.LmdbTripleTerm", tripleTerm.getClass().getName());
	}

	@Test
	public void testGetLmdbValueWrapsTripleTerm() {
		TripleTerm tripleTerm = SimpleValueFactory.getInstance()
				.createTripleTerm(RDF.TYPE, RDFS.SUBCLASSOF, RDFS.CLASS);

		LmdbValue lmdbValue = valueStore.getLmdbValue(tripleTerm);

		assertEquals("org.eclipse.rdf4j.sail.lmdb.model.LmdbTripleTerm", lmdbValue.getClass().getName());
		assertEquals(tripleTerm, lmdbValue);
	}

	@Test
	public void testStoreAndGetTripleTerm() throws Exception {
		TripleTerm tripleTerm = valueStore.createTripleTerm(RDF.TYPE, RDFS.SUBCLASSOF, RDFS.CLASS);

		valueStore.startTransaction(true);
		long id = valueStore.storeValue(tripleTerm);
		valueStore.commit();
		reopenValueStore(new LmdbStoreConfig());

		assertEquals("org.eclipse.rdf4j.sail.lmdb.model.LmdbTripleTerm", valueStore.getValue(id).getClass().getName());
		assertEquals(tripleTerm, valueStore.getValue(id));
	}

	@Test
	public void testLazyTripleTermDoesNotInitializeAfterRestart() throws Exception {
		TripleTerm tripleTerm = valueStore.createTripleTerm(RDF.TYPE, RDFS.SUBCLASSOF, RDFS.CLASS);
		long id = storeValueAndReopen(tripleTerm, new LmdbStoreConfig());

		LmdbTripleTerm lazyValue = (LmdbTripleTerm) valueStore.getLazyValue(id);
		assertFalse(isInitialized(lazyValue));
		assertEquals(RDF.TYPE, lazyValue.getSubject());
		assertTrue(isInitialized(lazyValue));
		assertEquals(tripleTerm, lazyValue);
	}

	private long storeValueAndReopen(Value value, LmdbStoreConfig config) throws Exception {
		valueStore.close();
		valueStore = createValueStore(config);

		long id;
		valueStore.startTransaction(true);
		id = valueStore.storeValue(value);
		valueStore.commit();
		reopenValueStore(config);
		return id;
	}

	private void reopenValueStore(LmdbStoreConfig config) throws Exception {
		valueStore.close();
		valueStore = createValueStore(config);
	}

	private boolean isInitialized(Object value) throws Exception {
		Field initializedField = value.getClass().getDeclaredField("initialized");
		initializedField.setAccessible(true);
		return initializedField.getBoolean(value);
	}

	private void invokeStoreValues(ValueStore store, Value[] values, long[] ids, int count) throws Exception {
		Method method;
		try {
			method = ValueStore.class.getDeclaredMethod("storeValues", Value[].class, long[].class, int.class);
		} catch (NoSuchMethodException e) {
			Assert.fail("Expected ValueStore.storeValues(Value[], long[], int) batch API");
			return;
		}
		method.setAccessible(true);
		method.invoke(store, new Object[] { values, ids, count });
	}

	private static final class CountingValueStore extends ValueStore {

		private int readTransactionCount;

		private CountingValueStore(File dir, LmdbStoreConfig config) throws IOException {
			super(dir, config);
		}

		@Override
		<T> T readTransaction(long env, LmdbUtil.Transaction<T> transaction) throws IOException {
			readTransactionCount++;
			return super.readTransaction(env, transaction);
		}
	}

	@AfterEach
	public void after() throws Exception {
		try {
			valueStore.close();
		} finally {
			LmdbTestUtil.deleteDir(dataDir);
		}
	}
}
