/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Field;
import java.util.concurrent.Semaphore;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.TripleTerm;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbIRI;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbLiteral;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbTripleTerm;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Tests dataset-scoped dictionary materialization without involving a complete Sail query.
 */
public class ValueStoreMaterializerTest {

	private static final SimpleValueFactory FACTORY = SimpleValueFactory.getInstance();

	private ValueStore valueStore;

	@BeforeEach
	void setUp(@TempDir File dataDir) throws IOException {
		LmdbStoreConfig config = new LmdbStoreConfig()
				.setValueCacheSize(2)
				.setNamespaceCacheSize(2)
				.setValueIDCacheSize(2)
				.setValueEvictionInterval(-1);
		valueStore = new ValueStore(new File(dataDir, "values"), config);
	}

	@AfterEach
	void tearDown() throws IOException {
		if (valueStore != null) {
			valueStore.close();
		}
	}

	@Test
	void firstReadAcquiresAndLaterReadsReuseOneRetainedReader() throws Exception {
		IRI first = FACTORY.createIRI("urn:materializer:first:", "value");
		IRI second = FACTORY.createIRI("urn:materializer:second:", "value");
		long firstId = store(first);
		long secondId = store(second);
		valueStore.clearCaches();

		int initialPermits = availableReaderPermits();
		try (ValueStoreMaterializer materializer = new ValueStoreMaterializer(valueStore)) {
			assertEquals(initialPermits, availableReaderPermits(), "materializer construction must be lazy");

			LmdbValue firstLazy = valueStore.getLazyValue(firstId, materializer);
			assertEquals(first, firstLazy);
			assertEquals(initialPermits - 1, availableReaderPermits());

			LmdbValue secondLazy = valueStore.getLazyValue(secondId, materializer);
			assertEquals(second, secondLazy);
			assertEquals(initialPermits - 1, availableReaderPermits(),
					"uncached values in one dataset must share the retained reader");
		}
		assertEquals(initialPermits, availableReaderPermits(),
				"closing the dataset materializer must release its lease");
	}

	@Test
	void inlineAndCachedValuesDoNotAcquireReader() throws Exception {
		long inlineId = store(FACTORY.createLiteral("inline"));
		long storedId = store(FACTORY.createIRI("urn:materializer:cached:", "value"));
		valueStore.clearCaches();
		LmdbValue cached = valueStore.getValue(storedId);
		assertTrue(cached != null);

		int initialPermits = availableReaderPermits();
		try (ValueStoreMaterializer materializer = new ValueStoreMaterializer(valueStore)) {
			LmdbValue inline = valueStore.getLazyValue(inlineId, materializer);
			assertEquals("inline", inline.stringValue());
			assertEquals(initialPermits, availableReaderPermits(), "inline values must not use the retained reader");

			LmdbValue lazyCached = valueStore.getLazyValue(storedId, materializer);
			assertSame(cached, lazyCached);
			assertEquals(initialPermits, availableReaderPermits(), "cache hits must not use the retained reader");
		}
	}

	@Test
	void datatypeAndNestedTripleDecodeUseOneMaterializerTransaction() throws Exception {
		IRI datatype = FACTORY.createIRI("urn:materializer:datatype:", "custom");
		Literal literal = FACTORY.createLiteral("a non-inline literal value", datatype);
		TripleTerm nested = FACTORY.createTripleTerm(
				FACTORY.createIRI("urn:materializer:nested:", "subject"),
				FACTORY.createIRI("urn:materializer:nested:", "predicate"), literal);
		TripleTerm outer = FACTORY.createTripleTerm(
				FACTORY.createIRI("urn:materializer:outer:", "subject"),
				FACTORY.createIRI("urn:materializer:outer:", "predicate"), nested);
		long outerId = store(outer);
		valueStore.clearCaches();

		int initialPermits = availableReaderPermits();
		LmdbTripleTerm outerLazy;
		TripleTerm nestedLazy;
		try (ValueStoreMaterializer materializer = new ValueStoreMaterializer(valueStore)) {
			outerLazy = (LmdbTripleTerm) valueStore.getLazyValue(outerId, materializer);
			// Keep the nested children unresolved until after the dataset materializer closes. This exercises the
			// original
			// lazy revision retained by each child rather than resolving through the scoped transaction recursively.
			nestedLazy = (TripleTerm) outerLazy.getObject();
			assertEquals(initialPermits - 1, availableReaderPermits());
		}

		assertEquals(initialPermits, availableReaderPermits());
		assertEquals(nested.getSubject(), nestedLazy.getSubject(),
				"nested subject must resolve after the dataset materializer closes");
		assertEquals(nested.getPredicate(), nestedLazy.getPredicate(),
				"nested predicate must resolve after the dataset materializer closes");
		Literal resolvedLiteral = (Literal) nestedLazy.getObject();
		assertEquals(literal, resolvedLiteral, "nested object must resolve after the dataset materializer closes");
		assertEquals(datatype, resolvedLiteral.getDatatype(), "nested datatype must remain detached and intact");
	}

	@Test
	void staleMaterializerCannotReadReopenedValueStore() throws Exception {
		long id = store(FACTORY.createIRI("urn:materializer:stale:", "old"));
		valueStore.clearCaches();
		ValueStoreMaterializer materializer = new ValueStoreMaterializer(valueStore);
		try {
			LmdbIRI lazy = (LmdbIRI) valueStore.getLazyValue(id, materializer);
			valueStore.clear();
			assertNull(lazy.stringValue(), "an old materializer must not resolve an ID in the reopened environment");
			assertFalse(materializer.isCurrentManager());

			TripleTerm reopenedTriple = FACTORY.createTripleTerm(
					FACTORY.createIRI("urn:materializer:reopened:", "subject"),
					FACTORY.createIRI("urn:materializer:reopened:", "predicate"),
					FACTORY.createLiteral("object"));
			long reopenedTripleId = store(reopenedTriple);
			assertEquals(reopenedTriple, valueStore.getValue(reopenedTripleId),
					"clear must rebuild triple indexes for the reopened environment");
		} finally {
			materializer.close();
		}
	}

	@Test
	void serializedMaterializedValueHasNoNativeResolver() throws Exception {
		IRI expected = FACTORY.createIRI("urn:materializer:serialized:", "value");
		long id = store(expected);
		valueStore.clearCaches();

		LmdbIRI lazy;
		byte[] serialized;
		try (ValueStoreMaterializer materializer = new ValueStoreMaterializer(valueStore)) {
			lazy = (LmdbIRI) valueStore.getLazyValue(id, materializer);
			ByteArrayOutputStream bytes = new ByteArrayOutputStream();
			try (ObjectOutputStream output = new ObjectOutputStream(bytes)) {
				output.writeObject(lazy);
			}
			serialized = bytes.toByteArray();
		}

		try (ObjectInputStream input = new ObjectInputStream(new ByteArrayInputStream(serialized))) {
			LmdbIRI restored = (LmdbIRI) input.readObject();
			assertEquals(expected, restored);
			assertNull(restored.getValueStoreRevision().getValueStore(),
					"serialized values must not retain the store or materializer");
		}
	}

	private long store(Value value) throws IOException {
		valueStore.startTransaction(true);
		try {
			long id = valueStore.storeValue(value);
			valueStore.commit();
			return id;
		} catch (IOException | RuntimeException e) {
			valueStore.rollback();
			throw e;
		}
	}

	private int availableReaderPermits() throws ReflectiveOperationException {
		Field readerSlots = TxnManager.class.getDeclaredField("readerSlots");
		readerSlots.setAccessible(true);
		return ((Semaphore) readerSlots.get(valueStore.getTxnManager())).availablePermits();
	}
}
