/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.base.sketchoptimizer;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.apache.datasketches.tuple.arrayofdoubles.ArrayOfDoublesCompactSketch;
import org.apache.datasketches.tuple.arrayofdoubles.ArrayOfDoublesSketchIterator;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Compare;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.JoinOrderPlanner;
import org.junit.jupiter.api.Test;

class MessagePassingJoinPlannerTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final long SEED = 9_001L;
	private static final int NOMINAL_ENTRIES = 4_096;

	@Test
	void canonicalMessageIsInvariantAcrossEquivalentSubsetConstructionOrder() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("s0", p1, "x0"),
				triple("s1", p1, "x1"),
				triple("x0", p2, "y0"),
				triple("x1", p2, "y0"),
				triple("y0", p3, "z0")));

		StatementPattern a = pattern("s", p1, "x");
		StatementPattern b = pattern("x", p2, "y");
		StatementPattern c = pattern("y", p3, "z");

		MessagePassingJoinPlanner firstPlanner = new MessagePassingJoinPlanner(
				adapt(synopsis, List.of(a, b, c)).orElseThrow());
		MessagePassingJoinPlanner secondPlanner = new MessagePassingJoinPlanner(
				adapt(synopsis, List.of(b, a, c)).orElseThrow());

		MessagePassingJoinPlanner.Message first = firstPlanner.canonicalMessage(0b11L, "x");
		MessagePassingJoinPlanner.Message second = secondPlanner.canonicalMessage(0b11L, "x");

		assertEquals("x", first.variable());
		assertEquals(first.variable(), second.variable());
		assertEquals(sketchValues(first.sketch()), sketchValues(second.sketch()),
				"Canonical messages should not depend on factor construction order");
	}

	@Test
	void dynamicProgrammingChoosesSelectiveChainEndFirst() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		List<TripleData> statements = new ArrayList<>();
		for (int i = 0; i < 100; i++) {
			statements.add(triple("s" + i, p1, "x" + i));
		}
		for (int i = 0; i < 30; i++) {
			statements.add(triple("x" + i, p2, "y" + i));
		}
		statements.add(triple("y0", p3, "z0"));

		StatementPattern a = pattern("s", p1, "x");
		StatementPattern b = pattern("x", p2, "y");
		StatementPattern c = pattern("y", p3, "z");

		Optional<JoinOrderPlanner.JoinOrderPlan> plan = new MessagePassingJoinPlanner(
				adapt(synopsis(statements), List.of(a, b, c)).orElseThrow())
				.plan(JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING);

		assertTrue(plan.isPresent(), "Expected DP planner to find a selective chain order");
		assertEquals(List.of(c, b, a), plan.get().getOrderedArgs(),
				"DP should start from the narrow chain end and expand inward");
	}

	@Test
	void dynamicProgrammingChoosesSelectiveStarArmFirst() {
		IRI pA = iri("pA");
		IRI pB = iri("pB");
		IRI pC = iri("pC");
		List<TripleData> statements = new ArrayList<>();
		for (int i = 0; i < 100; i++) {
			statements.add(triple("s" + i, pA, "a" + i));
		}
		for (int i = 0; i < 8; i++) {
			statements.add(triple("s0", pA, "a-extra-" + i));
		}
		for (int i = 0; i < 12; i++) {
			statements.add(triple("s" + i, pB, "b" + i));
		}
		statements.add(triple("s0", pC, "c0"));

		StatementPattern a = pattern("s", pA, "a");
		StatementPattern b = pattern("s", pB, "b");
		StatementPattern c = pattern("s", pC, "c");

		Optional<JoinOrderPlanner.JoinOrderPlan> plan = new MessagePassingJoinPlanner(
				adapt(synopsis(statements), List.of(a, b, c)).orElseThrow())
				.plan(JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING);

		assertTrue(plan.isPresent(), "Expected DP planner to find a selective star order");
		assertEquals(List.of(c, b, a), plan.get().getOrderedArgs(),
				"DP should start from the narrowest star arm before the broader arms");
	}

	@Test
	void dynamicProgrammingChoosesSelectiveUnaryChainTailFirstWithContext() {
		IRI hasArm = iri("hasArm");
		IRI hasResult = iri("hasResult");
		IRI biomarker = iri("biomarker");
		IRI context = iri("ctx");
		IRI targetMarker = iri("targetMarker");
		List<TripleData> statements = new ArrayList<>();
		for (int trialIndex = 0; trialIndex < 8; trialIndex++) {
			for (int armIndex = 0; armIndex < 50; armIndex++) {
				IRI trial = iri("trial-" + trialIndex);
				IRI arm = iri("arm-" + trialIndex + '-' + armIndex);
				IRI result = iri("result-" + trialIndex + '-' + armIndex);
				IRI marker = trialIndex == 0 && armIndex == 0 ? targetMarker
						: iri("marker-" + trialIndex + '-' + armIndex);
				statements.add(new TripleData(trial, hasArm, arm, context));
				statements.add(new TripleData(arm, hasResult, result, context));
				statements.add(new TripleData(result, biomarker, marker, context));
			}
		}

		StatementPattern trialArmPattern = new StatementPattern(
				Var.of("trial"),
				Var.of("hasArmPredicate", hasArm),
				Var.of("arm"),
				Var.of("context", context));
		StatementPattern armResultPattern = new StatementPattern(
				Var.of("arm"),
				Var.of("hasResultPredicate", hasResult),
				Var.of("result"),
				Var.of("context", context));
		StatementPattern biomarkerPattern = new StatementPattern(
				Var.of("result"),
				Var.of("biomarkerPredicate", biomarker),
				Var.of("targetMarker", targetMarker),
				Var.of("context", context));

		Optional<JoinOrderPlanner.JoinOrderPlan> plan = new MessagePassingJoinPlanner(
				adapt(synopsis(statements), List.of(trialArmPattern, armResultPattern, biomarkerPattern)).orElseThrow())
				.plan(JoinOrderPlanner.Algorithm.DYNAMIC_PROGRAMMING);

		assertTrue(plan.isPresent(), "Expected DP planner to keep the supported unary-tail chain");
		assertEquals(List.of(biomarkerPattern, armResultPattern, trialArmPattern), plan.get().getOrderedArgs(),
				"DP should seed from the selective unary tail before expanding toward the broad root");
	}

	@Test
	void adaptRejectsCycleFactors() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("x0", p1, "y0"),
				triple("y0", p2, "z0"),
				triple("z0", p3, "x0")));

		Optional<PatternSynopsisAdapter.SupportedQuery> supported = adapt(synopsis,
				List.of(pattern("x", p1, "y"), pattern("y", p2, "z"), pattern("z", p3, "x")));

		assertTrue(supported.isEmpty(), "Cycle-shaped factors must reject the robust sketch plan");
	}

	@Test
	void adaptRejectsMultiSharedVariableAttachment() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("x0", p1, "y0"),
				triple("x0", p2, "y0")));

		Optional<PatternSynopsisAdapter.SupportedQuery> supported = adapt(synopsis,
				List.of(pattern("x", p1, "y"), pattern("x", p2, "y")));

		assertTrue(supported.isEmpty(),
				"Factors sharing two join variables must reject the robust sketch plan");
	}

	@Test
	void adaptRejectsLeftJoinSegment() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("s0", p1, "x0"),
				triple("x0", p2, "y0"),
				triple("y0", p3, "z0")));

		LeftJoin leftJoin = new LeftJoin(pattern("s", p1, "x"), pattern("x", p2, "y"));
		Optional<PatternSynopsisAdapter.SupportedQuery> supported = adapt(synopsis,
				List.of(leftJoin, pattern("y", p3, "z")));

		assertTrue(supported.isEmpty(), "LeftJoin segments must reject the robust sketch plan");
	}

	@Test
	void adaptRejectsUnsupportedFilterWrapper() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("s0", p1, "x0"),
				triple("x0", p2, "y0"),
				triple("y0", p3, "z0")));

		StatementPattern a = pattern("s", p1, "x");
		StatementPattern b = pattern("x", p2, "y");
		Filter wrappedJoin = new Filter(new Join(a, b),
				new Compare(Var.of("y"), new ValueConstant(iri("y0")), Compare.CompareOp.EQ));

		Optional<PatternSynopsisAdapter.SupportedQuery> supported = adapt(synopsis,
				List.of(wrappedJoin, pattern("y", p3, "z")));

		assertTrue(supported.isEmpty(), "Unsupported wrappers must reject the robust sketch plan");
	}

	@Test
	void adaptRejectsUnsupportedUnionWrapper() {
		IRI p1 = iri("p1");
		IRI p2 = iri("p2");
		IRI p3 = iri("p3");
		StoreSynopsis synopsis = synopsis(List.of(
				triple("s0", p1, "x0"),
				triple("x0", p2, "y0"),
				triple("x0", p3, "z0")));

		Union union = new Union(pattern("s", p1, "x"), pattern("x", p2, "y"));
		Optional<PatternSynopsisAdapter.SupportedQuery> supported = adapt(synopsis,
				List.of(union, pattern("x", p3, "z")));

		assertTrue(supported.isEmpty(), "Unsupported wrappers must reject the robust sketch plan");
	}

	private static Optional<PatternSynopsisAdapter.SupportedQuery> adapt(StoreSynopsis synopsis, List<TupleExpr> args) {
		return new PatternSynopsisAdapter(synopsis, (filter, pattern) -> 1.0d).adapt(args, Set.of());
	}

	private static StoreSynopsis synopsis(List<TripleData> statements) {
		StoreSynopsis.Builder builder = new StoreSynopsis.Builder(NOMINAL_ENTRIES, SEED);
		for (TripleData statement : statements) {
			builder.addStatement(fingerprint(statement.subject().stringValue()),
					fingerprint(statement.predicate().stringValue()),
					fingerprint(statement.object().stringValue()),
					fingerprint(statement.context().stringValue()));
		}
		return builder.build();
	}

	private static Map<Long, Double> sketchValues(ArrayOfDoublesCompactSketch sketch) {
		Map<Long, Double> values = new LinkedHashMap<>();
		ArrayOfDoublesSketchIterator iterator = sketch.iterator();
		while (iterator.next()) {
			values.put(iterator.getKey(), iterator.getValues()[0]);
		}
		return values;
	}

	private static StatementPattern pattern(String subjectVar, IRI predicate, String objectVar) {
		return new StatementPattern(Var.of(subjectVar), Var.of(predicate.getLocalName(), predicate), Var.of(objectVar));
	}

	private static TripleData triple(String subject, IRI predicate, String object) {
		return new TripleData(iri(subject), predicate, iri(object));
	}

	private static IRI iri(String localName) {
		return VF.createIRI("urn:" + localName);
	}

	private static long fingerprint(String value) {
		return SketchFingerprint.valueFingerprint(value);
	}

	private record TripleData(IRI subject, IRI predicate, IRI object, IRI context) {
		private TripleData(IRI subject, IRI predicate, IRI object) {
			this(subject, predicate, object, iri("defaultContext"));
		}
	}
}
