PREFIX : <http://example.com/data/>
PREFIX affected: <http://www.ontotext.com/semantic-object/affected>
PREFIX dash: <http://datashapes.org/dash#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX ont: <http://example.com/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX puml: <http://plantuml.com/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX res: <http://www.ontotext.com/semantic-object/result/>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX so: <http://www.ontotext.com/semantic-object/>
PREFIX vocsh: <http://example.org/shape/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .
[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .
[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

[] a ont:LangStringUniq;
        ont:uniqStrOrLangstrEnDeAllDialects "en val"@en .

[] a ont:LangStringUniq .

}
