/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.opentelemetry.http;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.net.URI;

import org.eclipse.rdf4j.http.client.spi.HttpRequest;
import org.eclipse.rdf4j.http.client.spi.HttpResponse;
import org.eclipse.rdf4j.opentelemetry.RDF4JOpenTelemetryConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import io.opentelemetry.sdk.testing.junit5.OpenTelemetryExtension;
import io.opentelemetry.sdk.trace.data.SpanData;

class TracingSessionSupportPrivacyTest {

	@RegisterExtension
	static final OpenTelemetryExtension otel = OpenTelemetryExtension.create();

	@Test
	void disabledCaptureDoesNotLeakQueryThroughUrl() throws Exception {
		URI uri = URI.create("https://example.test/sparql?query=ASK%7B%3Fs%20%3Fp%20%22private-value%22%7D");
		SpanData span = trace(uri, false);
		assertThat(span.getAttributes().get(SparqlOtelAttributes.SPARQL_QUERY)).isNull();
		assertThat(span.getAttributes().get(SparqlOtelAttributes.URL_FULL))
				.isEqualTo("https://example.test/sparql");
	}

	@Test
	void enabledCaptureCannotBypassQueryLengthLimitThroughUrl() throws Exception {
		SpanData span = trace(URI.create("https://example.test/sparql?query=ASK%20%7Bprivate-value%7D"), true);
		assertThat(span.getAttributes().get(SparqlOtelAttributes.SPARQL_QUERY)).isEqualTo("ASK {");
		assertThat(span.getAttributes().get(SparqlOtelAttributes.URL_FULL))
				.isEqualTo("https://example.test/sparql");
	}

	@ParameterizedTest
	@CsvSource({
			"https://alice:password@example.test/sparql?token=secret#private, https://example.test/sparql",
			"https://alice:password@example.test/sparql, https://example.test/sparql",
			"https://alice%40example.test:password@[::1]:8443/a%2Fb?query=secret, https://[::1]:8443/a%2Fb",
			"https://example.test/a%2Fb?query=secret, https://example.test/a%2Fb",
			"https://example.test/a%3Fb%23c?query=secret, https://example.test/a%3Fb%23c",
			"https://example.test/sparql#secret, https://example.test/sparql",
			"https://example.test/sparql, https://example.test/sparql"
	})
	void urlContainsOnlyEndpointWithoutCredentialsQueryOrFragment(String input, String expected) throws Exception {
		assertThat(trace(URI.create(input), false).getAttributes().get(SparqlOtelAttributes.URL_FULL))
				.isEqualTo(expected);
	}

	private SpanData trace(URI uri, boolean capture) throws Exception {
		RDF4JOpenTelemetryConfig config = RDF4JOpenTelemetryConfig.builder()
				.openTelemetry(otel.getOpenTelemetry())
				.captureQueryText(capture)
				.maxQueryTextLength(5)
				.build();
		TracingSessionSupport support = new TracingSessionSupport(config);
		HttpRequest request = HttpRequest.newBuilder("GET", uri).build();
		HttpResponse response = mock(HttpResponse.class);
		when(response.getStatusCode()).thenReturn(200);
		support.capture("query", "ASK {private-value}");
		assertThat(support.trace(request, () -> response)).isSameAs(response);
		// Redact only the telemetry: never modify the actual outbound request.
		assertThat(request.getUri()).isSameAs(uri);
		assertThat(otel.getSpans()).hasSize(1);
		return otel.getSpans().get(0);
	}
}
