/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.rio.helpers;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.zip.DeflaterOutputStream;
import java.util.zip.GZIPInputStream;
import java.util.zip.GZIPOutputStream;
import java.util.zip.InflaterInputStream;

/**
 * Compression codecs commonly used around RDF input and output streams.
 */
public enum RioCompression {

	ZSTD("zstd", Set.of("zst", "zstd")) {
		@Override
		public InputStream decompress(InputStream inputStream) throws IOException {
			return ZstdSupport.decompress(inputStream);
		}

		@Override
		public OutputStream compress(OutputStream outputStream) throws IOException {
			return ZstdSupport.compress(new NonClosingOutputStream(outputStream));
		}

		@Override
		public byte[] compress(byte[] uncompressed) throws IOException {
			return ZstdSupport.compress(uncompressed);
		}

		@Override
		public boolean isAvailable() {
			if (isDisabled()) {
				return false;
			}
			return ZstdSupport.isAvailable();
		}
	},

	GZIP("gzip", Set.of("gz", "gzip")) {
		@Override
		public InputStream decompress(InputStream inputStream) throws IOException {
			return new GZIPInputStream(inputStream);
		}

		@Override
		public OutputStream compress(OutputStream outputStream) throws IOException {
			return new GZIPOutputStream(outputStream, true);
		}
	},

	DEFLATE("deflate", Set.of("deflate")) {
		@Override
		public InputStream decompress(InputStream inputStream) {
			return new InflaterInputStream(inputStream);
		}

		@Override
		public OutputStream compress(OutputStream outputStream) {
			return new DeflaterOutputStream(outputStream, true);
		}
	},

	BROTLI("br", Set.of("br", "brotli")) {
		@Override
		public InputStream decompress(InputStream inputStream) throws IOException {
			return BrotliSupport.decompress(inputStream);
		}

		@Override
		public OutputStream compress(OutputStream outputStream) throws IOException {
			return BrotliSupport.compress(new NonClosingOutputStream(outputStream));
		}

		@Override
		public boolean isAvailable() {
			if (isDisabled()) {
				return false;
			}
			return BrotliSupport.isAvailable();
		}
	};

	public static final String DISABLED_ENCODINGS_PROPERTY = "org.eclipse.rdf4j.rio.compression.disabledEncodings";
	private static final int SIGNATURE_LENGTH = 4;

	private final String contentEncoding;
	private final Set<String> fileExtensions;

	RioCompression(String contentEncoding, Set<String> fileExtensions) {
		this.contentEncoding = contentEncoding;
		this.fileExtensions = fileExtensions;
	}

	public String contentEncoding() {
		return contentEncoding;
	}

	public abstract InputStream decompress(InputStream inputStream) throws IOException;

	public abstract OutputStream compress(OutputStream outputStream) throws IOException;

	public byte[] compress(byte[] uncompressed) throws IOException {
		ByteArrayOutputStream buffer = new ByteArrayOutputStream();
		try (OutputStream outputStream = compress(buffer)) {
			outputStream.write(uncompressed);
		}
		return buffer.toByteArray();
	}

	public void finish(OutputStream outputStream) throws IOException {
		if (outputStream instanceof DeflaterOutputStream) {
			((DeflaterOutputStream) outputStream).finish();
			outputStream.flush();
		} else {
			outputStream.close();
		}
	}

	public boolean isAvailable() {
		return !isDisabled();
	}

	public static InputStream decompressIfDetected(InputStream inputStream) throws IOException {
		Objects.requireNonNull(inputStream, "inputStream must not be null");
		InputStream source = markable(inputStream);
		Optional<RioCompression> compression = forStreamSignature(source);
		if (compression.isPresent()) {
			return compression.get().decompress(source);
		}
		return source;
	}

	public static InputStream decompressIfDetected(InputStream inputStream, String fileName) throws IOException {
		Objects.requireNonNull(inputStream, "inputStream must not be null");
		Optional<RioCompression> compression = forFileName(fileName);
		if (compression.isPresent()) {
			return compression.get().decompress(inputStream);
		}
		return decompressIfDetected(inputStream);
	}

	public static Optional<RioCompression> forContentEncoding(String contentEncoding) {
		if (contentEncoding == null) {
			return Optional.empty();
		}
		for (String value : contentEncoding.split(",")) {
			String normalized = value.trim().toLowerCase(Locale.ROOT);
			for (RioCompression compression : values()) {
				if (compression.contentEncoding.equals(normalized) && compression.isAvailable()) {
					return Optional.of(compression);
				}
			}
		}
		return Optional.empty();
	}

	public static Optional<RioCompression> forFileName(String fileName) {
		if (fileName == null || fileName.isBlank()) {
			return Optional.empty();
		}
		String normalizedFileName = fileName.toLowerCase(Locale.ROOT);
		int fragment = normalizedFileName.indexOf('#');
		if (fragment >= 0) {
			normalizedFileName = normalizedFileName.substring(0, fragment);
		}
		int query = normalizedFileName.indexOf('?');
		if (query >= 0) {
			normalizedFileName = normalizedFileName.substring(0, query);
		}
		int separator = Math.max(normalizedFileName.lastIndexOf('/'), normalizedFileName.lastIndexOf('\\'));
		if (separator >= 0) {
			normalizedFileName = normalizedFileName.substring(separator + 1);
		}
		int dot = normalizedFileName.lastIndexOf('.');
		if (dot < 0 || dot == normalizedFileName.length() - 1) {
			return Optional.empty();
		}

		String extension = normalizedFileName.substring(dot + 1);
		for (RioCompression compression : values()) {
			if (compression.fileExtensions.contains(extension) && compression.isAvailable()) {
				return Optional.of(compression);
			}
		}
		return Optional.empty();
	}

	public static List<RioCompression> availableEncodings() {
		return List.of(values())
				.stream()
				.filter(RioCompression::isAvailable)
				.collect(Collectors.toUnmodifiableList());
	}

	private static Optional<RioCompression> forStreamSignature(InputStream inputStream) throws IOException {
		inputStream.mark(SIGNATURE_LENGTH);
		byte[] signature = inputStream.readNBytes(SIGNATURE_LENGTH);
		inputStream.reset();

		if (isGzip(signature) && GZIP.isAvailable()) {
			return Optional.of(GZIP);
		}
		if (isZstd(signature) && ZSTD.isAvailable()) {
			return Optional.of(ZSTD);
		}
		if (isZlibDeflate(signature) && DEFLATE.isAvailable()) {
			return Optional.of(DEFLATE);
		}
		return Optional.empty();
	}

	private static InputStream markable(InputStream inputStream) {
		return inputStream.markSupported() ? inputStream : new BufferedInputStream(inputStream, SIGNATURE_LENGTH);
	}

	private static boolean isGzip(byte[] signature) {
		return signature.length >= 2 && (signature[0] & 0xff) == 0x1f && (signature[1] & 0xff) == 0x8b;
	}

	private static boolean isZstd(byte[] signature) {
		return signature.length >= 4
				&& (signature[0] & 0xff) == 0x28
				&& (signature[1] & 0xff) == 0xb5
				&& (signature[2] & 0xff) == 0x2f
				&& (signature[3] & 0xff) == 0xfd;
	}

	private static boolean isZlibDeflate(byte[] signature) {
		if (signature.length < 2) {
			return false;
		}
		int cmf = signature[0] & 0xff;
		int flg = signature[1] & 0xff;
		return (cmf & 0x0f) == 8 && (cmf >> 4) <= 7 && ((cmf << 8) + flg) % 31 == 0;
	}

	private static Class<?> compressionClass(String className) throws IOException {
		try {
			return Class.forName(className);
		} catch (ClassNotFoundException | LinkageError e) {
			throw new IOException("Compression library is not available: " + className, e);
		}
	}

	private static IOException compressionUnavailable(String name, ReflectiveOperationException e) {
		Throwable cause = e instanceof InvocationTargetException ? ((InvocationTargetException) e).getCause() : e;
		return new IOException("Compression library is not available: " + name, cause);
	}

	boolean isDisabled() {
		String disabledEncodings = System.getProperty(DISABLED_ENCODINGS_PROPERTY);
		if (disabledEncodings == null || disabledEncodings.isBlank()) {
			return false;
		}
		for (String disabledEncoding : disabledEncodings.split(",")) {
			if (contentEncoding.equals(disabledEncoding.trim().toLowerCase(Locale.ROOT))) {
				return true;
			}
		}
		return false;
	}

	private static final class ZstdSupport {

		private static final String ZSTD = "com.github.luben.zstd.Zstd";
		private static final String ZSTD_INPUT_STREAM = "com.github.luben.zstd.ZstdInputStream";
		private static final String ZSTD_OUTPUT_STREAM = "com.github.luben.zstd.ZstdOutputStream";

		private static InputStream decompress(InputStream inputStream) throws IOException {
			try {
				Constructor<?> constructor = compressionClass(ZSTD_INPUT_STREAM).getConstructor(InputStream.class);
				return (InputStream) constructor.newInstance(inputStream);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(ZSTD_INPUT_STREAM, e);
			}
		}

		private static OutputStream compress(OutputStream outputStream) throws IOException {
			try {
				Constructor<?> constructor = compressionClass(ZSTD_OUTPUT_STREAM).getConstructor(OutputStream.class);
				return (OutputStream) constructor.newInstance(outputStream);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(ZSTD_OUTPUT_STREAM, e);
			}
		}

		private static byte[] compress(byte[] uncompressed) throws IOException {
			try {
				Method compress = compressionClass(ZSTD).getMethod("compress", byte[].class);
				return (byte[]) compress.invoke(null, uncompressed);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(ZSTD, e);
			}
		}

		private static boolean isAvailable() {
			try {
				compress(new byte[0]);
				return true;
			} catch (IOException | RuntimeException | LinkageError e) {
				return false;
			}
		}
	}

	private static final class BrotliSupport {

		private static final String BROTLI_LOADER = "com.aayushatharva.brotli4j.Brotli4jLoader";
		private static final String BROTLI_INPUT_STREAM = "com.aayushatharva.brotli4j.decoder.BrotliInputStream";
		private static final String BROTLI_OUTPUT_STREAM = "com.aayushatharva.brotli4j.encoder.BrotliOutputStream";
		private static final String BROTLI_PARAMETERS = "com.aayushatharva.brotli4j.encoder.Encoder$Parameters";

		private static InputStream decompress(InputStream inputStream) throws IOException {
			ensureAvailable();
			try {
				Constructor<?> constructor = compressionClass(BROTLI_INPUT_STREAM).getConstructor(InputStream.class);
				return (InputStream) constructor.newInstance(inputStream);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(BROTLI_INPUT_STREAM, e);
			}
		}

		private static OutputStream compress(OutputStream outputStream) throws IOException {
			ensureAvailable();
			try {
				Class<?> parametersClass = compressionClass(BROTLI_PARAMETERS);
				Object parameters = parametersClass.getConstructor().newInstance();
				parametersClass.getMethod("setQuality", int.class).invoke(parameters, 4);

				Constructor<?> constructor = compressionClass(BROTLI_OUTPUT_STREAM)
						.getConstructor(OutputStream.class, parametersClass);
				return (OutputStream) constructor.newInstance(outputStream, parameters);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(BROTLI_OUTPUT_STREAM, e);
			}
		}

		private static boolean isAvailable() {
			try {
				ensureAvailable();
				return true;
			} catch (IOException | RuntimeException | LinkageError e) {
				return false;
			}
		}

		private static void ensureAvailable() throws IOException {
			try {
				compressionClass(BROTLI_LOADER).getMethod("ensureAvailability").invoke(null);
			} catch (ReflectiveOperationException e) {
				throw compressionUnavailable(BROTLI_LOADER, e);
			}
		}
	}

	private static final class NonClosingOutputStream extends FilterOutputStream {

		private NonClosingOutputStream(OutputStream out) {
			super(out);
		}

		@Override
		public void close() throws IOException {
			flush();
		}
	}
}
