/*******************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.util;

import java.io.File;
import java.util.UUID;

import org.eclipse.rdf4j.common.app.AppConfiguration;
import org.eclipse.rdf4j.common.exception.RDF4JException;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.base.CoreDatatype;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BooleanQuery;
import org.eclipse.rdf4j.query.MalformedQueryException;
import org.eclipse.rdf4j.query.Operation;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.QueryResultHandlerException;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.Update;
import org.eclipse.rdf4j.query.UpdateExecutionException;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.sail.nativerdf.NativeStore;
import org.eclipse.rdf4j.workbench.exceptions.BadRequestException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Provides an interface to the private repository with the saved queries.
 *
 * @author Dale Visser
 */
public class QueryStorage {

	private static final Object LOCK = new Object();

	private static final QueryEvaluator EVAL = QueryEvaluator.INSTANCE;

	private static QueryStorage instance;

	public static QueryStorage getSingletonInstance(final AppConfiguration config)
			throws RepositoryException {
		synchronized (LOCK) {
			if (instance == null || instance.isShutdown()) {
				instance = new QueryStorage(config);
			}
			return instance;
		}
	}

	private boolean isShutdown() {
		return queries == null || !queries.isInitialized();
	}

	private static final Logger LOGGER = LoggerFactory.getLogger(QueryStorage.class);

	private static final ValueFactory VF = SimpleValueFactory.getInstance();

	private static final String PRE = "PREFIX : <https://openrdf.org/workbench/>\n";

	private static final String SAVE = PRE
			+ "INSERT { ?query :userName ?userName ; :queryName ?queryName ; "
			+ ":repository ?repository ; :shared ?shared ; :queryLanguage ?queryLanguage ; :query ?queryText ; "
			+ ":infer ?infer ; :rowsPerPage ?rowsPerPage ; :queryTimeout ?queryTimeout . } WHERE {}";

	private static final String ASK_EXISTS = PRE
			+ "ASK { [] :userName ?userName ; :queryName ?queryName ; :repository ?repository . }";

	private static final String UPDATE_FILTER = "FILTER (?user = ?currentUser || ?user = \"\" ) } ";

	private static final String READ_FILTER = "FILTER (?user = ?currentUser || ?user = \"\" || ?shared) } ";

	private static final String ASK_UPDATABLE = PRE + "ASK { ?query :userName ?user . " + UPDATE_FILTER;

	private static final String ASK_READABLE = PRE + "ASK { ?query :userName ?user  ; :shared ?shared . "
			+ READ_FILTER;

	private static final String DELETE = PRE
			+ "DELETE { ?query ?p ?o } WHERE { ?query :userName ?user ; ?p ?o . " + UPDATE_FILTER;

	private static final String MATCH = ":shared ?oldShared ; :queryLanguage ?oldQueryLanguage ; "
			+ ":query ?oldQueryText ; :rowsPerPage ?oldRowsPerPage .\n";

	private static final String OPTIONAL_UPDATE_FIELDS = "OPTIONAL { ?query :infer ?oldInfer . }\n"
			+ "OPTIONAL { ?query :queryTimeout ?oldQueryTimeout . }\n";

	private static final String UPDATE = PRE
			+ "DELETE { ?query " + MATCH + "?query :infer ?oldInfer .\n?query :queryTimeout ?oldQueryTimeout .\n"
			+ "}\nINSERT { ?query :shared ?shared ; :queryLanguage ?queryLanguage ; :query ?queryText ; "
			+ ":infer ?infer ; :rowsPerPage ?rowsPerPage ; :queryTimeout ?queryTimeout . }\n"
			+ "WHERE { ?query :userName ?user ; " + MATCH + OPTIONAL_UPDATE_FIELDS + UPDATE_FILTER;

	private static final String SELECT_URI = PRE
			+ "SELECT ?query { ?query :repository ?repository ; :userName ?userName ; :queryName ?queryName . } ";

	private static final String SELECT_TEXT = PRE
			+ "SELECT ?queryText { [] :repository ?repository ; :userName ?userName ; :queryName ?queryName ; :query ?queryText . } ";

	private static final String SELECT = PRE
			+ "SELECT ?query ?user ?queryName ?shared ?queryLn ?queryText ?infer ?rowsPerPage ?queryTimeout "
			+ "{ ?query :repository ?repository ; :userName ?user ; :queryName ?queryName ; :shared ?shared ; "
			+ ":queryLanguage ?queryLn ; :query ?queryText ; :infer ?infer ; :rowsPerPage ?rowsPerPage .\n"
			+ "OPTIONAL { ?query :queryTimeout ?queryTimeout . }\n"
			+ READ_FILTER + "ORDER BY ?user ?queryName";

	private final Repository queries;

	private static final String USER_NAME = "userName";

	private static final String CURRENT_USER = "currentUser";

	private static final String REPOSITORY = "repository";

	private static final String QUERY = "query";

	private static final String QUERY_NAME = "queryName";

	/**
	 * Create a new object for accessing the store of user queries.
	 *
	 * @param appConfig the application configuration, for obtaining the data directory
	 * @throws RepositoryException if there is an issue creating the object to access the repository
	 */
	private QueryStorage(final AppConfiguration appConfig) throws RepositoryException {
		this(new SailRepository(new NativeStore(new File(appConfig.getDataDir(), "queries"))));
		queries.init();
	}

	QueryStorage(final Repository queries) {
		this.queries = queries;
	}

	public void shutdown() {
		try {
			if (queries != null && queries.isInitialized()) {
				queries.shutDown();
			}
		} catch (RepositoryException e) {
			LOGGER.warn(e.getMessage());
		}
	}

	/**
	 * Checks whether the current user/password credentials can really access the current repository.
	 *
	 * @param repository the current repository
	 * @return true, if it is possible to request a statement from the repository with the given credentials
	 * @throws RepositoryException if there is an issue closing the connection
	 */
	public boolean checkAccess(final Repository repository) throws RepositoryException {
		LOGGER.info("repository: {}", repository);
		boolean rval = true;
		try (RepositoryConnection con = repository.getConnection()) {
			// Manufacture an unlikely unique statement to check.
			IRI uri = con.getValueFactory().createIRI("urn:uuid:" + UUID.randomUUID());
			con.hasStatement(uri, uri, uri, false, uri);
		} catch (RepositoryException re) {
			rval = false;
		}
		return rval;
	}

	/**
	 * Save a query. It is the responsibility of the calling code to call checkAccess() with the full credentials first.
	 *
	 * @param repository    the repository the query is associated with
	 * @param queryName     the name for the query
	 * @param userName      the user saving the query
	 * @param shared        whether the query is to be shared with other users
	 * @param queryLanguage the language of the query (only SPARQL is currently supported)
	 * @param queryText     the actual query text
	 * @param infer
	 * @param rowsPerPage   rows to display per page, may be 0 (all), 10, 50, 100, or 200)
	 * @param queryTimeout  query timeout in seconds, may be 0 to use the repository default
	 * @throws RDF4JException
	 */
	public void saveQuery(final String repositoryReference, final String queryName, final String userName,
			final boolean shared, final QueryLanguage queryLanguage, final String queryText, final boolean infer,
			final int rowsPerPage, final int queryTimeout) throws RDF4JException {
		validateSavedQueryFields(queryLanguage, rowsPerPage, queryTimeout);
		try (RepositoryConnection connection = this.queries.getConnection()) {
			Update save = connection.prepareUpdate(QueryLanguage.SPARQL, SAVE);
			save.setBinding(REPOSITORY, VF.createIRI(repositoryReference));
			save.setBinding(QUERY, VF.createIRI("urn:uuid:" + UUID.randomUUID()));
			save.setBinding(QUERY_NAME, VF.createLiteral(queryName));
			bindSavedQueryFields(save, userName, shared, queryLanguage, queryText, infer, rowsPerPage, queryTimeout);
			save.execute();
		}
	}

	/**
	 * Determines whether the user with the given userName is allowed to update or delete the given query.
	 *
	 * @param query       the node identifying the query of interest
	 * @param currentUser the user to check access for
	 * @return <var>true</var> if the given query was saved by the given user or the anonymous user
	 */
	public boolean canChange(final IRI query, final String currentUser)
			throws RepositoryException, QueryEvaluationException, MalformedQueryException {
		return performAccessQuery(ASK_UPDATABLE, query, currentUser);
	}

	/**
	 * Determines whether the user with the given userName is allowed to read the given query.
	 *
	 * @param query       the node identifying the query of interest
	 * @param currentUser the user to check access for
	 * @return <var>true</var> if the given query was saved by either the given user or the anonymous user, or is shared
	 */
	public boolean canRead(IRI query, String currentUser)
			throws RepositoryException, QueryEvaluationException, MalformedQueryException {
		return performAccessQuery(ASK_READABLE, query, currentUser);
	}

	private boolean performAccessQuery(String accessSPARQL, IRI query, String currentUser)
			throws RepositoryException, QueryEvaluationException, MalformedQueryException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			BooleanQuery accessQuery = connection.prepareBooleanQuery(QueryLanguage.SPARQL, accessSPARQL);
			accessQuery.setBinding(QUERY, query);
			accessQuery.setBinding(CURRENT_USER, VF.createLiteral(currentUser));
			return accessQuery.evaluate();
		}
	}

	public boolean askExists(final String repositoryReference, final String queryName, final String userName)
			throws QueryEvaluationException, RepositoryException, MalformedQueryException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			BooleanQuery ask = connection.prepareBooleanQuery(QueryLanguage.SPARQL, ASK_EXISTS);
			ask.setBinding(REPOSITORY, VF.createIRI(repositoryReference));
			ask.setBinding(QUERY_NAME, VF.createLiteral(queryName));
			ask.setBinding(USER_NAME, VF.createLiteral(userName));
			return ask.evaluate();
		}
	}

	/**
	 * Delete the given query for the given user. It is the responsibility of the calling code to call checkAccess() and
	 * canDelete() with the full credentials first.
	 *
	 * @param query
	 * @param userName
	 * @throws RepositoryException
	 * @throws UpdateExecutionException
	 * @throws MalformedQueryException
	 */
	public void deleteQuery(final IRI query, final String userName)
			throws RepositoryException, UpdateExecutionException, MalformedQueryException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			Update delete = connection.prepareUpdate(QueryLanguage.SPARQL, DELETE);
			delete.setBinding(QUERY, query);
			delete.setBinding(CURRENT_USER, VF.createLiteral(userName));
			delete.execute();
		}
	}

	/**
	 * Update the entry for the given query. It is the responsibility of the calling code to call checkAccess() with the
	 * full credentials first.
	 *
	 * @param query         the query to update
	 * @param userName      the user name
	 * @param shared        whether to share with other users
	 * @param queryLanguage the query language
	 * @param queryText     the text of the query
	 * @param infer
	 * @param rowsPerPage   the rows per page to display of the query
	 * @param queryTimeout  query timeout in seconds, may be 0 to use the repository default
	 * @throws RepositoryException      if a problem occurs during the update
	 * @throws UpdateExecutionException if a problem occurs during the update
	 * @throws MalformedQueryException  if a problem occurs during the update
	 */
	public void updateQuery(final IRI query, final String userName, final boolean shared,
			final QueryLanguage queryLanguage, final String queryText, final boolean infer, final int rowsPerPage,
			final int queryTimeout)
			throws RepositoryException, UpdateExecutionException, MalformedQueryException {
		validateSavedQueryFields(queryLanguage, rowsPerPage, queryTimeout);
		try (RepositoryConnection connection = this.queries.getConnection()) {
			Update update = connection.prepareUpdate(QueryLanguage.SPARQL, UPDATE);
			update.setBinding(QUERY, query);
			update.setBinding(CURRENT_USER, VF.createLiteral(userName));
			bindSavedQueryFields(update, userName, shared, queryLanguage, queryText, infer, rowsPerPage, queryTimeout);
			update.execute();
		}
	}

	/**
	 * Prepares a query to retrieve the queries accessible to the given user in the given repository. When evaluated,
	 * the query result will have the following binding names: query, user, queryName, shared, queryLn, queryText,
	 * rowsPerPage, queryTimeout. It is the responsibility of the calling code to call checkAccess() with the full
	 * credentials first.
	 *
	 * @param repository that the saved queries run against
	 * @param userName   that is requesting the saved queries
	 * @param builder    receives a list of all the saved queries against the given repository and accessible to the
	 *                   given user
	 * @throws RepositoryException         if there's a problem connecting to the saved queries repository
	 * @throws MalformedQueryException     if the query is not legal SPARQL
	 * @throws QueryEvaluationException    if there is a problem while attempting to evaluate the query
	 * @throws QueryResultHandlerException
	 */
	public void selectSavedQueries(final String repositoryReference, final String userName,
			final TupleResultBuilder builder)
			throws RepositoryException, MalformedQueryException, QueryEvaluationException, QueryResultHandlerException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			TupleQuery select = connection.prepareTupleQuery(QueryLanguage.SPARQL, SELECT);
			select.setBinding(CURRENT_USER, VF.createLiteral(userName));
			select.setBinding(REPOSITORY, VF.createIRI(repositoryReference));
			EVAL.evaluateTupleQuery(builder, select);
		}
	}

	/**
	 * Returns the URI for the saved query in the given repository with the given name, owned by the given owner.
	 *
	 * @param repository The repository the query is associated with.
	 * @param owner      The user that saved the query.
	 * @param queryName  The name given to the query.
	 * @return if it exists, the URI referring to the specified saved query.
	 * @throws RDF4JException      if issues occur performing the necessary queries.
	 * @throws BadRequestException if the the specified stored query doesn't exist
	 */
	public IRI selectSavedQuery(final String repositoryReference, final String owner, final String queryName)
			throws RDF4JException, BadRequestException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			TupleQuery query = connection.prepareTupleQuery(QueryLanguage.SPARQL, SELECT_URI);
			query.setBinding(USER_NAME, VF.createLiteral(owner));
			query.setBinding(REPOSITORY, VF.createIRI(repositoryReference));
			query.setBinding(QUERY_NAME, VF.createLiteral(queryName));
			try (TupleQueryResult result = query.evaluate()) {
				if (result.hasNext()) {
					return (IRI) (result.next().getValue("query"));
				} else {
					throw new BadRequestException("Could not find query entry in storage.");
				}
			}

		}
	}

	/**
	 * Retrieves the specified query text. No security checks are done here. If the saved query exists, its text is
	 * returned.
	 *
	 * @param repository Repository that the saved query is associated with.
	 * @param owner      The user that saved the query.
	 * @param queryName  The name given to the saved query.
	 * @return the text of the saved query, if it exists
	 * @throws RDF4JException      if a problem occurs accessing storage
	 * @throws BadRequestException if the specified query doesn't exist
	 */
	public String getQueryText(final String repositoryReference, final String owner, final String queryName)
			throws RDF4JException, BadRequestException {
		try (RepositoryConnection connection = this.queries.getConnection()) {
			TupleQuery query = connection.prepareTupleQuery(QueryLanguage.SPARQL, SELECT_TEXT);
			query.setBinding(USER_NAME, VF.createLiteral(owner));
			query.setBinding(REPOSITORY, VF.createIRI(repositoryReference));
			query.setBinding(QUERY_NAME, VF.createLiteral(queryName));
			try (TupleQueryResult result = query.evaluate()) {
				if (result.hasNext()) {
					return result.next().getValue("queryText").stringValue();
				} else {
					throw new BadRequestException("Could not find query entry in storage.");
				}
			}

		}
	}

	private void bindSavedQueryFields(Operation operation, String userName, boolean shared,
			QueryLanguage queryLanguage, String queryText, boolean infer, int rowsPerPage, int queryTimeout) {
		operation.setBinding(USER_NAME, VF.createLiteral(userName));
		operation.setBinding("shared", VF.createLiteral(shared));
		operation.setBinding("queryLanguage", VF.createLiteral(queryLanguage.toString()));
		operation.setBinding("queryText", VF.createLiteral(queryText));
		operation.setBinding("infer", VF.createLiteral(infer));
		operation.setBinding("rowsPerPage",
				VF.createLiteral(String.valueOf(rowsPerPage), CoreDatatype.XSD.UNSIGNED_BYTE));
		operation.setBinding("queryTimeout",
				VF.createLiteral(String.valueOf(queryTimeout), CoreDatatype.XSD.INTEGER));
	}

	private void validateSavedQueryFields(QueryLanguage queryLanguage, int rowsPerPage, int queryTimeout)
			throws RepositoryException {
		if (QueryLanguage.SPARQL != queryLanguage) {
			throw new RepositoryException("May only save SPARQL queries, not" + queryLanguage.toString());
		}
		if (0 != rowsPerPage && 10 != rowsPerPage && 20 != rowsPerPage && 50 != rowsPerPage && 100 != rowsPerPage
				&& 200 != rowsPerPage) {
			throw new RepositoryException("Illegal value for rows per page: " + rowsPerPage);
		}
		if (queryTimeout < 0) {
			throw new RepositoryException("Illegal value for query timeout: " + queryTimeout);
		}
	}
}
