/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.util;

import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Pattern;

import jakarta.servlet.http.HttpServletRequest;

/** Query-only representation selection; a v2 Accept header never promotes generic page or export writers. */
public final class WorkbenchQueryProtocol {

	public static final String ACCEPT = "application/vnd.rdf4j.workbench-query-v2+ndjson";

	public static final String VERSION_ATTRIBUTE = "org.eclipse.rdf4j.workbench.queryStreamVersion";

	private static final Pattern QUALITY = Pattern.compile("(?:0(?:\\.[0-9]{0,3})?|1(?:\\.0{0,3})?)");

	private WorkbenchQueryProtocol() {
	}

	public static void configure(HttpServletRequest request) {
		request.setAttribute(VERSION_ATTRIBUTE, negotiateVersion(request));
	}

	public static int version(HttpServletRequest request) {
		Object version = request.getAttribute(VERSION_ATTRIBUTE);
		return version instanceof Integer value && (value == 1 || value == 2) ? value : 0;
	}

	public static int negotiateVersion(HttpServletRequest request) {
		String[] formats = request.getParameterValues("Accept");
		if (formats != null && formats.length > 0) {
			String format = formats[formats.length - 1];
			if (format != null && !format.isBlank()) {
				return 0;
			}
		}
		Map<String, Double> preferences = qualities(request, "Accept");
		double compact = preferences.getOrDefault(ACCEPT, 0.0);
		double legacy = preferences.getOrDefault(WorkbenchPageProtocol.ACCEPT, 0.0);
		return compact > 0 && compact >= legacy ? 2 : legacy > 0 ? 1 : 0;
	}

	public static String contentType(HttpServletRequest request) {
		return version(request) == 2 ? ACCEPT + "; charset=UTF-8" : WorkbenchPageProtocol.CONTENT_TYPE;
	}

	static Map<String, Double> qualities(HttpServletRequest request, String headerName) {
		Map<String, Double> preferences = new LinkedHashMap<>();
		Enumeration<String> headers = request.getHeaders(headerName);
		if (headers == null || !headers.hasMoreElements()) {
			addQualities(preferences, request.getHeader(headerName));
		} else {
			while (headers.hasMoreElements()) {
				addQualities(preferences, headers.nextElement());
			}
		}
		return preferences;
	}

	private static void addQualities(Map<String, Double> preferences, String header) {
		if (header == null) {
			return;
		}
		for (String range : header.split(",")) {
			String[] parts = range.trim().split(";");
			String token = parts[0].trim().toLowerCase(Locale.ROOT);
			if (token.isEmpty()) {
				continue;
			}
			double quality = 1;
			for (int index = 1; index < parts.length; index++) {
				String parameter = parts[index].trim();
				int equals = parameter.indexOf('=');
				if (equals >= 0 && "q".equalsIgnoreCase(parameter.substring(0, equals).trim())) {
					String value = parameter.substring(equals + 1).trim();
					quality = QUALITY.matcher(value).matches() ? Double.parseDouble(value) : 0;
				}
			}
			preferences.put(token, quality);
		}
	}
}
