/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.util;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.lang.reflect.Method;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.eclipse.rdf4j.common.iteration.CloseableIteratorIteration;
import org.eclipse.rdf4j.model.Namespace;
import org.eclipse.rdf4j.query.GraphQuery;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.TupleQuery;
import org.eclipse.rdf4j.query.TupleQueryResult;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.query.impl.AbstractQuery;
import org.eclipse.rdf4j.query.impl.IteratingTupleQueryResult;
import org.eclipse.rdf4j.query.trace.QueryTrace;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryResult;
import org.eclipse.rdf4j.workbench.exceptions.BadRequestException;
import org.junit.jupiter.api.Test;

class QueryEvaluatorTraceTest {

	private static void stubNamespaces(RepositoryConnection connection) {
		when(connection.getNamespaces()).thenReturn(new RepositoryResult<>(
				new CloseableIteratorIteration<>(List.<Namespace>of().iterator())));
	}

	private static boolean isPreserveQueryOrderEnabled(AbstractQuery query) {
		try {
			Method method = query.getClass().getMethod("isPreserveQueryOrder");
			return (Boolean) method.invoke(query);
		} catch (ReflectiveOperationException e) {
			throw new AssertionError("Query should expose preserve query order flag", e);
		}
	}

	@Test
	void shouldUseTraceInsteadOfEvaluateWhenTraceParameterIsPresent() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery tupleQuery = new TraceTupleQuery();

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(tupleQuery);

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp, new ByteArrayOutputStream(), xslPath, con,
				queryText, req, cookies, null);
	}

	@Test
	void shouldPreferTraceOverExplainWhenBothRequested() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery tupleQuery = mock(TupleQuery.class);

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(req.isParameterPresent("explain")).thenReturn(true);
		when(req.getParameter("explain")).thenReturn("Optimized");
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(tupleQuery);
		when(tupleQuery.trace()).thenReturn(QueryTrace.success(List.of(), List.of()));
		when(tupleQuery.explain(Explanation.Level.Optimized))
				.thenThrow(new AssertionError("explain() should not run when trace is selected"));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp, new ByteArrayOutputStream(), xslPath, con,
				queryText, req, cookies, null);

		verify(tupleQuery).trace();
		verify(tupleQuery, never()).explain(Explanation.Level.Optimized);
	}

	@Test
	void shouldApplyWorkbenchLimitBeforeTracingTupleQuery() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String pagedQueryText = queryText + "\nlimit 5";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery unpagedQuery = mock(TupleQuery.class);
		TupleQuery pagedQuery = mock(TupleQuery.class);

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(req.getInt("limit_query")).thenReturn(5);
		when(req.getInt("offset")).thenReturn(0);
		when(req.getInt("query-timeout")).thenReturn(0);
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(unpagedQuery);
		when(con.prepareQuery(QueryLanguage.SPARQL, pagedQueryText)).thenReturn(pagedQuery);
		when(unpagedQuery.trace()).thenThrow(new AssertionError("trace() should use the paged query text"));
		when(pagedQuery.trace()).thenReturn(QueryTrace.success(List.of(), List.of()));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp, new ByteArrayOutputStream(), xslPath, con,
				queryText, req, cookies, null);

		verify(pagedQuery).trace();
		verify(unpagedQuery, never()).trace();
	}

	@Test
	void shouldApplyInferTimeoutAndPreserveOrderBeforeTracingTupleQuery() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery tupleQuery = new TraceSettingsAwareTupleQuery();

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(req.isParameterPresent("infer")).thenReturn(true);
		when(req.getParameter("infer")).thenReturn("false");
		when(req.getParameter("preserve-query-order")).thenReturn("true");
		when(req.getInt("query-timeout")).thenReturn(9);
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(tupleQuery);

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp, new ByteArrayOutputStream(), xslPath, con,
				queryText, req, cookies, null);
	}

	@Test
	void shouldRejectTraceForNonTupleQueries() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp,
				new ByteArrayOutputStream(), xslPath, con, queryText, req, cookies, null))
				.isInstanceOf(BadRequestException.class)
				.hasMessage("Trace is only supported for tuple queries.");
	}

	@Test
	void shouldTranslateUnsupportedTraceOperationsToBadRequest() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery tupleQuery = new UnsupportedTraceTupleQuery();

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.getParameter("trace")).thenReturn("true");
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(tupleQuery);

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp,
				new ByteArrayOutputStream(), xslPath, con, queryText, req, cookies, null))
				.isInstanceOf(BadRequestException.class)
				.hasMessage("Trace is not supported for this query or repository.");
	}

	@Test
	void shouldIgnoreFalseTraceParameterAndEvaluateQuery() throws Exception {
		String queryText = "select * where { ?s ?p ?o }";
		String xslPath = "/xsl";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		WorkbenchRequest req = mock(WorkbenchRequest.class);
		HttpServletResponse resp = mock(HttpServletResponse.class);
		RepositoryConnection con = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		TupleQuery tupleQuery = new EvaluateTupleQuery();

		stubNamespaces(con);
		when(req.getParameter("queryLn")).thenReturn("SPARQL");
		when(req.isParameterPresent("trace")).thenReturn(true);
		when(req.getParameter("trace")).thenReturn("false");
		when(req.isParameterPresent("Accept")).thenReturn(false);
		when(req.getInt("offset")).thenReturn(0);
		when(req.getInt("limit_query")).thenReturn(0);
		when(req.getInt("know_total")).thenReturn(0);
		when(req.getInt("query-timeout")).thenReturn(0);
		when(con.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(tupleQuery);

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, resp, new ByteArrayOutputStream(), xslPath, con,
				queryText, req, cookies, null);
	}

	private static final class TraceTupleQuery extends AbstractQuery implements TupleQuery {
		@Override
		public TupleQueryResult evaluate() {
			throw new AssertionError("evaluate() should not run when trace is selected");
		}

		@Override
		public void evaluate(org.eclipse.rdf4j.query.TupleQueryResultHandler handler) {
			throw new AssertionError("evaluate(handler) should not run when trace is selected");
		}

		@Override
		public QueryTrace trace() {
			return QueryTrace.success(List.of(), List.of());
		}
	}

	private static final class EvaluateTupleQuery extends AbstractQuery implements TupleQuery {
		@Override
		public TupleQueryResult evaluate() {
			return new IteratingTupleQueryResult(List.of("s"), List.of());
		}

		@Override
		public void evaluate(org.eclipse.rdf4j.query.TupleQueryResultHandler handler) {
			throw new AssertionError("evaluate(handler) should not run in this regression test");
		}

		@Override
		public QueryTrace trace() {
			throw new AssertionError("trace() should not run when trace=false");
		}
	}

	private static final class TraceSettingsAwareTupleQuery extends AbstractQuery implements TupleQuery {
		@Override
		public TupleQueryResult evaluate() {
			throw new AssertionError("evaluate() should not run when trace is selected");
		}

		@Override
		public void evaluate(org.eclipse.rdf4j.query.TupleQueryResultHandler handler) {
			throw new AssertionError("evaluate(handler) should not run when trace is selected");
		}

		@Override
		public QueryTrace trace() {
			if (getIncludeInferred()) {
				throw new AssertionError("trace() should see includeInferred=false");
			}
			if (getMaxExecutionTime() != 9) {
				throw new AssertionError("trace() should see maxExecutionTime=9");
			}
			if (!isPreserveQueryOrderEnabled(this)) {
				throw new AssertionError("trace() should see preserveQueryOrder=true");
			}
			return QueryTrace.success(List.of(), List.of());
		}
	}

	private static final class UnsupportedTraceTupleQuery extends AbstractQuery implements TupleQuery {
		@Override
		public TupleQueryResult evaluate() {
			throw new AssertionError("evaluate() should not run when trace is selected");
		}

		@Override
		public void evaluate(org.eclipse.rdf4j.query.TupleQueryResultHandler handler) {
			throw new AssertionError("evaluate(handler) should not run when trace is selected");
		}

		@Override
		public QueryTrace trace() {
			throw new UnsupportedOperationException("unsupported");
		}
	}
}
