/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.workbench.util;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletResponse;

import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.BooleanQuery;
import org.eclipse.rdf4j.query.GraphQuery;
import org.eclipse.rdf4j.query.Query;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.explanation.Explanation;
import org.eclipse.rdf4j.query.impl.IteratingGraphQueryResult;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.workbench.exceptions.BadRequestException;
import org.junit.jupiter.api.Test;

class QueryEvaluatorCoverageTest {

	@Test
	void extractExplainRequestDefaultsNullFormatAndParsesInferFlag() throws Exception {
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.getInt("query-timeout")).thenReturn(7);
		when(request.isParameterPresent("infer")).thenReturn(true);
		when(request.getParameter("infer")).thenReturn("false");
		when(request.getParameter("explain")).thenReturn("Optimized");
		when(request.getParameter("explain-format")).thenReturn(null);

		QueryEvaluator.ExplainRequest explainRequest = QueryEvaluator.INSTANCE.extractExplainRequest(request);

		assertThat(explainRequest.getIncludeInferred()).isFalse();
		assertThat(explainRequest.getQueryTimeoutSeconds()).isEqualTo(7);
		assertThat(explainRequest.getExplainFormatValue()).isEqualTo("text");
	}

	@Test
	void extractExplainRequestRejectsUnknownLevelsAndFormats() throws Exception {
		WorkbenchRequest levelRequest = mock(WorkbenchRequest.class);
		when(levelRequest.getParameter("queryLn")).thenReturn("SPARQL");
		when(levelRequest.getInt("query-timeout")).thenReturn(0);
		when(levelRequest.isParameterPresent("infer")).thenReturn(false);
		when(levelRequest.getParameter("explain")).thenReturn("Nope");

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.extractExplainRequest(levelRequest))
				.isInstanceOf(BadRequestException.class)
				.hasMessageContaining("Unknown explain level 'Nope'");

		WorkbenchRequest formatRequest = mock(WorkbenchRequest.class);
		when(formatRequest.getParameter("queryLn")).thenReturn("SPARQL");
		when(formatRequest.getInt("query-timeout")).thenReturn(0);
		when(formatRequest.isParameterPresent("infer")).thenReturn(false);
		when(formatRequest.getParameter("explain")).thenReturn("Optimized");
		when(formatRequest.getParameter("explain-format")).thenReturn("yaml");

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.extractExplainRequest(formatRequest))
				.isInstanceOf(BadRequestException.class)
				.hasMessageContaining("Unknown explain format 'yaml'");
	}

	@Test
	void explainRejectsRepositoriesWithoutExplainSupport() throws Exception {
		RepositoryConnection connection = mock(RepositoryConnection.class);
		Query query = mock(Query.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.getParameter("explain")).thenReturn("Optimized");
		when(request.getParameter("explain-format")).thenReturn("");
		when(request.getInt("query-timeout")).thenReturn(0);
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(connection.prepareQuery(QueryLanguage.SPARQL, "select * where { ?s ?p ?o }")).thenReturn(query);
		when(query.explain(Explanation.Level.Optimized))
				.thenThrow(new UnsupportedOperationException("unsupported"));

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.explain(connection, "select * where { ?s ?p ?o }", request))
				.isInstanceOf(BadRequestException.class)
				.hasMessage("Explain is not supported for this query or repository.");
	}

	@Test
	void graphQueriesRenderWorkbenchMetadataAndCountCookies() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o }";
		Statement statement = SimpleValueFactory.getInstance()
				.createStatement(
						SimpleValueFactory.getInstance().createIRI("urn:s"),
						SimpleValueFactory.getInstance().createIRI("urn:p"),
						SimpleValueFactory.getInstance().createLiteral("o"));
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(0);
		when(request.getInt("limit_query")).thenReturn(0);
		when(request.getInt("know_total")).thenReturn(0);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(request.getParameter("query-timeout")).thenReturn("");
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);
		when(graphQuery.evaluate()).thenReturn(new IteratingGraphQueryResult(Map.of(), List.of(statement)));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, queryText);

		verify(builder).transform("transformations", "graph.xsl");
		verify(builder).start("subject", "predicate", "object");
		verify(builder).metadata("query-text", queryText);
		verify(builder).metadata("infer", false);
		verify(builder).metadata("query-timeout", 0);
		verify(builder).result(statement.getSubject(), statement.getPredicate(), statement.getObject(),
				statement.getContext());
		verify(builder).end();
		verify(cookies).addTotalResultCountCookie(request, response, 1);
	}

	@Test
	void graphQueriesCanBeStreamedThroughRioWriters() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o }";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(true);
		when(request.isParameterPresent("download_limit")).thenReturn(false);
		when(request.getParameter("Accept")).thenReturn("text/turtle");
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(0);
		when(request.getInt("limit_query")).thenReturn(2);
		when(request.getInt("know_total")).thenReturn(0);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, null);

		verify(graphQuery).evaluate(any(org.eclipse.rdf4j.rio.RDFWriter.class));
		verify(builder, never()).transform(any(), any());
	}

	@Test
	void graphQueriesPageResultsAndCanSkipWorkbenchMetadata() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o }";
		Statement first = SimpleValueFactory.getInstance()
				.createStatement(
						SimpleValueFactory.getInstance().createIRI("urn:first"),
						SimpleValueFactory.getInstance().createIRI("urn:p"),
						SimpleValueFactory.getInstance().createLiteral("one"));
		Statement second = SimpleValueFactory.getInstance()
				.createStatement(
						SimpleValueFactory.getInstance().createIRI("urn:second"),
						SimpleValueFactory.getInstance().createIRI("urn:p"),
						SimpleValueFactory.getInstance().createLiteral("two"));
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(1);
		when(request.getInt("limit_query")).thenReturn(1);
		when(request.getInt("know_total")).thenReturn(0);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(request.getParameter("query-timeout")).thenReturn("");
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);
		when(graphQuery.evaluate()).thenReturn(new IteratingGraphQueryResult(Map.of(), List.of(first, second)));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, null);

		verify(cookies).addTotalResultCountCookie(request, response, 2);
		verify(builder, never()).metadata(any(), any());
		verify(builder, times(1)).result(any(), any(), any(), any());
	}

	@Test
	void graphQueriesRenderExplicitInferAndTimeoutMetadata() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o }";
		Statement statement = SimpleValueFactory.getInstance()
				.createStatement(
						SimpleValueFactory.getInstance().createIRI("urn:s"),
						SimpleValueFactory.getInstance().createIRI("urn:p"),
						SimpleValueFactory.getInstance().createLiteral("o"));
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("infer")).thenReturn(true);
		when(request.getParameter("infer")).thenReturn("true");
		when(request.getInt("offset")).thenReturn(0);
		when(request.getInt("limit_query")).thenReturn(0);
		when(request.getInt("know_total")).thenReturn(0);
		when(request.getInt("query-timeout")).thenReturn(7);
		when(request.getParameter("query-timeout")).thenReturn("7");
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);
		when(graphQuery.evaluate()).thenReturn(new IteratingGraphQueryResult(Map.of(), List.of(statement)));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, queryText);

		verify(builder).metadata("query-text", queryText);
		verify(builder).metadata("infer", true);
		verify(builder).metadata("query-timeout", "7");
	}

	@Test
	void booleanQueriesUseLimitQueryFallbackAndBooleanTemplate() throws Exception {
		String queryText = "ask { ?s ?p ?o }";
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		BooleanQuery booleanQuery = mock(BooleanQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(true);
		when(request.isParameterPresent("download_limit")).thenReturn(false);
		when(request.getParameter("Accept")).thenReturn("application/sparql-results+json");
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(0);
		when(request.getInt("limit_query")).thenReturn(5);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(booleanQuery);
		when(booleanQuery.evaluate()).thenReturn(true);

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, null);

		verify(builder).transform("transformations", "boolean.xsl");
		verify(builder).startBoolean();
		verify(builder).bool(true);
		verify(builder).endBoolean();
	}

	@Test
	void unknownQueryTypesFailFast() throws Exception {
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		Query query = mock(Query.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(0);
		when(request.getInt("limit_query")).thenReturn(0);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(connection.prepareQuery(QueryLanguage.SPARQL, "describe ?s where { ?s ?p ?o }")).thenReturn(query);

		assertThatThrownBy(() -> QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response,
				new ByteArrayOutputStream(), "transformations", connection, "describe ?s where { ?s ?p ?o }", request,
				cookies, null))
						.isInstanceOf(BadRequestException.class)
						.hasMessageContaining("Unknown query type:");
	}

	@Test
	void extractExplainRequestDefaultsMissingInferAndBlankFormatToText() throws Exception {
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.getParameter("explain")).thenReturn("Optimized");
		when(request.getParameter("explain-format")).thenReturn(" ");
		when(request.getInt("query-timeout")).thenReturn(3);
		when(request.isParameterPresent("infer")).thenReturn(false);

		QueryEvaluator.ExplainRequest explainRequest = QueryEvaluator.INSTANCE.extractExplainRequest(request);

		org.assertj.core.api.Assertions.assertThat(explainRequest.getIncludeInferred()).isNull();
		org.assertj.core.api.Assertions.assertThat(explainRequest.getExplainFormatValue()).isEqualTo("text");
	}

	@Test
	void graphQueriesReuseKnownTotalsWhenQueryAlreadyContainsPaging() throws Exception {
		String queryText = "construct { ?s ?p ?o } where { ?s ?p ?o } limit 2";
		Statement statement = SimpleValueFactory.getInstance()
				.createStatement(
						SimpleValueFactory.getInstance().createIRI("urn:s"),
						SimpleValueFactory.getInstance().createIRI("urn:p"),
						SimpleValueFactory.getInstance().createLiteral("o"));
		TupleResultBuilder builder = mock(TupleResultBuilder.class);
		HttpServletResponse response = mock(HttpServletResponse.class);
		RepositoryConnection connection = mock(RepositoryConnection.class);
		CookieHandler cookies = mock(CookieHandler.class);
		WorkbenchRequest request = mock(WorkbenchRequest.class);
		GraphQuery graphQuery = mock(GraphQuery.class);

		when(request.getParameter("queryLn")).thenReturn("SPARQL");
		when(request.isParameterPresent("explain")).thenReturn(false);
		when(request.isParameterPresent("Accept")).thenReturn(false);
		when(request.isParameterPresent("infer")).thenReturn(false);
		when(request.getInt("offset")).thenReturn(1);
		when(request.getInt("limit_query")).thenReturn(2);
		when(request.getInt("know_total")).thenReturn(5);
		when(request.getInt("query-timeout")).thenReturn(0);
		when(request.getParameter("query-timeout")).thenReturn("");
		when(connection.prepareQuery(QueryLanguage.SPARQL, queryText)).thenReturn(graphQuery);
		when(graphQuery.evaluate()).thenReturn(new IteratingGraphQueryResult(Map.of(), List.of(statement)));

		QueryEvaluator.INSTANCE.extractQueryAndEvaluate(builder, response, new ByteArrayOutputStream(),
				"transformations", connection, queryText, request, cookies, null);

		verify(cookies).addTotalResultCountCookie(request, response, 5);
		verify(connection, times(2)).prepareQuery(QueryLanguage.SPARQL, queryText);
		verify(builder, never()).metadata(any(), any());
	}
}
