/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.rdf4j.query.algebra.And;
import org.eclipse.rdf4j.query.algebra.Extension;
import org.eclipse.rdf4j.query.algebra.ExtensionElem;
import org.eclipse.rdf4j.query.algebra.Group;
import org.eclipse.rdf4j.query.algebra.GroupElem;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;

final class LmdbTupleExprFacts {

	private LmdbTupleExprFacts() {
	}

	static List<ValueExpr> splitAnd(ValueExpr valueExpr) {
		List<ValueExpr> conjuncts = new ArrayList<>();
		collectConjuncts(valueExpr, conjuncts);
		return conjuncts;
	}

	private static void collectConjuncts(ValueExpr valueExpr, List<ValueExpr> conjuncts) {
		if (valueExpr instanceof And and) {
			collectConjuncts(and.getLeftArg(), conjuncts);
			collectConjuncts(and.getRightArg(), conjuncts);
		} else {
			conjuncts.add(valueExpr);
		}
	}

	static ValueExpr combineAnd(List<ValueExpr> conjuncts) {
		if (conjuncts.isEmpty()) {
			throw new IllegalArgumentException("conjuncts must not be empty");
		}
		Iterator<ValueExpr> iterator = conjuncts.iterator();
		ValueExpr result = iterator.next();
		while (iterator.hasNext()) {
			result = new And(result, iterator.next());
		}
		return result;
	}

	static void replaceVars(ValueExpr valueExpr, String oldName, String newName) {
		valueExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Var node) {
				if (!node.hasValue() && oldName.equals(node.getName())) {
					node.replaceWith(Var.of(newName));
				}
			}
		});
	}

	static List<TupleExpr> allUnionBranches(Union union) {
		List<TupleExpr> branches = new ArrayList<>();
		collectUnionBranches(union, branches);
		return branches;
	}

	private static void collectUnionBranches(TupleExpr tupleExpr, List<TupleExpr> branches) {
		if (tupleExpr instanceof Union union) {
			collectUnionBranches(union.getLeftArg(), branches);
			collectUnionBranches(union.getRightArg(), branches);
		} else {
			branches.add(tupleExpr);
		}
	}

	static void anonymizeDeadSingleUseVars(TupleExpr tupleExpr, Set<String> liveVars) {
		Map<String, Integer> occurrences = new HashMap<>();
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(Var node) {
				if (!node.hasValue() && !liveVars.contains(node.getName())) {
					occurrences.merge(node.getName(), 1, Integer::sum);
				}
			}
		});
		AtomicInteger counter = new AtomicInteger();
		tupleExpr.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			public void meet(StatementPattern node) {
				anonymizeSingleUseVar(node.getSubjectVar(), occurrences, counter);
				anonymizeSingleUseVar(node.getObjectVar(), occurrences, counter);
			}
		});
	}

	private static void anonymizeSingleUseVar(Var var, Map<String, Integer> occurrences, AtomicInteger counter) {
		if (var != null && !var.hasValue() && occurrences.getOrDefault(var.getName(), 0) == 1) {
			var.replaceWith(Var.of("_anon_lmdb_eligibility_" + counter.incrementAndGet(), true));
		}
	}

	static ExtensionElem findExtensionElem(Extension extension, String name) {
		return extension.getElements()
				.stream()
				.filter(element -> name.equals(element.getName()))
				.findFirst()
				.orElse(null);
	}

	static GroupElem findGroupElem(Group group, String name) {
		return group.getGroupElements()
				.stream()
				.filter(element -> name.equals(element.getName()))
				.findFirst()
				.orElse(null);
	}
}
