/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.frontier;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class FrontierCenterIndexTest {

	@Test
	void estimatesConditionalRowsFromTheSameCoordinatedCenters(@TempDir Path directory) throws Exception {
		try (CenterFixture fixture = centerFixture(directory,
				new long[] { 1L, 1L, 2L, 2L },
				new long[] { 7L, 8L, 7L, 8L },
				new long[] { 10L, 20L, 30L, 40L },
				new long[] { 7L, 7L, 8L, 8L },
				new int[] { 0, 2, 1, 3 })) {
			FrontierJoinEstimate estimate = fixture.index.estimateConditionalJoin(subjectJoin(), 3.0d);

			assertEquals(FrontierFallbackReason.NONE, estimate.fallbackReason());
			assertEquals(1.0d, estimate.pointRows(), 0.0d,
					"one right row per sampled left center must remain one row per invocation");
		}
	}

	@Test
	void rejectsPredicatePostingOrdinalsThatAreNotStrictlySorted(@TempDir Path directory) throws Exception {
		try (CenterFixture fixture = centerFixture(directory, new long[] { 7L, 7L, 8L }, new int[] { 1, 0, 2 })) {
			assertThrows(IOException.class, () -> fixture.index.estimateJoin(subjectJoin(), 9.0d));
		}
	}

	@Test
	void rejectsPredicatePostingsThatDisagreeWithStatementRows(@TempDir Path directory) throws Exception {
		try (CenterFixture fixture = centerFixture(directory, new long[] { 7L, 7L, 8L }, new int[] { 0, 2, 1 })) {
			assertThrows(IOException.class, () -> fixture.index.estimateJoin(subjectJoin(), 9.0d));
		}
	}

	private static CenterFixture centerFixture(Path directory, long[] postingPredicates, int[] postingOrdinals)
			throws Exception {
		return centerFixture(directory,
				new long[] { 1L, 2L, 3L },
				new long[] { 7L, 7L, 8L },
				new long[] { 10L, 20L, 30L },
				postingPredicates,
				postingOrdinals);
	}

	private static CenterFixture centerFixture(Path directory, long[] subjects, long[] predicates, long[] objects,
			long[] postingPredicates, int[] postingOrdinals) throws Exception {
		int shardId = 500;
		Path path = directory.resolve("generation-1-shard-00500.fs2s");
		int rowCount = subjects.length;
		try (FrontierStatisticsShardWriter writer = new FrontierStatisticsShardWriter(
				path, 1L, shardId, 1L, 40L, rowCount)) {
			writer.addTermColumn(0, subjects, rowCount);
			writer.addTermColumn(1, predicates, rowCount);
			writer.addTermColumn(2, objects, rowCount);
			writer.addTermColumn(3, new long[rowCount], rowCount);
			writer.addTermColumn(4, postingPredicates, rowCount);
			writer.addUnsignedIntColumn(5, postingOrdinals, rowCount);
			writer.finish();
		}
		FrontierStatisticsShardDescriptor descriptor = new FrontierStatisticsShardDescriptor(
				shardId, FrontierStatisticsTier.JOIN_SAMPLES, true, path.getFileName().toString(),
				Files.size(path), rowCount, FrontierStatisticsShardKind.CENTER_SAMPLES,
				0L, 0, Long.MAX_VALUE, Long.MAX_VALUE);
		FrontierStatisticsManifest manifest = new FrontierStatisticsManifest(
				1L, -1L, 1L, 1L, 0L, 1L, 30L, List.of(descriptor));
		FrontierStatisticsShard shard = FrontierStatisticsShard.open(path);
		return new CenterFixture(shard, new FrontierCenterIndex(manifest, Map.of(shardId, shard), 1));
	}

	private static FrontierJoinProbe subjectJoin() {
		FrontierLeafProbe left = new FrontierLeafProbe(
				FrontierLeafProbe.EXPLICIT, FrontierLeafProbe.PREDICATE, 0L, 7L, 0L, 0L);
		FrontierLeafProbe right = new FrontierLeafProbe(
				FrontierLeafProbe.EXPLICIT, FrontierLeafProbe.PREDICATE, 0L, 8L, 0L, 0L);
		return new FrontierJoinProbe(left, 0, right, 0);
	}

	private record CenterFixture(FrontierStatisticsShard shard, FrontierCenterIndex index) implements AutoCloseable {

		@Override
		public void close() throws IOException {
			shard.close();
		}
	}
}
