/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import org.eclipse.rdf4j.model.Literal;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.BinaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.Distinct;
import org.eclipse.rdf4j.query.algebra.EmptySet;
import org.eclipse.rdf4j.query.algebra.Filter;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.LeftJoin;
import org.eclipse.rdf4j.query.algebra.Reduced;
import org.eclipse.rdf4j.query.algebra.SingletonSet;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Union;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.VariableScopeChange;
import org.eclipse.rdf4j.query.algebra.equivalence.CertificateStep;
import org.eclipse.rdf4j.query.algebra.equivalence.CheckOptions;
import org.eclipse.rdf4j.query.algebra.equivalence.ContextMode;
import org.eclipse.rdf4j.query.algebra.equivalence.ObservationMode;
import org.eclipse.rdf4j.query.algebra.equivalence.RuleId;

/**
 * Small independent certificate kernel that applies submitted root rewrites to complete RDF4J trees.
 *
 * <p>
 * This class deliberately is not a canonicalizer. Each accepted step checks one closed, theorem-backed rule and returns
 * the complete resulting tree. Unsupported shapes, nested paths, physical operator state, or failed side conditions
 * reject the certificate. The caller compares the final trees with {@link ExactTreeEquality}.
 * </p>
 */
public final class LocalCertificateReplayer {
	private static final Map<String, String> DEDUPLICATE = Map.of("multiplicity", "deduplicate");

	private final CheckOptions options;
	private final CertificateExpressionSafetyAnalyzer safety;

	public LocalCertificateReplayer(CheckOptions options) {
		this.options = Objects.requireNonNull(options, "options");
		this.safety = new CertificateExpressionSafetyAnalyzer(options);
	}

	/** Returns the complete rewritten tree, or {@code null} when any submitted step is invalid. */
	public TupleExpr replay(
			TupleExpr expression,
			ObservationMode observationMode,
			List<CertificateStep> expectedSteps) {
		Objects.requireNonNull(expression, "expression");
		Objects.requireNonNull(observationMode, "observationMode");
		Objects.requireNonNull(expectedSteps, "expectedSteps");
		if (observationMode != options.getObservationMode()) {
			return null;
		}

		TupleExpr current = expression.clone();
		for (CertificateStep step : expectedSteps) {
			if (!validEnvelope(step)) {
				return null;
			}
			current = apply(current, step.getRule());
			if (current == null) {
				return null;
			}
		}
		return current;
	}

	private boolean validEnvelope(CertificateStep step) {
		return step != null
				&& "$".equals(step.getNodePath())
				&& CertifiedRuleRegistry.permits(step.getRule(), options)
				&& expectedParameters(step.getRule()).equals(step.getParameters())
				&& !step.getResultingSubtree().isBlank();
	}

	private TupleExpr apply(TupleExpr expression, RuleId rule) {
		if (!hasDefaultPhysicalState(expression) || hasScopeBoundary(expression)) {
			return null;
		}
		return switch (rule) {
		case JOIN_UNIT_IDENTITY -> joinUnit(expression);
		case UNION_EMPTY_IDENTITY -> unionEmpty(expression);
		case LEFT_JOIN_EMPTY_LEFT -> leftJoinEmptyLeft(expression);
		case LEFT_JOIN_EMPTY_RIGHT -> leftJoinEmptyRight(expression);
		case LEFT_JOIN_UNIT_RIGHT -> leftJoinUnitRight(expression);
		case MINUS_EMPTY_LEFT -> minusEmptyLeft(expression);
		case MINUS_EMPTY_RIGHT -> minusEmptyRight(expression);
		case FILTER_TRUE_IDENTITY -> filterTrue(expression);
		case DISTINCT_IDEMPOTENT -> distinctIdempotent(expression);
		case UNION_IDEMPOTENT_UNDER_SET_OBSERVATION -> unionIdempotent(expression);
		case DISTINCT_OR_SET_OBSERVATION -> distinctHidden(expression);
		case REDUCED_HIDDEN_BY_SET_OBSERVATION -> reducedHidden(expression);
		case VALUES_EMPTY -> valuesEmpty(expression);
		case VALUES_UNIT -> valuesUnit(expression);
		case STRUCTURAL_EQUALITY, JOIN_ASSOCIATIVE, JOIN_COMMUTATIVE, JOIN_EMPTY_ANNIHILATOR, UNION_ASSOCIATIVE, UNION_COMMUTATIVE, FILTER_DISTRIBUTES_OVER_UNION, FILTER_PUSHED_TO_JOIN_LEFT, FILTER_PUSHED_TO_JOIN_RIGHT, FILTER_PUSHED_TO_LEFT_JOIN_LEFT, FILTER_FALSE_EMPTY, LEFT_JOIN_DISTRIBUTES_OVER_LEFT_UNION, MINUS_UNIT_RIGHT, MINUS_DISJOINT_DOMAINS, MINUS_DISTRIBUTES_OVER_LEFT_UNION, MINUS_RIGHT_UNION_TO_CHAIN, MINUS_CHAIN_REORDER, PROJECTION_ELEMENT_ORDER_IGNORED -> null;
		};
	}

	private TupleExpr joinUnit(TupleExpr expression) {
		if (expression.getClass() != Join.class) {
			return null;
		}
		Join join = (Join) expression;
		if (!safety.isReorderSafe(join.getRightArg())) {
			return null;
		}
		if (isUnit(join.getLeftArg())) {
			return join.getRightArg().clone();
		}
		return isUnit(join.getRightArg()) ? join.getLeftArg().clone() : null;
	}

	private static TupleExpr unionEmpty(TupleExpr expression) {
		if (expression.getClass() != Union.class) {
			return null;
		}
		Union union = (Union) expression;
		if (isEmpty(union.getLeftArg())) {
			return union.getRightArg().clone();
		}
		return isEmpty(union.getRightArg()) ? union.getLeftArg().clone() : null;
	}

	private TupleExpr leftJoinEmptyLeft(TupleExpr expression) {
		LeftJoin leftJoin = safeLeftJoin(expression);
		return leftJoin != null && isEmpty(leftJoin.getLeftArg()) ? new EmptySet() : null;
	}

	private TupleExpr leftJoinEmptyRight(TupleExpr expression) {
		LeftJoin leftJoin = safeLeftJoin(expression);
		return leftJoin != null && isEmpty(leftJoin.getRightArg()) ? leftJoin.getLeftArg().clone() : null;
	}

	private TupleExpr leftJoinUnitRight(TupleExpr expression) {
		LeftJoin leftJoin = safeLeftJoin(expression);
		return leftJoin != null && isUnit(leftJoin.getRightArg()) ? leftJoin.getLeftArg().clone() : null;
	}

	private LeftJoin safeLeftJoin(TupleExpr expression) {
		if (expression.getClass() != LeftJoin.class) {
			return null;
		}
		LeftJoin leftJoin = (LeftJoin) expression;
		boolean conditionSafe = !leftJoin.hasCondition() || safety.isRelocatable(leftJoin.getCondition());
		return conditionSafe && safety.isReorderSafe(leftJoin.getRightArg()) ? leftJoin : null;
	}

	private TupleExpr minusEmptyLeft(TupleExpr expression) {
		if (expression.getClass() != Difference.class) {
			return null;
		}
		Difference difference = (Difference) expression;
		return isEmpty(difference.getLeftArg()) && safety.isReorderSafe(difference.getRightArg())
				? new EmptySet()
				: null;
	}

	private static TupleExpr minusEmptyRight(TupleExpr expression) {
		if (expression.getClass() != Difference.class) {
			return null;
		}
		Difference difference = (Difference) expression;
		return isEmpty(difference.getRightArg()) ? difference.getLeftArg().clone() : null;
	}

	private TupleExpr filterTrue(TupleExpr expression) {
		if (expression.getClass() != Filter.class) {
			return null;
		}
		Filter filter = (Filter) expression;
		return safety.isRelocatable(filter.getCondition()) && isBooleanTrue(filter.getCondition())
				? filter.getArg().clone()
				: null;
	}

	private static TupleExpr distinctIdempotent(TupleExpr expression) {
		if (expression.getClass() != Distinct.class) {
			return null;
		}
		TupleExpr argument = ((Distinct) expression).getArg();
		return argument.getClass() == Distinct.class ? argument.clone() : null;
	}

	private TupleExpr unionIdempotent(TupleExpr expression) {
		if (expression.getClass() != Union.class || !safety.isReorderSafe(expression)) {
			return null;
		}
		Union union = (Union) expression;
		return ExactTreeEquality.equal(union.getLeftArg(), union.getRightArg()) ? union.getLeftArg().clone() : null;
	}

	private static TupleExpr distinctHidden(TupleExpr expression) {
		return expression.getClass() == Distinct.class ? ((Distinct) expression).getArg().clone() : null;
	}

	private static TupleExpr reducedHidden(TupleExpr expression) {
		return expression.getClass() == Reduced.class ? ((Reduced) expression).getArg().clone() : null;
	}

	private static TupleExpr valuesEmpty(TupleExpr expression) {
		BindingSetAssignment assignment = assignment(expression);
		if (assignment == null || !(assignment.getBindingSets()instanceof Collection<?> rows) || !rows.isEmpty()) {
			return null;
		}
		return new EmptySet();
	}

	private TupleExpr valuesUnit(TupleExpr expression) {
		BindingSetAssignment assignment = assignment(expression);
		if (assignment == null || !(assignment.getBindingSets()instanceof Collection<?> rows)) {
			return null;
		}
		int emptyRows = 0;
		for (BindingSet row : assignment.getBindingSets()) {
			if (row.iterator().hasNext()) {
				return null;
			}
			emptyRows++;
		}
		boolean setLike = options.getObservationMode() == ObservationMode.SET
				|| options.getObservationMode() == ObservationMode.ASK;
		if (emptyRows == 0 || (!setLike && emptyRows != 1)) {
			return null;
		}
		return new SingletonSet();
	}

	private static BindingSetAssignment assignment(TupleExpr expression) {
		return expression.getClass() == BindingSetAssignment.class ? (BindingSetAssignment) expression : null;
	}

	private static boolean isEmpty(TupleExpr expression) {
		return expression.getClass() == EmptySet.class && !hasScopeBoundary(expression);
	}

	private static boolean isUnit(TupleExpr expression) {
		return expression.getClass() == SingletonSet.class && !hasScopeBoundary(expression);
	}

	private static boolean hasDefaultPhysicalState(TupleExpr expression) {
		if (expression instanceof BinaryTupleOperator binary && binary.getAlgorithmName() != null) {
			return false;
		}
		return !(expression instanceof Join join) || (!join.isMergeJoin() && !join.isCacheable());
	}

	private static boolean hasScopeBoundary(Object expression) {
		return expression instanceof VariableScopeChange scopeChange && scopeChange.isVariableScopeChange();
	}

	private static boolean isBooleanTrue(Object expression) {
		if (!(expression instanceof ValueConstant constant) || !(constant.getValue()instanceof Literal literal)) {
			return false;
		}
		if (!XSD.BOOLEAN.equals(literal.getDatatype())) {
			return false;
		}
		try {
			return literal.booleanValue();
		} catch (IllegalArgumentException invalidLexicalForm) {
			return false;
		}
	}

	private static Map<String, String> expectedParameters(RuleId rule) {
		return switch (rule) {
		case UNION_IDEMPOTENT_UNDER_SET_OBSERVATION, DISTINCT_IDEMPOTENT -> DEDUPLICATE;
		default -> Map.of();
		};
	}
}
