/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence.internal;

import java.util.Collection;
import java.util.Optional;
import java.util.Set;

import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.algebra.BindingSetAssignment;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.ValueConstant;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.equivalence.EvaluationCase;
import org.eclipse.rdf4j.query.algebra.equivalence.SemanticsTarget;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor;

/** Validates that a tree has a semantic contract under the selected profile. */
public final class SemanticsValidator {
	private static final String RDF4J_ALGEBRA_PACKAGE = "org.eclipse.rdf4j.query.algebra";

	private static final Set<String> SPARQL_12_ONLY = Set.of(
			"AnnotationTripleRef",
			"HasLang",
			"HasLangDir",
			"IsTriple",
			"LangDir",
			"Lateral",
			"ReifiedTripleRef",
			"StrLangDir",
			"TripleComponent",
			"TripleRef",
			"ValueExprTripleRef");

	private static final Set<String> RDF4J_RUNTIME_ONLY = Set.of(
			"AggregateFunctionCall",
			"DescribeOperator",
			"Intersection",
			"TupleFunctionCall");

	public Validation validate(QueryModelNode root, SemanticsTarget target) {
		final String[] problem = { null };
		root.visit(new AbstractQueryModelVisitor<RuntimeException>() {
			@Override
			protected void meetNode(QueryModelNode node) {
				if (problem[0] != null) {
					return;
				}

				Package nodePackage = node.getClass().getPackage();
				String packageName = nodePackage == null ? "" : nodePackage.getName();
				boolean nativeRdf4j = RDF4J_ALGEBRA_PACKAGE.equals(packageName)
						|| packageName.startsWith(RDF4J_ALGEBRA_PACKAGE + ".");
				if (!nativeRdf4j) {
					problem[0] = "Application-defined algebra node has no registered semantic adapter: "
							+ node.getClass().getName();
					return;
				}
				if (!NativeAlgebraSchema.isRegistered(node.getClass())) {
					problem[0] = "Native RDF4J algebra node is not registered in the semantic schema: "
							+ node.getClass().getName();
					return;
				}

				String simpleName = node.getClass().getSimpleName();
				if (!target.isRuntimeTarget() && RDF4J_RUNTIME_ONLY.contains(simpleName)) {
					problem[0] = "RDF4J implementation-specific algebra node is outside the selected W3C profile: "
							+ node.getClass().getName();
					return;
				}
				if (!target.permitsSparql12Nodes() && SPARQL_12_ONLY.contains(simpleName)) {
					problem[0] = "SPARQL 1.2 algebra node is outside the selected SPARQL 1.1/shared profile: "
							+ node.getClass().getName();
					return;
				}
				if (node instanceof Var variable) {
					rejectValue(variable.getValue());
				}
				if (node instanceof ValueConstant constant) {
					rejectValue(constant.getValue());
				}
				if (node instanceof BindingSetAssignment assignment) {
					Iterable<BindingSet> rows = assignment.getBindingSets();
					if (rows == null) {
						// Evaluating such a node fails at precompile time, so no algebraic proof
						// about it can be checked against runtime behaviour.
						problem[0] = "BindingSetAssignment has no binding sets: evaluation would fail before "
								+ "producing a result";
					} else if (!(rows instanceof Collection<?>)) {
						problem[0] = "BindingSetAssignment rows are not materialized: certified replay must not "
								+ "consume a stateful or one-shot Iterable";
					} else {
						for (BindingSet row : rows) {
							for (String name : row.getBindingNames()) {
								if (problem[0] == null) {
									rejectValue(row.getValue(name));
								}
							}
						}
					}
				}
				node.visitChildren(this);
			}

			private void rejectValue(Value value) {
				Optional<String> reason = SparqlValueFeatures.unsupportedReason(value, target);
				if (reason.isPresent()) {
					problem[0] = reason.get();
				}
			}
		});
		return problem[0] == null ? Validation.supported() : Validation.unsupported(problem[0]);
	}

	public Validation validate(EvaluationCase evaluationCase, SemanticsTarget target) {
		for (Statement statement : evaluationCase.getStatements()) {
			Validation validation = validateValues(
					statement.getSubject(),
					statement.getPredicate(),
					statement.getObject(),
					statement.getContext(),
					target);
			if (!validation.isSupported()) {
				return validation;
			}
		}
		BindingSet bindings = evaluationCase.getInitialBindings();
		for (String name : bindings.getBindingNames()) {
			Optional<String> reason = SparqlValueFeatures.unsupportedReason(bindings.getValue(name), target);
			if (reason.isPresent()) {
				return Validation.unsupported(reason.get());
			}
		}
		return Validation.supported();
	}

	private static Validation validateValues(
			Value subject,
			Value predicate,
			Value object,
			Value context,
			SemanticsTarget target) {
		for (Value value : new Value[] { subject, predicate, object, context }) {
			Optional<String> reason = SparqlValueFeatures.unsupportedReason(value, target);
			if (reason.isPresent()) {
				return Validation.unsupported(reason.get());
			}
		}
		return Validation.supported();
	}

	public static final class Validation {
		private final boolean supported;
		private final String reason;

		private Validation(boolean supported, String reason) {
			this.supported = supported;
			this.reason = reason;
		}

		public static Validation supported() {
			return new Validation(true, "");
		}

		public static Validation unsupported(String reason) {
			return new Validation(false, reason);
		}

		public boolean isSupported() {
			return supported;
		}

		public String getReason() {
			return reason;
		}
	}
}
