/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.lenient;

import java.util.List;
import java.util.stream.Collectors;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.sail.lmdb.config.FrontierEstimatorMode;
import org.eclipse.rdf4j.sail.lmdb.estimation.QuadSnapshotIdentity;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierFallbackReason;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierLeafEstimate;
import org.eclipse.rdf4j.sail.lmdb.frontier.FrontierLeafProbe;
import org.eclipse.rdf4j.sail.lmdb.frontier.LmdbStatisticsService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * Review reproducers for how the storage evidence source behaves when the Frontier service exists but cannot answer
 * (cold start / stale generation) and in SHADOW mode.
 */
@ExtendWith(MockitoExtension.class)
class LmdbStorageEvidenceReviewReproTest {

	private static final SimpleValueFactory VF = SimpleValueFactory.getInstance();
	private static final IRI PREDICATE = VF.createIRI("urn:review:p");
	private static final QuadSnapshotIdentity IDENTITY = new QuadSnapshotIdentity(3L, 5L, 8L);
	private static final double STORAGE_ROWS = 250_000.0d;

	@Mock
	private LmdbStatementPatternCardinalitySource cardinalities;
	@Mock
	private ValueStore valueStore;
	@Mock
	private LmdbStatisticsService statistics;

	/**
	 * Candidate 10: SHADOW is documented as observation-only, yet merely having a statistics service in SHADOW mode
	 * removes the storage-summary and exact-count candidates that OFF mode provides. SHADOW therefore changes plans.
	 */
	@Test
	void shadowModeKeepsTheSameStorageEvidenceAsOffMode() throws Exception {
		StatementPattern pattern = pattern();
		lenient().when(cardinalities.estimateForPlanning(pattern)).thenReturn(STORAGE_ROWS);
		lenient().when(cardinalities.estimateExact(pattern)).thenReturn(STORAGE_ROWS);
		lenient().when(valueStore.getId(PREDICATE)).thenReturn(7L);
		lenient().when(statistics.estimateLeafCurrent(any(FrontierLeafProbe.class)))
				.thenReturn(new FrontierLeafEstimate(4_000.0d, 3_000.0d, 5_000.0d, 0.9d, "frontier-v2-omni",
						FrontierFallbackReason.NONE));

		LmdbStorageEstimatorEvidence off = new LmdbStorageEstimatorEvidence(valueStore, cardinalities, null, null,
				null, null, null, null, FrontierEstimatorMode.OFF);
		LmdbStorageEstimatorEvidence shadow = new LmdbStorageEstimatorEvidence(valueStore, cardinalities, null, null,
				null, null, null, statistics, FrontierEstimatorMode.SHADOW);

		EstimateContext context = EstimateContext.root(pattern, IDENTITY, 1L);
		List<String> offKinds = kinds(off.leafCandidates(pattern, context));
		List<String> shadowKinds = kinds(shadow.leafCandidates(pattern, context));
		boolean offExact = off.exactCandidate(pattern, context).isPresent();
		boolean shadowExact = shadow.exactCandidate(pattern, context).isPresent();
		System.out.println("[review-f6] OFF candidates=" + offKinds + " exact=" + offExact
				+ " | SHADOW candidates=" + shadowKinds + " exact=" + shadowExact);
		assertEquals(offKinds, shadowKinds, "SHADOW must not remove planner evidence that OFF mode provides");
		assertEquals(offExact, shadowExact, "SHADOW must not remove the exact storage candidate");
	}

	/**
	 * Cold start (already verified end-to-end on datagovbe): AUTHORITATIVE with a service that has no generation yet.
	 * The exact/B-tree cardinality source is available but suppressed, so the pattern has no row evidence at all and
	 * the caller falls back to its optimistic default.
	 */
	@Test
	void authoritativeWithoutGenerationStillOffersCheapStorageEvidence() throws Exception {
		StatementPattern pattern = pattern();
		lenient().when(cardinalities.estimateForPlanning(pattern)).thenReturn(STORAGE_ROWS);
		lenient().when(cardinalities.estimateExact(pattern)).thenReturn(STORAGE_ROWS);
		lenient().when(valueStore.getId(PREDICATE)).thenReturn(7L);
		lenient().when(statistics.estimateLeafCurrent(any(FrontierLeafProbe.class)))
				.thenReturn(new FrontierLeafEstimate(1.0d, 0.0d, Double.MAX_VALUE, 0.0d, "frontier-v2-unavailable",
						FrontierFallbackReason.NO_GENERATION));

		LmdbStorageEstimatorEvidence authoritative = new LmdbStorageEstimatorEvidence(valueStore, cardinalities,
				null, null, null, null, null, statistics, FrontierEstimatorMode.AUTHORITATIVE);
		EstimateContext context = EstimateContext.root(pattern, IDENTITY, 1L);
		List<EstimateCandidate> candidates = authoritative.leafCandidates(pattern, context);
		boolean exact = authoritative.exactCandidate(pattern, context).isPresent();
		System.out.println("[review-f6] AUTHORITATIVE/no-generation candidates=" + kinds(candidates)
				+ " exact=" + exact);
		assertTrue(!candidates.isEmpty() || exact,
				"with no Frontier generation, the " + STORAGE_ROWS
						+ "-row storage count must remain available instead of leaving the planner with no evidence");
	}

	private static List<String> kinds(List<EstimateCandidate> candidates) {
		return candidates.stream()
				.map(candidate -> candidate.kind() + ":" + candidate.estimate().rows())
				.collect(Collectors.toList());
	}

	private static StatementPattern pattern() {
		return new StatementPattern(new Var("s"), new Var("predicate", PREDICATE), new Var("o"));
	}
}
