PREFIX dc1: <http://purl.org/dc/elements/1.1/>
PREFIX dc2: <http://purl.org/dc/elements/1.1/>
PREFIX dc3: <http://purl.org/dc/elements/1.1/>
PREFIX dc4: <http://purl.org/dc/elements/1.1/>
PREFIX dc5: <http://purl.org/dc/elements/1.1/>
PREFIX dc6: <http://purl.org/dc/elements/1.1/>
PREFIX dc7: <http://purl.org/dc/elements/1.1/>
PREFIX dc8: <http://purl.org/dc/elements/1.1/>
PREFIX dc9: <http://purl.org/dc/elements/1.1/>
PREFIX dc10: <http://purl.org/dc/elements/1.1/>
PREFIX dc11: <http://purl.org/dc/elements/1.1/>
PREFIX dc12: <http://purl.org/dc/elements/1.1/>
PREFIX dc13: <http://purl.org/dc/elements/1.1/>
PREFIX dc14: <http://purl.org/dc/elements/1.1/>
PREFIX dc15: <http://purl.org/dc/elements/1.1/>
PREFIX dc16: <http://purl.org/dc/elements/1.1/>
PREFIX dc17: <http://purl.org/dc/elements/1.1/>
PREFIX dc18: <http://purl.org/dc/elements/1.1/>
PREFIX dc19: <http://purl.org/dc/elements/1.1/>
PREFIX dc20: <http://purl.org/dc/elements/1.1/>
PREFIX dc21: <http://purl.org/dc/elements/1.1/>
PREFIX dc22: <http://purl.org/dc/elements/1.1/>
PREFIX dc23: <http://purl.org/dc/elements/1.1/>
PREFIX dc24: <http://purl.org/dc/elements/1.1/>
PREFIX dc25: <http://purl.org/dc/elements/1.1/>
PREFIX dc26: <http://purl.org/dc/elements/1.1/>
PREFIX dc27: <http://purl.org/dc/elements/1.1/>
PREFIX dc28: <http://purl.org/dc/elements/1.1/>
PREFIX dc29: <http://purl.org/dc/elements/1.1/>
PREFIX dc30: <http://purl.org/dc/elements/1.1/>
PREFIX dc31: <http://purl.org/dc/elements/1.1/>
PREFIX dc32: <http://purl.org/dc/elements/1.1/>
PREFIX dc33: <http://purl.org/dc/elements/1.1/>
PREFIX dc34: <http://purl.org/dc/elements/1.1/>
PREFIX dc35: <http://purl.org/dc/elements/1.1/>
PREFIX dc36: <http://purl.org/dc/elements/1.1/>
PREFIX dc37: <http://purl.org/dc/elements/1.1/>
PREFIX dc38: <http://purl.org/dc/elements/1.1/>
PREFIX dc39: <http://purl.org/dc/elements/1.1/>
PREFIX dc40: <http://purl.org/dc/elements/1.1/>
PREFIX dc41: <http://purl.org/dc/elements/1.1/>
PREFIX dc42: <http://purl.org/dc/elements/1.1/>
PREFIX dc43: <http://purl.org/dc/elements/1.1/>
PREFIX dc44: <http://purl.org/dc/elements/1.1/>
PREFIX dc45: <http://purl.org/dc/elements/1.1/>
PREFIX dc46: <http://purl.org/dc/elements/1.1/>
PREFIX dc47: <http://purl.org/dc/elements/1.1/>
PREFIX dc48: <http://purl.org/dc/elements/1.1/>
PREFIX dc49: <http://purl.org/dc/elements/1.1/>

select * where {?s ?p ?o}
