/*******************************************************************************
 * Copyright (c) 2020 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.helpers;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import org.eclipse.rdf4j.common.annotation.Experimental;
import org.eclipse.rdf4j.common.annotation.InternalUseOnly;
import org.eclipse.rdf4j.query.algebra.BinaryTupleOperator;
import org.eclipse.rdf4j.query.algebra.QueryModelNode;
import org.eclipse.rdf4j.query.algebra.QueryRoot;
import org.eclipse.rdf4j.query.algebra.VariableScopeChange;
import org.eclipse.rdf4j.query.explanation.GenericPlanNode;

/**
 * Convert TupleExpr (QueryModelNode) to GenericPlanNode for the Query.explain(...) feature.
 */
@Experimental
@InternalUseOnly
public class QueryModelTreeToGenericPlanNode extends AbstractQueryModelVisitor<RuntimeException> {

	private static final String OPTIMIZER_MODE_PROPERTY = "rdf4j.optimizer.mode";
	private static final String HYBRID_OPTIMIZER_MODE = "hybrid";
	private static final String HYBRID_Q_ERROR_LIMIT_PROPERTY = "rdf4j.optimizer.hybrid.qerror.limit";
	private static final String HYBRID_Q_ERROR_LOG_LIMIT_PROPERTY = "rdf4j.optimizer.hybrid.qerror.log.limit";
	private static final int HYBRID_Q_ERROR_DEFAULT_LIMIT = 5;

	GenericPlanNode top = null;
	QueryModelNode topTupleExpr;
	ArrayDeque<GenericPlanNode> planNodes = new ArrayDeque<>();
	private final boolean includeResultSizeQError;
	private boolean qErrorLimitApplied;

	public QueryModelTreeToGenericPlanNode(QueryModelNode topTupleExpr) {
		if (topTupleExpr instanceof QueryRoot) {
			topTupleExpr = ((QueryRoot) topTupleExpr).getArg();
		}
		this.topTupleExpr = topTupleExpr;
		this.includeResultSizeQError = HYBRID_OPTIMIZER_MODE
				.equalsIgnoreCase(System.getProperty(OPTIMIZER_MODE_PROPERTY, ""));
	}

	public GenericPlanNode getGenericPlanNode() {
		if (includeResultSizeQError && !qErrorLimitApplied && top != null) {
			applyResultSizeQErrorLimit(top, getHybridQErrorLimit());
			qErrorLimitApplied = true;
		}
		return top;
	}

	@Override
	protected void meetNode(QueryModelNode node) {
		GenericPlanNode genericPlanNode = new GenericPlanNode(node.getSignature());
		genericPlanNode.setCostEstimate(node.getCostEstimate());
		genericPlanNode.setResultSizeEstimate(node.getResultSizeEstimate());
		genericPlanNode.setResultSizeActual(node.getResultSizeActual());
		if (includeResultSizeQError) {
			Double resultSizeQError = getResultSizeQError(genericPlanNode);
			if (resultSizeQError != null) {
				genericPlanNode.setResultSizeQError(resultSizeQError);
			}
		}
		if (node instanceof VariableScopeChange) {
			boolean newScope = ((VariableScopeChange) node).isVariableScopeChange();
			genericPlanNode.setNewScope(newScope);
		}

		if (node instanceof BinaryTupleOperator) {
			String algorithmName = ((BinaryTupleOperator) node).getAlgorithmName();
			genericPlanNode.setAlgorithm(algorithmName);
		}

		// convert from nanoseconds to milliseconds
		genericPlanNode.setTotalTimeActual(node.getTotalTimeNanosActual() / 1_000_000.0);

		if (node == topTupleExpr) {
			top = genericPlanNode;
		}

		if (!planNodes.isEmpty()) {
			GenericPlanNode genericParentNode = planNodes.getLast();
			genericParentNode.addPlans(genericPlanNode);
		}

		planNodes.addLast(genericPlanNode);
		super.meetNode(node);
		planNodes.removeLast();
	}

	private static Double getResultSizeQError(GenericPlanNode genericPlanNode) {
		Double estimated = genericPlanNode.getResultSizeEstimate();
		Long actualLong = genericPlanNode.getResultSizeActual();
		if (estimated == null || actualLong == null) {
			return null;
		}
		double actual = actualLong.doubleValue();
		if (estimated == 0.0 && actual == 0.0) {
			return 1.0;
		}
		if (estimated == 0.0 || actual == 0.0) {
			return Double.POSITIVE_INFINITY;
		}
		return Math.max(estimated / actual, actual / estimated);
	}

	private static int getHybridQErrorLimit() {
		String configuredLimit = getConfiguredQErrorLimit();
		if (configuredLimit == null || configuredLimit.isBlank()) {
			return HYBRID_Q_ERROR_DEFAULT_LIMIT;
		}
		try {
			int parsed = Integer.parseInt(configuredLimit.trim());
			return parsed >= 0 ? parsed : HYBRID_Q_ERROR_DEFAULT_LIMIT;
		} catch (NumberFormatException ignored) {
			return HYBRID_Q_ERROR_DEFAULT_LIMIT;
		}
	}

	private static String getConfiguredQErrorLimit() {
		String configuredLimit = System.getProperty(HYBRID_Q_ERROR_LIMIT_PROPERTY);
		if (configuredLimit == null || configuredLimit.isBlank()) {
			configuredLimit = System.getProperty(HYBRID_Q_ERROR_LOG_LIMIT_PROPERTY);
		}
		return configuredLimit;
	}

	private static void applyResultSizeQErrorLimit(GenericPlanNode root, int limit) {
		List<GenericPlanNode> qErrorNodes = new ArrayList<>();
		collectQErrorNodes(root, qErrorNodes);
		if (qErrorNodes.isEmpty()) {
			return;
		}
		if (limit == 0) {
			qErrorNodes.forEach(node -> node.setResultSizeQError(null));
			return;
		}
		if (qErrorNodes.size() <= limit) {
			return;
		}

		qErrorNodes.sort(Comparator.comparingDouble((GenericPlanNode node) -> node.getResultSizeQError()).reversed());
		for (int i = limit; i < qErrorNodes.size(); i++) {
			qErrorNodes.get(i).setResultSizeQError(null);
		}
	}

	private static void collectQErrorNodes(GenericPlanNode node, List<GenericPlanNode> qErrorNodes) {
		if (node.getResultSizeQError() != null) {
			qErrorNodes.add(node);
		}
		List<GenericPlanNode> children = node.getPlans();
		if (children != null) {
			children.forEach(child -> collectQErrorNodes(child, qErrorNodes));
		}
	}

}
