/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.Var;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.OptimizationGoal;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedCascadesPlanner;
import org.eclipse.rdf4j.query.algebra.evaluation.optimizer.cascades.packed.PackedPlanningResult;

/** Source-launchable completion-status probe for the frozen packed synthetic benchmark. */
public final class PackedCascadesSearchStatusCli {

	private PackedCascadesSearchStatusCli() {
	}

	public static void main(String[] args) throws Exception {
		Options options = Options.parse(args);
		PackedPlanningResult result = PackedCascadesPlanner.optimize(query(options.factors()), OptimizationGoal.root());
		String completionStatus = completionStatus(result);
		long retainedBytes = optionalLong(result, "retainedBytes", -1L);
		String json = "{\n"
				+ "  \"formatVersion\": 1,\n"
				+ "  \"kind\": \"packed-cascades-search-audit\",\n"
				+ "  \"factors\": " + options.factors() + ",\n"
				+ "  \"completionStatus\": \"" + completionStatus + "\",\n"
				+ "  \"exact\": " + "EXACT_COMPLETE".equals(completionStatus) + ",\n"
				+ "  \"workLimitReached\": " + result.workLimitReached() + ",\n"
				+ "  \"deadlineReached\": " + result.deadlineReached() + ",\n"
				+ "  \"retainedBytes\": " + retainedBytes + ",\n"
				+ "  \"outputRows\": " + result.outputRows() + ",\n"
				+ "  \"totalCost\": " + result.totalCost() + "\n"
				+ "}\n";
		Path parent = options.output().toAbsolutePath().getParent();
		if (parent != null) {
			Files.createDirectories(parent);
		}
		Files.writeString(options.output(), json, StandardCharsets.UTF_8);
		System.out.println("PACKED_CASCADES_SEARCH_AUDIT_OK " + options.output().toAbsolutePath());
	}

	private static String completionStatus(PackedPlanningResult result) throws ReflectiveOperationException {
		try {
			Method method = result.getClass().getMethod("completionStatus");
			return String.valueOf(method.invoke(result));
		} catch (NoSuchMethodException ignored) {
			if (result.workLimitReached()) {
				return "INCOMPLETE_WORK_LIMIT";
			}
			return result.deadlineReached() ? "INCOMPLETE_DEADLINE" : "EXACT_COMPLETE";
		} catch (InvocationTargetException failure) {
			throw unwrap(failure);
		}
	}

	private static long optionalLong(PackedPlanningResult result, String methodName, long fallback)
			throws ReflectiveOperationException {
		try {
			Method method = result.getClass().getMethod(methodName);
			return ((Number) method.invoke(result)).longValue();
		} catch (NoSuchMethodException ignored) {
			return fallback;
		} catch (InvocationTargetException failure) {
			throw unwrap(failure);
		}
	}

	private static ReflectiveOperationException unwrap(InvocationTargetException failure) {
		Throwable cause = failure.getCause();
		if (cause instanceof ReflectiveOperationException reflectionFailure) {
			return reflectionFailure;
		}
		return failure;
	}

	private static TupleExpr query(int factors) {
		SimpleValueFactory values = SimpleValueFactory.getInstance();
		TupleExpr root = pattern(values, 0);
		for (int ordinal = 1; ordinal < factors; ordinal++) {
			root = new Join(root, pattern(values, ordinal));
		}
		return root;
	}

	private static StatementPattern pattern(SimpleValueFactory values, int ordinal) {
		StatementPattern pattern = new StatementPattern(Var.of("chain" + ordinal),
				Var.of("predicate" + ordinal, values.createIRI("urn:predicate:" + ordinal)),
				Var.of("chain" + (ordinal + 1)));
		pattern.setResultSizeEstimate(10.0d * (ordinal + 1));
		return pattern;
	}

	private record Options(int factors, Path output) {

		private static Options parse(String[] args) {
			int factors = -1;
			Path output = null;
			for (int index = 0; index < args.length; index += 2) {
				if (index + 1 >= args.length || !args[index].startsWith("--")) {
					throw usage();
				}
				switch (args[index]) {
					case "--factors" -> factors = Integer.parseInt(args[index + 1]);
					case "--output" -> output = Path.of(args[index + 1]);
					default -> throw usage();
				}
			}
			if (factors <= 0 || output == null) {
				throw usage();
			}
			return new Options(factors, output);
		}

		private static IllegalArgumentException usage() {
			return new IllegalArgumentException("Usage: --factors POSITIVE_INTEGER --output FILE");
		}
	}
}
