/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.lmdb.join;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import org.eclipse.rdf4j.common.iteration.CloseableIteration;
import org.eclipse.rdf4j.common.iteration.LookAheadIteration;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.query.Binding;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryEvaluationException;
import org.eclipse.rdf4j.query.algebra.Difference;
import org.eclipse.rdf4j.query.algebra.evaluation.QueryEvaluationStep;
import org.eclipse.rdf4j.sail.lmdb.LmdbIdSet;
import org.eclipse.rdf4j.sail.lmdb.LmdbIdSets;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;

/**
 * Batch anti-join iterator for LMDB ID-capable MINUS right-hand BGPs.
 */
public final class LmdbIdDifferenceIterator extends LookAheadIteration<BindingSet> {

	private static final String MODE_MEMBERSHIP_DP = "membership-dp";
	private static final String MODE_ID_MEMBERSHIP_DP = "id-membership-dp";
	private static final int DEFAULT_MAX_MEMBERSHIP_ROWS = 4096;

	private final CloseableIteration<BindingSet> leftIter;
	private final BindingSet initialBindings;
	private final QueryEvaluationStep rightEvaluationStep;
	private final LmdbIdBatchQueryEvaluationStep batchRightEvaluationStep;
	private final Set<String> sharedVariables;
	private final Difference difference;
	private final int batchSize;
	private final int maxMembershipRows;

	private ArrayDeque<BindingSet> batchOutput;
	private long batchesActual;
	private long scalarFallbackBatchesActual;
	private long leftRowsActual;
	private long rightRowsActual;
	private long matchedRowsActual;
	private long outputRowsActual;
	private String actualMode = MODE_MEMBERSHIP_DP;
	private boolean membershipAttempted;
	private String membershipVariable;
	private LmdbIdBGPQueryEvaluationStep.IdMembership membershipSet;
	private String membershipFallbackReason;

	public static CloseableIteration<BindingSet> getInstance(QueryEvaluationStep left, BindingSet bindings,
			QueryEvaluationStep rightEvaluationStep, Set<String> sharedVariables, Difference difference) {
		return getInstance(left, bindings, rightEvaluationStep, sharedVariables, difference,
				DEFAULT_MAX_MEMBERSHIP_ROWS);
	}

	public static CloseableIteration<BindingSet> getInstance(QueryEvaluationStep left, BindingSet bindings,
			QueryEvaluationStep rightEvaluationStep, Set<String> sharedVariables, Difference difference,
			int maxMembershipRows) {
		CloseableIteration<BindingSet> leftIter = left.evaluate(bindings);
		if (leftIter == QueryEvaluationStep.EMPTY_ITERATION || sharedVariables.isEmpty()) {
			return leftIter;
		}
		return new LmdbIdDifferenceIterator(leftIter, bindings, rightEvaluationStep, sharedVariables, difference,
				maxMembershipRows);
	}

	private LmdbIdDifferenceIterator(CloseableIteration<BindingSet> leftIter, BindingSet initialBindings,
			QueryEvaluationStep rightEvaluationStep, Set<String> sharedVariables, Difference difference,
			int maxMembershipRows) {
		this.leftIter = leftIter;
		this.initialBindings = initialBindings;
		this.rightEvaluationStep = rightEvaluationStep;
		this.batchRightEvaluationStep = rightEvaluationStep instanceof LmdbIdBatchQueryEvaluationStep
				&& LmdbIdBatchJoinIterator.enabled()
						? (LmdbIdBatchQueryEvaluationStep) rightEvaluationStep
						: null;
		this.sharedVariables = sharedVariables;
		this.difference = difference;
		this.batchSize = LmdbIdBatchJoinIterator.configuredBatchSize();
		this.maxMembershipRows = maxMembershipRows;
		flushActualMetrics();
	}

	@Override
	protected BindingSet getNextElement() throws QueryEvaluationException {
		if (tryUseIdMembershipSet()) {
			return getNextMembershipElement();
		}
		if (batchRightEvaluationStep != null && batchRightEvaluationStep.batchResultIncludesAllInputBindings()) {
			return getNextBatchElement();
		}
		return getNextScalarElement();
	}

	private boolean tryUseIdMembershipSet() throws QueryEvaluationException {
		if (membershipAttempted) {
			return membershipSet != null;
		}
		membershipAttempted = true;
		if (!(rightEvaluationStep instanceof LmdbIdBGPQueryEvaluationStep)) {
			membershipFallbackReason = "right-not-lmdb-bgp";
			flushActualMetrics();
			return false;
		}
		if (sharedVariables.size() != 1) {
			membershipFallbackReason = "shared-variable-count";
			flushActualMetrics();
			return false;
		}
		String variable = sharedVariables.iterator().next();
		LmdbIdBGPQueryEvaluationStep.IdMembership collected = ((LmdbIdBGPQueryEvaluationStep) rightEvaluationStep)
				.collectExistingIds(initialBindings, variable, maxMembershipRows);
		if (collected == null || collected.oversized()) {
			membershipFallbackReason = "membership-unavailable";
			flushActualMetrics();
			return false;
		}
		membershipVariable = variable;
		membershipSet = collected;
		actualMode = MODE_ID_MEMBERSHIP_DP;
		rightRowsActual += collected.rowsScanned();
		flushActualMetrics();
		return true;
	}

	private BindingSet getNextMembershipElement() throws QueryEvaluationException {
		while (leftIter.hasNext()) {
			BindingSet left = leftIter.next();
			leftRowsActual++;
			Value value = left.getValue(membershipVariable);
			if (value == null) {
				outputRowsActual++;
				flushActualMetrics();
				return left;
			}
			long id = internalId(value);
			boolean matched = id == LmdbValue.UNKNOWN_ID ? matchesAnyRight(left) : membershipSet.contains(id);
			if (matched) {
				matchedRowsActual++;
			} else {
				outputRowsActual++;
				flushActualMetrics();
				return left;
			}
		}
		flushActualMetrics();
		return null;
	}

	private BindingSet getNextScalarElement() throws QueryEvaluationException {
		while (leftIter.hasNext()) {
			BindingSet left = leftIter.next();
			leftRowsActual++;
			if (!matchesAnyRight(left)) {
				outputRowsActual++;
				flushActualMetrics();
				return left;
			}
			matchedRowsActual++;
		}
		flushActualMetrics();
		return null;
	}

	private BindingSet getNextBatchElement() throws QueryEvaluationException {
		while (true) {
			if (batchOutput != null) {
				if (!batchOutput.isEmpty()) {
					return batchOutput.removeFirst();
				}
				batchOutput = null;
			}
			if (!openBatch()) {
				flushActualMetrics();
				return null;
			}
		}
	}

	private boolean openBatch() throws QueryEvaluationException {
		List<BindingSet> batch = new ArrayList<>(batchSize);
		while (batch.size() < batchSize && leftIter.hasNext()) {
			batch.add(leftIter.next());
		}
		if (batch.isEmpty()) {
			return false;
		}
		batchesActual++;
		leftRowsActual += batch.size();

		Set<String> keyNames = actualSharedKeyNames(batch.get(0));
		if (keyNames.isEmpty()) {
			return openScalarBatch(batch);
		}
		for (int i = 1; i < batch.size(); i++) {
			if (!keyNames.equals(actualSharedKeyNames(batch.get(i)))) {
				return openScalarBatch(batch);
			}
		}

		String[] sortedKeyNames = keyNames.toArray(new String[0]);
		Arrays.sort(sortedKeyNames);
		MatchedKeys matchedKeys = createMatchedKeys(batch, sortedKeyNames);

		LmdbIdBatchQueryEvaluationStep.BatchMetadata metadata = LmdbIdBatchQueryEvaluationStep.BatchMetadata.unsorted();
		String sortedByVariable = batchRightEvaluationStep.preferredBatchSortVariable(keyNames);
		if (sortedByVariable != null && keyNames.contains(sortedByVariable)
				&& LmdbIdLeftJoinIterator.sortBySingleLmdbId(batch, sortedByVariable)) {
			metadata = LmdbIdBatchQueryEvaluationStep.BatchMetadata.sortedBy(sortedByVariable);
		}

		try (CloseableIteration<BindingSet> right = batchRightEvaluationStep
				.evaluateBatch(new LmdbIdBatchQueryEvaluationStep.Batch(batch, metadata))) {
			while (right.hasNext()) {
				BindingSet row = right.next();
				rightRowsActual++;
				if (hasAllBindings(row, sortedKeyNames)) {
					matchedKeys.add(row);
				}
			}
		}

		batchOutput = new ArrayDeque<>();
		for (BindingSet left : batch) {
			if (matchedKeys.contains(left)) {
				matchedRowsActual++;
			} else {
				outputRowsActual++;
				batchOutput.addLast(left);
			}
		}
		flushActualMetrics();
		return true;
	}

	private boolean openScalarBatch(List<BindingSet> batch) throws QueryEvaluationException {
		scalarFallbackBatchesActual++;
		batchOutput = new ArrayDeque<>();
		for (BindingSet left : batch) {
			if (matchesAnyRight(left)) {
				matchedRowsActual++;
			} else {
				outputRowsActual++;
				batchOutput.addLast(left);
			}
		}
		flushActualMetrics();
		return true;
	}

	private boolean matchesAnyRight(BindingSet left) throws QueryEvaluationException {
		if (actualSharedKeyNames(left).isEmpty()) {
			return false;
		}
		try (CloseableIteration<BindingSet> right = rightEvaluationStep.evaluate(left)) {
			while (right.hasNext()) {
				BindingSet row = right.next();
				rightRowsActual++;
				if (hasSharedAndCompatibleBindings(left, row)) {
					return true;
				}
			}
		}
		return false;
	}

	private Set<String> actualSharedKeyNames(BindingSet bindings) {
		Set<String> names = actualBindingNames(bindings);
		names.retainAll(sharedVariables);
		names.retainAll(batchRightEvaluationStep == null ? sharedVariables
				: batchRightEvaluationStep.batchResultBindingNames());
		return names;
	}

	private static boolean hasSharedAndCompatibleBindings(BindingSet left, BindingSet right) {
		boolean shared = false;
		for (Binding binding : left) {
			String name = binding.getName();
			if (isInternalBindingName(name) || binding.getValue() == null || !right.hasBinding(name)) {
				continue;
			}
			shared = true;
			Value rightValue = right.getValue(name);
			if (rightValue != null && !binding.getValue().equals(rightValue)) {
				return false;
			}
		}
		return shared;
	}

	private static boolean hasAllBindings(BindingSet bindings, String[] sortedKeyNames) {
		for (String name : sortedKeyNames) {
			if (bindings.getValue(name) == null) {
				return false;
			}
		}
		return true;
	}

	private static Set<String> actualBindingNames(BindingSet bindings) {
		Set<String> names = new HashSet<>();
		for (Binding binding : bindings) {
			if (binding.getValue() != null && !isInternalBindingName(binding.getName())) {
				names.add(binding.getName());
			}
		}
		return names;
	}

	private static boolean isInternalBindingName(String name) {
		return name.startsWith("_const_") || name.startsWith("_anon_");
	}

	private static MatchedKeys createMatchedKeys(List<BindingSet> batch, String[] sortedKeyNames) {
		if (LmdbIdLeftJoinIterator.canUseSingleIdMatchedKeys(batch, sortedKeyNames)) {
			return new SingleIdMatchedKeys(sortedKeyNames[0], batch.size());
		}
		return new GenericMatchedKeys(sortedKeyNames, batch.size());
	}

	private static long internalId(Value value) {
		if (value instanceof LmdbValue) {
			long id = ((LmdbValue) value).getInternalID();
			if (id != LmdbValue.UNKNOWN_ID) {
				return id;
			}
		}
		return LmdbValue.UNKNOWN_ID;
	}

	@Override
	protected void handleClose() throws QueryEvaluationException {
		try {
			leftIter.close();
		} finally {
			batchOutput = null;
			flushActualMetrics();
		}
	}

	private void flushActualMetrics() {
		difference.setStringMetricActual("lmdbEvalDpAntiJoinActual", "true");
		difference.setStringMetricActual("lmdbEvalDpModeActual", actualMode);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinBatchesActual", batchesActual);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinScalarFallbackBatchesActual", scalarFallbackBatchesActual);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinLeftRowsActual", leftRowsActual);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinRightRowsActual", rightRowsActual);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinMatchedRowsActual", matchedRowsActual);
		difference.setLongMetricActual("lmdbEvalDpAntiJoinOutputRowsActual", outputRowsActual);
		if (membershipSet != null) {
			difference.setStringMetricActual("lmdbEvalDpAntiJoinMembershipSetActual", "true");
			difference.setLongMetricActual("lmdbEvalDpAntiJoinMembershipSetSizeActual", membershipSet.size());
			difference.setLongMetricActual("lmdbEvalDpAntiJoinMembershipRowsActual", membershipSet.rowsScanned());
		} else if (membershipFallbackReason != null) {
			difference.setStringMetricActual("lmdbEvalDpAntiJoinMembershipFallbackActual", membershipFallbackReason);
		}
	}

	private interface MatchedKeys {

		void add(BindingSet bindings);

		boolean contains(BindingSet bindings);
	}

	private static final class SingleIdMatchedKeys implements MatchedKeys {
		private final String name;
		private final LmdbIdSet ids;

		private SingleIdMatchedKeys(String name, int expectedRows) {
			this.name = name;
			this.ids = LmdbIdSets.create(expectedRows);
		}

		@Override
		public void add(BindingSet bindings) {
			long id = BindingKey.internalId(bindings.getValue(name));
			if (id != LmdbValue.UNKNOWN_ID) {
				ids.add(id);
			}
		}

		@Override
		public boolean contains(BindingSet bindings) {
			long id = BindingKey.internalId(bindings.getValue(name));
			return id != LmdbValue.UNKNOWN_ID && ids.contains(id);
		}
	}

	private static final class GenericMatchedKeys implements MatchedKeys {
		private final String[] sortedKeyNames;
		private final Set<BindingKey> keys;

		private GenericMatchedKeys(String[] sortedKeyNames, int expectedRows) {
			this.sortedKeyNames = sortedKeyNames;
			this.keys = new HashSet<>(expectedRows * 2);
		}

		@Override
		public void add(BindingSet bindings) {
			keys.add(BindingKey.from(bindings, sortedKeyNames));
		}

		@Override
		public boolean contains(BindingSet bindings) {
			return keys.contains(BindingKey.from(bindings, sortedKeyNames));
		}
	}

	private static final class BindingKey {
		private final String[] names;
		private final long[] ids;
		private final Value[] values;
		private final int hash;

		private BindingKey(String[] names, long[] ids, Value[] values) {
			this.names = names;
			this.ids = ids;
			this.values = values;
			this.hash = computeHash(names, ids, values);
		}

		private static BindingKey from(BindingSet bindings, String[] sortedNames) {
			long[] ids = new long[sortedNames.length];
			Value[] values = new Value[sortedNames.length];
			for (int i = 0; i < sortedNames.length; i++) {
				Value value = bindings.getValue(sortedNames[i]);
				long id = internalId(value);
				ids[i] = id;
				if (id == LmdbValue.UNKNOWN_ID) {
					values[i] = value;
				}
			}
			return new BindingKey(sortedNames, ids, values);
		}

		private static long internalId(Value value) {
			if (value instanceof LmdbValue) {
				long id = ((LmdbValue) value).getInternalID();
				if (id != LmdbValue.UNKNOWN_ID) {
					return id;
				}
			}
			return LmdbValue.UNKNOWN_ID;
		}

		private static int computeHash(String[] names, long[] ids, Value[] values) {
			int hash = Arrays.hashCode(names);
			for (int i = 0; i < ids.length; i++) {
				long id = ids[i];
				hash = 31 * hash + (id != LmdbValue.UNKNOWN_ID ? Long.hashCode(id) : Objects.hashCode(values[i]));
			}
			return hash;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) {
				return true;
			}
			if (!(o instanceof BindingKey)) {
				return false;
			}
			BindingKey that = (BindingKey) o;
			if (!Arrays.equals(names, that.names)) {
				return false;
			}
			for (int i = 0; i < ids.length; i++) {
				long id = ids[i];
				long thatId = that.ids[i];
				if (id != LmdbValue.UNKNOWN_ID || thatId != LmdbValue.UNKNOWN_ID) {
					if (id != thatId) {
						return false;
					}
				} else if (!Objects.equals(values[i], that.values[i])) {
					return false;
				}
			}
			return true;
		}

		@Override
		public int hashCode() {
			return hash;
		}
	}
}
