PREFIX ex: <http://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * {
   ?s ex:predicate ?o
   LATERAL {
      {SELECT * { ?s rdfs:label ?label } LIMIT 1}
      UNION
      {SELECT * { ?s ex:alternative ?alt } LIMIT 1}
   }
}

