/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude Code
package org.eclipse.rdf4j.workbench.proxy.config;

import java.io.IOException;
import java.io.StringReader;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.Set;

import org.eclipse.rdf4j.common.app.AppConfiguration;
import org.eclipse.rdf4j.common.app.config.Configuration;
import org.eclipse.rdf4j.common.app.util.ConfigurationUtil;

import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletException;

/** Loads and caches the validated Workbench policy for one servlet application. */
public final class WorkbenchPolicyLoader {
	public static final String POLICY_ATTRIBUTE = WorkbenchPolicyLoader.class.getName() + ".policy";

	private static final String APP_CONFIGURATION_ATTRIBUTE = WorkbenchPolicyLoader.class.getName()
			+ ".appConfiguration";

	private WorkbenchPolicyLoader() {
	}

	/**
	 * Returns the context's cached policy, loading and validating it on the first call.
	 *
	 * @param context          servlet application context
	 * @param appConfiguration already initialized Workbench application configuration, if available
	 * @return immutable application policy
	 * @throws ServletException if the configuration cannot be loaded or validated
	 */
	public static WorkbenchPolicy getPolicy(ServletContext context, AppConfiguration appConfiguration)
			throws ServletException {
		if (context == null) {
			throw new ServletException("Workbench policy requires a ServletContext");
		}
		Object existing = context.getAttribute(POLICY_ATTRIBUTE);
		if (existing instanceof WorkbenchPolicy) {
			return (WorkbenchPolicy) existing;
		}
		synchronized (context) {
			existing = context.getAttribute(POLICY_ATTRIBUTE);
			if (existing instanceof WorkbenchPolicy) {
				return (WorkbenchPolicy) existing;
			}
			try {
				AppConfiguration config = getAppConfiguration(context, appConfiguration);
				Properties properties = loadProperties(config.getDataDir().toPath());
				WorkbenchPolicy policy = WorkbenchPolicy.fromProperties(properties, Set.of());
				context.setAttribute(POLICY_ATTRIBUTE, policy);
				return policy;
			} catch (IOException | IllegalArgumentException e) {
				throw new ServletException("Unable to load valid Workbench policy", e);
			}
		}
	}

	private static AppConfiguration getAppConfiguration(ServletContext context, AppConfiguration supplied)
			throws IOException {
		if (supplied != null) {
			context.setAttribute(APP_CONFIGURATION_ATTRIBUTE, supplied);
			return supplied;
		}
		Object existing = context.getAttribute(APP_CONFIGURATION_ATTRIBUTE);
		if (existing instanceof AppConfiguration) {
			return (AppConfiguration) existing;
		}
		AppConfiguration created = new AppConfiguration("Workbench", "RDF4J Workbench");
		created.init(false);
		context.setAttribute(APP_CONFIGURATION_ATTRIBUTE, created);
		return created;
	}

	private static Properties loadProperties(Path dataDirectory) throws IOException {
		Properties classpath = ConfigurationUtil.loadConfigurationProperties("workbench.properties", null);
		Properties layered = new Properties(classpath);
		Path external = dataDirectory.resolve(Configuration.DIR).resolve("workbench.properties");
		if (Files.isRegularFile(external)) {
			loadExternalProperties(external, layered);
		}
		Properties flattened = new Properties();
		for (String key : layered.stringPropertyNames()) {
			flattened.setProperty(key, layered.getProperty(key));
		}
		return flattened;
	}

	/**
	 * Reads the administrator's policy file as UTF-8, so that labels such as {@code Spørring} can be written as they
	 * are. A file that is not valid UTF-8 is read as ISO-8859-1, the encoding of
	 * {@link Properties#load(java.io.InputStream)}, as {@link java.util.PropertyResourceBundle} does; Unicode escapes
	 * (a backslash, {@code u} and four hex digits) work in either encoding.
	 */
	private static void loadExternalProperties(Path file, Properties target) throws IOException {
		byte[] contents = Files.readAllBytes(file);
		String text;
		try {
			text = StandardCharsets.UTF_8.newDecoder()
					.onMalformedInput(CodingErrorAction.REPORT)
					.onUnmappableCharacter(CodingErrorAction.REPORT)
					.decode(ByteBuffer.wrap(contents))
					.toString();
		} catch (CharacterCodingException notUtf8) {
			text = new String(contents, StandardCharsets.ISO_8859_1);
		}
		target.load(new StringReader(text));
	}
}
