/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.query.algebra.equivalence;

import java.util.Objects;

import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.algebra.equivalence.internal.Normalization;
import org.eclipse.rdf4j.query.algebra.equivalence.internal.Rdf4jCanonicalizer;

/** Computes checked semantic-normal-form fingerprints for optimizer indexing. */
public final class SemanticFingerprinter {
	private final CheckOptions options;
	private final SemanticAnalyzer analyzer;

	public SemanticFingerprinter() {
		this(CheckOptions.defaults());
	}

	public SemanticFingerprinter(CheckOptions options) {
		this.options = Objects.requireNonNull(options, "options");
		this.analyzer = new SemanticAnalyzer(options);
	}

	public SemanticFingerprint fingerprint(TupleExpr expression) {
		Objects.requireNonNull(expression, "expression");
		Normalization normalization = new Rdf4jCanonicalizer(options)
				.normalize(expression, options.getObservationMode());
		return new SemanticFingerprint(
				normalization.fingerprint(),
				normalization.canonicalEncoding(),
				normalization.canonicalIdentity(),
				options.getObservationMode(),
				analyzer.analyze(expression));
	}
}
