/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.eclipse.rdf4j.sail.lmdb.sketch.omni;

import static java.lang.Long.compareUnsigned;

import java.util.Arrays;
import java.util.List;

/** Internal query summary used to combine dimensions. */
record OmniSketchSummary(long count, long[] hashes, int retained, int nominalEntries, long minCount, long maxCount,
		double samplingProbability) {
	OmniSketchSummary(final long count, final long[] hashes, final int retained, final int nominalEntries,
			final long minCount, final long maxCount, final double samplingProbability) {
		this.count = Math.max(0L, count);
		this.hashes = hashes;
		this.retained = Math.max(0, retained);
		this.nominalEntries = Math.max(0, nominalEntries);
		this.minCount = Math.max(0L, minCount);
		this.maxCount = Math.max(0L, maxCount);
		this.samplingProbability = Math.max(0.0d, Math.min(1.0d, samplingProbability));
	}

	OmniSketchEstimate asEstimate() {
		final double estimate = distinctEstimate();
		return OmniSketchEstimate.of(estimate, samplingProbability, retained, retained, minCount, maxCount, this);
	}

	double distinctEstimate() {
		return count;
	}

	static OmniSketchSummary fromCells(final List<OmniSketchCell> cells, final int nominalEntries) {
		if (cells.isEmpty()) {
			return new OmniSketchSummary(0L, new long[0], 0, nominalEntries, 0L, 0L, 1.0d);
		}
		return fromCells(cells.toArray(OmniSketchCell[]::new), cells.size(), nominalEntries);
	}

	static OmniSketchSummary fromCells(final OmniSketchCell[] cells, final int cellCount, final int nominalEntries) {
		if (cells == null || cellCount <= 0) {
			return new OmniSketchSummary(0L, new long[0], 0, nominalEntries, 0L, 0L, 1.0d);
		}
		long minCount = Long.MAX_VALUE;
		long maxCount = 0L;
		double minEstimate = Double.POSITIVE_INFINITY;
		double probability = 1.0d;
		final long[][] sampleLists = new long[cellCount][];
		final int[] sampleLengths = new int[cellCount];
		int samples = 0;
		for (int i = 0; i < cellCount; i++) {
			final OmniSketchCell cell = cells[i];
			if (cell == null) {
				continue;
			}
			final long count = cell.getCount();
			minCount = Math.min(minCount, count);
			maxCount = Math.max(maxCount, count);
			sampleLists[samples] = cell.hashesArray();
			sampleLengths[samples] = cell.getRetainedEntries();
			double cellProbability = sampleProbability(sampleLists[samples], sampleLengths[samples], nominalEntries,
					count);
			probability = Math.min(probability, cellProbability);
			minEstimate = Math.min(minEstimate,
					estimateDistinct(sampleLists[samples], sampleLengths[samples], nominalEntries, count));
			samples++;
		}
		if (samples == 0) {
			return new OmniSketchSummary(0L, new long[0], 0, nominalEntries, 0L, 0L, 1.0d);
		}
		final long[] intersection = intersectSamples(sampleLists, sampleLengths, samples, nominalEntries);
		final long estimate;
		if (maxCount == 0L || minCount == 0L) {
			estimate = 0L;
		} else if (!Double.isFinite(minEstimate)) {
			estimate = minCount;
		} else {
			estimate = roundedEstimate(minEstimate);
		}
		return new OmniSketchSummary(estimate, intersection, intersection.length, nominalEntries, minCount, maxCount,
				probability);
	}

	static OmniSketchSummary union(final List<OmniSketchSummary> summaries, final int nominalEntries) {
		if (summaries.isEmpty()) {
			return new OmniSketchSummary(0L, new long[0], 0, nominalEntries, 0L, 0L, 1.0d);
		}
		long minCount = 0L;
		long maxCount = 0L;
		double probability = 1.0d;
		long[] merged = new long[0];
		int mergedLen = 0;
		for (final OmniSketchSummary summary : summaries) {
			minCount += summary.minCount;
			maxCount += summary.maxCount;
			probability = Math.min(probability, summary.samplingProbability);
			merged = OmniSketchCell.mergeSamples(merged, mergedLen, summary.hashes, summary.retained, nominalEntries);
			mergedLen = merged.length;
		}
		double unionEstimate = mergedLen >= nominalEntries
				? estimateDistinct(merged, mergedLen, nominalEntries, minCount)
				: probability >= 1.0d ? mergedLen : mergedLen / Math.max(probability, Double.MIN_NORMAL);
		return new OmniSketchSummary(roundedEstimate(unionEstimate), merged, mergedLen, nominalEntries, minCount,
				maxCount, probability);
	}

	static OmniSketchEstimate intersectionEstimate(final List<OmniSketchSummary> summaries) {
		if (summaries.isEmpty()) {
			final OmniSketchSummary empty = new OmniSketchSummary(0L, new long[0], 0, 0, 0L, 0L, 1.0d);
			return OmniSketchEstimate.of(0.0, 1.0, 0, 0, 0L, 0L, empty);
		}
		long minCount = Long.MAX_VALUE;
		long maxCount = 0L;
		OmniSketchSummary maxSummary = summaries.get(0);
		int nominalEntries = Integer.MAX_VALUE;
		final long[][] sampleLists = new long[summaries.size()][];
		final int[] sampleLengths = new int[summaries.size()];
		int samples = 0;
		for (final OmniSketchSummary summary : summaries) {
			minCount = Math.min(minCount, summary.count);
			if (summary.count >= maxCount) {
				maxCount = summary.count;
				maxSummary = summary;
			}
			nominalEntries = Math.min(nominalEntries, summary.nominalEntries);
			sampleLists[samples] = summary.hashes;
			sampleLengths[samples] = summary.retained;
			samples++;
		}
		if (nominalEntries == Integer.MAX_VALUE) {
			nominalEntries = 0;
		}
		final long[] intersection = intersectSamples(sampleLists, sampleLengths, samples, nominalEntries);
		final double estimate;
		final double samplingProbability;
		if (maxCount == 0L || minCount == 0L) {
			estimate = 0.0;
			samplingProbability = 1.0;
		} else if (maxSummary.retained == 0) {
			estimate = minCount;
			samplingProbability = 0.0;
		} else {
			samplingProbability = Math.min(1.0, maxSummary.retained / (double) maxCount);
			estimate = Math.min(minCount, maxCount * (intersection.length / (double) maxSummary.retained));
		}
		final OmniSketchSummary resultSummary = new OmniSketchSummary(Math.round(estimate), intersection,
				intersection.length, nominalEntries, minCount, maxCount, samplingProbability);
		return OmniSketchEstimate.of(estimate, samplingProbability, intersection.length, intersection.length, minCount,
				maxCount, resultSummary);
	}

	private static long[] intersectSamples(final long[][] samples, final int[] lengths, final int sampleCount,
			final int limit) {
		if (samples == null || lengths == null || sampleCount <= 0 || limit <= 0) {
			return new long[0];
		}
		int seedIndex = 0;
		int seedLen = Math.min(lengths[0], limit);
		if (seedLen <= 0) {
			return new long[0];
		}
		for (int i = 1; i < sampleCount; i++) {
			final int len = Math.min(lengths[i], limit);
			if (len <= 0) {
				return new long[0];
			}
			if (len < seedLen) {
				seedIndex = i;
				seedLen = len;
			}
		}
		if (sampleCount == 1) {
			return Arrays.copyOf(samples[seedIndex], seedLen);
		}
		long[] current = samples[seedIndex];
		int currentLen = seedLen;
		for (int i = 0; i < sampleCount && currentLen > 0; i++) {
			if (i == seedIndex) {
				continue;
			}
			current = intersectTwo(current, currentLen, samples[i], lengths[i], limit);
			currentLen = current.length;
		}
		return current;
	}

	static double estimateDistinct(final long[] sample, final int retained, final int nominalEntries,
			final long noSampleFallback) {
		if (retained <= 0) {
			return Math.max(0L, noSampleFallback);
		}
		if (retained < nominalEntries) {
			return retained;
		}
		double theta = theta(sample[retained - 1]);
		return retained == 1 ? 1.0d / theta : (retained - 1.0d) / theta;
	}

	static double sampleProbability(final long[] sample, final int retained, final int nominalEntries,
			final long count) {
		if (retained <= 0) {
			return count <= 0L ? 1.0d : 0.0d;
		}
		return retained < nominalEntries ? 1.0d : theta(sample[retained - 1]);
	}

	private static double theta(final long hash) {
		double unsigned = hash >= 0L ? hash : (double) (hash & Long.MAX_VALUE) + 0x1.0p63;
		return Math.max(0x1.0p-64, (unsigned + 1.0d) * 0x1.0p-64);
	}

	private static long roundedEstimate(final double estimate) {
		if (!Double.isFinite(estimate) || estimate >= Long.MAX_VALUE) {
			return Long.MAX_VALUE;
		}
		return Math.max(0L, Math.round(estimate));
	}

	private static long[] intersectTwo(final long[] a, final int aLen, final long[] b, final int bLen,
			final int limit) {
		final long[] out = new long[Math.min(Math.min(aLen, bLen), limit)];
		int ai = 0;
		int bi = 0;
		int oi = 0;
		while (ai < aLen && bi < bLen && oi < limit) {
			final int cmp = compareUnsigned(a[ai], b[bi]);
			if (cmp == 0) {
				out[oi++] = a[ai];
				ai++;
				bi++;
			} else if (cmp < 0) {
				ai++;
			} else {
				bi++;
			}
		}
		return oi == out.length ? out : Arrays.copyOf(out, oi);
	}
}
