PREFIX dash: <http://datashapes.org/dash#>
PREFIX ex: <http://example.com/ns#>
PREFIX rdf4j: <http://rdf4j.org/schema/rdf4j#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rsx: <http://rdf4j.org/shacl-extensions#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
    ex:validNode1 a ex:Type1 .
    ex:validNode1 ex:trueProp true .
    ex:validNode1 ex:knows ex:validNode2 .

    ex:validNode2 rdf:type ex:Type2 .
}
