/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.http.client.apache5;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

import java.io.IOException;
import java.net.URI;

import org.apache.hc.client5.http.config.RequestConfig;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.core5.http.ClassicHttpRequest;
import org.apache.hc.core5.http.ClassicHttpResponse;
import org.apache.hc.core5.http.HttpHost;
import org.apache.hc.core5.http.protocol.HttpContext;
import org.eclipse.rdf4j.common.net.PublicNetworkAccessPolicy;
import org.eclipse.rdf4j.common.net.RemoteResourceAccessPolicy;
import org.eclipse.rdf4j.http.client.spi.HttpRequest;
import org.eclipse.rdf4j.http.client.spi.RDF4JHttpClient;
import org.eclipse.rdf4j.http.client.spi.RDF4JHttpClientConfig;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockserver.client.MockServerClient;
import org.mockserver.junit.jupiter.MockServerExtension;

@ExtendWith(MockServerExtension.class)
class ApacheHC5RDF4JHttpClientSecurityTest {

	@Test
	void rejectsInitialTargetBeforeTransportExecution() {
		CloseableHttpClient transport = mock(CloseableHttpClient.class);
		ApacheHC5RDF4JHttpClient client = new ApacheHC5RDF4JHttpClient(transport, 2, RequestConfig.DEFAULT,
				new PublicNetworkAccessPolicy());

		assertThatThrownBy(() -> client.execute(HttpRequest.newBuilder("GET",
				URI.create("http://127.0.0.1/resource")).build()))
						.isInstanceOf(java.io.IOException.class)
						.hasMessageContaining("127.0.0.1");
		verifyNoInteractions(transport);
	}

	@Test
	void rejectsRedirectTargetBeforeRedirectConnection(MockServerClient server) throws Exception {
		URI initialTarget = URI.create("http://127.0.0.1:" + server.getPort() + "/start");
		URI redirectedTarget = URI.create("http://127.0.0.1:" + server.getPort() + "/blocked");
		server.when(request().withMethod("GET").withPath("/start"))
				.respond(response().withStatusCode(302).withHeader("Location", redirectedTarget.toString()));
		server.when(request().withMethod("GET").withPath("/blocked"))
				.respond(response().withStatusCode(200).withBody("must not be reached"));
		IOException denied = new IOException("redirect denied by test policy");
		RemoteResourceAccessPolicy policy = mock(RemoteResourceAccessPolicy.class);
		doThrow(denied).when(policy).checkRedirect(initialTarget, redirectedTarget);

		try (RDF4JHttpClient client = new ApacheHC5RDF4JHttpClientFactory().create(
				RDF4JHttpClientConfig.newBuilder().remoteResourceAccessPolicy(policy).build())) {
			assertThatThrownBy(() -> client.execute(HttpRequest.newBuilder("GET", initialTarget).build()))
					.isSameAs(denied);
		}
	}

	@Test
	void revalidatesBeforeExplicitResponseRetry() throws Exception {
		URI target = URI.create("https://example.org/resource");
		IOException rebound = new IOException("rebound to private address");
		RemoteResourceAccessPolicy policy = mock(RemoteResourceAccessPolicy.class);
		doNothing().doThrow(rebound).when(policy).checkInitial(target);
		ClassicHttpResponse timeout = mock(ClassicHttpResponse.class);
		when(timeout.getCode()).thenReturn(408);
		CloseableHttpClient transport = mock(CloseableHttpClient.class);
		when(transport.executeOpen(isNull(HttpHost.class), any(ClassicHttpRequest.class), isNull(HttpContext.class)))
				.thenReturn(timeout);
		ApacheHC5RDF4JHttpClient client = new ApacheHC5RDF4JHttpClient(transport, 2, RequestConfig.DEFAULT, policy);

		assertThatThrownBy(() -> client.execute(HttpRequest.newBuilder("GET", target).build())).isSameAs(rebound);

		verify(policy, times(2)).checkInitial(target);
		verify(transport).executeOpen(isNull(HttpHost.class), any(ClassicHttpRequest.class), isNull(HttpContext.class));
		verify(timeout).close();
	}
}
