/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.http.server;

import java.nio.charset.StandardCharsets;
import java.util.Map;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.View;
import org.springframework.web.servlet.mvc.Controller;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class ServerHomeController implements Controller {

	private static final String CONTENT_TYPE = "text/html;charset=UTF-8";
	private static final View REDIRECT_TO_HOME_VIEW = new RedirectToHomeView();
	private static final View HOME_VIEW = new HomeView();

	private static final String HOME_HTML = """
			<!DOCTYPE html>
			<html>
			<head>
				<meta http-equiv="content-type" content="text/html; charset=utf-8" />
				<title>RDF4J Server - Home</title>
			</head>
			<body>
				<header>
					<h1>RDF4J Server</h1>
				</header>
				<main id="content">
					<h1>Welcome</h1>
					<p>
						You are currently accessing an RDF4J Server. This server is intended to be accessed by
						dedicated clients, using a specialized protocol. To access the information on this server
						through a browser, we recommend using the RDF4J Workbench software.
					</p>
				</main>
			</body>
			</html>
			""";

	@Override
	public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response) {
		if (!request.getRequestURI().endsWith("/home/overview.view")) {
			return new ModelAndView(REDIRECT_TO_HOME_VIEW);
		}
		return new ModelAndView(HOME_VIEW);
	}

	private static final class RedirectToHomeView implements View {

		@Override
		public String getContentType() {
			return null;
		}

		@Override
		public void render(Map<String, ?> model, HttpServletRequest request, HttpServletResponse response)
				throws Exception {
			response.sendRedirect(response.encodeRedirectURL(request.getContextPath() + "/home/overview.view"));
		}
	}

	private static final class HomeView implements View {

		@Override
		public String getContentType() {
			return CONTENT_TYPE;
		}

		@Override
		public void render(Map<String, ?> model, HttpServletRequest request, HttpServletResponse response)
				throws Exception {
			response.setCharacterEncoding(StandardCharsets.UTF_8.name());
			response.setContentType(CONTENT_TYPE);
			response.getWriter().write(HOME_HTML);
		}
	}
}
