/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex

package org.eclipse.rdf4j.sail.base;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.apache.datasketches.theta.Intersection;
import org.apache.datasketches.theta.SetOperation;
import org.apache.datasketches.theta.Sketch;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Resource;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.algebra.Join;
import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.eclipse.rdf4j.query.algebra.Var;
import org.junit.jupiter.api.Test;

class SketchBasedJoinEstimatorZeroIntersectionSamplingRegressionTest {

	private static final ValueFactory VF = SimpleValueFactory.getInstance();
	private static final String PROPERTY_PREFIX = "org.eclipse.rdf4j.sail.base.SketchBasedJoinEstimator.";
	private static final String EXACT_LIMIT_PROPERTY = PROPERTY_PREFIX + "zeroIntersectionExactDistinctLimit";
	private static final String SKEW_RATIO_PROPERTY = PROPERTY_PREFIX + "zeroIntersectionSkewRatio";
	private static final String ROW_BUDGET_PROPERTY = PROPERTY_PREFIX + "zeroIntersectionRowBudget";
	private static final String SAMPLE_SIZE_PROPERTY = PROPERTY_PREFIX + "zeroIntersectionSampleSize";

	@Test
	void plannerFallsBackToPositiveEstimateWhenThetaMissesRareOverlap() throws Exception {
		PropertyState properties = PropertyState.capture(
				EXACT_LIMIT_PROPERTY,
				SKEW_RATIO_PROPERTY,
				ROW_BUDGET_PROPERTY,
				SAMPLE_SIZE_PROPERTY);
		try {
			System.setProperty(EXACT_LIMIT_PROPERTY, "8");
			System.setProperty(SKEW_RATIO_PROPERTY, "32");
			System.setProperty(ROW_BUDGET_PROPERTY, "200000");
			System.setProperty(SAMPLE_SIZE_PROPERTY, "32");

			RareOverlapFixture fixture = buildRareOverlapFixture();
			double plannerJoinEstimate = fixture.estimator.cardinality(fixture.join);
			double relativeError = Math.abs(plannerJoinEstimate - fixture.actualJoinRows) / fixture.actualJoinRows;

			assertEquals(0.0d, fixture.thetaIntersectionDistinct, 0.0d,
					"Test precondition: raw theta intersection should miss the rare overlap");
			assertTrue(plannerJoinEstimate > 0.0d,
					() -> "Planner should recover from zero theta intersection. actual=" + fixture.actualJoinRows
							+ ", thetaDistinct=" + fixture.thetaIntersectionDistinct);
			assertTrue(relativeError <= 0.25d,
					() -> "Sampled rare-overlap fallback should stay within 25% relative error. estimate="
							+ plannerJoinEstimate + ", actual=" + fixture.actualJoinRows + ", error=" + relativeError);
		} finally {
			properties.restore();
		}
	}

	private static RareOverlapFixture buildRareOverlapFixture() throws Exception {
		IRI locatedAt = VF.createIRI("urn:locatedAt");
		IRI hasName = VF.createIRI("urn:hasName");
		int overlapBranches = 64;
		int copiesPerBranch = 4;

		for (int noiseSubjects = 4096; noiseSubjects <= 262144; noiseSubjects *= 2) {
			StubSailStore store = new StubSailStore();
			populateRareOverlapData(store, locatedAt, hasName, overlapBranches, copiesPerBranch, noiseSubjects);

			SketchBasedJoinEstimator estimator = new SketchBasedJoinEstimator(store, config());
			estimator.rebuildOnceSlow();

			double thetaIntersectionDistinct = rawThetaIntersectionDistinct(estimator, locatedAt, hasName);
			if (thetaIntersectionDistinct == 0.0d) {
				return new RareOverlapFixture(estimator, joinNode(locatedAt, hasName),
						(double) overlapBranches * copiesPerBranch, thetaIntersectionDistinct);
			}
		}

		throw new AssertionError("Unable to construct a zero-intersection rare-overlap fixture");
	}

	private static void populateRareOverlapData(StubSailStore store, IRI locatedAt, IRI hasName, int overlapBranches,
			int copiesPerBranch, int noiseSubjects) {
		List<Resource> branches = new ArrayList<>(overlapBranches);
		for (int branchIndex = 0; branchIndex < overlapBranches; branchIndex++) {
			Resource branch = VF.createIRI("urn:branch:" + branchIndex);
			branches.add(branch);
			store.add(st(branch, hasName, VF.createLiteral("Branch " + branchIndex)));
			for (int copyIndex = 0; copyIndex < copiesPerBranch; copyIndex++) {
				Resource copy = VF.createIRI("urn:copy:" + branchIndex + ":" + copyIndex);
				store.add(st(copy, locatedAt, branch));
			}
		}

		for (int noiseIndex = 0; noiseIndex < noiseSubjects; noiseIndex++) {
			Resource noiseSubject = VF.createIRI("urn:noise:" + noiseIndex);
			store.add(st(noiseSubject, hasName, VF.createLiteral("Noise " + noiseIndex)));
		}
	}

	private static double rawThetaIntersectionDistinct(SketchBasedJoinEstimator estimator, IRI locatedAt, IRI hasName)
			throws Exception {
		Object leftEstimate = estimator.estimate(SketchBasedJoinEstimator.Component.O, null, locatedAt.stringValue(),
				null, null);
		Object rightEstimate = estimator.estimate(SketchBasedJoinEstimator.Component.S, null, hasName.stringValue(),
				null, null);
		Sketch leftBindings = bindingsSketch(leftEstimate);
		Sketch rightBindings = bindingsSketch(rightEstimate);

		Intersection intersection = SetOperation.builder().buildIntersection();
		intersection.intersect(leftBindings);
		intersection.intersect(rightBindings);
		return intersection.getResult().getEstimate();
	}

	private static Sketch bindingsSketch(Object joinEstimate) throws Exception {
		Field bindingsField = joinEstimate.getClass().getDeclaredField("bindings");
		bindingsField.setAccessible(true);
		return (Sketch) bindingsField.get(joinEstimate);
	}

	private static SketchBasedJoinEstimator.Config config() {
		return SketchBasedJoinEstimator.Config.defaults()
				.withNominalEntries(128)
				.withSketchK(512)
				.withThrottleEveryN(1)
				.withThrottleMillis(0)
				.withRefreshSleepMillis(5);
	}

	private static Join joinNode(IRI locatedAt, IRI hasName) {
		return new Join(
				new StatementPattern(Var.of("copy"), Var.of("locatedAt", locatedAt), Var.of("branch")),
				new StatementPattern(Var.of("branch"), Var.of("hasName", hasName), Var.of("branchName")));
	}

	private static org.eclipse.rdf4j.model.Statement st(Resource subject, IRI predicate, Value object) {
		return VF.createStatement(subject, predicate, object);
	}

	private record RareOverlapFixture(SketchBasedJoinEstimator estimator, Join join, double actualJoinRows,
			double thetaIntersectionDistinct) {
	}

	private static final class PropertyState {
		private final String[] keys;
		private final String[] values;

		private PropertyState(String[] keys, String[] values) {
			this.keys = keys;
			this.values = values;
		}

		private static PropertyState capture(String... keys) {
			String[] values = new String[keys.length];
			for (int i = 0; i < keys.length; i++) {
				values[i] = System.getProperty(keys[i]);
			}
			return new PropertyState(keys, values);
		}

		private void restore() {
			for (int i = 0; i < keys.length; i++) {
				if (values[i] == null) {
					System.clearProperty(keys[i]);
				} else {
					System.setProperty(keys[i], values[i]);
				}
			}
		}
	}
}
