/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.base;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Collections;

import org.eclipse.rdf4j.query.Query;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.algebra.TupleExpr;
import org.eclipse.rdf4j.query.parser.QueryParserUtil;
import org.eclipse.rdf4j.queryrender.sparql.TupleExprIRRenderer;
import org.eclipse.rdf4j.queryrender.sparql.TupleExprIRRenderer.DatasetView;
import org.junit.jupiter.api.Test;

class SlowQueryLogFormatterTest {

	@Test
	void formatterEmitsRawUnoptimizedAndOptimizedSections() {
		String queryText = "SELECT * WHERE { ?s ?p ?o }";
		TupleExpr tupleExpr = parseTupleExpr(queryText);
		SlowQueryLogInfo info = new SlowQueryLogInfo("org.eclipse.rdf4j.sail.memory.MemoryStore", 1L,
				Query.QueryType.TUPLE, queryText, tupleExpr, tupleExpr, null, Collections.emptySet());

		String formatted = new SlowQueryLogFormatter().format(info, 2_000L);

		assertThat(formatted)
				.contains("Raw query text")
				.contains(queryText)
				.contains("Unoptimized explanation")
				.contains("Optimized explanation")
				.contains("Rendered optimized query after optimization");
	}

	@Test
	void graphQueriesEmitWarningInsteadOfRenderedSelect() {
		String queryText = "CONSTRUCT WHERE { ?s ?p ?o }";
		TupleExpr tupleExpr = parseTupleExpr(queryText);
		SlowQueryLogInfo info = new SlowQueryLogInfo("org.eclipse.rdf4j.sail.memory.MemoryStore", 1L,
				Query.QueryType.GRAPH, queryText, tupleExpr, tupleExpr, null, Collections.emptySet());

		String formatted = new SlowQueryLogFormatter().format(info, 2_000L);

		assertThat(formatted)
				.contains("Skipped: GRAPH queries are not rendered")
				.doesNotContain("SELECT * WHERE");
	}

	@Test
	void rendererThrowableIsRecordedWithoutThrowing() {
		String queryText = "SELECT * WHERE { ?s ?p ?o }";
		TupleExpr tupleExpr = parseTupleExpr(queryText);
		SlowQueryLogInfo info = new SlowQueryLogInfo("org.eclipse.rdf4j.sail.memory.MemoryStore", 1L,
				Query.QueryType.TUPLE, queryText, tupleExpr, tupleExpr, null, Collections.emptySet());

		String formatted = new SlowQueryLogFormatter() {
			@Override
			protected TupleExprIRRenderer createRenderer() {
				return new TupleExprIRRenderer() {
					@Override
					public String render(TupleExpr tupleExpr, DatasetView dataset) {
						throw new IllegalStateException("boom");
					}
				};
			}
		}.format(info, 2_000L);

		assertThat(formatted)
				.contains("Renderer throwable:")
				.contains("boom");
	}

	private TupleExpr parseTupleExpr(String queryText) {
		return QueryParserUtil.parseQuery(QueryLanguage.SPARQL, queryText, null).getTupleExpr();
	}
}
