/*******************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
// Some portions generated by Claude Code
package org.eclipse.rdf4j.workbench.proxy;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

import org.eclipse.rdf4j.common.exception.ValidationException;
import org.eclipse.rdf4j.http.protocol.UnauthorizedException;
import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.Namespace;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.query.QueryResultHandlerException;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.RepositoryException;
import org.eclipse.rdf4j.repository.config.RepositoryConfigException;
import org.eclipse.rdf4j.repository.manager.LocalRepositoryManager;
import org.eclipse.rdf4j.repository.manager.RemoteRepositoryManager;
import org.eclipse.rdf4j.repository.manager.RepositoryManager;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.WriterConfig;
import org.eclipse.rdf4j.rio.helpers.BasicWriterSettings;
import org.eclipse.rdf4j.workbench.base.AbstractServlet;
import org.eclipse.rdf4j.workbench.base.WorkbenchHtmlShell;
import org.eclipse.rdf4j.workbench.base.WorkbenchViewRegistry;
import org.eclipse.rdf4j.workbench.exceptions.BadRequestException;
import org.eclipse.rdf4j.workbench.exceptions.MissingInitParameterException;
import org.eclipse.rdf4j.workbench.proxy.config.WorkbenchPageUrl;
import org.eclipse.rdf4j.workbench.proxy.config.WorkbenchPolicy;
import org.eclipse.rdf4j.workbench.proxy.config.WorkbenchPolicyLoader;
import org.eclipse.rdf4j.workbench.proxy.config.WorkbenchPolicyResponse;
import org.eclipse.rdf4j.workbench.util.BasicServletConfig;
import org.eclipse.rdf4j.workbench.util.DynamicHttpRequest;
import org.eclipse.rdf4j.workbench.util.ServerCredentials;
import org.eclipse.rdf4j.workbench.util.ShaclValidationSummary;
import org.eclipse.rdf4j.workbench.util.TupleResultBuilder;
import org.eclipse.rdf4j.workbench.util.WorkbenchPageProtocol;
import org.eclipse.rdf4j.workbench.util.WorkbenchPageResultWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.servlet.Servlet;
import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

public class WorkbenchServlet extends AbstractServlet {

	private static final Logger LOGGER = LoggerFactory.getLogger(WorkbenchServlet.class);

	private static final String DEFAULT_PATH = "default-path";

	private static final String NO_REPOSITORY = "no-repository-id";

	public static final String SERVER_PARAM = "server";

	private RepositoryManager manager;

	private WorkbenchPolicy policy;

	private final ConcurrentMap<String, ProxyRepositoryServlet> repositories = new ConcurrentHashMap<>();

	@Override
	public void init(final ServletConfig config) throws ServletException {
		this.config = config;
		if (config.getInitParameter(DEFAULT_PATH) == null) {
			throw new MissingInitParameterException(DEFAULT_PATH);
		}
		final String param = config.getInitParameter(SERVER_PARAM);
		if (param == null || param.trim().isEmpty()) {
			throw new MissingInitParameterException(SERVER_PARAM);
		}
		this.policy = WorkbenchPolicyLoader.getPolicy(config.getServletContext(), null);
		try {
			manager = createRepositoryManager(param);
		} catch (IOException | RepositoryException e) {
			throw new ServletException(e);
		}
	}

	@Override
	public void destroy() {
		for (Servlet servlet : repositories.values()) {
			servlet.destroy();
		}
		manager.shutDown();
	}

	public void resetCache() {
		for (ProxyRepositoryServlet proxy : repositories.values()) {
			// inform browser that server changed and cache is invalid
			proxy.resetCache();
		}
	}

	@Override
	public void service(final HttpServletRequest req, final HttpServletResponse resp)
			throws ServletException, IOException {
		final String pathInfo = req.getPathInfo();
		boolean landingRequest = pathInfo == null || "/".equals(pathInfo);
		String landingPath = landingRequest
				? policy.selectLandingPath(WorkbenchPolicy.LandingContext.WORKBENCH,
						config.getInitParameter(DEFAULT_PATH))
				: null;
		if (landingRequest && landingPath == null) {
			WorkbenchPolicyResponse.sendDisabledLanding(resp,
					"The RDF4J Workbench has no Workbench landing page enabled by policy.");
			return;
		}
		String route = landingRequest ? landingPath : getRoutePath(pathInfo);
		if (!policy.isRouteAllowed(route)) {
			WorkbenchPolicyResponse.sendHiddenPage(resp);
			return;
		}
		if (!landingRequest) {
			WorkbenchViewRegistry.viewIdForRoute(route)
					.ifPresent(viewId -> req.setAttribute(WorkbenchPageProtocol.PAGE_VIEW_ID_ATTRIBUTE, viewId));
		}
		if (landingRequest) {
			resp.sendRedirect(WorkbenchPageUrl.resolveWorkbenchPath(req, landingPath));
		} else if ('/' == pathInfo.charAt(0)) {
			try {
				handleRequest(req, resp, pathInfo);
			} catch (QueryResultHandlerException e) {
				throw new IOException(e);
			}
		} else {
			throw new BadRequestException("Request path must contain a repository ID");
		}
	}

	private String getRoutePath(String pathInfo) {
		String path = pathInfo;
		if (path == null || "/".equals(path)) {
			path = config.getInitParameter(DEFAULT_PATH);
		} else if (!path.startsWith("/")) {
			return config.getInitParameter("default-command");
		}
		if (path == null) {
			return config.getInitParameter("default-command");
		}
		int routeStart = path.indexOf('/', 1);
		if (routeStart < 0 || routeStart == path.length() - 1) {
			return policy.selectLandingPath(WorkbenchPolicy.LandingContext.REPOSITORY,
					config.getInitParameter("default-command"));
		}
		return path.substring(routeStart);
	}

	/**
	 * @param req      the servlet request
	 * @param resp     the servlet response
	 * @param pathInfo the path info from the request
	 * @throws IOException
	 * @throws ServletException
	 * @throws QueryResultHandlerException
	 */
	private void handleRequest(final HttpServletRequest req, final HttpServletResponse resp, final String pathInfo)
			throws IOException, ServletException, QueryResultHandlerException {
		int idx = pathInfo.indexOf('/', 1);
		if (idx < 0) {
			idx = pathInfo.length();
		}
		final String repoID = pathInfo.substring(1, idx);
		try {
			service(repoID, req, resp);
		} catch (UnauthorizedException e) {
			handleUnauthorizedException(req, resp);
		} catch (RepositoryConfigException | RepositoryException e) {
			Optional<ValidationException> validation = ShaclValidationSummary.find(e);
			if (causedByUnauthorized(e)) {
				// A remote manager reports a server that refuses the user (listing its repositories) this way.
				handleUnauthorizedException(req, resp);
			} else if (validation.isPresent()) {
				Model model = validation.get().validationReportAsModel();
				// One line per violation (focus node, path, value, what was expected), not the report's RDF.
				String summary = ShaclValidationSummary.summarize(model, repositoryNamespaces(repoID));

				if (WorkbenchPageProtocol.requestsPageData(req) && !resp.isCommitted()) {
					// An in-page change (Add, Remove, Clear, Update) reads a page model, not plain text.
					writePageError(req, resp, HttpServletResponse.SC_CONFLICT, "shacl-validation", summary);
				} else {
					StringWriter report = new StringWriter();
					PrintWriter writer = new PrintWriter(report);
					writer.println(summary);
					writer.println("\nThe validation report:\n");
					WriterConfig writerConfig = new WriterConfig();
					writerConfig.set(BasicWriterSettings.PRETTY_PRINT, true);
					writerConfig.set(BasicWriterSettings.INLINE_BLANK_NODES, true);
					Rio.write(model, writer, RDFFormat.TURTLE, writerConfig);

					writer.println(
							"\n" +
									"THIS ERROR MESSAGE IS EXPERIMENTAL AND IS SUBJECT TO CHANGE - " +
									"DO NOT TRY TO PARSE THIS ERROR MESSAGE");
					writer.flush();
					resp.setStatus(HttpServletResponse.SC_CONFLICT);
					resp.setContentType(TEXT_PLAIN);
					resp.getWriter().print(report);
				}
			} else {
				throw new ServletException(e);
			}
		} catch (ServletException e) {
			if (e.getCause() instanceof UnauthorizedException) {
				handleUnauthorizedException(req, resp);
			} else {
				throw e;
			}
		}
	}

	private static boolean causedByUnauthorized(Throwable error) {
		for (Throwable cause = error.getCause(); cause != null; cause = cause.getCause()) {
			if (cause instanceof UnauthorizedException) {
				return true;
			}
		}
		return false;
	}

	/** The namespaces of a repository, to write the names of a validation report with; none when unavailable. */
	private List<Namespace> repositoryNamespaces(String repoID) {
		try {
			Repository repository = manager.getRepository(repoID);
			if (repository == null) {
				return List.of();
			}
			try (RepositoryConnection connection = repository.getConnection()) {
				return ShaclValidationSummary.namespaces(connection);
			}
		} catch (RepositoryConfigException | RepositoryException e) {
			LOGGER.debug("Unable to read the namespaces of repository {}", repoID, e);
			return List.of();
		}
	}

	/**
	 * @param req
	 * @param resp
	 * @throws IOException
	 * @throws QueryResultHandlerException
	 */
	private void handleUnauthorizedException(final HttpServletRequest req, final HttpServletResponse resp)
			throws IOException, QueryResultHandlerException {
		if (WorkbenchPageProtocol.requestsHtmlNavigation(req) || WorkbenchPageProtocol.requestsPageData(req)) {
			writeUnauthorizedPageModel(req, resp);
			return;
		}
		// Invalid credentials or insufficient authorization. Present
		// entry form again with error message.
		final TupleResultBuilder builder = getTupleResultBuilder(req, resp, resp.getOutputStream());
		builder.start("error-message");
		builder.result(
				"The entered credentials entered either failed to authenticate to the RDF4J server, or were unauthorized for the requested operation.");
		builder.end();
	}

	private void writeUnauthorizedPageModel(HttpServletRequest request, HttpServletResponse response)
			throws IOException, QueryResultHandlerException {
		ByteArrayOutputStream pageData = new ByteArrayOutputStream();
		WorkbenchPageResultWriter pageWriter = new WorkbenchPageResultWriter(pageData);
		String viewId = pageViewId(request);
		pageWriter.view(viewId);
		TupleResultBuilder builder = new TupleResultBuilder(pageWriter, SimpleValueFactory.getInstance());
		builder.start("error-message")
				.link(List.of("info"))
				.result(
						"The entered credentials entered either failed to authenticate to the RDF4J server, or were unauthorized for the requested operation.")
				.end();
		if (WorkbenchPageProtocol.requestsHtmlNavigation(request)) {
			WorkbenchHtmlShell.writeInitialPageModel(request, response, config, viewId, pageData.toByteArray());
			return;
		}
		WorkbenchPageProtocol.configureDynamicPageResponse(response);
		response.setCharacterEncoding(StandardCharsets.UTF_8.name());
		response.setContentType(WorkbenchPageProtocol.CONTENT_TYPE);
		pageData.writeTo(response.getOutputStream());
		response.flushBuffer();
	}

	/**
	 * Answers an unknown repository with 404: a page model ending in a {@code repository-not-found} error record for
	 * page-data requests, the HTML shell carrying that model for browser navigations, and plain text otherwise.
	 */
	private void writeRepositoryNotFound(String repoID, HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		String message = "No such repository: " + repoID;
		response.setHeader("Cache-Control", "no-cache, no-store");
		response.setStatus(HttpServletResponse.SC_NOT_FOUND);
		boolean pageData = WorkbenchPageProtocol.requestsPageData(request);
		boolean navigation = WorkbenchPageProtocol.requestsHtmlNavigation(request);
		if (!pageData && !navigation) {
			response.setCharacterEncoding(StandardCharsets.UTF_8.name());
			response.setContentType(TEXT_PLAIN);
			response.getWriter().write(message);
			return;
		}
		ByteArrayOutputStream modelData = new ByteArrayOutputStream();
		String viewId = pageViewId(request);
		try {
			WorkbenchPageResultWriter pageWriter = new WorkbenchPageResultWriter(modelData);
			pageWriter.view(viewId);
			pageWriter.error(HttpServletResponse.SC_NOT_FOUND, "repository-not-found", message);
		} catch (QueryResultHandlerException e) {
			throw new IOException(e);
		}
		if (navigation) {
			WorkbenchHtmlShell.writeInitialPageModel(request, response, config, viewId, modelData.toByteArray());
			response.setStatus(HttpServletResponse.SC_NOT_FOUND);
			return;
		}
		WorkbenchPageProtocol.configureDynamicPageResponse(response);
		response.setCharacterEncoding(StandardCharsets.UTF_8.name());
		response.setContentType(WorkbenchPageProtocol.CONTENT_TYPE);
		modelData.writeTo(response.getOutputStream());
		response.flushBuffer();
	}

	/** Answers a page-data request with a page model ending in an error record, keeping the requested view. */
	private void writePageError(HttpServletRequest request, HttpServletResponse response, int status, String code,
			String message) throws IOException, QueryResultHandlerException {
		ByteArrayOutputStream modelData = new ByteArrayOutputStream();
		WorkbenchPageResultWriter pageWriter = new WorkbenchPageResultWriter(modelData);
		pageWriter.view(pageViewId(request));
		pageWriter.error(status, code, message);
		response.resetBuffer();
		WorkbenchPageProtocol.configureDynamicPageResponse(response);
		response.setStatus(status);
		response.setCharacterEncoding(StandardCharsets.UTF_8.name());
		response.setContentType(WorkbenchPageProtocol.CONTENT_TYPE);
		modelData.writeTo(response.getOutputStream());
		response.flushBuffer();
	}

	private String pageViewId(HttpServletRequest request) {
		Object requestViewId = request.getAttribute(WorkbenchPageProtocol.PAGE_VIEW_ID_ATTRIBUTE);
		if (requestViewId instanceof String viewId && !viewId.isBlank()) {
			return viewId;
		}
		return WorkbenchViewRegistry.viewIdForRoute(getRoutePath(request.getPathInfo())).orElse("server");
	}

	private File asLocalFile(final URL rdf) {
		return new File(URLDecoder.decode(rdf.getFile(), StandardCharsets.UTF_8));
	}

	private void service(final String repoID, final HttpServletRequest req, final HttpServletResponse resp)
			throws RepositoryConfigException, RepositoryException, ServletException, IOException {
		LOGGER.info("Servicing repository: {}", repoID);
		setCredentials(req, resp);
		final DynamicHttpRequest http = new DynamicHttpRequest(req);
		final String path = req.getPathInfo();
		final int idx = path.indexOf(repoID) + repoID.length();
		http.setServletPath(http.getServletPath() + path.substring(0, idx));
		final String pathInfo = path.substring(idx);
		http.setPathInfo(pathInfo.isEmpty() ? null : pathInfo);
		if (repositories.containsKey(repoID)) {
			repositories.get(repoID).service(http, resp);
		} else {
			final Repository repository = manager.getRepository(repoID);
			if (repository == null) {
				final String noId = config.getInitParameter(NO_REPOSITORY);
				if (noId == null || !noId.equals(repoID)) {
					writeRepositoryNotFound(repoID, req, resp);
					return;
				}
			}
			final ProxyRepositoryServlet createdServlet = createProxyRepositoryServlet();
			createdServlet.setRepositoryManager(manager);
			if (repository != null) {
				createdServlet.setRepositoryInfo(manager.getRepositoryInfo(repoID));
				createdServlet.setRepository(repository);
			}
			createdServlet.init(new BasicServletConfig(repoID, config));
			repositories.putIfAbsent(repoID, createdServlet);
			repositories.get(repoID).service(http, resp);
		}
	}

	/**
	 * Set the username and password for all requests to the repository.
	 *
	 * @param req  the servlet request
	 * @param resp the servlet response
	 * @throws MalformedURLException if the repository location is malformed
	 */
	private void setCredentials(final HttpServletRequest req, final HttpServletResponse resp)
			throws MalformedURLException, RepositoryException {
		if (manager instanceof RemoteRepositoryManager) {
			final RemoteRepositoryManager rrm = (RemoteRepositoryManager) manager;
			LOGGER.info("RemoteRepositoryManager URL: {}", rrm.getLocation());
			final CookieHandler cookies = createCookieHandler();
			final String user_password = cookies.getCookieNullIfEmpty(req, resp, WorkbenchGateway.SERVER_USER_PASSWORD);
			if (user_password == null) {
				rrm.setUsernameAndPassword(null, null);
			} else {
				String decoded = ServerCredentials.decode(user_password);
				if (decoded == null) {
					decoded = user_password; // older browsers
				}
				int colon = decoded.indexOf(':');
				final String user = colon >= 0 ? decoded.substring(0, colon) : decoded;
				final String password = colon >= 0 ? decoded.substring(colon + 1) : "";
				LOGGER.info("Setting user '{}' and their password.", user);
				rrm.setUsernameAndPassword(user, password);
			}
			// init() required to push credentials to internal HTTP
			// client.
			rrm.init();
		}
	}

	protected RepositoryManager createRepositoryManager(final String param) throws IOException, RepositoryException {
		RepositoryManager manager;
		if (param.startsWith("file:")) {
			manager = new LocalRepositoryManager(asLocalFile(new URL(param)));
		} else {
			manager = new RemoteRepositoryManager(param);
		}
		manager.init();
		return manager;
	}

	protected ProxyRepositoryServlet createProxyRepositoryServlet() {
		return new ProxyRepositoryServlet();
	}

	protected CookieHandler createCookieHandler() {
		return new CookieHandler(config);
	}
}
