/*******************************************************************************
 * Copyright (c) 2026 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Codex
package org.eclipse.rdf4j.sail.parquet.mapping;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Value;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

final class TermSpec {

	enum TermType {
		IRI,
		LITERAL
	}

	enum ValueSource {
		VALUE,
		COLUMN,
		TEMPLATE
	}

	private final TermType termType;
	private final ValueSource valueSource;
	private final String constantValue;
	private final ColumnRef column;
	private final Template template;
	private final Map<String, String> prefixes;
	private final IRI datatype;
	private final String language;
	private final ColumnRef languageColumn;

	TermSpec(TermType termType, ValueSource valueSource, String constantValue, ColumnRef column,
			Template template, Map<String, String> prefixes, IRI datatype, String language,
			ColumnRef languageColumn) {
		this.termType = termType;
		this.valueSource = valueSource;
		this.constantValue = constantValue;
		this.column = column;
		this.template = template;
		this.prefixes = prefixes;
		this.datatype = datatype;
		this.language = language;
		this.languageColumn = languageColumn;
	}

	void collectColumnsForAlias(String alias, Set<String> columns) {
		if (column != null && alias.equals(column.getAlias())) {
			columns.add(column.getColumn());
		}
		if (languageColumn != null && alias.equals(languageColumn.getAlias())) {
			columns.add(languageColumn.getColumn());
		}
		if (template != null) {
			template.collectColumnsForAlias(alias, columns);
		}
	}

	Value resolve(Map<String, Map<String, Object>> rowsByAlias) {
		String lexicalValue = resolveLexicalValue(rowsByAlias);
		if (lexicalValue == null) {
			return null;
		}

		SimpleValueFactory valueFactory = SimpleValueFactory.getInstance();
		if (termType == TermType.IRI) {
			return valueFactory.createIRI(ParquetStoreMapping.resolveIri(lexicalValue, prefixes, "IRI value"));
		}

		if (datatype != null) {
			return valueFactory.createLiteral(lexicalValue, datatype);
		}

		String resolvedLanguage = language;
		if (resolvedLanguage == null && languageColumn != null) {
			resolvedLanguage = lexical(rowsByAlias, languageColumn);
		}

		if (resolvedLanguage != null && !resolvedLanguage.isBlank()) {
			return valueFactory.createLiteral(lexicalValue, resolvedLanguage);
		}

		return valueFactory.createLiteral(lexicalValue);
	}

	Optional<String> tryExtractSingleTemplateValue(String lexicalValue) {
		if (template == null) {
			return Optional.empty();
		}
		return template.tryExtract(lexicalValue);
	}

	private String resolveLexicalValue(Map<String, Map<String, Object>> rowsByAlias) {
		switch (valueSource) {
		case VALUE:
			return constantValue;
		case COLUMN:
			return lexical(rowsByAlias, column);
		case TEMPLATE:
			return template.expand(rowsByAlias);
		default:
			throw new IllegalStateException("Unsupported value source: " + valueSource);
		}
	}

	static String lexical(Map<String, Map<String, Object>> rowsByAlias, ColumnRef columnRef) {
		Map<String, Object> row = rowsByAlias.get(columnRef.getAlias());
		if (row == null) {
			return null;
		}
		Object value = row.get(columnRef.getColumn());
		if (value == null) {
			return null;
		}
		return Objects.toString(value, null);
	}
}

final class ColumnRef {

	private final String alias;
	private final String column;

	ColumnRef(String alias, String column) {
		this.alias = alias;
		this.column = column;
	}

	String getAlias() {
		return alias;
	}

	String getColumn() {
		return column;
	}
}

final class Template {

	private static final Pattern TEMPLATE_PLACEHOLDER = Pattern.compile("\\{([^{}]+)}");

	private final List<TemplatePart> parts;
	private final ColumnRef singlePlaceholder;
	private final String prefix;
	private final String suffix;

	Template(String template, String context) {
		Matcher matcher = TEMPLATE_PLACEHOLDER.matcher(template);
		List<TemplatePart> mutableParts = new ArrayList<>();
		List<ColumnRef> placeholders = new ArrayList<>();
		int cursor = 0;
		while (matcher.find()) {
			if (matcher.start() > cursor) {
				mutableParts.add(TemplatePart.text(template.substring(cursor, matcher.start())));
			}
			ColumnRef columnRef = ParquetStoreMapping.parseColumnReference(matcher.group(1), context + " placeholder");
			mutableParts.add(TemplatePart.column(columnRef));
			placeholders.add(columnRef);
			cursor = matcher.end();
		}
		if (cursor < template.length()) {
			mutableParts.add(TemplatePart.text(template.substring(cursor)));
		}
		this.parts = List.copyOf(mutableParts);
		if (placeholders.size() == 1) {
			this.singlePlaceholder = placeholders.get(0);
			this.prefix = mutableParts.isEmpty() || mutableParts.get(0).getColumnRef() != null ? ""
					: mutableParts.get(0).getText();
			this.suffix = mutableParts.isEmpty() || mutableParts.get(mutableParts.size() - 1).getColumnRef() != null
					? ""
					: mutableParts.get(mutableParts.size() - 1).getText();
		} else {
			this.singlePlaceholder = null;
			this.prefix = null;
			this.suffix = null;
		}
	}

	void collectColumnsForAlias(String alias, Set<String> columns) {
		for (TemplatePart part : parts) {
			if (part.getColumnRef() != null && alias.equals(part.getColumnRef().getAlias())) {
				columns.add(part.getColumnRef().getColumn());
			}
		}
	}

	String expand(Map<String, Map<String, Object>> rowsByAlias) {
		StringBuilder builder = new StringBuilder();
		for (TemplatePart part : parts) {
			if (part.getColumnRef() == null) {
				builder.append(part.getText());
			} else {
				String lexicalValue = TermSpec.lexical(rowsByAlias, part.getColumnRef());
				if (lexicalValue == null) {
					return null;
				}
				builder.append(lexicalValue);
			}
		}
		return builder.toString();
	}

	Optional<String> tryExtract(String value) {
		if (singlePlaceholder == null) {
			return Optional.empty();
		}
		if (!value.startsWith(prefix) || !value.endsWith(suffix)
				|| value.length() < prefix.length() + suffix.length()) {
			return Optional.empty();
		}
		return Optional.of(value.substring(prefix.length(), value.length() - suffix.length()));
	}
}

final class TemplatePart {

	private final String text;
	private final ColumnRef columnRef;

	private TemplatePart(String text, ColumnRef columnRef) {
		this.text = text;
		this.columnRef = columnRef;
	}

	static TemplatePart text(String value) {
		return new TemplatePart(value, null);
	}

	static TemplatePart column(ColumnRef value) {
		return new TemplatePart(null, value);
	}

	String getText() {
		return text;
	}

	ColumnRef getColumnRef() {
		return columnRef;
	}
}
