PREFIX ex: <http://example.com/ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
ex:validPerson1 a ex:Person .


ex:validPerson5 a ex:Person .


ex:validPerson3 a ex:Person .


ex:validPerson4 a ex:Person .

ex:validPerson2 a ex:Person .


ex:pete ex:inverseKnows ex:validPerson1 .
ex:fluffy ex:inverseKnows ex:validPerson1 .

ex:a ex:inverseKnows ex:validPerson5 .
ex:b ex:inverseKnows ex:validPerson3 .

ex:c ex:inverseKnows ex:validPerson4 .

ex:d ex:inverseKnows ex:validPerson2 .




ex:pete a ex:Person.
ex:fluffy a ex:Animal.

ex:a a ex:Person.
ex:b a ex:Animal.
ex:c a ex:Person.
ex:d a ex:Animal.
}
