name: cancel-previous-builds.yml
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://docs.github.com/en/actions/learn-github-actions/expressions
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/github.ref_protected' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
