name: PR unit test (JDK 8)

on: pull_request

strategy:
  matrix:
    jdk: [1.8, 11]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Verify formatting
      run: mvn -B formatter:validate
    - name: Build
      run: mvn -B clean install -DskipTests
    - name: Run tests
      run: mvn -B verify --file pom.xml
