name: PR unit test (JDK 8)

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify formatting
      run: mvn formatter:validate
    - name: Build
      run: mvn clean install -DskipTests
    - name: Run tests
      run: mvn -B verify --file pom.xml
